package app.masroufy.android

import app.masroufy.firestore.FirestoreContainer
import app.masroufy.usecase.AssistantStores
import app.masroufy.wiring.SpaceRepositories

/** مستودعات فايربيز لبلد (`FirestoreContainer` — بذاكرتها `LocalMirror`) ⇒ واجهات بس للتجميع. سطر بسطر بنفس الأسماء. */
fun FirestoreContainer.toRepositories() = SpaceRepositories(
    uow = uow,
    transactions = transactions,
    sourceRecords = sourceRecords,
    importBatches = importBatches,
    wallets = wallets,
    categories = categories,
    rules = rules,
    merchants = merchants,
    merchantCategories = merchantCategories,
    people = people,
    obligations = obligations,
    settlements = settlements,
    settlementWriter = settlementWriter,
    allocations = allocations,
    tags = tags,
    transactionTags = transactionTags,
    budgets = budgets,
    recurring = recurring,
    notificationReceipts = notificationReceipts,
    assets = assets,
    assetLots = assetLots,
    assetSales = assetSales,
    assetPrices = assetPrices,
    projects = projects,
    projectRules = projectRules,
    projectLinks = projectLinks,
    roscas = roscas,
    roscaEntries = roscaEntries,
    installmentPlans = installmentPlans,
    installmentPayments = installmentPayments,
    debtTerms = debtTerms,
    transferParties = transferParties,
    zakatFacts = zakatFacts,
    zakatYears = zakatYears,
    zakatPayments = zakatPayments,
    lifeEvents = lifeEvents,
    eventLinks = eventLinks,
    occasions = occasions,
    personProfiles = personProfiles,
    personRelations = personRelations,
    alertSettings = alertSettings,
    alertInbox = alertInbox,
    alertReceipts = alertReceipts,
    savingsGoals = savingsGoals,
    goalContributions = goalContributions,
    inheritanceScenarios = inheritanceScenarios,
    incomeSources = incomeSources,
    reservations = reservations,
    eventPrep = eventPrep,
    profile = profile,
    spaces = spaces,
    spaceTransfers = spaceTransfers,
    assistant = AssistantStores(
        conversations = assistantConversations, messages = assistantMessages, topics = assistantTopics, forgotten = assistantForgotten,
        unknown = assistantUnknown, settings = userSettings, alertDismissals = alertDismissals,
    ),
    fullBackup = fullBackup,
    spacesBackup = spacesBackup,
)
