import type { LucideIcon } from 'lucide-react'
import {
  ArrowLeftRight,
  Baby,
  BadgeDollarSign,
  Banknote,
  Bath,
  Blocks,
  BookOpen,
  BriefcaseBusiness,
  Brush,
  BuildingComplex,
  BusFront,
  CalendarClock,
  Car,
  CarTaxiFront,
  Carrot,
  ChefHat,
  Cloud,
  Coffee,
  Coins,
  CreditCard,
  Croissant,
  CupSoda,
  Droplets,
  Dumbbell,
  Ellipsis,
  FaceSlightlySmiling,
  FileText,
  Fish,
  Flame,
  Footprints,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Glasses,
  GraduationCap,
  Hammer,
  HandCoins,
  HandHeart,
  HeartHandshake,
  HeartPulse,
  Hotel,
  House,
  HouseHeart,
  IdCard,
  KeyRound,
  Landmark,
  Laptop,
  Library,
  MapPin,
  Megaphone,
  Milk,
  Monitor,
  Music,
  Package,
  PartyPopper,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  PlaneTakeoff,
  Popcorn,
  Repeat,
  Route,
  Router,
  School,
  Scissors,
  Send,
  ShieldCheck,
  ShieldPlus,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Siren,
  Soup,
  Sparkles,
  SprayCan,
  SquareParking,
  Stamp,
  Stethoscope,
  Store,
  Tag,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  UserRound,
  Users,
  Utensils,
  Wallet,
  WalletCards,
  WandSparkles,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react'

/**
 * رموز التصنيفات والمجموعات — OVERRIDES §28 وARCHITECTURE §28.
 * استيراد بالاسم بس، فالتطبيق بيضم الرموز دي وحدها. مفتاح مش معروف ⇒ رمز عام (spec/04: لا مساحة مكسورة).
 */
export const CATEGORY_ICONS: Readonly<Record<string, LucideIcon>> = {
  'arrow-left-right': ArrowLeftRight,
  'baby': Baby,
  'badge-dollar-sign': BadgeDollarSign,
  'banknote': Banknote,
  'bath': Bath,
  'blocks': Blocks,
  'book-open': BookOpen,
  'briefcase-business': BriefcaseBusiness,
  'brush': Brush,
  'building-complex': BuildingComplex,
  'bus-front': BusFront,
  'calendar-clock': CalendarClock,
  'car': Car,
  'car-taxi-front': CarTaxiFront,
  'carrot': Carrot,
  'chef-hat': ChefHat,
  'cloud': Cloud,
  'coffee': Coffee,
  'coins': Coins,
  'credit-card': CreditCard,
  'croissant': Croissant,
  'cup-soda': CupSoda,
  'droplets': Droplets,
  'dumbbell': Dumbbell,
  'ellipsis': Ellipsis,
  'face-slightly-smiling': FaceSlightlySmiling,
  'file-text': FileText,
  'fish': Fish,
  'flame': Flame,
  'footprints': Footprints,
  'fuel': Fuel,
  'gamepad-2': Gamepad2,
  'gavel': Gavel,
  'gem': Gem,
  'glasses': Glasses,
  'graduation-cap': GraduationCap,
  'hammer': Hammer,
  'hand-coins': HandCoins,
  'hand-heart': HandHeart,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  'hotel': Hotel,
  'house': House,
  'house-heart': HouseHeart,
  'id-card': IdCard,
  'key-round': KeyRound,
  'landmark': Landmark,
  'laptop': Laptop,
  'library': Library,
  'map-pin': MapPin,
  'megaphone': Megaphone,
  'milk': Milk,
  'monitor': Monitor,
  'music': Music,
  'package': Package,
  'party-popper': PartyPopper,
  'phone': Phone,
  'piggy-bank': PiggyBank,
  'pill': Pill,
  'plane': Plane,
  'plane-takeoff': PlaneTakeoff,
  'popcorn': Popcorn,
  'repeat': Repeat,
  'route': Route,
  'router': Router,
  'school': School,
  'scissors': Scissors,
  'send': Send,
  'shield-check': ShieldCheck,
  'shield-plus': ShieldPlus,
  'shirt': Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  'siren': Siren,
  'soup': Soup,
  'sparkles': Sparkles,
  'spray-can': SprayCan,
  'square-parking': SquareParking,
  'stamp': Stamp,
  'stethoscope': Stethoscope,
  'store': Store,
  'tag': Tag,
  'ticket': Ticket,
  'train-front': TrainFront,
  'trending-up': TrendingUp,
  'tv': Tv,
  'user-round': UserRound,
  'users': Users,
  'utensils': Utensils,
  'wallet': Wallet,
  'wallet-cards': WalletCards,
  'wand-sparkles': WandSparkles,
  'wifi': Wifi,
  'wrench': Wrench,
  'zap': Zap,
}

export function CategoryIcon({ iconKey, size = 20 }: { iconKey: string; size?: number }) {
  const Icon = CATEGORY_ICONS[iconKey] ?? Tag
  return <Icon size={size} strokeWidth={2} aria-hidden="true" focusable="false" />
}
