package app.masroufy.core

/** أسماء المجموعات للعرض — بتتقرا وقت العرض عشان تتغير مع اللغة (Texts.kt). */
val BACKUP_LABELS: Map<String, String>
    get() = mapOf(
        "wallets" to uiText(TextKey.BACKUP_GROUP_WALLETS),
        "categories" to uiText(TextKey.BACKUP_GROUP_CATEGORIES),
        "merchants" to uiText(TextKey.BACKUP_GROUP_MERCHANTS),
        "rules" to uiText(TextKey.BACKUP_GROUP_RULES),
        "people" to uiText(TextKey.BACKUP_GROUP_PEOPLE),
        "assets" to uiText(TextKey.BACKUP_GROUP_ASSETS),
        "tags" to uiText(TextKey.BACKUP_GROUP_TAGS),
        "budgets" to uiText(TextKey.BACKUP_GROUP_BUDGETS),
        "recurringItems" to uiText(TextKey.BACKUP_GROUP_RECURRING_ITEMS),
        "importBatches" to uiText(TextKey.BACKUP_GROUP_IMPORT_BATCHES),
        "transactions" to uiText(TextKey.BACKUP_GROUP_TRANSACTIONS),
        "obligations" to uiText(TextKey.BACKUP_GROUP_OBLIGATIONS),
        "allocations" to uiText(TextKey.BACKUP_GROUP_ALLOCATIONS),
        "settlements" to uiText(TextKey.BACKUP_GROUP_SETTLEMENTS),
        "sourceRecords" to uiText(TextKey.BACKUP_GROUP_SOURCE_RECORDS),
        "transactionTags" to uiText(TextKey.BACKUP_GROUP_TRANSACTION_TAGS),
        "categoryBudgets" to uiText(TextKey.BACKUP_GROUP_CATEGORY_BUDGETS),
        "assetLots" to uiText(TextKey.BACKUP_GROUP_ASSET_LOTS),
        "assetSales" to uiText(TextKey.BACKUP_GROUP_ASSET_SALES),
        "assetPrices" to uiText(TextKey.BACKUP_GROUP_ASSET_PRICES),
        "notificationReceipts" to uiText(TextKey.BACKUP_GROUP_NOTIFICATION_RECEIPTS),
        "projects" to uiText(TextKey.BACKUP_GROUP_PROJECTS),
        "projectLinks" to uiText(TextKey.BACKUP_GROUP_PROJECT_LINKS),
        "projectRules" to uiText(TextKey.BACKUP_GROUP_PROJECT_RULES),
        "roscas" to uiText(TextKey.BACKUP_GROUP_ROSCAS),
        "roscaEntries" to uiText(TextKey.BACKUP_GROUP_ROSCA_ENTRIES),
        "installmentPlans" to uiText(TextKey.BACKUP_GROUP_INSTALLMENT_PLANS),
        "installmentPayments" to uiText(TextKey.BACKUP_GROUP_INSTALLMENT_PAYMENTS),
        "debtTerms" to uiText(TextKey.BACKUP_GROUP_DEBT_TERMS),
        "transferParties" to uiText(TextKey.BACKUP_GROUP_TRANSFER_PARTIES),
        "zakatFacts" to uiText(TextKey.BACKUP_GROUP_ZAKAT_FACTS),
        "zakatYears" to uiText(TextKey.BACKUP_GROUP_ZAKAT_YEARS),
        "zakatPayments" to uiText(TextKey.BACKUP_GROUP_ZAKAT_PAYMENTS),
        "lifeEvents" to uiText(TextKey.BACKUP_GROUP_LIFE_EVENTS),
        "eventLinks" to uiText(TextKey.BACKUP_GROUP_EVENT_LINKS),
        "occasions" to uiText(TextKey.BACKUP_GROUP_OCCASIONS),
        "incomeSources" to uiText(TextKey.BACKUP_GROUP_INCOME_SOURCES),
        MERCHANT_CATEGORIES_GROUP to uiText(TextKey.BACKUP_GROUP_MERCHANT_CATEGORIES),
        "reservations" to uiText(TextKey.BACKUP_GROUP_RESERVATIONS),
        "eventPrep" to uiText(TextKey.BACKUP_GROUP_EVENT_PREP),
        PERSON_PROFILES_GROUP to uiText(TextKey.BACKUP_GROUP_PERSON_PROFILES),
        PERSON_RELATIONS_GROUP to uiText(TextKey.BACKUP_GROUP_PERSON_RELATIONS),
        ALERT_SETTINGS_GROUP to uiText(TextKey.BACKUP_GROUP_ALERT_SETTINGS),
    )
