package app.masroufy.core

/**
 * نصوص «المستحقات» (الجمعيات والأقساط ومواعيد الديون — OVERRIDES §50) باللغتين.
 * ملف لوحده عشان حد الـ300 سطر؛ بيتدمج في `ARABIC_TEXTS` و`ENGLISH_TEXTS` في `Texts.kt`.
 * الإنجليزي كتابة Claude ومستني مراجعة المالك زي باقي الجدول (§40).
 */
internal val ARABIC_DUES_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.KIND_ROSCA_CONTRIBUTION to "قسط جمعية",
    TextKey.KIND_INSTALLMENT_PAID to "قسط تمويل",
    TextKey.DUE_BAD_FIRST_DATE to "تاريخ أول قسط مش صحيح.",
    TextKey.DUE_BAD_CYCLE to "القسط لازم يكون كل شهر لحد كل {0} شهر.",
    TextKey.DUE_INSTALLMENT_POSITIVE to "القسط لازم يكون أكبر من صفر.",
    TextKey.DUE_TOTAL_POSITIVE to "الإجمالي لازم يكون أكبر من صفر.",
    TextKey.DUE_TOO_MANY to "عدد الأقساط أكتر من {0} — راجع القسط والإجمالي.",
    TextKey.DUE_PAID_NEGATIVE to "المدفوع مينفعش يكون بالسالب.",
    TextKey.DUE_OVERPAID to "المدفوع ({0}) أكبر من الإجمالي ({1}).",
    TextKey.DUE_AMOUNT_POSITIVE to "المبلغ لازم يكون أكبر من صفر.",
    TextKey.ROSCA_NAME_LENGTH to "اسم الجمعية لازم يكون من حرف لـ {0} حرف.",
    TextKey.ROSCA_CYCLE_COUNT to "عدد الأدوار لازم يكون من 2 لـ {0}.",
    TextKey.ROSCA_TURNS to "اختار دورك: رقم من 1 لـ {0}، ومن غير تكرار.",
    TextKey.ROSCA_PAYOUT_POSITIVE to "قيمة الدور لازم تكون أكبر من صفر.",
    TextKey.ROSCA_PAYOUT_UNEVEN to "قيمة الدور مش بتتقسم بالظبط على أدوارك — اكتبها بنفسك.",
    TextKey.ROSCA_MEMBER_TURN to "دور «{0}» لازم يكون من 1 لـ {1}.",
    TextKey.ROSCA_CONTRIBUTION_OVER to "المبلغ ده أكبر من اللي فاضل عليك في الجمعية ({0}). الزيادة {1}.",
    TextKey.ROSCA_PAYOUT_OVER to "المبلغ ده أكبر من اللي فاضل لك تقبضه ({0}). الزيادة {1}.",
    TextKey.ROSCA_NOT_FOUND to "الجمعية مش موجودة.",
    TextKey.INSTALLMENT_NAME_LENGTH to "الاسم لازم يكون من حرف لـ {0} حرف.",
    TextKey.INSTALLMENT_TOTAL_BELOW_PRINCIPAL to "إجمالي اللي هتدفعه مينفعش يكون أقل من المبلغ الأصلي.",
    TextKey.INSTALLMENT_OVER to "المبلغ ده أكبر من اللي فاضل في الأقساط ({0}). الزيادة {1}.",
    TextKey.INSTALLMENT_NOT_FOUND to "خطة الأقساط مش موجودة.",
    TextKey.DEBT_NOT_FOUND to "الدين مش موجود.",
    TextKey.DUE_TXN_NOT_FOUND to "العملية مش موجودة.",
    TextKey.DUE_TXN_NEEDS_OUT to "القسط لازم يكون فلوس طالعة من حسابك.",
    TextKey.DUE_TXN_NEEDS_IN to "قبض الدور لازم يكون فلوس داخلة لحسابك.",
    TextKey.DUE_TXN_CURRENCY to "عملة العملية غير عملة {0}.",
    TextKey.DUE_TXN_ALREADY_LINKED to "العملية دي مربوطة قبل كده.",
    TextKey.DUE_AMOUNT_OVER_TXN to "المبلغ أكبر من مبلغ العملية نفسها ({0}).",
    TextKey.DUE_LOCKED_AFTER_LINK to "مينفعش تغيّر العملة أو النوع بعد ما عمليات اتربطت — فك الربط الأول.",
)

internal val ENGLISH_DUES_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.KIND_ROSCA_CONTRIBUTION to "Savings circle contribution",
    TextKey.KIND_INSTALLMENT_PAID to "Financing installment",
    TextKey.DUE_BAD_FIRST_DATE to "The first due date is not valid.",
    TextKey.DUE_BAD_CYCLE to "Installments can be monthly up to every {0} months.",
    TextKey.DUE_INSTALLMENT_POSITIVE to "The installment has to be greater than zero.",
    TextKey.DUE_TOTAL_POSITIVE to "The total has to be greater than zero.",
    TextKey.DUE_TOO_MANY to "More than {0} installments — check the installment and the total.",
    TextKey.DUE_PAID_NEGATIVE to "The paid amount cannot be negative.",
    TextKey.DUE_OVERPAID to "The paid amount ({0}) is more than the total ({1}).",
    TextKey.DUE_AMOUNT_POSITIVE to "The amount has to be greater than zero.",
    TextKey.ROSCA_NAME_LENGTH to "The circle name has to be 1 to {0} characters.",
    TextKey.ROSCA_CYCLE_COUNT to "The number of turns has to be 2 to {0}.",
    TextKey.ROSCA_TURNS to "Pick your turn: a number from 1 to {0}, with no repeats.",
    TextKey.ROSCA_PAYOUT_POSITIVE to "The payout has to be greater than zero.",
    TextKey.ROSCA_PAYOUT_UNEVEN to "The payout does not divide evenly over your turns — enter it yourself.",
    TextKey.ROSCA_MEMBER_TURN to "The turn of \"{0}\" has to be 1 to {1}.",
    TextKey.ROSCA_CONTRIBUTION_OVER to "This is more than what is left for you to pay in the circle ({0}). Extra: {1}.",
    TextKey.ROSCA_PAYOUT_OVER to "This is more than what is left for you to receive ({0}). Extra: {1}.",
    TextKey.ROSCA_NOT_FOUND to "The circle does not exist.",
    TextKey.INSTALLMENT_NAME_LENGTH to "The name has to be 1 to {0} characters.",
    TextKey.INSTALLMENT_TOTAL_BELOW_PRINCIPAL to "The total you pay cannot be less than the original amount.",
    TextKey.INSTALLMENT_OVER to "This is more than what is left in the installments ({0}). Extra: {1}.",
    TextKey.INSTALLMENT_NOT_FOUND to "The installment plan does not exist.",
    TextKey.DEBT_NOT_FOUND to "The debt does not exist.",
    TextKey.DUE_TXN_NOT_FOUND to "The transaction does not exist.",
    TextKey.DUE_TXN_NEEDS_OUT to "An installment has to be money leaving your account.",
    TextKey.DUE_TXN_NEEDS_IN to "A payout has to be money coming into your account.",
    TextKey.DUE_TXN_CURRENCY to "The transaction currency is not the currency of {0}.",
    TextKey.DUE_TXN_ALREADY_LINKED to "This transaction is already linked.",
    TextKey.DUE_AMOUNT_OVER_TXN to "The amount is more than the transaction itself ({0}).",
    TextKey.DUE_LOCKED_AFTER_LINK to "The currency or type cannot change after transactions are linked — unlink them first.",
)
