package app.masroufy.core

/**
 * نصوص «المستحقات» (الجمعيات والأقساط ومواعيد الديون — OVERRIDES §50) باللغتين.
 * ملف لوحده عشان حد الـ300 سطر؛ بيتدمج في `ARABIC_TEXTS` و`ENGLISH_TEXTS` في `Texts.kt`.
 * الإنجليزي كتابة Claude ومستني مراجعة المالك زي باقي الجدول (§40).
 */
internal val ARABIC_DUES_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.KIND_ROSCA_CONTRIBUTION to "قسط جمعية",
    TextKey.KIND_INSTALLMENT_PAID to "قسط تمويل",
    TextKey.KIND_FINANCING_RECEIVED to "مبلغ تمويل مستلم",
    TextKey.DUE_BAD_FIRST_DATE to "تاريخ أول قسط مش صحيح.",
    TextKey.DUE_BAD_CYCLE to "القسط لازم يكون كل شهر لحد كل {0} شهر.",
    TextKey.DUE_INSTALLMENT_POSITIVE to "القسط لازم يكون أكبر من صفر.",
    TextKey.DUE_TOTAL_POSITIVE to "الإجمالي لازم يكون أكبر من صفر.",
    TextKey.DUE_TOO_MANY to "عدد الأقساط أكتر من {0} — راجع القسط والإجمالي.",
    TextKey.DUE_PAID_NEGATIVE to "المدفوع مينفعش يكون بالسالب.",
    TextKey.DUE_OVERPAID to "المدفوع ({0}) أكبر من الإجمالي ({1}).",
    TextKey.DUE_AMOUNT_POSITIVE to "المبلغ لازم يكون أكبر من صفر.",
    TextKey.ROSCA_NAME_LENGTH to "اسم الجمعية لازم يكون من حرف لـ {0} حرف.",
    TextKey.ROSCA_CYCLE_COUNT to "عدد الأدوار لازم يكون من 2 لـ {0}.",
    TextKey.ROSCA_TURNS to "اختار دورك: رقم من 1 لـ {0}، ومن غير تكرار.",
    TextKey.ROSCA_PAYOUT_POSITIVE to "قيمة الدور لازم تكون أكبر من صفر.",
    TextKey.ROSCA_PAYOUT_UNEVEN to "قيمة الدور مش بتتقسم بالظبط على أدوارك — اكتبها بنفسك.",
    TextKey.ROSCA_MEMBER_TURN to "دور «{0}» لازم يكون من 1 لـ {1}.",
    TextKey.ROSCA_CONTRIBUTION_OVER to "المبلغ ده أكبر من اللي فاضل عليك في الجمعية ({0}). الزيادة {1}.",
    TextKey.ROSCA_PAYOUT_OVER to "المبلغ ده أكبر من اللي فاضل لك تقبضه ({0}). الزيادة {1}.",
    TextKey.ROSCA_NOT_FOUND to "الجمعية مش موجودة.",
    TextKey.INSTALLMENT_NAME_LENGTH to "الاسم لازم يكون من حرف لـ {0} حرف.",
    TextKey.INSTALLMENT_TOTAL_BELOW_PRINCIPAL to "إجمالي اللي هتدفعه مينفعش يكون أقل من المبلغ الأصلي.",
    TextKey.INSTALLMENT_OVER to "المبلغ ده أكبر من اللي فاضل في الأقساط ({0}). الزيادة {1}.",
    TextKey.INSTALLMENT_NOT_FOUND to "خطة الأقساط مش موجودة.",
    TextKey.INSTALLMENT_RECEIVED_NEEDS_FINANCING to "المبلغ المستلم بيتربط بخطة تمويل بس — تقسيط المشتريات مافيهوش فلوس بتستلمها.",
    TextKey.INSTALLMENT_ALREADY_RECEIVED to "الخطة دي مربوط بيها مبلغ مستلم قبل كده — فك الربط الأول.",
    TextKey.DUE_RECEIVED_NEEDS_IN to "مبلغ التمويل المستلم لازم يكون فلوس داخلة لحسابك.",
    TextKey.DEBT_NOT_FOUND to "الدين مش موجود.",
    TextKey.DUE_TXN_NOT_FOUND to "العملية مش موجودة.",
    TextKey.DUE_TXN_NEEDS_OUT to "القسط لازم يكون فلوس طالعة من حسابك.",
    TextKey.DUE_TXN_NEEDS_IN to "قبض الدور لازم يكون فلوس داخلة لحسابك.",
    TextKey.DUE_TXN_CURRENCY to "عملة العملية غير عملة {0}.",
    TextKey.DUE_TXN_ALREADY_LINKED to "العملية دي مربوطة قبل كده.",
    TextKey.DUE_AMOUNT_OVER_TXN to "المبلغ أكبر من مبلغ العملية نفسها ({0}).",
    TextKey.DUE_LOCKED_AFTER_LINK to "مينفعش تغيّر العملة أو النوع بعد ما عمليات اتربطت — فك الربط الأول.",
    TextKey.DUE_BAD_CYCLE_WEEKS to "القسط لازم يكون كل أسبوع لحد كل {0} أسابيع.",
    TextKey.ROSCA_Q_NAME to "اسم الجمعية إيه؟",
    TextKey.ROSCA_Q_NAME_HINT to "مثلًا: جمعية الشغل",
    TextKey.ROSCA_Q_TURNS_COUNT to "الجمعية كام دور؟",
    TextKey.ROSCA_Q_TURNS_COUNT_HINT to "غالبًا نفس عدد الأعضاء",
    TextKey.ROSCA_Q_SHARE_AMOUNT to "القسط كام كل مرة؟",
    TextKey.ROSCA_Q_SHARE_AMOUNT_HINT to "قسط السهم الكامل — اللي بيتقال «الجمعية بكام»",
    TextKey.ROSCA_Q_FREQUENCY to "بتدفعوا كل قد إيه؟",
    TextKey.ROSCA_Q_FIRST_DATE to "أول دفعة كانت أو هتكون إمتى؟",
    TextKey.ROSCA_Q_SHARE to "إنت داخل بكام سهم؟",
    TextKey.ROSCA_Q_MY_TURN to "دورك رقم كام؟",
    TextKey.ROSCA_Q_PAYOUT to "هتقبض كام في دورك؟",
    TextKey.ROSCA_Q_PAYOUT_HINT to "المحسوب: {0}",
    TextKey.ROSCA_FREQ_WEEKLY to "كل أسبوع",
    TextKey.ROSCA_FREQ_BIWEEKLY to "كل أسبوعين",
    TextKey.ROSCA_FREQ_MONTHLY to "كل شهر",
    TextKey.ROSCA_FREQ_BIMONTHLY to "كل شهرين",
    TextKey.ROSCA_FREQ_QUARTERLY to "كل 3 شهور",
    TextKey.ROSCA_SHARE_HALF to "نص سهم",
    TextKey.ROSCA_SHARE_ONE to "سهم واحد",
    TextKey.ROSCA_SHARE_TWO to "سهمين",
    TextKey.ROSCA_TURN_UNKNOWN_CHOICE to "لسه ما اتعرفش",
    TextKey.ROSCA_TURN_UNKNOWN to "حدد دورك الأول.",
    TextKey.ROSCA_HALF_UNEVEN to "نص القسط لازم يطلع بالهللة — راجع المبلغ.",
    TextKey.ROSCA_TURNS_FOR_SHARE to "اختار {0} دور.",
    TextKey.ROSCA_DRAFT_INCOMPLETE to "لسه فيه أسئلة ما اتجاوبتش.",
)

internal val ENGLISH_DUES_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.KIND_ROSCA_CONTRIBUTION to "Savings circle contribution",
    TextKey.KIND_INSTALLMENT_PAID to "Financing installment",
    TextKey.KIND_FINANCING_RECEIVED to "Financing received",
    TextKey.DUE_BAD_FIRST_DATE to "The first due date is not valid.",
    TextKey.DUE_BAD_CYCLE to "Installments can be monthly up to every {0} months.",
    TextKey.DUE_INSTALLMENT_POSITIVE to "The installment has to be greater than zero.",
    TextKey.DUE_TOTAL_POSITIVE to "The total has to be greater than zero.",
    TextKey.DUE_TOO_MANY to "More than {0} installments — check the installment and the total.",
    TextKey.DUE_PAID_NEGATIVE to "The paid amount cannot be negative.",
    TextKey.DUE_OVERPAID to "The paid amount ({0}) is more than the total ({1}).",
    TextKey.DUE_AMOUNT_POSITIVE to "The amount has to be greater than zero.",
    TextKey.ROSCA_NAME_LENGTH to "The circle name has to be 1 to {0} characters.",
    TextKey.ROSCA_CYCLE_COUNT to "The number of turns has to be 2 to {0}.",
    TextKey.ROSCA_TURNS to "Pick your turn: a number from 1 to {0}, with no repeats.",
    TextKey.ROSCA_PAYOUT_POSITIVE to "The payout has to be greater than zero.",
    TextKey.ROSCA_PAYOUT_UNEVEN to "The payout does not divide evenly over your turns — enter it yourself.",
    TextKey.ROSCA_MEMBER_TURN to "The turn of \"{0}\" has to be 1 to {1}.",
    TextKey.ROSCA_CONTRIBUTION_OVER to "This is more than what is left for you to pay in the circle ({0}). Extra: {1}.",
    TextKey.ROSCA_PAYOUT_OVER to "This is more than what is left for you to receive ({0}). Extra: {1}.",
    TextKey.ROSCA_NOT_FOUND to "The circle does not exist.",
    TextKey.INSTALLMENT_NAME_LENGTH to "The name has to be 1 to {0} characters.",
    TextKey.INSTALLMENT_TOTAL_BELOW_PRINCIPAL to "The total you pay cannot be less than the original amount.",
    TextKey.INSTALLMENT_OVER to "This is more than what is left in the installments ({0}). Extra: {1}.",
    TextKey.INSTALLMENT_NOT_FOUND to "The installment plan does not exist.",
    TextKey.INSTALLMENT_RECEIVED_NEEDS_FINANCING to "Only a financing plan can have received money — a purchase plan has nothing to receive.",
    TextKey.INSTALLMENT_ALREADY_RECEIVED to "This plan already has received money linked — unlink it first.",
    TextKey.DUE_RECEIVED_NEEDS_IN to "Received financing has to be money coming into your account.",
    TextKey.DEBT_NOT_FOUND to "The debt does not exist.",
    TextKey.DUE_TXN_NOT_FOUND to "The transaction does not exist.",
    TextKey.DUE_TXN_NEEDS_OUT to "An installment has to be money leaving your account.",
    TextKey.DUE_TXN_NEEDS_IN to "A payout has to be money coming into your account.",
    TextKey.DUE_TXN_CURRENCY to "The transaction currency is not the currency of {0}.",
    TextKey.DUE_TXN_ALREADY_LINKED to "This transaction is already linked.",
    TextKey.DUE_AMOUNT_OVER_TXN to "The amount is more than the transaction itself ({0}).",
    TextKey.DUE_LOCKED_AFTER_LINK to "The currency or type cannot change after transactions are linked — unlink them first.",
    TextKey.DUE_BAD_CYCLE_WEEKS to "Installments can be weekly up to every {0} weeks.",
    TextKey.ROSCA_Q_NAME to "What is the circle called?",
    TextKey.ROSCA_Q_NAME_HINT to "For example: the work circle",
    TextKey.ROSCA_Q_TURNS_COUNT to "How many turns does the circle have?",
    TextKey.ROSCA_Q_TURNS_COUNT_HINT to "Usually the same as the number of members",
    TextKey.ROSCA_Q_SHARE_AMOUNT to "How much is each payment?",
    TextKey.ROSCA_Q_SHARE_AMOUNT_HINT to "The payment for one full share",
    TextKey.ROSCA_Q_FREQUENCY to "How often do you pay?",
    TextKey.ROSCA_Q_FIRST_DATE to "When was or will be the first payment?",
    TextKey.ROSCA_Q_SHARE to "How many shares do you hold?",
    TextKey.ROSCA_Q_MY_TURN to "Which turn is yours?",
    TextKey.ROSCA_Q_PAYOUT to "How much will you receive on your turn?",
    TextKey.ROSCA_Q_PAYOUT_HINT to "Calculated: {0}",
    TextKey.ROSCA_FREQ_WEEKLY to "Every week",
    TextKey.ROSCA_FREQ_BIWEEKLY to "Every two weeks",
    TextKey.ROSCA_FREQ_MONTHLY to "Every month",
    TextKey.ROSCA_FREQ_BIMONTHLY to "Every two months",
    TextKey.ROSCA_FREQ_QUARTERLY to "Every 3 months",
    TextKey.ROSCA_SHARE_HALF to "Half a share",
    TextKey.ROSCA_SHARE_ONE to "One share",
    TextKey.ROSCA_SHARE_TWO to "Two shares",
    TextKey.ROSCA_TURN_UNKNOWN_CHOICE to "Not known yet",
    TextKey.ROSCA_TURN_UNKNOWN to "Set your turn first.",
    TextKey.ROSCA_HALF_UNEVEN to "Half the payment has to come out in whole halalas — check the amount.",
    TextKey.ROSCA_TURNS_FOR_SHARE to "Pick {0} turns.",
    TextKey.ROSCA_DRAFT_INCOMPLETE to "Some questions are still unanswered.",
)
