package app.masroufy.core

/**
 * نصوص لوحة «أصل جديد · شراء · بيع · سعر يدوي» (`AssetTradeSheet`) و«الصورة كاملة» (`AssetProjection`) — جزء من نصوص منطقة الاستثمار.
 * جملة «إن ربطته بعمليته تصبح شراء أصل» اتشالت: الربط في كوتلن بيحفظ رقم العملية بس ومش بيغيّر نوعها (HANDOVER — ناقص في المنطق).
 */
internal val MSA_INVEST_TRADE_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ASSET_TRADE_ADD_TITLE to "أصل جديد",
    UiKey.ASSET_TRADE_BUY_TITLE to "شراء {0}",
    UiKey.ASSET_TRADE_SELL_TITLE to "بيع {0}",
    UiKey.ASSET_TRADE_PRICE_TITLE to "سعر يدوي — {0}",
    UiKey.ASSET_TRADE_SUB to "تملك {0}، التكلفة {1} — تسجيل فقط، لا تداول",
    UiKey.ASSET_TRADE_WHEN to "متى؟",
    UiKey.ASSET_TRADE_TODAY to "اليوم",
    UiKey.ASSET_TRADE_YESTERDAY to "أمس",
    UiKey.ASSET_TRADE_QTY to "الكمية",
    UiKey.ASSET_TRADE_PAID to "المبلغ المدفوع",
    UiKey.ASSET_TRADE_PROCEEDS to "مبلغ البيع",
    UiKey.ASSET_TRADE_FEES to "الرسوم (اختياري)",
    UiKey.ASSET_TRADE_LINK_BUY to "اربطه بعملية الدفع (اختياري)",
    UiKey.ASSET_TRADE_LINK_SELL to "اربطه بالمبلغ الوارد (اختياري)",
    UiKey.ASSET_TRADE_NO_LINK to "بلا ربط",
    UiKey.ASSET_TRADE_PRICE_LABEL to "سعر ال{0} اليوم",
    UiKey.ASSET_TRADE_NOTE_BUY to "يدخل المبلغ في التكلفة ومعه الرسوم.",
    UiKey.ASSET_TRADE_NOTE_SELL to "مبلغ البيع ليس دخلًا — يظهر المكسب وحده.",
    UiKey.ASSET_TRADE_NOTE_PRICE to "سعر يدوي بتاريخ اليوم. إن كان الأصل مربوطًا بالسعر اليومي فسيكتب التحديث القادم فوقه.",
    UiKey.ASSET_TRADE_SAVE_ADD to "أضف الأصل",
    UiKey.ASSET_TRADE_SAVE_BUY to "سجّل الشراء",
    UiKey.ASSET_TRADE_SAVE_SELL to "سجّل البيع",
    UiKey.ASSET_TRADE_SAVE_PRICE to "احفظ السعر",
    UiKey.ASSET_TRADE_ERR_QTY to "اكتب الكمية.",
    UiKey.ASSET_TRADE_ERR_PAID to "اكتب المبلغ المدفوع.",
    UiKey.ASSET_TRADE_ERR_PROCEEDS to "اكتب مبلغ البيع.",
    UiKey.ASSET_TRADE_ERR_PRICE to "اكتب سعرًا أكبر من صفر.",
    UiKey.ASSET_TRADE_DONE_ADD to "أُضيف «{0}» — سجّل أول شراء له",
    UiKey.ASSET_TRADE_DONE_BUY to "سُجّل شراء {0} — تحدّثت التكلفة والمتوسط",
    UiKey.ASSET_TRADE_DONE_SELL to "سُجّل بيع {0} — مبلغ البيع ليس دخلًا",
    UiKey.ASSET_TRADE_DONE_PRICE to "حُفظ سعر يدوي {0} بتاريخ اليوم",
    UiKey.ASSET_TRADE_NAME to "اسم الأصل",
    UiKey.ASSET_TRADE_NAME_HINT to "مثل: ذهب عيار 21",
    UiKey.ASSET_TRADE_KIND to "النوع",
    UiKey.ASSET_TRADE_UNIT to "الوحدة (اختياري)",
    UiKey.ASSET_PROJ_SUB to "{0}، اشتريتها {1} بـ {2} مع الرسوم",
    UiKey.ASSET_PROJ_SUB_NO_COST to "{0}، لا شراء مسجّل بعد",
    UiKey.ASSET_PROJ_VALUE to "قيمتها اليوم",
    UiKey.ASSET_PROJ_BY_AREA to "سعر المتر × المساحة",
    UiKey.ASSET_PROJ_WHOLE to "القيمة كاملة",
    UiKey.ASSET_PROJ_AREA to "المساحة",
    UiKey.ASSET_PROJ_SQM to "سعر المتر",
    UiKey.ASSET_PROJ_SQM_UNIT to "م²",
    UiKey.ASSET_PROJ_APPLY to "حدّث سعر المتر في أملاكي",
    UiKey.ASSET_PROJ_APPLIED to "حُدّث سعر المتر في أملاكك بتاريخ اليوم",
    UiKey.ASSET_PROJ_RENT to "الإيجار",
    UiKey.ASSET_PROJ_RENT_SUB to "كل خانة اختيارية — الفارغة = صفر",
    UiKey.ASSET_PROJ_RENT_MONTHLY to "شهريًا",
    UiKey.ASSET_PROJ_RENT_INC to "زيادة سنوية",
    UiKey.ASSET_PROJ_VACANT to "أشهر فارغة سنويًا",
    UiKey.ASSET_PROJ_MONTH_UNIT to "شهر",
    UiKey.ASSET_PROJ_YEAR to "سنة البيع",
    UiKey.ASSET_PROJ_YEARS_ZERO to "هذه السنة",
    UiKey.ASSET_PROJ_YEARS_ONE to "بعد سنة",
    UiKey.ASSET_PROJ_YEARS_TWO to "بعد سنتين",
    UiKey.ASSET_PROJ_YEARS_FEW to "بعد {0} سنوات",
    UiKey.ASSET_PROJ_YEARS_MANY to "بعد {0} سنة",
    UiKey.ASSET_PROJ_YEAR_UP to "السنة التالية",
    UiKey.ASSET_PROJ_YEAR_DOWN to "السنة السابقة",
    UiKey.ASSET_PROJ_RATE to "الزيادة السنوية المتوقعة",
    UiKey.ASSET_PROJ_RATE_TYPED to "كتبتها أنت",
    UiKey.ASSET_PROJ_RATE_SAVED to "محفوظة على الأصل",
    UiKey.ASSET_PROJ_RATE_DEFAULT to "الافتراضي",
    UiKey.ASSET_PROJ_RATE_OLD to "قديم",
    UiKey.ASSET_PROJ_RATE_MISSING to "ناقص",
    UiKey.ASSET_PROJ_RATE_VALUE to "{0} سنويًا",
    UiKey.ASSET_PROJ_RATE_INPUT to "اكتب النسبة السنوية التي تتوقعها (اختياري)",
    UiKey.ASSET_PROJ_RESULT to "لو بعتها في {0}",
    UiKey.ASSET_PROJ_SALE_PRICE to "سعرها في {0}",
    UiKey.ASSET_PROJ_METHOD to "الزيادة مركّبة كل سنة. الإيجار يُجمع كما هو (لا يُستثمر) ويبدأ من السنة القادمة. المكسب = سعر البيع − ما دفعته فيها + الإيجار.",
    UiKey.ASSET_PROJ_SAVE to "احفظ على الأصل",
    UiKey.ASSET_PROJ_SAVED to "حُفظ على «{0}»: القيمة والإيجار والنسبة",
    UiKey.ASSET_PROJ_ERR_NUMBER to "في إحدى الخانات قيمة ليست رقمًا.",
    UiKey.ASSET_PROJ_ERR_VACANT to "الأشهر الفارغة في السنة من 0 إلى 12",
)

internal val EGYPTIAN_INVEST_TRADE_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ASSET_TRADE_ADD_TITLE to "أصل جديد",
    UiKey.ASSET_TRADE_BUY_TITLE to "شراء {0}",
    UiKey.ASSET_TRADE_SELL_TITLE to "بيع {0}",
    UiKey.ASSET_TRADE_PRICE_TITLE to "سعر بإيدك — {0}",
    UiKey.ASSET_TRADE_SUB to "معاك {0}، التكلفة {1} — تسجيل بس، مفيش تداول",
    UiKey.ASSET_TRADE_WHEN to "إمتى؟",
    UiKey.ASSET_TRADE_TODAY to "النهارده",
    UiKey.ASSET_TRADE_YESTERDAY to "امبارح",
    UiKey.ASSET_TRADE_QTY to "الكمية",
    UiKey.ASSET_TRADE_PAID to "دفعت كام",
    UiKey.ASSET_TRADE_PROCEEDS to "قبضت كام",
    UiKey.ASSET_TRADE_FEES to "الرسوم (لو فيه)",
    UiKey.ASSET_TRADE_LINK_BUY to "اربطه بعملية دفعت بيها (اختياري)",
    UiKey.ASSET_TRADE_LINK_SELL to "اربطه بالفلوس اللي دخلت (اختياري)",
    UiKey.ASSET_TRADE_NO_LINK to "من غير ربط",
    UiKey.ASSET_TRADE_PRICE_LABEL to "سعر ال{0} النهارده",
    UiKey.ASSET_TRADE_NOTE_BUY to "المبلغ بيدخل التكلفة ومعاه الرسوم.",
    UiKey.ASSET_TRADE_NOTE_SELL to "الفلوس اللي قبضتها مش دخل — المكسب بس هو اللي بيبان.",
    UiKey.ASSET_TRADE_NOTE_PRICE to "سعر بإيدك بتاريخ النهارده. لو الأصل مربوط بالسعر اليومي، التحديث الجاي هيكتب فوقه.",
    UiKey.ASSET_TRADE_SAVE_ADD to "ضيف الأصل",
    UiKey.ASSET_TRADE_SAVE_BUY to "سجّل الشراء",
    UiKey.ASSET_TRADE_SAVE_SELL to "سجّل البيع",
    UiKey.ASSET_TRADE_SAVE_PRICE to "احفظ السعر",
    UiKey.ASSET_TRADE_ERR_QTY to "اكتب الكمية.",
    UiKey.ASSET_TRADE_ERR_PAID to "اكتب دفعت كام.",
    UiKey.ASSET_TRADE_ERR_PROCEEDS to "اكتب قبضت كام.",
    UiKey.ASSET_TRADE_ERR_PRICE to "اكتب سعر أكبر من صفر.",
    UiKey.ASSET_TRADE_DONE_ADD to "اتضاف «{0}» — سجّل أول شراء ليه",
    UiKey.ASSET_TRADE_DONE_BUY to "اتسجّل شراء {0} — التكلفة والمتوسط اتحدّثوا",
    UiKey.ASSET_TRADE_DONE_SELL to "اتسجّل بيع {0} — الفلوس دي مش دخل",
    UiKey.ASSET_TRADE_DONE_PRICE to "اتسجّل سعر بإيدك {0} بتاريخ النهارده",
    UiKey.ASSET_TRADE_NAME to "اسم الأصل",
    UiKey.ASSET_TRADE_NAME_HINT to "زي: دهب عيار 21",
    UiKey.ASSET_TRADE_KIND to "النوع",
    UiKey.ASSET_TRADE_UNIT to "الوحدة (لو عايز تغيّرها)",
    UiKey.ASSET_PROJ_SUB to "{0}، اشتريتها {1} بـ {2} بالرسوم",
    UiKey.ASSET_PROJ_SUB_NO_COST to "{0}، مفيش شراء متسجّل لسه",
    UiKey.ASSET_PROJ_VALUE to "قيمتها النهارده",
    UiKey.ASSET_PROJ_BY_AREA to "سعر المتر × المساحة",
    UiKey.ASSET_PROJ_WHOLE to "القيمة كلها",
    UiKey.ASSET_PROJ_AREA to "المساحة",
    UiKey.ASSET_PROJ_SQM to "سعر المتر",
    UiKey.ASSET_PROJ_SQM_UNIT to "م²",
    UiKey.ASSET_PROJ_APPLY to "حدّث سعر المتر في أملاكي",
    UiKey.ASSET_PROJ_APPLIED to "سعر المتر في أملاكك اتحدّث بتاريخ النهارده",
    UiKey.ASSET_PROJ_RENT to "الإيجار",
    UiKey.ASSET_PROJ_RENT_SUB to "كل خانة اختيارية — الفاضية = صفر",
    UiKey.ASSET_PROJ_RENT_MONTHLY to "في الشهر",
    UiKey.ASSET_PROJ_RENT_INC to "زيادة كل سنة",
    UiKey.ASSET_PROJ_VACANT to "شهور فاضية في السنة",
    UiKey.ASSET_PROJ_MONTH_UNIT to "شهر",
    UiKey.ASSET_PROJ_YEAR to "هتبيعها سنة كام؟",
    UiKey.ASSET_PROJ_YEARS_ZERO to "السنة دي",
    UiKey.ASSET_PROJ_YEARS_ONE to "بعد سنة",
    UiKey.ASSET_PROJ_YEARS_TWO to "بعد سنتين",
    UiKey.ASSET_PROJ_YEARS_FEW to "بعد {0} سنين",
    UiKey.ASSET_PROJ_YEARS_MANY to "بعد {0} سنة",
    UiKey.ASSET_PROJ_YEAR_UP to "سنة بعدها",
    UiKey.ASSET_PROJ_YEAR_DOWN to "سنة قبلها",
    UiKey.ASSET_PROJ_RATE to "الزيادة السنوية المتوقعة",
    UiKey.ASSET_PROJ_RATE_TYPED to "كتبتها إنت",
    UiKey.ASSET_PROJ_RATE_SAVED to "محفوظة على الأصل",
    UiKey.ASSET_PROJ_RATE_DEFAULT to "الافتراضي",
    UiKey.ASSET_PROJ_RATE_OLD to "قديم",
    UiKey.ASSET_PROJ_RATE_MISSING to "ناقص",
    UiKey.ASSET_PROJ_RATE_VALUE to "{0} في السنة",
    UiKey.ASSET_PROJ_RATE_INPUT to "اكتب النسبة السنوية اللي متوقعها (اختياري)",
    UiKey.ASSET_PROJ_RESULT to "لو بعتها سنة {0}",
    UiKey.ASSET_PROJ_SALE_PRICE to "سعرها سنة {0}",
    UiKey.ASSET_PROJ_METHOD to "الزيادة مركّبة كل سنة. الإيجار بيتجمع زي ما هو (مش بيتستثمر) ويبدأ من السنة الجاية. المكسب = سعر البيع − اللي دفعته فيها + الإيجار.",
    UiKey.ASSET_PROJ_SAVE to "احفظ على الأصل",
    UiKey.ASSET_PROJ_SAVED to "اتحفظت على «{0}»: القيمة والإيجار والنسبة",
    UiKey.ASSET_PROJ_ERR_NUMBER to "فيه خانة مكتوب فيها حاجة مش رقم.",
    UiKey.ASSET_PROJ_ERR_VACANT to "الشهور الفاضية في السنة من 0 لـ 12",
)

internal val ENGLISH_INVEST_TRADE_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ASSET_TRADE_ADD_TITLE to "New asset",
    UiKey.ASSET_TRADE_BUY_TITLE to "Buy {0}",
    UiKey.ASSET_TRADE_SELL_TITLE to "Sell {0}",
    UiKey.ASSET_TRADE_PRICE_TITLE to "Manual price — {0}",
    UiKey.ASSET_TRADE_SUB to "You hold {0}, cost {1} — record only, no trading",
    UiKey.ASSET_TRADE_WHEN to "When?",
    UiKey.ASSET_TRADE_TODAY to "Today",
    UiKey.ASSET_TRADE_YESTERDAY to "Yesterday",
    UiKey.ASSET_TRADE_QTY to "Quantity",
    UiKey.ASSET_TRADE_PAID to "Amount paid",
    UiKey.ASSET_TRADE_PROCEEDS to "Sale amount",
    UiKey.ASSET_TRADE_FEES to "Fees (optional)",
    UiKey.ASSET_TRADE_LINK_BUY to "Link it to the payment (optional)",
    UiKey.ASSET_TRADE_LINK_SELL to "Link it to the money received (optional)",
    UiKey.ASSET_TRADE_NO_LINK to "No link",
    UiKey.ASSET_TRADE_PRICE_LABEL to "Price per {0} today",
    UiKey.ASSET_TRADE_NOTE_BUY to "The amount goes into the cost, together with the fees.",
    UiKey.ASSET_TRADE_NOTE_SELL to "The sale amount isn't income — only the gain shows.",
    UiKey.ASSET_TRADE_NOTE_PRICE to "A manual price dated today. If the asset is linked to the daily price, the next update will overwrite it.",
    UiKey.ASSET_TRADE_SAVE_ADD to "Add the asset",
    UiKey.ASSET_TRADE_SAVE_BUY to "Record the purchase",
    UiKey.ASSET_TRADE_SAVE_SELL to "Record the sale",
    UiKey.ASSET_TRADE_SAVE_PRICE to "Save the price",
    UiKey.ASSET_TRADE_ERR_QTY to "Enter the quantity.",
    UiKey.ASSET_TRADE_ERR_PAID to "Enter the amount paid.",
    UiKey.ASSET_TRADE_ERR_PROCEEDS to "Enter the sale amount.",
    UiKey.ASSET_TRADE_ERR_PRICE to "Enter a price above zero.",
    UiKey.ASSET_TRADE_DONE_ADD to "“{0}” added — record its first purchase",
    UiKey.ASSET_TRADE_DONE_BUY to "Purchase of {0} recorded — cost and average updated",
    UiKey.ASSET_TRADE_DONE_SELL to "Sale of {0} recorded — the sale amount isn't income",
    UiKey.ASSET_TRADE_DONE_PRICE to "Manual price {0} saved for today",
    UiKey.ASSET_TRADE_NAME to "Asset name",
    UiKey.ASSET_TRADE_NAME_HINT to "e.g. 21-karat gold",
    UiKey.ASSET_TRADE_KIND to "Kind",
    UiKey.ASSET_TRADE_UNIT to "Unit (optional)",
    UiKey.ASSET_PROJ_SUB to "{0}, bought on {1} for {2} with fees",
    UiKey.ASSET_PROJ_SUB_NO_COST to "{0}, no purchase recorded yet",
    UiKey.ASSET_PROJ_VALUE to "Its value today",
    UiKey.ASSET_PROJ_BY_AREA to "Price per m² × area",
    UiKey.ASSET_PROJ_WHOLE to "Whole value",
    UiKey.ASSET_PROJ_AREA to "Area",
    UiKey.ASSET_PROJ_SQM to "Price per m²",
    UiKey.ASSET_PROJ_SQM_UNIT to "m²",
    UiKey.ASSET_PROJ_APPLY to "Update the price per m² in my assets",
    UiKey.ASSET_PROJ_APPLIED to "The price per m² in your assets is updated as of today",
    UiKey.ASSET_PROJ_RENT to "Rent",
    UiKey.ASSET_PROJ_RENT_SUB to "Every field is optional — empty means zero",
    UiKey.ASSET_PROJ_RENT_MONTHLY to "Monthly",
    UiKey.ASSET_PROJ_RENT_INC to "Yearly increase",
    UiKey.ASSET_PROJ_VACANT to "Empty months a year",
    UiKey.ASSET_PROJ_MONTH_UNIT to "mo",
    UiKey.ASSET_PROJ_YEAR to "Year of sale",
    UiKey.ASSET_PROJ_YEARS_ZERO to "This year",
    UiKey.ASSET_PROJ_YEARS_ONE to "In one year",
    UiKey.ASSET_PROJ_YEARS_TWO to "In two years",
    UiKey.ASSET_PROJ_YEARS_FEW to "In {0} years",
    UiKey.ASSET_PROJ_YEARS_MANY to "In {0} years",
    UiKey.ASSET_PROJ_YEAR_UP to "Next year",
    UiKey.ASSET_PROJ_YEAR_DOWN to "Previous year",
    UiKey.ASSET_PROJ_RATE to "Expected yearly increase",
    UiKey.ASSET_PROJ_RATE_TYPED to "You entered it",
    UiKey.ASSET_PROJ_RATE_SAVED to "Saved on the asset",
    UiKey.ASSET_PROJ_RATE_DEFAULT to "Default",
    UiKey.ASSET_PROJ_RATE_OLD to "Old",
    UiKey.ASSET_PROJ_RATE_MISSING to "Missing",
    UiKey.ASSET_PROJ_RATE_VALUE to "{0} a year",
    UiKey.ASSET_PROJ_RATE_INPUT to "Enter the yearly rate you expect (optional)",
    UiKey.ASSET_PROJ_RESULT to "If you sold it in {0}",
    UiKey.ASSET_PROJ_SALE_PRICE to "Its price in {0}",
    UiKey.ASSET_PROJ_METHOD to "The increase compounds every year. Rent is added as is (not invested) and starts next year. Gain = sale price − what you paid + rent.",
    UiKey.ASSET_PROJ_SAVE to "Save on the asset",
    UiKey.ASSET_PROJ_SAVED to "Saved on “{0}”: value, rent and rate",
    UiKey.ASSET_PROJ_ERR_NUMBER to "One of the fields isn't a number.",
    UiKey.ASSET_PROJ_ERR_VACANT to "Empty months a year go from 0 to 12",
)
