package app.masroufy.core

/** نصوص «القواعد والتجار» (`Rules`) ولوحتها — منطقة الميزانيات (`TextsAreaBudgets.kt`). */
internal val MSA_BUDGETS_RULES: Map<TextKey, String> = mapOf(
    TextKey.RULES_TITLE to "القواعد والتجار",
    TextKey.RULES_INTRO to "تأخذ العمليات الجديدة تصنيفها تلقائيًا: أولًا التاجر المحفوظ، ثم قواعدك بالترتيب.",
    TextKey.RULES_NEW to "قاعدة جديدة",
    TextKey.RULES_MERCHANTS_TITLE to "تجار يتذكرهم التطبيق",
    TextKey.RULES_MERCHANTS_NOTE to "عندما تختار تصنيفًا لتاجر بنفسك يُحفظ له تلقائيًا، ويُطبَّق قبل أي قاعدة.",
    TextKey.RULES_MERCHANTS_EMPTY to "لا شيء بعد. يظهر هنا التاجر بعد أول تصنيف تختاره له.",
    TextKey.RULES_YOURS_TITLE to "قواعدك",
    TextKey.RULES_YOURS_NOTE to "الأصغر رقمًا يُطبَّق أولًا. الإقفال لا يحذف القاعدة.",
    TextKey.RULES_EMPTY to "لا قواعد بعد. اضغط + لإضافة أول قاعدة.",
    TextKey.RULES_MERCHANT to "التاجر",
    TextKey.RULES_NO_FIXED to "بلا تصنيف ثابت — تُطبَّق القواعد",
    TextKey.RULES_ALIASES to "أسماء بديلة: {0}",
    TextKey.RULES_MODE_CONTAINS to "يحتوي",
    TextKey.RULES_MODE_STARTS to "يبدأ بـ",
    TextKey.RULES_MODE_EXACT to "مطابق تمامًا",
    TextKey.RULES_RULE_ARIA to "تعديل قاعدة {0}",
    TextKey.RULES_OFF_META to "مقفولة — تبقى هنا ولا تُطبَّق",
    TextKey.RULES_MISSING_META to "حُذف تصنيفها — اختر تصنيفًا آخر",
    TextKey.RULES_SWITCH to "تشغيل قاعدة {0}",
    TextKey.RULES_OFF_TOAST to "أُقفلت القاعدة — ما زالت ظاهرة",
    TextKey.RULES_ON_TOAST to "شُغّلت القاعدة",
    TextKey.RULES_APPLY_TITLE to "طبّق القواعد على السابق",
    TextKey.RULES_APPLY_BODY to "تعديل القاعدة لا يغيّر السابق وحده. اعرض ما سيتغير أولًا.",
    TextKey.RULES_APPLY_NONE to "لا قاعدة مفعّلة ستغيّر شيئًا في السابق.",
    TextKey.RULES_APPLY_DONE to "طُبّقت. ما أكدته بنفسك لم يُمس.",
    TextKey.RULES_APPLY_PREVIEW to "اعرض ما سيتغير",
    TextKey.RULES_APPLY_GO to "طبّق ({0})",
    TextKey.RULES_APPLY_DONE_BTN to "طُبّقت",
    TextKey.RULES_APPLY_CONFIRMED to "أكّدتها بنفسك — لن تُمس",
    TextKey.RULES_APPLY_UNMATCHED to "لا قاعدة تطابقها — تبقى للمراجعة",
    TextKey.RULES_APPLIED_TOAST to "تغيّر تصنيف {0}",
    TextKey.RULES_OPS_ONE to "عملية واحدة",
    TextKey.RULES_OPS_TWO to "عمليتان",
    TextKey.RULES_OPS_FEW to "{0} عمليات",
    TextKey.RULES_OPS_MANY to "{0} عملية",
    TextKey.RULES_SYNC_TITLE to "قاعدة التجار المشتركة",
    TextKey.RULES_SYNC_BODY to "أسماء محلات وتصنيفها المبدئي من مستخدمي مصروفي — بلا مبالغ ولا تواريخ. لا يُكتب فوق تصنيفك.",
    TextKey.RULES_SYNC_NA to "التحديث غير متاح بعد في هذه النسخة.",
    TextKey.RULES_SYNC_BTN to "حدّث الآن",
    TextKey.RULES_SHEET_EDIT to "تعديل قاعدة",
    TextKey.RULES_SHEET_MERCHANT to "تعديل التاجر",
    TextKey.RULES_TEXT_LABEL to "إذا كان الوصف…",
    TextKey.RULES_TEXT_HINT to "مثلًا: مطعم",
    TextKey.RULES_MERCHANT_NAME to "اسم التاجر",
    TextKey.RULES_MODE_LABEL to "طريقة المطابقة",
    TextKey.RULES_ALIAS_LABEL to "أسماء بديلة في الكشف",
    TextKey.RULES_ALIAS_HINT to "كما يظهر في رسالة البنك",
    TextKey.RULES_CAT_LABEL to "التصنيف",
    TextKey.RULES_PRI_LABEL to "الترتيب",
    TextKey.RULES_PRI_NOTE to "١ يُطبَّق أولًا",
    TextKey.RULES_PRI_UP to "قدّمها",
    TextKey.RULES_PRI_DOWN to "أخّرها",
    TextKey.RULES_NOTE_MERCHANT to "يُطبَّق هذا التصنيف على عمليات التاجر القادمة، والسابقة عبر «طبّق على السابق».",
    TextKey.RULES_NOTE_RULE to "تعديل القاعدة لا يغيّر العمليات السابقة وحده.",
    TextKey.RULES_FORGET to "انسَ تصنيفه",
    TextKey.RULES_MERCHANT_SAVED to "حُفظ التاجر",
    TextKey.RULES_SAVED to "حُفظت القاعدة",
    TextKey.RULES_ADDED to "أُضيفت القاعدة — تُطبَّق على الجديد",
    TextKey.RULES_FORGOT to "نُسي تصنيفه — تُطبَّق القواعد عليه",
    TextKey.RULES_QUOTED to "«{0}»",
    TextKey.RULES_ALIAS_ADD to "أضف",
    TextKey.RULES_SAVE to "احفظ",
)

internal val EGYPTIAN_BUDGETS_RULES: Map<TextKey, String> = mapOf(
    TextKey.RULES_TITLE to "القواعد والتجار",
    TextKey.RULES_INTRO to "العمليات الجديدة بتاخد تصنيفها لوحدها: الأول التاجر اللي فاكره البرنامج، وبعدين قواعدك بالترتيب.",
    TextKey.RULES_NEW to "قاعدة جديدة",
    TextKey.RULES_MERCHANTS_TITLE to "تجار فاكرهم البرنامج",
    TextKey.RULES_MERCHANTS_NOTE to "لما تختار تصنيف لتاجر بإيدك، بيتحفظ له على طول ويتطبق قبل أي قاعدة.",
    TextKey.RULES_MERCHANTS_EMPTY to "لسه مفيش. أول ما تختار تصنيف لتاجر هيظهر هنا.",
    TextKey.RULES_YOURS_TITLE to "قواعدك",
    TextKey.RULES_YOURS_NOTE to "الرقم الأصغر بيتطبق الأول. القفل مش مسح.",
    TextKey.RULES_EMPTY to "مفيش قواعد. دوس + وضيف أول قاعدة.",
    TextKey.RULES_MERCHANT to "التاجر",
    TextKey.RULES_NO_FIXED to "من غير تصنيف ثابت — القواعد بتشتغل",
    TextKey.RULES_ALIASES to "أسامي تانية: {0}",
    TextKey.RULES_MODE_CONTAINS to "فيه",
    TextKey.RULES_MODE_STARTS to "بيبدأ بـ",
    TextKey.RULES_MODE_EXACT to "بالظبط",
    TextKey.RULES_RULE_ARIA to "عدّل قاعدة {0}",
    TextKey.RULES_OFF_META to "مقفولة — بتفضل هنا ومش بتتطبق",
    TextKey.RULES_MISSING_META to "تصنيفها اتشال — اختار تصنيف تاني",
    TextKey.RULES_SWITCH to "شغّل قاعدة {0}",
    TextKey.RULES_OFF_TOAST to "القاعدة اتقفلت — لسه موجودة",
    TextKey.RULES_ON_TOAST to "القاعدة اشتغلت",
    TextKey.RULES_APPLY_TITLE to "طبّق القواعد على القديم",
    TextKey.RULES_APPLY_BODY to "تعديل قاعدة مش بيغيّر القديم لوحده. شوف الأول هيتغيّر إيه.",
    TextKey.RULES_APPLY_NONE to "مفيش قاعدة شغالة هتغيّر حاجة في القديم.",
    TextKey.RULES_APPLY_DONE to "اتطبقت. اللي أكدته بإيدك ما اتلمسش.",
    TextKey.RULES_APPLY_PREVIEW to "شوف هيتغيّر إيه",
    TextKey.RULES_APPLY_GO to "غيّرهم ({0})",
    TextKey.RULES_APPLY_DONE_BTN to "اتطبقت",
    TextKey.RULES_APPLY_CONFIRMED to "أكّدتها بإيدك — مش هتتلمس",
    TextKey.RULES_APPLY_UNMATCHED to "مفيش قاعدة تطابقها — تفضل للمراجعة",
    TextKey.RULES_APPLIED_TOAST to "اتغيّر تصنيف {0}",
    TextKey.RULES_OPS_ONE to "عملية واحدة",
    TextKey.RULES_OPS_TWO to "عمليتين",
    TextKey.RULES_OPS_FEW to "{0} عمليات",
    TextKey.RULES_OPS_MANY to "{0} عملية",
    TextKey.RULES_SYNC_TITLE to "قاعدة التجار المشتركة",
    TextKey.RULES_SYNC_BODY to "أسامي محلات وتصنيفها المبدئي من مستخدمين مصروفي — من غير مبالغ ولا تواريخ. تصنيفك إنت ما بيتكتبش فوقه.",
    TextKey.RULES_SYNC_NA to "التحديث لسه مش متاح في النسخة دي.",
    TextKey.RULES_SYNC_BTN to "حدّث دلوقتي",
    TextKey.RULES_SHEET_EDIT to "تعديل قاعدة",
    TextKey.RULES_SHEET_MERCHANT to "تعديل التاجر",
    TextKey.RULES_TEXT_LABEL to "لو الوصف…",
    TextKey.RULES_TEXT_HINT to "مثلًا: مطعم",
    TextKey.RULES_MERCHANT_NAME to "اسم التاجر",
    TextKey.RULES_MODE_LABEL to "طريقة المطابقة",
    TextKey.RULES_ALIAS_LABEL to "أسامي تانية في الكشف",
    TextKey.RULES_ALIAS_HINT to "زي ما بيظهر في رسالة البنك",
    TextKey.RULES_CAT_LABEL to "التصنيف",
    TextKey.RULES_PRI_LABEL to "الترتيب",
    TextKey.RULES_PRI_NOTE to "١ بيتطبق الأول",
    TextKey.RULES_PRI_UP to "قدّمها",
    TextKey.RULES_PRI_DOWN to "أخّرها",
    TextKey.RULES_NOTE_MERCHANT to "التصنيف ده بيتطبق على عمليات التاجر الجاية. القديمة تتغير من «طبّق على القديم».",
    TextKey.RULES_NOTE_RULE to "تعديل القاعدة مش بيغيّر العمليات القديمة لوحده.",
    TextKey.RULES_FORGET to "انسى تصنيفه",
    TextKey.RULES_MERCHANT_SAVED to "اتحفظ التاجر",
    TextKey.RULES_SAVED to "اتحفظت القاعدة",
    TextKey.RULES_ADDED to "اتضافت القاعدة — بتشتغل على الجديد",
    TextKey.RULES_FORGOT to "البرنامج نسي تصنيفه — القواعد هي اللي هتشتغل",
    TextKey.RULES_QUOTED to "«{0}»",
    TextKey.RULES_ALIAS_ADD to "ضيف",
    TextKey.RULES_SAVE to "احفظ",
)

internal val ENGLISH_BUDGETS_RULES: Map<TextKey, String> = mapOf(
    TextKey.RULES_TITLE to "Rules and merchants",
    TextKey.RULES_INTRO to "New operations get their category by themselves: first a remembered merchant, then your rules in order.",
    TextKey.RULES_NEW to "New rule",
    TextKey.RULES_MERCHANTS_TITLE to "Merchants the app remembers",
    TextKey.RULES_MERCHANTS_NOTE to "When you pick a category for a merchant yourself, it's kept for that merchant and applies before any rule.",
    TextKey.RULES_MERCHANTS_EMPTY to "Nothing yet. A merchant shows here after the first category you pick for it.",
    TextKey.RULES_YOURS_TITLE to "Your rules",
    TextKey.RULES_YOURS_NOTE to "The smaller number applies first. Turning a rule off doesn't delete it.",
    TextKey.RULES_EMPTY to "No rules yet. Tap + to add the first one.",
    TextKey.RULES_MERCHANT to "Merchant",
    TextKey.RULES_NO_FIXED to "No fixed category — rules apply",
    TextKey.RULES_ALIASES to "Other names: {0}",
    TextKey.RULES_MODE_CONTAINS to "Contains",
    TextKey.RULES_MODE_STARTS to "Starts with",
    TextKey.RULES_MODE_EXACT to "Exactly",
    TextKey.RULES_RULE_ARIA to "Edit rule {0}",
    TextKey.RULES_OFF_META to "Off — it stays here and doesn't apply",
    TextKey.RULES_MISSING_META to "Its category was removed — pick another one",
    TextKey.RULES_SWITCH to "Turn on rule {0}",
    TextKey.RULES_OFF_TOAST to "Rule turned off — it's still listed",
    TextKey.RULES_ON_TOAST to "Rule turned on",
    TextKey.RULES_APPLY_TITLE to "Apply the rules to past operations",
    TextKey.RULES_APPLY_BODY to "Editing a rule doesn't change past operations by itself. See what would change first.",
    TextKey.RULES_APPLY_NONE to "No active rule would change anything in the past.",
    TextKey.RULES_APPLY_DONE to "Applied. What you confirmed yourself wasn't touched.",
    TextKey.RULES_APPLY_PREVIEW to "See what would change",
    TextKey.RULES_APPLY_GO to "Apply ({0})",
    TextKey.RULES_APPLY_DONE_BTN to "Applied",
    TextKey.RULES_APPLY_CONFIRMED to "You confirmed these — they won't be touched",
    TextKey.RULES_APPLY_UNMATCHED to "No rule matches — they stay for review",
    TextKey.RULES_APPLIED_TOAST to "Changed the category of {0}",
    TextKey.RULES_OPS_ONE to "one operation",
    TextKey.RULES_OPS_TWO to "two operations",
    TextKey.RULES_OPS_FEW to "{0} operations",
    TextKey.RULES_OPS_MANY to "{0} operations",
    TextKey.RULES_SYNC_TITLE to "Shared merchant list",
    TextKey.RULES_SYNC_BODY to "Shop names and their starting category from Masroufy users — no amounts or dates. Your own category is never overwritten.",
    TextKey.RULES_SYNC_NA to "Updating isn't available in this version yet.",
    TextKey.RULES_SYNC_BTN to "Update now",
    TextKey.RULES_SHEET_EDIT to "Edit rule",
    TextKey.RULES_SHEET_MERCHANT to "Edit merchant",
    TextKey.RULES_TEXT_LABEL to "If the description…",
    TextKey.RULES_TEXT_HINT to "For example: restaurant",
    TextKey.RULES_MERCHANT_NAME to "Merchant name",
    TextKey.RULES_MODE_LABEL to "How it matches",
    TextKey.RULES_ALIAS_LABEL to "Other names on the statement",
    TextKey.RULES_ALIAS_HINT to "As it appears in the bank message",
    TextKey.RULES_CAT_LABEL to "Category",
    TextKey.RULES_PRI_LABEL to "Order",
    TextKey.RULES_PRI_NOTE to "1 applies first",
    TextKey.RULES_PRI_UP to "Move up",
    TextKey.RULES_PRI_DOWN to "Move down",
    TextKey.RULES_NOTE_MERCHANT to "This category applies to the merchant's coming operations; past ones change through “Apply to past operations”.",
    TextKey.RULES_NOTE_RULE to "Editing a rule doesn't change past operations by itself.",
    TextKey.RULES_FORGET to "Forget its category",
    TextKey.RULES_MERCHANT_SAVED to "Merchant saved",
    TextKey.RULES_SAVED to "Rule saved",
    TextKey.RULES_ADDED to "Rule added — it applies to new operations",
    TextKey.RULES_FORGOT to "Its category is forgotten — rules apply to it now",
    TextKey.RULES_QUOTED to "“{0}”",
    TextKey.RULES_ALIAS_ADD to "Add",
    TextKey.RULES_SAVE to "Save",
)
