package app.masroufy.core

/**
 * «الاستيراد» ٥/٥: `ImportBatches` + `RevertBatchSheet`. النص من النموذج التفاعلي بالحرف (الفصحى من `space = السعودية` والمصري من `مصر`)،
 * واللي مالوش مقابل في النموذج كتابة Claude بنفس النبرة. سبب بقاء كل عملية = جملة المنطق نفسها (`REVERT_KEPT_*`) — هنا الكلمة اللي على الشارة بس.
 * **ممنوع «·» جنب رقم عربي** ⇒ «،».
 */
internal val MSA_IMPORTS_BATCHES_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.IMPORT_BATCHES_TITLE to "دفعات الاستيراد",
    TextKey.IMPORT_BATCHES_INTRO to "كل كشف أو مجموعة رسائل تُسجَّل دفعة واحدة. يمكنك إرجاع أي دفعة، ويبقى ما ارتبط بشيء آخر.",
    TextKey.IMPORT_BATCHES_EMPTY_TITLE to "لم تستورد شيئًا بعد",
    TextKey.IMPORT_BATCHES_EMPTY_BODY to "أول كشف تستورده يظهر هنا، ويمكنك إرجاعه متى شئت.",
    TextKey.IMPORT_BATCHES_IMPORT to "استورد كشفًا",
    TextKey.IMPORT_BATCHES_STAGED_TITLE to "استيراد انقطع في المنتصف",
    TextKey.IMPORT_BATCHES_STAGED_BODY to "توقف الحفظ قبل أن يكتمل، وما حُفظ منه غير معتمد — نظّفه أولًا ثم استورد الملف من جديد.",
    TextKey.IMPORT_BATCHES_CLEAN to "نظّفه الآن",
    TextKey.IMPORT_BATCHES_CLEANING to "جارٍ التنظيف…",
    TextKey.IMPORT_BATCHES_CLEANED_TITLE to "نُظّف الاستيراد المنقطع",
    TextKey.IMPORT_BATCHES_CLEANED_BODY to "حُذف ما لم يكتمل: {0}. لإكماله استورد الملف من جديد.",
    TextKey.IMPORT_BATCHES_CLEANED_TOAST to "نُظّف: حُذف ما لم يكتمل ({0})",
    TextKey.IMPORT_BATCHES_CLEAN_FAILED to "تعذّر التنظيف",
    TextKey.IMPORT_BATCHES_REIMPORT to "استورد الملف من جديد",
    TextKey.IMPORT_BATCHES_SRC_SMS to "سُجّلت تلقائيًا من رسائل البنك",
    TextKey.IMPORT_BATCHES_SRC_ALRAJHI to "كشف مصرف الراجحي",
    TextKey.IMPORT_BATCHES_SRC_QNB to "كشف QNB مصر",
    TextKey.IMPORT_BATCHES_SRC_CSV to "ملف CSV",
    TextKey.IMPORT_BATCHES_COMMITTED_CHIP to "مسجّلة",
    TextKey.IMPORT_BATCHES_REVERTED_CHIP to "أُرجعت",
    TextKey.IMPORT_BATCHES_ADDED to "أُضيف",
    TextKey.IMPORT_BATCHES_COUNT to "{0} {1}",
    TextKey.IMPORT_BATCHES_REVERT to "إرجاع الدفعة",
    TextKey.IMPORT_BATCHES_FOOT to "الإرجاع يحذف عمليات الدفعة فقط، ولا يمس أي تسوية أو دين.",
    TextKey.IMPORT_BATCHES_REVERTED to "أُرجعت الدفعة: {0}",
    TextKey.IMPORT_BATCHES_RESULT to "حُذفت {0}.",
    TextKey.IMPORT_BATCHES_RESULT_KEPT to "حُذفت {0}، وبقيت {1} لارتباطها بغيرها.",
    TextKey.REVERT_SHEET_TITLE to "إرجاع «{0}»",
    TextKey.REVERT_SHEET_LOADING to "نتحقق مما سيُحذف وما سيبقى…",
    TextKey.REVERT_SHEET_FAILED to "تعذّر إرجاع هذه الدفعة",
    TextKey.REVERT_SHEET_WILL_DELETE to "سيُحذف",
    TextKey.REVERT_SHEET_WILL_KEEP to "سيبقى",
    TextKey.REVERT_SHEET_NOTHING to "لا شيء",
    TextKey.REVERT_SHEET_KEPT_TITLE to "ما سيبقى ولماذا",
    TextKey.REVERT_SHEET_KEEP_SETTLE to "تسوية",
    TextKey.REVERT_SHEET_KEEP_ALLOC to "تقسيم",
    TextKey.REVERT_SHEET_KEEP_DUE to "مستحقات",
    TextKey.REVERT_SHEET_KEEP_GIFT to "نقوط",
    TextKey.REVERT_SHEET_KEEP_INVEST to "استثمار",
    TextKey.REVERT_SHEET_KEEP_SOURCE to "مصدر آخر",
    TextKey.REVERT_SHEET_CLEAN to "الإرجاع نظيف: لا عملية من هذه الدفعة مرتبطة بشيء آخر.",
    TextKey.REVERT_SHEET_DELETE_TITLE to "ما سيُحذف",
    TextKey.REVERT_SHEET_MORE to "ومعها {0} غيرها",
    TextKey.REVERT_SHEET_UNLINK to "يُزال مع المحذوف {0} (مشروع، وسم، حدث). ولا تُمس التسويات والديون.",
    TextKey.REVERT_SHEET_UNTOUCHED to "لا تُمس التسويات والديون.",
    TextKey.REVERT_SHEET_LINKS_ONE to "رابط واحد",
    TextKey.REVERT_SHEET_LINKS_TWO to "رابطان",
    TextKey.REVERT_SHEET_LINKS_FEW to "{0} روابط",
    TextKey.REVERT_SHEET_LINKS_MANY to "{0} رابطًا",
    TextKey.REVERT_SHEET_CONFIRM to "أرجِع الدفعة",
    TextKey.REVERT_SHEET_RUNNING to "جارٍ الإرجاع…",
)

internal val EGYPTIAN_IMPORTS_BATCHES_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.IMPORT_BATCHES_TITLE to "دفعات الاستيراد",
    TextKey.IMPORT_BATCHES_INTRO to "كل كشف أو مجموعة رسايل بتتسجل دفعة واحدة. تقدر ترجّع أي دفعة، واللي متربط بحاجة تانية بيفضل.",
    TextKey.IMPORT_BATCHES_EMPTY_TITLE to "لسه ما استوردتش حاجة",
    TextKey.IMPORT_BATCHES_EMPTY_BODY to "أول كشف تستورده هيظهر هنا، وتقدر ترجّعه لو حبيت.",
    TextKey.IMPORT_BATCHES_IMPORT to "استورد كشف",
    TextKey.IMPORT_BATCHES_STAGED_TITLE to "استيراد اتقطع في النص",
    TextKey.IMPORT_BATCHES_STAGED_BODY to "الحفظ وقف قبل ما يكمل، واللي اتحفظ منه مش معتمد — نضّفه الأول، وبعدين استورد الملف تاني.",
    TextKey.IMPORT_BATCHES_CLEAN to "نضّفه دلوقتي",
    TextKey.IMPORT_BATCHES_CLEANING to "بينضّف…",
    TextKey.IMPORT_BATCHES_CLEANED_TITLE to "اتنضّف الاستيراد اللي اتقطع",
    TextKey.IMPORT_BATCHES_CLEANED_BODY to "اتمسح اللي ما كملش: {0}. علشان تكمّله، استورد الملف تاني.",
    TextKey.IMPORT_BATCHES_CLEANED_TOAST to "اتنضّف: اتمسح اللي ما كملش ({0})",
    TextKey.IMPORT_BATCHES_CLEAN_FAILED to "ما قدرناش ننضّفه",
    TextKey.IMPORT_BATCHES_REIMPORT to "استورد الملف تاني",
    TextKey.IMPORT_BATCHES_SRC_SMS to "اتسجلت لوحدها من رسايل البنك",
    TextKey.IMPORT_BATCHES_SRC_ALRAJHI to "كشف مصرف الراجحي",
    TextKey.IMPORT_BATCHES_SRC_QNB to "كشف QNB مصر",
    TextKey.IMPORT_BATCHES_SRC_CSV to "ملف CSV",
    TextKey.IMPORT_BATCHES_COMMITTED_CHIP to "متسجلة",
    TextKey.IMPORT_BATCHES_REVERTED_CHIP to "اترجعت",
    TextKey.IMPORT_BATCHES_ADDED to "اتضاف",
    TextKey.IMPORT_BATCHES_COUNT to "{0} {1}",
    TextKey.IMPORT_BATCHES_REVERT to "رجّع الدفعة",
    TextKey.IMPORT_BATCHES_FOOT to "الترجيع بيمسح عمليات الدفعة بس، ومفيش تسوية ولا دين بيتلمس.",
    TextKey.IMPORT_BATCHES_REVERTED to "اترجعت الدفعة: {0}",
    TextKey.IMPORT_BATCHES_RESULT to "اتمسحت {0}.",
    TextKey.IMPORT_BATCHES_RESULT_KEPT to "اتمسحت {0}، وفضلت {1} متربطة بحاجات تانية.",
    TextKey.REVERT_SHEET_TITLE to "ترجيع «{0}»",
    TextKey.REVERT_SHEET_LOADING to "بنشوف إيه اللي هيتمسح وإيه اللي هيفضل…",
    TextKey.REVERT_SHEET_FAILED to "مقدرناش نرجّع الدفعة دي",
    TextKey.REVERT_SHEET_WILL_DELETE to "هيتمسح",
    TextKey.REVERT_SHEET_WILL_KEEP to "هيفضل",
    TextKey.REVERT_SHEET_NOTHING to "ولا حاجة",
    TextKey.REVERT_SHEET_KEPT_TITLE to "اللي هيفضل وليه",
    TextKey.REVERT_SHEET_KEEP_SETTLE to "تسوية",
    TextKey.REVERT_SHEET_KEEP_ALLOC to "تقسيم",
    TextKey.REVERT_SHEET_KEEP_DUE to "مستحقات",
    TextKey.REVERT_SHEET_KEEP_GIFT to "نقطة",
    TextKey.REVERT_SHEET_KEEP_INVEST to "استثمار",
    TextKey.REVERT_SHEET_KEEP_SOURCE to "مصدر تاني",
    TextKey.REVERT_SHEET_CLEAN to "الترجيع نظيف: مفيش عملية من الدفعة دي متربطة بحاجة تانية.",
    TextKey.REVERT_SHEET_DELETE_TITLE to "اللي هيتمسح",
    TextKey.REVERT_SHEET_MORE to "ومعاها {0} كمان",
    TextKey.REVERT_SHEET_UNLINK to "هيتشال مع اللي هيتمسح {0} (مشروع، وسم، حدث). والتسويات والديون مش بتتلمس.",
    TextKey.REVERT_SHEET_UNTOUCHED to "التسويات والديون مش بتتلمس.",
    TextKey.REVERT_SHEET_LINKS_ONE to "ربط واحد",
    TextKey.REVERT_SHEET_LINKS_TWO to "ربطين",
    TextKey.REVERT_SHEET_LINKS_FEW to "{0} روابط",
    TextKey.REVERT_SHEET_LINKS_MANY to "{0} ربط",
    TextKey.REVERT_SHEET_CONFIRM to "رجّع الدفعة",
    TextKey.REVERT_SHEET_RUNNING to "بيترجع…",
)

internal val ENGLISH_IMPORTS_BATCHES_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.IMPORT_BATCHES_TITLE to "Import batches",
    TextKey.IMPORT_BATCHES_INTRO to "Each statement or group of messages is saved as one batch. You can undo any batch; anything linked to something else stays.",
    TextKey.IMPORT_BATCHES_EMPTY_TITLE to "Nothing imported yet",
    TextKey.IMPORT_BATCHES_EMPTY_BODY to "The first statement you import appears here, and you can undo it whenever you like.",
    TextKey.IMPORT_BATCHES_IMPORT to "Import a statement",
    TextKey.IMPORT_BATCHES_STAGED_TITLE to "An import stopped halfway",
    TextKey.IMPORT_BATCHES_STAGED_BODY to "Saving stopped before it finished, and what was saved isn't confirmed — clean it up first, then import the file again.",
    TextKey.IMPORT_BATCHES_CLEAN to "Clean it up now",
    TextKey.IMPORT_BATCHES_CLEANING to "Cleaning up…",
    TextKey.IMPORT_BATCHES_CLEANED_TITLE to "The interrupted import was cleaned up",
    TextKey.IMPORT_BATCHES_CLEANED_BODY to "Removed what didn't finish: {0}. To complete it, import the file again.",
    TextKey.IMPORT_BATCHES_CLEANED_TOAST to "Cleaned up: removed what didn't finish ({0})",
    TextKey.IMPORT_BATCHES_CLEAN_FAILED to "Couldn't clean it up",
    TextKey.IMPORT_BATCHES_REIMPORT to "Import the file again",
    TextKey.IMPORT_BATCHES_SRC_SMS to "Saved automatically from bank messages",
    TextKey.IMPORT_BATCHES_SRC_ALRAJHI to "Al Rajhi Bank statement",
    TextKey.IMPORT_BATCHES_SRC_QNB to "QNB Egypt statement",
    TextKey.IMPORT_BATCHES_SRC_CSV to "CSV file",
    TextKey.IMPORT_BATCHES_COMMITTED_CHIP to "Saved",
    TextKey.IMPORT_BATCHES_REVERTED_CHIP to "Undone",
    TextKey.IMPORT_BATCHES_ADDED to "Added",
    TextKey.IMPORT_BATCHES_COUNT to "{0} {1}",
    TextKey.IMPORT_BATCHES_REVERT to "Undo batch",
    TextKey.IMPORT_BATCHES_FOOT to "Undoing deletes only the batch's transactions; no settlement or debt is touched.",
    TextKey.IMPORT_BATCHES_REVERTED to "Batch undone: {0}",
    TextKey.IMPORT_BATCHES_RESULT to "deleted {0}.",
    TextKey.IMPORT_BATCHES_RESULT_KEPT to "deleted {0}; {1} stayed because linked to something else.",
    TextKey.REVERT_SHEET_TITLE to "Undo “{0}”",
    TextKey.REVERT_SHEET_LOADING to "Checking what will be deleted and what will stay…",
    TextKey.REVERT_SHEET_FAILED to "Couldn't undo this batch",
    TextKey.REVERT_SHEET_WILL_DELETE to "Will be deleted",
    TextKey.REVERT_SHEET_WILL_KEEP to "Will stay",
    TextKey.REVERT_SHEET_NOTHING to "Nothing",
    TextKey.REVERT_SHEET_KEPT_TITLE to "What stays and why",
    TextKey.REVERT_SHEET_KEEP_SETTLE to "Settlement",
    TextKey.REVERT_SHEET_KEEP_ALLOC to "Split",
    TextKey.REVERT_SHEET_KEEP_DUE to "Dues",
    TextKey.REVERT_SHEET_KEEP_GIFT to "Gift",
    TextKey.REVERT_SHEET_KEEP_INVEST to "Investment",
    TextKey.REVERT_SHEET_KEEP_SOURCE to "Another source",
    TextKey.REVERT_SHEET_CLEAN to "A clean undo: no transaction in this batch is linked to anything else.",
    TextKey.REVERT_SHEET_DELETE_TITLE to "What will be deleted",
    TextKey.REVERT_SHEET_MORE to "and {0} more",
    TextKey.REVERT_SHEET_UNLINK to "{0} (project, tag, event) are removed with what's deleted. Settlements and debts are not touched.",
    TextKey.REVERT_SHEET_UNTOUCHED to "Settlements and debts are not touched.",
    TextKey.REVERT_SHEET_LINKS_ONE to "1 link",
    TextKey.REVERT_SHEET_LINKS_TWO to "2 links",
    TextKey.REVERT_SHEET_LINKS_FEW to "{0} links",
    TextKey.REVERT_SHEET_LINKS_MANY to "{0} links",
    TextKey.REVERT_SHEET_CONFIRM to "Undo batch",
    TextKey.REVERT_SHEET_RUNNING to "Undoing…",
)
