package app.masroufy.core

/** نصوص «ميزانية تصنيف» (`CategoryBudget`) ولوحة السقف (`BudgetLimitSheet`) — منطقة الميزانيات (`TextsAreaBudgets.kt`). */
internal val MSA_BUDGETS_CATEGORY: Map<UiKey, String> = mapOf(
    UiKey.CAT_BUDGET_PERIOD to "ميزانية {0}، من {1} إلى {2}",
    UiKey.CAT_BUDGET_NA_TITLE to "مصروف هذا التصنيف غير معروف حاليًا",
    UiKey.CAT_BUDGET_NA_BODY to "عمليات هذا الشهر نوعها غير مؤكد، وقد يكون بعضها منه. أكّدها ليظهر الرقم.",
    UiKey.CAT_BUDGET_REVIEW to "راجعها",
    UiKey.CAT_BUDGET_NA_LIMIT to "السقف {0} — بانتظار المراجعة",
    UiKey.CAT_BUDGET_NA_WAIT to "بانتظار المراجعة",
    UiKey.CAT_BUDGET_HERO to "المصروف في {0}",
    UiKey.CAT_BUDGET_CHIP_NO_LIMIT to "بلا سقف",
    UiKey.CAT_BUDGET_CHIP_THRESHOLD to "بلغت نسبة التنبيه",
    UiKey.CAT_BUDGET_OF to "/ {0}",
    UiKey.CAT_BUDGET_TODAY_LINE to "الخط = اليوم، يوم {0} من {1}",
    UiKey.CAT_BUDGET_NO_LIMIT_LINE to "بلا سقف — حدّد سقفًا بالأسفل لتتابع ما بقي منه.",
    UiKey.CAT_BUDGET_PACE_TITLE to "الوتيرة",
    UiKey.CAT_BUDGET_PACE_NONE to "لا مصروف في هذا التصنيف هذا الشهر بعد",
    UiKey.CAT_BUDGET_PACE_USED to "صُرف {0}% ومضى {1}% من الشهر",
    UiKey.CAT_BUDGET_PACE_NO_LIMIT to "بلا سقف، فلا وتيرة مقابل حد",
    UiKey.CAT_BUDGET_PACE_HINT to "حدّد سقفًا لتقارن صرفك بما مضى من الشهر.",
    UiKey.CAT_BUDGET_AVG_NA_NOTE to "يحتاج {0} أشهر مكتملة",
    UiKey.CAT_BUDGET_ANOM_LABEL to "الصرف غير المعتاد",
    UiKey.CAT_BUDGET_ANOM_NONE to "لا صرف بعد",
    UiKey.CAT_BUDGET_LIMIT_TITLE to "السقف والتنبيه",
    UiKey.CAT_BUDGET_SUBS_TITLE to "التصنيفات الفرعية",
    UiKey.CAT_BUDGET_NO_SUBS to "لا تصنيفات فرعية هنا.",
    UiKey.CAT_BUDGET_ADD_SUB to "أضف فرعيًا",
    UiKey.CAT_BUDGET_TX_TITLE to "عمليات {0} ({1})",
    UiKey.CAT_BUDGET_TX_TITLE_EMPTY to "عمليات {0}",
    UiKey.CAT_BUDGET_EMPTY_TITLE to "لا عمليات في {0} هذا الشهر",
    UiKey.CAT_BUDGET_EMPTY_BODY to "تظهر هنا أول عملية فيه، ويبقى السقف كما هو.",
    UiKey.CAT_BUDGET_TX_NOTE to "آخر {0} من {1} عملية — البقية في «العمليات».",
    UiKey.CAT_BUDGET_SAVED_ALERT to "حُفظ السقف {0}، والتنبيه عند {1}%",
    UiKey.CAT_BUDGET_SAVED_NO_ALERT to "حُفظ السقف {0} بلا تنبيه",
    UiKey.CAT_BUDGET_CLEARED to "أُزيل السقف — المصروف يُحسب كما هو",
    UiKey.LIMIT_SHEET_TITLE to "سقف {0}",
    UiKey.LIMIT_SHEET_SPENT to "المصروف حتى الآن {0}",
    UiKey.LIMIT_SHEET_AVG to "متوسطك {0} — معلومة وليس سقفًا",
    UiKey.LIMIT_SHEET_AVG_NA to "المتوسط غير متاح بعد — يحتاج {0} أشهر مكتملة",
    UiKey.LIMIT_SHEET_LABEL to "السقف الشهري",
    UiKey.LIMIT_SHEET_USE_AVG to "استخدم المتوسط {0}",
    UiKey.LIMIT_SHEET_ALERT to "التنبيه",
    UiKey.LIMIT_SHEET_ALERT_ON to "يصلك إشعار عند بلوغ هذه النسبة",
    UiKey.LIMIT_SHEET_ALERT_OFF to "لن يصلك إشعار لهذا السقف",
    UiKey.LIMIT_SHEET_PCT to "نسبة التنبيه",
    UiKey.LIMIT_SHEET_OTHER to "أخرى",
    UiKey.LIMIT_SHEET_OTHER_ARIA to "نسبة أخرى",
    UiKey.LIMIT_SHEET_SAVE to "احفظ",
    UiKey.LIMIT_SHEET_CLEAR to "إزالة السقف",
    UiKey.LIMIT_SHEET_EDIT to "عدّل السقف",
    UiKey.LIMIT_SHEET_NOTE_SET to "السقف {0}، التنبيه عند {1}%",
    UiKey.LIMIT_SHEET_NOTE_OFF to "السقف {0}، التنبيه متوقف",
    UiKey.LIMIT_SHEET_NOTE_NONE to "بلا سقف — المصروف يُحسب على أي حال",
    UiKey.LIMIT_SHEET_PERCENT to "{0}%",
)

internal val EGYPTIAN_BUDGETS_CATEGORY: Map<UiKey, String> = mapOf(
    UiKey.CAT_BUDGET_PERIOD to "ميزانية {0}، من {1} لـ{2}",
    UiKey.CAT_BUDGET_NA_TITLE to "مصروف التصنيف ده مش معروف دلوقتي",
    UiKey.CAT_BUDGET_NA_BODY to "عمليات الشهر ده نوعها لسه مش أكيد، وممكن يكون منها فيه. أكّدها والرقم يرجع.",
    UiKey.CAT_BUDGET_REVIEW to "راجعها",
    UiKey.CAT_BUDGET_NA_LIMIT to "السقف {0} — مستني المراجعة",
    UiKey.CAT_BUDGET_NA_WAIT to "مستني المراجعة",
    UiKey.CAT_BUDGET_HERO to "صرفت في {0}",
    UiKey.CAT_BUDGET_CHIP_NO_LIMIT to "من غير سقف",
    UiKey.CAT_BUDGET_CHIP_THRESHOLD to "وصلت لنسبة التنبيه",
    UiKey.CAT_BUDGET_OF to "/ {0}",
    UiKey.CAT_BUDGET_TODAY_LINE to "الخط = النهارده، يوم {0} من {1}",
    UiKey.CAT_BUDGET_NO_LIMIT_LINE to "من غير سقف — حدّد سقف تحت عشان تتابع فاضل منه كام.",
    UiKey.CAT_BUDGET_PACE_TITLE to "الوتيرة",
    UiKey.CAT_BUDGET_PACE_NONE to "لسه ما صرفتش حاجة في التصنيف ده الشهر ده",
    UiKey.CAT_BUDGET_PACE_USED to "صرفت {0}% وعدّى {1}% من الشهر",
    UiKey.CAT_BUDGET_PACE_NO_LIMIT to "من غير سقف، فمفيش وتيرة قصاد حد",
    UiKey.CAT_BUDGET_PACE_HINT to "حدّد سقف عشان تقارن صرفك باللي عدّى من الشهر.",
    UiKey.CAT_BUDGET_AVG_NA_NOTE to "محتاج {0} شهور مكتملة",
    UiKey.CAT_BUDGET_ANOM_LABEL to "الصرف غير المعتاد",
    UiKey.CAT_BUDGET_ANOM_NONE to "مفيش صرف لسه",
    UiKey.CAT_BUDGET_LIMIT_TITLE to "السقف والتنبيه",
    UiKey.CAT_BUDGET_SUBS_TITLE to "التصنيفات الفرعية",
    UiKey.CAT_BUDGET_NO_SUBS to "مفيش تصنيفات فرعية هنا.",
    UiKey.CAT_BUDGET_ADD_SUB to "ضيف فرعي",
    UiKey.CAT_BUDGET_TX_TITLE to "عمليات {0} ({1})",
    UiKey.CAT_BUDGET_TX_TITLE_EMPTY to "عمليات {0}",
    UiKey.CAT_BUDGET_EMPTY_TITLE to "مفيش عمليات في {0} الشهر ده",
    UiKey.CAT_BUDGET_EMPTY_BODY to "أول ما تصرف فيه هتلاقي العملية هنا، والسقف بيفضل زي ما هو.",
    UiKey.CAT_BUDGET_TX_NOTE to "آخر {0} من {1} عملية — الباقي في «العمليات».",
    UiKey.CAT_BUDGET_SAVED_ALERT to "اتحفظ السقف {0}، والتنبيه عند {1}%",
    UiKey.CAT_BUDGET_SAVED_NO_ALERT to "اتحفظ السقف {0} من غير تنبيه",
    UiKey.CAT_BUDGET_CLEARED to "اتشال السقف — المصروف بيتحسب زي ما هو",
    UiKey.LIMIT_SHEET_TITLE to "سقف {0}",
    UiKey.LIMIT_SHEET_SPENT to "صرفت لحد دلوقتي {0}",
    UiKey.LIMIT_SHEET_AVG to "متوسطك {0} — معلومة مش سقف",
    UiKey.LIMIT_SHEET_AVG_NA to "المتوسط لسه مش متاح — محتاج {0} شهور مكتملة",
    UiKey.LIMIT_SHEET_LABEL to "السقف في الشهر",
    UiKey.LIMIT_SHEET_USE_AVG to "اكتب المتوسط {0}",
    UiKey.LIMIT_SHEET_ALERT to "التنبيه",
    UiKey.LIMIT_SHEET_ALERT_ON to "هيوصلك إشعار لما توصل للنسبة دي",
    UiKey.LIMIT_SHEET_ALERT_OFF to "مش هيوصلك إشعار للسقف ده",
    UiKey.LIMIT_SHEET_PCT to "نسبة التنبيه",
    UiKey.LIMIT_SHEET_OTHER to "غيرها",
    UiKey.LIMIT_SHEET_OTHER_ARIA to "نسبة تانية",
    UiKey.LIMIT_SHEET_SAVE to "احفظ",
    UiKey.LIMIT_SHEET_CLEAR to "شيل السقف",
    UiKey.LIMIT_SHEET_EDIT to "غيّر السقف",
    UiKey.LIMIT_SHEET_NOTE_SET to "السقف {0}، التنبيه عند {1}%",
    UiKey.LIMIT_SHEET_NOTE_OFF to "السقف {0}، التنبيه مقفول",
    UiKey.LIMIT_SHEET_NOTE_NONE to "من غير سقف — المصروف بيتحسب برضه",
    UiKey.LIMIT_SHEET_PERCENT to "{0}%",
)

internal val ENGLISH_BUDGETS_CATEGORY: Map<UiKey, String> = mapOf(
    UiKey.CAT_BUDGET_PERIOD to "{0} budget, {1} to {2}",
    UiKey.CAT_BUDGET_NA_TITLE to "This category's spending isn't known right now",
    UiKey.CAT_BUDGET_NA_BODY to "This month's operations don't have a confirmed type yet, and some may belong here. Confirm them to see the number.",
    UiKey.CAT_BUDGET_REVIEW to "Review them",
    UiKey.CAT_BUDGET_NA_LIMIT to "Cap {0} — waiting for review",
    UiKey.CAT_BUDGET_NA_WAIT to "Waiting for review",
    UiKey.CAT_BUDGET_HERO to "Spent in {0}",
    UiKey.CAT_BUDGET_CHIP_NO_LIMIT to "No cap",
    UiKey.CAT_BUDGET_CHIP_THRESHOLD to "Alert level reached",
    UiKey.CAT_BUDGET_OF to "/ {0}",
    UiKey.CAT_BUDGET_TODAY_LINE to "Line = today, day {0} of {1}",
    UiKey.CAT_BUDGET_NO_LIMIT_LINE to "No cap — set one below to follow what's left of it.",
    UiKey.CAT_BUDGET_PACE_TITLE to "Pace",
    UiKey.CAT_BUDGET_PACE_NONE to "Nothing spent in this category this month yet",
    UiKey.CAT_BUDGET_PACE_USED to "{0}% spent and {1}% of the month gone",
    UiKey.CAT_BUDGET_PACE_NO_LIMIT to "No cap, so no pace to measure against",
    UiKey.CAT_BUDGET_PACE_HINT to "Set a cap to compare your spending with how much of the month has passed.",
    UiKey.CAT_BUDGET_AVG_NA_NOTE to "Needs {0} complete months",
    UiKey.CAT_BUDGET_ANOM_LABEL to "Unusual spending",
    UiKey.CAT_BUDGET_ANOM_NONE to "Nothing spent yet",
    UiKey.CAT_BUDGET_LIMIT_TITLE to "Cap and alert",
    UiKey.CAT_BUDGET_SUBS_TITLE to "Subcategories",
    UiKey.CAT_BUDGET_NO_SUBS to "No subcategories here.",
    UiKey.CAT_BUDGET_ADD_SUB to "Add a subcategory",
    UiKey.CAT_BUDGET_TX_TITLE to "{0} operations ({1})",
    UiKey.CAT_BUDGET_TX_TITLE_EMPTY to "{0} operations",
    UiKey.CAT_BUDGET_EMPTY_TITLE to "No operations in {0} this month",
    UiKey.CAT_BUDGET_EMPTY_BODY to "The first one will show here, and the cap stays as it is.",
    UiKey.CAT_BUDGET_TX_NOTE to "Last {0} of {1} operations — the rest are in “Operations”.",
    UiKey.CAT_BUDGET_SAVED_ALERT to "Cap {0} saved, alert at {1}%",
    UiKey.CAT_BUDGET_SAVED_NO_ALERT to "Cap {0} saved without an alert",
    UiKey.CAT_BUDGET_CLEARED to "Cap removed — spending is still counted",
    UiKey.LIMIT_SHEET_TITLE to "{0} cap",
    UiKey.LIMIT_SHEET_SPENT to "Spent so far {0}",
    UiKey.LIMIT_SHEET_AVG to "Your average {0} — information, not a cap",
    UiKey.LIMIT_SHEET_AVG_NA to "The average isn't available yet — it needs {0} complete months",
    UiKey.LIMIT_SHEET_LABEL to "Monthly cap",
    UiKey.LIMIT_SHEET_USE_AVG to "Use the average {0}",
    UiKey.LIMIT_SHEET_ALERT to "Alert",
    UiKey.LIMIT_SHEET_ALERT_ON to "You'll get a notification at this level",
    UiKey.LIMIT_SHEET_ALERT_OFF to "No notification for this cap",
    UiKey.LIMIT_SHEET_PCT to "Alert level",
    UiKey.LIMIT_SHEET_OTHER to "Other",
    UiKey.LIMIT_SHEET_OTHER_ARIA to "Another level",
    UiKey.LIMIT_SHEET_SAVE to "Save",
    UiKey.LIMIT_SHEET_CLEAR to "Remove the cap",
    UiKey.LIMIT_SHEET_EDIT to "Edit the cap",
    UiKey.LIMIT_SHEET_NOTE_SET to "Cap {0}, alert at {1}%",
    UiKey.LIMIT_SHEET_NOTE_OFF to "Cap {0}, alert off",
    UiKey.LIMIT_SHEET_NOTE_NONE to "No cap — spending is counted either way",
    UiKey.LIMIT_SHEET_PERCENT to "{0}%",
)
