package app.masroufy.core

/** نصوص الواجهة المشتركة **بالمصري** لحساب مصر (OVERRIDES §66) — من النموذج التفاعلي بالحرف (`eg ? …`). الفصحى في `TextsShell.kt`. */
internal val EGYPTIAN_SHELL_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.TAB_HOME to "الرئيسية",
    UiKey.TAB_OPERATIONS to "العمليات",
    UiKey.TAB_PEOPLE to "الأشخاص",
    UiKey.TAB_INVESTMENT to "الاستثمار",
    UiKey.SHELL_NAV to "التنقل",
    UiKey.SHELL_GEAR to "المزيد والإعدادات",
    UiKey.SHELL_BACK to "رجوع",
    UiKey.SHELL_CLOSE to "اقفل",
    UiKey.SHELL_NEW_DOT to "فيه جديد",
    UiKey.SHELL_TAB_WITH_NEW to "{0} — فيه جديد",
    UiKey.SHELL_OFFLINE to "مفيش نت — اللي قدامك محفوظ على الموبايل وممكن ما يكونش الأحدث.",
    UiKey.SHELL_OPENING to "بنجهّز بياناتك…",
    UiKey.SHELL_OPENING_PROGRESS to "{0} من {1}",
    UiKey.SHELL_PENDING_SCREEN to "الشاشة دي لسه بتتبني.",
    UiKey.SHELL_LOADING to "بيحمّل",
    UiKey.SHELL_RETRY to "جرّب تاني",
    UiKey.SHELL_LOAD_FAILED to "ما عرفناش نحمّل.",
    UiKey.BADGE_APPROX to "تقريبي",
    UiKey.GREETING_MORNING_NAME to "صباح الخير يا {0}",
    UiKey.GREETING_EVENING_NAME to "مساء الخير يا {0}",
    UiKey.GREETING_MORNING to "صباح الخير",
    UiKey.GREETING_EVENING to "مساء الخير",
    UiKey.ME_PROFILE to "ملفك",
    UiKey.ME_PROFILE_PERCENT to "ملفك — مكتمل {0}٪",
    UiKey.WEEKDAY_MON to "الاتنين",
    UiKey.WEEKDAY_TUE to "التلات",
    UiKey.WEEKDAY_WED to "الأربع",
    UiKey.WEEKDAY_THU to "الخميس",
    UiKey.WEEKDAY_FRI to "الجمعة",
    UiKey.WEEKDAY_SAT to "السبت",
    UiKey.WEEKDAY_SUN to "الحد",
    UiKey.WEEKDAY_SHORT_MON to "اتنين",
    UiKey.WEEKDAY_SHORT_TUE to "تلات",
    UiKey.WEEKDAY_SHORT_WED to "أربع",
    UiKey.WEEKDAY_SHORT_THU to "خميس",
    UiKey.WEEKDAY_SHORT_FRI to "جمعة",
    UiKey.WEEKDAY_SHORT_SAT to "سبت",
    UiKey.WEEKDAY_SHORT_SUN to "حد",
    UiKey.MONTH_1 to "يناير",
    UiKey.MONTH_2 to "فبراير",
    UiKey.MONTH_3 to "مارس",
    UiKey.MONTH_4 to "أبريل",
    UiKey.MONTH_5 to "مايو",
    UiKey.MONTH_6 to "يونيو",
    UiKey.MONTH_7 to "يوليو",
    UiKey.MONTH_8 to "أغسطس",
    UiKey.MONTH_9 to "سبتمبر",
    UiKey.MONTH_10 to "أكتوبر",
    UiKey.MONTH_11 to "نوفمبر",
    UiKey.MONTH_12 to "ديسمبر",
    UiKey.DATE_DAY_MONTH to "{0} {1}",
    UiKey.DATE_WEEKDAY_DAY_MONTH to "{0}، {1}",
    UiKey.DATE_MONTH_YEAR to "{0} {1}",
    UiKey.ASK_BAR to "اسأل مصروفي أو اطلب منه أي حاجة…",
    UiKey.ASK_MIC to "ضيف بصوتك",
    UiKey.ASK_TITLE to "مصروفي",
    UiKey.ASK_BRAND_TITLE to "مساعدك المالي الذكي",
    UiKey.ASK_DIALOG to "محادثة مع {0}",
    UiKey.ASK_HISTORY to "سجل المحادثات",
    UiKey.ASK_NEW to "محادثة جديدة",
    UiKey.ASK_NEW_STARTED to "بدأنا محادثة جديدة — اللي فاتت في السجل",
    UiKey.ASK_INTRO to "أنا {0}، {1}. اسألني عن فلوسك، أو قولّي أسجّل مصروف أو أقسّم فاتورة.",
    UiKey.ASK_TODO_TITLE to "حاجات لسه ما عملتهاش",
    UiKey.ASK_TODO_NOT_READY to "لسه مش متاح — القايمة دي لسه ما اتربطتش ببياناتك في النسخة دي.",
    UiKey.ASK_TODO_BASIS to "من رسايل البنك والفواتير اللي بتتكرر والميزانيات والديون.",
    UiKey.ASK_INPUT_HINT to "اكتب سؤالك أو اطلب أي حاجة…",
    UiKey.ASK_INPUT_LABEL to "رسالتك لـ{0}",
    UiKey.ASK_SEND to "ابعت",
    UiKey.ASK_TALK to "اتكلّم",
    UiKey.ASK_CLOSE to "اقفل المحادثة",
    UiKey.ASK_CHIPS_FOR to "اقتراحات لصفحة «{0}»",
    UiKey.ASK_NOT_READY to "المساعد لسه مش متاح — محتاج خدمة ذكاء اصطناعي ما اتحددش مزوّدها. تقدر تشوف بياناتك من التبويبات.",
    UiKey.ASK_VOICE_NOT_READY to "الإضافة بالصوت لسه مش متاحة.",
    UiKey.ASK_CHIP_SPENT to "صرفت كام الشهر ده؟",
    UiKey.ASK_CHIP_VOICE to "ضيف عملية بصوتي",
    UiKey.ASK_CHIP_SPLIT to "قسّم فاتورة مع صحابي",
    UiKey.ASK_CHIP_PLAN to "أنا ماشي على الخطة؟",
    UiKey.ASK_CHIP_OWED to "ليّا كام عند الناس؟",
    UiKey.ASK_CHIP_LOCK to "فين أغيّر القفل؟",
    UiKey.ASK_TYPING to "مصروفي بيكتب",
    UiKey.ASK_LISTENING to "بسمعك…",
    UiKey.ASK_HISTORY_CLOSE to "اقفل السجل",
    UiKey.ASK_HISTORY_SEARCH to "دوّر في محادثاتك",
    UiKey.ASK_HISTORY_TODAY to "النهارده",
    UiKey.ASK_HISTORY_CURRENT to "الحالية",
    UiKey.ASK_HISTORY_EMPTY to "لسه مفيش محادثات.",
    UiKey.ASK_HISTORY_NO_MATCH to "مفيش محادثات بالبحث ده.",
    UiKey.ASK_HISTORY_DELETE to "امسح «{0}»",
    UiKey.ASK_HISTORY_DELETED to "اتمسحت «{0}»",
    UiKey.ASK_HISTORY_UNDO to "رجّعها",
    UiKey.ADD_LABEL to "ضيف عملية",
    UiKey.ADD_TITLE to "عملية جديدة",
    UiKey.ADD_VOICE to "بصوتك",
    UiKey.ADD_KIND_TABS to "نوع العملية",
    UiKey.ADD_TYPE_OUT to "صرف",
    UiKey.ADD_TYPE_IN to "دخل",
    UiKey.ADD_TYPE_MOVE to "تحويل",
    UiKey.ADD_AMOUNT to "المبلغ",
    UiKey.ADD_CATEGORY to "التصنيف",
    UiKey.ADD_INCOME_KIND to "النوع",
    UiKey.ADD_FROM to "منين؟",
    UiKey.ADD_TO to "لفين؟",
    UiKey.ADD_SAVE to "سجّل",
    UiKey.ADD_SAVING to "بيتسجّل…",
    UiKey.ADD_SAVED to "اتسجّلت: {0}",
    UiKey.ADD_NO_WALLET to "ضيف محفظة الأول من «المزيد ← المحافظ».",
    UiKey.ADD_AMOUNT_INVALID to "اكتب مبلغ أكبر من صفر.",
    UiKey.BELL_TITLE to "الإشعارات",
    UiKey.BELL_LABEL_NEW to "الإشعارات — فيه جديد",
    UiKey.BELL_NEW_COUNT to "{0} جديد",
    UiKey.BELL_ALL_READ to "كله مقروء",
    UiKey.BELL_MARK_READ to "علّم الكل مقروء",
    UiKey.BELL_ALL to "كل الإشعارات",
    UiKey.BELL_EMPTY to "مفيش إشعارات دلوقتي.",
    UiKey.BELL_CLOSE to "اقفل الإشعارات",
    UiKey.SPACE_SWITCH_TITLE to "بدّل البلد",
    UiKey.SPACE_SWITCH_BODY to "كل بلد ليها حساب لوحدها بمحافظها وأرقامها وعملتها. التبديل على الموبايل ده بس، ومش بيغيّر حاجة في بياناتك.",
    UiKey.SPACE_ACTIVE to "الحالية",
    UiKey.SPACE_WITH_YOU to "معاك دلوقتي",
    UiKey.SPACE_OPENING to "بيفتح…",
    UiKey.SPACE_SHARED_NOTE to "مشترك بين البلاد: ملفك ويوم المرتب والأشخاص والتجار والوسوم.",
    UiKey.SPACE_MANAGE to "إدارة البلاد",
    UiKey.SPACE_TRIGGER to "البلد: {0} — دوس عشان تبدّل",
    UiKey.SPACE_SWITCHED to "بقيت في حساب {0}",
    UiKey.SPACE_SUB to "{0}، {1}",
    UiKey.CURRENCY_NAME_SAR to "ريال سعودي",
    UiKey.CURRENCY_NAME_EGP to "جنيه مصري",
    UiKey.HERO_WITH_YOU to "معاك دلوقتي",
    UiKey.HERO_CASH_CHIP to "منهم {0} كاش",
    UiKey.HERO_BANKS_TITLE to "معاك دلوقتي فين؟",
    UiKey.HERO_BANKS_LABEL to "البنوك اللي في «معاك دلوقتي»: {0}",
    UiKey.HERO_BANK_SUB to "حساب بنك",
    UiKey.HERO_DIGITAL_SUB to "محفظة إلكترونية",
    UiKey.HERO_CASH_SUB to "اللي في جيبك",
    UiKey.HERO_LOGO_NOTE to "لوجو كل بنك هيتحط مكان الحرف بعد ما بحث اللوجوهات يتعتمد.",
    UiKey.HERO_NA_LINE to "رصيد محفظة لسه مش متاح — بيبدأ من يوم ما اتفتحت في التطبيق.",
)
