package app.masroufy.core

/** «العمليات» بالإنجليزي — الجزء التاني: «اربطها بـ» (شخص · مشروع أو حدث) · صفحة التاجر. */
internal val ENGLISH_OPERATIONS_LINK_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.LINK_PERSON_CARD to "Person",
    UiKey.LINK_PERSON_SUB to "Split it with someone: a debt they owe or a gift",
    UiKey.LINK_PERSON_SUB_MORE to "You can split it with someone else",
    UiKey.LINK_PERSON_LOCKED to "A transfer between your countries — can't be linked to a person.",
    UiKey.LINK_PERSON_TRANSFER_SOON to "Linking a transfer to a person (loan, support or repayment) isn't available yet.",
    UiKey.LINK_PERSON_OPEN to "Link",
    UiKey.LINK_PERSON_ANOTHER to "Someone else",
    UiKey.LINK_PERSON_LINE to "{0} — {1}",
    UiKey.LINK_PERSON_KIND_RECEIVABLE to "A debt they owe",
    UiKey.LINK_PERSON_KIND_GIFT to "A gift",
    UiKey.LINK_PERSON_TITLE to "Link to a person",
    UiKey.LINK_PERSON_WHO to "Who?",
    UiKey.LINK_PERSON_SEARCH to "Search or type a new name",
    UiKey.LINK_PERSON_ADD_NEW to "+ Add “{0}”",
    UiKey.LINK_PERSON_WILL_ADD to "Will be added to your people with this name.",
    UiKey.LINK_PERSON_OWES_YOU to "They owe you {0}",
    UiKey.LINK_PERSON_YOU_OWE to "You owe them {0}",
    UiKey.LINK_PERSON_CUSTODY to "You hold {0} for them",
    UiKey.LINK_PERSON_NO_BALANCE to "No balance between you",
    UiKey.LINK_PERSON_KIND to "Link type",
    UiKey.LINK_PERSON_NOTE_RECEIVABLE to "You paid for them; it's recorded as a debt they owe you.",
    UiKey.LINK_PERSON_NOTE_GIFT to "A gift that won't come back — it stays in your spending and shows in their record.",
    UiKey.LINK_PERSON_NOTE_NONE to "Pick the type to see its effect below.",
    UiKey.LINK_PERSON_AMOUNT to "Their share of the operation",
    UiKey.LINK_PERSON_EFFECT_TITLE to "Effect on your numbers",
    UiKey.LINK_PERSON_EFFECT_SPEND to "Your spending on this operation",
    UiKey.LINK_PERSON_EFFECT_OWES to "{0} owes you",
    UiKey.LINK_PERSON_EFFECT_DEBT_ON to "Debt on {0}",
    UiKey.LINK_PERSON_SAME to "No change",
    UiKey.LINK_PERSON_NOTHING to "Nothing",
    UiKey.LINK_PERSON_PICK_BOTH to "Pick the person and type",
    UiKey.LINK_PERSON_PICK_KIND to "Pick the type",
    UiKey.LINK_PERSON_WRITE_AMOUNT to "Enter the amount",
    UiKey.LINK_PERSON_EFFECT_HERE to "to see the effect here",
    UiKey.LINK_PERSON_ERR_PERSON to "Pick the person or type a new name.",
    UiKey.LINK_PERSON_ERR_KIND to "Choose: a debt they owe or a gift.",
    UiKey.LINK_PERSON_ERR_AMOUNT to "Enter an amount above zero.",
    UiKey.LINK_PERSON_SAVE to "Save link",
    UiKey.LINK_PROJECT_EVENT_CARD to "Project or event",
    UiKey.LINK_PROJECT_EVENT_SUB_NONE to "Not linked yet",
    UiKey.LINK_PROJECT_EVENT_SUB_TAGS to "Labels on the operation — they don't change any total.",
    UiKey.LINK_PROJECT_EVENT_LOCKED to "A transfer between your countries — can't be linked to a project or event.",
    UiKey.LINK_PROJECT_EVENT_PROJECT_TAG to "Project:",
    UiKey.LINK_PROJECT_EVENT_EVENT_TAG to "Event:",
    UiKey.LINK_PROJECT_EVENT_NAME_SHARE to "{0}, {1}",
    UiKey.LINK_PROJECT_EVENT_PERCENT to "{0}%",
    UiKey.LINK_PROJECT_EVENT_PERCENT_SIGN to "%",
    UiKey.LINK_PROJECT_EVENT_TITLE to "Link to a project or event",
    UiKey.LINK_PROJECT_EVENT_PROJECTS to "Projects",
    UiKey.LINK_PROJECT_EVENT_PROJECTS_HINT to "More than one project is fine; each counts it once.",
    UiKey.LINK_PROJECT_EVENT_NO_PROJECTS to "No projects yet — add them from Projects.",
    UiKey.LINK_PROJECT_EVENT_EVENT to "Event",
    UiKey.LINK_PROJECT_EVENT_EVENT_HINT to "Only one event per operation, with a share of its amount.",
    UiKey.LINK_PROJECT_EVENT_EVENT_HINT_IN to "Money in is linked to an event as a gift — from the event page, “Record gifts”.",
    UiKey.LINK_PROJECT_EVENT_NONE to "No event",
    UiKey.LINK_PROJECT_EVENT_HOSTED to "{0}'s event",
    UiKey.LINK_PROJECT_EVENT_MINE to "Your event",
    UiKey.LINK_PROJECT_EVENT_WHEN to "{0}, {1}",
    UiKey.LINK_PROJECT_EVENT_NOW_LINKED to ", linked now",
    UiKey.LINK_PROJECT_EVENT_NOT_ON_ANY to "The operation isn't on any event.",
    UiKey.LINK_PROJECT_EVENT_CONFLICT_TITLE to "Already linked to “{0}”",
    UiKey.LINK_PROJECT_EVENT_CONFLICT_BODY to "An operation links to one event only. Unlink it first, then link it to “{0}”.",
    UiKey.LINK_PROJECT_EVENT_UNLINK to "Unlink from “{0}”",
    UiKey.LINK_PROJECT_EVENT_SHARE to "Event's share of the operation",
    UiKey.LINK_PROJECT_EVENT_RANGE to "Share from {0} to {1}",
    UiKey.LINK_PROJECT_EVENT_ON to "On “{0}”",
    UiKey.LINK_PROJECT_EVENT_OUTSIDE to "Rest outside the event",
    UiKey.LINK_PROJECT_EVENT_NOTE to "The link is a label — it doesn't change this month's spending or the category, and the share is saved with it.",
    UiKey.LINK_PROJECT_EVENT_SAVE to "Save",
    UiKey.LINK_PROJECT_EVENT_ERR_PENDING to "Unlink the old event first, or pick the same event.",
    UiKey.LINK_PROJECT_EVENT_ERR_SHARE to "The event's share must be between 1 and 100.",
    UiKey.MERCHANT_PROFILE_TITLE to "Merchant page",
    UiKey.MERCHANT_PROFILE_IN_PERIOD to "{0} in {1}",
    UiKey.MERCHANT_PROFILE_RENAME to "Rename",
    UiKey.MERCHANT_PROFILE_SPENT_PERIOD to "Spent there in {0}",
    UiKey.MERCHANT_PROFILE_SPENT_ALL to "Since the first operation",
    UiKey.MERCHANT_PROFILE_CATEGORY_IN to "Its category in {0}",
    UiKey.MERCHANT_PROFILE_HINT_SAVED to "Applied to its next operations before any rule, in {0} only.",
    UiKey.MERCHANT_PROFILE_HINT_SUGGESTED to "From a general rule — pick its category once and it's saved for good.",
    UiKey.MERCHANT_PROFILE_HINT_OTHER_COUNTRY to "That's its category in your other country — a suggestion; confirm it if right.",
    UiKey.MERCHANT_PROFILE_NOT_SAVED to "This store isn't saved yet, so its category and name can't be changed here.",
    UiKey.MERCHANT_PROFILE_CATEGORY_BODY to "Your choice is saved for this merchant for good.",
    UiKey.MERCHANT_PROFILE_ALIASES to "Other names in statements",
    UiKey.MERCHANT_PROFILE_ALIAS_HINT to "As it appears in the bank message",
    UiKey.MERCHANT_PROFILE_ALIAS_NOTE to "When any of these names shows up in a message or statement, the operation goes to this merchant.",
    UiKey.MERCHANT_PROFILE_ALIAS_ADDED to "Added — any operation with this name goes to this merchant",
    UiKey.MERCHANT_PROFILE_ALIAS_EXISTS to "That name already exists",
    UiKey.MERCHANT_PROFILE_LIST to "Its operations",
    UiKey.MERCHANT_PROFILE_NONE_PERIOD to "No operations in {0}.",
    UiKey.MERCHANT_PROFILE_RENAME_TITLE to "Rename merchant",
    UiKey.MERCHANT_PROFILE_RENAME_BODY to "Only you see this name; matching statements still uses the original name.",
    UiKey.MERCHANT_PROFILE_RENAMED to "Name saved",
)
