package app.masroufy.core

/** منطقة «الأشخاص» بالإنجليزي (كتابة Claude — مستنية مراجعة المالك §40) — المناسبات · الأحداث · التجهيزات · ربط المصروف · النقوط · المشاريع. */
internal val ENGLISH_PEOPLE_AREA_2: Map<TextKey, String> = mapOf(
    // ── Occasion
    TextKey.OCC_ADD to "+ Add an occasion",
    TextKey.OCC_ADD_FOR to "+ Add an occasion for {0}",
    TextKey.OCC_CHIP_BIRTHDAY to "Birthday",
    TextKey.OCC_CHIP_ANNIV to "Anniversary",
    TextKey.OCC_CHIP_WEDDING to "Wedding",
    TextKey.OCC_CHIP_OTHER to "Other",
    TextKey.OCC_CHIP_DAY to "1 day",
    TextKey.OCC_CHIP_WEEK to "1 week",
    TextKey.OCC_CHIP_TWO_WEEKS to "2 weeks",
    TextKey.OCC_CHIP_MONTH to "1 month",
    TextKey.OCC_EDIT to "Edit",
    TextKey.OCC_LABEL_PH to "Its name, e.g. graduation",
    TextKey.OCC_LEAD_DAYS to "{0} before",
    TextKey.OCC_LEAD_LABEL to "When should we remind you?",
    TextKey.OCC_LEAD_MONTH to "a month before",
    TextKey.OCC_LEAD_ONE to "a day before",
    TextKey.OCC_LEAD_TWO to "2 days before",
    TextKey.OCC_LEAD_TWO_WEEKS to "2 weeks before",
    TextKey.OCC_LEAD_WEEK to "a week before",
    TextKey.OCC_LESS to "One day less",
    TextKey.OCC_MORE to "One more day",
    TextKey.OCC_NEED_DAY to "Enter the day (1 to 31).",
    TextKey.OCC_NEED_LABEL to "Enter the occasion's name.",
    TextKey.OCC_NEED_MONTH to "Pick the month.",
    TextKey.OCC_NEXT to "Next: {0}",
    TextKey.OCC_ONCE to "Once",
    TextKey.OCC_YEARLY to "Every year",
    TextKey.OCC_PAST to "This date has passed — a one-time occasion won't repeat.",
    TextKey.OCC_PICK to "Pick the month and day.",
    TextKey.OCC_REMIND_NOW to "Within the reminder window — it shows in alerts right away.",
    TextKey.OCC_REMIND_PLAIN to "The reminder reaches you at your usual time.",
    TextKey.OCC_REMIND_PREFIX to "Reminder: {0}",
    TextKey.OCC_REMIND_USUAL to "The reminder reaches you at your usual time, {0}.",
    TextKey.OCC_REMOVE to "Delete occasion",
    TextKey.OCC_REMOVE_CONFIRM to "Tap again to delete",
    TextKey.OCC_SAVE_NEW to "Add",
    TextKey.OCC_TITLE_EDIT to "Edit occasion",
    TextKey.OCC_TITLE_FOR to "An occasion for {0}",
    TextKey.OCC_TITLE_OWN to "Your occasion",
    // ── Events
    TextKey.EVENTS_TITLE to "Events",
    TextKey.EVENTS_NEW to "New event",
    TextKey.EVENTS_ACTIVE to "Active ({0})",
    TextKey.EVENTS_ARCHIVED to "Archived ({0})",
    TextKey.EVENTS_EMPTY_TITLE to "No events yet",
    TextKey.EVENTS_EMPTY_BODY to "Add a wedding, a trip or an occasion to gather its spending and gifts.",
    TextKey.EVENTS_GAVE to "What you gave",
    TextKey.EVENTS_GAVE_CONDOLENCE to "What you gave",
    TextKey.EVENTS_GIFTS_IN to "Gifts you received",
    TextKey.EVENTS_NEXT to "Next event",
    TextKey.EVENTS_NOT_LINKED to "Nothing linked yet",
    TextKey.EVENTS_NOT_YET to "Not yet",
    TextKey.EVENTS_OTHER_OWNER to "Someone else's",
    TextKey.EVENTS_SPEND to "Spending",
    // ── Event page
    TextKey.EVENT_DETAIL_GIFTS_NONE to "Nothing yet",
    TextKey.EVENT_DETAIL_HOST to "Host: {0}",
    TextKey.EVENT_DETAIL_NOTE_MINE to "Gifts are for information only — not subtracted from spending.",
    TextKey.EVENT_DETAIL_NOTE_OTHER to "{0}'s event — gifts they received don't show here, only what you gave.",
    TextKey.EVENT_DETAIL_NO_GIFTS_MINE to "No gifts recorded yet.",
    TextKey.EVENT_DETAIL_NO_GIFTS_OTHER to "You haven't recorded anything yet.",
    TextKey.EVENT_DETAIL_NO_PREP_CONDOLENCE to "No preparations for condolences.",
    TextKey.EVENT_DETAIL_NO_PREP_PAST to "Preparations are for upcoming events only.",
    TextKey.EVENT_DETAIL_NO_SPEND to "No spending linked to this event yet.",
    TextKey.EVENT_DETAIL_PREP to "Preparations",
    TextKey.EVENT_DETAIL_PREP_DONE to "{0} done",
    TextKey.EVENT_DETAIL_PREP_NONE_DONE to "None done yet",
    TextKey.EVENT_DETAIL_REMIND to "Remind me every year",
    TextKey.EVENT_DETAIL_REMIND_WEDDING to "Remind me of the anniversary every year",
    TextKey.EVENT_DETAIL_REMIND_OFF to "Reminder turned off",
    TextKey.EVENT_DETAIL_REMIND_ON to "We'll remind you {0} every year",
    TextKey.EVENT_DETAIL_REMIND_SUB to "{0} — for a gift or a celebration",
    TextKey.EVENT_DETAIL_SHARE_OF to "{0}% of {1}",
    TextKey.EVENT_DETAIL_SPEND to "Spent on it",
    TextKey.EVENT_DETAIL_SPEND_TITLE to "Spending",
    TextKey.EVENT_DETAIL_WHOLE to "Whole transaction",
    // ── Add / edit event
    TextKey.EVENT_FORM_ADD to "Add",
    TextKey.EVENT_FORM_ADDED to "“{0}” added",
    TextKey.EVENT_FORM_ARCHIVED_SUB to "Hidden from active; its transactions and gifts stay — nothing is deleted.",
    TextKey.EVENT_FORM_DATE_NOTE to "Shows in the calendar on its day, with a reminder before.",
    TextKey.EVENT_FORM_EDIT_OPEN to "Edit event",
    TextKey.EVENT_FORM_EDIT_TITLE to "Edit event",
    TextKey.EVENT_FORM_HINT to "No amount for now — preparations, amounts and gifts are on the event page.",
    TextKey.EVENT_FORM_HOST_NOTE to "{0}'s event: only what you gave shows, not gifts they received.",
    TextKey.EVENT_FORM_KIND to "Type",
    TextKey.EVENT_FORM_LOCK_MINE to "It has gifts you received — it stays your event, since gifts you receive are recorded on your own events only.",
    TextKey.EVENT_FORM_ME to "Mine",
    TextKey.EVENT_FORM_NAME to "Event name",
    TextKey.EVENT_FORM_NAME_PH to "e.g. Youssef's engagement",
    TextKey.EVENT_FORM_NEED_NAME to "Enter the event's name.",
    TextKey.EVENT_FORM_NEW to "New event",
    TextKey.EVENT_FORM_SCHOOL_NOTE to "You add the school start as an event — not from an official calendar.",
    TextKey.EVENT_FORM_WHEN to "When?",
    TextKey.EVENT_FORM_WHO to "Whose event?",
    // ── Preparations
    TextKey.EVENT_PREP_TITLE to "Preparing {0}",
    TextKey.EVENT_PREP_ADD to "Add",
    TextKey.EVENT_PREP_ALL_DONE to "All items done ✓",
    TextKey.EVENT_PREP_ALL_PRICED to "Every item has an amount",
    TextKey.EVENT_PREP_AMOUNT_ERR to "The amount must be above zero — or leave it without one.",
    TextKey.EVENT_PREP_ASSIGN to "Put it on:",
    TextKey.EVENT_PREP_ASSIGNED to "Put on “{0}”",
    TextKey.EVENT_PREP_BLOCK_CONDOLENCE_TITLE to "No preparations for condolences",
    TextKey.EVENT_PREP_BLOCK_CONDOLENCE_BODY to "Its spending and what you gave are on the event page.",
    TextKey.EVENT_PREP_BLOCK_PAST_TITLE to "This event is over",
    TextKey.EVENT_PREP_DONE_LABEL to "Done: {0}",
    TextKey.EVENT_PREP_ITEMS to "Items ({0})",
    TextKey.EVENT_PREP_LEFT to "{0} left",
    TextKey.EVENT_PREP_LOOSE_LINE to "Not on an item: {0}",
    TextKey.EVENT_PREP_LOOSE_TITLE to "Spending not on an item",
    TextKey.EVENT_PREP_NEW to "New item",
    TextKey.EVENT_PREP_NOT_SPENT to "Nothing spent yet",
    TextKey.EVENT_PREP_NO_AMOUNT to "No amount",
    TextKey.EVENT_PREP_NO_ITEMS to "No items yet",
    TextKey.EVENT_PREP_NO_PRICED to "No item has an amount",
    TextKey.EVENT_PREP_OTHER_CURRENCY to "{0} in another currency, not in the total",
    TextKey.EVENT_PREP_OVER to "over",
    TextKey.EVENT_PREP_PLANNED to "Planned",
    TextKey.EVENT_PREP_PLANNED_INPUT to "Planned amount",
    TextKey.EVENT_PREP_PLANNED_OF to "Planned {0}",
    TextKey.EVENT_PREP_REMOVE to "Remove item",
    TextKey.EVENT_PREP_REMOVED to "Item removed",
    TextKey.EVENT_PREP_REMOVED_SPENT to "Item removed — its spending stays on the event without an item",
    TextKey.EVENT_PREP_SPENT to "Spent",
    TextKey.EVENT_PREP_SPENT_OF to "Spent {0}",
    TextKey.EVENT_PREP_SUG_TITLE to "Suggested items",
    TextKey.EVENT_PREP_SUG_BODY to "Pick what fits — no amounts; you can add an amount later if you like.",
    TextKey.EVENT_PREP_SUG_PICK to "Pick at least one item",
    TextKey.EVENT_PREP_SUG_SAVE to "Save {0}",
    TextKey.EVENT_PREP_SUG_SAVED to "Saved {0} without amounts",
    TextKey.EVENT_PREP_UNPRICED to "+ {0} without an amount",
    // ── Link spending to an event
    TextKey.SPEND_LINK_OPEN to "Link spending by share",
    TextKey.SPEND_LINK_TITLE to "Link spending to “{0}”",
    TextKey.SPEND_LINK_INTRO to "Pick one or more transactions and set the event's share of each.",
    TextKey.SPEND_LINK_SEARCH to "Search by store name or amount",
    TextKey.SPEND_LINK_LIST to "Your recent spending",
    TextKey.SPEND_LINK_HINT to "Last 30 days, newest first. A transaction links to one event only.",
    TextKey.SPEND_LINK_HERE to "Linked to this event",
    TextKey.SPEND_LINK_OTHER_EVENT to "Linked to “{0}” — unlink it from the transaction page first",
    TextKey.SPEND_LINK_NONE to "No spending in the last 30 days.",
    TextKey.SPEND_LINK_NO_MATCH to "No transactions match “{0}”",
    TextKey.SPEND_LINK_PART to "The event's share; the rest stays as usual",
    TextKey.SPEND_LINK_WHOLE to "The whole transaction on the event",
    TextKey.SPEND_LINK_RANGE to "Share from 1 to 100",
    TextKey.SPEND_LINK_TAG_NOTE to "Linking tags the transaction — it doesn't change the month's spending or its category; the share is saved with the link.",
    TextKey.SPEND_LINK_TOTAL to "Added to the event's spending",
    TextKey.SPEND_LINK_NOT_PICKED to "Nothing picked yet",
    TextKey.SPEND_LINK_PICK_HINT to "Pick a transaction from the list.",
    TextKey.SPEND_LINK_EACH to "{0} — each with its own share.",
    TextKey.SPEND_LINK_BAD_PCT_SUB to "A share is outside 1–100.",
    TextKey.SPEND_LINK_SAVE to "Link {0}",
    TextKey.SPEND_LINK_SAVE_EMPTY to "Link to event",
    TextKey.SPEND_LINK_NEED_ONE to "Pick at least one transaction.",
    TextKey.SPEND_LINK_NEED_PCT to "Each transaction's share must be from 1 to 100.",
    TextKey.SPEND_LINK_DONE to "Linked {0} to “{1}” — {2} added to its spending",
    // ── Gifts (nuqoot)
    TextKey.NUQOOT_OPEN_MINE to "Record gifts you received",
    TextKey.NUQOOT_OPEN_OTHER to "Record {0}",
    TextKey.NUQOOT_MODE_CASH to "Cash gifts",
    TextKey.NUQOOT_MODE_LINK to "Existing transaction",
    TextKey.NUQOOT_WALLET to "Which wallet?",
    TextKey.NUQOOT_ROWS to "An amount for each name",
    TextKey.NUQOOT_NAME to "Name",
    TextKey.NUQOOT_ADD_ROW to "+ Another name",
    TextKey.NUQOOT_SUM to "Total {0}, {1} in “{2}”",
    TextKey.NUQOOT_EACH to "Each name becomes its own transaction in the wallet.",
    TextKey.NUQOOT_KIND_NOTE to "Categorized as “Gifts › Nuqoot” automatically; you won't be asked about them in reviews.",
    TextKey.NUQOOT_SAVE to "Record",
    TextKey.NUQOOT_SAVE_N to "Record {0}",
    TextKey.NUQOOT_SAVE_LINK to "Link as a gift",
    TextKey.NUQOOT_NEED_ONE to "Add at least one gift with an amount above zero.",
    TextKey.NUQOOT_FILL_ROWS to "Fill in the name and amount on every row.",
    TextKey.NUQOOT_DUP to "The same name is repeated — one gift per name.",
    TextKey.NUQOOT_NEED_TXN to "Pick the transaction first.",
    TextKey.NUQOOT_NEED_WHO to "Pick the person.",
    TextKey.NUQOOT_NO_CANDIDATES to "No suitable transactions in the last 30 days.",
    TextKey.NUQOOT_NO_WALLET to "Add a wallet first.",
    TextKey.NUQOOT_LINKED to "Transaction linked as a gift",
    TextKey.NUQOOT_DONE to "Recorded {0} — one transaction per name in “{1}”",
    // ── Projects
    TextKey.PROJECTS_TITLE to "Projects",
    TextKey.PROJECTS_NEW to "New project",
    TextKey.PROJECTS_INTRO to "A project is an extra tag: the transaction keeps its category and no overall total changes.",
    TextKey.PROJECTS_EMPTY_TITLE to "No projects yet",
    TextKey.PROJECTS_EMPTY_BODY to "A trip, a home setup or a side job: create a project to see what it cost or earned you.",
    TextKey.PROJECTS_KIND_PERSONAL to "Personal",
    TextKey.PROJECTS_KIND_WORK to "Work",
    TextKey.PROJECTS_Q_PERSONAL to "What did it cost me?",
    TextKey.PROJECTS_Q_WORK to "What did I earn?",
    TextKey.PROJECTS_LINE to "Spent {0}, received {1}",
    TextKey.PROJECTS_NO_OPS to "No transactions yet",
    TextKey.PROJECTS_NO_DEADLINE to "No deadline",
    TextKey.PROJECTS_PASSED to "Passed",
    TextKey.PROJECTS_APPROX to "Approximate, {0} awaiting type confirmation",
    TextKey.PROJECTS_ARCHIVED to "Archived ({0})",
    TextKey.PROJECTS_RESTORE to "Restore",
    TextKey.PROJECTS_RESTORED to "“{0}” is active again",
    TextKey.PROJECTS_ARCH_NOTE to "Archived projects are closed: their rules are paused, nothing is deleted.",
    TextKey.PROJECTS_ASK_KIND to "Is the project personal or work?",
    TextKey.PROJECTS_EX_PERSONAL to "Wedding, travel, home setup — money received lowers the cost",
    TextKey.PROJECTS_EX_WORK to "A client, part-time, a side job — the net can be negative",
    TextKey.PROJECTS_NAME to "Name",
    TextKey.PROJECTS_NAME_PH to "e.g. Eid trip",
    TextKey.PROJECTS_DEADLINE to "Deadline (optional)",
    TextKey.PROJECTS_DEADLINE_NOTE to "If set, the project shows in the calendar on that day.",
    TextKey.PROJECTS_CREATE to "Create project",
    TextKey.PROJECTS_CREATED to "“{0}” created",
    TextKey.PROJECTS_EDIT_TITLE to "Edit project",
    // ── Project page
    TextKey.PROJECT_DETAIL_EDIT to "Edit name and deadline",
    TextKey.PROJECT_DETAIL_ARCHIVE to "Archive project",
    TextKey.PROJECT_DETAIL_ARCHIVED to "“{0}” archived — nothing deleted",
    TextKey.PROJECT_DETAIL_UNTIL to "Until {0}",
    TextKey.PROJECT_DETAIL_OUT to "Spent (your share)",
    TextKey.PROJECT_DETAIL_IN to "Received",
    TextKey.PROJECT_DETAIL_FORMULA_WORK to "Net = received − spent, and it can be negative.",
    TextKey.PROJECT_DETAIL_FORMULA_PERSONAL to "What you received (gifts or presents) lowers the cost.",
    TextKey.PROJECT_DETAIL_TAB_OPS to "Transactions ({0})",
    TextKey.PROJECT_DETAIL_TAB_RULES to "Rules ({0})",
    TextKey.PROJECT_DETAIL_NO_OPS to "No transactions in the project yet",
    TextKey.PROJECT_DETAIL_SRC_RULE to "By a rule",
    TextKey.PROJECT_DETAIL_SRC_MANUAL to "Added by you",
    TextKey.PROJECT_DETAIL_UNSURE to "Type not confirmed",
    TextKey.PROJECT_DETAIL_REMOVE_OP to "Remove {0} from the project",
    TextKey.PROJECT_DETAIL_ADD_HINT to "To add a transaction yourself: its three dots → “Add to project”. A transaction can be in more than one project.",
    TextKey.PROJECT_DETAIL_RULES_INTRO to "A rule adds new transactions automatically; we ask about older ones when you create it.",
    TextKey.PROJECT_DETAIL_MODE_CONTAINS to "Contains",
    TextKey.PROJECT_DETAIL_MODE_STARTS to "Starts with",
    TextKey.PROJECT_DETAIL_MODE_EXACT to "Exact",
    TextKey.PROJECT_DETAIL_QUOTED to "“{0}”",
    TextKey.PROJECT_DETAIL_DIR to "Direction: {0}",
    TextKey.PROJECT_DETAIL_DIR_OUT to "Outgoing",
    TextKey.PROJECT_DETAIL_DIR_IN to "Incoming",
    TextKey.PROJECT_DETAIL_DIR_ANY to "Both",
    TextKey.PROJECT_DETAIL_RULE_SWITCH to "Turn on rule {0}",
    TextKey.PROJECT_DETAIL_NEW_RULE to "New rule",
    TextKey.PROJECT_DETAIL_RULE_TITLE to "Project rule",
    TextKey.PROJECT_DETAIL_RULE_TEXT to "Text in the merchant name or description",
    TextKey.PROJECT_DETAIL_RULE_PH to "e.g. AlUla",
    TextKey.PROJECT_DETAIL_RULE_ERR to "Rule text must be 2 to 60 characters.",
    TextKey.PROJECT_DETAIL_MODE_LABEL to "Match type",
    TextKey.PROJECT_DETAIL_DIR_LABEL to "Direction",
    TextKey.PROJECT_DETAIL_NEXT to "Next",
    TextKey.PROJECT_DETAIL_OLD_TITLE to "Add older ones too?",
    TextKey.PROJECT_DETAIL_OLD_BODY to "Earlier transactions (last 3 years) that match: {0}",
    TextKey.PROJECT_DETAIL_OLD_NONE to "No earlier transactions match. New ones will be added automatically.",
    TextKey.PROJECT_DETAIL_ADD_OLD to "Yes, add earlier ones too",
    TextKey.PROJECT_DETAIL_NEW_ONLY to "No, new ones only",
    TextKey.PROJECT_DETAIL_OK to "Done",
    TextKey.PROJECT_DETAIL_OLD_ADDED to "Added to the project: {0}",
)
