package app.masroufy.core

/** منطقة «الأشخاص» بالمصري (مصر) — المناسبات · الأحداث · التجهيزات · ربط المصروف · النقوط · المشاريع. */
internal val EGYPTIAN_PEOPLE_AREA_2: Map<UiKey, String> = mapOf(
    // ── المناسبة (OccasionSheet)
    UiKey.OCC_ADD to "+ ضيف مناسبة",
    UiKey.OCC_ADD_FOR to "+ ضيف مناسبة لـ{0}",
    UiKey.OCC_CHIP_BIRTHDAY to "عيد ميلاد",
    UiKey.OCC_CHIP_ANNIV to "عيد جواز",
    UiKey.OCC_CHIP_WEDDING to "فرح",
    UiKey.OCC_CHIP_OTHER to "غيره",
    UiKey.OCC_CHIP_DAY to "بيوم",
    UiKey.OCC_CHIP_WEEK to "بأسبوع",
    UiKey.OCC_CHIP_TWO_WEEKS to "بأسبوعين",
    UiKey.OCC_CHIP_MONTH to "بشهر",
    UiKey.OCC_EDIT to "عدّلها",
    UiKey.OCC_LABEL_PH to "اسمها، مثلًا: تخرّجه",
    UiKey.OCC_LEAD_DAYS to "قبلها بـ{0}",
    UiKey.OCC_LEAD_LABEL to "نفكّرك إمتى؟",
    UiKey.OCC_LEAD_MONTH to "قبلها بشهر",
    UiKey.OCC_LEAD_ONE to "قبلها بيوم",
    UiKey.OCC_LEAD_TWO to "قبلها بيومين",
    UiKey.OCC_LEAD_TWO_WEEKS to "قبلها بأسبوعين",
    UiKey.OCC_LEAD_WEEK to "قبلها بأسبوع",
    UiKey.OCC_LESS to "يوم أقل",
    UiKey.OCC_MORE to "يوم زيادة",
    UiKey.OCC_NEED_DAY to "اكتب اليوم (من 1 لـ31).",
    UiKey.OCC_NEED_LABEL to "اكتب اسم المناسبة.",
    UiKey.OCC_NEED_MONTH to "اختار الشهر.",
    UiKey.OCC_NEXT to "المرة الجاية: {0}",
    UiKey.OCC_ONCE to "مرة واحدة بس",
    UiKey.OCC_YEARLY to "كل سنة",
    UiKey.OCC_PAST to "التاريخ ده فات — ومرة واحدة مش هتتكرر.",
    UiKey.OCC_PICK to "اختار الشهر واليوم.",
    UiKey.OCC_REMIND_NOW to "جوه مدة التذكير — هتظهر في التنبيهات على طول.",
    UiKey.OCC_REMIND_PLAIN to "التذكير بيوصلك في وقتك المعتاد.",
    UiKey.OCC_REMIND_PREFIX to "التذكير {0}",
    UiKey.OCC_REMIND_USUAL to "التذكير بيوصلك في وقتك المعتاد، {0}.",
    UiKey.OCC_REMOVE to "امسح المناسبة",
    UiKey.OCC_REMOVE_CONFIRM to "متأكد؟ اضغط تاني للمسح",
    UiKey.OCC_SAVE_NEW to "ضيفها",
    UiKey.OCC_TITLE_EDIT to "تعديل المناسبة",
    UiKey.OCC_TITLE_FOR to "مناسبة لـ{0}",
    UiKey.OCC_TITLE_OWN to "مناسبة ليك",
    // ── الأحداث (Events)
    UiKey.EVENTS_TITLE to "الأحداث",
    UiKey.EVENTS_NEW to "حدث جديد",
    UiKey.EVENTS_ACTIVE to "الشغالة ({0})",
    UiKey.EVENTS_ARCHIVED to "المتأرشفة ({0})",
    UiKey.EVENTS_EMPTY_TITLE to "مفيش أحداث لسه",
    UiKey.EVENTS_EMPTY_BODY to "ضيف فرح أو سفر أو مناسبة، ونجمعلك مصروفها ونقوطها.",
    UiKey.EVENTS_GAVE to "اللي نقّطته",
    UiKey.EVENTS_GAVE_CONDOLENCE to "اللي ادّيته",
    UiKey.EVENTS_GIFTS_IN to "النقوط اللي جاتلك",
    UiKey.EVENTS_NEXT to "أقرب حدث",
    UiKey.EVENTS_NOT_LINKED to "لسه ما اتربطش",
    UiKey.EVENTS_NOT_YET to "لسه",
    UiKey.EVENTS_OTHER_OWNER to "حدث حد تاني",
    UiKey.EVENTS_SPEND to "المصروف",
    // ── صفحة الحدث (EventDetail)
    UiKey.EVENT_DETAIL_GIFTS_NONE to "لسه مفيش",
    UiKey.EVENT_DETAIL_HOST to "صاحبه: {0}",
    UiKey.EVENT_DETAIL_NOTE_MINE to "النقوط للمعلومية بس — ما بتتطرحش من المصروف.",
    UiKey.EVENT_DETAIL_NOTE_OTHER to "حدث {0} — النقوط اللي جاتله مش بتظهر هنا، بس اللي إنت ادّيته.",
    UiKey.EVENT_DETAIL_NO_GIFTS_MINE to "لسه مفيش نقوط متسجلة.",
    UiKey.EVENT_DETAIL_NO_GIFTS_OTHER to "لسه ما سجّلتش حاجة.",
    UiKey.EVENT_DETAIL_NO_PREP_CONDOLENCE to "العزا مالوش تجهيزات.",
    UiKey.EVENT_DETAIL_NO_PREP_PAST to "التجهيزات للأحداث الجاية بس.",
    UiKey.EVENT_DETAIL_NO_SPEND to "لسه مفيش مصروف متربط بالحدث ده.",
    UiKey.EVENT_DETAIL_PREP to "التجهيزات",
    UiKey.EVENT_DETAIL_PREP_DONE to "خلص {0}",
    UiKey.EVENT_DETAIL_PREP_NONE_DONE to "لسه ولا بند خلص",
    UiKey.EVENT_DETAIL_REMIND to "فكّرني بيه كل سنة",
    UiKey.EVENT_DETAIL_REMIND_WEDDING to "فكّرني بعيد الجواز كل سنة",
    UiKey.EVENT_DETAIL_REMIND_OFF to "التذكير اتقفل",
    UiKey.EVENT_DETAIL_REMIND_ON to "هنفكّرك {0} كل سنة",
    UiKey.EVENT_DETAIL_REMIND_SUB to "{0} — هدية أو احتفال",
    UiKey.EVENT_DETAIL_SHARE_OF to "{0}% من {1}",
    UiKey.EVENT_DETAIL_SPEND to "المصروف عليه",
    UiKey.EVENT_DETAIL_SPEND_TITLE to "المصروف",
    UiKey.EVENT_DETAIL_WHOLE to "العملية كلها",
    // ── إضافة الحدث وتعديله (EventAddSheet · EventEditSheet)
    UiKey.EVENT_FORM_ADD to "ضيفه",
    UiKey.EVENT_FORM_ADDED to "اتضاف «{0}»",
    UiKey.EVENT_FORM_ARCHIVED_SUB to "بيختفي من الشغالة، وعملياته ونقوطه بتفضل — مش بيتمسح.",
    UiKey.EVENT_FORM_DATE_NOTE to "بيظهر في التقويم في اليوم ده، ويفكّرك قبله.",
    UiKey.EVENT_FORM_EDIT_OPEN to "عدّل الحدث",
    UiKey.EVENT_FORM_EDIT_TITLE to "تعديل الحدث",
    UiKey.EVENT_FORM_HINT to "من غير مبلغ دلوقتي — التجهيزات ومبالغها والنقوط من صفحة الحدث.",
    UiKey.EVENT_FORM_HOST_NOTE to "حدث {0}: بيظهر فيه اللي إنت نقّطته بس، مش النقوط اللي جاتله.",
    UiKey.EVENT_FORM_KIND to "نوعه",
    UiKey.EVENT_FORM_LOCK_MINE to "عليه نقوط جاتلك — بيفضل حدثك، لأن النقوط اللي جاتلك بتتسجل في حدثك إنت بس.",
    UiKey.EVENT_FORM_ME to "حدثي أنا",
    UiKey.EVENT_FORM_NAME to "اسمه",
    UiKey.EVENT_FORM_NAME_PH to "مثلًا: خطوبة يوسف",
    UiKey.EVENT_FORM_NEED_NAME to "اكتب اسم الحدث.",
    UiKey.EVENT_FORM_NEW to "حدث جديد",
    UiKey.EVENT_FORM_SCHOOL_NOTE to "بداية الدراسة بتحطها إنت كحدث — مش من تقويم رسمي.",
    UiKey.EVENT_FORM_WHEN to "إمتى؟",
    UiKey.EVENT_FORM_WHO to "حدث مين؟",
    // ── التجهيزات (EventPrep)
    UiKey.EVENT_PREP_TITLE to "تجهيزات {0}",
    UiKey.EVENT_PREP_ADD to "ضيف",
    UiKey.EVENT_PREP_ALL_DONE to "كل البنود خلصت ✓",
    UiKey.EVENT_PREP_ALL_PRICED to "كل البنود ليها مبلغ",
    UiKey.EVENT_PREP_AMOUNT_ERR to "مبلغ البند لازم يبقى أكبر من صفر — أو سيبه من غير مبلغ.",
    UiKey.EVENT_PREP_ASSIGN to "حطّه على:",
    UiKey.EVENT_PREP_ASSIGNED to "اتحط على «{0}»",
    UiKey.EVENT_PREP_BLOCK_CONDOLENCE_TITLE to "العزا مالوش تجهيزات",
    UiKey.EVENT_PREP_BLOCK_CONDOLENCE_BODY to "مصروفه واللي ادّيته في صفحة الحدث.",
    UiKey.EVENT_PREP_BLOCK_PAST_TITLE to "الحدث ده عدّى",
    UiKey.EVENT_PREP_DONE_LABEL to "خلص: {0}",
    UiKey.EVENT_PREP_ITEMS to "البنود ({0})",
    UiKey.EVENT_PREP_LEFT to "فاضل {0}",
    UiKey.EVENT_PREP_LOOSE_LINE to "مش على بند: {0}",
    UiKey.EVENT_PREP_LOOSE_TITLE to "مصروف مش على بند",
    UiKey.EVENT_PREP_NEW to "بند جديد",
    UiKey.EVENT_PREP_NOT_SPENT to "لسه ما اتصرفش",
    UiKey.EVENT_PREP_NO_AMOUNT to "من غير مبلغ",
    UiKey.EVENT_PREP_NO_ITEMS to "مفيش بنود لسه",
    UiKey.EVENT_PREP_NO_PRICED to "ولا بند ليه مبلغ",
    UiKey.EVENT_PREP_OTHER_CURRENCY to "{0} بعملة تانية برّه المجموع",
    UiKey.EVENT_PREP_OVER to "زيادة",
    UiKey.EVENT_PREP_PLANNED to "المخطط",
    UiKey.EVENT_PREP_PLANNED_INPUT to "المبلغ المخطط",
    UiKey.EVENT_PREP_PLANNED_OF to "مخطط {0}",
    UiKey.EVENT_PREP_REMOVE to "شيل البند",
    UiKey.EVENT_PREP_REMOVED to "البند اتشال",
    UiKey.EVENT_PREP_REMOVED_SPENT to "البند اتشال — ومصروفه فضل على الحدث من غير بند",
    UiKey.EVENT_PREP_SPENT to "اتصرف",
    UiKey.EVENT_PREP_SPENT_OF to "اتصرف {0}",
    UiKey.EVENT_PREP_SUG_TITLE to "بنود مقترحة",
    UiKey.EVENT_PREP_SUG_BODY to "اختار اللي يخصك — من غير مبالغ، وإنت تحط المبلغ بعدين لو حبيت.",
    UiKey.EVENT_PREP_SUG_PICK to "اختار بند واحد على الأقل",
    UiKey.EVENT_PREP_SUG_SAVE to "احفظ {0}",
    UiKey.EVENT_PREP_SUG_SAVED to "اتحفظ {0} من غير مبالغ",
    UiKey.EVENT_PREP_UNPRICED to "+ {0} من غير مبلغ",
    // ── ربط مصروف بالحدث (EventSpendLinkSheet)
    UiKey.SPEND_LINK_OPEN to "اربط مصروف بنسبة",
    UiKey.SPEND_LINK_TITLE to "اربط مصروف بـ«{0}»",
    UiKey.SPEND_LINK_INTRO to "اختار عملية أو أكتر، وحدد نصيب الحدث من كل واحدة.",
    UiKey.SPEND_LINK_SEARCH to "دوّر باسم المحل أو المبلغ",
    UiKey.SPEND_LINK_LIST to "مصروفك الأخير",
    UiKey.SPEND_LINK_HINT to "آخر 30 يوم، والأحدث الأول. العملية بتتربط بحدث واحد بس.",
    UiKey.SPEND_LINK_HERE to "مربوطة بالحدث ده",
    UiKey.SPEND_LINK_OTHER_EVENT to "مربوطة بـ«{0}» — فكّها من صفحة العملية الأول",
    UiKey.SPEND_LINK_NONE to "مفيش مصروف في آخر 30 يوم.",
    UiKey.SPEND_LINK_NO_MATCH to "مفيش عمليات فيها «{0}»",
    UiKey.SPEND_LINK_PART to "نصيب الحدث، والباقي بيفضل عادي",
    UiKey.SPEND_LINK_WHOLE to "العملية كلها على الحدث",
    UiKey.SPEND_LINK_RANGE to "النسبة من 1 لـ100",
    UiKey.SPEND_LINK_TAG_NOTE to "الربط علامة على العملية — مش بيغيّر مصروف الشهر ولا تصنيفها، والنسبة بتتحفظ مع الربط.",
    UiKey.SPEND_LINK_TOTAL to "هيتضاف لمصروف الحدث",
    UiKey.SPEND_LINK_NOT_PICKED to "لسه ما اخترتش",
    UiKey.SPEND_LINK_PICK_HINT to "اختار عملية من القايمة.",
    UiKey.SPEND_LINK_EACH to "{0} — كل واحدة بنصيبها.",
    UiKey.SPEND_LINK_BAD_PCT_SUB to "فيه نسبة برّه 1–100.",
    UiKey.SPEND_LINK_SAVE to "اربط {0}",
    UiKey.SPEND_LINK_SAVE_EMPTY to "اربط بالحدث",
    UiKey.SPEND_LINK_NEED_ONE to "اختار عملية واحدة على الأقل.",
    UiKey.SPEND_LINK_NEED_PCT to "نسبة كل عملية لازم تبقى من 1 لـ100.",
    UiKey.SPEND_LINK_DONE to "اتربطت {0} بـ«{1}» — اتضاف {2} لمصروفه",
    // ── النقوط (NuqootSheet)
    UiKey.NUQOOT_OPEN_MINE to "سجّل النقوط اللي جاتلك",
    UiKey.NUQOOT_OPEN_OTHER to "سجّل {0}",
    UiKey.NUQOOT_MODE_CASH to "نقوط كاش",
    UiKey.NUQOOT_MODE_LINK to "عملية موجودة",
    UiKey.NUQOOT_WALLET to "في أنهي محفظة؟",
    UiKey.NUQOOT_ROWS to "لكل اسم مبلغه",
    UiKey.NUQOOT_NAME to "الاسم",
    UiKey.NUQOOT_ADD_ROW to "+ اسم كمان",
    UiKey.NUQOOT_SUM to "المجموع {0}، {1} في «{2}»",
    UiKey.NUQOOT_EACH to "كل اسم بيبقى عملية لوحده في المحفظة.",
    UiKey.NUQOOT_KIND_NOTE to "بتتصنّف «هدايا › نقوط» لوحدها، ومش هتتسأل عنها في المراجعة.",
    UiKey.NUQOOT_SAVE to "سجّل",
    UiKey.NUQOOT_SAVE_N to "سجّل {0}",
    UiKey.NUQOOT_SAVE_LINK to "اربطها نقطة",
    UiKey.NUQOOT_NEED_ONE to "ضيف نقطة واحدة على الأقل بمبلغ أكبر من صفر.",
    UiKey.NUQOOT_FILL_ROWS to "كمّل الاسم والمبلغ في كل سطر.",
    UiKey.NUQOOT_DUP to "نفس الاسم متكرر — كل نقطة لاسم واحد.",
    UiKey.NUQOOT_NEED_TXN to "اختار العملية الأول.",
    UiKey.NUQOOT_NEED_WHO to "اختار الشخص.",
    UiKey.NUQOOT_NO_CANDIDATES to "مفيش عمليات مناسبة في آخر 30 يوم.",
    UiKey.NUQOOT_NO_WALLET to "ضيف محفظة الأول.",
    UiKey.NUQOOT_LINKED to "اتربطت العملية نقطة",
    UiKey.NUQOOT_DONE to "اتسجّلت {0} — عملية لكل اسم في «{1}»",
    // ── المشاريع (Projects)
    UiKey.PROJECTS_TITLE to "المشاريع",
    UiKey.PROJECTS_NEW to "مشروع جديد",
    UiKey.PROJECTS_INTRO to "المشروع علامة زيادة على العملية: تصنيفها زي ما هو، ومفيش مجموع عام بيتغير.",
    UiKey.PROJECTS_EMPTY_TITLE to "مفيش مشاريع",
    UiKey.PROJECTS_EMPTY_BODY to "سفرية أو تجهيز أو شغلانة جنب: اعمل مشروع واعرف كلّفك كام أو كسبت كام.",
    UiKey.PROJECTS_KIND_PERSONAL to "شخصي",
    UiKey.PROJECTS_KIND_WORK to "شغل",
    UiKey.PROJECTS_Q_PERSONAL to "كلّفني كام؟",
    UiKey.PROJECTS_Q_WORK to "كسبت منه كام؟",
    UiKey.PROJECTS_LINE to "صرفت {0}، جالك {1}",
    UiKey.PROJECTS_NO_OPS to "لسه مفيش عمليات",
    UiKey.PROJECTS_NO_DEADLINE to "من غير ميعاد",
    UiKey.PROJECTS_PASSED to "عدّى",
    UiKey.PROJECTS_APPROX to "تقريبي، {0} مستنية تأكيد النوع",
    UiKey.PROJECTS_ARCHIVED to "المؤرشفة ({0})",
    UiKey.PROJECTS_RESTORE to "رجّعه",
    UiKey.PROJECTS_RESTORED to "«{0}» رجع للنشطة",
    UiKey.PROJECTS_ARCH_NOTE to "المؤرشف مقفول: قواعده واقفة، ومفيش مسح.",
    UiKey.PROJECTS_ASK_KIND to "المشروع ده شخصي ولا شغل؟",
    UiKey.PROJECTS_EX_PERSONAL to "فرح، سفر، تجهيز بيت — اللي جالك بيقلل الكلفة",
    UiKey.PROJECTS_EX_WORK to "عميل، بارت تايم، شغلانة جنب — الصافي ممكن يطلع بالسالب",
    UiKey.PROJECTS_NAME to "الاسم",
    UiKey.PROJECTS_NAME_PH to "مثلًا: سفرية العيد",
    UiKey.PROJECTS_DEADLINE to "آخر ميعاد (اختياري)",
    UiKey.PROJECTS_DEADLINE_NOTE to "لو حطيته، المشروع بيظهر في التقويم يومها.",
    UiKey.PROJECTS_CREATE to "اعمل المشروع",
    UiKey.PROJECTS_CREATED to "اتعمل «{0}»",
    UiKey.PROJECTS_EDIT_TITLE to "تعديل المشروع",
    // ── صفحة المشروع (ProjectDetail)
    UiKey.PROJECT_DETAIL_EDIT to "عدّل الاسم والميعاد",
    UiKey.PROJECT_DETAIL_ARCHIVE to "أرشف المشروع",
    UiKey.PROJECT_DETAIL_ARCHIVED to "اتأرشف «{0}» — مفيش حاجة اتمسحت",
    UiKey.PROJECT_DETAIL_UNTIL to "لحد {0}",
    UiKey.PROJECT_DETAIL_OUT to "صرفت (نصيبك)",
    UiKey.PROJECT_DETAIL_IN to "جالك",
    UiKey.PROJECT_DETAIL_FORMULA_WORK to "الصافي = اللي جالك − اللي صرفته، وممكن يطلع بالسالب.",
    UiKey.PROJECT_DETAIL_FORMULA_PERSONAL to "اللي جالك (نقوط أو هدايا) بيقلل الكلفة.",
    UiKey.PROJECT_DETAIL_TAB_OPS to "العمليات ({0})",
    UiKey.PROJECT_DETAIL_TAB_RULES to "القواعد ({0})",
    UiKey.PROJECT_DETAIL_NO_OPS to "لسه مفيش عمليات في المشروع",
    UiKey.PROJECT_DETAIL_SRC_RULE to "بقاعدة",
    UiKey.PROJECT_DETAIL_SRC_MANUAL to "ضفتها بإيدك",
    UiKey.PROJECT_DETAIL_UNSURE to "نوعها مش أكيد",
    UiKey.PROJECT_DETAIL_REMOVE_OP to "شيل {0} من المشروع",
    UiKey.PROJECT_DETAIL_ADD_HINT to "تضيف عملية بإيدك من التلات نقط بتوعها ← «ضيف لمشروع». والعملية ممكن تبقى في أكتر من مشروع.",
    UiKey.PROJECT_DETAIL_RULES_INTRO to "القاعدة بتضيف الجديد لوحدها. القديم بنسألك عليه وقت ما تعملها.",
    UiKey.PROJECT_DETAIL_MODE_CONTAINS to "فيه",
    UiKey.PROJECT_DETAIL_MODE_STARTS to "بيبدأ بـ",
    UiKey.PROJECT_DETAIL_MODE_EXACT to "بالظبط",
    UiKey.PROJECT_DETAIL_QUOTED to "«{0}»",
    UiKey.PROJECT_DETAIL_DIR to "الاتجاه: {0}",
    UiKey.PROJECT_DETAIL_DIR_OUT to "صادر",
    UiKey.PROJECT_DETAIL_DIR_IN to "وارد",
    UiKey.PROJECT_DETAIL_DIR_ANY to "الاتنين",
    UiKey.PROJECT_DETAIL_RULE_SWITCH to "شغّل قاعدة {0}",
    UiKey.PROJECT_DETAIL_NEW_RULE to "قاعدة جديدة",
    UiKey.PROJECT_DETAIL_RULE_TITLE to "قاعدة للمشروع",
    UiKey.PROJECT_DETAIL_RULE_TEXT to "النص في اسم التاجر أو الوصف",
    UiKey.PROJECT_DETAIL_RULE_PH to "مثلًا: الغردقة",
    UiKey.PROJECT_DETAIL_RULE_ERR to "اكتب نص القاعدة من حرفين لـ60 حرف.",
    UiKey.PROJECT_DETAIL_MODE_LABEL to "طريقة المطابقة",
    UiKey.PROJECT_DETAIL_DIR_LABEL to "الاتجاه",
    UiKey.PROJECT_DETAIL_NEXT to "التالي",
    UiKey.PROJECT_DETAIL_OLD_TITLE to "نضيف القديم كمان؟",
    UiKey.PROJECT_DETAIL_OLD_BODY to "من العمليات القديمة (آخر 3 سنين) بيطابقها: {0}",
    UiKey.PROJECT_DETAIL_OLD_NONE to "مفيش عمليات قديمة بتطابقها. الجديدة هتتضاف لوحدها.",
    UiKey.PROJECT_DETAIL_ADD_OLD to "أيوه، ضيف القديمة كمان",
    UiKey.PROJECT_DETAIL_NEW_ONLY to "لأ، الجديد بس",
    UiKey.PROJECT_DETAIL_OK to "تمام",
    UiKey.PROJECT_DETAIL_OLD_ADDED to "اتضاف للمشروع: {0}",
)
