package app.masroufy.core

/**
 * المساعد «مصروفي» (§78 + ردود المالك 2026-10-09): التنقل · كروت التأكيد والتقسيم · «بتصرف عادةً منين؟» · «أمور لم تُنجزها بعد» ·
 * «اللي اتعلمته عنك». مفيش زرار «ذكّره» ولا رسالة تذكير لشخص (رد المالك ٣).
 */
internal val MSA_ASSIST_ACTION_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_NAV to "تجدها في {0}.",
    TextKey.ASSIST_NAV_LOCK to "القفل في «المزيد ← الإعدادات ← القفل».",
    TextKey.ASSIST_NAV_NEEDS_SPACE to "التحويل بين البلدين يحتاج بلدًا ثانية — أضفها من «البلاد».",
    TextKey.ASSIST_NAV_IOS_SMS to "قراءة رسائل البنك على أندرويد فقط — على الآيفون الصق الرسالة هنا.",
    TextKey.ASSIST_NAV_ZAKAT_NO_YEAR to "حدّد بداية الحول أولًا من «الزكاة»، ثم سجّل الدفع.",
    TextKey.ASSIST_NAV_NEEDS_EVENT to "هذا داخل صفحة الحدث — اختر الحدث من «الأحداث».",
    TextKey.ASSIST_PICK_SUBJECT to "تقصد من؟",
    TextKey.ASSIST_ASK_MAIN_WALLET to "من أين تصرف عادةً؟",
    TextKey.ASSIST_TXN_CARD to "أسجّلها هكذا؟",
    TextKey.ASSIST_SIMILAR_WARNING to "سجّلت اليوم عملية بنفس المبلغ — تأكد أنها ليست مكررة.",
    TextKey.ASSIST_EXPENSE to "مصروف",
    TextKey.ASSIST_FOREIGN to "المبلغ بعملة غير عملة {0} — سجّله من «أضف عملية» لتحدد سعر الصرف.",
    TextKey.ASSIST_INVALID_AMOUNT to "لم أفهم المبلغ — اكتبه مثل «قهوة 15» أو «15.50».",
    TextKey.ASSIST_TWO_AMOUNTS to "في كلامك أكثر من مبلغ — اكتب كل مصروف وحده.",
    TextKey.ASSIST_FUTURE_DATE to "هذا اليوم لم يأتِ بعد — سجّل المصروف يوم يحدث.",
    TextKey.ASSIST_NOT_EXPENSE_IN to "هذا مال دخل لك وليس مصروفًا، فلن أسجّله مصروفًا. أضفه دخلًا من «إضافة عملية»، أو من صفحة الشخص إن كان سدادًا لدَين.",
    TextKey.ASSIST_NOT_EXPENSE_REFUND to "هذا مبلغ رجع لك وليس مصروفًا، فلن أسجّله مصروفًا. أضفه مبلغًا داخلًا من «إضافة عملية».",
    TextKey.ASSIST_NOT_EXPENSE_DEBT to "هذه سلفة أو دَين وليست مصروفًا، فلن أسجّلها مصروفًا. سجّلها من صفحة الشخص أو من «الديون» حتى تُحسب على صاحبها.",
    TextKey.ASSIST_NOT_EXPENSE_TRANSFER to "هذا تحويل وليس مصروفًا بالضرورة، فلن أسجّله مصروفًا. سجّله من «التحويلات»، أو من صفحة الشخص إن كان سلفة أو سدادًا.",
    TextKey.ASSIST_NOT_EXPENSE_CASH_MOVE to "هذا نقل بين محافظك (سحب أو إيداع) وليس مصروفًا، فلن أسجّله مصروفًا. سجّله من «التحويلات».",
    TextKey.ASSIST_NOT_RECORDED to "حسنًا، لم أسجّل شيئًا.",
    TextKey.ASSIST_NO_FUTURE to "لا أعرف أرقام ما لم يحدث بعد — غير متاح. أستطيع أن أخبرك بما صرفته فعلًا، أو بتوقع نهاية هذا الشهر.",
    TextKey.ASSIST_CANCELLED to "تمام، ألغيتها.",
    TextKey.ASSIST_NOTHING_PENDING to "لا يوجد شيء ينتظر تأكيدك.",
    TextKey.ASSIST_MAIN_CONFIRM to "أجعل {0} محفظتك الأساسية؟",
    TextKey.ASSIST_MAIN_SET to "صارت {0} محفظتك الأساسية — غيّرها من «المحافظ».",
    TextKey.ASSIST_OPT_YES to "نعم",
    TextKey.ASSIST_OPT_NO to "لا",
    TextKey.ASSIST_OPT_ADD to "أضفه",
    TextKey.ASSIST_OPT_SPLIT_EXISTING to "قسّم الموجودة",
    TextKey.ASSIST_OPT_RECORD_NEW to "سجّل جديدة",
    TextKey.ASSIST_ADD_PERSON to "{0} ليس في الأشخاص — أضيفه؟",
    TextKey.ASSIST_SPLIT_EXISTING to "سجّلت اليوم عملية بنفس المبلغ ({0}) — أقسّمها هي؟",
    TextKey.ASSIST_SPLIT_CARD to "قسّمتها هكذا:",
    TextKey.ASSIST_SPLIT_DONE to "تم: نصيب كل شخص {0}، وسُجّل لك عندهم.",
    TextKey.ASSIST_SPLIT_ME to "أنت",
    TextKey.ASSIST_SPLIT_OTHER to "شخص {0}",
    TextKey.ASSIST_SPLIT_TITLE to "فاتورة مقسّمة",
    TextKey.ASSIST_SPLIT_NEEDS to "اكتب المبلغ ومن ستقسم معه، مثل: «قسّم 300 مع أحمد».",
    TextKey.ASSIST_SPLIT_NEEDS_PEOPLE to "لا أستطيع أن أقسّم مع شخص غير موجود في «الأشخاص».",
    TextKey.ASSIST_RECORD_BILL_NONE to "لا أعرف فاتورة بهذا الاسم — فواتيرك في «الاشتراكات».",
    TextKey.ASSIST_LEARNING_ON_CONFIRM to "أرجع أتعلم من أسئلتك؟",
    TextKey.ASSIST_LEARNING_OFF_CONFIRM to "أتوقف عن التعلم من أسئلتك؟",
    TextKey.ASSIST_LEARNING_ON_DONE to "رجعت أتعلم من أسئلتك.",
    TextKey.ASSIST_LEARNING_OFF_DONE to "توقفت عن التعلم من أسئلتك — ما تعلمته باقٍ حتى تمسحه.",
    TextKey.ASSIST_HISTORY_OPEN to "محادثاتك السابقة في «السجل».",
    TextKey.ASSIST_FORGET_OPEN to "امسحه من «ما تعلمته عنك» — كل عنصر وحده أو الكل.",
    TextKey.ASSIST_MEMORY_SUMMARY to "ما تعلمته عنك: {0}.",
    TextKey.ASSIST_MEMORY_EMPTY to "لم أتعلم عنك شيئًا بعد.",
    TextKey.ASSIST_NEW_CONVERSATION_HINT to "بدأنا محادثة جديدة، وهذه محفوظة في السجل.",
    TextKey.ASSIST_START_SMS to "{0} رسالة بنك تنتظر تأكيدك.",
    TextKey.ASSIST_START_BILL to "فاتورة {0} فات موعدها ({1}) ولم تُسجّل بعد.",
    TextKey.ASSIST_START_BUDGET to "{0} وصل {1}% من سقفه.",
    TextKey.ASSIST_START_DEBT to "{0}: {1} متأخر منذ {2}.",
    TextKey.ASSIST_ACTION_REVIEW to "راجعها",
    TextKey.ASSIST_ACTION_RECORD to "سجّلها",
    TextKey.ASSIST_ACTION_OPEN to "افتحها",
    TextKey.ASSIST_FACT_SALARY to "راتبك يوم {0} من {1}.",
    TextKey.ASSIST_FACT_STORE to "أكثر محل تشتري منه: {0} ({1}).",
    TextKey.ASSIST_FACT_PARTNER to "تقسّم الفواتير عادةً مع {0}.",
    TextKey.ASSIST_FACT_GOAL to "خطتك المفضلة: {0}.",
    TextKey.ASSIST_FACT_FROM_INCOME to "من مصادر الدخل",
    TextKey.ASSIST_FACT_FROM_TXNS to "من عملياتك المؤكدة",
    TextKey.ASSIST_FACT_FROM_SPLITS to "من تقسيماتك",
    TextKey.ASSIST_FACT_FROM_GOALS to "من خطط الادخار",
    TextKey.ASSIST_FACT_ASKED to "سألت عنها {0}",
    TextKey.BACKUP_GROUP_USER_SETTINGS to "إعدادات المستخدم",
    TextKey.BACKUP_GROUP_ASSISTANT_CONVERSATIONS to "محادثات المساعد",
    TextKey.BACKUP_GROUP_ASSISTANT_MESSAGES to "رسائل المساعد",
    TextKey.BACKUP_GROUP_ASSISTANT_TOPICS to "ما تسأل عنه كثيرًا",
    TextKey.BACKUP_GROUP_ASSISTANT_FORGOTTEN to "ما طلبت من المساعد نسيانه",
    TextKey.BACKUP_GROUP_ASSISTANT_UNKNOWN to "أسئلة لم يفهمها المساعد",
    TextKey.BACKUP_GROUP_ALERT_DISMISSALS to "الإشعارات الممسوحة",
)

internal val EGYPTIAN_ASSIST_ACTION_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_NAV to "تلاقيها في {0}.",
    TextKey.ASSIST_NAV_LOCK to "القفل في «المزيد ← الإعدادات ← القفل».",
    TextKey.ASSIST_NAV_NEEDS_SPACE to "التحويل بين البلدين محتاج بلد تانية — ضيفها من «البلاد».",
    TextKey.ASSIST_NAV_IOS_SMS to "قراية رسايل البنك على أندرويد بس — على الآيفون الصق الرسالة هنا.",
    TextKey.ASSIST_NAV_ZAKAT_NO_YEAR to "حدد بداية الحول الأول من «الزكاة»، وبعدين سجّل الدفع.",
    TextKey.ASSIST_NAV_NEEDS_EVENT to "دي جوه صفحة الحدث — اختار الحدث من «الأحداث».",
    TextKey.ASSIST_PICK_SUBJECT to "تقصد مين؟",
    TextKey.ASSIST_ASK_MAIN_WALLET to "بتصرف عادةً منين؟",
    TextKey.ASSIST_TXN_CARD to "أسجّلها كده؟",
    TextKey.ASSIST_SIMILAR_WARNING to "اتسجلت النهارده عملية بنفس المبلغ — اتأكد إنها مش مكررة.",
    TextKey.ASSIST_EXPENSE to "مصروف",
    TextKey.ASSIST_FOREIGN to "المبلغ بعملة غير عملة {0} — سجّله من «ضيف عملية» عشان تحدد سعر الصرف.",
    TextKey.ASSIST_INVALID_AMOUNT to "ما فهمتش المبلغ — اكتبه زي «قهوة 15» أو «15.50».",
    TextKey.ASSIST_TWO_AMOUNTS to "في كلامك أكتر من مبلغ — اكتب كل مصروف لوحده.",
    TextKey.ASSIST_FUTURE_DATE to "اليوم ده لسه ما جاش — سجّل المصروف يوم ما يحصل.",
    TextKey.ASSIST_NOT_EXPENSE_IN to "دي فلوس دخلت لك مش مصروف، فمش هسجّلها مصروف. ضيفها دخل من «إضافة عملية»، أو من صفحة الشخص لو كانت سداد دين.",
    TextKey.ASSIST_NOT_EXPENSE_REFUND to "ده مبلغ رجع لك مش مصروف، فمش هسجّله مصروف. ضيفه فلوس داخلة من «إضافة عملية».",
    TextKey.ASSIST_NOT_EXPENSE_DEBT to "دي سلفة أو دين مش مصروف، فمش هسجّلها مصروف. سجّلها من صفحة الشخص أو من «الديون» عشان تتحسب على صاحبها.",
    TextKey.ASSIST_NOT_EXPENSE_TRANSFER to "ده تحويل مش لازم يكون مصروف، فمش هسجّله مصروف. سجّله من «التحويلات»، أو من صفحة الشخص لو سلفة أو سداد.",
    TextKey.ASSIST_NOT_EXPENSE_CASH_MOVE to "ده نقل فلوس بين محافظك (سحب أو إيداع) مش مصروف، فمش هسجّله مصروف. سجّله من «التحويلات».",
    TextKey.ASSIST_NOT_RECORDED to "تمام، ما سجّلتش حاجة.",
    TextKey.ASSIST_NO_FUTURE to "ما اعرفش أرقام حاجة لسه ما حصلتش — مش متاح. أقدر أقولك صرفت كام فعلًا، أو توقع آخر الشهر ده.",
    TextKey.ASSIST_CANCELLED to "ماشي، اتلغت.",
    TextKey.ASSIST_NOTHING_PENDING to "مفيش حاجة مستنية تأكيدك.",
    TextKey.ASSIST_MAIN_CONFIRM to "أخلّي {0} محفظتك الأساسية؟",
    TextKey.ASSIST_MAIN_SET to "بقت {0} محفظتك الأساسية — غيّرها من «المحافظ».",
    TextKey.ASSIST_OPT_YES to "أيوه",
    TextKey.ASSIST_OPT_NO to "لأ",
    TextKey.ASSIST_OPT_ADD to "ضيفه",
    TextKey.ASSIST_OPT_SPLIT_EXISTING to "قسّم اللي اتسجلت",
    TextKey.ASSIST_OPT_RECORD_NEW to "سجّل جديدة",
    TextKey.ASSIST_ADD_PERSON to "{0} مش في الأشخاص — أضيفه؟",
    TextKey.ASSIST_SPLIT_EXISTING to "اتسجلت النهارده عملية بنفس المبلغ ({0}) — أقسّمها هي؟",
    TextKey.ASSIST_SPLIT_CARD to "قسّمتها كده:",
    TextKey.ASSIST_SPLIT_DONE to "تمام: نصيب كل واحد {0}، واتسجّل ليك عندهم.",
    TextKey.ASSIST_SPLIT_ME to "إنت",
    TextKey.ASSIST_SPLIT_OTHER to "شخص {0}",
    TextKey.ASSIST_SPLIT_TITLE to "فاتورة متقسمة",
    TextKey.ASSIST_SPLIT_NEEDS to "اكتب المبلغ وهتقسم مع مين، زي: «قسّم 300 مع أحمد».",
    TextKey.ASSIST_SPLIT_NEEDS_PEOPLE to "مش هقدر أقسّم مع حد مش موجود في «الأشخاص».",
    TextKey.ASSIST_RECORD_BILL_NONE to "مش عارف فاتورة بالاسم ده — فواتيرك في «الاشتراكات».",
    TextKey.ASSIST_LEARNING_ON_CONFIRM to "أرجع أتعلم من أسئلتك؟",
    TextKey.ASSIST_LEARNING_OFF_CONFIRM to "أبطّل أتعلم من أسئلتك؟",
    TextKey.ASSIST_LEARNING_ON_DONE to "رجعت أتعلم من أسئلتك.",
    TextKey.ASSIST_LEARNING_OFF_DONE to "بطّلت أتعلم من أسئلتك — اللي اتعلمته فاضل لحد ما تمسحه.",
    TextKey.ASSIST_HISTORY_OPEN to "محادثاتك اللي فاتت في «السجل».",
    TextKey.ASSIST_FORGET_OPEN to "امسحه من «اللي اتعلمته عنك» — كل حاجة لوحدها أو الكل.",
    TextKey.ASSIST_MEMORY_SUMMARY to "اللي اتعلمته عنك: {0}.",
    TextKey.ASSIST_MEMORY_EMPTY to "لسه ما اتعلمتش عنك حاجة.",
    TextKey.ASSIST_NEW_CONVERSATION_HINT to "بدأنا محادثة جديدة، ودي محفوظة في السجل.",
    TextKey.ASSIST_START_SMS to "{0} رسالة بنك مستنية تأكيدك.",
    TextKey.ASSIST_START_BILL to "فاتورة {0} عدّى ميعادها ({1}) ولسه ما اتسجلتش.",
    TextKey.ASSIST_START_BUDGET to "{0} وصل {1}% من سقفه.",
    TextKey.ASSIST_START_DEBT to "{0}: {1} متأخر من {2}.",
    TextKey.ASSIST_ACTION_REVIEW to "راجعها",
    TextKey.ASSIST_ACTION_RECORD to "سجّلها",
    TextKey.ASSIST_ACTION_OPEN to "افتحها",
    TextKey.ASSIST_FACT_SALARY to "مرتبك يوم {0} من {1}.",
    TextKey.ASSIST_FACT_STORE to "أكتر محل بتشتري منه: {0} ({1}).",
    TextKey.ASSIST_FACT_PARTNER to "بتقسّم الفواتير عادةً مع {0}.",
    TextKey.ASSIST_FACT_GOAL to "خطتك المفضلة: {0}.",
    TextKey.ASSIST_FACT_FROM_INCOME to "من مصادر الدخل",
    TextKey.ASSIST_FACT_FROM_TXNS to "من عملياتك المؤكدة",
    TextKey.ASSIST_FACT_FROM_SPLITS to "من تقسيماتك",
    TextKey.ASSIST_FACT_FROM_GOALS to "من خطط التحويش",
    TextKey.ASSIST_FACT_ASKED to "سألت عنها {0}",
    TextKey.BACKUP_GROUP_USER_SETTINGS to "إعدادات المستخدم",
    TextKey.BACKUP_GROUP_ASSISTANT_CONVERSATIONS to "محادثات المساعد",
    TextKey.BACKUP_GROUP_ASSISTANT_MESSAGES to "رسايل المساعد",
    TextKey.BACKUP_GROUP_ASSISTANT_TOPICS to "اللي بتسأل عنه كتير",
    TextKey.BACKUP_GROUP_ASSISTANT_FORGOTTEN to "اللي طلبت من المساعد ينساه",
    TextKey.BACKUP_GROUP_ASSISTANT_UNKNOWN to "أسئلة المساعد ما فهمهاش",
    TextKey.BACKUP_GROUP_ALERT_DISMISSALS to "الإشعارات الممسوحة",
)

internal val ENGLISH_ASSIST_ACTION_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_NAV to "You'll find it in {0}.",
    TextKey.ASSIST_NAV_LOCK to "The lock is in “More → Settings → Lock”.",
    TextKey.ASSIST_NAV_NEEDS_SPACE to "Moving money between countries needs a second country — add one in “Countries”.",
    TextKey.ASSIST_NAV_IOS_SMS to "Reading bank messages works on Android only — on iPhone, paste the message here.",
    TextKey.ASSIST_NAV_ZAKAT_NO_YEAR to "Set the start of your zakat year in “Zakat” first, then record the payment.",
    TextKey.ASSIST_NAV_NEEDS_EVENT to "That's inside an event's page — pick the event in “Events”.",
    TextKey.ASSIST_PICK_SUBJECT to "Who do you mean?",
    TextKey.ASSIST_ASK_MAIN_WALLET to "Where do you usually spend from?",
    TextKey.ASSIST_TXN_CARD to "Record it like this?",
    TextKey.ASSIST_SIMILAR_WARNING to "A transaction with the same amount was recorded today — make sure this isn't a duplicate.",
    TextKey.ASSIST_EXPENSE to "Expense",
    TextKey.ASSIST_FOREIGN to "That amount isn't in {0}'s currency — record it from “Add transaction” to set the rate.",
    TextKey.ASSIST_INVALID_AMOUNT to "I didn't get the amount — write it like “coffee 15” or “15.50”.",
    TextKey.ASSIST_TWO_AMOUNTS to "There's more than one amount — write each expense on its own.",
    TextKey.ASSIST_FUTURE_DATE to "That day hasn't come yet — record the expense when it happens.",
    TextKey.ASSIST_NOT_EXPENSE_IN to "That's money coming in, not spending, so I won't record it as an expense. Add it as income from “Add operation”, or from the person's page if it repays a debt.",
    TextKey.ASSIST_NOT_EXPENSE_REFUND to "That's money back to you, not spending, so I won't record it as an expense. Add it as money in from “Add operation”.",
    TextKey.ASSIST_NOT_EXPENSE_DEBT to "That's a loan or a debt, not spending, so I won't record it as an expense. Record it from the person's page or “Debts” so it counts for the right person.",
    TextKey.ASSIST_NOT_EXPENSE_TRANSFER to "That's a transfer, not necessarily spending, so I won't record it as an expense. Record it from “Transfers”, or from the person's page if it's a loan or a repayment.",
    TextKey.ASSIST_NOT_EXPENSE_CASH_MOVE to "That's a move between your wallets (withdrawal or deposit), not spending, so I won't record it as an expense. Record it from “Transfers”.",
    TextKey.ASSIST_NOT_RECORDED to "OK, I didn't record anything.",
    TextKey.ASSIST_NO_FUTURE to "I can't know numbers for what hasn't happened yet — not available. I can tell you what you actually spent, or the forecast for the end of this month.",
    TextKey.ASSIST_CANCELLED to "OK, cancelled.",
    TextKey.ASSIST_NOTHING_PENDING to "Nothing is waiting for your confirmation.",
    TextKey.ASSIST_MAIN_CONFIRM to "Make {0} your main wallet?",
    TextKey.ASSIST_MAIN_SET to "{0} is now your main wallet — change it in “Wallets”.",
    TextKey.ASSIST_OPT_YES to "Yes",
    TextKey.ASSIST_OPT_NO to "No",
    TextKey.ASSIST_OPT_ADD to "Add",
    TextKey.ASSIST_OPT_SPLIT_EXISTING to "Split that one",
    TextKey.ASSIST_OPT_RECORD_NEW to "Record a new one",
    TextKey.ASSIST_ADD_PERSON to "{0} isn't in your people — add them?",
    TextKey.ASSIST_SPLIT_EXISTING to "A transaction with the same amount was recorded today ({0}) — split that one?",
    TextKey.ASSIST_SPLIT_CARD to "Here's the split:",
    TextKey.ASSIST_SPLIT_DONE to "Done: each share is {0}, recorded as owed to you.",
    TextKey.ASSIST_SPLIT_ME to "You",
    TextKey.ASSIST_SPLIT_OTHER to "Person {0}",
    TextKey.ASSIST_SPLIT_TITLE to "Split bill",
    TextKey.ASSIST_SPLIT_NEEDS to "Write the amount and who you split with, like: “split 300 with Ahmed”.",
    TextKey.ASSIST_SPLIT_NEEDS_PEOPLE to "I can't split with someone who isn't in “People”.",
    TextKey.ASSIST_RECORD_BILL_NONE to "I don't know a bill by that name — your bills are in “Subscriptions”.",
    TextKey.ASSIST_LEARNING_ON_CONFIRM to "Start learning from your questions again?",
    TextKey.ASSIST_LEARNING_OFF_CONFIRM to "Stop learning from your questions?",
    TextKey.ASSIST_LEARNING_ON_DONE to "I'm learning from your questions again.",
    TextKey.ASSIST_LEARNING_OFF_DONE to "I stopped learning from your questions — what I learned stays until you clear it.",
    TextKey.ASSIST_HISTORY_OPEN to "Your past conversations are in “History”.",
    TextKey.ASSIST_FORGET_OPEN to "Clear it from “What I learned about you” — one item or everything.",
    TextKey.ASSIST_MEMORY_SUMMARY to "What I learned about you: {0}.",
    TextKey.ASSIST_MEMORY_EMPTY to "I haven't learned anything about you yet.",
    TextKey.ASSIST_NEW_CONVERSATION_HINT to "New conversation started; that one is saved in history.",
    TextKey.ASSIST_START_SMS to "{0} bank messages are waiting for you.",
    TextKey.ASSIST_START_BILL to "The {0} bill was due {1} and isn't recorded yet.",
    TextKey.ASSIST_START_BUDGET to "{0} reached {1}% of its cap.",
    TextKey.ASSIST_START_DEBT to "{0}: {1} overdue for {2}.",
    TextKey.ASSIST_ACTION_REVIEW to "Review",
    TextKey.ASSIST_ACTION_RECORD to "Record it",
    TextKey.ASSIST_ACTION_OPEN to "Open",
    TextKey.ASSIST_FACT_SALARY to "Your salary comes on day {0} from {1}.",
    TextKey.ASSIST_FACT_STORE to "Your top store: {0} ({1}).",
    TextKey.ASSIST_FACT_PARTNER to "You usually split bills with {0}.",
    TextKey.ASSIST_FACT_GOAL to "Your favourite plan: {0}.",
    TextKey.ASSIST_FACT_FROM_INCOME to "From income sources",
    TextKey.ASSIST_FACT_FROM_TXNS to "From your confirmed transactions",
    TextKey.ASSIST_FACT_FROM_SPLITS to "From your splits",
    TextKey.ASSIST_FACT_FROM_GOALS to "From savings plans",
    TextKey.ASSIST_FACT_ASKED to "Asked {0}",
    TextKey.BACKUP_GROUP_USER_SETTINGS to "User settings",
    TextKey.BACKUP_GROUP_ASSISTANT_CONVERSATIONS to "Assistant conversations",
    TextKey.BACKUP_GROUP_ASSISTANT_MESSAGES to "Assistant messages",
    TextKey.BACKUP_GROUP_ASSISTANT_TOPICS to "Topics you ask often",
    TextKey.BACKUP_GROUP_ASSISTANT_FORGOTTEN to "Things the assistant was asked to forget",
    TextKey.BACKUP_GROUP_ASSISTANT_UNKNOWN to "Questions the assistant didn't understand",
    TextKey.BACKUP_GROUP_ALERT_DISMISSALS to "Deleted notifications",
)
