package app.masroufy.core

/**
 * منطقة «المستحقات» — الجزء الثاني بالإنجليزي (كتابة Claude — مستني مراجعة المالك §40). نفس مفاتيح ومتغيرات `TextsAreaDuesPlans.kt`.
 */
internal val ENGLISH_DUES_PLANS_TEXTS: Map<TextKey, String> = mapOf(
    // ── Installments
    TextKey.INSTALLMENTS_TITLE to "Installments",
    TextKey.INSTALLMENTS_NEW to "New plan",
    TextKey.INSTALLMENTS_LEFT to "Left to pay in installments",
    TextKey.INSTALLMENTS_NOTE to "The whole installment counts as spending when you pay it.",
    TextKey.INSTALLMENTS_RECEIVED to "Amount received",
    TextKey.INSTALLMENTS_EMPTY_TITLE to "No installments",
    TextKey.INSTALLMENTS_EMPTY_BODY to "Add a bank installment or a purchase plan and we will track its dates.",
    TextKey.INST_PLANS_ONE to "1 plan",
    TextKey.INST_PLANS_TWO to "2 plans",
    TextKey.INST_PLANS_FEW to "{0} plans",
    TextKey.INST_PLANS_MANY to "{0} plans",
    TextKey.INST_KIND_FINANCING to "Bank financing",
    TextKey.INST_KIND_PURCHASE to "Purchase plan",
    TextKey.INST_WITH_PROFIT to "with profit",
    TextKey.INST_PAID_OF to "Paid {0} of {1}",
    TextKey.INST_NEXT to "Next {0}",
    TextKey.INST_NEXT_N to "Next {0}, installment {1}",
    TextKey.INST_LATE_SINCE to "Late since {0}",
    TextKey.INST_DONE to "All installments paid",
    TextKey.INST_NOT_LINKED to "Not linked yet",

    // ── Installment detail
    TextKey.INST_EDIT to "Edit plan",
    TextKey.INST_LEFT to "Left to pay",
    TextKey.INST_DONE_HERO to "All installments paid",
    TextKey.INST_LINE to "Installment {0} · {1} · total {2}",
    TextKey.INST_SCHEDULE to "Schedule",
    TextKey.INST_YEAR_LABEL to "Year {0}, {1} – {2}",
    TextKey.INST_RANGE to "{0} – {1}",
    TextKey.INST_LEG_PAID to "Paid",
    TextKey.INST_LEG_LATE to "Late",
    TextKey.INST_LEG_NEXT to "Next",
    TextKey.INST_LEG_UP to "Remaining",
    TextKey.INST_SCHED_ARIA to "Paid {0} of {1}, {2} late",
    TextKey.INST_SCHED_ARIA_NOLATE to "Paid {0} of {1}",
    TextKey.INST_LAST_LINE to "Last installment {0} · {1} on day {2}",
    TextKey.INST_RECV_HINT to "Link the deposit to show what actually reached you.",
    TextKey.INST_RECV_NA to "Does not apply",
    TextKey.INST_RECV_NA_SUB to "Purchase plan — you receive no money in it.",
    TextKey.INST_UNLINK to "Unlink",
    TextKey.INST_UNLINK_RECV_TITLE to "Unlink the financing amount?",
    TextKey.INST_PROFIT_TITLE to "Financing profit",
    TextKey.INST_INFO_ONLY to "For information",
    TextKey.INST_TOTAL_PAY to "Total you will pay",
    TextKey.INST_PRINCIPAL to "Original amount",
    TextKey.INST_PROFIT to "Financing profit",
    TextKey.INST_PROFIT_PAID to "Paid so far",
    TextKey.INST_PROFIT_LEFT to "Still to pay",
    TextKey.INST_PROFIT_PER to "In each installment, roughly",
    TextKey.INST_NOTE_FIN to "The whole installment ({0}) counts as spending under «Dues ← Financing», so the profit is not added to spending again.",
    TextKey.INST_NOTE_BUY to "The whole installment counts as spending under «Dues ← Purchase plans».",

    // ── New plan / edit plan
    TextKey.INST_EDIT_TITLE_NEW to "New plan",
    TextKey.INST_EDIT_TITLE to "Edit plan",
    TextKey.INST_EDIT_SUB_NEW to "Bank installment or purchase plan",
    TextKey.INST_F_NAME to "Name",
    TextKey.INST_F_NAME_HINT to "e.g. Car installment",
    TextKey.INST_F_PROVIDER to "Provider",
    TextKey.INST_F_PROVIDER_HINT to "The bank or the store",
    TextKey.INST_F_KIND to "Type",
    TextKey.INST_KIND_FIN_HINT to "I received money from them",
    TextKey.INST_KIND_BUY_HINT to "I bought something in installments",
    TextKey.INST_F_CURRENCY to "Currency",
    TextKey.INST_F_CURRENCY_HINT to "This space's currency",
    TextKey.INST_F_PRINCIPAL_FIN to "Original amount (what you received)",
    TextKey.INST_F_PRINCIPAL_BUY to "Price of the item",
    TextKey.INST_F_TOTAL to "Total you will pay",
    TextKey.INST_F_INSTALLMENT to "Installment",
    TextKey.INST_F_CYCLE to "Every how many months",
    TextKey.INST_F_FIRST to "First due date",
    TextKey.INST_EDIT_NOTE_FIN to "The whole installment counts as spending under «Dues ← Financing»; the profit is for information only.",
    TextKey.INST_EDIT_NOTE_BUY to "The whole installment counts as spending under «Dues ← Purchase plans».",
    TextKey.INST_SAVE_NEW to "Add the plan",
    TextKey.INST_SAVE to "Save changes",
    TextKey.INST_SAVE_ERR to "Check the fields marked in red.",
    TextKey.INST_SAVED_NEW to "«{0}» added — find it in Installments",
    TextKey.INST_SAVED to "Changes saved — the schedule updates from the first due date",
    TextKey.INST_DONE_NEW to "To installments",
    TextKey.INST_DONE_EDIT to "Back to the plan",

    // ── ROSCAs and ROSCA detail
    TextKey.ROSCAS_TITLE to "ROSCAs",
    TextKey.ROSCAS_NEW to "New ROSCA",
    TextKey.ROSCAS_EMPTY_TITLE to "No ROSCAs",
    TextKey.ROSCAS_EMPTY_BODY to "Add a ROSCA and we will work out what you paid and what you received.",
    TextKey.ROSCAS_TERMS to "{0} · {1} · {2}",
    TextKey.ROSCA_TERMS_TO to "{0} · paid to {1}",
    TextKey.ROSCAS_PAID to "Paid",
    TextKey.ROSCAS_GOT to "Received",
    TextKey.ROSCAS_GAIN to "Gain",
    TextKey.ROSCA_TURNS_ONE to "1 turn",
    TextKey.ROSCA_TURNS_TWO to "2 turns",
    TextKey.ROSCA_TURNS_FEW to "{0} turns",
    TextKey.ROSCA_TURNS_MANY to "{0} turns",
    TextKey.ROSCA_TURN_N to "Turn {0}",
    TextKey.ROSCA_TURNS_N2 to "Turns {0} and {1}",
    TextKey.ROSCA_TURN_UNKNOWN_LINE to "Your turn is not known yet",
    TextKey.ROSCA_PHASE_SAVING to "Saving",
    TextKey.ROSCA_PHASE_REPAYING to "Repaying",
    TextKey.ROSCA_PHASE_DONE to "Finished",
    TextKey.ROSCA_POS_SAVED to "The ROSCA holds {0} for you",
    TextKey.ROSCA_POS_OWED to "You owe the ROSCA {0}",
    TextKey.ROSCA_POS_DONE to "Finished with no gain and no loss",
    TextKey.ROSCA_POS_ZERO to "Nothing either way",
    TextKey.ROSCA_GAIN_NONE to "None",
    TextKey.ROSCA_HERO_SAVED to "The ROSCA holds for you",
    TextKey.ROSCA_HERO_OWED to "You owe the ROSCA",
    TextKey.ROSCA_KIND_NOTE to "A ROSCA payment counts as spending and the payout as income — both under «Dues».",
    TextKey.ROSCA_TURNS_TITLE to "Turns and dates",
    TextKey.ROSCA_ALL_TURNS to "All turns ({0})",
    TextKey.ROSCA_ROW_MINE to "Your turn · you receive {0}",
    TextKey.ROSCA_ROW_MINE_GOT to "Your turn · you received {0}",
    TextKey.ROSCA_ROW_PAID to "Paid",
    TextKey.ROSCA_ROW_SAVED to "Holds {0} for you",
    TextKey.ROSCA_ROW_OWED to "You owe {0}",
    TextKey.ROSCA_ROW_EVEN to "Even",
    TextKey.ROSCA_ANALYSIS to "Analysis",
    TextKey.ROSCA_AND to " and ",
    TextKey.ROSCA_ST_PAYOUT_DATE to "Your payout date",
    TextKey.ROSCA_ST_GAIN to "Gain versus saving alone",
    TextKey.ROSCA_ST_GAIN_NEEDS_TURN to "Needs your turn",
    TextKey.ROSCA_ST_GAIN_EVEN to "You get back what you pay",
    TextKey.ROSCA_ST_GAIN_PROFIT to "Profit",
    TextKey.ROSCA_ST_GAIN_FEES to "Fees on you",
    TextKey.ROSCA_ST_TOTAL_PAY to "Total you pay",
    TextKey.ROSCA_ST_UNTIL to "Until {0}",
    TextKey.ROSCA_ST_TOTAL_GET to "Total you receive",
    TextKey.ROSCA_ST_IN to "In {0}",
    TextKey.ROSCA_ST_BEFORE to "Payments before payout",
    TextKey.ROSCA_ST_BEFORE_NOTE to "The ROSCA saves for you",
    TextKey.ROSCA_ST_AFTER to "Payments after payout",
    TextKey.ROSCA_ST_AFTER_NOTE to "You pay the ROSCA back",
    TextKey.ROSCA_ST_PEAK_SAVED to "Most it holds for you",
    TextKey.ROSCA_ST_PEAK_SAVED_NOTE to "Just before your turn",
    TextKey.ROSCA_ST_PEAK_OWED to "Most you owe",
    TextKey.ROSCA_ST_PEAK_OWED_NOTE to "Right after the payout",
    TextKey.ROSCA_NOTE_KNOWN to "Worked out from the ROSCA itself: your payment, the number of turns and your turn.",
    TextKey.ROSCA_NOTE_UNKNOWN to "Once your turn is known (by a draw, say), the payout date and the gain show up. Linking the payout waits until your turn is set.",

    // ── New ROSCA wizard
    TextKey.RW_TITLE to "New ROSCA",
    TextKey.RW_STEP to "Question {0} of {1}",
    TextKey.RW_SUMMARY_STEP to "Analysis before saving",
    TextKey.RW_FIRST_HINT to "The first payment date is also the first payout date.",
    TextKey.RW_TURN_HINT to "If it is by a draw, choose «Not known yet».",
    TextKey.RW_PAYOUT_HINT to "The payout does not split evenly over your turns — type it yourself.",
    TextKey.RW_FREQ_COMMON to "Most common",
    TextKey.RW_COUNT_UP to "One more turn",
    TextKey.RW_COUNT_DOWN to "One turn less",
    TextKey.RW_ERR_FIRST to "Choose the day of the first payment.",
    TextKey.RW_ERR_TURN to "Choose your turn, or «Not known yet».",
    TextKey.RW_HERO_GET to "You receive",
    TextKey.RW_HERO_WHEN to "Your payout date",
    TextKey.RW_HERO_EACH to "{0} each turn",
    TextKey.RW_HERO_UNKNOWN_SUB to "The date and the gain show up once your turn is known.",
    TextKey.RW_LAST to "Last payment",
    TextKey.RW_ANSWERS to "Your answers — tap any to change it",
    TextKey.RW_A_NAME to "Name",
    TextKey.RW_A_COUNT to "Turns",
    TextKey.RW_A_AMOUNT to "Payment",
    TextKey.RW_A_FREQ to "How often",
    TextKey.RW_A_FIRST to "First payment",
    TextKey.RW_A_SHARE to "Shares",
    TextKey.RW_A_TURN to "Your turn",
    TextKey.RW_A_PAYOUT to "Payout",
    TextKey.RW_EDIT to "Change {0}",
    TextKey.RW_PREV to "Back",
    TextKey.RW_NEXT to "Next",
    TextKey.RW_SAVE to "Save the ROSCA",
    TextKey.RW_SAVED to "«{0}» saved — find it in ROSCAs",
    TextKey.RW_DONE to "To ROSCAs",

    // ── Subscriptions and bills
    TextKey.SUBS_TITLE to "Subscriptions and bills",
    TextKey.SUBS_NOTE to "Payments are counted automatically from the same merchant's transactions.",
    TextKey.SUBS_EMPTY_TITLE to "No subscriptions",
    TextKey.SUBS_EMPTY_BODY to "When a charge from the same merchant repeats, we suggest it here.",
    TextKey.SUBS_CAND_TITLE to "This looks like a subscription",
    TextKey.SUBS_CAND_YES to "Yes, a subscription",
    TextKey.SUBS_CAND_ADDED to "«{0}» added to subscriptions",
    TextKey.SUBS_KIND_SUB to "Subscription",
    TextKey.SUBS_KIND_BILL to "Bill",
    TextKey.SUBS_CYCLE_MONTHLY to "Monthly",
    TextKey.SUBS_CYCLE_QUARTERLY to "Every three months",
    TextKey.SUBS_CYCLE_YEARLY to "Yearly",
    TextKey.SUBS_CHIP_LATE to "Late",
    TextKey.SUBS_CHIP_SOON to "Soon",
    TextKey.SUBS_CHIP_NEXT to "Upcoming",
    TextKey.SUBS_CHIP_STOPPED to "Stopped",
    TextKey.SUBS_F_NEXT to "Next due date",
    TextKey.SUBS_STOPPED_LABEL to "Tracking stopped",
    TextKey.SUBS_STOPPED_SUB to "It will not show in Dues and we will not remind you of it.",
    TextKey.SUBS_LATE_BY to "Late, {0}",
    TextKey.SUBS_NEXT_SUB to "{0}, expected {1}",
    TextKey.SUBS_PAID_12 to "Paid in the last year",
    TextKey.SUBS_PAYMENTS_NONE to "No payments yet",
    TextKey.SUBS_PAYMENTS_ONE to "1 payment",
    TextKey.SUBS_PAYMENTS_TWO to "2 payments",
    TextKey.SUBS_PAYMENTS_FEW to "{0} payments",
    TextKey.SUBS_PAYMENTS_MANY to "{0} payments",
    TextKey.SUBS_ANNUAL to "Expected per year",
    TextKey.SUBS_ANNUAL_NOTE to "{0} × {1}",
    TextKey.SUBS_OUT_OF_CALC to "Not counted",
    TextKey.SUBS_DATES to "Dates",
    TextKey.SUBS_F_CYCLE to "Cycle",
    TextKey.SUBS_F_EXPECTED to "Expected amount",
    TextKey.SUBS_F_AMOUNT to "Expected amount per cycle",
    TextKey.SUBS_EDIT to "Edit the amount, cycle and date",
    TextKey.SUBS_EDIT_LOCKED to "Resume tracking first to edit it",
    TextKey.SUBS_EDIT_TITLE to "Edit «{0}»",
    TextKey.SUBS_EDIT_SAVED to "Change saved",
    TextKey.SUBS_SAVE to "Save",
    TextKey.SUBS_PAY_NOTE to "Counted automatically from «{0}» transactions — no manual payments.",
    TextKey.SUBS_STOP to "Stop tracking",
    TextKey.SUBS_STOP_NOTE to "Past transactions stay as they are.",
    TextKey.SUBS_STOP_TITLE to "Stop tracking «{0}»?",
    TextKey.SUBS_STOP_BODY to "It will not show in Dues and we will not remind you of it. You can resume it any time.",
    TextKey.SUBS_STOP_YES to "Stop it",
    TextKey.SUBS_STOPPED to "Tracking stopped",
    TextKey.SUBS_RESUME to "Resume tracking",
    TextKey.SUBS_RESUMED to "Tracking resumed",
)
