package app.masroufy.core

/**
 * منطقة «المستحقات» — الجزء الثاني بالمصري (مصر — OVERRIDES §66): من لوحات النموذج بنسخة `space = مصر` بالحرف.
 * نفس مفاتيح ومتغيرات `TextsAreaDuesPlans.kt`. **ممنوع «·» جنب رقم عربي** ⇒ «،».
 */
internal val EGYPTIAN_DUES_PLANS_TEXTS: Map<TextKey, String> = mapOf(
    // ── «الأقساط»
    TextKey.INSTALLMENTS_TITLE to "الأقساط",
    TextKey.INSTALLMENTS_NEW to "خطة جديدة",
    TextKey.INSTALLMENTS_LEFT to "الباقي عليك في الأقساط",
    TextKey.INSTALLMENTS_NOTE to "القسط كله بيتحسب مصروف وقت ما بيتدفع.",
    TextKey.INSTALLMENTS_RECEIVED to "المبلغ اللي استلمته",
    TextKey.INSTALLMENTS_EMPTY_TITLE to "مفيش أقساط",
    TextKey.INSTALLMENTS_EMPTY_BODY to "ضيف قسط بنك أو تقسيط مشتريات وهنتابعلك مواعيده.",
    TextKey.INST_PLANS_ONE to "خطة واحدة",
    TextKey.INST_PLANS_TWO to "خطتين",
    TextKey.INST_PLANS_FEW to "{0} خطط",
    TextKey.INST_PLANS_MANY to "{0} خطة",
    TextKey.INST_KIND_FINANCING to "تمويل من البنك",
    TextKey.INST_KIND_PURCHASE to "تقسيط مشتريات",
    TextKey.INST_WITH_PROFIT to "فيه أرباح",
    TextKey.INST_PAID_OF to "دفعت {0} من {1}",
    TextKey.INST_NEXT to "الجاي {0}",
    TextKey.INST_NEXT_N to "الجاي {0}، القسط {1}",
    TextKey.INST_LATE_SINCE to "متأخر من {0}",
    TextKey.INST_DONE to "خلصت الأقساط",
    TextKey.INST_NOT_LINKED to "لسه ما اتربطش",

    // ── «تفاصيل القسط»
    TextKey.INST_EDIT to "عدّل الخطة",
    TextKey.INST_LEFT to "الباقي عليك",
    TextKey.INST_DONE_HERO to "خلصت الأقساط",
    TextKey.INST_LINE to "القسط {0} {1} · الإجمالي {2}",
    TextKey.INST_SCHEDULE to "الجدول",
    TextKey.INST_YEAR_LABEL to "السنة {0}، {1} – {2}",
    TextKey.INST_RANGE to "{0} – {1}",
    TextKey.INST_LEG_PAID to "اتدفع",
    TextKey.INST_LEG_LATE to "متأخر",
    TextKey.INST_LEG_NEXT to "الجاي",
    TextKey.INST_LEG_UP to "باقي",
    TextKey.INST_SCHED_ARIA to "اتدفع {0} من {1}، ومتأخر {2}",
    TextKey.INST_SCHED_ARIA_NOLATE to "اتدفع {0} من {1}",
    TextKey.INST_LAST_LINE to "آخر قسط {0}، {1} يوم {2}",
    TextKey.INST_RECV_HINT to "اربط عملية الإيداع وهيبان اللي وصلك فعلًا.",
    TextKey.INST_RECV_NA to "مش متاح",
    TextKey.INST_RECV_NA_SUB to "تقسيط مشتريات — مافيهوش فلوس بتستلمها.",
    TextKey.INST_UNLINK to "فك الربط",
    TextKey.INST_UNLINK_RECV_TITLE to "تفك ربط مبلغ التمويل؟",
    TextKey.INST_PROFIT_TITLE to "أرباح التمويل",
    TextKey.INST_INFO_ONLY to "معلومة بس",
    TextKey.INST_TOTAL_PAY to "إجمالي اللي هتدفعه",
    TextKey.INST_PRINCIPAL to "المبلغ الأصلي",
    TextKey.INST_PROFIT to "أرباح التمويل",
    TextKey.INST_PROFIT_PAID to "منها اتدفع لحد دلوقتي",
    TextKey.INST_PROFIT_LEFT to "منها فاضل",
    TextKey.INST_PROFIT_PER to "في كل قسط تقريبًا",
    TextKey.INST_NOTE_FIN to "القسط كله ({0}) بيتحسب مصروف في «المستحقات ← تمويل»، فالأرباح ما بتتضافش للمصروف تاني.",
    TextKey.INST_NOTE_BUY to "القسط كله بيتحسب مصروف في «المستحقات ← تقسيط مشتريات».",

    // ── «خطة جديدة» / «تعديل الخطة»
    TextKey.INST_EDIT_TITLE_NEW to "خطة جديدة",
    TextKey.INST_EDIT_TITLE to "تعديل الخطة",
    TextKey.INST_EDIT_SUB_NEW to "قسط بنك أو تقسيط مشتريات",
    TextKey.INST_F_NAME to "الاسم",
    TextKey.INST_F_NAME_HINT to "مثلًا: قسط العربية",
    TextKey.INST_F_PROVIDER to "الجهة",
    TextKey.INST_F_PROVIDER_HINT to "البنك أو المحل",
    TextKey.INST_F_KIND to "النوع",
    TextKey.INST_KIND_FIN_HINT to "استلمت فلوس من الجهة",
    TextKey.INST_KIND_BUY_HINT to "اشتريت حاجة بالتقسيط",
    TextKey.INST_F_CURRENCY to "العملة",
    TextKey.INST_F_CURRENCY_HINT to "عملة المساحة دي",
    TextKey.INST_F_PRINCIPAL_FIN to "المبلغ الأصلي (اللي استلمته)",
    TextKey.INST_F_PRINCIPAL_BUY to "تمن الحاجة",
    TextKey.INST_F_TOTAL to "إجمالي اللي هتدفعه",
    TextKey.INST_F_INSTALLMENT to "القسط",
    TextKey.INST_F_CYCLE to "كل كام شهر",
    TextKey.INST_F_FIRST to "أول ميعاد",
    TextKey.INST_EDIT_NOTE_FIN to "القسط كله بيتحسب مصروف في «المستحقات ← تمويل»، والأرباح معلومة بس.",
    TextKey.INST_EDIT_NOTE_BUY to "القسط كله بيتحسب مصروف في «المستحقات ← تقسيط مشتريات».",
    TextKey.INST_SAVE_NEW to "ضيف الخطة",
    TextKey.INST_SAVE to "احفظ التعديلات",
    TextKey.INST_SAVE_ERR to "راجع الخانات اللي عليها أحمر.",
    TextKey.INST_SAVED_NEW to "اتضافت «{0}» — هتلاقيها في الأقساط",
    TextKey.INST_SAVED to "اتحفظت التعديلات — الجدول بيتحدّث من أول ميعاد",
    TextKey.INST_DONE_NEW to "للأقساط",
    TextKey.INST_DONE_EDIT to "ارجع للخطة",

    // ── «الجمعيات» و«تفاصيل الجمعية»
    TextKey.ROSCAS_TITLE to "الجمعيات",
    TextKey.ROSCAS_NEW to "جمعية جديدة",
    TextKey.ROSCAS_EMPTY_TITLE to "مفيش جمعيات",
    TextKey.ROSCAS_EMPTY_BODY to "ضيف جمعية وهنحسبلك دفعت كام وقبضت كام.",
    TextKey.ROSCAS_TERMS to "{0} · {1} {2}",
    TextKey.ROSCA_TERMS_TO to "{0} · بتدفع لـ{1}",
    TextKey.ROSCAS_PAID to "دفعت",
    TextKey.ROSCAS_GOT to "قبضت",
    TextKey.ROSCAS_GAIN to "المكسب",
    TextKey.ROSCA_TURNS_ONE to "دور واحد",
    TextKey.ROSCA_TURNS_TWO to "دورين",
    TextKey.ROSCA_TURNS_FEW to "{0} أدوار",
    TextKey.ROSCA_TURNS_MANY to "{0} دور",
    TextKey.ROSCA_TURN_N to "دور رقم {0}",
    TextKey.ROSCA_TURNS_N2 to "دور {0} و{1}",
    TextKey.ROSCA_TURN_UNKNOWN_LINE to "دورك لسه ما اتعرفش",
    TextKey.ROSCA_PHASE_SAVING to "ادخار",
    TextKey.ROSCA_PHASE_REPAYING to "سداد",
    TextKey.ROSCA_PHASE_DONE to "خلصت",
    TextKey.ROSCA_POS_SAVED to "الجمعية شايلالك {0}",
    TextKey.ROSCA_POS_OWED to "عليك للجمعية {0}",
    TextKey.ROSCA_POS_DONE to "خلصت من غير مكسب ولا خسارة",
    TextKey.ROSCA_POS_ZERO to "لا ليك ولا عليك",
    TextKey.ROSCA_GAIN_NONE to "ولا حاجة",
    TextKey.ROSCA_HERO_SAVED to "الجمعية شايلالك",
    TextKey.ROSCA_HERO_OWED to "عليك للجمعية",
    TextKey.ROSCA_KIND_NOTE to "قسط الجمعية بيتحسب مصروف، والقبض دخل — الاتنين تحت «المستحقات».",
    TextKey.ROSCA_TURNS_TITLE to "الأدوار ومواعيدها",
    TextKey.ROSCA_ALL_TURNS to "كل الأدوار ({0})",
    TextKey.ROSCA_ROW_MINE to "دورك · هتقبض {0}",
    TextKey.ROSCA_ROW_MINE_GOT to "دورك · قبضت {0}",
    TextKey.ROSCA_ROW_PAID to "اتدفع",
    TextKey.ROSCA_ROW_SAVED to "شايلالك {0}",
    TextKey.ROSCA_ROW_OWED to "عليك {0}",
    TextKey.ROSCA_ROW_EVEN to "لا ليك ولا عليك",
    TextKey.ROSCA_ANALYSIS to "التحليل",
    TextKey.ROSCA_AND to " و",
    TextKey.ROSCA_ST_PAYOUT_DATE to "ميعاد قبضك",
    TextKey.ROSCA_ST_GAIN to "المكسب لو حوّشت لوحدك",
    TextKey.ROSCA_ST_GAIN_NEEDS_TURN to "محتاج دورك",
    TextKey.ROSCA_ST_GAIN_EVEN to "هتقبض قد اللي دفعته",
    TextKey.ROSCA_ST_GAIN_PROFIT to "مكسب",
    TextKey.ROSCA_ST_GAIN_FEES to "رسوم عليك",
    TextKey.ROSCA_ST_TOTAL_PAY to "إجمالي اللي هتدفعه",
    TextKey.ROSCA_ST_UNTIL to "لحد {0}",
    TextKey.ROSCA_ST_TOTAL_GET to "إجمالي اللي هتقبضه",
    TextKey.ROSCA_ST_IN to "في {0}",
    TextKey.ROSCA_ST_BEFORE to "أقساط قبل القبض",
    TextKey.ROSCA_ST_BEFORE_NOTE to "الجمعية بتحوّشلك",
    TextKey.ROSCA_ST_AFTER to "أقساط بعد القبض",
    TextKey.ROSCA_ST_AFTER_NOTE to "بتسدّد للجمعية",
    TextKey.ROSCA_ST_PEAK_SAVED to "أكبر مبلغ شايلاهولك",
    TextKey.ROSCA_ST_PEAK_SAVED_NOTE to "قبل دورك على طول",
    TextKey.ROSCA_ST_PEAK_OWED to "أكبر دين عليك",
    TextKey.ROSCA_ST_PEAK_OWED_NOTE to "بعد ما تقبض على طول",
    TextKey.ROSCA_NOTE_KNOWN to "محسوب من الجمعية نفسها: قسطك وعدد الأدوار ودورك.",
    TextKey.ROSCA_NOTE_UNKNOWN to "لما تعرف دورك (بالقرعة مثلًا) هيبان ميعاد القبض والمكسب. ربط قبض الدور مقفول لحد ما دورك يتحدد.",

    // ── معالج «جمعية جديدة»
    TextKey.RW_TITLE to "جمعية جديدة",
    TextKey.RW_STEP to "سؤال {0} من {1}",
    TextKey.RW_SUMMARY_STEP to "التحليل قبل الحفظ",
    TextKey.RW_FIRST_HINT to "ميعاد أول دفعة هو نفسه ميعاد قبض الدور الأول.",
    TextKey.RW_TURN_HINT to "لو لسه بالقرعة اختار «لسه ما اتعرفش».",
    TextKey.RW_PAYOUT_HINT to "قيمة الدور مش بتتقسم بالظبط على أدوارك — اكتبها بنفسك.",
    TextKey.RW_FREQ_COMMON to "الأشهر في الجمعيات",
    TextKey.RW_COUNT_UP to "زوّد دور",
    TextKey.RW_COUNT_DOWN to "قلّل دور",
    TextKey.RW_ERR_FIRST to "اختار يوم أول دفعة.",
    TextKey.RW_ERR_TURN to "اختار دورك، أو «لسه ما اتعرفش».",
    TextKey.RW_HERO_GET to "هتقبض",
    TextKey.RW_HERO_WHEN to "ميعاد قبضك",
    TextKey.RW_HERO_EACH to "{0} في كل دور",
    TextKey.RW_HERO_UNKNOWN_SUB to "لما دورك يتعرف هيبان الميعاد والمكسب.",
    TextKey.RW_LAST to "آخر قسط",
    TextKey.RW_ANSWERS to "إجاباتك — دوس على أي واحدة تغيّرها",
    TextKey.RW_A_NAME to "الاسم",
    TextKey.RW_A_COUNT to "الأدوار",
    TextKey.RW_A_AMOUNT to "القسط",
    TextKey.RW_A_FREQ to "كل قد إيه",
    TextKey.RW_A_FIRST to "أول دفعة",
    TextKey.RW_A_SHARE to "الأسهم",
    TextKey.RW_A_TURN to "دورك",
    TextKey.RW_A_PAYOUT to "قيمة الدور",
    TextKey.RW_EDIT to "غيّر {0}",
    TextKey.RW_PREV to "اللي قبله",
    TextKey.RW_NEXT to "التالي",
    TextKey.RW_SAVE to "احفظ الجمعية",
    TextKey.RW_SAVED to "اتحفظت «{0}» — هتلاقيها في الجمعيات",
    TextKey.RW_DONE to "روح للجمعيات",

    // ── «الاشتراكات والفواتير» و«تفاصيل الاشتراك»
    TextKey.SUBS_TITLE to "الاشتراكات والفواتير",
    TextKey.SUBS_NOTE to "المدفوعات بتتحسب من عمليات نفس التاجر لوحدها.",
    TextKey.SUBS_EMPTY_TITLE to "مفيش اشتراكات",
    TextKey.SUBS_EMPTY_BODY to "لما خصم يتكرر من نفس التاجر هنقترحه هنا.",
    TextKey.SUBS_CAND_TITLE to "لقينا حاجة شكلها اشتراك",
    TextKey.SUBS_CAND_YES to "أيوه اشتراك",
    TextKey.SUBS_CAND_ADDED to "اتضاف «{0}» للاشتراكات",
    TextKey.SUBS_KIND_SUB to "اشتراك",
    TextKey.SUBS_KIND_BILL to "فاتورة",
    TextKey.SUBS_CYCLE_MONTHLY to "كل شهر",
    TextKey.SUBS_CYCLE_QUARTERLY to "كل تلات شهور",
    TextKey.SUBS_CYCLE_YEARLY to "كل سنة",
    TextKey.SUBS_CHIP_LATE to "متأخرة",
    TextKey.SUBS_CHIP_SOON to "قرّبت",
    TextKey.SUBS_CHIP_NEXT to "جاية",
    TextKey.SUBS_CHIP_STOPPED to "متوقف",
    TextKey.SUBS_F_NEXT to "الميعاد الجاي",
    TextKey.SUBS_STOPPED_LABEL to "المتابعة متوقفة",
    TextKey.SUBS_STOPPED_SUB to "مش هيظهر في المستحقات ومش هننبهك بميعاده.",
    TextKey.SUBS_LATE_BY to "متأخرة {0}",
    TextKey.SUBS_NEXT_SUB to "{0}، المتوقع {1}",
    TextKey.SUBS_PAID_12 to "دفعت في آخر سنة",
    TextKey.SUBS_PAYMENTS_NONE to "لسه مفيش دفعات",
    TextKey.SUBS_PAYMENTS_ONE to "دفعة واحدة",
    TextKey.SUBS_PAYMENTS_TWO to "دفعتين",
    TextKey.SUBS_PAYMENTS_FEW to "{0} دفعات",
    TextKey.SUBS_PAYMENTS_MANY to "{0} دفعة",
    TextKey.SUBS_ANNUAL to "المتوقع في السنة",
    TextKey.SUBS_ANNUAL_NOTE to "{0} × {1}",
    TextKey.SUBS_OUT_OF_CALC to "مش داخل في الحساب",
    TextKey.SUBS_DATES to "المواعيد",
    TextKey.SUBS_F_CYCLE to "الدورة",
    TextKey.SUBS_F_EXPECTED to "المبلغ المتوقع",
    TextKey.SUBS_F_AMOUNT to "المبلغ المتوقع كل دورة",
    TextKey.SUBS_EDIT to "عدّل المبلغ والدورة والميعاد",
    TextKey.SUBS_EDIT_LOCKED to "رجّع المتابعة الأول عشان تعدّل",
    TextKey.SUBS_EDIT_TITLE to "تعديل «{0}»",
    TextKey.SUBS_EDIT_SAVED to "اتحفظ التعديل",
    TextKey.SUBS_SAVE to "احفظ",
    TextKey.SUBS_PAY_NOTE to "بتتحسب لوحدها من عمليات «{0}» — مفيش تسجيل دفعة بإيدك.",
    TextKey.SUBS_STOP to "وقّف المتابعة",
    TextKey.SUBS_STOP_NOTE to "العمليات اللي فاتت بتفضل زي ما هي.",
    TextKey.SUBS_STOP_TITLE to "توقّف متابعة «{0}»؟",
    TextKey.SUBS_STOP_BODY to "مش هيظهر في المستحقات ومش هننبهك بميعاده. تقدر ترجّعه في أي وقت.",
    TextKey.SUBS_STOP_YES to "وقّفه",
    TextKey.SUBS_STOPPED to "اتوقفت المتابعة",
    TextKey.SUBS_RESUME to "رجّع المتابعة",
    TextKey.SUBS_RESUMED to "رجعت المتابعة",
)
