package app.masroufy.core

/**
 * نصوص التقويم والمبالغ المحجوزة وتجهيزات الحدث (OVERRIDES §65) باللغتين — بيتدمجوا في `ARABIC_TEXTS` و`ENGLISH_TEXTS`.
 * أسامي البنود المقترحة اختيار Claude (المالك يزود أو يشيل)، والإنجليزي كتابة Claude ومستني مراجعة المالك (§40).
 */
internal val ARABIC_CALENDAR_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.CAL_TITLE_PAYDAY to "يوم المرتب",
    TextKey.CAL_TITLE_ZAKAT to "ميعاد الزكاة",
    TextKey.CAL_TITLE_PROJECT_DEADLINE to "آخر ميعاد «{0}»",
    TextKey.PUBLIC_RAMADAN_START to "بداية رمضان",
    TextKey.PUBLIC_EID_AL_FITR to "عيد الفطر",
    TextKey.PUBLIC_EID_AL_ADHA to "عيد الأضحى",
    TextKey.PUBLIC_OCCASION_SOURCE to "حسب تقويم أم القرى — الميعاد الرسمي بيتعلن بالرؤية وممكن يفرق يوم",
    TextKey.RESERVATION_NONE to "مش محسوب",
    TextKey.RESERVATION_ONLY to "محسوب {0}",
    TextKey.RESERVATION_OF to "محسوب {0} من {1}",
    TextKey.RESERVATION_AMOUNT to "المبلغ المحسوب لازم يبقى أكبر من صفر",
    TextKey.RESERVATION_RECEIVE to "الحساب للمواعيد اللي هتدفع فيها — دي فلوس جاية ليك",
    TextKey.RESERVATION_ITEM_NOT_FOUND to "الميعاد ده مش في التقويم",
    TextKey.RESERVATION_NOT_FOUND to "الميعاد ده مش محسوب من فلوسك",
    TextKey.RESERVATION_PAST to "الميعاد ده عدّى — بيتحسب الجاي بس",
    TextKey.RESERVATION_AMOUNT_NEEDED to "الميعاد ده مالوش مبلغ معروف — اكتب المبلغ اللي هيتحسب",
    TextKey.LEFTOVER_MONTH_END to "فاضلك تقريبًا آخر الشهر",
    TextKey.LEFTOVER_FROM_WHAT_YOU_HAVE to "فاضلك تصرف من اللي معاك",
    TextKey.LEFTOVER_NEXT_PAY to "فاضلك تقريبًا لحد القبض الجاي",
    TextKey.PREP_NAME_LENGTH to "اسم البند لازم يبقى من حرف لـ{0} حرف",
    TextKey.PREP_NAME_DUPLICATE to "فيه بند بنفس الاسم في الحدث ده",
    TextKey.PREP_NOT_ALLOWED to "العزا مالوش تجهيزات",
    TextKey.PREP_ITEM_NOT_FOUND to "البند مش موجود",
    TextKey.PREP_PLANNED_POSITIVE to "مبلغ البند لازم يبقى أكبر من صفر — أو سيبه فاضي",
    TextKey.PREP_LINK_SPEND_ONLY to "البند بيتربط بمصروف الحدث بس — النقطة مش تجهيز",
    TextKey.PREP_ITEM_OTHER_EVENT to "البند ده من حدث تاني",
    TextKey.PROJECT_DEADLINE_INVALID to "آخر ميعاد للمشروع مش تاريخ صالح",
    TextKey.BACKUP_GROUP_RESERVATIONS to "المبالغ المحجوزة",
    TextKey.BACKUP_GROUP_EVENT_PREP to "تجهيزات الأحداث",
    TextKey.PREP_HALL to "القاعة",
    TextKey.PREP_OUTFIT to "اللبس",
    TextKey.PREP_CATERING to "الأكل والضيافة",
    TextKey.PREP_PHOTOGRAPHY to "التصوير",
    TextKey.PREP_INVITATIONS to "الدعوات",
    TextKey.PREP_SALON to "الكوافير",
    TextKey.PREP_HONEYMOON to "شهر العسل",
    TextKey.PREP_ENGAGEMENT_GOLD to "الشبكة",
    TextKey.PREP_VENUE to "المكان",
    TextKey.PREP_HOSPITAL to "المستشفى",
    TextKey.PREP_BABY_SUPPLIES to "مستلزمات المولود",
    TextKey.PREP_SEBOU to "السبوع",
    TextKey.PREP_GUESTS to "ضيافة الزوار",
    TextKey.PREP_TICKETS to "التذاكر",
    TextKey.PREP_LODGING to "السكن",
    TextKey.PREP_VISA to "التأشيرة",
    TextKey.PREP_LOCAL_TRANSPORT to "المواصلات هناك",
    TextKey.PREP_FOOD to "الأكل",
    TextKey.PREP_GIFTS_TO_BRING to "الهدايا",
    TextKey.PREP_SURGERY to "العملية",
    TextKey.PREP_TESTS to "التحاليل والأشعة",
    TextKey.PREP_MEDICINE to "الأدوية",
    TextKey.PREP_FOLLOW_UP to "المتابعة بعدها",
    TextKey.PREP_TRANSPORT to "المواصلات",
    TextKey.PREP_EID_CLOTHES to "لبس العيد",
    TextKey.PREP_EIDIYA to "العيدية",
    TextKey.PREP_SWEETS to "الحلويات والضيافة",
    TextKey.PREP_OUTINGS to "الخروجات",
    TextKey.PREP_TUITION to "المصاريف الدراسية",
    TextKey.PREP_BOOKS to "الكتب والأدوات",
    TextKey.PREP_UNIFORM to "الزي",
    TextKey.PREP_CELEBRATION to "الحفلة",
)

internal val ENGLISH_CALENDAR_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.CAL_TITLE_PAYDAY to "Payday",
    TextKey.CAL_TITLE_ZAKAT to "Zakat due",
    TextKey.CAL_TITLE_PROJECT_DEADLINE to "“{0}” deadline",
    TextKey.PUBLIC_RAMADAN_START to "Start of Ramadan",
    TextKey.PUBLIC_EID_AL_FITR to "Eid al-Fitr",
    TextKey.PUBLIC_EID_AL_ADHA to "Eid al-Adha",
    TextKey.PUBLIC_OCCASION_SOURCE to "Per the Umm al-Qura calendar — the official date follows the moon sighting and may differ by a day",
    TextKey.RESERVATION_NONE to "Not counted",
    TextKey.RESERVATION_ONLY to "{0} counted",
    TextKey.RESERVATION_OF to "{0} of {1} counted",
    TextKey.RESERVATION_AMOUNT to "The counted amount must be above zero",
    TextKey.RESERVATION_RECEIVE to "Counting is for dates you pay — this is money coming to you",
    TextKey.RESERVATION_ITEM_NOT_FOUND to "This date is not on the calendar",
    TextKey.RESERVATION_NOT_FOUND to "This date is not counted against your money",
    TextKey.RESERVATION_PAST to "This date has passed — only upcoming dates are counted",
    TextKey.RESERVATION_AMOUNT_NEEDED to "This date has no known amount — type the amount to count",
    TextKey.LEFTOVER_MONTH_END to "Roughly left by month end",
    TextKey.LEFTOVER_FROM_WHAT_YOU_HAVE to "Left to spend from what you have",
    TextKey.LEFTOVER_NEXT_PAY to "Roughly left until your next pay",
    TextKey.PREP_NAME_LENGTH to "The item name must be 1 to {0} characters",
    TextKey.PREP_NAME_DUPLICATE to "This event already has an item with this name",
    TextKey.PREP_NOT_ALLOWED to "Condolences have no preparations",
    TextKey.PREP_ITEM_NOT_FOUND to "Item not found",
    TextKey.PREP_PLANNED_POSITIVE to "The item amount must be above zero — or leave it empty",
    TextKey.PREP_LINK_SPEND_ONLY to "Items link to event spending only — a gift is not a preparation",
    TextKey.PREP_ITEM_OTHER_EVENT to "This item belongs to another event",
    TextKey.PROJECT_DEADLINE_INVALID to "The project deadline is not a valid date",
    TextKey.BACKUP_GROUP_RESERVATIONS to "Reserved amounts",
    TextKey.BACKUP_GROUP_EVENT_PREP to "Event preparations",
    TextKey.PREP_HALL to "Venue hall",
    TextKey.PREP_OUTFIT to "Outfits",
    TextKey.PREP_CATERING to "Food and hospitality",
    TextKey.PREP_PHOTOGRAPHY to "Photography",
    TextKey.PREP_INVITATIONS to "Invitations",
    TextKey.PREP_SALON to "Hair and makeup",
    TextKey.PREP_HONEYMOON to "Honeymoon",
    TextKey.PREP_ENGAGEMENT_GOLD to "Engagement jewelry",
    TextKey.PREP_VENUE to "Venue",
    TextKey.PREP_HOSPITAL to "Hospital",
    TextKey.PREP_BABY_SUPPLIES to "Baby supplies",
    TextKey.PREP_SEBOU to "Sebou celebration",
    TextKey.PREP_GUESTS to "Hosting visitors",
    TextKey.PREP_TICKETS to "Tickets",
    TextKey.PREP_LODGING to "Accommodation",
    TextKey.PREP_VISA to "Visa",
    TextKey.PREP_LOCAL_TRANSPORT to "Getting around there",
    TextKey.PREP_FOOD to "Food",
    TextKey.PREP_GIFTS_TO_BRING to "Gifts",
    TextKey.PREP_SURGERY to "The operation",
    TextKey.PREP_TESTS to "Tests and scans",
    TextKey.PREP_MEDICINE to "Medicine",
    TextKey.PREP_FOLLOW_UP to "Follow-up",
    TextKey.PREP_TRANSPORT to "Transport",
    TextKey.PREP_EID_CLOTHES to "Eid clothes",
    TextKey.PREP_EIDIYA to "Eidiya",
    TextKey.PREP_SWEETS to "Sweets and hospitality",
    TextKey.PREP_OUTINGS to "Outings",
    TextKey.PREP_TUITION to "Tuition",
    TextKey.PREP_BOOKS to "Books and supplies",
    TextKey.PREP_UNIFORM to "Uniform",
    TextKey.PREP_CELEBRATION to "Celebration",
)
