package app.masroufy.core

/** نصوص الواجهة المشتركة **بالإنجليزي** — كتابة Claude ومستنية مراجعة المالك (OVERRIDES §40). نفس مفاتيح `TextsShell.kt` و`TextsShellAuth.kt`. */
internal val ENGLISH_SHELL_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.TAB_HOME to "Home",
    UiKey.TAB_OPERATIONS to "Transactions",
    UiKey.TAB_PEOPLE to "People",
    UiKey.TAB_INVESTMENT to "Investment",
    UiKey.SHELL_NAV to "Navigation",
    UiKey.SHELL_GEAR to "More and settings",
    UiKey.SHELL_BACK to "Back",
    UiKey.SHELL_CLOSE to "Close",
    UiKey.SHELL_NEW_DOT to "New",
    UiKey.SHELL_TAB_WITH_NEW to "{0} — new",
    UiKey.SHELL_OFFLINE to "No internet — showing what's saved on your phone, which may not be the latest.",
    UiKey.SHELL_OPENING to "Getting your data ready…",
    UiKey.SHELL_OPENING_PROGRESS to "{0} of {1}",
    UiKey.SHELL_PENDING_SCREEN to "This screen is being built.",
    UiKey.SHELL_LOADING to "Loading",
    UiKey.SHELL_RETRY to "Try again",
    UiKey.SHELL_LOAD_FAILED to "Couldn't load.",
    UiKey.BADGE_APPROX to "Approx.",
    UiKey.GREETING_MORNING_NAME to "Good morning, {0}",
    UiKey.GREETING_EVENING_NAME to "Good evening, {0}",
    UiKey.GREETING_MORNING to "Good morning",
    UiKey.GREETING_EVENING to "Good evening",
    UiKey.ME_PROFILE to "Your profile",
    UiKey.ME_PROFILE_PERCENT to "Your profile — {0}% complete",
    UiKey.WEEKDAY_MON to "Monday",
    UiKey.WEEKDAY_TUE to "Tuesday",
    UiKey.WEEKDAY_WED to "Wednesday",
    UiKey.WEEKDAY_THU to "Thursday",
    UiKey.WEEKDAY_FRI to "Friday",
    UiKey.WEEKDAY_SAT to "Saturday",
    UiKey.WEEKDAY_SUN to "Sunday",
    UiKey.WEEKDAY_SHORT_MON to "Mon",
    UiKey.WEEKDAY_SHORT_TUE to "Tue",
    UiKey.WEEKDAY_SHORT_WED to "Wed",
    UiKey.WEEKDAY_SHORT_THU to "Thu",
    UiKey.WEEKDAY_SHORT_FRI to "Fri",
    UiKey.WEEKDAY_SHORT_SAT to "Sat",
    UiKey.WEEKDAY_SHORT_SUN to "Sun",
    UiKey.MONTH_1 to "January",
    UiKey.MONTH_2 to "February",
    UiKey.MONTH_3 to "March",
    UiKey.MONTH_4 to "April",
    UiKey.MONTH_5 to "May",
    UiKey.MONTH_6 to "June",
    UiKey.MONTH_7 to "July",
    UiKey.MONTH_8 to "August",
    UiKey.MONTH_9 to "September",
    UiKey.MONTH_10 to "October",
    UiKey.MONTH_11 to "November",
    UiKey.MONTH_12 to "December",
    UiKey.DATE_DAY_MONTH to "{1} {0}",
    UiKey.DATE_WEEKDAY_DAY_MONTH to "{0}, {1}",
    UiKey.DATE_MONTH_YEAR to "{0} {1}",
    UiKey.ASK_BAR to "Ask Masroufy or tell it to do anything…",
    UiKey.ASK_MIC to "Add by voice",
    UiKey.ASK_TITLE to "Masroufy",
    UiKey.ASK_BRAND_TITLE to "Your smart money assistant",
    UiKey.ASK_DIALOG to "Chat with {0}",
    UiKey.ASK_HISTORY to "Chat history",
    UiKey.ASK_NEW to "New chat",
    UiKey.ASK_NEW_STARTED to "Started a new chat — the previous one is in history",
    UiKey.ASK_INTRO to "I'm {0}, {1}. Ask me about your money, or ask me to record an expense or split a bill.",
    UiKey.ASK_TODO_TITLE to "Things you haven't done yet",
    UiKey.ASK_TODO_NOT_READY to "Not available yet — this list isn't linked to your data in this version.",
    UiKey.ASK_TODO_BASIS to "From bank messages, recurring bills, budgets and debts.",
    UiKey.ASK_INPUT_HINT to "Type a question or ask for anything…",
    UiKey.ASK_INPUT_LABEL to "Your message to {0}",
    UiKey.ASK_SEND to "Send",
    UiKey.ASK_TALK to "Speak",
    UiKey.ASK_CLOSE to "Close chat",
    UiKey.ASK_CHIPS_FOR to "Suggestions for “{0}”",
    UiKey.ASK_NOT_READY to "The assistant isn't available yet — it needs an AI service whose provider hasn't been approved. You can browse your data from the tabs.",
    UiKey.ASK_VOICE_NOT_READY to "Adding by voice isn't available yet.",
    UiKey.ASK_CHIP_SPENT to "How much did I spend this month?",
    UiKey.ASK_CHIP_VOICE to "Add a transaction by voice",
    UiKey.ASK_CHIP_SPLIT to "Split a bill with friends",
    UiKey.ASK_CHIP_PLAN to "Am I on plan?",
    UiKey.ASK_CHIP_OWED to "How much do people owe me?",
    UiKey.ASK_CHIP_LOCK to "Where do I change the lock?",
    UiKey.ASK_TYPING to "Masroufy is typing",
    UiKey.ASK_LISTENING to "Listening…",
    UiKey.ASK_HISTORY_CLOSE to "Close history",
    UiKey.ASK_HISTORY_SEARCH to "Search your chats",
    UiKey.ASK_HISTORY_TODAY to "Today",
    UiKey.ASK_HISTORY_CURRENT to "Current",
    UiKey.ASK_HISTORY_EMPTY to "No chats yet.",
    UiKey.ASK_HISTORY_NO_MATCH to "No chats match this search.",
    UiKey.ASK_HISTORY_DELETE to "Delete “{0}”",
    UiKey.ASK_HISTORY_DELETED to "Deleted “{0}”",
    UiKey.ASK_HISTORY_UNDO to "Undo",
    UiKey.ADD_LABEL to "Add a transaction",
    UiKey.ADD_TITLE to "New transaction",
    UiKey.ADD_VOICE to "By voice",
    UiKey.ADD_KIND_TABS to "Transaction type",
    UiKey.ADD_TYPE_OUT to "Spend",
    UiKey.ADD_TYPE_IN to "Income",
    UiKey.ADD_TYPE_MOVE to "Transfer",
    UiKey.ADD_AMOUNT to "Amount",
    UiKey.ADD_CATEGORY to "Category",
    UiKey.ADD_INCOME_KIND to "Type",
    UiKey.ADD_FROM to "From?",
    UiKey.ADD_TO to "To?",
    UiKey.ADD_SAVE to "Save",
    UiKey.ADD_SAVING to "Saving…",
    UiKey.ADD_SAVED to "Saved: {0}",
    UiKey.ADD_NO_WALLET to "Add a wallet first from “More ← Wallets”.",
    UiKey.ADD_AMOUNT_INVALID to "Enter an amount above zero.",
    UiKey.BELL_TITLE to "Notifications",
    UiKey.BELL_LABEL_NEW to "Notifications — new",
    UiKey.BELL_NEW_COUNT to "{0} new",
    UiKey.BELL_ALL_READ to "All read",
    UiKey.BELL_MARK_READ to "Mark all as read",
    UiKey.BELL_ALL to "All notifications",
    UiKey.BELL_EMPTY to "No notifications now.",
    UiKey.BELL_CLOSE to "Close notifications",
    UiKey.SPACE_SWITCH_TITLE to "Switch country",
    UiKey.SPACE_SWITCH_BODY to "Each country has its own account with its wallets, numbers and currency. Switching is on this phone only and changes nothing in your data.",
    UiKey.SPACE_ACTIVE to "Current",
    UiKey.SPACE_WITH_YOU to "With you now",
    UiKey.SPACE_OPENING to "Opening…",
    UiKey.SPACE_SHARED_NOTE to "Shared across countries: your profile, payday, people, stores and tags.",
    UiKey.SPACE_MANAGE to "Manage countries",
    UiKey.SPACE_TRIGGER to "Country: {0} — tap to switch",
    UiKey.SPACE_SWITCHED to "Switched to the {0} account",
    UiKey.SPACE_SUB to "{0}, {1}",
    UiKey.CURRENCY_NAME_SAR to "Saudi riyal",
    UiKey.CURRENCY_NAME_EGP to "Egyptian pound",
    UiKey.HERO_WITH_YOU to "With you now",
    UiKey.HERO_CASH_CHIP to "Includes {0} cash",
    UiKey.HERO_BANKS_TITLE to "Where is your money now?",
    UiKey.HERO_BANKS_LABEL to "Banks in “With you now”: {0}",
    UiKey.HERO_BANK_SUB to "Bank account",
    UiKey.HERO_DIGITAL_SUB to "Digital wallet",
    UiKey.HERO_CASH_SUB to "In your pocket",
    UiKey.HERO_LOGO_NOTE to "Each bank's logo replaces the letter once the logo research is approved.",
    UiKey.HERO_NA_LINE to "A wallet's balance isn't available yet — it starts from the day it was opened in the app.",
)
