package app.masroufy.core

/** نصوص حاسبة الورث بالإنجليزي (§69) — كتابة Claude ومستنية مراجعة المالك (§40). */
internal val ENGLISH_INHERITANCE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INHERIT_LAW_SA to "Personal Status Law (1443H)",
    TextKey.INHERIT_LAW_EG_77 to "Inheritance Law No. 77 of 1943",
    TextKey.INHERIT_LAW_EG_71 to "Bequest Law No. 71 of 1946",
    TextKey.INHERIT_CITATION to "Article {0} of the {1}",
    TextKey.INHERIT_DISCLAIMER to "An approximate figure for planning; the official division is the court's heirs certificate",
    TextKey.INHERIT_HEIR_HUSBAND to "Husband",
    TextKey.INHERIT_HEIR_WIFE to "Wife",
    TextKey.INHERIT_HEIR_SON to "Son",
    TextKey.INHERIT_HEIR_DAUGHTER to "Daughter",
    TextKey.INHERIT_HEIR_FATHER to "Father",
    TextKey.INHERIT_HEIR_MOTHER to "Mother",
    TextKey.INHERIT_HEIR_GRANDFATHER to "Grandfather (father's father)",
    TextKey.INHERIT_HEIR_PATERNAL_GRANDMOTHER to "Grandmother (father's mother)",
    TextKey.INHERIT_HEIR_MATERNAL_GRANDMOTHER to "Grandmother (mother's mother)",
    TextKey.INHERIT_HEIR_SON_SON to "Son's son",
    TextKey.INHERIT_HEIR_SON_DAUGHTER to "Son's daughter",
    TextKey.INHERIT_HEIR_FULL_BROTHER to "Full brother",
    TextKey.INHERIT_HEIR_FULL_SISTER to "Full sister",
    TextKey.INHERIT_HEIR_PATERNAL_BROTHER to "Brother through the father",
    TextKey.INHERIT_HEIR_PATERNAL_SISTER to "Sister through the father",
    TextKey.INHERIT_HEIR_MATERNAL_BROTHER to "Brother through the mother",
    TextKey.INHERIT_HEIR_MATERNAL_SISTER to "Sister through the mother",
    TextKey.INHERIT_HEIR_FULL_NEPHEW to "Full brother's son",
    TextKey.INHERIT_HEIR_PATERNAL_NEPHEW to "Son of the brother through the father",
    TextKey.INHERIT_HEIR_FULL_UNCLE to "Full paternal uncle",
    TextKey.INHERIT_HEIR_PATERNAL_UNCLE to "Paternal uncle through the father",
    TextKey.INHERIT_HEIR_FULL_COUSIN to "Full paternal uncle's son",
    TextKey.INHERIT_HEIR_PATERNAL_COUSIN to "Son of the paternal uncle through the father",
    TextKey.INHERIT_NOTE_ORDER to "Order: funeral costs, then debts, then the bequest, then the heirs",
    TextKey.INHERIT_NOTE_BLOCKED to "{0} does not inherit because of the {1} (hajb)",
    TextKey.INHERIT_NOTE_AWL to "The shares add up to more than the estate, so every share was reduced in the same proportion (awl): from {0} to {1}",
    TextKey.INHERIT_NOTE_RADD to "Part of the estate was left with no one to take the rest, so it went back to the share holders other than the spouse, in proportion (radd)",
    TextKey.INHERIT_NOTE_RADD_SPOUSE to "No heir other than the {0} and no other relatives, so the {0} takes the whole estate (radd)",
    TextKey.INHERIT_NOTE_UMARIYYA to "The heirs are only the father, the mother and the {0}, so the mother takes a third of what is left after the {0}'s share (umariyya)",
    TextKey.INHERIT_NOTE_GF_MOTHER_THIRD to "With the grandfather, the mother takes a third of the whole estate, not of the rest",
    TextKey.INHERIT_NOTE_TAKMILA to "The {0} takes a sixth with the {1} to complete two thirds",
    TextKey.INHERIT_NOTE_WITH_DAUGHTERS to "The {0} takes the rest together with the daughters",
    TextKey.INHERIT_NOTE_RESIDUE_NONE to "The fixed shares took the whole estate, so nothing is left for the {0}",
    TextKey.INHERIT_NOTE_MUSHTARAKA_SHARED to "The full siblings share the maternal siblings' third equally (mushtaraka)",
    TextKey.INHERIT_NOTE_MUSHTARAKA_DROPPED to "The full siblings do not share the maternal siblings' third, and nothing is left for them",
    TextKey.INHERIT_NOTE_GF_BLOCKS_SIBLINGS to "The grandfather excludes the brothers and sisters, like the father",
    TextKey.INHERIT_NOTE_GF_SHARES to "The grandfather shares with the siblings as if he were a brother",
    TextKey.INHERIT_NOTE_GF_RESIDUE to "The grandfather takes what is left after the sisters' share",
    TextKey.INHERIT_NOTE_GF_SIXTH to "Sharing with the siblings would have given the grandfather less than a sixth, so he takes a sixth",
    TextKey.INHERIT_NOTE_DEBTS_EXCEED to "Funeral costs and debts ({0}) exceed the estate ({1}), so nothing is left for the bequest or the heirs",
    TextKey.INHERIT_NOTE_BEQUEST_CAPPED to "The bequest ({0}) is more than the available third, so only {1} was carried out",
    TextKey.INHERIT_NOTE_BEQUEST_EXCESS_CONSENTED to "The bequest is more than a third and was carried out because all the heirs agreed after the death",
    TextKey.INHERIT_NOTE_BEQUEST_HEIR_VOID to "A bequest to an heir only takes effect if the other heirs agree after the death, so it was not counted",
    TextKey.INHERIT_NOTE_BEQUEST_HEIR_CONSENTED to "The bequest to an heir was carried out because the other heirs agreed",
    TextKey.INHERIT_NOTE_BEQUEST_HEIR_VALID to "A bequest to an heir is valid within a third without the heirs' consent",
    TextKey.INHERIT_NOTE_WAJIBA to "The children of the {0} who died earlier get an obligatory bequest of {1}, taken out before the rest is divided",
    TextKey.INHERIT_NOTE_WAJIBA_CAPPED to "The share of the children who died earlier is more than a third, so their children get a third only",
    TextKey.INHERIT_NOTE_WAJIBA_GIFT to "What was given to them during his life ({0}) was deducted",
    TextKey.INHERIT_NOTE_NO_WAJIBA to "Saudi law has no obligatory bequest; the children of a son or daughter who died earlier only receive through a bequest",
    TextKey.INHERIT_NO_TEXT to "No text — ask the court: {0}",
    TextKey.INHERIT_NO_TEXT_GF_MIXED to "The grandfather is with full siblings and siblings through the father together, and Article 22 does not say how to divide in this case",
    TextKey.INHERIT_UNSUPPORTED_COUNTRY to "The inheritance calculator is available for Saudi Arabia and Egypt only",
    TextKey.INHERIT_UNSUPPORTED_ASK_DISTANT to "Did the deceased leave other relatives, such as daughters' children or maternal uncles or aunts? The answer changes the division",
    TextKey.INHERIT_UNSUPPORTED_NO_HEIRS to "None of the listed relatives inherits; the estate goes to other relatives or the treasury, which this version does not calculate",
    TextKey.INHERIT_UNSUPPORTED_PREGNANCY to "A pregnancy requires keeping a share until the birth, which this version does not calculate",
    TextKey.INHERIT_UNSUPPORTED_MISSING to "A missing heir requires keeping their share, which this version does not calculate",
    TextKey.INHERIT_UNSUPPORTED_SUCCESSIVE to "An heir who died before the division requires calculating two estates together, which this version does not do",
    TextKey.INHERIT_UNSUPPORTED_TAKHARUJ to "An agreement for one heir to leave for compensation (takharuj) is not calculated in this version",
    TextKey.INHERIT_UNSUPPORTED_PREDECEASED_SON to "No son is alive, so the children of the son who died earlier may inherit directly; enter them as son's sons and son's daughters",
    TextKey.INHERIT_INVALID_COUNT to "The number of {0} must be from 0 to {1}",
    TextKey.INHERIT_INVALID_WIVES to "Four wives at most",
    TextKey.INHERIT_INVALID_HUSBAND_WIFE to "A husband and a wife cannot be in the same case",
    TextKey.INHERIT_INVALID_ONLY_ONE to "Only one {0}",
    TextKey.INHERIT_INVALID_NO_ITEMS to "Add at least one thing to the estate",
    TextKey.INHERIT_INVALID_ITEM_NAME to "Name every thing in the estate",
    TextKey.INHERIT_INVALID_NEGATIVE to "Amounts cannot be negative",
    TextKey.INHERIT_INVALID_TOO_LARGE to "The numbers are larger than allowed",
    TextKey.INHERIT_INVALID_PREDECEASED to "Enter the number of children of the son or daughter who died earlier",
    TextKey.INHERIT_CLAIMANT_FUNERAL to "Funeral costs",
    TextKey.INHERIT_CLAIMANT_DEBTS to "Debts",
    TextKey.INHERIT_CLAIMANT_BEQUEST to "Bequest",
    TextKey.INHERIT_CLAIMANT_WAJIBA to "Obligatory bequest",
)
