package app.masroufy.core

/**
 * نصوص حاسبات «الاستثمار» (الادخار والتقاعد — OVERRIDES §69) + اسم «صفحة الإشعارات» في النسخة الشاملة:
 * فصحى مختصرة للسعودية (§66) · مصري لمصر · إنجليزي (كتابة Claude ومستني مراجعة المالك §40).
 * كل سبب «غير متاح» بيقول **إيه الناقص** — مش رقم افتراضي (القاعدة 10).
 */
internal val MSA_CALC_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.CALC_TARGET_POSITIVE to "اكتب المبلغ الذي تريد الوصول إليه (أكبر من صفر)",
    TextKey.CALC_SAVED_NOT_NEGATIVE to "المبلغ الذي معك لا يكون سالبًا",
    TextKey.CALC_DATE_AFTER_TODAY to "اختر تاريخًا بعد اليوم",
    TextKey.CALC_MONTHS_RANGE to "المدة من شهر واحد حتى {0} شهرًا",
    TextKey.CALC_MONTHLY_POSITIVE to "اكتب المبلغ الشهري (أكبر من صفر)",
    TextKey.CALC_RATE_RANGE to "المعدل السنوي خارج الحدود المقبولة",
    TextKey.CALC_WAGE_POSITIVE to "اكتب الأجر الشهري (أكبر من صفر)",
    TextKey.CALC_SERVICE_DATES to "تاريخ نهاية الخدمة يكون بعد بدايتها",
    TextKey.CALC_BIRTH_DATE to "اكتب تاريخ الميلاد (قبل اليوم)",
    TextKey.CALC_MONTHS_1422 to "شهور ما قبل 1422هـ جزء من مدة اشتراكك، فلا تزيد عليها",
    TextKey.CALC_MONTHS_AT_2024 to "شهور الاشتراك في يوليو 2024 لا تزيد على مدة اشتراكك اليوم",
    TextKey.CALC_RETIRE_AGE to "سن التقاعد غير صحيح",
    TextKey.CALC_DESIRED_POSITIVE to "اكتب المبلغ الشهري الذي تريد العيش به (أكبر من صفر)",
    TextKey.CALC_YEARS_RANGE to "عدد السنوات من 1 إلى 100",
    TextKey.CALC_UNTIL_AGE to "السن يكون بعد سن التقاعد",
    TextKey.CALC_REASON_NEED_WAGE to "غير متاح: اكتب الأجر الشهري الخاضع للاشتراك",
    TextKey.CALC_REASON_NEED_MONTHS_AT_2024 to "غير متاح: اكتب شهور اشتراكك في 3 يوليو 2024 — سن تقاعدك يتحدد منها",
    TextKey.CALC_REASON_TOO_FEW_MONTHS to "مدة الاشتراك أقل من الحد الأدنى للمعاش — التعويض بدفعة واحدة غير محسوب هنا",
    TextKey.CALC_REASON_EARLY_NOT_ALLOWED to "التقاعد المبكر بهذا السن غير مسموح بمدة اشتراكك",
    TextKey.CALC_REASON_EGYPT_NOT_READY to "غير متاح: حساب معاش مصر يحتاج جداول القانون 148 لسنة 2019 الرسمية ولم تُراجع بعد",
    TextKey.CALC_REASON_NEED_YEARS to "غير متاح: اكتب كم سنة يكفيك مال التقاعد، أو حتى أي سن",
    TextKey.CALC_REASON_NEED_PENSION to "غير متاح: المعاش المتوقع غير معروف",
    TextKey.CALC_REASON_NEED_JOB_START to "غير متاح: اكتب تاريخ بداية عملك الحالي لحساب مكافأة نهاية الخدمة",
    TextKey.CALC_REASON_NO_MONTHS_TO_SAVE to "لم يبق وقت للادخار قبل التقاعد",
    TextKey.CALC_ACTUAL_UNKNOWN to "ما تدّخره فعلًا غير متاح: أحد الأشهر الثلاثة الأخيرة بلا عمليات أو فيه عمليات لم يُحدَّد نوعها",
    TextKey.CALC_EOS_EGYPT_NOT_APPLICABLE to "لا تنطبق: في مصر لا مكافأة نهاية خدمة لمن له حق في التأمينات",
    TextKey.CALC_EOS_NO_JOB to "لا تنطبق: لا يوجد عمل حالي في مصادر الدخل",
    TextKey.CALC_GOAL_NAME_DEFAULT to "ادخار {0}",
    TextKey.BACKUP_GROUP_ALERT_INBOX to "صفحة الإشعارات",
)

internal val EGYPTIAN_CALC_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.CALC_TARGET_POSITIVE to "اكتب المبلغ اللي عايز توصله (أكبر من صفر)",
    TextKey.CALC_SAVED_NOT_NEGATIVE to "المبلغ اللي معاك ما ينفعش يبقى بالسالب",
    TextKey.CALC_DATE_AFTER_TODAY to "اختار تاريخ بعد النهارده",
    TextKey.CALC_MONTHS_RANGE to "المدة من شهر لحد {0} شهر",
    TextKey.CALC_MONTHLY_POSITIVE to "اكتب المبلغ الشهري (أكبر من صفر)",
    TextKey.CALC_RATE_RANGE to "المعدل السنوي برا الحدود المقبولة",
    TextKey.CALC_WAGE_POSITIVE to "اكتب الأجر الشهري (أكبر من صفر)",
    TextKey.CALC_SERVICE_DATES to "تاريخ نهاية الخدمة لازم يبقى بعد بدايتها",
    TextKey.CALC_BIRTH_DATE to "اكتب تاريخ الميلاد (قبل النهارده)",
    TextKey.CALC_MONTHS_1422 to "شهور ما قبل 1422هـ جزء من مدة اشتراكك، فما تزيدش عليها",
    TextKey.CALC_MONTHS_AT_2024 to "شهور الاشتراك في يوليو 2024 ما تزيدش عن مدة اشتراكك النهارده",
    TextKey.CALC_RETIRE_AGE to "سن التقاعد مش صح",
    TextKey.CALC_DESIRED_POSITIVE to "اكتب المبلغ اللي عايز تعيش بيه في الشهر (أكبر من صفر)",
    TextKey.CALC_YEARS_RANGE to "عدد السنين من 1 لـ100",
    TextKey.CALC_UNTIL_AGE to "السن لازم يبقى بعد سن التقاعد",
    TextKey.CALC_REASON_NEED_WAGE to "غير متاح: اكتب الأجر الشهري اللي عليه الاشتراك",
    TextKey.CALC_REASON_NEED_MONTHS_AT_2024 to "غير متاح: اكتب شهور اشتراكك يوم 3 يوليو 2024 — سن تقاعدك بيتحدد منها",
    TextKey.CALC_REASON_TOO_FEW_MONTHS to "مدة الاشتراك أقل من اللازم للمعاش — التعويض بدفعة واحدة مش متحسب هنا",
    TextKey.CALC_REASON_EARLY_NOT_ALLOWED to "التقاعد المبكر في السن ده مش مسموح بمدة اشتراكك",
    TextKey.CALC_REASON_EGYPT_NOT_READY to "غير متاح: حساب معاش مصر محتاج جداول قانون 148 لسنة 2019 الرسمية ولسه ما اتراجعتش",
    TextKey.CALC_REASON_NEED_YEARS to "غير متاح: اكتب فلوس التقاعد تكفيك كام سنة، أو لحد سن كام",
    TextKey.CALC_REASON_NEED_PENSION to "غير متاح: المعاش المتوقع مش معروف",
    TextKey.CALC_REASON_NEED_JOB_START to "غير متاح: اكتب تاريخ بداية شغلك الحالي عشان مكافأة نهاية الخدمة",
    TextKey.CALC_REASON_NO_MONTHS_TO_SAVE to "مفيش وقت للتحويش قبل التقاعد",
    TextKey.CALC_ACTUAL_UNKNOWN to "اللي بتحوّشه فعلًا غير متاح: شهر من التلاتة اللي فاتوا مفيهوش عمليات أو فيه عمليات نوعها لسه ما اتحددش",
    TextKey.CALC_EOS_EGYPT_NOT_APPLICABLE to "مش منطبقة: في مصر مفيش مكافأة نهاية خدمة لمين له حق في التأمينات",
    TextKey.CALC_EOS_NO_JOB to "مش منطبقة: مفيش شغل حالي في مصادر الدخل",
    TextKey.CALC_GOAL_NAME_DEFAULT to "تحويش {0}",
    TextKey.BACKUP_GROUP_ALERT_INBOX to "صفحة الإشعارات",
)

internal val ENGLISH_CALC_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.CALC_TARGET_POSITIVE to "Enter the amount you want to reach (more than zero)",
    TextKey.CALC_SAVED_NOT_NEGATIVE to "The amount you already have can't be negative",
    TextKey.CALC_DATE_AFTER_TODAY to "Pick a date after today",
    TextKey.CALC_MONTHS_RANGE to "The duration is from one month up to {0} months",
    TextKey.CALC_MONTHLY_POSITIVE to "Enter the monthly amount (more than zero)",
    TextKey.CALC_RATE_RANGE to "The yearly rate is outside the accepted range",
    TextKey.CALC_WAGE_POSITIVE to "Enter the monthly wage (more than zero)",
    TextKey.CALC_SERVICE_DATES to "The end of service must be after its start",
    TextKey.CALC_BIRTH_DATE to "Enter your date of birth (before today)",
    TextKey.CALC_MONTHS_1422 to "Months before 1422H are part of your contribution period, so they can't exceed it",
    TextKey.CALC_MONTHS_AT_2024 to "Contribution months in July 2024 can't exceed your contribution period today",
    TextKey.CALC_RETIRE_AGE to "The retirement age isn't valid",
    TextKey.CALC_DESIRED_POSITIVE to "Enter the monthly amount you want to live on (more than zero)",
    TextKey.CALC_YEARS_RANGE to "Years from 1 to 100",
    TextKey.CALC_UNTIL_AGE to "The age must be after the retirement age",
    TextKey.CALC_REASON_NEED_WAGE to "Not available: enter the monthly wage you contribute on",
    TextKey.CALC_REASON_NEED_MONTHS_AT_2024 to "Not available: enter your contribution months on 3 July 2024 — your retirement age depends on it",
    TextKey.CALC_REASON_TOO_FEW_MONTHS to "The contribution period is below the minimum for a pension — the one-time compensation isn't calculated here",
    TextKey.CALC_REASON_EARLY_NOT_ALLOWED to "Early retirement at this age isn't allowed with your contribution period",
    TextKey.CALC_REASON_EGYPT_NOT_READY to "Not available: the Egypt pension needs the official tables of Law 148 of 2019, not reviewed yet",
    TextKey.CALC_REASON_NEED_YEARS to "Not available: enter how many years the retirement money should last, or until what age",
    TextKey.CALC_REASON_NEED_PENSION to "Not available: the expected pension isn't known",
    TextKey.CALC_REASON_NEED_JOB_START to "Not available: enter the start date of your current job for the end-of-service award",
    TextKey.CALC_REASON_NO_MONTHS_TO_SAVE to "No time left to save before retirement",
    TextKey.CALC_ACTUAL_UNKNOWN to "What you actually save isn't available: one of the last three months has no transactions or has transactions without a type",
    TextKey.CALC_EOS_EGYPT_NOT_APPLICABLE to "Doesn't apply: in Egypt there's no end-of-service award for people entitled to social insurance",
    TextKey.CALC_EOS_NO_JOB to "Doesn't apply: no current job in your income sources",
    TextKey.CALC_GOAL_NAME_DEFAULT to "Saving {0}",
    TextKey.BACKUP_GROUP_ALERT_INBOX to "Alerts page",
)
