package app.masroufy.core

/**
 * نصوص الواجهة المشتركة (الهيكل · شريطي التنقل والسؤال · لوحة الإضافة · الجرس · البلد · «معك الآن» · «القادم» · التقويم · الدخول · القفل ·
 * التواريخ) — **بالفصحى المختصرة** للسعودية والافتراضي (OVERRIDES §66). منقولة من نصوص النموذج التفاعلي (`design-source/prototype` على
 * فرع التصميم) بالحرف، إلا المكتوب جنبه. المصري في `TextsShellEgyptian.kt` والإنجليزي في `TextsShellEnglish.kt` (كتابة Claude — مستني
 * مراجعة المالك §40). **ممنوع «·» جنب رقم عربي** (KOTLIN-MAP §٣) ⇒ «،».
 */
internal val MSA_SHELL_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.TAB_HOME to "الرئيسية",
    TextKey.TAB_OPERATIONS to "العمليات",
    TextKey.TAB_PEOPLE to "الأشخاص",
    TextKey.TAB_INVESTMENT to "الاستثمار",
    TextKey.SHELL_NAV to "التنقل",
    TextKey.SHELL_GEAR to "المزيد والإعدادات",
    TextKey.SHELL_BACK to "رجوع",
    TextKey.SHELL_CLOSE to "إغلاق",
    TextKey.SHELL_NEW_DOT to "يوجد جديد",
    TextKey.SHELL_TAB_WITH_NEW to "{0} — يوجد جديد",
    TextKey.SHELL_OFFLINE to "لا اتصال بالإنترنت — المعروض محفوظ على جهازك وقد لا يكون الأحدث.",
    TextKey.SHELL_OPENING to "نجهّز بياناتك…",
    TextKey.SHELL_OPENING_PROGRESS to "{0} من {1}",
    TextKey.SHELL_PENDING_SCREEN to "هذه الشاشة قيد البناء.",
    TextKey.SHELL_LOADING to "جارٍ التحميل",
    TextKey.SHELL_RETRY to "أعد المحاولة",
    TextKey.SHELL_LOAD_FAILED to "تعذّر التحميل.",
    TextKey.BADGE_APPROX to "تقريبي",
    TextKey.GREETING_MORNING_NAME to "صباح الخير، {0}",
    TextKey.GREETING_EVENING_NAME to "مساء الخير، {0}",
    TextKey.GREETING_MORNING to "صباح الخير",
    TextKey.GREETING_EVENING to "مساء الخير",
    TextKey.ME_PROFILE to "ملفك",
    TextKey.ME_PROFILE_PERCENT to "ملفك — مكتمل {0}٪",
    TextKey.WEEKDAY_MON to "الإثنين",
    TextKey.WEEKDAY_TUE to "الثلاثاء",
    TextKey.WEEKDAY_WED to "الأربعاء",
    TextKey.WEEKDAY_THU to "الخميس",
    TextKey.WEEKDAY_FRI to "الجمعة",
    TextKey.WEEKDAY_SAT to "السبت",
    TextKey.WEEKDAY_SUN to "الأحد",
    TextKey.WEEKDAY_SHORT_MON to "اثنين",
    TextKey.WEEKDAY_SHORT_TUE to "ثلاثاء",
    TextKey.WEEKDAY_SHORT_WED to "أربعاء",
    TextKey.WEEKDAY_SHORT_THU to "خميس",
    TextKey.WEEKDAY_SHORT_FRI to "جمعة",
    TextKey.WEEKDAY_SHORT_SAT to "سبت",
    TextKey.WEEKDAY_SHORT_SUN to "أحد",
    TextKey.MONTH_1 to "يناير",
    TextKey.MONTH_2 to "فبراير",
    TextKey.MONTH_3 to "مارس",
    TextKey.MONTH_4 to "أبريل",
    TextKey.MONTH_5 to "مايو",
    TextKey.MONTH_6 to "يونيو",
    TextKey.MONTH_7 to "يوليو",
    TextKey.MONTH_8 to "أغسطس",
    TextKey.MONTH_9 to "سبتمبر",
    TextKey.MONTH_10 to "أكتوبر",
    TextKey.MONTH_11 to "نوفمبر",
    TextKey.MONTH_12 to "ديسمبر",
    TextKey.DATE_DAY_MONTH to "{0} {1}",
    TextKey.DATE_WEEKDAY_DAY_MONTH to "{0}، {1}",
    TextKey.DATE_MONTH_YEAR to "{0} {1}",
    TextKey.ASK_BAR to "اسأل مصروفي أو اطلب منه أي شيء…",
    TextKey.ASK_MIC to "أضف بالصوت",
    TextKey.ASK_TITLE to "مصروفي",
    TextKey.ASK_CONTEXT to "محادثة جديدة · أنت في «{0}»",
    TextKey.ASK_GREETING_NAME to "أهلًا {0}. اسألني عن مالك، أو اطلب مني تنفيذ شيء: إضافة عملية بصوتك، تقسيم فاتورة مع أصدقائك، أو تذكيرك بموعد.",
    TextKey.ASK_GREETING to "أهلًا بك. اسألني عن مالك، أو اطلب مني تنفيذ شيء: إضافة عملية بصوتك، تقسيم فاتورة مع أصدقائك، أو تذكيرك بموعد.",
    TextKey.ASK_INPUT_HINT to "اكتب أو اضغط الميكروفون",
    TextKey.ASK_INPUT_LABEL to "رسالتك",
    TextKey.ASK_SEND to "أرسل",
    TextKey.ASK_TALK to "تكلّم",
    TextKey.ASK_CLOSE to "إغلاق المحادثة",
    // اختيار Claude: النموذج بيرد بإجابات جاهزة؛ التطبيق ما عندوش مساعد (باقة Spark ومفيش مزوّد معتمد — OVERRIDES §73) ⇒ بيقول كده بصراحة
    TextKey.ASK_NOT_READY to "المساعد غير متاح بعد — يحتاج خدمة ذكاء اصطناعي لم يُعتمد مزوّدها. يمكنك تصفّح بياناتك من التبويبات.",
    TextKey.ASK_VOICE_NOT_READY to "الإضافة بالصوت غير متاحة بعد.",
    TextKey.ASK_CHIP_SPENT to "كم صرفت هذا الشهر؟",
    TextKey.ASK_CHIP_VOICE to "أضف عملية بصوتي",
    TextKey.ASK_CHIP_SPLIT to "قسّم فاتورة مع أصدقائي",
    TextKey.ASK_CHIP_PLAN to "هل أنا على الخطة؟",
    TextKey.ASK_CHIP_OWED to "كم لي عند الناس؟",
    TextKey.ASK_CHIP_LOCK to "أين أغيّر القفل؟",
    TextKey.ASK_TYPING to "مصروفي يكتب",
    TextKey.ASK_LISTENING to "أستمع إليك…",
    TextKey.ADD_LABEL to "أضف عملية",
    TextKey.ADD_TITLE to "عملية جديدة",
    TextKey.ADD_VOICE to "بصوتك",
    TextKey.ADD_KIND_TABS to "نوع العملية",
    TextKey.ADD_TYPE_OUT to "صرف",
    TextKey.ADD_TYPE_IN to "دخل",
    TextKey.ADD_TYPE_MOVE to "تحويل",
    TextKey.ADD_AMOUNT to "المبلغ",
    TextKey.ADD_CATEGORY to "التصنيف",
    TextKey.ADD_INCOME_KIND to "النوع",
    TextKey.ADD_FROM to "من أين؟",
    TextKey.ADD_TO to "إلى أين؟",
    TextKey.ADD_SAVE to "احفظ",
    TextKey.ADD_SAVING to "جارٍ الحفظ…",
    TextKey.ADD_SAVED to "سُجّلت: {0}",
    TextKey.ADD_NO_WALLET to "أضف محفظة أولًا من «المزيد ← المحافظ».",
    TextKey.ADD_AMOUNT_INVALID to "اكتب مبلغًا أكبر من صفر.",
    TextKey.BELL_TITLE to "الإشعارات",
    TextKey.BELL_LABEL_NEW to "الإشعارات — يوجد جديد",
    TextKey.BELL_NEW_COUNT to "{0} جديدة",
    TextKey.BELL_ALL_READ to "كلها مقروءة",
    TextKey.BELL_MARK_READ to "تعليم الكل كمقروء",
    TextKey.BELL_ALL to "كل الإشعارات",
    TextKey.BELL_EMPTY to "لا إشعارات الآن.",
    TextKey.BELL_CLOSE to "إغلاق الإشعارات",
    TextKey.SPACE_SWITCH_TITLE to "تبديل البلد",
    TextKey.SPACE_SWITCH_BODY to "لكل بلد حساب منفصل بمحافظه وأرقامه وعملته. التبديل على هذا الجوال فقط، ولا يغيّر شيئًا في بياناتك.",
    TextKey.SPACE_ACTIVE to "الحالية",
    TextKey.SPACE_WITH_YOU to "معك الآن",
    TextKey.SPACE_OPENING to "جارٍ الفتح…",
    TextKey.SPACE_SHARED_NOTE to "مشترك بين البلدان: ملفك ويوم الراتب والأشخاص والتجار والوسوم.",
    TextKey.SPACE_MANAGE to "إدارة البلدان",
    TextKey.SPACE_TRIGGER to "البلد: {0} — اضغط للتبديل",
    TextKey.SPACE_SWITCHED to "انتقلت إلى حساب {0}",
    TextKey.SPACE_SUB to "{0}، {1}",
    TextKey.CURRENCY_NAME_SAR to "ريال سعودي",
    TextKey.CURRENCY_NAME_EGP to "جنيه مصري",
    TextKey.HERO_WITH_YOU to "معك الآن",
    TextKey.HERO_CASH_CHIP to "يشمل {0} كاش",
    TextKey.HERO_BANKS_TITLE to "أين ما معك الآن؟",
    TextKey.HERO_BANKS_LABEL to "البنوك المشمولة في «معك الآن»: {0}",
    TextKey.HERO_BANK_SUB to "حساب بنكي",
    TextKey.HERO_DIGITAL_SUB to "محفظة إلكترونية",
    TextKey.HERO_CASH_SUB to "الذي معك",
    TextKey.HERO_LOGO_NOTE to "يحل شعار كل بنك محل الحرف بعد اعتماد بحث الشعارات.",
    TextKey.HERO_NA_LINE to "رصيد إحدى المحافظ غير متاح بعد — يبدأ من يوم فتحها في التطبيق.",
)
