package app.masroufy.core

/**
 * نصوص شاشات منطقة «الاستثمار» (`ui/screens/investment/`) — **الملف ده بتاع المنطقة بس** (المناطق بتتبني بالتوازي، ARCHITECTURE §31.31).
 * المفاتيح في `TextKeys.kt` **تحت سطر «منطقة الاستثمار»** بس. الفصحى للسعودية والافتراضي · المصري لمصر (OVERRIDES §66) · الإنجليزي
 * (كتابة Claude — مستني مراجعة المالك §40). النص من النموذج التفاعلي بالحرف (الفصحى من `space = السعودية` والمصري من `مصر`)، إلا اللي
 * كان بيوعد بحاجة مش متبنية في كوتلن (اتشال الوعد — HANDOVER). **ممنوع «·» جنب رقم عربي** ⇒ «،».
 * الملف ده: شاشة «الاستثمار» نفسها، والباقي في `TextsAreaInvestmentAsset.kt` (تفاصيل الأصل) · `TextsAreaInvestmentTrade.kt` (لوحة الشراء
 * والبيع و«الصورة كاملة») · `TextsAreaInvestmentZakat.kt` (الزكاة ووقائعها) · `TextsAreaInvestmentPay.kt` (دفع الزكاة ويوم الحول والتحليلات).
 */
internal val MSA_AREA_INVESTMENT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INVEST_ERROR_TITLE to "تعذّر تحديث الأسعار",
    TextKey.INVEST_ERROR_BODY to "المعروض بأسعار آخر تحديث ناجح.",
    TextKey.INVEST_EMPTY_TITLE to "لا توجد أصول بعد",
    TextKey.INVEST_EMPTY_BODY to "أضف عقارًا أو ذهبًا أو أسهمًا لترى قيمتها اليوم.",
    TextKey.INVEST_ADD_ASSET to "إضافة أصل",
    TextKey.INVEST_REFRESH to "تحديث الأسعار",
    TextKey.INVEST_REFRESHED to "تحدّثت الأسعار",
    TextKey.INVEST_REFRESH_SKIPPED to "تحدّثت الأسعار — وبقي {0} من أصولك دون تحديث",
    TextKey.INVEST_TOTAL_LABEL to "إجمالي أملاكك بأسعار اليوم",
    TextKey.INVEST_TOTAL_NA_ONE to "سعر «{0}» اليوم غير متاح، فلا يكتمل الإجمالي.",
    TextKey.INVEST_TOTAL_NA_MANY to "أصول بلا سعر اليوم: {0}، فلا يكتمل الإجمالي.",
    TextKey.INVEST_COST to "التكلفة",
    TextKey.INVEST_UNREALIZED to "المكسب غير المحقق",
    TextKey.INVEST_REALIZED to "المكسب المحقق",
    TextKey.INVEST_RE_SUB_AREA to "عقار، {0} م² × {1} للمتر",
    TextKey.INVEST_RE_ASK to "كم ستساوي لو بعتها في {0}؟",
    TextKey.INVEST_RE_PRICE_THEN to "سعرها وقتها",
    TextKey.INVEST_RE_RENT_UNTIL to "+ الإيجار حتى {0}",
    TextKey.INVEST_RE_GAIN to "المكسب منذ الشراء (مع الإيجار)",
    TextKey.INVEST_RE_RATE to "بزيادة {0} سنويًا = {1}",
    TextKey.INVEST_PRICE_TODAY to "السعر اليوم",
    TextKey.INVEST_PRICE_ON to "السعر بتاريخ {0}",
    TextKey.INVEST_PRICE_OLD to "سعر قديم من {0}",
    TextKey.INVEST_PRICE_NONE to "سعر اليوم غير متاح",
    TextKey.INVEST_ARCHIVED_SUB to "مؤرشف",
    TextKey.INVEST_QTY_UNIT to "{0} {1}",
    TextKey.INVEST_ROW_SUB to "{0}، {1}",
    TextKey.INVEST_TOOL_ZAKAT to "الزكاة",
    TextKey.INVEST_TOOL_ZAKAT_HINT to "إرشادية حسب {0}",
    TextKey.INVEST_TOOL_ADVISOR to "التحليلات الذكية",
    TextKey.INVEST_TOOL_ADVISOR_HINT to "أفكار من صرفك، ولماذا ظهرت",
    TextKey.INVEST_TOOL_GOALS to "خطط الادخار",
    TextKey.INVEST_GOALS_NONE to "لا خطط بعد",
    TextKey.INVEST_GOALS_ONE to "خطة واحدة",
    TextKey.INVEST_GOALS_TWO to "خطتان",
    TextKey.INVEST_GOALS_FEW to "{0} خطط",
    TextKey.INVEST_GOALS_MANY to "{0} خطة",
    TextKey.INVEST_CALCS to "الحاسبات",
    TextKey.INVEST_CALC_SAVINGS to "الادخار",
    TextKey.INVEST_CALC_RETIREMENT to "التقاعد",
    TextKey.INVEST_CALC_INHERITANCE to "الورث",
    TextKey.INVEST_PERCENT to "{0}٪",
    TextKey.INVEST_DATE_YEAR to "{0} {1}",
) + MSA_INVEST_ASSET_TEXTS + MSA_INVEST_TRADE_TEXTS + MSA_INVEST_ZAKAT_TEXTS + MSA_INVEST_PAY_TEXTS

internal val EGYPTIAN_AREA_INVESTMENT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INVEST_ERROR_TITLE to "ما قدرناش نحدّث الأسعار",
    TextKey.INVEST_ERROR_BODY to "المعروض بأسعار آخر تحديث نجح.",
    TextKey.INVEST_EMPTY_TITLE to "مفيش أصول لسه",
    TextKey.INVEST_EMPTY_BODY to "ضيف عقار أو دهب أو أسهم عشان تشوف قيمتها النهارده.",
    TextKey.INVEST_ADD_ASSET to "إضافة أصل",
    TextKey.INVEST_REFRESH to "تحديث الأسعار",
    TextKey.INVEST_REFRESHED to "الأسعار اتحدّثت",
    TextKey.INVEST_REFRESH_SKIPPED to "الأسعار اتحدّثت — وفضل {0} من أصولك من غير تحديث",
    TextKey.INVEST_TOTAL_LABEL to "إجمالي أملاكك بأسعار النهارده",
    TextKey.INVEST_TOTAL_NA_ONE to "سعر «{0}» النهارده غير متاح، فالإجمالي مش كامل.",
    TextKey.INVEST_TOTAL_NA_MANY to "أصول من غير سعر النهارده: {0}، فالإجمالي مش كامل.",
    TextKey.INVEST_COST to "التكلفة",
    TextKey.INVEST_UNREALIZED to "المكسب اللي لسه ما اتحققش",
    TextKey.INVEST_REALIZED to "المكسب المحقق",
    TextKey.INVEST_RE_SUB_AREA to "عقار، {0} م² × {1} للمتر",
    TextKey.INVEST_RE_ASK to "هتساوي كام لو بعتها سنة {0}؟",
    TextKey.INVEST_RE_PRICE_THEN to "سعرها وقتها",
    TextKey.INVEST_RE_RENT_UNTIL to "+ الإيجار لحد {0}",
    TextKey.INVEST_RE_GAIN to "المكسب من يوم الشراء (بالإيجار)",
    TextKey.INVEST_RE_RATE to "بزيادة {0} في السنة = {1}",
    TextKey.INVEST_PRICE_TODAY to "السعر النهارده",
    TextKey.INVEST_PRICE_ON to "السعر بتاريخ {0}",
    TextKey.INVEST_PRICE_OLD to "سعر قديم من {0}",
    TextKey.INVEST_PRICE_NONE to "سعر النهارده غير متاح",
    TextKey.INVEST_ARCHIVED_SUB to "متأرشف",
    TextKey.INVEST_QTY_UNIT to "{0} {1}",
    TextKey.INVEST_ROW_SUB to "{0}، {1}",
    TextKey.INVEST_TOOL_ZAKAT to "الزكاة",
    TextKey.INVEST_TOOL_ZAKAT_HINT to "إرشادية حسب {0}",
    TextKey.INVEST_TOOL_ADVISOR to "التحليلات الذكية",
    TextKey.INVEST_TOOL_ADVISOR_HINT to "أفكار من صرفك، وليه ظهرت",
    TextKey.INVEST_TOOL_GOALS to "خطط الادخار",
    TextKey.INVEST_GOALS_NONE to "مفيش خطط لسه",
    TextKey.INVEST_GOALS_ONE to "خطة واحدة",
    TextKey.INVEST_GOALS_TWO to "خطتين",
    TextKey.INVEST_GOALS_FEW to "{0} خطط",
    TextKey.INVEST_GOALS_MANY to "{0} خطة",
    TextKey.INVEST_CALCS to "الحاسبات",
    TextKey.INVEST_CALC_SAVINGS to "الادخار",
    TextKey.INVEST_CALC_RETIREMENT to "التقاعد",
    TextKey.INVEST_CALC_INHERITANCE to "الورث",
    TextKey.INVEST_PERCENT to "{0}٪",
    TextKey.INVEST_DATE_YEAR to "{0} {1}",
) + EGYPTIAN_INVEST_ASSET_TEXTS + EGYPTIAN_INVEST_TRADE_TEXTS + EGYPTIAN_INVEST_ZAKAT_TEXTS + EGYPTIAN_INVEST_PAY_TEXTS

internal val ENGLISH_AREA_INVESTMENT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INVEST_ERROR_TITLE to "Couldn't update prices",
    TextKey.INVEST_ERROR_BODY to "Showing prices from the last successful update.",
    TextKey.INVEST_EMPTY_TITLE to "No assets yet",
    TextKey.INVEST_EMPTY_BODY to "Add property, gold or shares to see what they are worth today.",
    TextKey.INVEST_ADD_ASSET to "Add an asset",
    TextKey.INVEST_REFRESH to "Update prices",
    TextKey.INVEST_REFRESHED to "Prices updated",
    TextKey.INVEST_REFRESH_SKIPPED to "Prices updated — {0} of your assets were not updated",
    TextKey.INVEST_TOTAL_LABEL to "Everything you own at today's prices",
    TextKey.INVEST_TOTAL_NA_ONE to "Today's price for “{0}” isn't available, so the total is incomplete.",
    TextKey.INVEST_TOTAL_NA_MANY to "Assets without a price today: {0}, so the total is incomplete.",
    TextKey.INVEST_COST to "Cost",
    TextKey.INVEST_UNREALIZED to "Unrealized gain",
    TextKey.INVEST_REALIZED to "Realized gain",
    TextKey.INVEST_RE_SUB_AREA to "Property, {0} m² × {1} per m²",
    TextKey.INVEST_RE_ASK to "What would it be worth if you sold it in {0}?",
    TextKey.INVEST_RE_PRICE_THEN to "Its price then",
    TextKey.INVEST_RE_RENT_UNTIL to "+ rent until {0}",
    TextKey.INVEST_RE_GAIN to "Gain since purchase (with rent)",
    TextKey.INVEST_RE_RATE to "Growing {0} a year = {1}",
    TextKey.INVEST_PRICE_TODAY to "Price today",
    TextKey.INVEST_PRICE_ON to "Price from {0}",
    TextKey.INVEST_PRICE_OLD to "Old price from {0}",
    TextKey.INVEST_PRICE_NONE to "No price today",
    TextKey.INVEST_ARCHIVED_SUB to "Archived",
    TextKey.INVEST_QTY_UNIT to "{0} {1}",
    TextKey.INVEST_ROW_SUB to "{0}, {1}",
    TextKey.INVEST_TOOL_ZAKAT to "Zakat",
    TextKey.INVEST_TOOL_ZAKAT_HINT to "For guidance, per {0}",
    TextKey.INVEST_TOOL_ADVISOR to "Smart insights",
    TextKey.INVEST_TOOL_ADVISOR_HINT to "Ideas from your spending, and why they showed up",
    TextKey.INVEST_TOOL_GOALS to "Savings plans",
    TextKey.INVEST_GOALS_NONE to "No plans yet",
    TextKey.INVEST_GOALS_ONE to "One plan",
    TextKey.INVEST_GOALS_TWO to "Two plans",
    TextKey.INVEST_GOALS_FEW to "{0} plans",
    TextKey.INVEST_GOALS_MANY to "{0} plans",
    TextKey.INVEST_CALCS to "Calculators",
    TextKey.INVEST_CALC_SAVINGS to "Savings",
    TextKey.INVEST_CALC_RETIREMENT to "Retirement",
    TextKey.INVEST_CALC_INHERITANCE to "Inheritance",
    TextKey.INVEST_PERCENT to "{0}%",
    TextKey.INVEST_DATE_YEAR to "{0} {1}",
) + ENGLISH_INVEST_ASSET_TEXTS + ENGLISH_INVEST_TRADE_TEXTS + ENGLISH_INVEST_ZAKAT_TEXTS + ENGLISH_INVEST_PAY_TEXTS
