package app.masroufy.core

/**
 * «تفاصيل المحفظة» (`WalletDetail`) — منطقة «المزيد». من النموذج بالحرف (المطابقة بصيغة العدد بدل «{1} حركة» — spec/06)، إلا:
 * - «آخر الحركات» من غير «ومصدرها» (مصدر كل حركة مش في بيانات «حركات الشهر» المعروضة هنا).
 * - سطر «غير متاح بعد» للمحفظة الأساسية (المنطق على فرع `assistant-engine`) — كتابة Claude.
 */
internal val MSA_MORE_WALLET_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.WDET_TITLE to "تفاصيل المحفظة",
    UiKey.WDET_GONE to "هذه المحفظة لم تعد موجودة.",
    UiKey.WDET_BALANCE to "الرصيد",
    UiKey.WDET_SUB_NA to "الرصيد غير معروف بعد — تحدده رسالة بنك جديدة أو كشف.",
    UiKey.WDET_SUB_CASH to "لا يظهر فيه الكاش الذي صُرف ولم يُسجَّل.",
    UiKey.WDET_SUB_BANK to "من رصيد البداية والحركات بعده",
    UiKey.WDET_KIND to "النوع",
    UiKey.WDET_CURRENCY to "العملة",
    UiKey.WDET_OPENING to "رصيد البداية",
    UiKey.WDET_OPENING_VALUE to "{0} في {1}",
    UiKey.WDET_MAIN_TITLE to "المحفظة الأساسية",
    UiKey.WDET_MAIN_IS to "محفظتك الأساسية",
    UiKey.WDET_MAIN_IS_SUB to "ما تسجّله بنفسك أو بصوتك أو في المساعد يُسجَّل عليها، ويمكنك تغييره في أي عملية.",
    UiKey.WDET_MAIN_NOW to "الآن: «{0}»",
    UiKey.WDET_MAIN_UNSET to "لم تحدّدها بعد — سنسألك أول مرة تسجّل عملية.",
    UiKey.WDET_MAIN_MAKE to "اجعلها الأساسية",
    UiKey.WDET_MAIN_DONE to "صارت «{0}» محفظتك الأساسية",
    UiKey.WDET_MAIN_NOT_YET to "تحديد المحفظة الأساسية غير متاح بعد في هذه النسخة.",
    UiKey.WDET_MOVES to "آخر الحركات",
    UiKey.WDET_MOVES_PERIOD to "الشهر المالي الحالي",
    UiKey.WDET_NO_MOVES to "لا حركات في هذا الشهر بعد.",
    UiKey.WDET_MOVE_UNNAMED to "عملية بلا اسم",
    UiKey.WDET_MOVE_IN_PREFIX to "تحويل وارد: {0}",
    UiKey.WDET_CASH_NOTE to "لا كشف للكاش يُطابق عليه — حين تعدّه، عدّل رصيد البداية من الزر أعلاه.",
    UiKey.WDET_REC_TITLE to "مطابقة الرصيد",
    UiKey.WDET_REC_OPTIONAL to "اختيارية",
    UiKey.WDET_REC_BODY to "تقارن رصيد كل حركة بالرصيد المكتوب في الكشف. لا شيء ينتظرها.",
    UiKey.WDET_REC_RUN to "شغّل المطابقة",
    UiKey.WDET_REC_AGAIN to "أعد المطابقة",
    UiKey.WDET_REC_OK to "مطابق",
    UiKey.WDET_REC_OK_UNTIL to "مطابق حتى {0}",
    UiKey.WDET_REC_GAP to "يوجد فرق",
    UiKey.WDET_GAP_ONE to "أول فرق في {0}، وفي ذلك اليوم حركة واحدة، فالفرق يخصها.",
    UiKey.WDET_GAP_MANY to "أول فرق في {0}، وفي ذلك اليوم {1}. ترتيب حركات اليوم الواحد غير مثبت في الكشف، فقد لا تكون هذه أول عملية فيها خلل.",
    UiKey.WDET_GAP_AMOUNTS to "المحسوب {0} والمكتوب في الكشف {1} — الفرق {2} {3}",
    UiKey.WDET_REC_COUNTS to "{0}، قُورن منها {1}",
    UiKey.WDET_REC_COUNTS_NO_BAL to "، و{0} بلا رصيد معلن",
    UiKey.WDET_REC_UNASSIGNED to "{0} غير منسوبة لأي محفظة — تُذكر ولا تُنسب بالتخمين.",
    UiKey.WDET_REC_NA to "لا حركات برصيد معلن بعد — استورد كشفًا لتعمل.",
    UiKey.WDET_REC_FAILED to "تعذّرت المطابقة. أعد المحاولة.",
    UiKey.WDET_MOVE_ONE to "حركة واحدة",
    UiKey.WDET_MOVE_TWO to "حركتان",
    UiKey.WDET_MOVE_FEW to "{0} حركات",
    UiKey.WDET_MOVE_MANY to "{0} حركة",
    UiKey.WDET_OP_ONE to "عملية واحدة",
    UiKey.WDET_OP_TWO to "عمليتان",
    UiKey.WDET_OP_FEW to "{0} عمليات",
    UiKey.WDET_OP_MANY to "{0} عملية",
)

internal val EGYPTIAN_MORE_WALLET_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.WDET_TITLE to "تفاصيل المحفظة",
    UiKey.WDET_GONE to "المحفظة دي مش موجودة.",
    UiKey.WDET_BALANCE to "الرصيد",
    UiKey.WDET_SUB_NA to "الرصيد مش معروف لسه — رسالة بنك جديدة أو كشف بيحدده.",
    UiKey.WDET_SUB_CASH to "الكاش اللي اتصرف ومااتسجلش مش باين فيه.",
    UiKey.WDET_SUB_BANK to "من رصيد البداية والحركات اللي بعده",
    UiKey.WDET_KIND to "النوع",
    UiKey.WDET_CURRENCY to "العملة",
    UiKey.WDET_OPENING to "رصيد البداية",
    UiKey.WDET_OPENING_VALUE to "{0} في {1}",
    UiKey.WDET_MAIN_TITLE to "المحفظة الأساسية",
    UiKey.WDET_MAIN_IS to "محفظتك الأساسية",
    UiKey.WDET_MAIN_IS_SUB to "اللي بتسجّله بإيدك أو بصوتك أو في المساعد بيتسجل عليها، وتقدر تغيّره في أي عملية.",
    UiKey.WDET_MAIN_NOW to "دلوقتي: «{0}»",
    UiKey.WDET_MAIN_UNSET to "لسه ما حددتهاش — هنسألك أول مرة تسجّل عملية.",
    UiKey.WDET_MAIN_MAKE to "خلّيها الأساسية",
    UiKey.WDET_MAIN_DONE to "«{0}» بقت محفظتك الأساسية",
    UiKey.WDET_MAIN_NOT_YET to "تحديد المحفظة الأساسية لسه مش متاح في النسخة دي.",
    UiKey.WDET_MOVES to "آخر الحركات",
    UiKey.WDET_MOVES_PERIOD to "الشهر المالي ده",
    UiKey.WDET_NO_MOVES to "مفيش حركات الشهر ده لسه.",
    UiKey.WDET_MOVE_UNNAMED to "عملية من غير اسم",
    UiKey.WDET_MOVE_IN_PREFIX to "تحويل جاي: {0}",
    UiKey.WDET_CASH_NOTE to "الكاش مالوش كشف يتطابق عليه — لما تعدّه، عدّل رصيد البداية من فوق.",
    UiKey.WDET_REC_TITLE to "مطابقة الرصيد",
    UiKey.WDET_REC_OPTIONAL to "اختيارية",
    UiKey.WDET_REC_BODY to "بتقارن رصيد كل حركة بالرصيد المكتوب في الكشف. مفيش حاجة مستنياها.",
    UiKey.WDET_REC_RUN to "طابق الرصيد",
    UiKey.WDET_REC_AGAIN to "طابق تاني",
    UiKey.WDET_REC_OK to "مطابق",
    UiKey.WDET_REC_OK_UNTIL to "مطابق لحد {0}",
    UiKey.WDET_REC_GAP to "فيه فرق",
    UiKey.WDET_GAP_ONE to "أول فرق في {0}، واليوم ده فيه حركة واحدة، فالفرق يخصها هي.",
    UiKey.WDET_GAP_MANY to "أول فرق في {0}، واليوم ده فيه {1}. ترتيب حركات اليوم الواحد مش مثبت في الكشف، فمش أكيد إن دي بالذات أول عملية فيها مشكلة.",
    UiKey.WDET_GAP_AMOUNTS to "المحسوب {0} والمكتوب في الكشف {1} — الفرق {2} {3}",
    UiKey.WDET_REC_COUNTS to "{0}، اتقارن منها {1}",
    UiKey.WDET_REC_COUNTS_NO_BAL to "، و{0} من غير رصيد مكتوب",
    UiKey.WDET_REC_UNASSIGNED to "{0} مش منسوبة لأي محفظة — بنذكرها ومش بننسبها بالتخمين.",
    UiKey.WDET_REC_NA to "مفيش حركات برصيد مكتوب لسه — استورد كشف عشان تشتغل.",
    UiKey.WDET_REC_FAILED to "المطابقة ما نجحتش. جرّب تاني.",
    UiKey.WDET_MOVE_ONE to "حركة واحدة",
    UiKey.WDET_MOVE_TWO to "حركتين",
    UiKey.WDET_MOVE_FEW to "{0} حركات",
    UiKey.WDET_MOVE_MANY to "{0} حركة",
    UiKey.WDET_OP_ONE to "عملية واحدة",
    UiKey.WDET_OP_TWO to "عمليتين",
    UiKey.WDET_OP_FEW to "{0} عمليات",
    UiKey.WDET_OP_MANY to "{0} عملية",
)

internal val ENGLISH_MORE_WALLET_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.WDET_TITLE to "Wallet details",
    UiKey.WDET_GONE to "This wallet no longer exists.",
    UiKey.WDET_BALANCE to "Balance",
    UiKey.WDET_SUB_NA to "The balance isn't known yet — a new bank message or a statement sets it.",
    UiKey.WDET_SUB_CASH to "Cash spent but not recorded doesn't show here.",
    UiKey.WDET_SUB_BANK to "From the opening balance and the movements after it",
    UiKey.WDET_KIND to "Type",
    UiKey.WDET_CURRENCY to "Currency",
    UiKey.WDET_OPENING to "Opening balance",
    UiKey.WDET_OPENING_VALUE to "{0} on {1}",
    UiKey.WDET_MAIN_TITLE to "Main wallet",
    UiKey.WDET_MAIN_IS to "Your main wallet",
    UiKey.WDET_MAIN_IS_SUB to "What you record yourself, by voice or in the assistant goes here, and you can change it on any transaction.",
    UiKey.WDET_MAIN_NOW to "Now: “{0}”",
    UiKey.WDET_MAIN_UNSET to "Not chosen yet — we'll ask the first time you record a transaction.",
    UiKey.WDET_MAIN_MAKE to "Make it the main one",
    UiKey.WDET_MAIN_DONE to "“{0}” is now your main wallet",
    UiKey.WDET_MAIN_NOT_YET to "Choosing the main wallet isn't available in this version yet.",
    UiKey.WDET_MOVES to "Latest movements",
    UiKey.WDET_MOVES_PERIOD to "This financial month",
    UiKey.WDET_NO_MOVES to "No movements this month yet.",
    UiKey.WDET_MOVE_UNNAMED to "Unnamed transaction",
    UiKey.WDET_MOVE_IN_PREFIX to "Transfer in: {0}",
    UiKey.WDET_CASH_NOTE to "Cash has no statement to match — when you count it, edit the opening balance with the button above.",
    UiKey.WDET_REC_TITLE to "Balance check",
    UiKey.WDET_REC_OPTIONAL to "Optional",
    UiKey.WDET_REC_BODY to "Compares each movement's balance with the balance written on the statement. Nothing waits on it.",
    UiKey.WDET_REC_RUN to "Run the check",
    UiKey.WDET_REC_AGAIN to "Check again",
    UiKey.WDET_REC_OK to "Matches",
    UiKey.WDET_REC_OK_UNTIL to "Matches up to {0}",
    UiKey.WDET_REC_GAP to "There's a difference",
    UiKey.WDET_GAP_ONE to "First difference on {0}, and that day has one movement, so the difference is in it.",
    UiKey.WDET_GAP_MANY to "First difference on {0}, and that day has {1}. The statement doesn't fix the order within a day, so this may not be the first movement with a problem.",
    UiKey.WDET_GAP_AMOUNTS to "Computed {0}, statement says {1} — difference {2} {3}",
    UiKey.WDET_REC_COUNTS to "{0}; {1} compared",
    UiKey.WDET_REC_COUNTS_NO_BAL to ", and {0} without a stated balance",
    UiKey.WDET_REC_UNASSIGNED to "{0} not assigned to any wallet — mentioned, never assigned by guessing.",
    UiKey.WDET_REC_NA to "No movements with a stated balance yet — import a statement to use it.",
    UiKey.WDET_REC_FAILED to "The balance check failed. Try again.",
    UiKey.WDET_MOVE_ONE to "one movement",
    UiKey.WDET_MOVE_TWO to "two movements",
    UiKey.WDET_MOVE_FEW to "{0} movements",
    UiKey.WDET_MOVE_MANY to "{0} movements",
    UiKey.WDET_OP_ONE to "one transaction",
    UiKey.WDET_OP_TWO to "two transactions",
    UiKey.WDET_OP_FEW to "{0} transactions",
    UiKey.WDET_OP_MANY to "{0} transactions",
)
