package app.masroufy.core

/**
 * «النسخة الاحتياطية» و«معاينة الاسترجاع» (`Backup` · `RestorePreview`) — منطقة «المزيد». من النموذج بالحرف، إلا:
 * - نطاق النسخة من غير «ما تعلّمه المساعد وسجل محادثاته» (ذاكرة المساعد لسه على فرع `assistant-engine` — CLAUDE.md #15).
 * - «آخر نسخة» بتظهر بعد ما تعمل نسخة بس (تاريخ آخر نسخة مش محفوظ في أي مكان).
 * - غلط الاسترجاع من غير «لم يُكتب شيء» (الإضافة على دفعات؛ إعادة المحاولة ما بتكرّرش لأن الدمج بيتحسب تاني).
 */
internal val MSA_MORE_BACKUP_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.BAK_TITLE to "النسخة الاحتياطية",
    TextKey.BAK_FULL_TITLE to "النسخة الشاملة",
    TextKey.BAK_FULL_BODY to "ملف واحد للحساب كله: كل بلدانك وملفك وأشخاصك والتجار.",
    TextKey.BAK_LAST_NOW to "آخر نسخة: الآن",
    TextKey.BAK_MAKE to "أنشئ نسخة الآن",
    TextKey.BAK_MAKING to "جارٍ تجهيز النسخة…",
    TextKey.BAK_MAKE_ANOTHER to "أنشئ نسخة أخرى",
    TextKey.BAK_SAVED to "حُفظت النسخة على الجوال",
    TextKey.BAK_PARTIAL to "لم يُكتب الملف كاملًا. لم يتغير شيء في حسابك — أعد المحاولة.",
    TextKey.BAK_FAILED to "تعذّر حفظ الملف على الجهاز. لم يتغير شيء في حسابك — أعد المحاولة.",
    TextKey.BAK_NO_FILES to "ملفات الجوال غير متاحة على هذا الجهاز.",
    TextKey.BAK_NOT_WIRED to "النسخة الشاملة غير متاحة بعد في هذه النسخة من التطبيق.",
    TextKey.BAK_SCOPE_NOTE to "النسخة تشمل بيانات الحساب في كل البلدان؛ أذونات الجوال ورسائل المراجعة المحلية وإعدادات المظهر لا تُستعاد منها.",
    TextKey.BAK_RESTORE_TITLE to "الاسترجاع (دمج)",
    TextKey.BAK_RESTORE_BODY to "لا يُكتب فوق ما عندك: نفس المعرّف يُتخطّى، والمكرر بالمحتوى نفسه يُتخطّى، والجديد يُضاف. ترى ذلك كله قبل أي كتابة.",
    TextKey.BAK_PICK to "اختر ملف النسخة",
    TextKey.BAK_PICK_FAILED to "تعذّرت قراءة الملف.",
    TextKey.BAK_CSV_TITLE to "تصدير العمليات",
    TextKey.BAK_CSV_BODY to "عمليات {0} في ملف جدول (CSV)، من تاريخ إلى تاريخ بالضبط.",
    TextKey.BAK_FROM to "من",
    TextKey.BAK_TO to "إلى",
    TextKey.BAK_RANGE_LINE to "{0} ← {1}، {2}",
    TextKey.BAK_RANGE_BAD_ORDER to "يجب أن يسبق تاريخ البداية تاريخ النهاية.",
    TextKey.BAK_RANGE_BAD_DATE to "اكتب التاريخين بالشكل 2026-10-07، ولا يكون أي منهما بعد اليوم.",
    TextKey.BAK_DAY_ONE to "يوم واحد",
    TextKey.BAK_DAY_TWO to "يومان",
    TextKey.BAK_DAY_FEW to "{0} أيام",
    TextKey.BAK_DAY_MANY to "{0} يومًا",
    TextKey.BAK_EXPORT to "صدّر الملف",
    TextKey.BAK_EXPORTED to "حُفظ {0}",
    TextKey.RST_TITLE to "معاينة الاسترجاع",
    TextKey.RST_MADE_ON to "أُنشئت {0}",
    TextKey.RST_READING to "نقرأ الملف ونقارنه بما عندك…",
    TextKey.RST_BAD_FILE to "تعذّرت قراءة هذا الملف",
    TextKey.RST_NOTHING_WRITTEN to "لم يُكتب أي حرف في حسابك.",
    TextKey.RST_OTHER_FILE to "اختر ملفًا آخر",
    TextKey.RST_WILL_ADD_N to "سيُضاف {0}",
    TextKey.RST_ADDED_N to "أُضيف {0}",
    TextKey.RST_DONE_BODY to "بقي ما عندك كما هو.",
    TextKey.RST_APPLYING to "نضيف على دفعات…",
    TextKey.RST_PLAN_BODY to "من أصل {0} في الملف — والباقي موجود عندك فيُتخطّى. لم يُكتب شيء بعد.",
    TextKey.RST_PROFILE_KEEP to "ملفك (الاسم والراتب ويوم الراتب): موجود عندك — لا يُكتب فوقه.",
    TextKey.RST_PROFILE_ADD to "ملفك (الاسم والراتب ويوم الراتب): غير موجود عندك — يُضاف من الملف.",
    TextKey.RST_PROFILE_NONE to "لا يحتوي الملف على ملفك الشخصي.",
    TextKey.RST_ROOT to "الحساب والسعودية",
    TextKey.RST_SPACE_NEW to "جديدة — تُنشأ",
    TextKey.RST_SPACE_MERGE to "موجودة — يُدمج فيها",
    TextKey.RST_ALL_THERE to "كل شيء موجود عندك",
    TextKey.RST_COL_GROUP to "المجموعة",
    TextKey.RST_COL_IN to "وارد",
    TextKey.RST_COL_ADD to "يُضاف",
    TextKey.RST_COL_SKIP to "يُتخطّى",
    TextKey.RST_CONFIRM to "أكّد وأضف {0}",
    TextKey.RST_ADDING to "جارٍ الإضافة…",
    TextKey.RST_CANCEL to "إلغاء — لا تكتب شيئًا",
    TextKey.RST_APPLY_FAILED to "تعذّر إكمال الاسترجاع. أعد المحاولة — ما أُضيف لن يتكرر.",
    TextKey.RST_REC_ONE to "سجل واحد",
    TextKey.RST_REC_TWO to "سجلان",
    TextKey.RST_REC_FEW to "{0} سجلات",
    TextKey.RST_REC_MANY to "{0} سجلًا",
)

internal val EGYPTIAN_MORE_BACKUP_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.BAK_TITLE to "النسخة الاحتياطية",
    TextKey.BAK_FULL_TITLE to "النسخة الشاملة",
    TextKey.BAK_FULL_BODY to "ملف واحد للحساب كله: كل بلادك وملفك وأشخاصك والتجار.",
    TextKey.BAK_LAST_NOW to "آخر نسخة: دلوقتي",
    TextKey.BAK_MAKE to "اعمل نسخة دلوقتي",
    TextKey.BAK_MAKING to "بنجهّز النسخة…",
    TextKey.BAK_MAKE_ANOTHER to "اعمل نسخة تانية",
    TextKey.BAK_SAVED to "النسخة اتحفظت على الجوال",
    TextKey.BAK_PARTIAL to "الملف ما اتكتبش كامل. ما اتغيّرش حاجة في حسابك — جرّب تاني.",
    TextKey.BAK_FAILED to "تعذر حفظ الملف على الجهاز. ما اتغيّرش حاجة في حسابك — جرّب تاني.",
    TextKey.BAK_NO_FILES to "ملفات الجوال مش متاحة على الجهاز ده.",
    TextKey.BAK_NOT_WIRED to "النسخة الشاملة لسه مش متاحة في النسخة دي من البرنامج.",
    TextKey.BAK_SCOPE_NOTE to "النسخة فيها بيانات الحساب في كل البلاد؛ أذونات الجوال ورسايل المراجعة اللي على الجهاز وإعدادات الشكل ما بترجعش منها.",
    TextKey.BAK_RESTORE_TITLE to "الاسترجاع (دمج)",
    TextKey.BAK_RESTORE_BODY to "اللي عندك ما بيتكتبش فوقه: نفس المعرّف بيتساب، والمكرر بنفس المحتوى بيتساب، والجديد بيتضاف. بتشوف كل ده قبل أي كتابة.",
    TextKey.BAK_PICK to "اختار ملف النسخة",
    TextKey.BAK_PICK_FAILED to "الملف ما اتقراش.",
    TextKey.BAK_CSV_TITLE to "تصدير العمليات",
    TextKey.BAK_CSV_BODY to "عمليات {0} في ملف جدول (CSV)، من اليوم ده لليوم ده بالظبط.",
    TextKey.BAK_FROM to "من",
    TextKey.BAK_TO to "لحد",
    TextKey.BAK_RANGE_LINE to "{0} ← {1}، {2}",
    TextKey.BAK_RANGE_BAD_ORDER to "تاريخ البداية لازم يبقى قبل النهاية.",
    TextKey.BAK_RANGE_BAD_DATE to "اكتب التاريخين كده 2026-10-07، ومينفعش يبقوا بعد النهارده.",
    TextKey.BAK_DAY_ONE to "يوم واحد",
    TextKey.BAK_DAY_TWO to "يومين",
    TextKey.BAK_DAY_FEW to "{0} أيام",
    TextKey.BAK_DAY_MANY to "{0} يوم",
    TextKey.BAK_EXPORT to "صدّر الملف",
    TextKey.BAK_EXPORTED to "اتحفظ {0}",
    TextKey.RST_TITLE to "معاينة الاسترجاع",
    TextKey.RST_MADE_ON to "اتعملت {0}",
    TextKey.RST_READING to "بنقرا الملف ونقارنه باللي عندك…",
    TextKey.RST_BAD_FILE to "الملف ده ما اتقراش",
    TextKey.RST_NOTHING_WRITTEN to "ما اتكتبش ولا حرف في حسابك.",
    TextKey.RST_OTHER_FILE to "اختار ملف تاني",
    TextKey.RST_WILL_ADD_N to "هيتضاف {0}",
    TextKey.RST_ADDED_N to "اتضاف {0}",
    TextKey.RST_DONE_BODY to "اللي كان عندك فضل زي ما هو.",
    TextKey.RST_APPLYING to "بنضيف على دفعات…",
    TextKey.RST_PLAN_BODY to "من {0} في الملف — والباقي موجود عندك فهيتساب. لسه ما اتكتبش حاجة.",
    TextKey.RST_PROFILE_KEEP to "ملفك (الاسم والمرتب ويوم المرتب): موجود عندك — ما بيتكتبش فوقه.",
    TextKey.RST_PROFILE_ADD to "ملفك (الاسم والمرتب ويوم المرتب): مش موجود عندك — هيتضاف من الملف.",
    TextKey.RST_PROFILE_NONE to "الملف ما فيهوش ملفك الشخصي.",
    TextKey.RST_ROOT to "الحساب والسعودية",
    TextKey.RST_SPACE_NEW to "جديدة — هتتعمل",
    TextKey.RST_SPACE_MERGE to "موجودة — هتتدمج",
    TextKey.RST_ALL_THERE to "كله موجود عندك",
    TextKey.RST_COL_GROUP to "المجموعة",
    TextKey.RST_COL_IN to "جاي",
    TextKey.RST_COL_ADD to "هيتضاف",
    TextKey.RST_COL_SKIP to "هيتساب",
    TextKey.RST_CONFIRM to "أكّد وضيف {0}",
    TextKey.RST_ADDING to "بنضيف…",
    TextKey.RST_CANCEL to "إلغاء — ما تكتبش حاجة",
    TextKey.RST_APPLY_FAILED to "الاسترجاع ما كملش. جرّب تاني — اللي اتضاف مش هيتكرر.",
    TextKey.RST_REC_ONE to "سجل واحد",
    TextKey.RST_REC_TWO to "سجلين",
    TextKey.RST_REC_FEW to "{0} سجلات",
    TextKey.RST_REC_MANY to "{0} سجل",
)

internal val ENGLISH_MORE_BACKUP_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.BAK_TITLE to "Backup",
    TextKey.BAK_FULL_TITLE to "Full backup",
    TextKey.BAK_FULL_BODY to "One file for the whole account: all your countries, your profile, your people and merchants.",
    TextKey.BAK_LAST_NOW to "Last backup: just now",
    TextKey.BAK_MAKE to "Back up now",
    TextKey.BAK_MAKING to "Preparing the backup…",
    TextKey.BAK_MAKE_ANOTHER to "Make another backup",
    TextKey.BAK_SAVED to "Backup saved on the phone",
    TextKey.BAK_PARTIAL to "The file wasn't written in full. Nothing changed in your account — try again.",
    TextKey.BAK_FAILED to "Couldn't save the file on the device. Nothing changed in your account — try again.",
    TextKey.BAK_NO_FILES to "Phone files aren't available on this device.",
    TextKey.BAK_NOT_WIRED to "The full backup isn't available in this version of the app yet.",
    TextKey.BAK_SCOPE_NOTE to "The backup includes the account's data in every country; phone permissions, local review messages and look settings aren't restored from it.",
    TextKey.BAK_RESTORE_TITLE to "Restore (merge)",
    TextKey.BAK_RESTORE_BODY to "Nothing you have is overwritten: the same ID is skipped, duplicates with the same content are skipped, and new items are added. You see all of it before anything is written.",
    TextKey.BAK_PICK to "Choose the backup file",
    TextKey.BAK_PICK_FAILED to "Couldn't read the file.",
    TextKey.BAK_CSV_TITLE to "Export transactions",
    TextKey.BAK_CSV_BODY to "{0} transactions in a spreadsheet file (CSV), from one exact date to another.",
    TextKey.BAK_FROM to "From",
    TextKey.BAK_TO to "To",
    TextKey.BAK_RANGE_LINE to "{0} → {1}, {2}",
    TextKey.BAK_RANGE_BAD_ORDER to "The start date must come before the end date.",
    TextKey.BAK_RANGE_BAD_DATE to "Write both dates like 2026-10-07, and neither after today.",
    TextKey.BAK_DAY_ONE to "one day",
    TextKey.BAK_DAY_TWO to "two days",
    TextKey.BAK_DAY_FEW to "{0} days",
    TextKey.BAK_DAY_MANY to "{0} days",
    TextKey.BAK_EXPORT to "Export the file",
    TextKey.BAK_EXPORTED to "{0} saved",
    TextKey.RST_TITLE to "Restore preview",
    TextKey.RST_MADE_ON to "Made on {0}",
    TextKey.RST_READING to "Reading the file and comparing it with what you have…",
    TextKey.RST_BAD_FILE to "This file couldn't be read",
    TextKey.RST_NOTHING_WRITTEN to "Not a single character was written to your account.",
    TextKey.RST_OTHER_FILE to "Choose another file",
    TextKey.RST_WILL_ADD_N to "{0} will be added",
    TextKey.RST_ADDED_N to "{0} added",
    TextKey.RST_DONE_BODY to "What you had stayed as it was.",
    TextKey.RST_APPLYING to "Adding in batches…",
    TextKey.RST_PLAN_BODY to "Out of {0} in the file — the rest is already here, so it's skipped. Nothing has been written yet.",
    TextKey.RST_PROFILE_KEEP to "Your profile (name, salary, payday): already here — not overwritten.",
    TextKey.RST_PROFILE_ADD to "Your profile (name, salary, payday): not here — added from the file.",
    TextKey.RST_PROFILE_NONE to "The file doesn't contain your profile.",
    TextKey.RST_ROOT to "Account and Saudi Arabia",
    TextKey.RST_SPACE_NEW to "New — will be created",
    TextKey.RST_SPACE_MERGE to "Exists — will be merged",
    TextKey.RST_ALL_THERE to "You already have everything",
    TextKey.RST_COL_GROUP to "Group",
    TextKey.RST_COL_IN to "In file",
    TextKey.RST_COL_ADD to "Added",
    TextKey.RST_COL_SKIP to "Skipped",
    TextKey.RST_CONFIRM to "Confirm and add {0}",
    TextKey.RST_ADDING to "Adding…",
    TextKey.RST_CANCEL to "Cancel — write nothing",
    TextKey.RST_APPLY_FAILED to "The restore didn't finish. Try again — what was added won't be duplicated.",
    TextKey.RST_REC_ONE to "one record",
    TextKey.RST_REC_TWO to "two records",
    TextKey.RST_REC_FEW to "{0} records",
    TextKey.RST_REC_MANY to "{0} records",
)
