package app.masroufy.core

/**
 * نصوص منطقة «الرئيسية» — صفحة الإشعارات (`Notifications`) و«اختر الشهر» (`PeriodPicker`). مضمومة في `TextsAreaHome.kt`.
 * النص من النموذج التفاعلي بالحرف قدر الإمكان (الفصحى من `السعودية` والمصري من `مصر`).
 */
internal val MSA_AREA_HOME_NOTIFY_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.NOTIFICATIONS_TITLE to "الإشعارات",
    TextKey.NOTIFICATIONS_SETTINGS to "إعدادات الإشعارات",
    TextKey.NOTIFICATIONS_WAITING to "بانتظار قرارك",
    TextKey.NOTIFICATIONS_NEW to "جديد",
    TextKey.NOTIFICATIONS_TODAY to "اليوم",
    TextKey.NOTIFICATIONS_YESTERDAY to "أمس",
    TextKey.NOTIFICATIONS_TWO_DAYS to "قبل يومين",
    TextKey.NOTIFICATIONS_FEW_DAYS to "قبل {0} أيام",
    TextKey.NOTIFICATIONS_MANY_DAYS to "قبل {0} يومًا",
    TextKey.NOTIFICATIONS_MUTED to "متوقفة",
    TextKey.NOTIFICATIONS_DROP to "احذف إشعار «{0}»",
    TextKey.NOTIFICATIONS_DROPPED to "حُذف الإشعار",
    TextKey.NOTIFICATIONS_UNDO to "تراجع",
    TextKey.NOTIFICATIONS_EMPTY_TITLE to "لا جديد",
    TextKey.NOTIFICATIONS_EMPTY_BODY to "سننبهك عندما يستحق الأمر.",
    TextKey.NOTIFICATIONS_LOCK_TITLE to "هكذا يظهر على شاشة القفل",
    TextKey.NOTIFICATIONS_LOCK_LETTER to "م",
    TextKey.NOTIFICATIONS_LOCK_NOW to "الآن",
    TextKey.NOTIFICATIONS_LOCK_NOTE to "بلا مبالغ ولا أسماء ولا أعداد. وما يُسجَّل تلقائيًا من رسائل البنك لا يصدر عنه إشعار — تراه في العمليات بلمعة.",
    TextKey.PERIOD_PICKER_TITLE to "اختر الشهر",
    TextKey.PERIOD_PICKER_INTRO to "يبدأ شهرك يوم {0} (يوم الراتب) وينتهي قبل اليوم نفسه من الشهر التالي.",
    TextKey.PERIOD_PICKER_PREV to "الشهر السابق",
    TextKey.PERIOD_PICKER_NEXT to "الشهر التالي",
    TextKey.PERIOD_PICKER_CURRENT to "الشهر الحالي",
    TextKey.PERIOD_PICKER_PAST to "شهر سابق",
    TextKey.PERIOD_PICKER_NOW_NOTE to "اليوم {0} من {1}، بقي {2} على الراتب",
    TextKey.PERIOD_PICKER_WAS to "كان {0}",
    TextKey.PERIOD_PICKER_DAYS_ONE to "يوم واحد",
    TextKey.PERIOD_PICKER_DAYS_TWO to "يومان",
    TextKey.PERIOD_PICKER_DAYS_FEW to "{0} أيام",
    TextKey.PERIOD_PICKER_DAYS_MANY to "{0} يومًا",
    TextKey.PERIOD_PICKER_BACK to "العودة إلى الشهر الحالي",
    TextKey.PERIOD_PICKER_YEAR_PREV to "السنة السابقة",
    TextKey.PERIOD_PICKER_YEAR_NEXT to "السنة التالية",
    TextKey.PERIOD_PICKER_NOW to "الحالي",
    TextKey.PERIOD_PICKER_NOT_STARTED to "لم يبدأ بعد",
    TextKey.PERIOD_PICKER_BEFORE_DATA to "قبل بداية بياناتك",
    TextKey.PERIOD_PICKER_DATA_FROM to "تبدأ بياناتك من {0}.",
    TextKey.PERIOD_PICKER_FUTURE_NOTE to "الأشهر القادمة تُفتح عند بدايتها.",
    TextKey.PERIOD_PICKER_RANGE to "{0} – {1}",
    TextKey.PERIOD_PICKER_DAY_MONTH_YEAR to "{0} {1}",
    TextKey.PERIOD_PICKER_TOAST to "{0} — {1}",
    TextKey.PERIOD_PICKER_PICKED_TOAST to "اخترت {0}",
    TextKey.PERIOD_PICKER_BACK_TOAST to "عدت إلى الشهر الحالي {0}",
)

internal val EGYPTIAN_AREA_HOME_NOTIFY_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.NOTIFICATIONS_TITLE to "الإشعارات",
    TextKey.NOTIFICATIONS_SETTINGS to "إعدادات الإشعارات",
    TextKey.NOTIFICATIONS_WAITING to "محتاج قرارك",
    TextKey.NOTIFICATIONS_NEW to "جديد",
    TextKey.NOTIFICATIONS_TODAY to "النهارده",
    TextKey.NOTIFICATIONS_YESTERDAY to "امبارح",
    TextKey.NOTIFICATIONS_TWO_DAYS to "من يومين",
    TextKey.NOTIFICATIONS_FEW_DAYS to "من {0} أيام",
    TextKey.NOTIFICATIONS_MANY_DAYS to "من {0} يوم",
    TextKey.NOTIFICATIONS_MUTED to "مقفولة",
    TextKey.NOTIFICATIONS_DROP to "امسح إشعار «{0}»",
    TextKey.NOTIFICATIONS_DROPPED to "اتمسح الإشعار",
    TextKey.NOTIFICATIONS_UNDO to "رجّعه",
    TextKey.NOTIFICATIONS_EMPTY_TITLE to "مفيش حاجة جديدة",
    TextKey.NOTIFICATIONS_EMPTY_BODY to "هنقولك لما يبقى فيه حاجة تستاهل.",
    TextKey.NOTIFICATIONS_LOCK_TITLE to "كده بيظهر على شاشة القفل",
    TextKey.NOTIFICATIONS_LOCK_LETTER to "م",
    TextKey.NOTIFICATIONS_LOCK_NOW to "دلوقتي",
    TextKey.NOTIFICATIONS_LOCK_NOTE to "من غير مبالغ ولا أسامي ولا عدد. واللي بيتسجل لوحده من رسايل البنك مالوش إشعار — بتشوفه في العمليات بلمعة.",
    TextKey.PERIOD_PICKER_TITLE to "اختار الشهر",
    TextKey.PERIOD_PICKER_INTRO to "شهرك بيبدأ يوم {0} (يوم المرتب) وبيخلص قبل نفس اليوم في الشهر اللي بعده.",
    TextKey.PERIOD_PICKER_PREV to "الشهر اللي فات",
    TextKey.PERIOD_PICKER_NEXT to "الشهر اللي بعده",
    TextKey.PERIOD_PICKER_CURRENT to "الشهر الحالي",
    TextKey.PERIOD_PICKER_PAST to "شهر فات",
    TextKey.PERIOD_PICKER_NOW_NOTE to "النهارده يوم {0} من {1}، فاضل {2} على المرتب",
    TextKey.PERIOD_PICKER_WAS to "كان {0}",
    TextKey.PERIOD_PICKER_DAYS_ONE to "يوم واحد",
    TextKey.PERIOD_PICKER_DAYS_TWO to "يومين",
    TextKey.PERIOD_PICKER_DAYS_FEW to "{0} أيام",
    TextKey.PERIOD_PICKER_DAYS_MANY to "{0} يوم",
    TextKey.PERIOD_PICKER_BACK to "ارجع للشهر الحالي",
    TextKey.PERIOD_PICKER_YEAR_PREV to "السنة اللي فاتت",
    TextKey.PERIOD_PICKER_YEAR_NEXT to "السنة اللي بعدها",
    TextKey.PERIOD_PICKER_NOW to "الحالي",
    TextKey.PERIOD_PICKER_NOT_STARTED to "لسه ما بدأش",
    TextKey.PERIOD_PICKER_BEFORE_DATA to "قبل بياناتك",
    TextKey.PERIOD_PICKER_DATA_FROM to "بياناتك بتبدأ من {0}.",
    TextKey.PERIOD_PICKER_FUTURE_NOTE to "الشهور الجاية بتفتح لما تبدأ.",
    TextKey.PERIOD_PICKER_RANGE to "{0} – {1}",
    TextKey.PERIOD_PICKER_DAY_MONTH_YEAR to "{0} {1}",
    TextKey.PERIOD_PICKER_TOAST to "{0} — {1}",
    TextKey.PERIOD_PICKER_PICKED_TOAST to "اخترت {0}",
    TextKey.PERIOD_PICKER_BACK_TOAST to "رجعت للشهر الحالي {0}",
)

internal val ENGLISH_AREA_HOME_NOTIFY_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.NOTIFICATIONS_TITLE to "Notifications",
    TextKey.NOTIFICATIONS_SETTINGS to "Notification settings",
    TextKey.NOTIFICATIONS_WAITING to "Waiting for your decision",
    TextKey.NOTIFICATIONS_NEW to "New",
    TextKey.NOTIFICATIONS_TODAY to "Today",
    TextKey.NOTIFICATIONS_YESTERDAY to "Yesterday",
    TextKey.NOTIFICATIONS_TWO_DAYS to "2 days ago",
    TextKey.NOTIFICATIONS_FEW_DAYS to "{0} days ago",
    TextKey.NOTIFICATIONS_MANY_DAYS to "{0} days ago",
    TextKey.NOTIFICATIONS_MUTED to "Muted",
    TextKey.NOTIFICATIONS_DROP to "Delete notification “{0}”",
    TextKey.NOTIFICATIONS_DROPPED to "Notification deleted",
    TextKey.NOTIFICATIONS_UNDO to "Undo",
    TextKey.NOTIFICATIONS_EMPTY_TITLE to "Nothing new",
    TextKey.NOTIFICATIONS_EMPTY_BODY to "We'll let you know when something matters.",
    TextKey.NOTIFICATIONS_LOCK_TITLE to "This is how it looks on the lock screen",
    TextKey.NOTIFICATIONS_LOCK_LETTER to "M",
    TextKey.NOTIFICATIONS_LOCK_NOW to "now",
    TextKey.NOTIFICATIONS_LOCK_NOTE to "No amounts, names or counts. Transactions recorded automatically from bank messages send no notification — you'll see them in Transactions with a shine.",
    TextKey.PERIOD_PICKER_TITLE to "Choose the month",
    TextKey.PERIOD_PICKER_INTRO to "Your month starts on day {0} (payday) and ends the day before it next month.",
    TextKey.PERIOD_PICKER_PREV to "Previous month",
    TextKey.PERIOD_PICKER_NEXT to "Next month",
    TextKey.PERIOD_PICKER_CURRENT to "Current month",
    TextKey.PERIOD_PICKER_PAST to "Past month",
    TextKey.PERIOD_PICKER_NOW_NOTE to "Day {0} of {1}, {2} to payday",
    TextKey.PERIOD_PICKER_WAS to "It was {0}",
    TextKey.PERIOD_PICKER_DAYS_ONE to "1 day",
    TextKey.PERIOD_PICKER_DAYS_TWO to "2 days",
    TextKey.PERIOD_PICKER_DAYS_FEW to "{0} days",
    TextKey.PERIOD_PICKER_DAYS_MANY to "{0} days",
    TextKey.PERIOD_PICKER_BACK to "Back to the current month",
    TextKey.PERIOD_PICKER_YEAR_PREV to "Previous year",
    TextKey.PERIOD_PICKER_YEAR_NEXT to "Next year",
    TextKey.PERIOD_PICKER_NOW to "Now",
    TextKey.PERIOD_PICKER_NOT_STARTED to "Not started yet",
    TextKey.PERIOD_PICKER_BEFORE_DATA to "Before your data",
    TextKey.PERIOD_PICKER_DATA_FROM to "Your data starts in {0}.",
    TextKey.PERIOD_PICKER_FUTURE_NOTE to "Upcoming months open when they start.",
    TextKey.PERIOD_PICKER_RANGE to "{0} – {1}",
    TextKey.PERIOD_PICKER_DAY_MONTH_YEAR to "{0} {1}",
    TextKey.PERIOD_PICKER_TOAST to "{0} — {1}",
    TextKey.PERIOD_PICKER_PICKED_TOAST to "Chose {0}",
    TextKey.PERIOD_PICKER_BACK_TOAST to "Back to the current month, {0}",
)
