package app.masroufy.core

/** باقي نصوص الواجهة المشتركة **بالإنجليزي** — كتابة Claude ومستنية مراجعة المالك (OVERRIDES §40). */
internal val ENGLISH_SHELL_AUTH_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.UPCOMING_TITLE to "Coming up",
    UiKey.UPCOMING_LIST to "Upcoming dates",
    UiKey.UPCOMING_TODAY to "Today",
    UiKey.UPCOMING_TOMORROW to "Tomorrow",
    UiKey.UPCOMING_TWO_DAYS to "In 2 days",
    UiKey.UPCOMING_FEW_DAYS to "In {0} days",
    UiKey.UPCOMING_MANY_DAYS to "In {0} days",
    UiKey.UPCOMING_HELD to "Set aside",
    UiKey.UPCOMING_OPEN to "Not set aside",
    UiKey.UPCOMING_NO_AMOUNT to "No amount",
    UiKey.UPCOMING_INCOMING to "Expected income",
    UiKey.UPCOMING_LATE to "Overdue",
    UiKey.UPCOMING_EMPTY to "No upcoming dates.",
    UiKey.CALENDAR_OPEN to "Calendar",
    UiKey.QUICK_TITLE to "Expected this month, not recorded yet",
    UiKey.QUICK_SHEET_BODY to "The usual amount is filled in — change it if it's different this month.",
    UiKey.QUICK_USUAL to "Usually {0}, on day {1}",
    UiKey.QUICK_FROM to "Paid from?",
    UiKey.QUICK_SAVE to "Record it",
    UiKey.QUICK_SKIP to "Not paying it this month",
    UiKey.QUICK_RECORDED to "Recorded “{0}” {1}",
    UiKey.QUICK_SKIPPED to "OK — we won't ask about it again this month.",
    UiKey.CAL_PREV to "Previous month",
    UiKey.CAL_NEXT to "Next month",
    UiKey.CAL_TODAY to "Today",
    UiKey.CAL_NO_DATES to "No dates",
    UiKey.CAL_LEGEND_SUB to "Subscriptions and bills",
    UiKey.CAL_LEGEND_INST to "Installments",
    UiKey.CAL_LEGEND_ROSCA to "Savings circles",
    UiKey.CAL_LEGEND_DEBT to "Debts",
    UiKey.CAL_LEGEND_EVENT to "Events and occasions",
    UiKey.CAL_LEGEND_PAY to "Payday",
    UiKey.CAL_LEGEND_LATE to "Overdue",
    UiKey.CAL_MORE to "+{0}",
    UiKey.SIGNIN_WELCOME_TITLE to "Welcome to Masroufy",
    UiKey.SIGNIN_WELCOME_SUB to "One minute to set up your account; the rest whenever you like.",
    UiKey.SIGNIN_HOW to "How do you want to sign in?",
    UiKey.SIGNIN_HOW_SUB to "Your account saves your data and syncs it to all your devices.",
    UiKey.SIGNIN_GOOGLE to "Sign in with Google",
    UiKey.SIGNIN_WITH_EMAIL to "Sign in with email",
    UiKey.SIGNIN_TITLE to "Sign in with email",
    UiKey.SIGNIN_MODES to "Sign-in type",
    UiKey.SIGNIN_MODE_IN to "Sign in",
    UiKey.SIGNIN_MODE_NEW to "New account",
    UiKey.SIGNIN_EMAIL to "Email",
    UiKey.SIGNIN_PASSWORD to "Password",
    UiKey.SIGNIN_PASS_HINT to "At least 6 characters.",
    UiKey.SIGNIN_SHOW_PASS to "Show password",
    UiKey.SIGNIN_HIDE_PASS to "Hide password",
    UiKey.SIGNIN_SUBMIT_IN to "Sign in",
    UiKey.SIGNIN_SUBMIT_NEW to "Create account",
    UiKey.SIGNIN_BUSY_IN to "Signing in…",
    UiKey.SIGNIN_BUSY_NEW to "Creating account…",
    UiKey.SIGNIN_DONE_IN to "Signed in",
    UiKey.SIGNIN_DONE_NEW to "Account created",
    UiKey.SIGNIN_DONE_LINE to "We will pick up setting up your account where you left off.",
    UiKey.SIGNIN_OFFLINE_NOTE to "Signing in needs an internet connection.",
    UiKey.SIGNIN_EMULATOR_NOTE to "Test build connected to the Firebase emulator on the computer — fake data only.",
    UiKey.RESET_TRIGGER to "Forgot your password?",
    UiKey.RESET_TITLE to "Reset password",
    UiKey.RESET_BODY to "Enter your email and we'll send it a link to set a new password.",
    UiKey.RESET_EMAIL_EMPTY to "Enter your email",
    UiKey.RESET_SEND to "Send reset link",
    UiKey.RESET_SENDING to "Sending…",
    UiKey.RESET_PRIVACY to "To protect accounts, we don't say whether an email is registered with us.",
    UiKey.RESET_SENT_TITLE to "Check your email",
    UiKey.RESET_SENT_BODY to "If {0} is registered with us, it will get a link to set a new password within minutes.",
    UiKey.RESET_SPAM to "Didn't arrive? Check your spam folder, or send it again.",
    UiKey.RESET_RESEND to "Send again",
    UiKey.RESET_AGAIN to "The link was sent again.",
    UiKey.RESET_WAIT_ONE to "You can send again in 1 second.",
    UiKey.RESET_WAIT_TWO to "You can send again in 2 seconds.",
    UiKey.RESET_WAIT_FEW to "You can send again in {0} seconds.",
    UiKey.RESET_WAIT_MANY to "You can send again in {0} seconds.",
    UiKey.RESET_CHANGE to "Change email",
    UiKey.RESET_FINISH to "Back to sign in",
    UiKey.RESET_OFFLINE to "Sending again needs an internet connection.",
    UiKey.LOCK_SCREEN_TITLE to "Masroufy is locked",
    UiKey.LOCK_SCREEN_BODY to "Unlock with your fingerprint or phone code.",
    UiKey.LOCK_SCREEN_OPEN to "Unlock",
    UiKey.LOCK_RELEASED to "Your phone has no lock, so the app lock was turned off. Turn it on from “More ← Settings” after setting a phone lock.",
    UiKey.FEED_OFFLINE to "No internet — couldn't update the prices.",
    UiKey.FEED_HTTP_FAILED to "Couldn't download the file (response {0}).",
    UiKey.FEED_UPDATED_AT to "Last updated {0}",
    UiKey.AUTH_GOOGLE_NO_ACCOUNT to "There's no Google account on this phone. Add one in the phone settings or sign in with email.",
    UiKey.AUTH_GOOGLE_FAILED to "Couldn't sign in with Google right now. Try again or sign in with email.",
)
