package app.masroufy.core

/**
 * نصوص شاشات منطقة «أول تشغيل» (`ui/screens/onboarding/`) — **الملف ده بتاع المنطقة بس** (المناطق بتتبني بالتوازي، ARCHITECTURE §31.31).
 * المفاتيح في `TextKeys.kt` **تحت سطر «منطقة أول تشغيل»** بس. الفصحى للسعودية والافتراضي · المصري لمصر (OVERRIDES §66) · الإنجليزي
 * (كتابة Claude — مستني مراجعة المالك §40). النص من النموذج التفاعلي بالحرف (الفصحى من `space = السعودية` والمصري من `مصر`).
 * **ممنوع «·» جنب رقم عربي** ⇒ «،». الملف قرّب على 300 سطر؟ اعمل `TextsAreaOnboarding2.kt` بخرايط جديدة وضمّها هنا بـ`+`.
 *
 * فروق عن النموذج (الصراحة — CLAUDE.md #15): «ليس ثابتًا» بيقول اليوم اللي هيفضل فعلًا (`{0}` = يوم الراتب المحفوظ، الافتراضي ٢٨)
 * بدل «نبدأ من أول الشهر» · الحلقة من غير نسبة (حسبة «ملفك ٪» لسه مالهاش منطق — `MeInfo.profilePercent`) · «١٠ ثوانٍ» رقمها `{0}`
 * عشان قرار الأرقام (§79) يتطبق عليها من مكان واحد. شكل المصري قبل اختيار البلد: النموذج فصحى لحد البلد، هنا بنسخة البلد الشغالة.
 */
internal val MSA_AREA_ONBOARDING_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ONB_STEP_OF to "الخطوة {0} من {1}",
    TextKey.ONB_SKIP to "تخطَّ",
    TextKey.ONB_NEXT to "متابعة",
    TextKey.ONB_DONE_NEXT to "انتهينا",
    TextKey.ONB_OK to "تم",
    TextKey.ONB_LOOK_TITLE to "اختر شكلك",
    TextKey.ONB_LOOK_SUB to "يمكنك تغييره لاحقًا.",
    TextKey.ONB_COUNTRY_TITLE to "أين تقيم؟",
    TextKey.ONB_COUNTRY_SUB to "يحدد العملة، والبنوك التي نفهم رسائلها، وقواعد الزكاة.",
    TextKey.ONB_CUR_SAR to "الريال السعودي",
    TextKey.ONB_CUR_EGP to "الجنيه المصري",
    TextKey.ONB_COUNTRY_NOT_YET to "إضافة بلد غير متاحة بعد",
    TextKey.ONB_PAY_TITLE to "في أي يوم ينزل راتبك؟",
    TextKey.ONB_PAY_SUB to "يبدأ شهرك المالي من هذا اليوم.",
    TextKey.ONB_NOT_FIXED to "ليس ثابتًا — اسألني لاحقًا",
    TextKey.ONB_SRC_TITLE to "من أين تصل عملياتك؟",
    TextKey.ONB_SRC_SUB to "لتدخل عملياتك وحدها.",
    TextKey.ONB_SRC_SMS to "رسائل البنك",
    TextKey.ONB_SRC_SMS_SUB to "على أندرويد",
    TextKey.ONB_SRC_SMS_IOS to "لا يقرأ الآيفون رسائل البنك.",
    TextKey.ONB_SRC_FILE to "كشف حساب",
    TextKey.ONB_SRC_FILE_SUB to "ملف من البنك ترفعه بنفسك",
    TextKey.ONB_SRC_LATER to "لاحقًا",
    TextKey.ONB_SRC_LATER_SUB to "من الإعدادات متى شئت",
    TextKey.ONB_READY_TITLE to "حسابك جاهز",
    TextKey.ONB_READY_SUB to "الباقي بطاقات صغيرة داخل التطبيق، كل منها {0} ثوانٍ.",
    TextKey.ONB_RING_NO_PERCENT to "نسبة ملفك غير متاحة بعد",
    TextKey.ONB_ENTER to "ادخل التطبيق",
    TextKey.ONB_SAVING to "جارٍ الحفظ…",
    TextKey.ONB_FINISH_FAILED to "تعذّر حفظ إجاباتك. أعد المحاولة.",
    TextKey.ONB_R_LOOK_T to "حُفظ",
    TextKey.ONB_R_LOOK_L to "هذا شكلك في التطبيق.",
    TextKey.ONB_R_SA_L to "الريال ورسائل مصرف الراجحي جاهزة.",
    TextKey.ONB_R_EG_L to "الجنيه ورسائل QNB مصر جاهزة.",
    TextKey.ONB_R_DAY_T to "ضُبط",
    TextKey.ONB_R_DAY_L to "يبدأ شهرك المالي يوم {0} من كل شهر.",
    TextKey.ONB_R_LATER_T to "لا بأس",
    TextKey.ONB_R_DAY_LATER_L to "يبقى شهرك المالي يبدأ يوم {0} حتى تخبرنا.",
    TextKey.ONB_R_SMS_L to "سنطلب الإذن في الخطوة التالية داخل التطبيق.",
    TextKey.ONB_R_FILE_L to "ارفعه من داخل التطبيق متى شئت.",
    TextKey.ONB_R_SRC_LATER_L to "يمكنك ربط البنك لاحقًا من الإعدادات.",
)

internal val EGYPTIAN_AREA_ONBOARDING_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ONB_STEP_OF to "الخطوة {0} من {1}",
    TextKey.ONB_SKIP to "تخطّي",
    TextKey.ONB_NEXT to "كمّل",
    TextKey.ONB_DONE_NEXT to "خلصنا",
    TextKey.ONB_OK to "تمام",
    TextKey.ONB_LOOK_TITLE to "اختار شكلك",
    TextKey.ONB_LOOK_SUB to "تقدر تغيّره بعدين.",
    TextKey.ONB_COUNTRY_TITLE to "إنت فين؟",
    TextKey.ONB_COUNTRY_SUB to "بيحدد العملة، والبنوك اللي بنفهم رسايلها، وقواعد الزكاة.",
    TextKey.ONB_CUR_SAR to "الريال السعودي",
    TextKey.ONB_CUR_EGP to "الجنيه المصري",
    TextKey.ONB_COUNTRY_NOT_YET to "إضافة بلد لسه مش متاحة",
    TextKey.ONB_PAY_TITLE to "مرتبك بينزل يوم كام؟",
    TextKey.ONB_PAY_SUB to "شهرك المالي بيبدأ من اليوم ده.",
    TextKey.ONB_NOT_FIXED to "مش ثابت — اسألني بعدين",
    TextKey.ONB_SRC_TITLE to "فلوسك بتيجي منين؟",
    TextKey.ONB_SRC_SUB to "عشان عملياتك تدخل لوحدها.",
    TextKey.ONB_SRC_SMS to "رسايل البنك",
    TextKey.ONB_SRC_SMS_SUB to "على أندرويد",
    TextKey.ONB_SRC_SMS_IOS to "الآيفون ما بيقراش رسايل البنك.",
    TextKey.ONB_SRC_FILE to "كشف حساب",
    TextKey.ONB_SRC_FILE_SUB to "ملف من البنك ترفعه بنفسك",
    TextKey.ONB_SRC_LATER to "بعدين",
    TextKey.ONB_SRC_LATER_SUB to "من الإعدادات وقت ما تحب",
    TextKey.ONB_READY_TITLE to "حسابك جاهز",
    TextKey.ONB_READY_SUB to "الباقي كروت صغيرة جوه التطبيق، كل واحد {0} ثواني.",
    TextKey.ONB_RING_NO_PERCENT to "نسبة ملفك لسه مش متاحة",
    TextKey.ONB_ENTER to "ادخل التطبيق",
    TextKey.ONB_SAVING to "بنحفظ…",
    TextKey.ONB_FINISH_FAILED to "إجاباتك ما اتحفظتش. جرّب تاني.",
    TextKey.ONB_R_LOOK_T to "اتحفظ",
    TextKey.ONB_R_LOOK_L to "ده شكلك في التطبيق.",
    TextKey.ONB_R_SA_L to "الريال ورسايل مصرف الراجحي جاهزين.",
    TextKey.ONB_R_EG_L to "الجنيه ورسايل QNB مصر جاهزين.",
    TextKey.ONB_R_DAY_T to "اتظبط",
    TextKey.ONB_R_DAY_L to "شهرك المالي بيبدأ يوم {0} من كل شهر.",
    TextKey.ONB_R_LATER_T to "مفيش مشكلة",
    TextKey.ONB_R_DAY_LATER_L to "شهرك المالي هيفضل يبدأ يوم {0} لحد ما تقولنا.",
    TextKey.ONB_R_SMS_L to "هنطلب الإذن في الخطوة الجاية جوه التطبيق.",
    TextKey.ONB_R_FILE_L to "ترفعه من جوه التطبيق وقت ما تحب.",
    TextKey.ONB_R_SRC_LATER_L to "تقدر توصّل البنك بعدين من الإعدادات.",
)

internal val ENGLISH_AREA_ONBOARDING_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ONB_STEP_OF to "Step {0} of {1}",
    TextKey.ONB_SKIP to "Skip",
    TextKey.ONB_NEXT to "Continue",
    TextKey.ONB_DONE_NEXT to "All done",
    TextKey.ONB_OK to "Done",
    TextKey.ONB_LOOK_TITLE to "Choose your look",
    TextKey.ONB_LOOK_SUB to "You can change it later.",
    TextKey.ONB_COUNTRY_TITLE to "Where do you live?",
    TextKey.ONB_COUNTRY_SUB to "It sets the currency, the banks whose messages we read, and the zakat rules.",
    TextKey.ONB_CUR_SAR to "Saudi riyal",
    TextKey.ONB_CUR_EGP to "Egyptian pound",
    TextKey.ONB_COUNTRY_NOT_YET to "Adding a country isn't available yet",
    TextKey.ONB_PAY_TITLE to "What day does your salary arrive?",
    TextKey.ONB_PAY_SUB to "Your financial month starts on this day.",
    TextKey.ONB_NOT_FIXED to "It varies — ask me later",
    TextKey.ONB_SRC_TITLE to "Where do your transactions come from?",
    TextKey.ONB_SRC_SUB to "So your transactions come in by themselves.",
    TextKey.ONB_SRC_SMS to "Bank messages",
    TextKey.ONB_SRC_SMS_SUB to "On Android",
    TextKey.ONB_SRC_SMS_IOS to "iPhone can't read bank messages.",
    TextKey.ONB_SRC_FILE to "Bank statement",
    TextKey.ONB_SRC_FILE_SUB to "A file from your bank that you upload",
    TextKey.ONB_SRC_LATER to "Later",
    TextKey.ONB_SRC_LATER_SUB to "From settings, whenever you like",
    TextKey.ONB_READY_TITLE to "Your account is ready",
    TextKey.ONB_READY_SUB to "The rest is small cards inside the app, {0} seconds each.",
    TextKey.ONB_RING_NO_PERCENT to "Your profile percentage isn't available yet",
    TextKey.ONB_ENTER to "Enter the app",
    TextKey.ONB_SAVING to "Saving…",
    TextKey.ONB_FINISH_FAILED to "Couldn't save your answers. Try again.",
    TextKey.ONB_R_LOOK_T to "Saved",
    TextKey.ONB_R_LOOK_L to "This is your look in the app.",
    TextKey.ONB_R_SA_L to "Riyal and Al Rajhi Bank messages are ready.",
    TextKey.ONB_R_EG_L to "Pound and QNB Egypt messages are ready.",
    TextKey.ONB_R_DAY_T to "Set",
    TextKey.ONB_R_DAY_L to "Your financial month starts on day {0} of every month.",
    TextKey.ONB_R_LATER_T to "No problem",
    TextKey.ONB_R_DAY_LATER_L to "Your financial month keeps starting on day {0} until you tell us.",
    TextKey.ONB_R_SMS_L to "We'll ask for permission in the next step inside the app.",
    TextKey.ONB_R_FILE_L to "Upload it from inside the app whenever you like.",
    TextKey.ONB_R_SRC_LATER_L to "You can connect your bank later from settings.",
)
