package app.masroufy.core

/**
 * «العمليات» بالمصري (لمصر — OVERRIDES §66) — الجزء الأول: القايمة · القايمة السائلة · التفاصيل · التصنيف · الوسوم · التصفية.
 * النص من النموذج التفاعلي (`space = مصر`) بالحرف قدر الإمكان. **ممنوع «·» جنب رقم عربي** ⇒ «،».
 */
internal val EGYPTIAN_OPERATIONS_LIST_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.OPERATIONS_FILTER to "فلترة العمليات",
    TextKey.OPERATIONS_PERIOD to "الشهر",
    TextKey.OPERATIONS_TAB_OPS to "العمليات",
    TextKey.OPERATIONS_TAB_BUDGETS to "الميزانيات",
    TextKey.OPERATIONS_TAB_DUES to "المستحقات",
    TextKey.OPERATIONS_ERROR_TITLE to "تعذّر تحميل العمليات",
    TextKey.OPERATIONS_ERROR_BODY to "تحقق من الاتصال ثم أعد المحاولة.",
    TextKey.OPERATIONS_EMPTY_TITLE to "لا توجد عمليات في {0}",
    TextKey.OPERATIONS_EMPTY_BODY to "أضف عملية أو استورد كشف حسابك.",
    TextKey.OPERATIONS_INCOME to "دخل الشهر",
    TextKey.OPERATIONS_EXPENSE to "المصروف الحقيقي",
    TextKey.OPERATIONS_APPROX_NOTE to "شوية أنواع تقديرية لحد ما تأكدها.",
    TextKey.OPERATIONS_TODAY to "النهارده",
    TextKey.OPERATIONS_YESTERDAY to "أمس",
    TextKey.OPERATIONS_ROW_MOVE to "{0}، {1} ← {2}",
    TextKey.OPERATIONS_ROW_ACCOUNT to "حساب آخره {0}",
    TextKey.OPERATIONS_ROW_FROM to "من {0}",
    TextKey.OPERATIONS_ROW_TO to "لـ{0}",
    TextKey.OPERATIONS_ROW_UNCLASSIFIED to "من غير تصنيف",
    TextKey.OPERATIONS_ROW_ACTIONS to "إجراءات {0}",
    TextKey.OPERATIONS_UNRECORDED to "غير مسجّلة",
    TextKey.OPERATIONS_COUNT_ONE to "عملية واحدة",
    TextKey.OPERATIONS_COUNT_TWO to "عمليتين",
    TextKey.OPERATIONS_COUNT_FEW to "{0} عمليات",
    TextKey.OPERATIONS_COUNT_MANY to "{0} عملية",
    TextKey.OPERATIONS_SMS_ONE to "رسالة من البنك مستنية تأكيدك",
    TextKey.OPERATIONS_SMS_TWO to "رسالتين من البنك مستنيين تأكيدك",
    TextKey.OPERATIONS_SMS_FEW to "{0} رسايل من البنك مستنية تأكيدك",
    TextKey.OPERATIONS_SMS_MANY to "{0} رسالة من البنك مستنية تأكيدك",
    TextKey.OPERATIONS_BANNER_REVIEW to "{0} نوعها مش أكيد",
    TextKey.OPERATIONS_PARTIES_ONE to "طرف مستني ردك",
    TextKey.OPERATIONS_PARTIES_TWO to "طرفين مستنيين ردك",
    TextKey.OPERATIONS_PARTIES_FEW to "{0} أطراف مستنية ردك",
    TextKey.OPERATIONS_PARTIES_MANY to "{0} طرف مستني ردك",
    TextKey.OPERATION_MENU_TITLE to "إجراءات العملية",
    TextKey.OPERATION_MENU_DETAIL to "شوف التفاصيل",
    TextKey.OPERATION_MENU_PERSON to "خصّص مبلغ لشخص",
    TextKey.OPERATION_MENU_ALL to "كل الإجراءات",
    TextKey.OPERATION_DETAIL_TITLE to "تفاصيل العملية",
    TextKey.OPERATION_DETAIL_ERROR_TITLE to "ما قدرناش نحمّل العملية",
    TextKey.OPERATION_DETAIL_SUB to "{0}، {1}",
    TextKey.OPERATION_DETAIL_IN to "دخل",
    TextKey.OPERATION_DETAIL_OUT to "صرف",
    TextKey.OPERATION_DETAIL_MERCHANT to "صفحة التاجر",
    TextKey.OPERATION_DETAIL_LOCK to "التاريخ والاتجاه جايين من المصدر، ما بيتعدلوش",
    TextKey.OPERATION_DETAIL_LOCK_CASH to "المبلغ من فرق العدّ",
    TextKey.OPERATION_DETAIL_CASH_TITLE to "دي مش عملية اتسجلت",
    TextKey.OPERATION_DETAIL_CASH_BODY to "ده فرق عدّ الكاش. داخل في صرف الشهر بنقطة حمرا لحد ما تقول اتصرف في إيه.",
    TextKey.OPERATION_DETAIL_WALLET to "المحفظة",
    TextKey.OPERATION_DETAIL_CATEGORY to "التصنيف",
    TextKey.OPERATION_DETAIL_KIND to "النوع",
    TextKey.OPERATION_DETAIL_KIND_WAITING to "مستني تحدد النوع",
    TextKey.OPERATION_DETAIL_WAITING_CHIP to "مستني",
    TextKey.OPERATION_DETAIL_KIND_ESTIMATED to "تقديري لحد ما تأكده",
    TextKey.OPERATION_DETAIL_SUGGESTED to "مقترح",
    TextKey.OPERATION_DETAIL_SUGGESTED_HINT to "محتاج تأكيدك",
    TextKey.OPERATION_DETAIL_CONFIRMED_CHIP to "مؤكد",
    TextKey.OPERATION_DETAIL_CHANGE to "غيّر",
    TextKey.OPERATION_DETAIL_CONFIRM to "تمام",
    TextKey.OPERATION_DETAIL_CATEGORIZE to "صنّفها",
    TextKey.OPERATION_DETAIL_CONFIRMED to "اتأكد التصنيف",
    TextKey.OPERATION_DETAIL_REMEMBERED to "تمام — «{0}» هيتصنّف «{1}» على طول",
    TextKey.OPERATION_DETAIL_CATEGORIZED to "تمام — اتصنّفت «{0}»",
    TextKey.OPERATION_DETAIL_LINK_TITLE to "اربطها بـ",
    TextKey.CATEGORY_PICKER_CASH_TITLE to "اتصرف في إيه؟",
    TextKey.CATEGORY_PICKER_TITLE to "تصنيف «{0}»",
    TextKey.CATEGORY_PICKER_EMPTY to "مفيش تصنيفات لسه.",
    TextKey.TAGS_SHEET_LABEL to "الوسوم",
    TextKey.TAGS_SHEET_NONE to "من غير وسوم",
    TextKey.TAGS_SHEET_ADD_TRIGGER to "ضيف وسم",
    TextKey.TAGS_SHEET_EDIT to "عدّل",
    TextKey.TAGS_SHEET_TITLE to "وسوم العملية",
    TextKey.TAGS_SHEET_BODY to "الوسم للبحث والتقارير بس — ما بيغيّرش المبلغ ولا بيتحسب مرتين. والوسوم مشتركة بين البلاد.",
    TextKey.TAGS_SHEET_EMPTY_LINE to "مفيش وسوم على العملية دي.",
    TextKey.TAGS_SHEET_INPUT to "وسم جديد أو دوّر",
    TextKey.TAGS_SHEET_ADD to "ضيف",
    TextKey.TAGS_SHEET_COUNTER to "{0}/{1}",
    TextKey.TAGS_SHEET_ALL to "وسومك",
    TextKey.TAGS_SHEET_NO_MATCH to "مفيش وسم بالاسم ده — «ضيف» يعمله جديد.",
    TextKey.TAGS_SHEET_ALL_ON to "كل وسومك على العملية دي.",
    TextKey.TAGS_SHEET_DONE to "تمام",
    TextKey.TAGS_SHEET_REMOVE to "شيل وسم {0}",
    TextKey.TAGS_SHEET_ADD_ONE to "ضيف وسم {0}",
    TextKey.TAGS_SHEET_ADDED to "اتضاف «{0}»",
    TextKey.TAGS_SHEET_CREATED to "اتعمل وسم جديد «{0}» واتضاف",
    TextKey.TAGS_SHEET_ALREADY to "«{0}» موجود على العملية",
    TextKey.TAGS_SHEET_REMOVED to "اتشال «{0}»",
    TextKey.OPERATION_FILTERS_TITLE to "فلترة العمليات",
    TextKey.OPERATION_FILTERS_RESULTS to "النتيجة",
    TextKey.OPERATION_FILTERS_CLEAR to "امسح الكل",
    TextKey.OPERATION_FILTERS_SEARCH to "اسم محل، شخص، ملاحظة…",
    TextKey.OPERATION_FILTERS_AMOUNT to "المبلغ ({0})",
    TextKey.OPERATION_FILTERS_NEAR to "قريب منه ±٥٪",
    TextKey.OPERATION_FILTERS_NEAR_CHIP to "≈ {0}",
    TextKey.OPERATION_FILTERS_PERIOD to "الفترة",
    TextKey.OPERATION_FILTERS_THIS to "الشهر ده",
    TextKey.OPERATION_FILTERS_LAST to "الشهر اللي فات",
    TextKey.OPERATION_FILTERS_THREE to "آخر ٣ شهور",
    TextKey.OPERATION_FILTERS_KIND to "النوع",
    TextKey.OPERATION_FILTERS_KIND_OUT to "مصروف",
    TextKey.OPERATION_FILTERS_KIND_IN to "دخل",
    TextKey.OPERATION_FILTERS_KIND_MOVE to "بين محافظك",
    TextKey.OPERATION_FILTERS_KIND_DEBT to "ديون وأقساط",
    TextKey.OPERATION_FILTERS_REVIEW to "المراجعة",
    TextKey.OPERATION_FILTERS_REVIEW_ALL to "الكل",
    TextKey.OPERATION_FILTERS_REVIEW_OK to "متأكدة",
    TextKey.OPERATION_FILTERS_REVIEW_NEEDS to "محتاجة تأكيد",
    TextKey.OPERATION_FILTERS_QUOTED to "«{0}»",
    TextKey.OPERATION_FILTERS_DROP to "شيل {0}",
    TextKey.OPERATION_FILTERS_NONE to "مفيش نتايج",
    TextKey.OPERATION_FILTERS_NONE_BODY to "شيل فلتر أو اتنين وجرّب تاني.",
    TextKey.OPERATION_FILTERS_SHOW to "اعرض {0}",
    TextKey.OPERATION_FILTERS_EDIT to "عدّل الفلاتر",
)
