package app.masroufy.core

/**
 * «تعديل المصدر» (`IncomeSourceEditSheet`) و«غيّرت عملي / أضف مصدر دخل / إنهاء» (`JobChangeSheet`) — منطقة «المزيد». من النموذج بالحرف، إلا:
 * - سؤال بداية الشهر من غير «من الشهر القادم» (كوتلن بيغيّر كل الشهور — سطر «غير متاح بعد» جنبه يقول كده، قرار المالك 2026-10-09 لسه ناقص).
 * - «تاريخ آخر» بخانة وغلطها — كتابة Claude.
 */
internal val MSA_MORE_JOB_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INCEDIT_TITLE to "تعديل المصدر",
    TextKey.INCEDIT_NAME to "اسم الشركة أو الجهة",
    TextKey.INCEDIT_DAY to "يوم القبض في الشهر (اختياري)",
    TextKey.INCEDIT_DAY_EMPTY to "فارغ = بلا موعد ثابت، ولا تنبيه إن تأخر.",
    TextKey.INCEDIT_DAY_NOTE to "٢٩–٣١ في الشهور الأقصر = آخر يوم فيها.",
    TextKey.INCEDIT_WEEKDAY to "يوم القبض في الأسبوع",
    TextKey.INCEDIT_MONTH_INFO to "يبدأ شهرك المالي يوم {0}",
    TextKey.INCEDIT_MONTH_SAME to "يوم {0} هو أيضًا بداية شهرك المالي",
    TextKey.INCEDIT_MONTH_NOTE to "للحساب كله في البلدين — ولا يتغيّر من هنا إلا بموافقتك.",
    TextKey.INCEDIT_EXPECTED to "المتوقع (اختياري)",
    TextKey.INCEDIT_EXPECTED_PH to "غير معروف",
    TextKey.INCEDIT_EXPECTED_EMPTY to "فارغ = «غير متاح» — لا نكتب صفرًا مكانه.",
    TextKey.INCEDIT_EXPECTED_NOTE to "للمعلومة فقط — لا نقارنه بأي إيداع.",
    TextKey.INCEDIT_PAST_HEAD to "انتهى في {0}",
    TextKey.INCEDIT_PAST_NOTE to "الرجوع إلى الجهة نفسها يُسجَّل فترة جديدة بالاسم نفسه — من «أضف مصدر دخل».",
    TextKey.INCEDIT_ERR_NAME to "اكتب اسم المصدر.",
    TextKey.INCEDIT_ERR_DAY to "اليوم من ١ إلى ٣١.",
    TextKey.INCEDIT_ERR_EXPECTED to "اكتب مبلغًا أكبر من صفر، أو اتركه فارغًا.",
    TextKey.INCEDIT_ERR_MONTH to "اختر: هل تتغيّر بداية شهرك المالي؟",
    TextKey.INCEDIT_UNCHANGED to "لم يتغيّر شيء",
    TextKey.INCEDIT_SAVE to "احفظ التعديل",
    TextKey.INCEDIT_SAVED to "حُفظ التعديل",
    TextKey.JOB_CLOSE_TITLE to "إنهاء «{0}»",
    TextKey.JOB_SUB_CLOSE to "يبقى المصدر في «السابقة» بتاريخه، ولا يُحذف شيء.",
    TextKey.JOB_SUB_CHANGE to "نغلق القديم بتاريخ ونفتح الجديد.",
    TextKey.JOB_SUB_ADD to "الاسم وتاريخ البداية فقط إلزاميان.",
    TextKey.JOB_SUB_NEW to "العمل الجديد",
    TextKey.JOB_SUB_ASK to "أسئلة سريعة، ويمكنك تخطي أيٍّ منها.",
    TextKey.JOB_WHICH_ENDED to "أيّ عمل انتهى؟",
    TextKey.JOB_WHEN_ENDED to "متى انتهى؟",
    TextKey.JOB_CLOSE_GO to "إنهاء",
    TextKey.JOB_NEXT to "التالي",
    TextKey.JOB_NAME to "اسم الشركة أو العميل",
    TextKey.JOB_NAME_PH to "مثلًا: شركة الأفق",
    TextKey.JOB_KIND to "النوع",
    TextKey.JOB_WHEN_STARTED to "متى بدأ؟",
    TextKey.JOB_ADD_GO to "إضافة",
    TextKey.JOB_ADDED to "أُضيف «{0}»",
    TextKey.JOB_CONGRATS to "مبارك الوظيفة الجديدة في «{0}»!",
    TextKey.JOB_CLOSED_LINE to "أُغلق «{0}» في {1}.",
    TextKey.JOB_Q_PAYDAY to "في أي يوم من الشهر ينزل الراتب الجديد؟",
    TextKey.JOB_Q_MONTH_START to "هل تغيّر بداية شهرك المالي إلى يوم {0}؟",
    TextKey.JOB_MONTH_YES to "نعم، غيّرها",
    TextKey.JOB_MONTH_NO to "لا، تبقى {0}",
    TextKey.JOB_Q_EXPECTED to "كم الراتب المتوقع؟ (اختياري — يمكنك تخطيه)",
    TextKey.JOB_Q_FREQUENCY to "متى تقبض من هذه الوظيفة؟ شهريًا أم أسبوعيًا؟",
    TextKey.JOB_Q_WEEKDAY to "في أي يوم من الأسبوع؟",
    TextKey.JOB_Q_MONTH_DAY to "في أي يوم من الشهر؟",
    TextKey.JOB_FREQ_MONTHLY to "شهريًا",
    TextKey.JOB_FREQ_WEEKLY to "أسبوعيًا",
    TextKey.JOB_Q_STEP to "{0} من {1}",
    TextKey.JOB_SKIP to "تخطَّ",
    TextKey.JOB_DONE_PAYDAY to "القبض يوم {0}",
    TextKey.JOB_DONE_WEEKDAY to "القبض كل {0}",
    TextKey.JOB_DONE_EXPECTED to "المتوقع {0}",
    TextKey.JOB_DONE_LATER to "يمكنك إكمال الباقي من تفاصيل المصدر لاحقًا.",
    TextKey.JOB_OTHER_DATE to "تاريخ آخر",
    TextKey.JOB_DATE_BAD to "اكتب التاريخ بالشكل 2026-10-07",
)

internal val EGYPTIAN_MORE_JOB_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INCEDIT_TITLE to "تعديل المصدر",
    TextKey.INCEDIT_NAME to "اسم الشركة أو الجهة",
    TextKey.INCEDIT_DAY to "يوم القبض في الشهر (مش لازم)",
    TextKey.INCEDIT_DAY_EMPTY to "فاضي = من غير ميعاد ثابت، ومفيش تنبيه لو اتأخر.",
    TextKey.INCEDIT_DAY_NOTE to "٢٩–٣١ في الشهور الأقصر = آخر يوم فيها.",
    TextKey.INCEDIT_WEEKDAY to "يوم القبض في الأسبوع",
    TextKey.INCEDIT_MONTH_INFO to "شهرك المالي بيبدأ يوم {0}",
    TextKey.INCEDIT_MONTH_SAME to "يوم {0} هو كمان بداية شهرك المالي",
    TextKey.INCEDIT_MONTH_NOTE to "للحساب كله في البلدين — ومش بيتغيّر من هنا غير لو وافقت.",
    TextKey.INCEDIT_EXPECTED to "المتوقع (مش لازم)",
    TextKey.INCEDIT_EXPECTED_PH to "مش معروف",
    TextKey.INCEDIT_EXPECTED_EMPTY to "فاضي = «غير متاح» — مش بنكتب صفر مكانه.",
    TextKey.INCEDIT_EXPECTED_NOTE to "للمعلومة بس — مش بنقارنه بأي إيداع.",
    TextKey.INCEDIT_PAST_HEAD to "خلص في {0}",
    TextKey.INCEDIT_PAST_NOTE to "الرجوع لنفس الجهة بيتسجل فترة جديدة بنفس الاسم — من «ضيف مصدر دخل».",
    TextKey.INCEDIT_ERR_NAME to "اكتب اسم المصدر.",
    TextKey.INCEDIT_ERR_DAY to "اليوم من ١ لـ٣١.",
    TextKey.INCEDIT_ERR_EXPECTED to "اكتب مبلغ أكبر من صفر، أو سيبه فاضي.",
    TextKey.INCEDIT_ERR_MONTH to "اختار: بداية شهرك المالي تتغيّر ولا لأ؟",
    TextKey.INCEDIT_UNCHANGED to "مفيش تغيير",
    TextKey.INCEDIT_SAVE to "احفظ التعديل",
    TextKey.INCEDIT_SAVED to "اتحفظ التعديل",
    TextKey.JOB_CLOSE_TITLE to "إنهاء «{0}»",
    TextKey.JOB_SUB_CLOSE to "المصدر بيفضل في «اللي فاتت» بتاريخه، ومفيش حاجة بتتمسح.",
    TextKey.JOB_SUB_CHANGE to "نقفل القديم بتاريخ ونفتح الجديد.",
    TextKey.JOB_SUB_ADD to "الاسم وتاريخ البداية بس اللي لازم.",
    TextKey.JOB_SUB_NEW to "الشغل الجديد",
    TextKey.JOB_SUB_ASK to "كام سؤال سريع، وكلهم تقدر تعدّيهم.",
    TextKey.JOB_WHICH_ENDED to "إيه اللي خلص؟",
    TextKey.JOB_WHEN_ENDED to "خلص إمتى؟",
    TextKey.JOB_CLOSE_GO to "إنهاء",
    TextKey.JOB_NEXT to "التالي",
    TextKey.JOB_NAME to "اسم الشركة أو العميل",
    TextKey.JOB_NAME_PH to "مثلًا: شركة النيل",
    TextKey.JOB_KIND to "النوع",
    TextKey.JOB_WHEN_STARTED to "بدأ إمتى؟",
    TextKey.JOB_ADD_GO to "ضيف",
    TextKey.JOB_ADDED to "اتضاف «{0}»",
    TextKey.JOB_CONGRATS to "مبروك الشغل الجديد في «{0}»!",
    TextKey.JOB_CLOSED_LINE to "«{0}» اتقفل في {1}.",
    TextKey.JOB_Q_PAYDAY to "المرتب الجديد بينزل يوم كام في الشهر؟",
    TextKey.JOB_Q_MONTH_START to "تغيّر بداية شهرك المالي ليوم {0}؟",
    TextKey.JOB_MONTH_YES to "أيوه، غيّرها",
    TextKey.JOB_MONTH_NO to "لأ، تفضل {0}",
    TextKey.JOB_Q_EXPECTED to "المرتب المتوقع كام؟ (اختياري — تقدر تعدّيه)",
    TextKey.JOB_Q_FREQUENCY to "بتقبض من الشغل ده إمتى؟ كل شهر ولا كل أسبوع؟",
    TextKey.JOB_Q_WEEKDAY to "يوم إيه في الأسبوع؟",
    TextKey.JOB_Q_MONTH_DAY to "يوم كام في الشهر؟",
    TextKey.JOB_FREQ_MONTHLY to "كل شهر",
    TextKey.JOB_FREQ_WEEKLY to "كل أسبوع",
    TextKey.JOB_Q_STEP to "{0} من {1}",
    TextKey.JOB_SKIP to "عدّي",
    TextKey.JOB_DONE_PAYDAY to "القبض يوم {0}",
    TextKey.JOB_DONE_WEEKDAY to "القبض كل {0}",
    TextKey.JOB_DONE_EXPECTED to "المتوقع {0}",
    TextKey.JOB_DONE_LATER to "تقدر تكمّل الباقي من تفاصيل المصدر بعدين.",
    TextKey.JOB_OTHER_DATE to "تاريخ تاني",
    TextKey.JOB_DATE_BAD to "اكتب التاريخ كده 2026-10-07",
)

internal val ENGLISH_MORE_JOB_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INCEDIT_TITLE to "Edit source",
    TextKey.INCEDIT_NAME to "Company or payer name",
    TextKey.INCEDIT_DAY to "Pay day of the month (optional)",
    TextKey.INCEDIT_DAY_EMPTY to "Empty = no fixed date, and no alert if it's late.",
    TextKey.INCEDIT_DAY_NOTE to "29–31 in shorter months = their last day.",
    TextKey.INCEDIT_WEEKDAY to "Pay day of the week",
    TextKey.INCEDIT_MONTH_INFO to "Your financial month starts on day {0}",
    TextKey.INCEDIT_MONTH_SAME to "Day {0} is also when your financial month starts",
    TextKey.INCEDIT_MONTH_NOTE to "For the whole account in both countries — it only changes here if you agree.",
    TextKey.INCEDIT_EXPECTED to "Expected (optional)",
    TextKey.INCEDIT_EXPECTED_PH to "Unknown",
    TextKey.INCEDIT_EXPECTED_EMPTY to "Empty = “Not available” — we never write zero in its place.",
    TextKey.INCEDIT_EXPECTED_NOTE to "For information only — we don't compare it with any deposit.",
    TextKey.INCEDIT_PAST_HEAD to "Ended on {0}",
    TextKey.INCEDIT_PAST_NOTE to "Going back to the same payer is recorded as a new period with the same name — from “Add an income source”.",
    TextKey.INCEDIT_ERR_NAME to "Write the source's name.",
    TextKey.INCEDIT_ERR_DAY to "The day is from 1 to 31.",
    TextKey.INCEDIT_ERR_EXPECTED to "Write an amount above zero, or leave it empty.",
    TextKey.INCEDIT_ERR_MONTH to "Choose: does your financial month's start change?",
    TextKey.INCEDIT_UNCHANGED to "Nothing changed",
    TextKey.INCEDIT_SAVE to "Save the change",
    TextKey.INCEDIT_SAVED to "Change saved",
    TextKey.JOB_CLOSE_TITLE to "End “{0}”",
    TextKey.JOB_SUB_CLOSE to "The source stays under “Past” with its date; nothing is deleted.",
    TextKey.JOB_SUB_CHANGE to "We close the old one with a date and open the new one.",
    TextKey.JOB_SUB_ADD to "Only the name and start date are required.",
    TextKey.JOB_SUB_NEW to "The new job",
    TextKey.JOB_SUB_ASK to "A few quick questions; you can skip any of them.",
    TextKey.JOB_WHICH_ENDED to "Which job ended?",
    TextKey.JOB_WHEN_ENDED to "When did it end?",
    TextKey.JOB_CLOSE_GO to "End it",
    TextKey.JOB_NEXT to "Next",
    TextKey.JOB_NAME to "Company or client name",
    TextKey.JOB_NAME_PH to "e.g. Horizon Company",
    TextKey.JOB_KIND to "Type",
    TextKey.JOB_WHEN_STARTED to "When did it start?",
    TextKey.JOB_ADD_GO to "Add",
    TextKey.JOB_ADDED to "“{0}” added",
    TextKey.JOB_CONGRATS to "Congratulations on the new job at “{0}”!",
    TextKey.JOB_CLOSED_LINE to "“{0}” closed on {1}.",
    TextKey.JOB_Q_PAYDAY to "What day of the month does the new salary arrive?",
    TextKey.JOB_Q_MONTH_START to "Change your financial month's start to day {0}?",
    TextKey.JOB_MONTH_YES to "Yes, change it",
    TextKey.JOB_MONTH_NO to "No, keep {0}",
    TextKey.JOB_Q_EXPECTED to "What's the expected salary? (optional — you can skip it)",
    TextKey.JOB_Q_FREQUENCY to "When are you paid for this job? Monthly or weekly?",
    TextKey.JOB_Q_WEEKDAY to "Which day of the week?",
    TextKey.JOB_Q_MONTH_DAY to "Which day of the month?",
    TextKey.JOB_FREQ_MONTHLY to "Monthly",
    TextKey.JOB_FREQ_WEEKLY to "Weekly",
    TextKey.JOB_Q_STEP to "{0} of {1}",
    TextKey.JOB_SKIP to "Skip",
    TextKey.JOB_DONE_PAYDAY to "Paid on day {0}",
    TextKey.JOB_DONE_WEEKDAY to "Paid every {0}",
    TextKey.JOB_DONE_EXPECTED to "Expected {0}",
    TextKey.JOB_DONE_LATER to "You can finish the rest from the source's details later.",
    TextKey.JOB_OTHER_DATE to "Another date",
    TextKey.JOB_DATE_BAD to "Write the date like 2026-10-07",
)
