package app.masroufy.core

/**
 * «العمليات» بالفصحى — الجزء التاني: «اربطها بـ» (شخص · مشروع أو حدث) · صفحة التاجر · التحويلات · «من هذا؟» · التحويل لنفسك بين البلدين.
 */
internal val MSA_OPERATIONS_LINK_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.LINK_PERSON_CARD to "شخص",
    UiKey.LINK_PERSON_SUB to "قسّمها على شخص: دين عليه أو هدية له",
    UiKey.LINK_PERSON_SUB_MORE to "يمكنك تقسيمها على شخص آخر",
    UiKey.LINK_PERSON_LOCKED to "تحويل بين بلديك — لا يُربط بشخص.",
    UiKey.LINK_PERSON_TRANSFER_SOON to "ربط الحوالة بشخص (سلفة أو دعم أو سداد) غير متاح بعد.",
    UiKey.LINK_PERSON_OPEN to "اربط",
    UiKey.LINK_PERSON_ANOTHER to "شخص آخر",
    UiKey.LINK_PERSON_LINE to "{0} — {1}",
    UiKey.LINK_PERSON_KIND_RECEIVABLE to "دين عليه",
    UiKey.LINK_PERSON_KIND_GIFT to "هدية له",
    UiKey.LINK_PERSON_TITLE to "اربطها بشخص",
    UiKey.LINK_PERSON_WHO to "مَن؟",
    UiKey.LINK_PERSON_SEARCH to "ابحث أو اكتب اسمًا جديدًا",
    UiKey.LINK_PERSON_ADD_NEW to "+ أضف «{0}»",
    UiKey.LINK_PERSON_WILL_ADD to "سيُضاف إلى الأشخاص بهذا الاسم.",
    UiKey.LINK_PERSON_OWES_YOU to "لك عنده {0}",
    UiKey.LINK_PERSON_YOU_OWE to "عليك له {0}",
    UiKey.LINK_PERSON_CUSTODY to "أمانة له عندك {0}",
    UiKey.LINK_PERSON_NO_BALANCE to "لا رصيد بينكما",
    UiKey.LINK_PERSON_KIND to "نوع الربط",
    UiKey.LINK_PERSON_NOTE_RECEIVABLE to "دفعتها عنه، وتُسجَّل دينًا عليه في «لك».",
    UiKey.LINK_PERSON_NOTE_GIFT to "هدية لا تُسترد — تبقى من مصروفك وتظهر في سجله.",
    UiKey.LINK_PERSON_NOTE_NONE to "اختر النوع ليظهر أثره بالأسفل.",
    UiKey.LINK_PERSON_AMOUNT to "نصيبه من العملية",
    UiKey.LINK_PERSON_EFFECT_TITLE to "الأثر على أرقامك",
    UiKey.LINK_PERSON_EFFECT_SPEND to "مصروفك من العملية",
    UiKey.LINK_PERSON_EFFECT_OWES to "لك عند {0}",
    UiKey.LINK_PERSON_EFFECT_DEBT_ON to "دين على {0}",
    UiKey.LINK_PERSON_SAME to "بلا تغيير",
    UiKey.LINK_PERSON_NOTHING to "لا شيء",
    UiKey.LINK_PERSON_PICK_BOTH to "اختر الشخص والنوع",
    UiKey.LINK_PERSON_PICK_KIND to "اختر النوع",
    UiKey.LINK_PERSON_WRITE_AMOUNT to "اكتب المبلغ",
    UiKey.LINK_PERSON_EFFECT_HERE to "ليظهر الأثر هنا",
    UiKey.LINK_PERSON_ERR_PERSON to "اختر الشخص أو اكتب اسمًا جديدًا.",
    UiKey.LINK_PERSON_ERR_KIND to "اختر: دين عليه أم هدية له.",
    UiKey.LINK_PERSON_ERR_AMOUNT to "اكتب مبلغًا أكبر من صفر.",
    UiKey.LINK_PERSON_SAVE to "احفظ الربط",
    UiKey.LINK_PROJECT_EVENT_CARD to "مشروع أو حدث",
    UiKey.LINK_PROJECT_EVENT_SUB_NONE to "لم تُربط بعد",
    UiKey.LINK_PROJECT_EVENT_SUB_TAGS to "علامات على العملية — لا تغيّر أي مجموع.",
    UiKey.LINK_PROJECT_EVENT_LOCKED to "تحويل بين بلديك — لا يُربط بمشروع أو حدث.",
    UiKey.LINK_PROJECT_EVENT_PROJECT_TAG to "مشروع:",
    UiKey.LINK_PROJECT_EVENT_EVENT_TAG to "حدث:",
    UiKey.LINK_PROJECT_EVENT_NAME_SHARE to "{0}، {1}",
    UiKey.LINK_PROJECT_EVENT_PERCENT to "{0}%",
    UiKey.LINK_PROJECT_EVENT_PERCENT_SIGN to "%",
    UiKey.LINK_PROJECT_EVENT_TITLE to "اربطها بمشروع أو حدث",
    UiKey.LINK_PROJECT_EVENT_PROJECTS to "المشاريع",
    UiKey.LINK_PROJECT_EVENT_PROJECTS_HINT to "يمكن أكثر من مشروع، وكل مشروع يحسبها مرة واحدة.",
    UiKey.LINK_PROJECT_EVENT_NO_PROJECTS to "لا مشاريع بعد — أضفها من «المشاريع».",
    UiKey.LINK_PROJECT_EVENT_EVENT to "الحدث",
    UiKey.LINK_PROJECT_EVENT_EVENT_HINT to "حدث واحد فقط للعملية، وبنسبة من مبلغها.",
    UiKey.LINK_PROJECT_EVENT_EVENT_HINT_IN to "الوارد يُربط بالحدث نقطةً — من صفحة الحدث «سجّل النقوط».",
    UiKey.LINK_PROJECT_EVENT_NONE to "بلا حدث",
    UiKey.LINK_PROJECT_EVENT_HOSTED to "حدث {0}",
    UiKey.LINK_PROJECT_EVENT_MINE to "حدثك",
    UiKey.LINK_PROJECT_EVENT_WHEN to "{0}، {1}",
    UiKey.LINK_PROJECT_EVENT_NOW_LINKED to "، ومربوطة به حاليًا",
    UiKey.LINK_PROJECT_EVENT_NOT_ON_ANY to "العملية ليست على أي حدث.",
    UiKey.LINK_PROJECT_EVENT_CONFLICT_TITLE to "مربوطة بـ«{0}» مسبقًا",
    UiKey.LINK_PROJECT_EVENT_CONFLICT_BODY to "تُربط العملية بحدث واحد فقط. فكّها أولًا، ثم تُربط بـ«{0}».",
    UiKey.LINK_PROJECT_EVENT_UNLINK to "فك الربط من «{0}»",
    UiKey.LINK_PROJECT_EVENT_SHARE to "نصيب الحدث من العملية",
    UiKey.LINK_PROJECT_EVENT_RANGE to "النسبة من {0} إلى {1}",
    UiKey.LINK_PROJECT_EVENT_ON to "على «{0}»",
    UiKey.LINK_PROJECT_EVENT_OUTSIDE to "الباقي خارج الحدث",
    UiKey.LINK_PROJECT_EVENT_NOTE to "الربط علامة على العملية — لا يغيّر مصروف الشهر ولا تصنيفها، وتُحفظ النسبة مع الربط.",
    UiKey.LINK_PROJECT_EVENT_SAVE to "احفظ",
    UiKey.LINK_PROJECT_EVENT_ERR_PENDING to "فكّ الربط القديم أولًا، أو اختر الحدث نفسه.",
    UiKey.LINK_PROJECT_EVENT_ERR_SHARE to "نسبة الحدث من العملية يجب أن تكون من 1 إلى 100.",
    UiKey.MERCHANT_PROFILE_TITLE to "صفحة التاجر",
    UiKey.MERCHANT_PROFILE_IN_PERIOD to "{0} في {1}",
    UiKey.MERCHANT_PROFILE_RENAME to "تغيير الاسم",
    UiKey.MERCHANT_PROFILE_SPENT_PERIOD to "صرفت لديه في {0}",
    UiKey.MERCHANT_PROFILE_SPENT_ALL to "منذ أول عملية",
    UiKey.MERCHANT_PROFILE_CATEGORY_IN to "تصنيفه في {0}",
    UiKey.MERCHANT_PROFILE_HINT_SAVED to "يُطبَّق على عملياته القادمة قبل أي قاعدة، وفي {0} فقط.",
    UiKey.MERCHANT_PROFILE_HINT_SUGGESTED to "من قاعدة عامة — اختر تصنيفه مرة ويُحفظ له دائمًا.",
    UiKey.MERCHANT_PROFILE_HINT_OTHER_COUNTRY to "التاجر مصنّف هكذا في بلدك الآخر — اقتراح، أكّده إن كان صحيحًا.",
    UiKey.MERCHANT_PROFILE_NOT_SAVED to "لم يُحفظ هذا المتجر بعد، فلا يُعدَّل تصنيفه ولا اسمه من هنا.",
    UiKey.MERCHANT_PROFILE_CATEGORY_BODY to "يُحفظ اختيارك لهذا التاجر دائمًا.",
    UiKey.MERCHANT_PROFILE_ALIASES to "أسماء بديلة في الكشف",
    UiKey.MERCHANT_PROFILE_ALIAS_HINT to "كما يظهر في رسالة البنك",
    UiKey.MERCHANT_PROFILE_ALIAS_NOTE to "حين يظهر أي اسم منها في رسالة أو كشف، تُنسب العملية إلى هذا التاجر.",
    UiKey.MERCHANT_PROFILE_ALIAS_ADDED to "أُضيف — تُنسب أي عملية بهذا الاسم إلى هذا التاجر",
    UiKey.MERCHANT_PROFILE_ALIAS_EXISTS to "هذا الاسم موجود سابقًا",
    UiKey.MERCHANT_PROFILE_LIST to "عملياته",
    UiKey.MERCHANT_PROFILE_NONE_PERIOD to "لا عمليات له في {0}.",
    UiKey.MERCHANT_PROFILE_RENAME_TITLE to "تغيير اسم التاجر",
    UiKey.MERCHANT_PROFILE_RENAME_BODY to "هذا الاسم يظهر لك فقط، وتبقى المطابقة مع الكشف بالاسم الأصلي.",
    UiKey.MERCHANT_PROFILE_RENAMED to "حُفظ الاسم",
)
