package app.masroufy.core

/**
 * نصوص شاشات منطقة «المزيد» (`ui/screens/more/`) — **الملف ده بتاع المنطقة بس** (المناطق بتتبني بالتوازي، ARCHITECTURE §31.31).
 * المفاتيح في `TextKeys.kt` **تحت سطر «منطقة المزيد»** بس. الفصحى للسعودية والافتراضي · المصري لمصر (OVERRIDES §66) · الإنجليزي
 * (كتابة Claude — مستني مراجعة المالك §40). النص من النموذج التفاعلي بالحرف (الفصحى من `space = السعودية` والمصري من `مصر`).
 * **ممنوع «·» جنب رقم عربي** ⇒ «،». الملفات التانية بتتضم هنا بـ`+`: ملفك (`TextsMoreAccount`) · الإشعارات والقفل واللغة (`TextsMoreSettings`) ·
 * البلدان والمحافظ (`TextsMoreSpaces`) · تفاصيل المحفظة (`TextsMoreWallet`) · محفظة جديدة (`TextsMoreWalletAdd`) · مصادر الدخل (`TextsMoreIncome`) ·
 * تعديل المصدر وتغيير الشغل (`TextsMoreJob`) · النسخة الاحتياطية والاسترجاع (`TextsMoreBackup`).
 */
internal val MSA_AREA_MORE_TEXTS: Map<UiKey, String> get() = MSA_MORE_MENU_TEXTS + MSA_MORE_ACCOUNT_TEXTS + MSA_MORE_SETTINGS_TEXTS + MSA_MORE_SPACES_TEXTS +
    MSA_MORE_WALLET_TEXTS + MSA_MORE_WALLET_ADD_TEXTS + MSA_MORE_INCOME_TEXTS + MSA_MORE_JOB_TEXTS + MSA_MORE_BACKUP_TEXTS

internal val EGYPTIAN_AREA_MORE_TEXTS: Map<UiKey, String> get() = EGYPTIAN_MORE_MENU_TEXTS + EGYPTIAN_MORE_ACCOUNT_TEXTS + EGYPTIAN_MORE_SETTINGS_TEXTS +
    EGYPTIAN_MORE_SPACES_TEXTS + EGYPTIAN_MORE_WALLET_TEXTS + EGYPTIAN_MORE_WALLET_ADD_TEXTS + EGYPTIAN_MORE_INCOME_TEXTS + EGYPTIAN_MORE_JOB_TEXTS +
    EGYPTIAN_MORE_BACKUP_TEXTS

internal val ENGLISH_AREA_MORE_TEXTS: Map<UiKey, String> get() = ENGLISH_MORE_MENU_TEXTS + ENGLISH_MORE_ACCOUNT_TEXTS + ENGLISH_MORE_SETTINGS_TEXTS +
    ENGLISH_MORE_SPACES_TEXTS + ENGLISH_MORE_WALLET_TEXTS + ENGLISH_MORE_WALLET_ADD_TEXTS + ENGLISH_MORE_INCOME_TEXTS + ENGLISH_MORE_JOB_TEXTS +
    ENGLISH_MORE_BACKUP_TEXTS

/** «المزيد» نفسها + الكلمات المشتركة بين شاشات المنطقة + «اختر شكلك» + «تغيير كلمة السر» في «ملفك». */
private val MSA_MORE_MENU_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.MORE_TITLE to "المزيد",
    UiKey.MORE_SPACE_LINE to "المساحة الحالية: {0} · {1}",
    UiKey.MORE_GROUP_ACCOUNT to "حسابك",
    UiKey.MORE_GROUP_DATA to "بياناتك",
    UiKey.MORE_GROUP_SETTINGS to "الإعدادات",
    UiKey.MORE_ITEM_PROFILE to "ملفك",
    UiKey.MORE_ITEM_INCOME to "مصادر الدخل",
    UiKey.MORE_INCOME_HINT to "الراتب يوم {0}",
    UiKey.MORE_ITEM_SPACES to "البلدان",
    UiKey.MORE_ITEM_WALLETS to "المحافظ",
    UiKey.MORE_ITEM_CATEGORIES to "التصنيفات",
    UiKey.MORE_ITEM_RULES to "القواعد والتجار",
    UiKey.MORE_HINT_RULES to "ما يتذكره التطبيق",
    UiKey.MORE_ITEM_PROJECTS to "المشاريع",
    UiKey.MORE_HINT_PROJECTS to "كم كلّفني؟ · كم كسبت؟",
    UiKey.MORE_ITEM_BANK_SMS to "رسائل البنك",
    UiKey.MORE_ITEM_STATEMENT to "كشف الحساب",
    UiKey.MORE_HINT_STATEMENT to "استيراد ملف من البنك",
    UiKey.MORE_ITEM_BATCHES to "دفعات الاستيراد",
    UiKey.MORE_HINT_BATCHES to "ما سُجّل من كل ملف، وإرجاعه",
    UiKey.MORE_ITEM_BACKUP to "النسخة الاحتياطية",
    UiKey.MORE_ITEM_EXPORT to "التصدير",
    UiKey.MORE_HINT_EXPORT to "ملف جدول من تاريخ إلى تاريخ",
    UiKey.MORE_ITEM_NOTIFICATIONS to "الإشعارات",
    UiKey.MORE_ITEM_LOCK to "القفل",
    UiKey.MORE_ITEM_LANGUAGE to "اللغة",
    UiKey.MORE_ITEM_ISLAMIC to "المحتوى الإسلامي",
    UiKey.MORE_YES to "نعم",
    UiKey.MORE_NO to "لا",
    UiKey.MORE_SAVE to "حفظ",
    UiKey.MORE_CANCEL to "إلغاء",
    UiKey.MORE_DONE to "تم",
    UiKey.MORE_RETRY to "أعد المحاولة",
    UiKey.MORE_TODAY to "اليوم",
    UiKey.MORE_SAVE_FAILED to "تعذّر الحفظ. حاول مرة أخرى.",
    UiKey.MORE_NOT_YET to "غير متاح بعد",
    UiKey.MORE_DATE_FULL to "{0} {1}",
    UiKey.LOOK_OPEN to "غيّر شكلك",
    UiKey.LOOK_TITLE to "اختر شكلك",
    UiKey.LOOK_N to "الشكل {0}",
    UiKey.LOOK_NOTE to "أشكال مؤقتة — الكاركتر النهائي قيد التصميم.",
    UiKey.LOOK_NOT_YET to "حفظ الشكل غير متاح بعد: ملفك لا يحفظ الشكل حتى الآن.",
    UiKey.LOOK_SAVED to "تغيّر شكلك",
    UiKey.RESET_CHANGE_TRIGGER to "تغيير كلمة السر",
    UiKey.RESET_CHANGE_HINT to "نرسل رابط التغيير إلى بريدك",
    UiKey.RESET_CHANGE_TITLE to "تغيير كلمة السر",
    UiKey.RESET_CHANGE_BODY to "سنرسل إلى بريدك رابطًا تغيّر منه كلمة المرور.",
    UiKey.RESET_CHANGE_SEND to "أرسل الرابط",
)

private val EGYPTIAN_MORE_MENU_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.MORE_TITLE to "المزيد",
    UiKey.MORE_SPACE_LINE to "المساحة الحالية: {0} · {1}",
    UiKey.MORE_GROUP_ACCOUNT to "حسابك",
    UiKey.MORE_GROUP_DATA to "بياناتك",
    UiKey.MORE_GROUP_SETTINGS to "الإعدادات",
    UiKey.MORE_ITEM_PROFILE to "ملفك",
    UiKey.MORE_ITEM_INCOME to "مصادر الدخل",
    UiKey.MORE_INCOME_HINT to "المرتب يوم {0}",
    UiKey.MORE_ITEM_SPACES to "البلدان",
    UiKey.MORE_ITEM_WALLETS to "المحافظ",
    UiKey.MORE_ITEM_CATEGORIES to "التصنيفات",
    UiKey.MORE_ITEM_RULES to "القواعد والتجار",
    UiKey.MORE_HINT_RULES to "اللي البرنامج فاكره",
    UiKey.MORE_ITEM_PROJECTS to "المشاريع",
    UiKey.MORE_HINT_PROJECTS to "كلّفني كام؟ · كسبت كام؟",
    UiKey.MORE_ITEM_BANK_SMS to "رسايل البنك",
    UiKey.MORE_ITEM_STATEMENT to "كشف الحساب",
    UiKey.MORE_HINT_STATEMENT to "استيراد ملف من البنك",
    UiKey.MORE_ITEM_BATCHES to "دفعات الاستيراد",
    UiKey.MORE_HINT_BATCHES to "اللي اتسجّل من كل ملف، وترجّعه لو حبيت",
    UiKey.MORE_ITEM_BACKUP to "النسخة الاحتياطية",
    UiKey.MORE_ITEM_EXPORT to "التصدير",
    UiKey.MORE_HINT_EXPORT to "ملف جدول من تاريخ لتاريخ",
    UiKey.MORE_ITEM_NOTIFICATIONS to "الإشعارات",
    UiKey.MORE_ITEM_LOCK to "القفل",
    UiKey.MORE_ITEM_LANGUAGE to "اللغة",
    UiKey.MORE_ITEM_ISLAMIC to "المحتوى الإسلامي",
    UiKey.MORE_YES to "أيوه",
    UiKey.MORE_NO to "لأ",
    UiKey.MORE_SAVE to "احفظ",
    UiKey.MORE_CANCEL to "إلغاء",
    UiKey.MORE_DONE to "تمام",
    UiKey.MORE_RETRY to "جرّب تاني",
    UiKey.MORE_TODAY to "النهارده",
    UiKey.MORE_SAVE_FAILED to "ما اتحفظش. جرّب تاني.",
    UiKey.MORE_NOT_YET to "لسه مش متاح",
    UiKey.MORE_DATE_FULL to "{0} {1}",
    UiKey.LOOK_OPEN to "غيّر شكلك",
    UiKey.LOOK_TITLE to "اختر شكلك",
    UiKey.LOOK_N to "الشكل {0}",
    UiKey.LOOK_NOTE to "أشكال مؤقتة — الكاركتر النهائي لسه بيتصمم.",
    UiKey.LOOK_NOT_YET to "حفظ الشكل لسه مش متاح: ملفك لسه ما بيحفظش الشكل.",
    UiKey.LOOK_SAVED to "اتغيّر شكلك",
    UiKey.RESET_CHANGE_TRIGGER to "تغيير كلمة السر",
    UiKey.RESET_CHANGE_HINT to "هنبعت لينك التغيير على إيميلك",
    UiKey.RESET_CHANGE_TITLE to "تغيير كلمة السر",
    UiKey.RESET_CHANGE_BODY to "هنبعت على إيميلك لينك تغيّر منه كلمة السر.",
    UiKey.RESET_CHANGE_SEND to "ابعت اللينك",
)

private val ENGLISH_MORE_MENU_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.MORE_TITLE to "More",
    UiKey.MORE_SPACE_LINE to "Current space: {0} · {1}",
    UiKey.MORE_GROUP_ACCOUNT to "Your account",
    UiKey.MORE_GROUP_DATA to "Your data",
    UiKey.MORE_GROUP_SETTINGS to "Settings",
    UiKey.MORE_ITEM_PROFILE to "Your profile",
    UiKey.MORE_ITEM_INCOME to "Income sources",
    UiKey.MORE_INCOME_HINT to "Salary on day {0}",
    UiKey.MORE_ITEM_SPACES to "Countries",
    UiKey.MORE_ITEM_WALLETS to "Wallets",
    UiKey.MORE_ITEM_CATEGORIES to "Categories",
    UiKey.MORE_ITEM_RULES to "Rules and merchants",
    UiKey.MORE_HINT_RULES to "What the app remembers",
    UiKey.MORE_ITEM_PROJECTS to "Projects",
    UiKey.MORE_HINT_PROJECTS to "What did it cost? What did I earn?",
    UiKey.MORE_ITEM_BANK_SMS to "Bank messages",
    UiKey.MORE_ITEM_STATEMENT to "Bank statement",
    UiKey.MORE_HINT_STATEMENT to "Import a file from the bank",
    UiKey.MORE_ITEM_BATCHES to "Import batches",
    UiKey.MORE_HINT_BATCHES to "What each file recorded, and undoing it",
    UiKey.MORE_ITEM_BACKUP to "Backup",
    UiKey.MORE_ITEM_EXPORT to "Export",
    UiKey.MORE_HINT_EXPORT to "A spreadsheet file from one date to another",
    UiKey.MORE_ITEM_NOTIFICATIONS to "Notifications",
    UiKey.MORE_ITEM_LOCK to "Lock",
    UiKey.MORE_ITEM_LANGUAGE to "Language",
    UiKey.MORE_ITEM_ISLAMIC to "Islamic content",
    UiKey.MORE_YES to "Yes",
    UiKey.MORE_NO to "No",
    UiKey.MORE_SAVE to "Save",
    UiKey.MORE_CANCEL to "Cancel",
    UiKey.MORE_DONE to "Done",
    UiKey.MORE_RETRY to "Try again",
    UiKey.MORE_TODAY to "Today",
    UiKey.MORE_SAVE_FAILED to "Couldn't save. Try again.",
    UiKey.MORE_NOT_YET to "Not available yet",
    UiKey.MORE_DATE_FULL to "{0} {1}",
    UiKey.LOOK_OPEN to "Change your look",
    UiKey.LOOK_TITLE to "Choose your look",
    UiKey.LOOK_N to "Look {0}",
    UiKey.LOOK_NOTE to "Temporary looks — the final character is still being designed.",
    UiKey.LOOK_NOT_YET to "Saving a look isn't available yet: your profile doesn't store it so far.",
    UiKey.LOOK_SAVED to "Your look changed",
    UiKey.RESET_CHANGE_TRIGGER to "Change password",
    UiKey.RESET_CHANGE_HINT to "We email you a link to change it",
    UiKey.RESET_CHANGE_TITLE to "Change password",
    UiKey.RESET_CHANGE_BODY to "We'll email you a link to change your password.",
    UiKey.RESET_CHANGE_SEND to "Send the link",
)
