package app.masroufy.core

/**
 * نصوص الزكاة (OVERRIDES §62) باللغتين. ملف لوحده عشان حد الـ300 سطر؛ بيتدمج في `ARABIC_TEXTS` و`ENGLISH_TEXTS`.
 * **الصياغة:** «حسب …» + «إرشادي، مش فتوى» — التطبيق ما بيقولش «لازم» ولا «حرام» (§46)، وما بيقولش حاجة المرجع ما قالهاش.
 * الإنجليزي كتابة Claude ومستني مراجعة المالك زي باقي الجدول (§40).
 */
internal val ARABIC_ZAKAT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSET_KIND_SILVER to "فضة",
    TextKey.BACKUP_GROUP_ZAKAT_FACTS to "وقائع الزكاة",
    TextKey.BACKUP_GROUP_ZAKAT_YEARS to "سنين الزكاة",
    TextKey.BACKUP_GROUP_ZAKAT_PAYMENTS to "دفعات الزكاة",
    TextKey.ZAKAT_AUTH_ZATCA to "هيئة الزكاة والضريبة والجمارك",
    TextKey.ZAKAT_AUTH_IFTAA to "دار الإفتاء المصرية",
    TextKey.ZAKAT_DOC_ZATCA_GUIDE to "دليل زكاة الأفراد (على فتاوى اللجنة الدائمة)",
    TextKey.ZAKAT_DOC_FATWA to "فتوى رقم {0}",
    TextKey.ZAKAT_DOC_IFTAA_GENERAL to "فتاوى دار الإفتاء",
    TextKey.ZAKAT_GUIDANCE to "إرشادي، مش فتوى.",
    TextKey.ZAKAT_RULE_RATE to "النسبة 2.5% (ربع العشر).",
    TextKey.ZAKAT_RULE_CASH to "الكاش وحسابات البنك بالكامل برصيدها يوم الزكاة.",
    TextKey.ZAKAT_RULE_NISAB_SA to "النصاب الأقل من نصاب الدهب (85 جم صافي) والفضة (595 جم صافي).",
    TextKey.ZAKAT_RULE_NISAB_EG to "النصاب 85 جم دهب عيار 21.",
    TextKey.ZAKAT_RULE_HAWL_FIXED to "يوم ثابت كل سنة هجرية.",
    TextKey.ZAKAT_RULE_DIP_RESTART to "لو الفلوس نزلت تحت النصاب في نص السنة، الحول بيبدأ من جديد.",
    TextKey.ZAKAT_RULE_DIP_START_END to "العبرة بالنصاب أول السنة وآخرها — النزول تحته في نص السنة ما بيقطعش الحول.",
    TextKey.ZAKAT_RULE_RECEIVABLE_ON_COLLECTION to "الدين ليك ما بيدخلش الحساب السنوي — بيتزكّى لما يتحصّل، لسنة واحدة.",
    TextKey.ZAKAT_RULE_RECEIVABLE_COLLECTED to "الدين اللي اتحصّل: 2.5% مرة واحدة على المبلغ اللي اتحصّل.",
    TextKey.ZAKAT_LINE_COLLECTED_RECEIVABLES to "ديون اتحصّلت السنة دي",
    TextKey.ZAKAT_DOC_SECTION_PAGES to "{0} — البند {1}، ص {2}",
    TextKey.ZAKAT_DOC_PAGES to "{0} — ص {1}",
    TextKey.ZAKAT_RULE_WORN_EXEMPT to "الدهب والفضة اللي للبس معفيين.",
    TextKey.ZAKAT_RULE_SAVED_COUNTED to "الدهب والفضة اللي للادخار عليهم زكاة بقيمتهم.",
    TextKey.ZAKAT_RULE_DEBTS_NOT_DEDUCTED to "الديون اللي عليك ما بتتخصمش.",
    TextKey.ZAKAT_RULE_TRADING_FULL to "الأسهم والصناديق للمضاربة عليها زكاة بقيمتها السوقية كلها.",
    TextKey.ZAKAT_RULE_LONG_TERM_COMPANY_PAYS to "الأسهم طويلة الأجل: الشركة السعودية بتزكّي.",
    TextKey.ZAKAT_RULE_LONG_TERM_DIVIDENDS to "الأسهم طويلة الأجل: الزكاة على الأرباح بس.",
    TextKey.ZAKAT_RULE_RECEIVABLE_STRONG to "الدين ليك اللي هيرجع عليه زكاة كل سنة.",
    TextKey.ZAKAT_RULE_RECEIVABLE_DOUBTFUL to "الدين ليك المشكوك فيه بيتزكّى لما يتحصّل.",
    TextKey.ZAKAT_RULE_ROSCA_RECEIVABLE to "الجمعية: اللي دفعته وما قبضتوش دين ليك هيرجع.",
    TextKey.ZAKAT_RULE_NO_RULING to "المرجع الرسمي ما حددش — راجع جهة الفتوى.",
    TextKey.ZAKAT_LINE_CASH to "الكاش وحسابات البنك",
    TextKey.ZAKAT_LINE_GOLD to "دهب ادخار",
    TextKey.ZAKAT_LINE_SILVER to "فضة ادخار",
    TextKey.ZAKAT_LINE_STOCKS to "أسهم",
    TextKey.ZAKAT_LINE_FUNDS to "صناديق",
    TextKey.ZAKAT_LINE_RECEIVABLES to "ديون ليك",
    TextKey.ZAKAT_LINE_ROSCA to "الجمعيات",
    TextKey.ZAKAT_EXTRA_CHARITY to "صدقة زيادة",
    TextKey.ZAKAT_NOT_COVERED to "النوع ده مش داخل في حساب الزكاة في التطبيق — راجعه بنفسك.",
    TextKey.ZAKAT_COUNTRY_UNSUPPORTED to "حساب الزكاة لسه مش متاح لبلد الحساب ده.",
    TextKey.ZAKAT_YEAR_NOT_FOUND to "سنة الزكاة دي مش موجودة.",
    TextKey.ZAKAT_YEAR_NOT_CLOSED to "ثبّت حساب السنة دي الأول، وبعدين سجّل الدفع.",
    TextKey.ZAKAT_YEAR_ALREADY_CLOSED to "حساب السنة دي متثبّت قبل كده.",
    TextKey.ZAKAT_YEAR_HAS_PAYMENTS to "السنة دي عليها دفعات — فكها الأول.",
    TextKey.ZAKAT_CANNOT_CLOSE to "الحساب لسه ناقص — كمّل الوقائع أو الأسعار الناقصة الأول.",
    TextKey.ZAKAT_LINES_INVALID to "اختار سطر واحد على الأقل من سطور السنة دي.",
    TextKey.ZAKAT_NOTHING_DUE to "مفيش زكاة مطلوبة في السنة دي.",
    TextKey.ZAKAT_PAYMENT_NOT_FOUND to "الدفعة مش موجودة.",
    TextKey.ZAKAT_TXN_TWICE to "نفس العملية متكررة في نفس الدفعة.",
    TextKey.ZAKAT_FACT_WRONG_KIND to "السؤال ده مش لنوع الأصل ده.",
    TextKey.ZAKAT_KARAT_RANGE to "العيار لازم يكون من 1 لـ 24.",
    TextKey.ZAKAT_FINENESS_RANGE to "نقاوة الفضة لازم تكون من 1 لـ 1000 (في الألف).",
    TextKey.ZAKAT_ASSET_NOT_FOUND to "الأصل مش موجود.",
    TextKey.ZAKAT_RECEIVABLE_NOT_FOUND to "الدين ليك مش موجود.",
    TextKey.ZAKAT_DATE_INVALID to "التاريخ مش صحيح.",
    TextKey.ZAKAT_PAYMENT_NAME to "زكاة {0}",
)

internal val ENGLISH_ZAKAT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSET_KIND_SILVER to "Silver",
    TextKey.BACKUP_GROUP_ZAKAT_FACTS to "Zakat facts",
    TextKey.BACKUP_GROUP_ZAKAT_YEARS to "Zakat years",
    TextKey.BACKUP_GROUP_ZAKAT_PAYMENTS to "Zakat payments",
    TextKey.ZAKAT_AUTH_ZATCA to "Zakat, Tax and Customs Authority (ZATCA)",
    TextKey.ZAKAT_AUTH_IFTAA to "Dar al-Iftaa al-Misriyyah",
    TextKey.ZAKAT_DOC_ZATCA_GUIDE to "Individuals' Zakat Guide (based on the Permanent Committee's fatwas)",
    TextKey.ZAKAT_DOC_FATWA to "Fatwa no. {0}",
    TextKey.ZAKAT_DOC_IFTAA_GENERAL to "Dar al-Iftaa fatwas",
    TextKey.ZAKAT_GUIDANCE to "For guidance only, not a fatwa.",
    TextKey.ZAKAT_RULE_RATE to "The rate is 2.5% (one fortieth).",
    TextKey.ZAKAT_RULE_CASH to "Cash and bank accounts in full, at their balance on the zakat day.",
    TextKey.ZAKAT_RULE_NISAB_SA to "The nisab is the lower of gold (85 g pure) and silver (595 g pure).",
    TextKey.ZAKAT_RULE_NISAB_EG to "The nisab is 85 g of 21-karat gold.",
    TextKey.ZAKAT_RULE_HAWL_FIXED to "A fixed day every Hijri year.",
    TextKey.ZAKAT_RULE_DIP_RESTART to "If wealth drops below the nisab during the year, the year starts again.",
    TextKey.ZAKAT_RULE_DIP_START_END to "What matters is the nisab at the start and the end of the year — dropping below it mid-year does not break the year.",
    TextKey.ZAKAT_RULE_RECEIVABLE_ON_COLLECTION to "Money owed to you is not part of the yearly calculation — it is zakatable when collected, for one year.",
    TextKey.ZAKAT_RULE_RECEIVABLE_COLLECTED to "Collected money owed to you: 2.5% once on the amount collected.",
    TextKey.ZAKAT_LINE_COLLECTED_RECEIVABLES to "Money owed to you collected this year",
    TextKey.ZAKAT_DOC_SECTION_PAGES to "{0} — section {1}, p. {2}",
    TextKey.ZAKAT_DOC_PAGES to "{0} — p. {1}",
    TextKey.ZAKAT_RULE_WORN_EXEMPT to "Gold and silver worn as jewelry are exempt.",
    TextKey.ZAKAT_RULE_SAVED_COUNTED to "Gold and silver kept as savings are zakatable at their value.",
    TextKey.ZAKAT_RULE_DEBTS_NOT_DEDUCTED to "Debts you owe are not deducted.",
    TextKey.ZAKAT_RULE_TRADING_FULL to "Shares and funds held for trading are zakatable at their full market value.",
    TextKey.ZAKAT_RULE_LONG_TERM_COMPANY_PAYS to "Long-term shares: the Saudi company pays the zakat.",
    TextKey.ZAKAT_RULE_LONG_TERM_DIVIDENDS to "Long-term shares: zakat is on the dividends only.",
    TextKey.ZAKAT_RULE_RECEIVABLE_STRONG to "Money owed to you that will be repaid is zakatable every year.",
    TextKey.ZAKAT_RULE_RECEIVABLE_DOUBTFUL to "Doubtful money owed to you is zakatable when collected.",
    TextKey.ZAKAT_RULE_ROSCA_RECEIVABLE to "Savings circle: what you paid and have not received back is money owed to you.",
    TextKey.ZAKAT_RULE_NO_RULING to "The official reference has not ruled on this — ask the fatwa authority.",
    TextKey.ZAKAT_LINE_CASH to "Cash and bank accounts",
    TextKey.ZAKAT_LINE_GOLD to "Gold savings",
    TextKey.ZAKAT_LINE_SILVER to "Silver savings",
    TextKey.ZAKAT_LINE_STOCKS to "Shares",
    TextKey.ZAKAT_LINE_FUNDS to "Funds",
    TextKey.ZAKAT_LINE_RECEIVABLES to "Money owed to you",
    TextKey.ZAKAT_LINE_ROSCA to "Savings circles",
    TextKey.ZAKAT_EXTRA_CHARITY to "Extra charity",
    TextKey.ZAKAT_NOT_COVERED to "This kind of asset is not part of the app's zakat calculation — review it yourself.",
    TextKey.ZAKAT_COUNTRY_UNSUPPORTED to "Zakat is not available yet for this account's country.",
    TextKey.ZAKAT_YEAR_NOT_FOUND to "This zakat year does not exist.",
    TextKey.ZAKAT_YEAR_NOT_CLOSED to "Lock this year's calculation first, then record the payment.",
    TextKey.ZAKAT_YEAR_ALREADY_CLOSED to "This year's calculation is already locked.",
    TextKey.ZAKAT_YEAR_HAS_PAYMENTS to "This year has payments — unlink them first.",
    TextKey.ZAKAT_CANNOT_CLOSE to "The calculation is still incomplete — fill in the missing facts or prices first.",
    TextKey.ZAKAT_LINES_INVALID to "Pick at least one of this year's lines.",
    TextKey.ZAKAT_NOTHING_DUE to "No zakat is due this year.",
    TextKey.ZAKAT_PAYMENT_NOT_FOUND to "The payment does not exist.",
    TextKey.ZAKAT_TXN_TWICE to "The same transaction appears twice in this payment.",
    TextKey.ZAKAT_FACT_WRONG_KIND to "This question does not apply to this kind of asset.",
    TextKey.ZAKAT_KARAT_RANGE to "The karat must be from 1 to 24.",
    TextKey.ZAKAT_FINENESS_RANGE to "Silver fineness must be from 1 to 1000 (per thousand).",
    TextKey.ZAKAT_ASSET_NOT_FOUND to "The asset does not exist.",
    TextKey.ZAKAT_RECEIVABLE_NOT_FOUND to "The money owed to you does not exist.",
    TextKey.ZAKAT_DATE_INVALID to "The date is not valid.",
    TextKey.ZAKAT_PAYMENT_NAME to "Zakat {0}",
)
