package app.masroufy.core

/**
 * نصوص الفلوس والكميات ورسايل البنك والنسخة الاحتياطية والألوان بالإنجليزي — كتابة Claude ومراجعة المالك.
 * (الجدول اتقسم لملفين عشان حد الـ300 سطر — CLAUDE.md #7.)
 */
internal val ENGLISH_DATA_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.COLOR_RED to "Red",
    TextKey.COLOR_ORANGE to "Orange",
    TextKey.COLOR_AMBER to "Amber",
    TextKey.COLOR_OLIVE to "Olive",
    TextKey.COLOR_LIME to "Lime",
    TextKey.COLOR_GREEN to "Green",
    TextKey.COLOR_MINT to "Mint",
    TextKey.COLOR_TEAL to "Teal",
    TextKey.COLOR_CYAN to "Cyan",
    TextKey.COLOR_BLUE to "Blue",
    TextKey.COLOR_INDIGO to "Indigo",
    TextKey.COLOR_PURPLE to "Purple",
    TextKey.COLOR_LILAC to "Lilac",
    TextKey.COLOR_MAGENTA to "Magenta",
    TextKey.COLOR_FUCHSIA to "Fuchsia",
    TextKey.COLOR_ROSE to "Rose",
    TextKey.COLOR_SLATE to "Slate",
    TextKey.COLOR_GRAY to "Gray",

    TextKey.BACKUP_GROUP_WALLETS to "Wallets",
    TextKey.BACKUP_GROUP_CATEGORIES to "Categories",
    TextKey.BACKUP_GROUP_MERCHANTS to "Stores",
    TextKey.BACKUP_GROUP_RULES to "Rules",
    TextKey.BACKUP_GROUP_PEOPLE to "People",
    TextKey.BACKUP_GROUP_ASSETS to "Assets",
    TextKey.BACKUP_GROUP_TAGS to "Tags",
    TextKey.BACKUP_GROUP_BUDGETS to "Budgets",
    TextKey.BACKUP_GROUP_RECURRING_ITEMS to "Subscriptions and bills",
    TextKey.BACKUP_GROUP_IMPORT_BATCHES to "Import batches",
    TextKey.BACKUP_GROUP_TRANSACTIONS to "Transactions",
    TextKey.BACKUP_GROUP_OBLIGATIONS to "Debts and custody",
    TextKey.BACKUP_GROUP_ALLOCATIONS to "Person splits",
    TextKey.BACKUP_GROUP_SETTLEMENTS to "Settlements",
    TextKey.BACKUP_GROUP_SOURCE_RECORDS to "Transaction sources",
    TextKey.BACKUP_GROUP_TRANSACTION_TAGS to "Tag links",
    TextKey.BACKUP_GROUP_CATEGORY_BUDGETS to "Category limits",
    TextKey.BACKUP_GROUP_ASSET_LOTS to "Asset purchases",
    TextKey.BACKUP_GROUP_ASSET_SALES to "Asset sales",
    TextKey.BACKUP_GROUP_ASSET_PRICES to "Asset prices",
    TextKey.BACKUP_GROUP_NOTIFICATION_RECEIPTS to "Notification read states",
    TextKey.BACKUP_GROUP_PROJECTS to "Projects",
    TextKey.BACKUP_GROUP_PROJECT_LINKS to "Project links",
    TextKey.BACKUP_GROUP_PROJECT_RULES to "Project rules",

    TextKey.AMOUNT_CONTEXT_DEFAULT to "amount",
    TextKey.MONEY_OUT_OF_RANGE_CONTEXT to "{0}: the amount is outside the safe range",
    TextKey.MONEY_EMPTY to "The amount is empty",
    TextKey.MONEY_BAD_FORMAT to "The amount format is not valid",
    TextKey.MONEY_TOO_MANY_DECIMALS to
        "The amount has more than {0} non-zero decimal places — it is not rounded silently",
    TextKey.MONEY_RESULT_OUT_OF_RANGE to "The result: the amount is outside the safe range",
    TextKey.MONEY_DIVIDE_BY_ZERO to "Division by zero",
    TextKey.MONEY_PARTS_POSITIVE to "The number of shares has to be a positive whole number",
    TextKey.AMOUNT_CONTEXT_TOTAL to "the total",
    TextKey.AMOUNT_CONTEXT_DIFFERENCE to "the difference",
    TextKey.AMOUNT_CONTEXT_SHARE to "the share",

    TextKey.QUANTITY_CONTEXT_DEFAULT to "quantity",
    TextKey.QUANTITY_OUT_OF_RANGE_CONTEXT to "{0}: the quantity is above the safe limit for the calculation",
    TextKey.QUANTITY_EMPTY to "Enter the quantity",
    TextKey.QUANTITY_TWO_POINTS to "The quantity has more than one decimal point",
    TextKey.QUANTITY_INVALID to "“{0}” is not a valid quantity",
    TextKey.QUANTITY_TOO_MANY_DECIMALS to
        "The quantity has more than {0} decimal places. The app will not round it behind your back — shorten it yourself.",
    TextKey.QUANTITY_NOT_A_NUMBER to "“{0}”: the value is not a valid number",
    TextKey.QUANTITY_OUT_OF_RANGE to "“{0}”: the quantity is above the safe limit for the calculation",
    TextKey.QUANTITY_CONTEXT_TOTAL to "the total quantity",
    TextKey.QUANTITY_DIVIDE_BY_ZERO to "Division by zero",
    TextKey.QUANTITY_RESULT_OUT_OF_RANGE to "The result is above the safe limit for the calculation",
    TextKey.QUANTITY_CONTEXT_PART to "the part quantity",
    TextKey.QUANTITY_CONTEXT_WHOLE to "the whole quantity",
    TextKey.QUANTITY_WHOLE_POSITIVE to "The whole quantity has to be greater than zero",
    TextKey.QUANTITY_PART_NEGATIVE to "The part quantity cannot be negative",
    TextKey.QUANTITY_PART_OVER_WHOLE to "The part quantity ({0}) is greater than the whole ({1})",

    TextKey.SMS_AMOUNT_INVALID to "The amount is not valid",
    TextKey.SMS_MULTIPLE_AMOUNTS to "There is more than one transaction amount in the message",
    TextKey.SMS_CURRENCY_UNCLEAR to "The currency of the amount is not clearly stated",
    TextKey.SMS_AMOUNT_UNCLEAR to "The transaction amount is not clear",
    TextKey.SMS_OFFER to "An offer or a future movement, not a completed transaction",
    TextKey.SMS_SENSITIVE to "A verification or password message; it was ignored",
    TextKey.SMS_DECLINED to "A declined or incomplete transaction",
    TextKey.SMS_DIRECTION_UNCLEAR to "The direction is not clear; we did not assume income or spending",
    TextKey.SMS_FOREIGN_CURRENCY to "This version only supports Saudi riyal messages",
    TextKey.SMS_DATE_UNCLEAR to "The transaction date is not clear; the arrival date of the message is not enough",

    TextKey.PDF_DEBIT_AND_CREDIT to "The transaction has a debit and a credit together — its direction is unclear",
    TextKey.PDF_ZERO_AMOUNT to "The transaction amount is zero in both the debit and the credit",

    TextKey.BACKUP_PROFILE_INVALID to "The account profile in the backup is not valid",
    TextKey.BACKUP_PROFILE_INVALID_FIELD to "The account profile in the backup is not valid: {0}",
    TextKey.BACKUP_DATA_INVALID to "The backup data is not valid",
    TextKey.BACKUP_GROUP_MISSING to "Missing group: {0}",
    TextKey.BACKUP_ROW_INVALID to "Invalid record: {0}",
    TextKey.BACKUP_ID_INVALID to "Invalid or duplicate id: {0}",
    TextKey.BACKUP_FIELD_MISSING to "Missing field: {0}.{1}",
    TextKey.BACKUP_IMPORT_UNFINISHED to
        "There is an unfinished import. Open the app and finish cleaning it up before backing up",
    TextKey.BACKUP_BUDGET_ID to "The budget id differs from the period",
    TextKey.BACKUP_RELATION_MISSING to "Missing relation: {0}.{1}",
    TextKey.BACKUP_TEXT_INVALID to "Invalid text: {0}.{1}",
    TextKey.BACKUP_NUMBER_INVALID to "Invalid amount or count: {0}",
    TextKey.BACKUP_NEGATIVE_AMOUNT to "Negative amount: {0}",
    TextKey.BACKUP_BOOLEAN_INVALID to "Invalid true or false value: {0}",
    TextKey.BACKUP_DATE_INVALID to "Invalid date: {0}",
    TextKey.BACKUP_CURRENCY_INVALID to "Invalid currency",
    TextKey.BACKUP_LAST_FOUR_ONLY to "Only the last four digits are allowed",
    TextKey.BACKUP_DIRECTION_INVALID to "Invalid transaction direction",
    TextKey.BACKUP_AMOUNT_POSITIVE to "The transaction amount has to be positive",
    TextKey.BACKUP_CYCLE_INVALID to "Invalid subscription cycle",
    TextKey.BACKUP_KIND_INVALID to "Invalid economic kind",
    TextKey.BACKUP_VALUE_UNSUPPORTED to "Unsupported value: {0}.{1}",
    TextKey.BACKUP_COUNTER_INVALID to "Invalid import counter",
    TextKey.BACKUP_ALLOCATION_CURRENCY to "The person split currency differs from the transaction",
    TextKey.BACKUP_ALLOCATIONS_EXCEED to "The person splits go past the transaction amount",
    TextKey.BACKUP_OBLIGATION_POSITIVE to "The old debt amount has to be positive",
    TextKey.BACKUP_OBLIGATION_MISMATCH to "The debt does not match the original transaction",
    TextKey.BACKUP_SETTLEMENT_MISMATCH to "The settlement does not match the transaction currency or amount",
    TextKey.BACKUP_SETTLEMENTS_EXCEED to "The settlements go past the original debt",

    TextKey.RECONCILE_FIRST_GAP_MANY to
        "The first gap is on {0}, and that day has {1} movements. The order of movements inside one day is not fixed in the statement, so it is not certain that this one in particular is the first transaction with a problem.",
    TextKey.RECONCILE_FIRST_GAP_ONE to
        "The first gap is on {0}, and that day has a single movement, so the gap belongs to it.",

    TextKey.SMS_NOT_EGP to "This version only supports Egyptian pound messages",

    TextKey.KIND_GIFT_RECEIVED to "Gift",
    TextKey.KIND_SUPPORT_RECEIVED to "Support received",
    TextKey.KIND_BENEFIT_RECEIVED to "Benefit or compensation",
    TextKey.KIND_INVESTMENT_INCOME to "Investment income",
    TextKey.KIND_EVENT_GIFT to "Event gift",
    TextKey.KIND_ROSCA_PAYOUT to "Savings circle payout",
    TextKey.KIND_REFUND_RECEIVED to "Refund",
    TextKey.KIND_ADVANCE_RECEIVED to "Salary advance",

    TextKey.FORECAST_NEEDS_KINDS to
        "A forecast is not available until you set the kinds of the transactions; the spending so far is incomplete.",
)
