package app.masroufy.core

/**
 * نصوص منطقة «الرئيسية» — المراجعة (`ReviewQueue` — §18 · §74). مضمومة في `TextsAreaHome.kt`. أسماء الأنواع نفسها من `KIND_*` (المنطق).
 */
internal val MSA_AREA_HOME_REVIEW_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.REVIEW_QUEUE_TITLE to "المراجعة",
    TextKey.REVIEW_QUEUE_HERO_BODY to "الوارد المجهول خارج الدخل حتى تؤكده. الواضح لا يُسأل عنه.",
    TextKey.REVIEW_QUEUE_DONE_TITLE to "اكتملت المراجعة",
    TextKey.REVIEW_QUEUE_DONE_BODY to "أصبحت الأرقام مؤكدة.",
    TextKey.REVIEW_QUEUE_LEFT_ONE to "عملية واحدة نوعها غير مؤكد",
    TextKey.REVIEW_QUEUE_LEFT_TWO to "عمليتان نوعهما غير مؤكد",
    TextKey.REVIEW_QUEUE_LEFT_FEW to "{0} عمليات نوعها غير مؤكد",
    TextKey.REVIEW_QUEUE_LEFT_MANY to "{0} عملية نوعها غير مؤكد",
    TextKey.REVIEW_QUEUE_GROUP_KIND to "تبدو «{0}»",
    TextKey.REVIEW_QUEUE_GROUP_IN to "مبالغ واردة نوعها غير واضح",
    TextKey.REVIEW_QUEUE_GROUP_OUT to "مبالغ صادرة نوعها غير واضح",
    TextKey.REVIEW_QUEUE_GROUP_COUNT to "{0} ({1})",
    TextKey.REVIEW_QUEUE_BULK to "أكّد الـ{0}",
    TextKey.REVIEW_QUEUE_SUGGESTED to "المقترح",
    TextKey.REVIEW_QUEUE_ACCEPT to "تأكيد",
    TextKey.REVIEW_QUEUE_CHOSEN to "✓ {0}",
    TextKey.REVIEW_QUEUE_UNDO to "تراجع",
    TextKey.REVIEW_QUEUE_EMPTY_TITLE to "لا شيء للمراجعة",
    TextKey.REVIEW_QUEUE_EMPTY_BODY to "كل العمليات نوعها واضح.",
    TextKey.REVIEW_QUEUE_SAVE_FAILED to "تعذّر حفظ آخر تأكيد",
    TextKey.REVIEW_QUEUE_SAVE_FAILED_BODY to "حاول مرة أخرى.",
    TextKey.REVIEW_QUEUE_RULES_TITLE to "طبّق قواعدك على السابق",
    TextKey.REVIEW_QUEUE_RULES_BODY to "اعرض أولًا ما سيتغير تصنيفه في آخر سنة. ما أكدته بنفسك لن يُمس.",
    TextKey.REVIEW_QUEUE_RULES_PREVIEW to "اعرض ما سيتغير",
    TextKey.REVIEW_QUEUE_RULES_COUNT to "سيتغير تصنيف {0} من العمليات السابقة:",
    TextKey.REVIEW_QUEUE_RULES_NONE to "لا عمليات سابقة سيتغير تصنيفها.",
    TextKey.REVIEW_QUEUE_RULES_APPLY to "طبّق على {0}",
    TextKey.REVIEW_QUEUE_RULES_DONE to "طُبّقت على {0}. التصنيفات التي أكدتها بنفسك لم تُمس.",
    TextKey.REVIEW_QUEUE_RULES_UNCATEGORIZED to "بلا تصنيف",
)

internal val EGYPTIAN_AREA_HOME_REVIEW_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.REVIEW_QUEUE_TITLE to "المراجعة",
    TextKey.REVIEW_QUEUE_HERO_BODY to "الداخل اللي نوعه مش معروف برّه الدخل لحد ما تأكده. اللي واضح ما بيتسألش.",
    TextKey.REVIEW_QUEUE_DONE_TITLE to "خلصت المراجعة",
    TextKey.REVIEW_QUEUE_DONE_BODY to "الأرقام بقت مؤكدة.",
    TextKey.REVIEW_QUEUE_LEFT_ONE to "عملية واحدة نوعها مش أكيد",
    TextKey.REVIEW_QUEUE_LEFT_TWO to "عمليتين نوعهم مش أكيد",
    TextKey.REVIEW_QUEUE_LEFT_FEW to "{0} عمليات نوعها مش أكيد",
    TextKey.REVIEW_QUEUE_LEFT_MANY to "{0} عملية نوعها مش أكيد",
    TextKey.REVIEW_QUEUE_GROUP_KIND to "شكلها «{0}»",
    TextKey.REVIEW_QUEUE_GROUP_IN to "فلوس داخلة نوعها مش واضح",
    TextKey.REVIEW_QUEUE_GROUP_OUT to "فلوس طالعة نوعها مش واضح",
    TextKey.REVIEW_QUEUE_GROUP_COUNT to "{0} ({1})",
    TextKey.REVIEW_QUEUE_BULK to "أكّد الـ{0}",
    TextKey.REVIEW_QUEUE_SUGGESTED to "المقترح",
    TextKey.REVIEW_QUEUE_ACCEPT to "تمام",
    TextKey.REVIEW_QUEUE_CHOSEN to "✓ {0}",
    TextKey.REVIEW_QUEUE_UNDO to "تراجع",
    TextKey.REVIEW_QUEUE_EMPTY_TITLE to "مفيش حاجة تتراجع",
    TextKey.REVIEW_QUEUE_EMPTY_BODY to "كل العمليات نوعها واضح.",
    TextKey.REVIEW_QUEUE_SAVE_FAILED to "ما اتحفظش آخر تأكيد",
    TextKey.REVIEW_QUEUE_SAVE_FAILED_BODY to "جرّب تاني.",
    TextKey.REVIEW_QUEUE_RULES_TITLE to "طبّق قواعدك على القديم",
    TextKey.REVIEW_QUEUE_RULES_BODY to "شوف الأول إيه اللي تصنيفه هيتغيّر في آخر سنة. اللي أكدته بنفسك مش هيتلمس.",
    TextKey.REVIEW_QUEUE_RULES_PREVIEW to "شوف هيتغيّر إيه",
    TextKey.REVIEW_QUEUE_RULES_COUNT to "تصنيف {0} من العمليات القديمة هيتغيّر:",
    TextKey.REVIEW_QUEUE_RULES_NONE to "مفيش عمليات قديمة تصنيفها هيتغيّر.",
    TextKey.REVIEW_QUEUE_RULES_APPLY to "طبّق على {0}",
    TextKey.REVIEW_QUEUE_RULES_DONE to "اتطبقت على {0}. التصنيفات اللي أكدتها بنفسك ما اتلمستش.",
    TextKey.REVIEW_QUEUE_RULES_UNCATEGORIZED to "من غير تصنيف",
)

internal val ENGLISH_AREA_HOME_REVIEW_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.REVIEW_QUEUE_TITLE to "Review",
    TextKey.REVIEW_QUEUE_HERO_BODY to "Unknown incoming money stays out of income until you confirm it. Clear ones aren't asked about.",
    TextKey.REVIEW_QUEUE_DONE_TITLE to "Review complete",
    TextKey.REVIEW_QUEUE_DONE_BODY to "Your numbers are confirmed.",
    TextKey.REVIEW_QUEUE_LEFT_ONE to "1 transaction with an unconfirmed type",
    TextKey.REVIEW_QUEUE_LEFT_TWO to "2 transactions with unconfirmed types",
    TextKey.REVIEW_QUEUE_LEFT_FEW to "{0} transactions with unconfirmed types",
    TextKey.REVIEW_QUEUE_LEFT_MANY to "{0} transactions with unconfirmed types",
    TextKey.REVIEW_QUEUE_GROUP_KIND to "Looks like “{0}”",
    TextKey.REVIEW_QUEUE_GROUP_IN to "Incoming money of unclear type",
    TextKey.REVIEW_QUEUE_GROUP_OUT to "Outgoing money of unclear type",
    TextKey.REVIEW_QUEUE_GROUP_COUNT to "{0} ({1})",
    TextKey.REVIEW_QUEUE_BULK to "Confirm all {0}",
    TextKey.REVIEW_QUEUE_SUGGESTED to "Suggested",
    TextKey.REVIEW_QUEUE_ACCEPT to "Confirm",
    TextKey.REVIEW_QUEUE_CHOSEN to "✓ {0}",
    TextKey.REVIEW_QUEUE_UNDO to "Undo",
    TextKey.REVIEW_QUEUE_EMPTY_TITLE to "Nothing to review",
    TextKey.REVIEW_QUEUE_EMPTY_BODY to "Every transaction has a clear type.",
    TextKey.REVIEW_QUEUE_SAVE_FAILED to "Couldn't save the last confirmation",
    TextKey.REVIEW_QUEUE_SAVE_FAILED_BODY to "Try again.",
    TextKey.REVIEW_QUEUE_RULES_TITLE to "Apply your rules to past transactions",
    TextKey.REVIEW_QUEUE_RULES_BODY to "First see which categories would change over the last year. What you confirmed yourself won't be touched.",
    TextKey.REVIEW_QUEUE_RULES_PREVIEW to "Show what will change",
    TextKey.REVIEW_QUEUE_RULES_COUNT to "{0} past transactions would change category:",
    TextKey.REVIEW_QUEUE_RULES_NONE to "No past transactions would change.",
    TextKey.REVIEW_QUEUE_RULES_APPLY to "Apply to {0}",
    TextKey.REVIEW_QUEUE_RULES_DONE to "Applied to {0}. Categories you confirmed yourself weren't touched.",
    TextKey.REVIEW_QUEUE_RULES_UNCATEGORIZED to "Uncategorized",
)
