package app.masroufy.core

/**
 * نصوص منطقة «الرئيسية» — «كمّل ملفك» (`ProfileQuestion` — §63). مضمومة في `TextsAreaHome.kt`. الأسئلة من ملف التسليم §4 (المصري) والفصحى
 * بلمسة سعودية زي النموذج. **جملة الرد بتقول اللي اتغير فعلًا بس** (التصنيفات المشروطة بالملف — `presentCategories`).
 */
internal val MSA_AREA_HOME_PROFILE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.PROFILE_QUESTION_TITLE to "أكمل ملفك",
    TextKey.PROFILE_QUESTION_LEAD to "بطاقة واحدة (١٠ ثوانٍ) تجعل أرقامك أدق",
    TextKey.PROFILE_QUESTION_YES to "نعم",
    TextKey.PROFILE_QUESTION_NO to "لا",
    TextKey.PROFILE_QUESTION_LATER to "ليس الآن",
    TextKey.PROFILE_QUESTION_NEXT to "السؤال التالي",
    TextKey.PROFILE_QUESTION_BACK_HOME to "العودة إلى الرئيسية",
    TextKey.PROFILE_QUESTION_SAVED_TITLE to "حُفظ في ملفك",
    TextKey.PROFILE_QUESTION_SAVED to "حُفظت إجابتك.",
    TextKey.PROFILE_QUESTION_SAVE_FAILED to "تعذّر الحفظ. حاول مرة أخرى.",
    TextKey.PROFILE_QUESTION_NONE_TITLE to "لا أسئلة الآن",
    TextKey.PROFILE_QUESTION_NONE_BODY to "أجبت عن كل الأسئلة المتاحة.",
    TextKey.PROFILE_QUESTION_CAR to "هل لديك سيارة؟",
    TextKey.PROFILE_QUESTION_CAR_SUB to "لنضبط تصنيفات البنزين والصيانة والمخالفات.",
    TextKey.PROFILE_QUESTION_CAR_YES to "ظهر لك تصنيف «السيارة» بفروعه.",
    TextKey.PROFILE_QUESTION_CAR_NO to "لن نعرض لك تصنيفات السيارة.",
    TextKey.PROFILE_QUESTION_CAR_WORK to "هل تذهب بها إلى العمل؟",
    TextKey.PROFILE_QUESTION_FAMILY to "هل تنفق على أحد غيرك؟",
    TextKey.PROFILE_QUESTION_FAMILY_SUB to "لنعرض تصنيفات المنزل والمدارس إن كانت تخصك.",
    TextKey.PROFILE_QUESTION_FAMILY_SPOUSE to "زوجة وأولاد",
    TextKey.PROFILE_QUESTION_FAMILY_PARENTS to "أهلي",
    TextKey.PROFILE_QUESTION_FAMILY_NO to "لن نعرض لك تصنيفات العائلة.",
    TextKey.PROFILE_QUESTION_FAMILY_YES to "تصنيفات العائلة جاهزة.",
    TextKey.PROFILE_QUESTION_HOME_RENT to "إيجار",
    TextKey.PROFILE_QUESTION_HOME_OWN to "ملك",
    TextKey.PROFILE_QUESTION_HOME_FAMILY to "مع أهلي",
    TextKey.PROFILE_QUESTION_HOME_RENT_REPLY to "ظهر لك تصنيف الإيجار.",
    TextKey.PROFILE_QUESTION_HOME_NO_RENT to "لن نعرض لك تصنيف الإيجار.",
    TextKey.PROFILE_QUESTION_HOUSING to "ما نوع سكنك؟",
    TextKey.PROFILE_QUESTION_BIZ to "هل لديك عمل خاص أو مشروع؟",
    TextKey.PROFILE_QUESTION_BIZ_YES to "ظهرت لك تصنيفات العمل الخاص.",
    TextKey.PROFILE_QUESTION_BIZ_NO to "لن نعرض لك تصنيفات العمل الخاص.",
)

internal val EGYPTIAN_AREA_HOME_PROFILE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.PROFILE_QUESTION_TITLE to "كمّل ملفك",
    TextKey.PROFILE_QUESTION_LEAD to "كارت واحد (١٠ ثواني) بيخلّي أرقامك أدق",
    TextKey.PROFILE_QUESTION_YES to "أيوه",
    TextKey.PROFILE_QUESTION_NO to "لأ",
    TextKey.PROFILE_QUESTION_LATER to "مش دلوقتي",
    TextKey.PROFILE_QUESTION_NEXT to "السؤال اللي بعده",
    TextKey.PROFILE_QUESTION_BACK_HOME to "رجوع للرئيسية",
    TextKey.PROFILE_QUESTION_SAVED_TITLE to "اتحفظ في ملفك",
    TextKey.PROFILE_QUESTION_SAVED to "إجابتك اتحفظت.",
    TextKey.PROFILE_QUESTION_SAVE_FAILED to "ما اتحفظش. جرّب تاني.",
    TextKey.PROFILE_QUESTION_NONE_TITLE to "مفيش أسئلة دلوقتي",
    TextKey.PROFILE_QUESTION_NONE_BODY to "جاوبت على كل الأسئلة المتاحة.",
    TextKey.PROFILE_QUESTION_CAR to "عندك عربية؟",
    TextKey.PROFILE_QUESTION_CAR_SUB to "عشان نظبط تصنيفات البنزين والصيانة والمخالفات.",
    TextKey.PROFILE_QUESTION_CAR_YES to "ظهرلك تصنيف «السيارة» بفروعه.",
    TextKey.PROFILE_QUESTION_CAR_NO to "مش هنوريك تصنيفات العربية.",
    TextKey.PROFILE_QUESTION_CAR_WORK to "هتروح بيها الشغل؟",
    TextKey.PROFILE_QUESTION_FAMILY to "بتصرف على حد غيرك؟",
    TextKey.PROFILE_QUESTION_FAMILY_SUB to "عشان نوريك تصنيفات البيت والمدارس لو تخصّك.",
    TextKey.PROFILE_QUESTION_FAMILY_SPOUSE to "زوجة وأولاد",
    TextKey.PROFILE_QUESTION_FAMILY_PARENTS to "أهلي",
    TextKey.PROFILE_QUESTION_FAMILY_NO to "مش هنوريك تصنيفات العيلة.",
    TextKey.PROFILE_QUESTION_FAMILY_YES to "تصنيفات العيلة جاهزة.",
    TextKey.PROFILE_QUESTION_HOME_RENT to "إيجار",
    TextKey.PROFILE_QUESTION_HOME_OWN to "ملك",
    TextKey.PROFILE_QUESTION_HOME_FAMILY to "مع أهلي",
    TextKey.PROFILE_QUESTION_HOME_RENT_REPLY to "ظهرلك تصنيف الإيجار.",
    TextKey.PROFILE_QUESTION_HOME_NO_RENT to "مش هنوريك تصنيف الإيجار.",
    TextKey.PROFILE_QUESTION_HOUSING to "ساكن في؟",
    TextKey.PROFILE_QUESTION_BIZ to "عندك شغل خاص أو مشروع؟",
    TextKey.PROFILE_QUESTION_BIZ_YES to "ظهرتلك تصنيفات الشغل الخاص.",
    TextKey.PROFILE_QUESTION_BIZ_NO to "مش هنوريك تصنيفات الشغل الخاص.",
)

internal val ENGLISH_AREA_HOME_PROFILE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.PROFILE_QUESTION_TITLE to "Complete your profile",
    TextKey.PROFILE_QUESTION_LEAD to "One card (10 seconds) makes your numbers sharper",
    TextKey.PROFILE_QUESTION_YES to "Yes",
    TextKey.PROFILE_QUESTION_NO to "No",
    TextKey.PROFILE_QUESTION_LATER to "Not now",
    TextKey.PROFILE_QUESTION_NEXT to "Next question",
    TextKey.PROFILE_QUESTION_BACK_HOME to "Back to Home",
    TextKey.PROFILE_QUESTION_SAVED_TITLE to "Saved to your profile",
    TextKey.PROFILE_QUESTION_SAVED to "Your answer is saved.",
    TextKey.PROFILE_QUESTION_SAVE_FAILED to "Couldn't save. Try again.",
    TextKey.PROFILE_QUESTION_NONE_TITLE to "No questions right now",
    TextKey.PROFILE_QUESTION_NONE_BODY to "You've answered every available question.",
    TextKey.PROFILE_QUESTION_CAR to "Do you have a car?",
    TextKey.PROFILE_QUESTION_CAR_SUB to "So we can set up fuel, maintenance and fines categories.",
    TextKey.PROFILE_QUESTION_CAR_YES to "The Car category and its subcategories are now shown.",
    TextKey.PROFILE_QUESTION_CAR_NO to "Car categories stay hidden.",
    TextKey.PROFILE_QUESTION_CAR_WORK to "Do you drive it to work?",
    TextKey.PROFILE_QUESTION_FAMILY to "Do you support anyone besides yourself?",
    TextKey.PROFILE_QUESTION_FAMILY_SUB to "So we show home and school categories if they apply to you.",
    TextKey.PROFILE_QUESTION_FAMILY_SPOUSE to "Spouse and children",
    TextKey.PROFILE_QUESTION_FAMILY_PARENTS to "My parents",
    TextKey.PROFILE_QUESTION_FAMILY_NO to "Family categories stay hidden.",
    TextKey.PROFILE_QUESTION_FAMILY_YES to "Family categories are ready.",
    TextKey.PROFILE_QUESTION_HOME_RENT to "Rent",
    TextKey.PROFILE_QUESTION_HOME_OWN to "Own",
    TextKey.PROFILE_QUESTION_HOME_FAMILY to "With family",
    TextKey.PROFILE_QUESTION_HOME_RENT_REPLY to "The Rent category is now shown.",
    TextKey.PROFILE_QUESTION_HOME_NO_RENT to "The Rent category stays hidden.",
    TextKey.PROFILE_QUESTION_HOUSING to "What's your housing?",
    TextKey.PROFILE_QUESTION_BIZ to "Do you have a business or side project?",
    TextKey.PROFILE_QUESTION_BIZ_YES to "Business categories are now shown.",
    TextKey.PROFILE_QUESTION_BIZ_NO to "Business categories stay hidden.",
)
