package app.masroufy.core

/** «العمليات» بالمصري — الجزء التالت: زون التحويلات · «مين ده؟» · التحويل لنفسك بين البلدين. */
internal val EGYPTIAN_OPERATIONS_TRANSFER_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.TRANSFERS_TITLE to "التحويلات",
    UiKey.TRANSFERS_INTRO to "كل طرف بتحوّله أو بيحوّلك: قول مين هو مرة واحدة، والقديم والجديد بيتظبطوا لوحدهم.",
    UiKey.TRANSFERS_WAITING to "محتاجين ردك",
    UiKey.TRANSFERS_UNDECIDED to "من غير قرار",
    UiKey.TRANSFERS_DECIDED to "اتقرر",
    UiKey.TRANSFERS_IN_MONTH to "{0} في {1}",
    UiKey.TRANSFERS_META to "{0}، آخر واحد {1}",
    UiKey.TRANSFERS_LAST4 to "•••• {0}",
    UiKey.TRANSFERS_PERSON_CHIP to "شخص: {0}",
    UiKey.TRANSFERS_HINT_ASK to "شخص: تحويلاته بتتسجل عليه، وبنسألك نوع كل تحويل (سلفة ولا دعم…).",
    UiKey.TRANSFERS_HINT_OWN to "كل التحويلات معاه بقت بين محافظك، مش دخل ولا مصروف.",
    UiKey.TRANSFERS_HINT_UNDO to "فك القرار بيرجّع السؤال.",
    UiKey.TRANSFERS_PERSON to "شخص",
    UiKey.TRANSFERS_FORGET to "فك القرار",
    UiKey.TRANSFERS_DONE_OWN to "اتصلّح {0} — بقوا بين محافظك",
    UiKey.TRANSFERS_DONE_NOT to "تمام، مش هنسأل عنه تاني",
    UiKey.TRANSFERS_DONE_FORGET to "اتفك القرار — التحويلات اللي اتغيرت رجعت «لسه ما اتحددش»",
    UiKey.TRANSFERS_DONE_PERSON to "اتربط بـ{0}",
    UiKey.TRANSFERS_DONE_PERSON_NEW to "اتربط بـ{0} واتضاف لأشخاصك",
    UiKey.TRANSFERS_PERSON_BODY to "اكتب اسم شخص جديد أو اختار من أشخاصك.",
    UiKey.TRANSFERS_NEW_PERSON to "شخص جديد",
    UiKey.TRANSFERS_LINK to "اربط",
    UiKey.TRANSFERS_NO_PARTY to "{0} مالهاش طرف — ملف البنك ما فيهوش اسم ولا رقم. بنسيبها زي ما هي ومن غير تخمين.",
    UiKey.TRANSFERS_EMPTY to "مفيش تحويلات لسه",
    UiKey.TRANSFERS_EMPTY_BODY to "لما تيجي تحويلات من رسايل البنك أو الكشف هتظهر هنا متجمّعة بالطرف.",
    UiKey.TRANSFERS_ERROR to "ما قدرناش نحمّل التحويلات",
    UiKey.TRANSFERS_COUNT_ONE to "تحويل واحد",
    UiKey.TRANSFERS_COUNT_TWO to "تحويلين",
    UiKey.TRANSFERS_COUNT_FEW to "{0} تحويلات",
    UiKey.TRANSFERS_COUNT_MANY to "{0} تحويل",
    UiKey.TRANSFER_PARTY_ASK to "مين ده؟",
    UiKey.TRANSFER_PARTY_NAME to "الاسم زي ما جه: {0}",
    UiKey.TRANSFER_PARTY_ACCOUNT to "حساب آخره {0}",
    UiKey.TRANSFER_PARTY_PERSON to "شخص أعرفه",
    UiKey.TRANSFER_PARTY_OWN to "حسابي التاني",
    UiKey.TRANSFER_PARTY_NOT to "مش ده",
    UiKey.TRANSFER_PARTY_UNDO to "تراجع",
    UiKey.TRANSFER_PARTY_DONE_PERSON to "اتربط بـ{0}، {1}",
    UiKey.TRANSFER_PARTY_ADDED to "{0} اتضاف لأشخاصك.",
    UiKey.TRANSFER_PARTY_DONE_PERSON_BODY to "أي تحويل من {0} أو ليه هيتسجل عليه لوحده، وهنسألك نوعه كل مرة (سلفة ولا دعم…).",
    UiKey.TRANSFER_PARTY_DONE_OWN to "تحويل بين محافظك",
    UiKey.TRANSFER_PARTY_DONE_OWN_BODY to "مش دخل ولا مصروف. واتصلّح كمان {0} من نفس الطرف.",
    UiKey.TRANSFER_PARTY_DONE_NOT to "تمام",
    UiKey.TRANSFER_PARTY_DONE_NOT_BODY to "مش هنسألك عن الحساب ده تاني.",
    UiKey.TRANSFER_PARTY_WHO_TITLE to "مين صاحب الحساب {0}؟",
    UiKey.TRANSFER_PARTY_KIND_TITLE to "الفلوس دي من {0}",
    UiKey.TRANSFER_PARTY_NEW_TITLE to "شخص جديد (الاسم زي ما جه)",
    UiKey.TRANSFER_PARTY_NAME_LABEL to "اسم الشخص",
    UiKey.TRANSFER_PARTY_OR to "أو واحد من أشخاصك",
    UiKey.TRANSFER_PARTY_NEXT to "التالي",
    UiKey.TRANSFER_PARTY_KIND_Q to "الفلوس دي إيه؟",
    UiKey.TRANSFER_PARTY_SAVE to "اربط وسجّل",
    UiKey.SPACE_TRANSFER_SCREEN_TITLE to "تحويلاتك بين البلدين",
    UiKey.SPACE_TRANSFER_SCREEN_INTRO to "فلوس نقلتها من حسابك في بلد لحسابك في التانية. مش بتتحسب مصروف ولا دخل في أي بلد، وكل رجل بعملتها زي الكشف بالظبط.",
    UiKey.SPACE_TRANSFER_SCREEN_ERROR to "ما قدرناش نحمّل التحويلات بين البلدين",
    UiKey.SPACE_TRANSFER_SCREEN_NA_TITLE to "عندك بلد واحدة بس",
    UiKey.SPACE_TRANSFER_SCREEN_NA_BODY to "التحويل لنفسك بيبقى بين بلدين مختلفين. ضيف بلدك التانية الأول، وبعدها تسجّل التحويلات بينهم.",
    UiKey.SPACE_TRANSFER_SCREEN_ADD_SPACE to "ضيف بلد",
    UiKey.SPACE_TRANSFER_SCREEN_NEW to "سجّل تحويل",
    UiKey.SPACE_TRANSFER_SCREEN_LINK to "اربط عمليتين",
    UiKey.SPACE_TRANSFER_SCREEN_LINK_SOON to "ربط عمليتين موجودين لسه مش متاح — قايمة العمليات المرشحة في البلدين ما اتبنتش.",
    UiKey.SPACE_TRANSFER_SCREEN_EMPTY to "مفيش تحويلات بين البلدين لسه",
    UiKey.SPACE_TRANSFER_SCREEN_EMPTY_BODY to "لما تنقل فلوس من بلد للتانية، سجّلها هنا.",
    UiKey.SPACE_TRANSFER_SCREEN_ROUTE to "من {0} لـ{1}",
    UiKey.SPACE_TRANSFER_SCREEN_NOT_SPEND to "مش مصروف ولا دخل",
    UiKey.SPACE_TRANSFER_SCREEN_LEFT to "طلعت من {0}",
    UiKey.SPACE_TRANSFER_SCREEN_ARRIVED to "وصلت في {0}",
    UiKey.SPACE_TRANSFER_SCREEN_RATE to "السعر اللي اتاخد (للعرض بس)",
    UiKey.SPACE_TRANSFER_SCREEN_RATE_LINE to "{0} {1} لكل {2} {3}",
    UiKey.SPACE_TRANSFER_SCREEN_NOTE_LINE to "ملاحظتك: {0}",
    UiKey.SPACE_TRANSFER_SCREEN_UNLINK to "فك الربط",
    UiKey.SPACE_TRANSFER_SCREEN_LOCK_NOTE to "كل رجل مقفولة على نوعها: لو عايز تغيّر نوعها أو تربطها بحاجة تانية فك الربط الأول. والسعر بيتحسب من المبلغين ومش بيحوّل أي رقم تاني.",
    UiKey.SPACE_TRANSFER_SCREEN_UNLINK_TITLE to "تفك ربط التحويل؟",
    UiKey.SPACE_TRANSFER_SCREEN_UNLINK_BODY to "العمليتين مش هيتمسحوا. نوع كل واحدة هيرجع «لسه ما اتحددش» وهيظهروا في المراجعات.",
    UiKey.SPACE_TRANSFER_SCREEN_CANCEL to "إلغاء",
    UiKey.SPACE_TRANSFER_SCREEN_UNLINKED to "اتفك الربط — العمليتين رجعوا للمراجعات",
    UiKey.SPACE_TRANSFER_SCREEN_SAVED to "اتسجّل التحويل — مش مصروف ولا دخل",
    UiKey.SPACE_TRANSFER_SCREEN_NEW_TITLE to "تحويل جديد لنفسك",
    UiKey.SPACE_TRANSFER_SCREEN_NEW_BODY to "عمليتين: طالعة من بلد وداخلة في التانية.",
    UiKey.SPACE_TRANSFER_SCREEN_AMOUNT_OUT to "المبلغ اللي طلع ({0})",
    UiKey.SPACE_TRANSFER_SCREEN_AMOUNT_IN to "المبلغ اللي وصل ({0})",
    UiKey.SPACE_TRANSFER_SCREEN_DATE to "التاريخ",
    UiKey.SPACE_TRANSFER_SCREEN_NOTE to "ملاحظة (اختياري)",
    UiKey.SPACE_TRANSFER_SCREEN_LIVE_RATE to "السعر (للعرض بس)",
    UiKey.SPACE_TRANSFER_SCREEN_AFTER_AMOUNTS to "بعد ما تكتب المبلغين",
    UiKey.SPACE_TRANSFER_SCREEN_RECORD to "سجّله",
    UiKey.SPACE_TRANSFER_SCREEN_LEG_OUT to "طلعت، {0}",
    UiKey.SPACE_TRANSFER_SCREEN_LEG_IN to "وصلت، {0}",
)
