package app.masroufy.core

/**
 * نصوص «حاسبة التقاعد» (`RetirementCalculator` + `RetirementSaudi`) — من النموذج بالحرف (الفصحى للسعودية والمصري لمصر)؛ الإنجليزي كتابة
 * Claude (مستني مراجعة المالك §40). أسباب «غير متاح» نفسها من `TextsCalculators.kt`/`TextsRetirement.kt` (حالة الاستخدام).
 */
internal val MSA_CALC_RETIRE_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.RETCALC_TITLE to "حاسبة التقاعد",
    UiKey.RETCALC_LAW_SA to "السعودية، نظام التأمينات الاجتماعية",
    UiKey.RETCALC_LAW_EG to "مصر، قانون التأمينات والمعاشات 148 لسنة 2019",
    UiKey.RETCALC_INTRO to "تجيب عن سؤالين: كم سيكون معاشك، وكم تدّخر شهريًا لتعيش بالمبلغ الذي تريده.",
    UiKey.RETCALC_COUNTRY_NA to "حاسبة التقاعد متاحة للسعودية ومصر فقط",
    UiKey.RETCALC_FILL to "أكمل البيانات",
    UiKey.RETCALC_FILL_SUB to "تظهر النتيجة حين تصح الخانات.",
    UiKey.RETCALC_NO_PENSION to "لا معاش",
    UiKey.RETCALC_EOS to "مكافأة نهاية الخدمة",
    UiKey.RETCALC_GAP to "كم تدّخر شهريًا حتى التقاعد",
    UiKey.RETCALC_NOT_APPLICABLE to "لا تنطبق",
    UiKey.RETCALC_NOT_COUNTED to "لا يُحسب",
    UiKey.RETCALC_EOS_PICK_END to "اختر كيف سينتهي عملك",
    UiKey.RETCALC_EOS_SUB to "{0} سنة و{1} يومًا، {2}",
    UiKey.RETCALC_EOS_NONE to "لا شيء",
    UiKey.RETCALC_EOS_THIRD to "ثلثها (استقالة)",
    UiKey.RETCALC_EOS_TWO_THIRDS to "ثلثاها (استقالة)",
    UiKey.RETCALC_EOS_FULL to "كاملة",
    UiKey.RETCALC_GAP_NEED_WANT to "اكتب المبلغ الشهري الذي تريد العيش به",
    UiKey.RETCALC_GAP_SUB to "ينقصك {0} شهريًا بعد المعاش × {1} شهرًا = {2} − المكافأة − ما معك = {3} ÷ {4} شهرًا، بلا أرباح",
    UiKey.RETCALC_HOW_SHOW to "كيف حُسب المعاش؟",
    UiKey.RETCALC_HOW_HIDE to "إخفاء طريقة الحساب",
    UiKey.RETCALC_HOW_APPLIED to " ← طُبّق",
    UiKey.RETCALC_SEC_CONTRIB to "اشتراكك",
    UiKey.RETCALC_BIRTH to "تاريخ الميلاد",
    UiKey.RETCALC_SO_FAR to "شهور الاشتراك حتى اليوم",
    UiKey.RETCALC_SO_FAR_NOTE to "من كشف التأمينات",
    UiKey.RETCALC_SOFAR_RANGE to "المدة من 0 حتى 1200 شهر",
    UiKey.RETCALC_RETIRE to "السن الذي تنوي التقاعد فيه (اختياري)",
    UiKey.RETCALC_RETIRE_NOTE to "فارغ = السن النظامية",
    UiKey.RETCALC_RETIRE_NOTE_LEGAL to "فارغ = السن النظامية لك: {0}",
    UiKey.RETCALC_MANY_JOBS to "لك أكثر من عمل حالي في مصادر الدخل — اكتب أجرك بنفسك",
    UiKey.RETCALC_SEC_LIVING to "ما تريد العيش به",
    UiKey.RETCALC_WANT to "المبلغ الشهري الذي تريد العيش به",
    UiKey.RETCALC_YEARS to "كم سنة يكفيك مال التقاعد؟",
    UiKey.RETCALC_YEARS_NOTE to "مطلوب — لا رقم افتراضي له",
    UiKey.RETCALC_HAVE to "كم معك الآن للتقاعد؟",
    UiKey.RETCALC_HAVE_NOTE to "فارغ = صفر",
    UiKey.RETSA_QUESTION to "هل اشتركت في التأمينات قبل يوليو 2024؟",
    UiKey.RETSA_LAW_LINE_OLD to "النظام القديم (م/33) — وسن التقاعد من جدول البند «خامسًا» في المرسوم م/273",
    UiKey.RETSA_LAW_LINE_NEW to "النظام الجديد (م/273) — السن النظامية 65",
    UiKey.RETSA_LAW_OLD to "النظام القديم",
    UiKey.RETSA_LAW_NEW to "النظام الجديد",
    UiKey.RETSA_HERO_LABEL to "المعاش المتوقع شهريًا",
    UiKey.RETSA_HERO_SUB to "{0}، التقاعد عند {1} في {2}، {3} شهر اشتراك",
    UiKey.RETSA_AT_2024 to "شهور اشتراكك في 3 يوليو 2024",
    UiKey.RETSA_AT_2024_NOTE to "سن تقاعدك في النظام القديم يتحدد منها",
    UiKey.RETSA_M_1422 to "منها قبل 1422هـ (اختياري)",
    UiKey.RETSA_M_1422_NOTE to "تُحسب على 600 بدل 480",
    UiKey.RETSA_SEC_WAGE to "أجرك الخاضع للاشتراك",
    UiKey.RETSA_BASIC to "الأجر الأساسي الشهري",
    UiKey.RETSA_BASIC_NOTE to "اكتب أجرك الأساسي الشهري",
    UiKey.RETSA_BASIC_NOTE_SUGGEST to "فارغ = راتبك في مصادر الدخل ({0}) — عدّله إن كان فيه بدلات",
    UiKey.RETSA_HOUSING to "بدل السكن الشهري",
    UiKey.RETSA_HOUSING_NOTE to "اكتب صفرًا إن لم يكن لك بدل سكن",
    UiKey.RETSA_JOB to "بداية عملك الحالي",
    UiKey.RETSA_JOB_NOTE to "اختر تاريخ بداية عملك الحالي",
    UiKey.RETSA_JOB_NOTE_SUGGEST to "من مصادر الدخل: {0} — غيّره إن لزم",
    UiKey.RETSA_EOS_WAGE to "أجرك الأخير كاملًا",
    UiKey.RETSA_EOS_WAGE_NOTE to "الأساسي مع كل البدلات (نظام العمل م2)",
    UiKey.RETSA_EOS_WAGE_NOTE_SUGGEST to "فارغ = راتبك في مصادر الدخل ({0}) — الأساسي مع كل البدلات (نظام العمل م2)",
    UiKey.RETSA_END to "كيف سينتهي عملك؟",
    UiKey.RETSA_END_NOTE to "نسألك كل مرة — الاستقالة تُنقص المكافأة (م85)",
    UiKey.RETSA_END_CONTRACT to "انتهاء العقد أو السن",
    UiKey.RETSA_END_RESIGN to "استقالة",
    UiKey.RETSA_END_ART80 to "فسخ (م80)",
    UiKey.RETSA_HOW_NEW_WAGE to "متوسط الأجر (الأساسي + السكن، بسقف 45,000): {0}",
    UiKey.RETSA_HOW_NEW_ACCRUED to "× 2.25% × {0} شهرًا ÷ 12 = {1}",
    UiKey.RETSA_HOW_CAPPED to " ← بسقف 100% من المتوسط",
    UiKey.RETSA_HOW_NEW_MIN to "الحد الأدنى لمدتك: {0}",
    UiKey.RETSA_HOW_NEW_REDUCE to "التخفيض المبكر: −{0} (3% عن كل 12 شهرًا من {1} شهرًا — بعد الحد الأدنى، فقد ينزل تحته)",
    UiKey.RETSA_HOW_NEW_INCREASE to "الزيادة بعد السن: +{0} (3% عن كل 12 شهرًا)",
    UiKey.RETSA_HOW_NEW_NONE to "لا تخفيض ولا زيادة: التقاعد في السن النظامية",
    UiKey.RETSA_HOW_OLD_WAGE to "متوسط أجر آخر سنتين (الأساسي + السكن): {0}",
    UiKey.RETSA_HOW_OLD_ACCRUED to "× {0} ÷ 480 = {1}",
    UiKey.RETSA_HOW_OLD_ACCRUED_1422 to "× {0} ÷ 480 + {1} ÷ 600 = {2}",
    UiKey.RETSA_HOW_OLD_MIN to "الحد الأدنى {0}",
    UiKey.RETSA_HOW_OLD_AGE_FIFTH to "سن تقاعدك: {0} — من جدول البند «خامسًا» في المرسوم م/273",
    UiKey.RETSA_HOW_OLD_AGE_60 to "سن تقاعدك: {0} — البند «خامسًا» لا ينطبق عليك",
    UiKey.RETSA_ASSUME to "فرض الحساب: الاشتراك والأجر مستمران كما هما حتى التقاعد، وما تدّخره بلا أرباح. حساب تقريبي للتخطيط، والرقم الرسمي من التأمينات.",
    UiKey.RETSA_SOURCES to "المصادر: نظام التأمينات الاجتماعية (م/273) المواد 8 و16–17 و26 وقرار مجلس الوزراء 1022، صفحة المعاش في التأمينات (النظام القديم)، نظام العمل المواد 2 و84–85 و87.",
)

internal val EGYPTIAN_CALC_RETIRE_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.RETCALC_TITLE to "حاسبة التقاعد",
    UiKey.RETCALC_LAW_SA to "السعودية، نظام التأمينات الاجتماعية",
    UiKey.RETCALC_LAW_EG to "مصر، قانون التأمينات والمعاشات 148 لسنة 2019",
    UiKey.RETCALC_INTRO to "بتجاوب على سؤالين: معاشك هيبقى كام، وتحوّش كام في الشهر عشان تعيش بالمبلغ اللي عايزه.",
    UiKey.RETCALC_COUNTRY_NA to "حاسبة التقاعد متاحة للسعودية ومصر بس",
    UiKey.RETCALC_FILL to "كمّل البيانات",
    UiKey.RETCALC_FILL_SUB to "الحساب بيظهر أول ما الخانات تبقى صح.",
    UiKey.RETCALC_NO_PENSION to "مفيش معاش",
    UiKey.RETCALC_EOS to "مكافأة نهاية الخدمة",
    UiKey.RETCALC_GAP to "تحوّش كام في الشهر لحد التقاعد",
    UiKey.RETCALC_NOT_APPLICABLE to "مش منطبقة",
    UiKey.RETCALC_NOT_COUNTED to "مش بتتحسب",
    UiKey.RETCALC_EOS_PICK_END to "اختار شغلك هيخلص إزاي",
    UiKey.RETCALC_EOS_SUB to "{0} سنة و{1} يوم، {2}",
    UiKey.RETCALC_EOS_NONE to "ولا حاجة",
    UiKey.RETCALC_EOS_THIRD to "تلتها (استقالة)",
    UiKey.RETCALC_EOS_TWO_THIRDS to "تلتينها (استقالة)",
    UiKey.RETCALC_EOS_FULL to "كاملة",
    UiKey.RETCALC_GAP_NEED_WANT to "اكتب المبلغ اللي عايز تعيش بيه في الشهر",
    UiKey.RETCALC_GAP_SUB to "ناقصك {0} في الشهر بعد المعاش × {1} شهر = {2} − المكافأة − اللي معاك = {3} ÷ {4} شهر، من غير أرباح",
    UiKey.RETCALC_HOW_SHOW to "المعاش اتحسب إزاي؟",
    UiKey.RETCALC_HOW_HIDE to "اخفي طريقة الحساب",
    UiKey.RETCALC_HOW_APPLIED to " ← اتطبّق",
    UiKey.RETCALC_SEC_CONTRIB to "اشتراكك",
    UiKey.RETCALC_BIRTH to "تاريخ الميلاد",
    UiKey.RETCALC_SO_FAR to "شهور الاشتراك لحد النهارده",
    UiKey.RETCALC_SO_FAR_NOTE to "من كشف التأمينات",
    UiKey.RETCALC_SOFAR_RANGE to "المدة من 0 لحد 1200 شهر",
    UiKey.RETCALC_RETIRE to "السن اللي ناوي تتقاعد فيه (اختياري)",
    UiKey.RETCALC_RETIRE_NOTE to "فاضي = سن المعاش",
    UiKey.RETCALC_RETIRE_NOTE_LEGAL to "فاضي = سن المعاش بتاعك: {0}",
    UiKey.RETCALC_MANY_JOBS to "ليك أكتر من شغل حالي في مصادر الدخل — اكتب أجرك بنفسك",
    UiKey.RETCALC_SEC_LIVING to "اللي عايز تعيش بيه",
    UiKey.RETCALC_WANT to "عايز تعيش بكام في الشهر؟",
    UiKey.RETCALC_YEARS to "فلوس التقاعد تكفيك كام سنة؟",
    UiKey.RETCALC_YEARS_NOTE to "مطلوب — مفيش رقم افتراضي له",
    UiKey.RETCALC_HAVE to "معاك كام للتقاعد دلوقتي؟",
    UiKey.RETCALC_HAVE_NOTE to "فاضي = صفر",
    UiKey.RETSA_QUESTION to "اشتركت في التأمينات قبل يوليو 2024؟",
    UiKey.RETSA_LAW_LINE_OLD to "النظام القديم (م/33) — وسن التقاعد من جدول البند «خامسًا» في المرسوم م/273",
    UiKey.RETSA_LAW_LINE_NEW to "النظام الجديد (م/273) — سن المعاش 65",
    UiKey.RETSA_LAW_OLD to "النظام القديم",
    UiKey.RETSA_LAW_NEW to "النظام الجديد",
    UiKey.RETSA_HERO_LABEL to "المعاش المتوقع في الشهر",
    UiKey.RETSA_HERO_SUB to "{0}، التقاعد على {1} في {2}، {3} شهر اشتراك",
    UiKey.RETSA_AT_2024 to "شهور اشتراكك يوم 3 يوليو 2024",
    UiKey.RETSA_AT_2024_NOTE to "سن تقاعدك في النظام القديم بيتحدد منها",
    UiKey.RETSA_M_1422 to "منهم قبل 1422هـ (اختياري)",
    UiKey.RETSA_M_1422_NOTE to "بتتحسب على 600 بدل 480",
    UiKey.RETSA_SEC_WAGE to "أجرك اللي عليه اشتراك",
    UiKey.RETSA_BASIC to "المرتب الأساسي في الشهر",
    UiKey.RETSA_BASIC_NOTE to "اكتب مرتبك الأساسي في الشهر",
    UiKey.RETSA_BASIC_NOTE_SUGGEST to "فاضي = مرتبك في مصادر الدخل ({0}) — عدّله لو فيه بدلات",
    UiKey.RETSA_HOUSING to "بدل السكن في الشهر",
    UiKey.RETSA_HOUSING_NOTE to "اكتب صفر لو مالكش بدل سكن",
    UiKey.RETSA_JOB to "بداية شغلك الحالي",
    UiKey.RETSA_JOB_NOTE to "اختار تاريخ بداية شغلك الحالي",
    UiKey.RETSA_JOB_NOTE_SUGGEST to "من مصادر الدخل: {0} — غيّره لو محتاج",
    UiKey.RETSA_EOS_WAGE to "أجرك الأخير كله",
    UiKey.RETSA_EOS_WAGE_NOTE to "الأساسي مع كل البدلات (نظام العمل م2)",
    UiKey.RETSA_EOS_WAGE_NOTE_SUGGEST to "فاضي = مرتبك في مصادر الدخل ({0}) — الأساسي مع كل البدلات (نظام العمل م2)",
    UiKey.RETSA_END to "شغلك هيخلص إزاي؟",
    UiKey.RETSA_END_NOTE to "بنسألك كل مرة — الاستقالة بتقلّل المكافأة (م85)",
    UiKey.RETSA_END_CONTRACT to "انتهاء العقد أو السن",
    UiKey.RETSA_END_RESIGN to "استقالة",
    UiKey.RETSA_END_ART80 to "فسخ (م80)",
    UiKey.RETSA_HOW_NEW_WAGE to "متوسط الأجر (الأساسي + السكن، بسقف 45,000): {0}",
    UiKey.RETSA_HOW_NEW_ACCRUED to "× 2.25% × {0} شهر ÷ 12 = {1}",
    UiKey.RETSA_HOW_CAPPED to " ← بسقف 100% من المتوسط",
    UiKey.RETSA_HOW_NEW_MIN to "الحد الأدنى لمدتك: {0}",
    UiKey.RETSA_HOW_NEW_REDUCE to "التخفيض المبكر: −{0} (3% عن كل 12 شهر من {1} شهر — بعد الحد الأدنى، فممكن ينزل تحته)",
    UiKey.RETSA_HOW_NEW_INCREASE to "الزيادة بعد السن: +{0} (3% عن كل 12 شهر)",
    UiKey.RETSA_HOW_NEW_NONE to "مفيش تخفيض ولا زيادة: التقاعد في سن المعاش",
    UiKey.RETSA_HOW_OLD_WAGE to "متوسط أجر آخر سنتين (الأساسي + السكن): {0}",
    UiKey.RETSA_HOW_OLD_ACCRUED to "× {0} ÷ 480 = {1}",
    UiKey.RETSA_HOW_OLD_ACCRUED_1422 to "× {0} ÷ 480 + {1} ÷ 600 = {2}",
    UiKey.RETSA_HOW_OLD_MIN to "الحد الأدنى {0}",
    UiKey.RETSA_HOW_OLD_AGE_FIFTH to "سن تقاعدك: {0} — من جدول البند «خامسًا» في المرسوم م/273",
    UiKey.RETSA_HOW_OLD_AGE_60 to "سن تقاعدك: {0} — البند «خامسًا» مش بينطبق عليك",
    UiKey.RETSA_ASSUME to "فرض الحسبة: الاشتراك والأجر مستمرين زي ما هم لحد التقاعد، واللي بتحوّشه من غير أرباح. حساب تقريبي للتخطيط، والرقم الرسمي من التأمينات.",
    UiKey.RETSA_SOURCES to "المصادر: نظام التأمينات الاجتماعية (م/273) مواد 8 و16–17 و26 وقرار مجلس الوزراء 1022، صفحة المعاش في التأمينات (النظام القديم)، نظام العمل مواد 2 و84–85 و87.",
)

internal val ENGLISH_CALC_RETIRE_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.RETCALC_TITLE to "Retirement calculator",
    UiKey.RETCALC_LAW_SA to "Saudi Arabia, Social Insurance Law",
    UiKey.RETCALC_LAW_EG to "Egypt, Social Insurance and Pensions Law 148 of 2019",
    UiKey.RETCALC_INTRO to "Answers two questions: what your pension will be, and how much to save each month to live on the amount you want.",
    UiKey.RETCALC_COUNTRY_NA to "The retirement calculator is available for Saudi Arabia and Egypt only",
    UiKey.RETCALC_FILL to "Complete the fields",
    UiKey.RETCALC_FILL_SUB to "The result shows once the fields are valid.",
    UiKey.RETCALC_NO_PENSION to "No pension",
    UiKey.RETCALC_EOS to "End-of-service award",
    UiKey.RETCALC_GAP to "Monthly saving until retirement",
    UiKey.RETCALC_NOT_APPLICABLE to "Not applicable",
    UiKey.RETCALC_NOT_COUNTED to "Not calculated",
    UiKey.RETCALC_EOS_PICK_END to "Choose how your job will end",
    UiKey.RETCALC_EOS_SUB to "{0} years and {1} days, {2}",
    UiKey.RETCALC_EOS_NONE to "nothing",
    UiKey.RETCALC_EOS_THIRD to "a third (resignation)",
    UiKey.RETCALC_EOS_TWO_THIRDS to "two thirds (resignation)",
    UiKey.RETCALC_EOS_FULL to "full",
    UiKey.RETCALC_GAP_NEED_WANT to "Enter the monthly amount you want to live on",
    UiKey.RETCALC_GAP_SUB to "{0} a month short after the pension × {1} months = {2} − the award − what you have = {3} ÷ {4} months, without returns",
    UiKey.RETCALC_HOW_SHOW to "How was the pension calculated?",
    UiKey.RETCALC_HOW_HIDE to "Hide the calculation",
    UiKey.RETCALC_HOW_APPLIED to " ← applied",
    UiKey.RETCALC_SEC_CONTRIB to "Your contributions",
    UiKey.RETCALC_BIRTH to "Date of birth",
    UiKey.RETCALC_SO_FAR to "Contribution months to date",
    UiKey.RETCALC_SO_FAR_NOTE to "From your social insurance statement",
    UiKey.RETCALC_SOFAR_RANGE to "From 0 to 1200 months",
    UiKey.RETCALC_RETIRE to "The age you plan to retire at (optional)",
    UiKey.RETCALC_RETIRE_NOTE to "Empty = the statutory age",
    UiKey.RETCALC_RETIRE_NOTE_LEGAL to "Empty = your statutory age: {0}",
    UiKey.RETCALC_MANY_JOBS to "You have more than one current job in your income sources — enter your wage yourself",
    UiKey.RETCALC_SEC_LIVING to "What you want to live on",
    UiKey.RETCALC_WANT to "The monthly amount you want to live on",
    UiKey.RETCALC_YEARS to "How many years should the retirement money last?",
    UiKey.RETCALC_YEARS_NOTE to "Required — there is no default for it",
    UiKey.RETCALC_HAVE to "How much do you have for retirement now?",
    UiKey.RETCALC_HAVE_NOTE to "Empty = zero",
    UiKey.RETSA_QUESTION to "Did you join social insurance before July 2024?",
    UiKey.RETSA_LAW_LINE_OLD to "Old system (M/33) — retirement age from the table in clause Five of decree M/273",
    UiKey.RETSA_LAW_LINE_NEW to "New system (M/273) — statutory age 65",
    UiKey.RETSA_LAW_OLD to "Old system",
    UiKey.RETSA_LAW_NEW to "New system",
    UiKey.RETSA_HERO_LABEL to "Expected monthly pension",
    UiKey.RETSA_HERO_SUB to "{0}, retiring at {1} in {2}, {3} contribution months",
    UiKey.RETSA_AT_2024 to "Your contribution months on 3 July 2024",
    UiKey.RETSA_AT_2024_NOTE to "Your retirement age in the old system depends on it",
    UiKey.RETSA_M_1422 to "Of which before 1422 AH (optional)",
    UiKey.RETSA_M_1422_NOTE to "Counted over 600 instead of 480",
    UiKey.RETSA_SEC_WAGE to "Your contributory wage",
    UiKey.RETSA_BASIC to "Basic monthly wage",
    UiKey.RETSA_BASIC_NOTE to "Enter your basic monthly wage",
    UiKey.RETSA_BASIC_NOTE_SUGGEST to "Empty = your salary in income sources ({0}) — edit it if it includes allowances",
    UiKey.RETSA_HOUSING to "Monthly housing allowance",
    UiKey.RETSA_HOUSING_NOTE to "Enter zero if you have no housing allowance",
    UiKey.RETSA_JOB to "Start of your current job",
    UiKey.RETSA_JOB_NOTE to "Pick the start date of your current job",
    UiKey.RETSA_JOB_NOTE_SUGGEST to "From income sources: {0} — change it if needed",
    UiKey.RETSA_EOS_WAGE to "Your full last wage",
    UiKey.RETSA_EOS_WAGE_NOTE to "Basic plus all allowances (Labor Law art. 2)",
    UiKey.RETSA_EOS_WAGE_NOTE_SUGGEST to "Empty = your salary in income sources ({0}) — basic plus all allowances (Labor Law art. 2)",
    UiKey.RETSA_END to "How will your job end?",
    UiKey.RETSA_END_NOTE to "Asked every time — resigning reduces the award (art. 85)",
    UiKey.RETSA_END_CONTRACT to "Contract end or age",
    UiKey.RETSA_END_RESIGN to "Resignation",
    UiKey.RETSA_END_ART80 to "Dismissal (art. 80)",
    UiKey.RETSA_HOW_NEW_WAGE to "Average wage (basic + housing, capped at 45,000): {0}",
    UiKey.RETSA_HOW_NEW_ACCRUED to "× 2.25% × {0} months ÷ 12 = {1}",
    UiKey.RETSA_HOW_CAPPED to " ← capped at 100% of the average",
    UiKey.RETSA_HOW_NEW_MIN to "Minimum for your service: {0}",
    UiKey.RETSA_HOW_NEW_REDUCE to "Early reduction: −{0} (3% per 12 months over {1} months — after the minimum, so it may go below it)",
    UiKey.RETSA_HOW_NEW_INCREASE to "Increase after the age: +{0} (3% per 12 months)",
    UiKey.RETSA_HOW_NEW_NONE to "No reduction or increase: retiring at the statutory age",
    UiKey.RETSA_HOW_OLD_WAGE to "Average wage of the last two years (basic + housing): {0}",
    UiKey.RETSA_HOW_OLD_ACCRUED to "× {0} ÷ 480 = {1}",
    UiKey.RETSA_HOW_OLD_ACCRUED_1422 to "× {0} ÷ 480 + {1} ÷ 600 = {2}",
    UiKey.RETSA_HOW_OLD_MIN to "Minimum {0}",
    UiKey.RETSA_HOW_OLD_AGE_FIFTH to "Your retirement age: {0} — from the table in clause Five of decree M/273",
    UiKey.RETSA_HOW_OLD_AGE_60 to "Your retirement age: {0} — clause Five does not apply to you",
    UiKey.RETSA_ASSUME to "Assumption: contributions and wage continue as they are until retirement, and savings earn no returns. An approximate planning estimate; the official figure comes from social insurance.",
    UiKey.RETSA_SOURCES to "Sources: Social Insurance Law (M/273) arts. 8, 16–17 and 26 and Council of Ministers decision 1022, the GOSI pension page (old system), Labor Law arts. 2, 84–85 and 87.",
)
