package app.masroufy.core

/**
 * نصوص أفكار المساعد الثمانية التانية (unusual · beforePayday · payFirst · billJump · dupSubs · bigOne · goalNear · weekly — §68):
 * فصحى · مصري · إنجليزي. نفس شروط `TextsAdvisor.kt`: `ALERT_LOCK_*` من غير أرقام، والعدّ بـ«مرات» مش أصناف (قرار المالك).
 */
internal val MSA_ADVISOR_MORE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ALERT_LOCK_UNUSUAL to "صرفك على أحد البنود أعلى من المعتاد بكثير هذا الشهر",
    TextKey.ALERT_LOCK_BEFORE_PAYDAY to "الراتب قريب ورصيدك منخفض — التفاصيل داخل التطبيق",
    TextKey.ALERT_LOCK_PAY_FIRST to "نزل الراتب — خصّص مبلغ خطتك قبل أن تصرف",
    TextKey.ALERT_LOCK_BILL_JUMP to "إحدى فواتيرك أعلى من المعتاد",
    TextKey.ALERT_LOCK_DUP_SUBS to "لديك اشتراكات متشابهة — راجعها داخل التطبيق",
    TextKey.ALERT_LOCK_BIG_ONE to "عملية كبيرة مقارنة بشهرك — التفاصيل داخل التطبيق",
    TextKey.ALERT_LOCK_GOAL_NEAR to "خبر جيد عن خطة ادخارك",
    TextKey.ALERT_LOCK_WEEKLY to "ملخص أسبوعك جاهز",
    TextKey.ALERT_WHY_UNUSUAL to "المتوقع لهذا البند أعلى من معتاده بوضوح",
    TextKey.ALERT_WHY_BEFORE_PAYDAY to "أيام قليلة على الراتب ورصيدك أقل مما تحتاجه حتى نزوله",
    TextKey.ALERT_WHY_PAY_FIRST to "نزل الراتب ولديك خطة ادخار",
    TextKey.ALERT_WHY_BILL_JUMP to "الفاتورة أعلى من دفعاتها المعتادة",
    TextKey.ALERT_WHY_DUP_SUBS to "لديك أكثر من اشتراك في التصنيف نفسه",
    TextKey.ALERT_WHY_BIG_ONE to "العملية كبيرة مقارنة بمصروف شهرك المعتاد",
    TextKey.ALERT_WHY_GOAL_NEAR to "خطتك قاربت على الاكتمال",
    TextKey.ALERT_WHY_WEEKLY to "ملخص الأسبوع الذي انتهى",
    TextKey.ADVISOR_UNUSUAL_TITLE to "«{0}» أعلى من المعتاد هذا الشهر",
    TextKey.ADVISOR_UNUSUAL_BODY to "{0} هذا الشهر {1} — بهذا المعدل {2} ({3})",
    TextKey.ADVISOR_RATIO_TRIPLE to "ثلاثة أضعاف المعتاد أو أكثر",
    TextKey.ADVISOR_RATIO_DOUBLE to "ضعف المعتاد أو أكثر",
    TextKey.ADVISOR_RATIO_ABOVE to "أعلى من المعتاد بوضوح",
    TextKey.ADVISOR_BEFORE_PAY_TITLE to "الراتب قريب",
    TextKey.ADVISOR_BEFORE_PAY_BODY to "الراتب بعد {0} يومًا ومعك {1}",
    TextKey.ADVISOR_BEFORE_NEXT_PAY_BODY to "القبض القادم بعد {0} يومًا ومعك {1}",
    TextKey.ADVISOR_BEFORE_PAY_DUES to "وعليك {0} مستحقات قبله",
    TextKey.ADVISOR_PAY_FIRST_TITLE to "نزل الراتب",
    TextKey.ADVISOR_PAY_FIRST_BODY to "نزل الراتب — حوّل {0} لخطة «{1}» قبل أن تصرف",
    TextKey.ADVISOR_BILL_JUMP_TITLE to "«{0}» أعلى من المعتاد",
    TextKey.ADVISOR_BILL_JUMP_BODY to "{0} {1} — أعلى من المعتاد ({2})",
    TextKey.ADVISOR_DUP_SUBS_TITLE to "لديك أكثر من اشتراك في «{0}»",
    TextKey.ADVISOR_DUP_SUBS_BODY to "{0} — هل تحتاجها كلها؟",
    TextKey.ADVISOR_BIG_ONE_TITLE to "عملية كبيرة يوم {0}",
    TextKey.ADVISOR_BIG_ONE_BODY to "عملية {0} — {1}",
    TextKey.ADVISOR_SHARE_FULL to "أكثر من مصروف شهر كامل",
    TextKey.ADVISOR_SHARE_HALF to "نصف مصروف شهرك أو أكثر",
    TextKey.ADVISOR_SHARE_QUARTER to "ربع مصروف شهرك أو أكثر",
    TextKey.ADVISOR_SHARE_FIFTH to "خُمس مصروف شهرك تقريبًا",
    TextKey.ADVISOR_GOAL_NEAR_TITLE to "خطة «{0}» قاربت على الاكتمال",
    TextKey.ADVISOR_GOAL_NEAR_BODY to "جمعت {0} من {1} — بقي {2}",
    TextKey.ADVISOR_GOAL_REACHED_TITLE to "أحسنت! اكتملت خطة «{0}»",
    TextKey.ADVISOR_GOAL_REACHED_BODY to "جمعت {0} من {1}",
    TextKey.ADVISOR_WEEKLY_TITLE to "ملخص أسبوعك",
    TextKey.ADVISOR_WEEKLY_SPENT to "صرفت {0} هذا الأسبوع",
    TextKey.ADVISOR_WEEKLY_MORE to "أكثر بـ{0} من الأسبوع الماضي",
    TextKey.ADVISOR_WEEKLY_LESS to "أقل بـ{0} من الأسبوع الماضي",
    TextKey.ADVISOR_WEEKLY_SAME to "مثل الأسبوع الماضي",
    TextKey.ADVISOR_WEEKLY_TOP to "الأعلى: «{0}» ({1})",
)

/** نفس المفاتيح بالمصري — لما البلد الشغالة مصر (§66). */
internal val EGYPTIAN_ADVISOR_MORE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ALERT_LOCK_UNUSUAL to "صرفك على بند أعلى من العادي بكتير الشهر ده",
    TextKey.ALERT_LOCK_BEFORE_PAYDAY to "المرتب قرّب ورصيدك قليل — التفاصيل جوه التطبيق",
    TextKey.ALERT_LOCK_PAY_FIRST to "المرتب نزل — حوّش مبلغ خطتك قبل ما تصرف",
    TextKey.ALERT_LOCK_BILL_JUMP to "فيه فاتورة أعلى من العادي",
    TextKey.ALERT_LOCK_DUP_SUBS to "عندك اشتراكات شبه بعض — بص عليها جوه التطبيق",
    TextKey.ALERT_LOCK_BIG_ONE to "عملية كبيرة بالنسبة لشهرك — التفاصيل جوه التطبيق",
    TextKey.ALERT_LOCK_GOAL_NEAR to "خبر حلو عن خطة الادخار",
    TextKey.ALERT_LOCK_WEEKLY to "ملخص أسبوعك جاهز",
    TextKey.ALERT_WHY_UNUSUAL to "المتوقع للبند ده أعلى من العادي بوضوح",
    TextKey.ALERT_WHY_BEFORE_PAYDAY to "فاضل أيام قليلة على المرتب ورصيدك أقل من اللي محتاجه لحده",
    TextKey.ALERT_WHY_PAY_FIRST to "المرتب نزل وعندك خطة ادخار",
    TextKey.ALERT_WHY_BILL_JUMP to "الفاتورة أعلى من دفعاتها العادية",
    TextKey.ALERT_WHY_DUP_SUBS to "عندك أكتر من اشتراك في نفس التصنيف",
    TextKey.ALERT_WHY_BIG_ONE to "العملية كبيرة بالنسبة لمصروف شهرك العادي",
    TextKey.ALERT_WHY_GOAL_NEAR to "خطتك قرّبت تكمل",
    TextKey.ALERT_WHY_WEEKLY to "ملخص الأسبوع اللي خلص",
    TextKey.ADVISOR_UNUSUAL_TITLE to "«{0}» أعلى من العادي الشهر ده",
    TextKey.ADVISOR_UNUSUAL_BODY to "{0} الشهر ده {1} — بالمعدل ده {2} ({3})",
    TextKey.ADVISOR_RATIO_TRIPLE to "تلات أضعاف العادي أو أكتر",
    TextKey.ADVISOR_RATIO_DOUBLE to "الضعف أو أكتر",
    TextKey.ADVISOR_RATIO_ABOVE to "أعلى من العادي بوضوح",
    TextKey.ADVISOR_BEFORE_PAY_TITLE to "المرتب قرّب",
    TextKey.ADVISOR_BEFORE_PAY_BODY to "المرتب كمان {0} يوم ومعاك {1}",
    TextKey.ADVISOR_BEFORE_NEXT_PAY_BODY to "القبض الجاي كمان {0} يوم ومعاك {1}",
    TextKey.ADVISOR_BEFORE_PAY_DUES to "وعليك {0} مستحقات قبله",
    TextKey.ADVISOR_PAY_FIRST_TITLE to "المرتب نزل",
    TextKey.ADVISOR_PAY_FIRST_BODY to "نزل المرتب — حوّل {0} لخطة «{1}» قبل ما تصرف",
    TextKey.ADVISOR_BILL_JUMP_TITLE to "«{0}» أعلى من العادي",
    TextKey.ADVISOR_BILL_JUMP_BODY to "{0} {1} — أعلى من العادي ({2})",
    TextKey.ADVISOR_DUP_SUBS_TITLE to "عندك أكتر من اشتراك في «{0}»",
    TextKey.ADVISOR_DUP_SUBS_BODY to "{0} — محتاجهم كلهم؟",
    TextKey.ADVISOR_BIG_ONE_TITLE to "عملية كبيرة يوم {0}",
    TextKey.ADVISOR_BIG_ONE_BODY to "عملية {0} — {1}",
    TextKey.ADVISOR_SHARE_FULL to "أكتر من مصروف شهر كامل",
    TextKey.ADVISOR_SHARE_HALF to "نص مصروف شهرك أو أكتر",
    TextKey.ADVISOR_SHARE_QUARTER to "ربع مصروف شهرك أو أكتر",
    TextKey.ADVISOR_SHARE_FIFTH to "حوالي خُمس مصروف شهرك",
    TextKey.ADVISOR_GOAL_NEAR_TITLE to "خطة «{0}» قرّبت تكمل",
    TextKey.ADVISOR_GOAL_NEAR_BODY to "جمعت {0} من {1} — فاضل {2}",
    TextKey.ADVISOR_GOAL_REACHED_TITLE to "برافو! خطة «{0}» كملت",
    TextKey.ADVISOR_GOAL_REACHED_BODY to "جمعت {0} من {1}",
    TextKey.ADVISOR_WEEKLY_TITLE to "ملخص أسبوعك",
    TextKey.ADVISOR_WEEKLY_SPENT to "صرفت {0} الأسبوع ده",
    TextKey.ADVISOR_WEEKLY_MORE to "أكتر بـ{0} من الأسبوع اللي فات",
    TextKey.ADVISOR_WEEKLY_LESS to "أقل بـ{0} من الأسبوع اللي فات",
    TextKey.ADVISOR_WEEKLY_SAME to "زي الأسبوع اللي فات",
    TextKey.ADVISOR_WEEKLY_TOP to "الأعلى: «{0}» ({1})",
)

internal val ENGLISH_ADVISOR_MORE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ALERT_LOCK_UNUSUAL to "Spending in one category is far above usual this month",
    TextKey.ALERT_LOCK_BEFORE_PAYDAY to "Payday is close and your balance is low — details inside the app",
    TextKey.ALERT_LOCK_PAY_FIRST to "Your salary arrived — set aside your plan's amount before spending",
    TextKey.ALERT_LOCK_BILL_JUMP to "One of your bills is higher than usual",
    TextKey.ALERT_LOCK_DUP_SUBS to "You have similar subscriptions — take a look inside the app",
    TextKey.ALERT_LOCK_BIG_ONE to "A large payment for your month — details inside the app",
    TextKey.ALERT_LOCK_GOAL_NEAR to "Good news about your savings plan",
    TextKey.ALERT_LOCK_WEEKLY to "Your weekly summary is ready",
    TextKey.ALERT_WHY_UNUSUAL to "This category is heading clearly above its usual level",
    TextKey.ALERT_WHY_BEFORE_PAYDAY to "A few days to payday and your balance is below what you need until then",
    TextKey.ALERT_WHY_PAY_FIRST to "Your salary arrived and you have a savings plan",
    TextKey.ALERT_WHY_BILL_JUMP to "The bill is higher than its usual payments",
    TextKey.ALERT_WHY_DUP_SUBS to "You have more than one subscription in the same category",
    TextKey.ALERT_WHY_BIG_ONE to "The payment is large compared with your usual monthly spending",
    TextKey.ALERT_WHY_GOAL_NEAR to "Your plan is close to complete",
    TextKey.ALERT_WHY_WEEKLY to "A summary of the week that ended",
    TextKey.ADVISOR_UNUSUAL_TITLE to "“{0}” is above usual this month",
    TextKey.ADVISOR_UNUSUAL_BODY to "{0} this month: {1} — at this rate {2} ({3})",
    TextKey.ADVISOR_RATIO_TRIPLE to "three times the usual or more",
    TextKey.ADVISOR_RATIO_DOUBLE to "double the usual or more",
    TextKey.ADVISOR_RATIO_ABOVE to "clearly above the usual",
    TextKey.ADVISOR_BEFORE_PAY_TITLE to "Payday is close",
    TextKey.ADVISOR_BEFORE_PAY_BODY to "Payday in {0} days and you have {1}",
    TextKey.ADVISOR_BEFORE_NEXT_PAY_BODY to "Next pay in {0} days and you have {1}",
    TextKey.ADVISOR_BEFORE_PAY_DUES to "and {0} in dues before it",
    TextKey.ADVISOR_PAY_FIRST_TITLE to "Your salary arrived",
    TextKey.ADVISOR_PAY_FIRST_BODY to "Salary is in — move {0} to “{1}” before you spend",
    TextKey.ADVISOR_BILL_JUMP_TITLE to "“{0}” is higher than usual",
    TextKey.ADVISOR_BILL_JUMP_BODY to "{0} {1} — higher than usual ({2})",
    TextKey.ADVISOR_DUP_SUBS_TITLE to "You have more than one subscription in “{0}”",
    TextKey.ADVISOR_DUP_SUBS_BODY to "{0} — do you need them all?",
    TextKey.ADVISOR_BIG_ONE_TITLE to "A large payment on {0}",
    TextKey.ADVISOR_BIG_ONE_BODY to "A payment of {0} — {1}",
    TextKey.ADVISOR_SHARE_FULL to "more than a whole month of your spending",
    TextKey.ADVISOR_SHARE_HALF to "half of your monthly spending or more",
    TextKey.ADVISOR_SHARE_QUARTER to "a quarter of your monthly spending or more",
    TextKey.ADVISOR_SHARE_FIFTH to "about a fifth of your monthly spending",
    TextKey.ADVISOR_GOAL_NEAR_TITLE to "“{0}” is almost complete",
    TextKey.ADVISOR_GOAL_NEAR_BODY to "You saved {0} of {1} — {2} to go",
    TextKey.ADVISOR_GOAL_REACHED_TITLE to "Well done! “{0}” is complete",
    TextKey.ADVISOR_GOAL_REACHED_BODY to "You saved {0} of {1}",
    TextKey.ADVISOR_WEEKLY_TITLE to "Your week",
    TextKey.ADVISOR_WEEKLY_SPENT to "You spent {0} this week",
    TextKey.ADVISOR_WEEKLY_MORE to "{0} more than last week",
    TextKey.ADVISOR_WEEKLY_LESS to "{0} less than last week",
    TextKey.ADVISOR_WEEKLY_SAME to "the same as last week",
    TextKey.ADVISOR_WEEKLY_TOP to "top: “{0}” ({1})",
)
