package app.masroufy.core

/**
 * نصوص «هتوصل لكام؟» + ملف المتوسطات (OVERRIDES §69.6): فصحى مختصرة للسعودية (§66) · مصري لمصر · إنجليزي (كتابة Claude ومستني
 * مراجعة المالك §40). كل «غير متاح» بيقول **إيه الناقص** (القاعدة 10)، وكل مصدر بيتكتب باسمه ورسمي ولا خاص.
 * سطر الجنيه بالمصري **بكلمة المالك** («جزء كبير من الزيادة سببه نزول الجنيه»).
 */
internal val MSA_GROWTH_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.GROWTH_YEARS_RANGE to "عدد السنوات من 0 إلى 100",
    TextKey.AVERAGES_BAD_VALUE to "النسبة ليست رقمًا صحيحًا بنقاط الأساس أو خارج الحدود",
    TextKey.AVERAGES_BAD_PERIOD to "الفترة غير صحيحة",
    TextKey.AVERAGES_NO_OFFICIAL_FLAG to "لم يُذكر هل المصدر رسمي أو خاص",
    TextKey.AVERAGES_BAD_KIND to "نوع السطر غير معروف (محسوب أو يدوي)",
    TextKey.AVERAGES_NO_REVIEW_DATE to "رقم يدوي بلا تاريخ مراجعة",
    TextKey.AVERAGES_SCHEMA_UNKNOWN to "نسخة ملف المتوسطات ({0}) غير مدعومة",
    TextKey.AVERAGES_NONE to "ملف المتوسطات بلا متوسطات",
    TextKey.GROWTH_NOTE_EGP to "جزء كبير من الزيادة سببه انخفاض الجنيه",
    TextKey.GROWTH_NOTE_EGP_DETAIL to "انخفض الجنيه أمام الدولار {0} سنويًا في المتوسط ({1}–{2})، وبالدولار تكون الزيادة {3} سنويًا",
    TextKey.GROWTH_NOTE_EGP_FALL to "انخفض الجنيه أمام الدولار {0} سنويًا في المتوسط ({1}–{2})",
    TextKey.GROWTH_NA_COUNTRY to "غير متاح: لا توجد متوسطات لهذا البلد بعد",
    TextKey.GROWTH_NA_NO_FILE to "غير متاح: ملف المتوسطات لم يصل بعد",
    TextKey.GROWTH_NA_MISSING to "غير متاح: هذا المتوسط غير موجود في الملف — اكتب النسبة بنفسك",
    TextKey.GROWTH_TYPE_BANK_RATE to "اكتب فائدة بنكك على الوديعة",
    TextKey.GROWTH_TYPE_YOUR_RATE to "اكتب النسبة السنوية التي تتوقعها",
    TextKey.GROWTH_NA_INFLATION to "«بقيمة المال اليوم» غير متاح: معدل التضخم الرسمي غير معروف",
    TextKey.GROWTH_YOUR_RATE to "النسبة التي كتبتها أنت",
    TextKey.GROWTH_SRC_GOLD to "متوسط سعر الذهب الشهري — البنك الدولي",
    TextKey.GROWTH_SRC_GOLD_EGP to "سعر الذهب — البنك الدولي، بسعر الصرف الرسمي للجنيه",
    TextKey.GROWTH_SRC_EGP_RATE to "سعر الصرف الرسمي للجنيه — البنك الدولي",
    TextKey.GROWTH_SRC_CPI_SA to "التضخم — الهيئة العامة للإحصاء (عبر البنك الدولي)",
    TextKey.GROWTH_SRC_CPI_EG to "التضخم — الجهاز المركزي للتعبئة العامة والإحصاء (عبر البنك الدولي)",
    TextKey.GROWTH_SRC_STOCKS_SA to "مؤشر MSCI للسوق السعودية مع التوزيعات",
    TextKey.GROWTH_SRC_STOCKS_EG to "مؤشر EGX30 للبورصة المصرية (السعر فقط، دون التوزيعات)",
    TextKey.GROWTH_SRC_POLICY_SA to "البنك المركزي السعودي — سعر إعادة الشراء المعاكس",
    TextKey.GROWTH_SRC_POLICY_EG to "البنك المركزي المصري — عائد الإيداع لليلة واحدة",
    TextKey.GROWTH_SRC_RE_INDEX_SA to "مؤشر أسعار العقارات السكنية — الهيئة العامة للإحصاء",
    TextKey.GROWTH_SRC_RE_INDEX_EG to "مؤشر أسعار عقارماب (موقع عقارات)",
    TextKey.GROWTH_SRC_CASH to "النقد في البيت لا يزيد",
    TextKey.GROWTH_OFFICIAL to "رسمي",
    TextKey.GROWTH_PRIVATE to "خاص (غير رسمي)",
    TextKey.GROWTH_NEWS_SOURCED to "منقول من خبر صحفي",
    TextKey.GROWTH_MANUAL_REVIEWED to "رقم يدوي — رُوجع في {0}",
    TextKey.GROWTH_STALE to "قديم: آخر تحديث لم ينجح — الرقم من {0}",
    TextKey.GROWTH_CLASS_GOLD to "ذهب",
    TextKey.GROWTH_CLASS_REAL_ESTATE to "عقار",
    TextKey.GROWTH_CLASS_DEPOSIT to "وديعة في البنك",
    TextKey.GROWTH_CLASS_LOCAL_STOCKS to "أسهم السوق المحلي",
    TextKey.GROWTH_CLASS_CASH to "نقد في البيت",
    TextKey.GROWTH_VALUATION_UNKNOWN to "طريقة قيمة العقار «{0}» غير معروفة",
    TextKey.GROWTH_PRICE_SQM_POSITIVE to "سعر المتر يكون أكبر من صفر",
    TextKey.GROWTH_RENT_NOT_NEGATIVE to "الإيجار لا يكون سالبًا",
    TextKey.GROWTH_VACANT_RANGE to "الأشهر الفارغة في السنة من 0 إلى 12",
    TextKey.GROWTH_NA_ASSET_VALUE to "قيمة الأصل اليوم غير متاحة: اكتب سعره، أو المساحة وسعر المتر",
    TextKey.GROWTH_NA_ASSET_COST to "المكسب منذ الشراء غير متاح: سجّل سعر الشراء وتاريخه",
    TextKey.GROWTH_NA_ASSET_RATE to "القيمة عند البيع غير متاحة: اكتب الزيادة السنوية التي تتوقعها",
    TextKey.GROWTH_SELL_YEAR_RANGE to "سنة البيع من {0} إلى {1}",
    TextKey.GROWTH_AREA_NEEDS_REAL_ESTATE to "المساحة وسعر المتر للعقار فقط — اختر طريقة قيمة العقار أولًا",
    TextKey.GROWTH_AREA_POSITIVE to "المساحة تكون أكبر من صفر",
    TextKey.GROWTH_NOT_AREA_VALUED to "قيمة هذا العقار مكتوبة كاملة وليست بسعر المتر",
)

internal val EGYPTIAN_GROWTH_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.GROWTH_YEARS_RANGE to "عدد السنين من 0 لـ100",
    TextKey.AVERAGES_BAD_VALUE to "النسبة مش رقم صحيح بنقاط الأساس أو برا الحدود",
    TextKey.AVERAGES_BAD_PERIOD to "الفترة مش صح",
    TextKey.AVERAGES_NO_OFFICIAL_FLAG to "مش مكتوب المصدر رسمي ولا خاص",
    TextKey.AVERAGES_BAD_KIND to "نوع السطر مش معروف (محسوب ولا يدوي)",
    TextKey.AVERAGES_NO_REVIEW_DATE to "رقم يدوي من غير تاريخ مراجعة",
    TextKey.AVERAGES_SCHEMA_UNKNOWN to "نسخة ملف المتوسطات ({0}) مش مدعومة",
    TextKey.AVERAGES_NONE to "ملف المتوسطات مفيهوش متوسطات",
    TextKey.GROWTH_NOTE_EGP to "جزء كبير من الزيادة سببه نزول الجنيه",
    TextKey.GROWTH_NOTE_EGP_DETAIL to "الجنيه نزل قدام الدولار {0} في السنة في المتوسط ({1}–{2})، وبالدولار الزيادة {3} في السنة",
    TextKey.GROWTH_NOTE_EGP_FALL to "الجنيه نزل قدام الدولار {0} في السنة في المتوسط ({1}–{2})",
    TextKey.GROWTH_NA_COUNTRY to "غير متاح: لسه مفيش متوسطات للبلد دي",
    TextKey.GROWTH_NA_NO_FILE to "غير متاح: ملف المتوسطات لسه ما وصلش",
    TextKey.GROWTH_NA_MISSING to "غير متاح: المتوسط ده مش موجود في الملف — اكتب النسبة بنفسك",
    TextKey.GROWTH_TYPE_BANK_RATE to "اكتب فايدة بنكك على الوديعة",
    TextKey.GROWTH_TYPE_YOUR_RATE to "اكتب النسبة السنوية اللي متوقعها",
    TextKey.GROWTH_NA_INFLATION to "«بقيمة فلوس النهارده» غير متاح: التضخم الرسمي مش معروف",
    TextKey.GROWTH_YOUR_RATE to "النسبة اللي إنت كتبتها",
    TextKey.GROWTH_SRC_GOLD to "متوسط سعر الذهب الشهري — البنك الدولي",
    TextKey.GROWTH_SRC_GOLD_EGP to "سعر الذهب — البنك الدولي، بسعر الصرف الرسمي للجنيه",
    TextKey.GROWTH_SRC_EGP_RATE to "سعر الصرف الرسمي للجنيه — البنك الدولي",
    TextKey.GROWTH_SRC_CPI_SA to "التضخم — الهيئة العامة للإحصاء (عن طريق البنك الدولي)",
    TextKey.GROWTH_SRC_CPI_EG to "التضخم — الجهاز المركزي للتعبئة العامة والإحصاء (عن طريق البنك الدولي)",
    TextKey.GROWTH_SRC_STOCKS_SA to "مؤشر MSCI للسوق السعودي مع التوزيعات",
    TextKey.GROWTH_SRC_STOCKS_EG to "مؤشر EGX30 للبورصة المصرية (السعر بس، من غير التوزيعات)",
    TextKey.GROWTH_SRC_POLICY_SA to "البنك المركزي السعودي — سعر إعادة الشراء المعاكس",
    TextKey.GROWTH_SRC_POLICY_EG to "البنك المركزي المصري — عائد الإيداع لليلة واحدة",
    TextKey.GROWTH_SRC_RE_INDEX_SA to "مؤشر أسعار العقارات السكنية — الهيئة العامة للإحصاء",
    TextKey.GROWTH_SRC_RE_INDEX_EG to "مؤشر أسعار عقارماب (موقع عقارات)",
    TextKey.GROWTH_SRC_CASH to "الكاش في البيت ما بيزيدش",
    TextKey.GROWTH_OFFICIAL to "رسمي",
    TextKey.GROWTH_PRIVATE to "خاص (مش رسمي)",
    TextKey.GROWTH_NEWS_SOURCED to "منقول من خبر صحفي",
    TextKey.GROWTH_MANUAL_REVIEWED to "رقم يدوي — اتراجع يوم {0}",
    TextKey.GROWTH_STALE to "قديم: آخر تحديث ما نجحش — الرقم من {0}",
    TextKey.GROWTH_CLASS_GOLD to "ذهب",
    TextKey.GROWTH_CLASS_REAL_ESTATE to "عقار",
    TextKey.GROWTH_CLASS_DEPOSIT to "وديعة في البنك",
    TextKey.GROWTH_CLASS_LOCAL_STOCKS to "أسهم السوق المحلي",
    TextKey.GROWTH_CLASS_CASH to "كاش في البيت",
    TextKey.GROWTH_VALUATION_UNKNOWN to "طريقة قيمة العقار «{0}» مش معروفة",
    TextKey.GROWTH_PRICE_SQM_POSITIVE to "سعر المتر لازم يبقى أكبر من صفر",
    TextKey.GROWTH_RENT_NOT_NEGATIVE to "الإيجار ما ينفعش يبقى بالسالب",
    TextKey.GROWTH_VACANT_RANGE to "الشهور الفاضية في السنة من 0 لـ12",
    TextKey.GROWTH_NA_ASSET_VALUE to "قيمة الأصل النهارده غير متاحة: اكتب سعره، أو المساحة وسعر المتر",
    TextKey.GROWTH_NA_ASSET_COST to "المكسب من يوم الشراء غير متاح: سجّل سعر الشراء وتاريخه",
    TextKey.GROWTH_NA_ASSET_RATE to "القيمة وقت البيع غير متاحة: اكتب الزيادة السنوية اللي متوقعها",
    TextKey.GROWTH_SELL_YEAR_RANGE to "سنة البيع من {0} لـ{1}",
    TextKey.GROWTH_AREA_NEEDS_REAL_ESTATE to "المساحة وسعر المتر للعقار بس — اختار طريقة قيمة العقار الأول",
    TextKey.GROWTH_AREA_POSITIVE to "المساحة لازم تبقى أكبر من صفر",
    TextKey.GROWTH_NOT_AREA_VALUED to "العقار ده قيمته مكتوبة كلها مش بسعر المتر",
)

internal val ENGLISH_GROWTH_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.GROWTH_YEARS_RANGE to "Years from 0 to 100",
    TextKey.AVERAGES_BAD_VALUE to "The rate isn't a whole number of basis points, or it's out of range",
    TextKey.AVERAGES_BAD_PERIOD to "The period isn't valid",
    TextKey.AVERAGES_NO_OFFICIAL_FLAG to "It doesn't say whether the source is official or private",
    TextKey.AVERAGES_BAD_KIND to "Unknown line type (computed or manual)",
    TextKey.AVERAGES_NO_REVIEW_DATE to "A manual figure without a review date",
    TextKey.AVERAGES_SCHEMA_UNKNOWN to "Averages file version ({0}) isn't supported",
    TextKey.AVERAGES_NONE to "The averages file has no averages",
    TextKey.GROWTH_NOTE_EGP to "A big part of the increase comes from the pound falling",
    TextKey.GROWTH_NOTE_EGP_DETAIL to "The pound fell {0} a year against the dollar on average ({1}–{2}); in dollars the increase is {3} a year",
    TextKey.GROWTH_NOTE_EGP_FALL to "The pound fell {0} a year against the dollar on average ({1}–{2})",
    TextKey.GROWTH_NA_COUNTRY to "Not available: no averages for this country yet",
    TextKey.GROWTH_NA_NO_FILE to "Not available: the averages file hasn't arrived yet",
    TextKey.GROWTH_NA_MISSING to "Not available: this average isn't in the file — enter the rate yourself",
    TextKey.GROWTH_TYPE_BANK_RATE to "Enter your bank's deposit rate",
    TextKey.GROWTH_TYPE_YOUR_RATE to "Enter the yearly rate you expect",
    TextKey.GROWTH_NA_INFLATION to "“In today's money” isn't available: the official inflation rate isn't known",
    TextKey.GROWTH_YOUR_RATE to "The rate you entered",
    TextKey.GROWTH_SRC_GOLD to "Monthly average gold price — World Bank",
    TextKey.GROWTH_SRC_GOLD_EGP to "Gold price — World Bank, at the official pound exchange rate",
    TextKey.GROWTH_SRC_EGP_RATE to "Official pound exchange rate — World Bank",
    TextKey.GROWTH_SRC_CPI_SA to "Inflation — General Authority for Statistics (via the World Bank)",
    TextKey.GROWTH_SRC_CPI_EG to "Inflation — CAPMAS (via the World Bank)",
    TextKey.GROWTH_SRC_STOCKS_SA to "MSCI Saudi Arabia index with dividends",
    TextKey.GROWTH_SRC_STOCKS_EG to "EGX30 Egyptian exchange index (price only, without dividends)",
    TextKey.GROWTH_SRC_POLICY_SA to "Saudi Central Bank — reverse repo rate",
    TextKey.GROWTH_SRC_POLICY_EG to "Central Bank of Egypt — overnight deposit rate",
    TextKey.GROWTH_SRC_RE_INDEX_SA to "Residential real estate price index — General Authority for Statistics",
    TextKey.GROWTH_SRC_RE_INDEX_EG to "Aqarmap price index (property website)",
    TextKey.GROWTH_SRC_CASH to "Cash at home doesn't grow",
    TextKey.GROWTH_OFFICIAL to "official",
    TextKey.GROWTH_PRIVATE to "private (not official)",
    TextKey.GROWTH_NEWS_SOURCED to "taken from a news report",
    TextKey.GROWTH_MANUAL_REVIEWED to "manual figure — reviewed on {0}",
    TextKey.GROWTH_STALE to "old: the last update failed — figure from {0}",
    TextKey.GROWTH_CLASS_GOLD to "Gold",
    TextKey.GROWTH_CLASS_REAL_ESTATE to "Real estate",
    TextKey.GROWTH_CLASS_DEPOSIT to "Bank deposit",
    TextKey.GROWTH_CLASS_LOCAL_STOCKS to "Local stocks",
    TextKey.GROWTH_CLASS_CASH to "Cash at home",
    TextKey.GROWTH_VALUATION_UNKNOWN to "Unknown property valuation “{0}”",
    TextKey.GROWTH_PRICE_SQM_POSITIVE to "The price per square metre must be more than zero",
    TextKey.GROWTH_RENT_NOT_NEGATIVE to "Rent can't be negative",
    TextKey.GROWTH_VACANT_RANGE to "Empty months per year are from 0 to 12",
    TextKey.GROWTH_NA_ASSET_VALUE to "Today's value isn't available: enter its price, or the area and the price per square metre",
    TextKey.GROWTH_NA_ASSET_COST to "The gain since purchase isn't available: record the purchase price and date",
    TextKey.GROWTH_NA_ASSET_RATE to "The value at sale isn't available: enter the yearly increase you expect",
    TextKey.GROWTH_SELL_YEAR_RANGE to "The sale year is from {0} to {1}",
    TextKey.GROWTH_AREA_NEEDS_REAL_ESTATE to "Area and price per square metre are for property only — choose how the property is valued first",
    TextKey.GROWTH_AREA_POSITIVE to "The area must be more than zero",
    TextKey.GROWTH_NOT_AREA_VALUED to "This property's value is entered as a whole, not by the square metre",
)
