package app.masroufy.core

/** منطقة «الأشخاص» بالمصري (مصر) — العام · الأشخاص · «ليك/عليك» · ملف الشخص · شخص جديد · الديون القديمة. */
internal val EGYPTIAN_PEOPLE_AREA_1: Map<TextKey, String> = mapOf(
    // ── العام في المنطقة
    TextKey.PPL_AGO_DAYS to "من {0}",
    TextKey.PPL_IN_DAYS to "بعد {0}",
    TextKey.PPL_ARCHIVED to "متأرشف",
    TextKey.PPL_CANCEL to "إلغاء",
    TextKey.PPL_DASH to "—",
    TextKey.PPL_DATE_INVALID to "تاريخ المناسبة مش صالح.",
    TextKey.PPL_DATE_WITH_YEAR to "{0} {1}",
    TextKey.PPL_DAYS_ONE to "يوم",
    TextKey.PPL_DAYS_TWO to "يومين",
    TextKey.PPL_DAYS_FEW to "{0} أيام",
    TextKey.PPL_DAYS_MANY to "{0} يوم",
    TextKey.PPL_DAY_LABEL to "اليوم",
    TextKey.PPL_GIFTS_ONE to "نقطة واحدة",
    TextKey.PPL_GIFTS_TWO to "نقطتين",
    TextKey.PPL_GIFTS_TWO_OBJ to "نقطتين",
    TextKey.PPL_GIFTS_FEW to "{0} نقاط",
    TextKey.PPL_GIFTS_MANY to "{0} نقطة",
    TextKey.PPL_HOST_OF to "ل{0}",
    TextKey.PPL_ITEMS_ONE to "بند واحد",
    TextKey.PPL_ITEMS_TWO to "بندين",
    TextKey.PPL_ITEMS_TWO_OBJ to "بندين",
    TextKey.PPL_ITEMS_FEW to "{0} بنود",
    TextKey.PPL_ITEMS_MANY to "{0} بند",
    TextKey.PPL_LOAD_FAILED to "ما عرفناش نحمّل.",
    TextKey.PPL_MINE to "حدثك",
    TextKey.PPL_MONTH_LABEL to "الشهر (ميلادي)",
    TextKey.PPL_NOT_BUILT to "لسه ما اشتغلتش — جاية في خطوة بعدين.",
    TextKey.PPL_ONCE_NEEDS_YEAR to "المناسبة اللي مرة واحدة محتاجة السنة.",
    TextKey.PPL_OPS_ONE to "عملية واحدة",
    TextKey.PPL_OPS_TWO to "عمليتين",
    TextKey.PPL_OPS_TWO_OBJ to "عمليتين",
    TextKey.PPL_OPS_FEW to "{0} عمليات",
    TextKey.PPL_OPS_MANY to "{0} عملية",
    TextKey.PPL_OPTIONAL to "اختياري",
    TextKey.PPL_PEOPLE_ONE to "شخص واحد",
    TextKey.PPL_PEOPLE_TWO to "شخصين",
    TextKey.PPL_PEOPLE_FEW to "{0} أشخاص",
    TextKey.PPL_PEOPLE_MANY to "{0} شخص",
    TextKey.PPL_PERCENT to "{0}%",
    TextKey.PPL_PERCENT_SIGN to "%",
    TextKey.PPL_PICK_DATE to "اختار التاريخ",
    TextKey.PPL_REMOVE_NAMED to "شيل {0}",
    TextKey.PPL_REMOVE_ROW to "شيل السطر",
    TextKey.PPL_RETRY to "جرّب تاني",
    TextKey.PPL_SAR_ONLY to "الدين القديم بالريال بس دلوقتي — لسه ما اشتغلش بعملة البلد دي.",
    TextKey.PPL_SAVE to "احفظ",
    TextKey.PPL_SAVED to "اتحفظ التعديل",
    TextKey.PPL_SAVE_EDIT to "احفظ التعديل",
    TextKey.PPL_SEP to "، ",
    TextKey.PPL_SWITCH_OFF to "مقفول",
    TextKey.PPL_SWITCH_ON to "شغّال",
    TextKey.PPL_TXN_NO_NAME to "عملية من غير اسم",
    TextKey.PPL_YEAR to "السنة",
    TextKey.PPL_YEAR_OPTIONAL to "السنة (مش لازم)",
    TextKey.PPL_YEAR_UNKNOWN to "مش عارف",
    // ── الأشخاص (People)
    TextKey.PEOPLE_ADD to "إضافة",
    TextKey.PEOPLE_ADD_PERSON to "ضيف شخص",
    TextKey.PEOPLE_ALL to "الكل ({0})",
    TextKey.PEOPLE_BACK to "رجوع",
    TextKey.PEOPLE_CHARACTER_SLOT to "مكان الكاركتر بتاعك",
    TextKey.PEOPLE_CHIP_OWE to "عليك {0}",
    TextKey.PEOPLE_CHIP_OWED to "ليك {0}",
    TextKey.PEOPLE_EMPTY_TITLE to "لسه ما ضفتش حد",
    TextKey.PEOPLE_EMPTY_BODY to "ضيف اللي بتتعامل معاهم عشان تتابع اللي ليك واللي عليك.",
    TextKey.PEOPLE_ERROR_TITLE to "ما عرفناش نحمّل الأرصدة",
    TextKey.PEOPLE_ERROR_BODY to "الأشخاص ظاهرين، والأرقام هتظهر بعد التحديث.",
    TextKey.PEOPLE_EVENTS to "الأحداث",
    TextKey.PEOPLE_ORBIT_NOTE to "اللي ليهم أرصدة الأول",
    TextKey.PEOPLE_OWED_BOX to "ليك",
    TextKey.PEOPLE_OWE_BOX to "عليك",
    TextKey.PEOPLE_OWED_COUNT to "عند {0}",
    TextKey.PEOPLE_OWE_COUNT to "لـ{0}",
    TextKey.PEOPLE_OWE_TWO to "لاتنين",
    TextKey.PEOPLE_YOU to "إنت",
    // ── ليك · عليك (OwedToYou · YouOwe)
    TextKey.OWED_TITLE_OWED to "ليك",
    TextKey.OWED_TITLE_OWE to "عليك",
    TextKey.OWED_TOTAL_OWED to "مجموع اللي ليك",
    TextKey.OWED_TOTAL_OWE to "مجموع اللي عليك",
    TextKey.OWED_SUB_OWED to "عند {0}، من غير مقاصة مع «عليك»",
    TextKey.OWED_SUB_OWE to "لـ{0}، من غير مقاصة مع «ليك»",
    TextKey.OWED_ORDER_NOTE to "الأهم الأول: اللي ميعاده فات، وبعده اللي ميعاده قرّب",
    TextKey.OWED_FOOT to "اضغط على أي حد عشان تشوف السجل بينكم وتسجّل سداد.",
    TextKey.OWED_EMPTY_OWED to "مفيش حد عليه ليك حاجة.",
    TextKey.OWED_EMPTY_OWE to "مفيش عليك حاجة لحد.",
    TextKey.OWED_DUE_ON to "ميعادها {0}",
    TextKey.OWED_NO_DUE to "من غير ميعاد",
    TextKey.OWED_REASON_OPENING to "دين قديم",
    TextKey.OWED_REASON_RECEIVABLE to "سلفة أو نصيب دفعته عنه",
    TextKey.OWED_REASON_LOAN to "سلفة منه",
    TextKey.OWED_REASON_CUSTODY to "أمانة عندك",
    TextKey.OWED_SIGNAL_OVERDUE to "ميعادها فات من {0}",
    TextKey.OWED_SIGNAL_SOON to "ميعادها قرّب، {0}",
    // ── ملف الشخص (PersonProfile)
    TextKey.PERSON_PAGE_LAK to "ليك عنده",
    TextKey.PERSON_PAGE_ALEK to "عليك ليه",
    TextKey.PERSON_PAGE_NOTHING to "ولا حاجة",
    TextKey.PERSON_PAGE_NO_NETTING to "من غير مقاصة بين الرقمين",
    TextKey.PERSON_PAGE_NOT_FOUND to "الشخص مش موجود.",
    TextKey.PERSON_PAGE_TOGETHER to "اعملوا سوا",
    TextKey.PERSON_PAGE_ACT_ROSCA to "جمعية",
    TextKey.PERSON_PAGE_ACT_PROJECT to "مشروع مشترك",
    TextKey.PERSON_PAGE_ACT_LINK to "طلب اتصال",
    TextKey.PERSON_PAGE_ACT_SPLIT to "تقسيم فاتورة",
    TextKey.PERSON_PAGE_FUTURE to "قريب: لما {0} يستخدم مصروفي، هتقدروا تبنوا حاجات سوا من الحسابين.",
    TextKey.PERSON_PAGE_ROSCA_TITLE to "جمعية مع {0}",
    TextKey.PERSON_PAGE_ROSCA_BODY to "حدّد القسط الشهري، وهتتسجّل الجمعية عندك. الدعوة بتوصل لـ{0} لما ربط الحسابات يشتغل.",
    TextKey.PERSON_PAGE_ROSCA_AMOUNT to "القسط الشهري",
    TextKey.PERSON_PAGE_ROSCA_GO to "سجّل الجمعية",
    TextKey.PERSON_PAGE_PROJECT_TITLE to "مشروع مع {0}",
    TextKey.PERSON_PAGE_PROJECT_BODY to "افتح مشروع تجمع فيه مصاريفكم المشتركة، وكل واحد يشوف نصيبه.",
    TextKey.PERSON_PAGE_PROJECT_GO to "اعمل المشروع",
    TextKey.PERSON_PAGE_LINK_TITLE to "اربط حسابك بحساب {0}",
    TextKey.PERSON_PAGE_LINK_BODY to "لما تتربطوا، السلف والفواتير بتتسجّل عندكم انتم الاتنين مرة واحدة.",
    TextKey.PERSON_PAGE_LINK_GO to "ابعت الطلب",
    TextKey.PERSON_PAGE_LINK_NOTE to "محتاج ربط الحسابات، وده جاي في مرحلة بعدين.",
    TextKey.PERSON_PAGE_SPLIT_TITLE to "قسّم فاتورة مع {0}",
    TextKey.PERSON_PAGE_SPLIT_BODY to "اكتب مبلغ الفاتورة، وهتتقسم بالتساوي بينك وبينه، ونصيبه يتسجّل في «ليك».",
    TextKey.PERSON_PAGE_SPLIT_AMOUNT to "مبلغ الفاتورة",
    TextKey.PERSON_PAGE_SPLIT_GO to "سجّل التقسيم",
    TextKey.PERSON_PAGE_HISTORY to "السجل بينكم",
    TextKey.PERSON_PAGE_HISTORY_EMPTY to "مفيش ديون مفتوحة بينكم.",
    TextKey.PERSON_PAGE_DEBT_RECEIVABLE to "سلفة منك",
    TextKey.PERSON_PAGE_DEBT_LOAN to "سلفة منه",
    TextKey.PERSON_PAGE_DEBT_CUSTODY to "أمانة منه",
    TextKey.PERSON_PAGE_REMAINING to "فاضل {0} من {1}",
    TextKey.PERSON_PAGE_BADGES to "النقوط بينكم",
    // ── شخص جديد (AddPersonSheet)
    TextKey.ADD_PERSON_TITLE to "شخص جديد",
    TextKey.ADD_PERSON_NAME to "الاسم",
    TextKey.ADD_PERSON_NAME_PH to "زي ما بتناديه",
    TextKey.ADD_PERSON_CIRCLE to "الدايرة (اختياري)",
    TextKey.ADD_PERSON_REL to "يقربلك إيه؟ (اختياري)",
    TextKey.ADD_PERSON_REL_PH to "مثلًا: أخويا، زميلي في الشغل",
    TextKey.ADD_PERSON_OCC to "مناسبة ليه",
    TextKey.ADD_PERSON_OCC_NOTE_ONCE to "مرة واحدة، وهنفكّرك قبلها بأسبوع.",
    TextKey.ADD_PERSON_OCC_NOTE_YEARLY to "كل سنة، وهنفكّرك قبلها بأسبوع — وتقدر تغيّر ده من ملفه.",
    TextKey.ADD_PERSON_DEBT to "دين قديم بينكم",
    TextKey.ADD_PERSON_SIDE_LAK to "ليا عنده",
    TextKey.ADD_PERSON_SIDE_ALEK to "عليا ليه",
    TextKey.ADD_PERSON_AMOUNT to "المبلغ",
    TextKey.ADD_PERSON_DEBT_NOTE to "من غير عملية، وما بيلمسش أي محفظة ولا المصروف ولا الدخل.",
    TextKey.ADD_PERSON_SAVE to "ضيفه",
    TextKey.ADD_PERSON_ADDED to "اتضاف {0}",
    TextKey.ADD_PERSON_NEED_NAME to "اكتب اسم الشخص.",
    TextKey.ADD_PERSON_NEED_MONTH to "اختار شهر المناسبة، أو اقفل خانتها.",
    TextKey.ADD_PERSON_NEED_SIDE to "اختار: ليك عنده ولا عليك ليه.",
    TextKey.ADD_PERSON_NEED_AMOUNT to "اكتب مبلغ الدين أكبر من صفر، أو اقفل خانته.",
    // ── الديون القديمة (ProfileDebtSheet)
    TextKey.PROFILE_DEBT_TITLE to "ضيف الديون القديمة",
    TextKey.PROFILE_DEBT_NOTE to "بتظهر في الأشخاص وتتسدد عادي، ومش بتدخل في المصروف ولا الدخل ولا رصيد الكاش.",
    TextKey.PROFILE_DEBT_WHO to "مين؟",
    TextKey.PROFILE_DEBT_NEW to "أو اكتب اسم شخص جديد",
    TextKey.PROFILE_DEBT_DIR_LAK to "ليك عنده",
    TextKey.PROFILE_DEBT_DIR_ALEK to "عليك ليه",
    TextKey.PROFILE_DEBT_HOW_MUCH_LAK to "ليك عنده كام؟",
    TextKey.PROFILE_DEBT_HOW_MUCH_ALEK to "عليك ليه كام؟",
    TextKey.PROFILE_DEBT_NEED_NAME to "اكتب اسم كل شخص",
    TextKey.PROFILE_DEBT_NEED_AMOUNT_OF to "مبلغ دين «{0}» لازم يكون أكبر من صفر",
    TextKey.PROFILE_DEBT_NEED_AMOUNT to "المبلغ لازم يكون أكبر من صفر",
    TextKey.PROFILE_DEBT_ADD_ANOTHER to "ضيف شخص تاني",
    TextKey.PROFILE_DEBT_DONE to "تمام",
)
