package app.masroufy.core

/** «العمليات» بالإنجليزي (كتابة Claude — مستني مراجعة المالك §40) — الجزء التالت: زون التحويلات · «من هذا؟» · التحويل لنفسك بين البلدين. */
internal val ENGLISH_OPERATIONS_TRANSFER_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.TRANSFERS_TITLE to "Transfers",
    TextKey.TRANSFERS_INTRO to "For everyone you send money to or get money from: say who they are once, and past and future transfers are set automatically.",
    TextKey.TRANSFERS_WAITING to "Waiting for you",
    TextKey.TRANSFERS_UNDECIDED to "No decision",
    TextKey.TRANSFERS_DECIDED to "Decided",
    TextKey.TRANSFERS_IN_MONTH to "{0} in {1}",
    TextKey.TRANSFERS_META to "{0}, last on {1}",
    TextKey.TRANSFERS_LAST4 to "•••• {0}",
    TextKey.TRANSFERS_PERSON_CHIP to "Person: {0}",
    TextKey.TRANSFERS_HINT_ASK to "Person: their transfers are recorded on them, and we ask the type of each one (loan or support…).",
    TextKey.TRANSFERS_HINT_OWN to "All their transfers are now between your wallets, neither income nor spending.",
    TextKey.TRANSFERS_HINT_UNDO to "Undoing the decision brings the question back.",
    TextKey.TRANSFERS_PERSON to "Person",
    TextKey.TRANSFERS_FORGET to "Undo decision",
    TextKey.TRANSFERS_DONE_OWN to "Fixed {0}: now between your wallets",
    TextKey.TRANSFERS_DONE_NOT to "Done, we won't ask about them again",
    TextKey.TRANSFERS_DONE_FORGET to "Decision undone: their transfers are «not set» again",
    TextKey.TRANSFERS_DONE_PERSON to "Linked to {0}",
    TextKey.TRANSFERS_DONE_PERSON_NEW to "Linked to {0} and added to your people",
    TextKey.TRANSFERS_PERSON_BODY to "Type a new person's name or pick one of your people.",
    TextKey.TRANSFERS_NEW_PERSON to "New person",
    TextKey.TRANSFERS_LINK to "Link",
    TextKey.TRANSFERS_NO_PARTY to "{0} with no party: no name or number in the bank file. They stay as they are, no guessing.",
    TextKey.TRANSFERS_EMPTY to "No transfers yet",
    TextKey.TRANSFERS_EMPTY_BODY to "When transfers arrive from bank messages or a statement, they show up here grouped by party.",
    TextKey.TRANSFERS_ERROR to "Couldn't load transfers",
    TextKey.TRANSFERS_COUNT_ONE to "1 transfer",
    TextKey.TRANSFERS_COUNT_TWO to "2 transfers",
    TextKey.TRANSFERS_COUNT_FEW to "{0} transfers",
    TextKey.TRANSFERS_COUNT_MANY to "{0} transfers",
    TextKey.TRANSFER_PARTY_ASK to "Who is this?",
    TextKey.TRANSFER_PARTY_NAME to "Name as received: {0}",
    TextKey.TRANSFER_PARTY_ACCOUNT to "Account ending {0}",
    TextKey.TRANSFER_PARTY_PERSON to "Someone I know",
    TextKey.TRANSFER_PARTY_OWN to "My other account",
    TextKey.TRANSFER_PARTY_NOT to "Not this",
    TextKey.TRANSFER_PARTY_UNDO to "Undo",
    TextKey.TRANSFER_PARTY_DONE_PERSON to "Linked to {0}, {1}",
    TextKey.TRANSFER_PARTY_ADDED to "{0} was added to your people.",
    TextKey.TRANSFER_PARTY_DONE_PERSON_BODY to "Any transfer from or to {0} is recorded on them automatically, and we ask its type every time (loan or support…).",
    TextKey.TRANSFER_PARTY_DONE_OWN to "Transfer between your wallets",
    TextKey.TRANSFER_PARTY_DONE_OWN_BODY to "Neither income nor spending. {0} from the same party were fixed too.",
    TextKey.TRANSFER_PARTY_DONE_NOT to "Done",
    TextKey.TRANSFER_PARTY_DONE_NOT_BODY to "We won't ask about this account again.",
    TextKey.TRANSFER_PARTY_WHO_TITLE to "Who owns {0}?",
    TextKey.TRANSFER_PARTY_KIND_TITLE to "This money is from {0}",
    TextKey.TRANSFER_PARTY_NEW_TITLE to "New person (name as received)",
    TextKey.TRANSFER_PARTY_NAME_LABEL to "Person's name",
    TextKey.TRANSFER_PARTY_OR to "Or one of your people",
    TextKey.TRANSFER_PARTY_NEXT to "Next",
    TextKey.TRANSFER_PARTY_KIND_Q to "What is this money?",
    TextKey.TRANSFER_PARTY_SAVE to "Link and record",
    TextKey.SPACE_TRANSFER_SCREEN_TITLE to "Your transfers between countries",
    TextKey.SPACE_TRANSFER_SCREEN_INTRO to "Money you moved from your account in one country to your account in the other. It is neither spending nor income in either country, and each side keeps its own currency exactly as in the statement.",
    TextKey.SPACE_TRANSFER_SCREEN_ERROR to "Couldn't load transfers between countries",
    TextKey.SPACE_TRANSFER_SCREEN_NA_TITLE to "You have only one country",
    TextKey.SPACE_TRANSFER_SCREEN_NA_BODY to "A transfer to yourself is between two different countries. Add your other country first, then record transfers between them.",
    TextKey.SPACE_TRANSFER_SCREEN_ADD_SPACE to "Add a country",
    TextKey.SPACE_TRANSFER_SCREEN_NEW to "Record a transfer",
    TextKey.SPACE_TRANSFER_SCREEN_LINK to "Link two operations",
    TextKey.SPACE_TRANSFER_SCREEN_LINK_SOON to "Linking two existing operations isn't available yet: the list of candidate operations in both countries isn't built.",
    TextKey.SPACE_TRANSFER_SCREEN_EMPTY to "No transfers between countries yet",
    TextKey.SPACE_TRANSFER_SCREEN_EMPTY_BODY to "When you move money from one country to another, record it here.",
    TextKey.SPACE_TRANSFER_SCREEN_ROUTE to "From {0} to {1}",
    TextKey.SPACE_TRANSFER_SCREEN_NOT_SPEND to "Not spending, not income",
    TextKey.SPACE_TRANSFER_SCREEN_LEFT to "Left {0}",
    TextKey.SPACE_TRANSFER_SCREEN_ARRIVED to "Arrived in {0}",
    TextKey.SPACE_TRANSFER_SCREEN_RATE to "Actual rate (display only)",
    TextKey.SPACE_TRANSFER_SCREEN_RATE_LINE to "{0} {1} per {2} {3}",
    TextKey.SPACE_TRANSFER_SCREEN_NOTE_LINE to "Your note: {0}",
    TextKey.SPACE_TRANSFER_SCREEN_UNLINK to "Unlink",
    TextKey.SPACE_TRANSFER_SCREEN_LOCK_NOTE to "Each side is locked to its type: to change its type or link it to something else, unlink first. The rate comes from the two amounts and converts nothing else.",
    TextKey.SPACE_TRANSFER_SCREEN_UNLINK_TITLE to "Unlink this transfer?",
    TextKey.SPACE_TRANSFER_SCREEN_UNLINK_BODY to "Neither operation is deleted. Each goes back to «not set» and shows up in your reviews.",
    TextKey.SPACE_TRANSFER_SCREEN_CANCEL to "Cancel",
    TextKey.SPACE_TRANSFER_SCREEN_UNLINKED to "Unlinked: both operations are back in your reviews",
    TextKey.SPACE_TRANSFER_SCREEN_SAVED to "Transfer recorded: not spending, not income",
    TextKey.SPACE_TRANSFER_SCREEN_NEW_TITLE to "New transfer to yourself",
    TextKey.SPACE_TRANSFER_SCREEN_NEW_BODY to "Two operations: one out of a country and one into the other.",
    TextKey.SPACE_TRANSFER_SCREEN_AMOUNT_OUT to "Amount that left ({0})",
    TextKey.SPACE_TRANSFER_SCREEN_AMOUNT_IN to "Amount that arrived ({0})",
    TextKey.SPACE_TRANSFER_SCREEN_DATE to "Date",
    TextKey.SPACE_TRANSFER_SCREEN_NOTE to "Note (optional)",
    TextKey.SPACE_TRANSFER_SCREEN_LIVE_RATE to "Rate (display only)",
    TextKey.SPACE_TRANSFER_SCREEN_AFTER_AMOUNTS to "after you type both amounts",
    TextKey.SPACE_TRANSFER_SCREEN_RECORD to "Record it",
)
