package app.masroufy.core

/**
 * «الاستيراد» ٣/٥: `StatementImport` + `StatementColumns`. النص من النموذج التفاعلي بالحرف (الفصحى من `space = السعودية` والمصري من `مصر`)،
 * واللي مالوش مقابل في النموذج (حالات المنطق الزيادة: ملف كبير · مش PDF ولا CSV · التعيين اليدوي لسه مالوش حالة استخدام) كتابة Claude بنفس النبرة.
 * **ممنوع «·» جنب رقم عربي** ⇒ «،».
 */
internal val MSA_IMPORTS_STATEMENT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.STATEMENT_IMPORT_TITLE to "كشف الحساب",
    TextKey.STATEMENT_IMPORT_INTRO to "نقرأ الكشف على جوالك ولا يُرفع الملف نفسه. لا يُسجَّل شيء قبل أن تراجع وتؤكد.",
    TextKey.STATEMENT_IMPORT_PICK_TITLE to "اختر ملف الكشف",
    TextKey.STATEMENT_IMPORT_PICK_BODY to "نزّله من تطبيق البنك أولًا، ثم اختره من هنا.",
    TextKey.STATEMENT_IMPORT_PICK_BUTTON to "اختر ملفًا",
    TextKey.STATEMENT_IMPORT_NO_PICKER to "اختيار الملفات غير متاح على هذا الجهاز.",
    TextKey.STATEMENT_IMPORT_SUPPORTED to "الملفات المدعومة",
    TextKey.STATEMENT_IMPORT_STATEMENT_OF to "كشف {0}",
    TextKey.STATEMENT_IMPORT_PDF_SUB to "ملف PDF من تطبيق البنك",
    TextKey.STATEMENT_IMPORT_CSV to "ملف CSV",
    TextKey.STATEMENT_IMPORT_CSV_SUB to "بأعمدة معروفة: التاريخ والاسم والمبلغ والنوع",
    TextKey.STATEMENT_IMPORT_OTHER_BANKS to "كشوف البنوك الأخرى",
    TextKey.STATEMENT_IMPORT_LATER to "لاحقًا",
    TextKey.STATEMENT_IMPORT_CURRENCY_NOTE to "العملة من البلد الحالي: {0} ({1})",
    TextKey.STATEMENT_IMPORT_BANK_ALRAJHI to "مصرف الراجحي",
    TextKey.STATEMENT_IMPORT_BANK_QNB to "QNB مصر",
    TextKey.STATEMENT_IMPORT_READING to "نقرأ الملف…",
    TextKey.STATEMENT_IMPORT_READING_PAGE to "نقرأ الصفحة {0} من {1}",
    TextKey.STATEMENT_IMPORT_CANCEL_SAFE to "الإلغاء آمن: لم يُسجَّل شيء بعد.",
    TextKey.STATEMENT_IMPORT_CANCEL to "إلغاء",
    TextKey.STATEMENT_IMPORT_CANCELLED to "أُلغيت القراءة — لم يُسجَّل شيء",
    TextKey.STATEMENT_IMPORT_READ_CHIP to "قُرئ",
    TextKey.STATEMENT_IMPORT_RANGE to " من {0} إلى {1}",
    TextKey.STATEMENT_IMPORT_FACT_BANK to "البنك",
    TextKey.STATEMENT_IMPORT_FACT_TYPE to "النوع",
    TextKey.STATEMENT_IMPORT_FACT_CURRENCY to "العملة",
    TextKey.STATEMENT_IMPORT_FACT_WALLET to "المحفظة",
    TextKey.STATEMENT_IMPORT_CSV_KNOWN to "ملف CSV بأعمدة معروفة",
    TextKey.STATEMENT_IMPORT_CURRENCY_VALUE to "{0} — من البلد الحالي",
    TextKey.STATEMENT_IMPORT_NO_WALLET to "لم تُختر بعد",
    TextKey.STATEMENT_IMPORT_WALLET_Q to "هذا الملف لأي محفظة؟",
    TextKey.STATEMENT_IMPORT_REVIEW to "راجع العمليات",
    TextKey.STATEMENT_IMPORT_REVIEW_NOTE to "في المراجعة ترى الجديد والمكرر وتختار ما يُسجَّل.",
    TextKey.STATEMENT_IMPORT_OTHER_FILE to "اختر ملفًا آخر",
    TextKey.STATEMENT_IMPORT_ERR_TITLE to "تعذّرت قراءة الملف",
    TextKey.STATEMENT_IMPORT_COLS_TITLE to "الأعمدة غير معروفة",
    TextKey.STATEMENT_IMPORT_MAP_COLUMNS to "حدّد الأعمدة يدويًا",
    TextKey.STATEMENT_IMPORT_BATCHES_LINK to "الكشوف المستوردة سابقًا",
    TextKey.STATEMENT_IMPORT_TOO_LARGE to "الملف أكبر من ٢٥ ميجابايت. صدّر من تطبيق البنك فترة أقصر ثم أعد المحاولة.",
    TextKey.STATEMENT_IMPORT_UNSUPPORTED to "هذا الملف ليس PDF ولا CSV. اختر كشفًا من تطبيق البنك.",
    TextKey.STATEMENT_IMPORT_NO_PDF to "قراءة ملفات PDF غير متاحة على هذا الجهاز.",
    TextKey.STATEMENT_COLUMNS_TITLE to "تحديد الأعمدة",
    TextKey.STATEMENT_COLUMNS_INTRO to "اختر معنى كل عمود. لا نخمّن الأعمدة المالية، ولا يُسجَّل شيء قبل المراجعة.",
    TextKey.STATEMENT_COLUMNS_TABLE to "أول ٤ أسطر",
    TextKey.STATEMENT_COLUMNS_TABLE_NOTE to "من {0}، اسحب جانبًا",
    TextKey.STATEMENT_COLUMNS_PICK to "اختر",
    TextKey.STATEMENT_COLUMNS_WORD to "العمود {0}",
    TextKey.STATEMENT_COLUMNS_SELECTED to "{0}، «{1}»",
    TextKey.STATEMENT_COLUMNS_FIRST to "أول قيمة: {0}",
    TextKey.STATEMENT_COLUMNS_ROLE_DATE to "التاريخ",
    TextKey.STATEMENT_COLUMNS_ROLE_DESC to "الوصف",
    TextKey.STATEMENT_COLUMNS_ROLE_DEBIT to "مدين",
    TextKey.STATEMENT_COLUMNS_ROLE_CREDIT to "دائن",
    TextKey.STATEMENT_COLUMNS_ROLE_SIGNED to "المبلغ (بإشارة)",
    TextKey.STATEMENT_COLUMNS_ROLE_BALANCE to "الرصيد",
    TextKey.STATEMENT_COLUMNS_ROLE_REF to "المرجع",
    TextKey.STATEMENT_COLUMNS_ROLE_SKIP to "تجاهل",
    TextKey.STATEMENT_COLUMNS_PREVIEW to "هكذا يُقرأ السطر الأول",
    TextKey.STATEMENT_COLUMNS_DESC_UNSET to "الوصف لم يُحدَّد",
    TextKey.STATEMENT_COLUMNS_DATE_UNSET to "التاريخ لم يُحدَّد",
    TextKey.STATEMENT_COLUMNS_UNSET to "لم يُحدَّد",
    TextKey.STATEMENT_COLUMNS_CHECK_DATE to "التاريخ",
    TextKey.STATEMENT_COLUMNS_CHECK_DESC to "الوصف",
    TextKey.STATEMENT_COLUMNS_CHECK_AMOUNT to "المبلغ",
    TextKey.STATEMENT_COLUMNS_CHECK_BALANCE to "الرصيد (اختياري)",
    TextKey.STATEMENT_COLUMNS_BALANCE_WHY to "عمود الرصيد يتيح التحقق من أن كل سطر = الرصيد السابق − المدين + الدائن، فيظهر أي سطر ناقص أو مقروء خطأ قبل التسجيل.",
    TextKey.STATEMENT_COLUMNS_PENDING to "قراءة الملف بالأعمدة التي تختارها لم تُبنَ في التطبيق بعد، لذلك لا يمكن المتابعة الآن.",
)

internal val EGYPTIAN_IMPORTS_STATEMENT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.STATEMENT_IMPORT_TITLE to "كشف الحساب",
    TextKey.STATEMENT_IMPORT_INTRO to "بنقرا الكشف على جوالك، والملف نفسه مش بيترفع. مفيش حاجة بتتسجل قبل ما تراجع وتأكد.",
    TextKey.STATEMENT_IMPORT_PICK_TITLE to "اختار ملف الكشف",
    TextKey.STATEMENT_IMPORT_PICK_BODY to "نزّله من تطبيق البنك الأول، وبعدين اختاره من هنا.",
    TextKey.STATEMENT_IMPORT_PICK_BUTTON to "اختار ملف",
    TextKey.STATEMENT_IMPORT_NO_PICKER to "اختيار الملفات مش متاح على الجهاز ده.",
    TextKey.STATEMENT_IMPORT_SUPPORTED to "الملفات اللي بنقراها",
    TextKey.STATEMENT_IMPORT_STATEMENT_OF to "كشف {0}",
    TextKey.STATEMENT_IMPORT_PDF_SUB to "ملف PDF من تطبيق البنك",
    TextKey.STATEMENT_IMPORT_CSV to "ملف CSV",
    TextKey.STATEMENT_IMPORT_CSV_SUB to "بأعمدة معروفة: التاريخ والاسم والمبلغ والنوع",
    TextKey.STATEMENT_IMPORT_OTHER_BANKS to "كشوف البنوك التانية",
    TextKey.STATEMENT_IMPORT_LATER to "لسه — بتيجي بعدين",
    TextKey.STATEMENT_IMPORT_CURRENCY_NOTE to "العملة من البلد الحالي: {0} ({1})",
    TextKey.STATEMENT_IMPORT_BANK_ALRAJHI to "مصرف الراجحي",
    TextKey.STATEMENT_IMPORT_BANK_QNB to "QNB مصر",
    TextKey.STATEMENT_IMPORT_READING to "بنقرا الملف…",
    TextKey.STATEMENT_IMPORT_READING_PAGE to "بنقرا الصفحة {0} من {1}",
    TextKey.STATEMENT_IMPORT_CANCEL_SAFE to "الإلغاء آمن: لسه مفيش حاجة اتسجلت.",
    TextKey.STATEMENT_IMPORT_CANCEL to "إلغاء",
    TextKey.STATEMENT_IMPORT_CANCELLED to "اتلغت القراية — مفيش حاجة اتسجلت",
    TextKey.STATEMENT_IMPORT_READ_CHIP to "اتقرا",
    TextKey.STATEMENT_IMPORT_RANGE to " من {0} لـ {1}",
    TextKey.STATEMENT_IMPORT_FACT_BANK to "البنك",
    TextKey.STATEMENT_IMPORT_FACT_TYPE to "النوع",
    TextKey.STATEMENT_IMPORT_FACT_CURRENCY to "العملة",
    TextKey.STATEMENT_IMPORT_FACT_WALLET to "المحفظة",
    TextKey.STATEMENT_IMPORT_CSV_KNOWN to "ملف CSV بأعمدة معروفة",
    TextKey.STATEMENT_IMPORT_CURRENCY_VALUE to "{0} — من البلد الحالي",
    TextKey.STATEMENT_IMPORT_NO_WALLET to "لسه ما اخترتش",
    TextKey.STATEMENT_IMPORT_WALLET_Q to "الملف ده بتاع أنهي محفظة؟",
    TextKey.STATEMENT_IMPORT_REVIEW to "راجع العمليات",
    TextKey.STATEMENT_IMPORT_REVIEW_NOTE to "في المراجعة هتشوف الجديد والمكرر، وتختار اللي يتسجل.",
    TextKey.STATEMENT_IMPORT_OTHER_FILE to "اختار ملف تاني",
    TextKey.STATEMENT_IMPORT_ERR_TITLE to "ما قدرناش نقرا الملف",
    TextKey.STATEMENT_IMPORT_COLS_TITLE to "الأعمدة مش معروفة",
    TextKey.STATEMENT_IMPORT_MAP_COLUMNS to "حدد الأعمدة بإيدك",
    TextKey.STATEMENT_IMPORT_BATCHES_LINK to "الكشوف اللي اتستوردت قبل كده",
    TextKey.STATEMENT_IMPORT_TOO_LARGE to "الملف أكبر من ٢٥ ميجا. صدّر من تطبيق البنك فترة أقصر وجرّب تاني.",
    TextKey.STATEMENT_IMPORT_UNSUPPORTED to "الملف ده مش PDF ولا CSV. اختار كشف من تطبيق البنك.",
    TextKey.STATEMENT_IMPORT_NO_PDF to "قراية ملفات PDF مش متاحة على الجهاز ده.",
    TextKey.STATEMENT_COLUMNS_TITLE to "تحديد الأعمدة",
    TextKey.STATEMENT_COLUMNS_INTRO to "اختار معنى كل عمود. مش بنخمّن أعمدة الفلوس، ومفيش حاجة بتتسجل قبل المراجعة.",
    TextKey.STATEMENT_COLUMNS_TABLE to "أول ٤ سطور",
    TextKey.STATEMENT_COLUMNS_TABLE_NOTE to "من {0}، اسحب للجنب",
    TextKey.STATEMENT_COLUMNS_PICK to "اختار",
    TextKey.STATEMENT_COLUMNS_WORD to "العمود {0}",
    TextKey.STATEMENT_COLUMNS_SELECTED to "{0}، «{1}»",
    TextKey.STATEMENT_COLUMNS_FIRST to "أول قيمة: {0}",
    TextKey.STATEMENT_COLUMNS_ROLE_DATE to "التاريخ",
    TextKey.STATEMENT_COLUMNS_ROLE_DESC to "الوصف",
    TextKey.STATEMENT_COLUMNS_ROLE_DEBIT to "مدين",
    TextKey.STATEMENT_COLUMNS_ROLE_CREDIT to "دائن",
    TextKey.STATEMENT_COLUMNS_ROLE_SIGNED to "المبلغ (بإشارة)",
    TextKey.STATEMENT_COLUMNS_ROLE_BALANCE to "الرصيد",
    TextKey.STATEMENT_COLUMNS_ROLE_REF to "المرجع",
    TextKey.STATEMENT_COLUMNS_ROLE_SKIP to "تجاهل",
    TextKey.STATEMENT_COLUMNS_PREVIEW to "كده هيتقرا أول سطر",
    TextKey.STATEMENT_COLUMNS_DESC_UNSET to "الوصف لسه ما اتحددش",
    TextKey.STATEMENT_COLUMNS_DATE_UNSET to "التاريخ لسه ما اتحددش",
    TextKey.STATEMENT_COLUMNS_UNSET to "لسه ما اتحددش",
    TextKey.STATEMENT_COLUMNS_CHECK_DATE to "التاريخ",
    TextKey.STATEMENT_COLUMNS_CHECK_DESC to "الوصف",
    TextKey.STATEMENT_COLUMNS_CHECK_AMOUNT to "المبلغ",
    TextKey.STATEMENT_COLUMNS_CHECK_BALANCE to "الرصيد (مش لازم)",
    TextKey.STATEMENT_COLUMNS_BALANCE_WHY to "الرصيد بيخلّينا نتأكد إن كل سطر = الرصيد اللي قبله − المدين + الدائن، فأي سطر ناقص أو متقري غلط يبان قبل التسجيل.",
    TextKey.STATEMENT_COLUMNS_PENDING to "قراية الملف بالأعمدة اللي بتختارها لسه ما اتبنتش في البرنامج، فمش هينفع تكمّل دلوقتي.",
)

internal val ENGLISH_IMPORTS_STATEMENT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.STATEMENT_IMPORT_TITLE to "Bank statement",
    TextKey.STATEMENT_IMPORT_INTRO to "We read the statement on your phone; the file itself is never uploaded. Nothing is saved before you review and confirm.",
    TextKey.STATEMENT_IMPORT_PICK_TITLE to "Choose the statement file",
    TextKey.STATEMENT_IMPORT_PICK_BODY to "Download it from your bank's app first, then choose it here.",
    TextKey.STATEMENT_IMPORT_PICK_BUTTON to "Choose a file",
    TextKey.STATEMENT_IMPORT_NO_PICKER to "Choosing files isn't available on this device.",
    TextKey.STATEMENT_IMPORT_SUPPORTED to "Supported files",
    TextKey.STATEMENT_IMPORT_STATEMENT_OF to "{0} statement",
    TextKey.STATEMENT_IMPORT_PDF_SUB to "PDF file from the bank's app",
    TextKey.STATEMENT_IMPORT_CSV to "CSV file",
    TextKey.STATEMENT_IMPORT_CSV_SUB to "With known columns: date, name, amount and type",
    TextKey.STATEMENT_IMPORT_OTHER_BANKS to "Other banks' statements",
    TextKey.STATEMENT_IMPORT_LATER to "Later",
    TextKey.STATEMENT_IMPORT_CURRENCY_NOTE to "Currency from the current country: {0} ({1})",
    TextKey.STATEMENT_IMPORT_BANK_ALRAJHI to "Al Rajhi Bank",
    TextKey.STATEMENT_IMPORT_BANK_QNB to "QNB Egypt",
    TextKey.STATEMENT_IMPORT_READING to "Reading the file…",
    TextKey.STATEMENT_IMPORT_READING_PAGE to "Reading page {0} of {1}",
    TextKey.STATEMENT_IMPORT_CANCEL_SAFE to "Cancelling is safe: nothing has been saved yet.",
    TextKey.STATEMENT_IMPORT_CANCEL to "Cancel",
    TextKey.STATEMENT_IMPORT_CANCELLED to "Reading cancelled — nothing was saved",
    TextKey.STATEMENT_IMPORT_READ_CHIP to "Read",
    TextKey.STATEMENT_IMPORT_RANGE to " from {0} to {1}",
    TextKey.STATEMENT_IMPORT_FACT_BANK to "Bank",
    TextKey.STATEMENT_IMPORT_FACT_TYPE to "Type",
    TextKey.STATEMENT_IMPORT_FACT_CURRENCY to "Currency",
    TextKey.STATEMENT_IMPORT_FACT_WALLET to "Wallet",
    TextKey.STATEMENT_IMPORT_CSV_KNOWN to "CSV file with known columns",
    TextKey.STATEMENT_IMPORT_CURRENCY_VALUE to "{0} — from the current country",
    TextKey.STATEMENT_IMPORT_NO_WALLET to "Not chosen yet",
    TextKey.STATEMENT_IMPORT_WALLET_Q to "Which wallet is this file for?",
    TextKey.STATEMENT_IMPORT_REVIEW to "Review transactions",
    TextKey.STATEMENT_IMPORT_REVIEW_NOTE to "In the review you see what's new and what's a duplicate, and choose what gets saved.",
    TextKey.STATEMENT_IMPORT_OTHER_FILE to "Choose another file",
    TextKey.STATEMENT_IMPORT_ERR_TITLE to "Couldn't read the file",
    TextKey.STATEMENT_IMPORT_COLS_TITLE to "Unknown columns",
    TextKey.STATEMENT_IMPORT_MAP_COLUMNS to "Set the columns yourself",
    TextKey.STATEMENT_IMPORT_BATCHES_LINK to "Previously imported statements",
    TextKey.STATEMENT_IMPORT_TOO_LARGE to "The file is larger than 25 MB. Export a shorter period from your bank's app and try again.",
    TextKey.STATEMENT_IMPORT_UNSUPPORTED to "This file is neither a PDF nor a CSV. Choose a statement from your bank's app.",
    TextKey.STATEMENT_IMPORT_NO_PDF to "Reading PDF files isn't available on this device.",
    TextKey.STATEMENT_COLUMNS_TITLE to "Set columns",
    TextKey.STATEMENT_COLUMNS_INTRO to "Choose what each column means. We never guess money columns, and nothing is saved before the review.",
    TextKey.STATEMENT_COLUMNS_TABLE to "First 4 lines",
    TextKey.STATEMENT_COLUMNS_TABLE_NOTE to "Of {0}, swipe sideways",
    TextKey.STATEMENT_COLUMNS_PICK to "Choose",
    TextKey.STATEMENT_COLUMNS_WORD to "Column {0}",
    TextKey.STATEMENT_COLUMNS_SELECTED to "{0}, “{1}”",
    TextKey.STATEMENT_COLUMNS_FIRST to "First value: {0}",
    TextKey.STATEMENT_COLUMNS_ROLE_DATE to "Date",
    TextKey.STATEMENT_COLUMNS_ROLE_DESC to "Description",
    TextKey.STATEMENT_COLUMNS_ROLE_DEBIT to "Debit",
    TextKey.STATEMENT_COLUMNS_ROLE_CREDIT to "Credit",
    TextKey.STATEMENT_COLUMNS_ROLE_SIGNED to "Signed amount",
    TextKey.STATEMENT_COLUMNS_ROLE_BALANCE to "Balance",
    TextKey.STATEMENT_COLUMNS_ROLE_REF to "Reference",
    TextKey.STATEMENT_COLUMNS_ROLE_SKIP to "Ignore",
    TextKey.STATEMENT_COLUMNS_PREVIEW to "This is how the first line reads",
    TextKey.STATEMENT_COLUMNS_DESC_UNSET to "Description not set",
    TextKey.STATEMENT_COLUMNS_DATE_UNSET to "Date not set",
    TextKey.STATEMENT_COLUMNS_UNSET to "Not set",
    TextKey.STATEMENT_COLUMNS_CHECK_DATE to "Date",
    TextKey.STATEMENT_COLUMNS_CHECK_DESC to "Description",
    TextKey.STATEMENT_COLUMNS_CHECK_AMOUNT to "Amount",
    TextKey.STATEMENT_COLUMNS_CHECK_BALANCE to "Balance (optional)",
    TextKey.STATEMENT_COLUMNS_BALANCE_WHY to "A balance column lets us check that every line = previous balance − debit + credit, so a missing or misread line shows up before saving.",
    TextKey.STATEMENT_COLUMNS_PENDING to "Reading a file with the columns you choose isn't built into the app yet, so you can't continue right now.",
)
