package app.masroufy.core

/** «الاستيراد» 2/5: `BankSmsSettings` + `SmsPermission` + `SmsPaste`. */
internal val MSA_IMPORTS_SETTINGS_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.SMS_SETTINGS_TITLE to "إعداد القراءة",
    UiKey.SMS_SETTINGS_PERM_TITLE to "سُحب إذن الرسائل",
    UiKey.SMS_SETTINGS_PERM_BODY to "راجع أذونات أندرويد. الرسائل المعلّقة محفوظة ولن تضيع.",
    UiKey.SMS_SETTINGS_PERM_BUTTON to "أعد الإذن",
    UiKey.SMS_SETTINGS_PERM_BACK to "عاد الإذن — عادت القراءة",
    UiKey.SMS_SETTINGS_AUTO_TITLE to "القراءة التلقائية",
    UiKey.SMS_SETTINGS_ON to "تعمل",
    UiKey.SMS_SETTINGS_OFF to "متوقفة",
    UiKey.SMS_SETTINGS_BODY_ON to "الرسالة المفهومة من بنك مربوط تُسجَّل وتُصنَّف تلقائيًا ولو كان التطبيق مغلقًا. وما يحتاج قرارك ينتظر في «رسائل البنك». وما يفوتنا نلحقه كل 4 ساعات.",
    UiKey.SMS_SETTINGS_BODY_OFF to "متوقفة: لن تُقرأ رسائل جديدة. وما سُجّل سابقًا يبقى كما هو.",
    UiKey.SMS_SETTINGS_BODY_PERM to "متوقفة لأن الإذن سُحب. أعده لتعمل تلقائيًا.",
    UiKey.SMS_SETTINGS_STOP to "أوقف القراءة التلقائية",
    UiKey.SMS_SETTINGS_START to "شغّل القراءة التلقائية",
    UiKey.SMS_SETTINGS_STOPPED to "أُوقفت القراءة",
    UiKey.SMS_SETTINGS_STARTED to "عادت القراءة",
    UiKey.SMS_SETTINGS_PERM_LINE_ON to "إذن الرسائل: ممنوح — طُلب مرة واحدة فقط",
    UiKey.SMS_SETTINGS_PERM_LINE_OFF to "إذن الرسائل: غير ممنوح",
    UiKey.SMS_SETTINGS_SENDERS to "البنوك المرسلة",
    UiKey.SMS_SETTINGS_SENDERS_COUNT to "{0} من {1}",
    UiKey.SMS_SETTINGS_RECORDS_IN to "تُسجَّل في: {0}",
    UiKey.SMS_SETTINGS_WAITING_WALLET to "{0} بانتظار اختيار المحفظة",
    UiKey.SMS_SETTINGS_NO_WALLET to "لم تُختر المحفظة بعد",
    UiKey.SMS_SETTINGS_ADD to "أضف مرسلًا",
    UiKey.SMS_SETTINGS_RULES to "إن كان في البلد حساب بنكي واحد تُسجَّل رسائله فيه مباشرة. وإن كان لك حسابان في البنك نفسه نفرّق بينهما بآخر 4 أرقام في الرسالة. والبنك الذي بلا محفظة تنتظر رسائله حتى تختار.",
    UiKey.SMS_SETTINGS_NOTIF_LINK to "إشعارات رسائل البنك",
    UiKey.SMS_SETTINGS_NEW_TITLE to "مرسل جديد",
    UiKey.SMS_SETTINGS_NEW_BODY to "اكتب اسم المرسل كما يظهر في الرسائل، واختر محفظته.",
    UiKey.SMS_SETTINGS_EDIT_BODY to "مرة واحدة فقط. ما ينتظر من رسائل هذا البنك يُسجَّل تلقائيًا بعد اختيارك.",
    UiKey.SMS_SETTINGS_NAME to "اسم المرسل",
    UiKey.SMS_SETTINGS_NAME_ERROR to "اكتب اسم مرسل البنك كما يظهر في الرسائل",
    UiKey.SMS_SETTINGS_SAVE to "احفظ",
    UiKey.SMS_SETTINGS_ADD_IT to "أضفه",
    UiKey.SMS_SETTINGS_UNLINK to "فك الربط",
    UiKey.SMS_SETTINGS_REMOVE to "احذف المرسل",
    UiKey.SMS_SETTINGS_LINKED to "رُبط «{0}» بـ«{1}»",
    UiKey.SMS_SETTINGS_ADDED to "أُضيف «{0}»",
    UiKey.SMS_SETTINGS_UNLINKED to "فُك الربط — تنتظر رسائله حتى تختار",
    UiKey.SMS_SETTINGS_REMOVED to "لن نقرأ رسائل «{0}»",
    UiKey.SMS_PERM_TITLE to "إذن قراءة الرسائل",
    UiKey.SMS_PERM_WHY to "نقرأ رسائل البنوك التي تختارها فقط، على جوالك.",
    UiKey.SMS_PERM_ONCE to "يطلب أندرويد الإذن مرة واحدة فقط.",
    UiKey.SMS_PERM_WHAT to "الرسالة المفهومة تُسجَّل تلقائيًا، وما يحتاج قرارك ينتظر في «رسائل البنك».",
    UiKey.SMS_PERM_DENIED to "لم يُمنح الإذن — يمكنك لصق الرسائل يدويًا.",
    UiKey.SMS_PERM_ALLOW to "موافق",
    UiKey.SMS_PERM_LATER to "ليس الآن",
    UiKey.SMS_PASTE_TITLE to "إضافة من الرسائل",
    UiKey.SMS_PASTE_TAB_PASTE to "الصق رسالة",
    UiKey.SMS_PASTE_TAB_PERIOD to "اقرأ فترة",
    UiKey.SMS_PASTE_NOTE_IOS to "لا يسمح الآيفون بقراءة الرسائل، فالصق نص الرسالة بنفسك. لا يُسجَّل شيء قبل أن تؤكد.",
    UiKey.SMS_PASTE_NOTE_PERIOD to "نقرأ رسائل البنوك التي تختارها في هذه الفترة فقط — ولو كانت القراءة التلقائية متوقفة.",
    UiKey.SMS_PASTE_NOTE_PASTE to "الصق رسالة بنك. لا يُسجَّل شيء قبل أن تؤكد.",
    UiKey.SMS_PASTE_NO_READER to "لا يوجد قارئ رسائل لهذا البلد بعد.",
    UiKey.SMS_PASTE_HINT to "الصق نص رسالة البنك هنا",
    UiKey.SMS_PASTE_FROM_CLIP to "الصق من الحافظة",
    UiKey.SMS_PASTE_READ to "اقرأها",
    UiKey.SMS_PASTE_RANGE to "الفترة",
    UiKey.SMS_PASTE_RANGE_MONTH to "منذ بداية الشهر ({0})",
    UiKey.SMS_PASTE_RANGE_WEEK to "آخر 7 أيام",
    UiKey.SMS_PASTE_RANGE_30 to "آخر 30 يومًا",
    UiKey.SMS_PASTE_BANKS to "من أي البنوك",
    UiKey.SMS_PASTE_NO_SENDERS to "لا مرسلين بعد — أضفهم من إعداد القراءة.",
    UiKey.SMS_PASTE_READ_PERIOD to "اقرأ الرسائل",
    UiKey.SMS_PASTE_ERR_TITLE to "لم نجد عملية في هذا النص",
    UiKey.SMS_PASTE_ERR_BODY to "تأكد أنك نسخت نص رسالة البنك كاملًا، أو سجّل العملية يدويًا.",
    UiKey.SMS_PASTE_SUMMARY to "فهمنا {0} وتجاوزنا {1}",
    UiKey.SMS_PASTE_SUMMARY_READ to "قرأنا {0}: {1}",
    UiKey.SMS_PASTE_TRUNCATED to "في الفترة رسائل كثيرة — قرأنا أولها فقط.",
    UiKey.SMS_PASTE_WALLET_Q to "هذه الرسائل من أي حساب؟",
    UiKey.SMS_PASTE_NEW to "جديدة",
    UiKey.SMS_PASTE_DUP to "مسجلة سابقًا",
    UiKey.SMS_PASTE_SIMILAR to "تحتاج مراجعة",
    UiKey.SMS_PASTE_SKIPPED to "تجاوزناها ({0})",
    UiKey.SMS_PASTE_SAVE to "سجّل {0}",
    UiKey.SMS_PASTE_PICK_WALLET to "اختر الحساب أولًا.",
    UiKey.SMS_PASTE_NOTE_DUPS to "المسجلة سابقًا لن تتكرر.",
    UiKey.SMS_PASTE_NOTE_NOTHING to "لا يُسجَّل شيء قبل هذه الضغطة.",
    UiKey.SMS_PASTE_SAVED to "سُجّلت {0}",
    UiKey.SMS_PASTE_DONE_BODY to "في «{0}». التصنيف القادم من قاعدة يبقى «مقترحًا» حتى تؤكده.",
    UiKey.SMS_PASTE_AGAIN to "الصق غيرها",
)

internal val EGYPTIAN_IMPORTS_SETTINGS_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.SMS_SETTINGS_TITLE to "إعداد القراية",
    UiKey.SMS_SETTINGS_PERM_TITLE to "إذن الرسايل اتسحب",
    UiKey.SMS_SETTINGS_PERM_BODY to "راجع أذونات أندرويد. الرسايل المستنية محفوظة ومش هتضيع.",
    UiKey.SMS_SETTINGS_PERM_BUTTON to "رجّع الإذن",
    UiKey.SMS_SETTINGS_PERM_BACK to "الإذن رجع — القراية شغالة تاني",
    UiKey.SMS_SETTINGS_AUTO_TITLE to "القراية التلقائية",
    UiKey.SMS_SETTINGS_ON to "شغالة",
    UiKey.SMS_SETTINGS_OFF to "واقفة",
    UiKey.SMS_SETTINGS_BODY_ON to "الرسالة المفهومة من بنك مربوط بتتسجل وتتصنف لوحدها حتى والبرنامج مقفول. اللي محتاج قرارك بيستنى في «رسايل البنك». ولو رسالة فاتتنا بنلحقها كل 4 ساعات.",
    UiKey.SMS_SETTINGS_BODY_OFF to "واقفة: مش هنقرا رسايل جديدة. اللي اتسجل قبل كده زي ما هو.",
    UiKey.SMS_SETTINGS_BODY_PERM to "واقفة لأن الإذن اتسحب. رجّعه وهي تشتغل لوحدها.",
    UiKey.SMS_SETTINGS_STOP to "وقّف القراية التلقائية",
    UiKey.SMS_SETTINGS_START to "شغّل القراية التلقائية",
    UiKey.SMS_SETTINGS_STOPPED to "القراية وقفت",
    UiKey.SMS_SETTINGS_STARTED to "القراية اشتغلت",
    UiKey.SMS_SETTINGS_PERM_LINE_ON to "إذن الرسايل: مسموح — اتطلب مرة واحدة بس",
    UiKey.SMS_SETTINGS_PERM_LINE_OFF to "إذن الرسايل: مش مسموح",
    UiKey.SMS_SETTINGS_SENDERS to "البنوك اللي بتبعتلك",
    UiKey.SMS_SETTINGS_SENDERS_COUNT to "{0} من {1}",
    UiKey.SMS_SETTINGS_RECORDS_IN to "بتتسجل في: {0}",
    UiKey.SMS_SETTINGS_WAITING_WALLET to "{0} مستنيين تختار المحفظة",
    UiKey.SMS_SETTINGS_NO_WALLET to "لسه ما اخترتش المحفظة",
    UiKey.SMS_SETTINGS_ADD to "ضيف مرسل",
    UiKey.SMS_SETTINGS_RULES to "لو في البلد حساب بنك واحد، رسايله بتتسجل فيه على طول. ولو عندك حسابين في نفس البنك، بنفرّق بينهم بآخر 4 أرقام في الرسالة. البنك اللي مالوش محفظة رسايله بتستنى لحد ما تختار.",
    UiKey.SMS_SETTINGS_NOTIF_LINK to "إشعارات رسايل البنك",
    UiKey.SMS_SETTINGS_NEW_TITLE to "مرسل جديد",
    UiKey.SMS_SETTINGS_NEW_BODY to "اكتب اسم المرسل زي ما بيظهر في الرسايل، واختار محفظته.",
    UiKey.SMS_SETTINGS_EDIT_BODY to "مرة واحدة بس. أي رسالة مستنية من البنك ده بتتسجل لوحدها بعد ما تختار.",
    UiKey.SMS_SETTINGS_NAME to "اسم المرسل",
    UiKey.SMS_SETTINGS_NAME_ERROR to "اكتب اسم مرسل البنك زي ما بيظهر في الرسايل",
    UiKey.SMS_SETTINGS_SAVE to "احفظ",
    UiKey.SMS_SETTINGS_ADD_IT to "ضيفه",
    UiKey.SMS_SETTINGS_UNLINK to "شيل الربط",
    UiKey.SMS_SETTINGS_REMOVE to "شيل المرسل",
    UiKey.SMS_SETTINGS_LINKED to "اتربط «{0}» بـ«{1}»",
    UiKey.SMS_SETTINGS_ADDED to "اتضاف «{0}»",
    UiKey.SMS_SETTINGS_UNLINKED to "اتشال الربط — رسايله هتستنى لحد ما تختار",
    UiKey.SMS_SETTINGS_REMOVED to "مش هنقرا رسايل «{0}»",
    UiKey.SMS_PERM_TITLE to "إذن قراية الرسايل",
    UiKey.SMS_PERM_WHY to "بنقرا رسايل البنوك اللي إنت تختارها بس، على جوالك.",
    UiKey.SMS_PERM_ONCE to "أندرويد بيطلب الإذن مرة واحدة بس.",
    UiKey.SMS_PERM_WHAT to "الرسالة المفهومة بتتسجل لوحدها، واللي محتاج قرارك بيستنى في «رسايل البنك».",
    UiKey.SMS_PERM_DENIED to "الإذن ما اتداش — تقدر تلصق الرسايل بإيدك.",
    UiKey.SMS_PERM_ALLOW to "موافق",
    UiKey.SMS_PERM_LATER to "بعدين",
    UiKey.SMS_PASTE_TITLE to "ضيف من الرسايل",
    UiKey.SMS_PASTE_TAB_PASTE to "الصق رسالة",
    UiKey.SMS_PASTE_TAB_PERIOD to "اقرا فترة",
    UiKey.SMS_PASTE_NOTE_IOS to "الآيفون ما بيسمحش للبرامج تقرا الرسايل، فالصق نص الرسالة بإيدك. مفيش حاجة بتتسجل قبل ما تأكد.",
    UiKey.SMS_PASTE_NOTE_PERIOD to "بنقرا رسايل البنوك اللي تختارها في الفترة دي بس — حتى لو القراية التلقائية واقفة.",
    UiKey.SMS_PASTE_NOTE_PASTE to "الصق رسالة بنك. مفيش حاجة بتتسجل قبل ما تأكد.",
    UiKey.SMS_PASTE_NO_READER to "مفيش قارئ رسايل للبلد دي لسه.",
    UiKey.SMS_PASTE_HINT to "الصق نص رسالة البنك هنا",
    UiKey.SMS_PASTE_FROM_CLIP to "الصق من الحافظة",
    UiKey.SMS_PASTE_READ to "اقراها",
    UiKey.SMS_PASTE_RANGE to "الفترة",
    UiKey.SMS_PASTE_RANGE_MONTH to "من أول الشهر ({0})",
    UiKey.SMS_PASTE_RANGE_WEEK to "آخر 7 أيام",
    UiKey.SMS_PASTE_RANGE_30 to "آخر 30 يوم",
    UiKey.SMS_PASTE_BANKS to "من أنهي بنوك",
    UiKey.SMS_PASTE_NO_SENDERS to "مفيش مرسلين لسه — ضيفهم من إعداد القراية.",
    UiKey.SMS_PASTE_READ_PERIOD to "اقرا الرسايل",
    UiKey.SMS_PASTE_ERR_TITLE to "ملقيناش عملية في النص ده",
    UiKey.SMS_PASTE_ERR_BODY to "اتأكد إنك نسخت نص رسالة البنك كله، أو سجّل العملية بإيدك.",
    UiKey.SMS_PASTE_SUMMARY to "فهمنا {0} وعدّينا {1}",
    UiKey.SMS_PASTE_SUMMARY_READ to "قرينا {0}: {1}",
    UiKey.SMS_PASTE_TRUNCATED to "الفترة فيها رسايل كتير — قرينا أولها بس.",
    UiKey.SMS_PASTE_WALLET_Q to "الرسايل دي من أنهي حساب؟",
    UiKey.SMS_PASTE_NEW to "جديدة",
    UiKey.SMS_PASTE_DUP to "متسجلة قبل كده",
    UiKey.SMS_PASTE_SIMILAR to "محتاجة مراجعة",
    UiKey.SMS_PASTE_SKIPPED to "عدّيناها ({0})",
    UiKey.SMS_PASTE_SAVE to "سجّل {0}",
    UiKey.SMS_PASTE_PICK_WALLET to "اختار الحساب الأول.",
    UiKey.SMS_PASTE_NOTE_DUPS to "المتسجلة قبل كده مش هتتكرر.",
    UiKey.SMS_PASTE_NOTE_NOTHING to "مفيش حاجة بتتسجل قبل الضغطة دي.",
    UiKey.SMS_PASTE_SAVED to "اتسجلت {0}",
    UiKey.SMS_PASTE_DONE_BODY to "في «{0}». التصنيف اللي جه من قاعدة بيفضل «مقترح» لحد ما تأكده.",
    UiKey.SMS_PASTE_AGAIN to "الصق تاني",
)

internal val ENGLISH_IMPORTS_SETTINGS_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.SMS_SETTINGS_TITLE to "Reading settings",
    UiKey.SMS_SETTINGS_PERM_TITLE to "Messages permission removed",
    UiKey.SMS_SETTINGS_PERM_BODY to "Check Android permissions. Waiting messages are kept and won't be lost.",
    UiKey.SMS_SETTINGS_PERM_BUTTON to "Allow again",
    UiKey.SMS_SETTINGS_PERM_BACK to "Permission back — reading is on again",
    UiKey.SMS_SETTINGS_AUTO_TITLE to "Automatic reading",
    UiKey.SMS_SETTINGS_ON to "On",
    UiKey.SMS_SETTINGS_OFF to "Off",
    UiKey.SMS_SETTINGS_BODY_ON to "Understood messages from a linked bank are recorded and categorised automatically, even when the app is closed. Anything needing your decision waits in “Bank messages”, and anything we miss is caught every 4 hours.",
    UiKey.SMS_SETTINGS_BODY_OFF to "Off: no new messages are read. What was recorded stays as it is.",
    UiKey.SMS_SETTINGS_BODY_PERM to "Stopped because the permission was removed. Allow it again and it runs by itself.",
    UiKey.SMS_SETTINGS_STOP to "Stop automatic reading",
    UiKey.SMS_SETTINGS_START to "Start automatic reading",
    UiKey.SMS_SETTINGS_STOPPED to "Reading stopped",
    UiKey.SMS_SETTINGS_STARTED to "Reading is on",
    UiKey.SMS_SETTINGS_PERM_LINE_ON to "Messages permission: allowed — asked once only",
    UiKey.SMS_SETTINGS_PERM_LINE_OFF to "Messages permission: not allowed",
    UiKey.SMS_SETTINGS_SENDERS to "Sending banks",
    UiKey.SMS_SETTINGS_SENDERS_COUNT to "{0} of {1}",
    UiKey.SMS_SETTINGS_RECORDS_IN to "Recorded in: {0}",
    UiKey.SMS_SETTINGS_WAITING_WALLET to "{0} waiting for a wallet",
    UiKey.SMS_SETTINGS_NO_WALLET to "No wallet chosen yet",
    UiKey.SMS_SETTINGS_ADD to "Add a sender",
    UiKey.SMS_SETTINGS_RULES to "If the country has one bank account, its messages go straight into it. If you have two accounts at the same bank, we tell them apart by the last 4 digits in the message. A bank without a wallet keeps its messages waiting until you choose.",
    UiKey.SMS_SETTINGS_NOTIF_LINK to "Bank message notifications",
    UiKey.SMS_SETTINGS_NEW_TITLE to "New sender",
    UiKey.SMS_SETTINGS_NEW_BODY to "Type the sender name as it appears in messages, and choose its wallet.",
    UiKey.SMS_SETTINGS_EDIT_BODY to "Only once. Waiting messages from this bank are recorded after you choose.",
    UiKey.SMS_SETTINGS_NAME to "Sender name",
    UiKey.SMS_SETTINGS_NAME_ERROR to "Type the bank sender name as it appears in messages",
    UiKey.SMS_SETTINGS_SAVE to "Save",
    UiKey.SMS_SETTINGS_ADD_IT to "Add it",
    UiKey.SMS_SETTINGS_UNLINK to "Unlink",
    UiKey.SMS_SETTINGS_REMOVE to "Remove sender",
    UiKey.SMS_SETTINGS_LINKED to "Linked “{0}” to “{1}”",
    UiKey.SMS_SETTINGS_ADDED to "Added “{0}”",
    UiKey.SMS_SETTINGS_UNLINKED to "Unlinked — its messages wait until you choose",
    UiKey.SMS_SETTINGS_REMOVED to "We won't read “{0}” messages",
    UiKey.SMS_PERM_TITLE to "Permission to read messages",
    UiKey.SMS_PERM_WHY to "We read only the banks you choose, on your phone.",
    UiKey.SMS_PERM_ONCE to "Android asks for the permission once only.",
    UiKey.SMS_PERM_WHAT to "Understood messages are recorded automatically; anything needing you waits in “Bank messages”.",
    UiKey.SMS_PERM_DENIED to "Permission not given — you can paste messages yourself.",
    UiKey.SMS_PERM_ALLOW to "Allow",
    UiKey.SMS_PERM_LATER to "Not now",
    UiKey.SMS_PASTE_TITLE to "Add from messages",
    UiKey.SMS_PASTE_TAB_PASTE to "Paste a message",
    UiKey.SMS_PASTE_TAB_PERIOD to "Read a period",
    UiKey.SMS_PASTE_NOTE_IOS to "iPhone doesn't allow reading messages, so paste the message text yourself. Nothing is saved before you confirm.",
    UiKey.SMS_PASTE_NOTE_PERIOD to "We read only the banks you choose in this period — even if automatic reading is off.",
    UiKey.SMS_PASTE_NOTE_PASTE to "Paste a bank message. Nothing is saved before you confirm.",
    UiKey.SMS_PASTE_NO_READER to "There is no message reader for this country yet.",
    UiKey.SMS_PASTE_HINT to "Paste the bank message here",
    UiKey.SMS_PASTE_FROM_CLIP to "Paste from clipboard",
    UiKey.SMS_PASTE_READ to "Read it",
    UiKey.SMS_PASTE_RANGE to "Period",
    UiKey.SMS_PASTE_RANGE_MONTH to "Since the month start ({0})",
    UiKey.SMS_PASTE_RANGE_WEEK to "Last 7 days",
    UiKey.SMS_PASTE_RANGE_30 to "Last 30 days",
    UiKey.SMS_PASTE_BANKS to "From which banks",
    UiKey.SMS_PASTE_NO_SENDERS to "No senders yet — add them in reading settings.",
    UiKey.SMS_PASTE_READ_PERIOD to "Read messages",
    UiKey.SMS_PASTE_ERR_TITLE to "We found no transaction in this text",
    UiKey.SMS_PASTE_ERR_BODY to "Make sure you copied the whole bank message, or record the transaction yourself.",
    UiKey.SMS_PASTE_SUMMARY to "Understood {0} and skipped {1}",
    UiKey.SMS_PASTE_SUMMARY_READ to "Read {0}: {1}",
    UiKey.SMS_PASTE_TRUNCATED to "The period has many messages — we read the first ones only.",
    UiKey.SMS_PASTE_WALLET_Q to "Which account are these messages from?",
    UiKey.SMS_PASTE_NEW to "New",
    UiKey.SMS_PASTE_DUP to "Already recorded",
    UiKey.SMS_PASTE_SIMILAR to "Needs review",
    UiKey.SMS_PASTE_SKIPPED to "Skipped ({0})",
    UiKey.SMS_PASTE_SAVE to "Record {0}",
    UiKey.SMS_PASTE_PICK_WALLET to "Choose the account first.",
    UiKey.SMS_PASTE_NOTE_DUPS to "Already-recorded ones won't repeat.",
    UiKey.SMS_PASTE_NOTE_NOTHING to "Nothing is saved before this tap.",
    UiKey.SMS_PASTE_SAVED to "Recorded {0}",
    UiKey.SMS_PASTE_DONE_BODY to "In “{0}”. A category from a rule stays “suggested” until you confirm it.",
    UiKey.SMS_PASTE_AGAIN to "Paste another",
)
