package app.masroufy.core

/** «العمليات» بالفصحى — الجزء التالت: زون التحويلات · «من هذا؟» · التحويل لنفسك بين البلدين. */
internal val MSA_OPERATIONS_TRANSFER_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.TRANSFERS_TITLE to "التحويلات",
    TextKey.TRANSFERS_INTRO to "لكل طرف تحوّل إليه أو منه: حدّد من هو مرة واحدة، فيُضبط السابق واللاحق تلقائيًا.",
    TextKey.TRANSFERS_WAITING to "بانتظار ردك",
    TextKey.TRANSFERS_UNDECIDED to "بلا قرار",
    TextKey.TRANSFERS_DECIDED to "تقرّر",
    TextKey.TRANSFERS_IN_MONTH to "{0} في {1}",
    TextKey.TRANSFERS_META to "{0}، آخرها {1}",
    TextKey.TRANSFERS_LAST4 to "•••• {0}",
    TextKey.TRANSFERS_PERSON_CHIP to "شخص: {0}",
    TextKey.TRANSFERS_HINT_ASK to "شخص: تُسجَّل تحويلاته عليه، ونسألك نوع كل تحويل (سلفة أو دعم…).",
    TextKey.TRANSFERS_HINT_OWN to "كل تحويلاته أصبحت بين محافظك، لا دخلًا ولا مصروفًا.",
    TextKey.TRANSFERS_HINT_UNDO to "إلغاء القرار يعيد السؤال.",
    TextKey.TRANSFERS_PERSON to "شخص",
    TextKey.TRANSFERS_FORGET to "إلغاء القرار",
    TextKey.TRANSFERS_DONE_OWN to "صُحّح {0} — أصبحت بين محافظك",
    TextKey.TRANSFERS_DONE_NOT to "تم، لن نسأل عنه مجددًا",
    TextKey.TRANSFERS_DONE_FORGET to "أُلغي القرار — عادت تحويلاته «غير محددة»",
    TextKey.TRANSFERS_DONE_PERSON to "رُبط بـ{0}",
    TextKey.TRANSFERS_DONE_PERSON_NEW to "رُبط بـ{0} وأُضيف إلى أشخاصك",
    TextKey.TRANSFERS_PERSON_BODY to "اكتب اسم شخص جديد أو اختر من أشخاصك.",
    TextKey.TRANSFERS_NEW_PERSON to "شخص جديد",
    TextKey.TRANSFERS_LINK to "اربط",
    TextKey.TRANSFERS_NO_PARTY to "{0} بلا طرف — لا اسم ولا رقم في ملف البنك. تبقى كما هي دون تخمين.",
    TextKey.TRANSFERS_EMPTY to "لا تحويلات بعد",
    TextKey.TRANSFERS_EMPTY_BODY to "حين تصل تحويلات من رسائل البنك أو الكشف تظهر هنا مجمّعة بالطرف.",
    TextKey.TRANSFERS_ERROR to "تعذّر تحميل التحويلات",
    TextKey.TRANSFERS_COUNT_ONE to "تحويل واحد",
    TextKey.TRANSFERS_COUNT_TWO to "تحويلان",
    TextKey.TRANSFERS_COUNT_FEW to "{0} تحويلات",
    TextKey.TRANSFERS_COUNT_MANY to "{0} تحويلًا",
    TextKey.TRANSFER_PARTY_ASK to "من هذا؟",
    TextKey.TRANSFER_PARTY_NAME to "الاسم كما ورد: {0}",
    TextKey.TRANSFER_PARTY_ACCOUNT to "حساب ينتهي بـ {0}",
    TextKey.TRANSFER_PARTY_PERSON to "شخص أعرفه",
    TextKey.TRANSFER_PARTY_OWN to "حسابي الآخر",
    TextKey.TRANSFER_PARTY_NOT to "ليس هذا",
    TextKey.TRANSFER_PARTY_UNDO to "تراجع",
    TextKey.TRANSFER_PARTY_DONE_PERSON to "رُبط بـ{0}، {1}",
    TextKey.TRANSFER_PARTY_ADDED to "أُضيف {0} إلى أشخاصك.",
    TextKey.TRANSFER_PARTY_DONE_PERSON_BODY to "أي تحويل من {0} أو إليه يُسجَّل عليه تلقائيًا، ونسألك نوعه كل مرة (سلفة أو دعم…).",
    TextKey.TRANSFER_PARTY_DONE_OWN to "تحويل بين محافظك",
    TextKey.TRANSFER_PARTY_DONE_OWN_BODY to "ليس دخلًا ولا مصروفًا. وصُحّحت {0} من الطرف نفسه.",
    TextKey.TRANSFER_PARTY_DONE_NOT to "تم",
    TextKey.TRANSFER_PARTY_DONE_NOT_BODY to "لن نسألك عن هذا الحساب مجددًا.",
    TextKey.TRANSFER_PARTY_WHO_TITLE to "من صاحب الحساب {0}؟",
    TextKey.TRANSFER_PARTY_KIND_TITLE to "هذا المبلغ من {0}",
    TextKey.TRANSFER_PARTY_NEW_TITLE to "شخص جديد (الاسم كما ورد)",
    TextKey.TRANSFER_PARTY_NAME_LABEL to "اسم الشخص",
    TextKey.TRANSFER_PARTY_OR to "أو أحد أشخاصك",
    TextKey.TRANSFER_PARTY_NEXT to "التالي",
    TextKey.TRANSFER_PARTY_KIND_Q to "ما نوع هذا المبلغ؟",
    TextKey.TRANSFER_PARTY_SAVE to "اربط وسجّل",
    TextKey.SPACE_TRANSFER_SCREEN_TITLE to "تحويلاتك بين البلدين",
    TextKey.SPACE_TRANSFER_SCREEN_INTRO to "أموال نقلتها من حسابك في بلد إلى حسابك في الآخر. لا تُحسب مصروفًا ولا دخلًا في أي بلد، وكل طرف بعملته كما في الكشف تمامًا.",
    TextKey.SPACE_TRANSFER_SCREEN_ERROR to "تعذّر تحميل التحويلات بين البلدين",
    TextKey.SPACE_TRANSFER_SCREEN_NA_TITLE to "لديك بلد واحد فقط",
    TextKey.SPACE_TRANSFER_SCREEN_NA_BODY to "التحويل لنفسك يكون بين بلدين مختلفين. أضف بلدك الآخر أولًا، ثم سجّل التحويلات بينهما.",
    TextKey.SPACE_TRANSFER_SCREEN_ADD_SPACE to "أضف بلدًا",
    TextKey.SPACE_TRANSFER_SCREEN_NEW to "سجّل تحويلًا",
    TextKey.SPACE_TRANSFER_SCREEN_LINK to "اربط عمليتين",
    TextKey.SPACE_TRANSFER_SCREEN_LINK_SOON to "ربط عمليتين موجودتين غير متاح بعد — قائمة العمليات المرشحة في البلدين لم تُبنَ.",
    TextKey.SPACE_TRANSFER_SCREEN_EMPTY to "لا تحويلات بين البلدين بعد",
    TextKey.SPACE_TRANSFER_SCREEN_EMPTY_BODY to "حين تنقل مالًا من بلد إلى آخر، سجّله هنا.",
    TextKey.SPACE_TRANSFER_SCREEN_ROUTE to "من {0} إلى {1}",
    TextKey.SPACE_TRANSFER_SCREEN_NOT_SPEND to "لا مصروف ولا دخل",
    TextKey.SPACE_TRANSFER_SCREEN_LEFT to "خرجت من {0}",
    TextKey.SPACE_TRANSFER_SCREEN_ARRIVED to "وصلت في {0}",
    TextKey.SPACE_TRANSFER_SCREEN_RATE to "السعر الفعلي (للعرض فقط)",
    TextKey.SPACE_TRANSFER_SCREEN_RATE_LINE to "{0} {1} لكل {2} {3}",
    TextKey.SPACE_TRANSFER_SCREEN_NOTE_LINE to "ملاحظتك: {0}",
    TextKey.SPACE_TRANSFER_SCREEN_UNLINK to "فك الربط",
    TextKey.SPACE_TRANSFER_SCREEN_LOCK_NOTE to "كل طرف مقفل على نوعه: لتغيير نوعه أو ربطه بشيء آخر فُكّ الربط أولًا. والسعر يُحسب من المبلغين ولا يحوّل أي رقم آخر.",
    TextKey.SPACE_TRANSFER_SCREEN_UNLINK_TITLE to "فك ربط التحويل؟",
    TextKey.SPACE_TRANSFER_SCREEN_UNLINK_BODY to "لن تُحذف العمليتان. يعود نوع كل منهما «غير محدد» وتظهران في المراجعات.",
    TextKey.SPACE_TRANSFER_SCREEN_CANCEL to "إلغاء",
    TextKey.SPACE_TRANSFER_SCREEN_UNLINKED to "فُكّ الربط — عادت العمليتان إلى المراجعات",
    TextKey.SPACE_TRANSFER_SCREEN_SAVED to "سُجّل التحويل — لا مصروف ولا دخل",
    TextKey.SPACE_TRANSFER_SCREEN_NEW_TITLE to "تحويل جديد لنفسك",
    TextKey.SPACE_TRANSFER_SCREEN_NEW_BODY to "عمليتان: صادرة من بلد وواردة في الآخر.",
    TextKey.SPACE_TRANSFER_SCREEN_AMOUNT_OUT to "المبلغ الذي خرج ({0})",
    TextKey.SPACE_TRANSFER_SCREEN_AMOUNT_IN to "المبلغ الذي وصل ({0})",
    TextKey.SPACE_TRANSFER_SCREEN_DATE to "التاريخ",
    TextKey.SPACE_TRANSFER_SCREEN_NOTE to "ملاحظة (اختياري)",
    TextKey.SPACE_TRANSFER_SCREEN_LIVE_RATE to "السعر (للعرض فقط)",
    TextKey.SPACE_TRANSFER_SCREEN_AFTER_AMOUNTS to "بعد كتابة المبلغين",
    TextKey.SPACE_TRANSFER_SCREEN_RECORD to "سجّله",
)
