package app.masroufy.core

/** نصوص «التصنيفات» (`Categories`) ولوحة «تعديل تصنيف» (`CategoryEditSheet`) — منطقة الميزانيات (`TextsAreaBudgets.kt`). */
internal val MSA_BUDGETS_CATEGORIES: Map<TextKey, String> = mapOf(
    TextKey.CATS_TITLE to "التصنيفات",
    TextKey.CATS_INTRO to "مجموعة ← تصنيف رئيسي ← فرعي. لون الفرعي درجة من لون رئيسه.",
    TextKey.CATS_ERR_TITLE to "تعذّر تحميل التصنيفات",
    TextKey.CATS_ERR_BODY to "الأرقام والعمليات كما هي. أعد المحاولة.",
    TextKey.CATS_SUBS_ONE to "فرع واحد",
    TextKey.CATS_SUBS_TWO to "فرعان",
    TextKey.CATS_SUBS_FEW to "{0} فروع",
    TextKey.CATS_SUBS_MANY to "{0} فرعًا",
    TextKey.CATS_NO_SUBS to "بلا فروع",
    TextKey.CATS_EDIT_LABEL to "تعديل {0}",
    TextKey.CATS_ADD_SUB to "فرع جديد",
    TextKey.CATS_HIDDEN_INTRO to "لا تظهر عند اختيار التصنيف. ما له شرط يظهر وحده عندما تجيب عن سؤاله في ملفك.",
    TextKey.CATS_SHOW to "إظهار",
    TextKey.CATS_ADD_MAIN to "تصنيف رئيسي جديد",
    TextKey.CATS_RULES_LINK to "القواعد والتجار",
    TextKey.CATS_RULES_HINT to "كيف تأخذ العمليات تصنيفها تلقائيًا",
    TextKey.CATS_HIDDEN_UNDER to "ضمن {0} · {1}",
    TextKey.CATS_HIDDEN_WITH_SUBS to "{0} معه · {1}",
    TextKey.CATS_HIDDEN_BY_YOU to "أخفيته بنفسك",
    TextKey.CATS_REQ_HAS_CAR to "يظهر إن كانت لديك سيارة",
    TextKey.CATS_REQ_DEPENDENTS to "يظهر إن كنت تعول زوجة أو أولادًا",
    TextKey.CATS_REQ_RENTER to "يظهر إن كنت تسكن بالإيجار",
    TextKey.CATS_REQ_DOMESTIC to "يظهر إن كانت لديك عمالة منزلية",
    TextKey.CATS_REQ_BUSINESS to "يظهر إن كان لديك عمل خاص",
    TextKey.CATS_SAVED to "حُفظ التصنيف",
    TextKey.CATS_SAVED_RECOLOR to "حُفظ — وتغيّرت درجات فروعه معه",
    TextKey.CATS_ADDED to "أُضيف «{0}»",
    TextKey.CATS_HIDDEN_TOAST to "أُخفي «{0}» — تجده في المخفية",
    TextKey.CATS_SHOWN_TOAST to "عاد «{0}» إلى الاختيار",
    TextKey.CATS_HIDDEN_TITLE to "المخفية",
    TextKey.CATS_NO_GROUP to "بلا مجموعة",
    TextKey.CAT_EDIT_TITLE_EDIT to "تعديل تصنيف",
    TextKey.CAT_EDIT_TITLE_MAIN to "تصنيف رئيسي جديد",
    TextKey.CAT_EDIT_TITLE_SUB to "فرع جديد",
    TextKey.CAT_EDIT_NAME to "الاسم",
    TextKey.CAT_EDIT_NAME_HINT to "اسم التصنيف",
    TextKey.CAT_EDIT_PARENT to "تحت أي تصنيف؟",
    TextKey.CAT_EDIT_NO_PARENT to "رئيسي (بلا أب)",
    TextKey.CAT_EDIT_LOCKED to "لهذا التصنيف فروع، فلا يُنقل تحت تصنيف آخر.",
    TextKey.CAT_EDIT_GROUP to "المجموعة",
    TextKey.CAT_EDIT_COLOR to "اللون: {0}",
    TextKey.CAT_EDIT_CURRENT_COLOR to "لونه الحالي",
    TextKey.CAT_EDIT_SUBS_COLOR to "تغيير اللون يغيّر درجات فروعه معه.",
    TextKey.CAT_EDIT_MAIN_COLOR to "لكل تصنيف رئيسي لون مختلف.",
    TextKey.CAT_EDIT_SUB_NOTE to "اللون درجة من لون «{0}»، والمجموعة منه — يُحسبان تلقائيًا.",
    TextKey.CAT_EDIT_ICON to "الرمز",
    TextKey.CAT_EDIT_NEED_ICON to "اختر رمزًا من القائمة.",
    TextKey.CAT_EDIT_SAVE to "احفظ",
    TextKey.CAT_EDIT_ADD to "أضف",
    TextKey.CAT_EDIT_HIDE to "أخفِه من الاختيار",
    TextKey.CAT_EDIT_HIDE_NOTE_SUBS to "تُخفى فروعه معه. العمليات المصنفة عليه تبقى كما هي.",
    TextKey.CAT_EDIT_HIDE_NOTE to "العمليات المصنفة عليه تبقى كما هي، ويمكن إعادته من «المخفية».",
    TextKey.CAT_EDIT_PATH to "{0} › {1}",
)

internal val EGYPTIAN_BUDGETS_CATEGORIES: Map<TextKey, String> = mapOf(
    TextKey.CATS_TITLE to "التصنيفات",
    TextKey.CATS_INTRO to "مجموعة ← تصنيف أساسي ← فرعي. لون الفرعي درجة من لون أبوه.",
    TextKey.CATS_ERR_TITLE to "التصنيفات ما اتحمّلتش",
    TextKey.CATS_ERR_BODY to "الأرقام والعمليات زي ما هي. جرّب تاني.",
    TextKey.CATS_SUBS_ONE to "فرعي واحد",
    TextKey.CATS_SUBS_TWO to "فرعيين",
    TextKey.CATS_SUBS_FEW to "{0} فرعيات",
    TextKey.CATS_SUBS_MANY to "{0} فرعي",
    TextKey.CATS_NO_SUBS to "من غير فرعيات",
    TextKey.CATS_EDIT_LABEL to "عدّل {0}",
    TextKey.CATS_ADD_SUB to "فرعي جديد",
    TextKey.CATS_HIDDEN_INTRO to "مش بتظهر وإنت بتختار تصنيف. اللي ليه شرط بيظهر لوحده لما تجاوب سؤاله في ملفك.",
    TextKey.CATS_SHOW to "اظهره",
    TextKey.CATS_ADD_MAIN to "تصنيف أساسي جديد",
    TextKey.CATS_RULES_LINK to "القواعد والتجار",
    TextKey.CATS_RULES_HINT to "إزاي العمليات بتاخد تصنيفها لوحدها",
    TextKey.CATS_HIDDEN_UNDER to "تحت {0} · {1}",
    TextKey.CATS_HIDDEN_WITH_SUBS to "{0} معاه · {1}",
    TextKey.CATS_HIDDEN_BY_YOU to "إنت اللي خفيته",
    TextKey.CATS_REQ_HAS_CAR to "بيظهر لو عندك سيارة",
    TextKey.CATS_REQ_DEPENDENTS to "بيظهر لو بتعول زوجة أو أولاد",
    TextKey.CATS_REQ_RENTER to "بيظهر لو ساكن بإيجار",
    TextKey.CATS_REQ_DOMESTIC to "بيظهر لو عندك عمالة منزلية",
    TextKey.CATS_REQ_BUSINESS to "بيظهر لو عندك شغل خاص",
    TextKey.CATS_SAVED to "اتحفظ التصنيف",
    TextKey.CATS_SAVED_RECOLOR to "اتحفظ — ودرجات فرعياته اتغيرت معاه",
    TextKey.CATS_ADDED to "اتضاف «{0}»",
    TextKey.CATS_HIDDEN_TOAST to "اتخفى «{0}» — هتلاقيه في المخفية",
    TextKey.CATS_SHOWN_TOAST to "«{0}» رجع يظهر في الاختيار",
    TextKey.CATS_HIDDEN_TITLE to "المخفية",
    TextKey.CATS_NO_GROUP to "من غير مجموعة",
    TextKey.CAT_EDIT_TITLE_EDIT to "تعديل تصنيف",
    TextKey.CAT_EDIT_TITLE_MAIN to "تصنيف أساسي جديد",
    TextKey.CAT_EDIT_TITLE_SUB to "فرعي جديد",
    TextKey.CAT_EDIT_NAME to "الاسم",
    TextKey.CAT_EDIT_NAME_HINT to "اسم التصنيف",
    TextKey.CAT_EDIT_PARENT to "تحت أنهي تصنيف؟",
    TextKey.CAT_EDIT_NO_PARENT to "أساسي (من غير أب)",
    TextKey.CAT_EDIT_LOCKED to "التصنيف ده تحته فرعيات، فمينفعش يتنقل تحت تصنيف تاني.",
    TextKey.CAT_EDIT_GROUP to "المجموعة",
    TextKey.CAT_EDIT_COLOR to "اللون: {0}",
    TextKey.CAT_EDIT_CURRENT_COLOR to "لونه الحالي",
    TextKey.CAT_EDIT_SUBS_COLOR to "لو غيّرت اللون، درجات الفرعيات بتتغير معاه.",
    TextKey.CAT_EDIT_MAIN_COLOR to "كل تصنيف أساسي ليه لون مختلف.",
    TextKey.CAT_EDIT_SUB_NOTE to "اللون درجة من لون «{0}»، والمجموعة من عنده — بيتحسبوا لوحدهم.",
    TextKey.CAT_EDIT_ICON to "الرمز",
    TextKey.CAT_EDIT_NEED_ICON to "اختار رمز من القايمة.",
    TextKey.CAT_EDIT_SAVE to "احفظ",
    TextKey.CAT_EDIT_ADD to "ضيف",
    TextKey.CAT_EDIT_HIDE to "اخفيه من الاختيار",
    TextKey.CAT_EDIT_HIDE_NOTE_SUBS to "فرعياته بتستخبى معاه. العمليات اللي عليه بتفضل زي ما هي.",
    TextKey.CAT_EDIT_HIDE_NOTE to "العمليات اللي عليه بتفضل زي ما هي، وتقدر ترجّعه من «المخفية».",
    TextKey.CAT_EDIT_PATH to "{0} › {1}",
)

internal val ENGLISH_BUDGETS_CATEGORIES: Map<TextKey, String> = mapOf(
    TextKey.CATS_TITLE to "Categories",
    TextKey.CATS_INTRO to "Group ← main category ← subcategory. A subcategory's color is a shade of its parent's.",
    TextKey.CATS_ERR_TITLE to "Couldn't load the categories",
    TextKey.CATS_ERR_BODY to "Your numbers and operations are unchanged. Try again.",
    TextKey.CATS_SUBS_ONE to "One subcategory",
    TextKey.CATS_SUBS_TWO to "Two subcategories",
    TextKey.CATS_SUBS_FEW to "{0} subcategories",
    TextKey.CATS_SUBS_MANY to "{0} subcategories",
    TextKey.CATS_NO_SUBS to "No subcategories",
    TextKey.CATS_EDIT_LABEL to "Edit {0}",
    TextKey.CATS_ADD_SUB to "New subcategory",
    TextKey.CATS_HIDDEN_INTRO to "They don't show when you pick a category. One with a condition shows by itself once you answer its question in your profile.",
    TextKey.CATS_SHOW to "Show",
    TextKey.CATS_ADD_MAIN to "New main category",
    TextKey.CATS_RULES_LINK to "Rules and merchants",
    TextKey.CATS_RULES_HINT to "How operations get their category by themselves",
    TextKey.CATS_HIDDEN_UNDER to "Under {0} · {1}",
    TextKey.CATS_HIDDEN_WITH_SUBS to "{0} with it · {1}",
    TextKey.CATS_HIDDEN_BY_YOU to "You hid it",
    TextKey.CATS_REQ_HAS_CAR to "Shows if you have a car",
    TextKey.CATS_REQ_DEPENDENTS to "Shows if you support a spouse or children",
    TextKey.CATS_REQ_RENTER to "Shows if you rent your home",
    TextKey.CATS_REQ_DOMESTIC to "Shows if you have domestic help",
    TextKey.CATS_REQ_BUSINESS to "Shows if you run your own business",
    TextKey.CATS_SAVED to "Category saved",
    TextKey.CATS_SAVED_RECOLOR to "Saved — its subcategories' shades changed with it",
    TextKey.CATS_ADDED to "Added “{0}”",
    TextKey.CATS_HIDDEN_TOAST to "“{0}” hidden — find it under Hidden",
    TextKey.CATS_SHOWN_TOAST to "“{0}” is back in the list",
    TextKey.CATS_HIDDEN_TITLE to "Hidden",
    TextKey.CATS_NO_GROUP to "No group",
    TextKey.CAT_EDIT_TITLE_EDIT to "Edit category",
    TextKey.CAT_EDIT_TITLE_MAIN to "New main category",
    TextKey.CAT_EDIT_TITLE_SUB to "New subcategory",
    TextKey.CAT_EDIT_NAME to "Name",
    TextKey.CAT_EDIT_NAME_HINT to "Category name",
    TextKey.CAT_EDIT_PARENT to "Under which category?",
    TextKey.CAT_EDIT_NO_PARENT to "Main (no parent)",
    TextKey.CAT_EDIT_LOCKED to "This category has subcategories, so it can't move under another one.",
    TextKey.CAT_EDIT_GROUP to "Group",
    TextKey.CAT_EDIT_COLOR to "Color: {0}",
    TextKey.CAT_EDIT_CURRENT_COLOR to "Its current color",
    TextKey.CAT_EDIT_SUBS_COLOR to "Changing the color changes its subcategories' shades too.",
    TextKey.CAT_EDIT_MAIN_COLOR to "Each main category has its own color.",
    TextKey.CAT_EDIT_SUB_NOTE to "The color is a shade of “{0}”, and the group comes from it — both are set automatically.",
    TextKey.CAT_EDIT_ICON to "Icon",
    TextKey.CAT_EDIT_NEED_ICON to "Pick an icon from the list.",
    TextKey.CAT_EDIT_SAVE to "Save",
    TextKey.CAT_EDIT_ADD to "Add",
    TextKey.CAT_EDIT_HIDE to "Hide it from the list",
    TextKey.CAT_EDIT_HIDE_NOTE_SUBS to "Its subcategories are hidden with it. Operations in it stay as they are.",
    TextKey.CAT_EDIT_HIDE_NOTE to "Operations in it stay as they are, and you can bring it back from “Hidden”.",
    TextKey.CAT_EDIT_PATH to "{0} › {1}",
)
