package app.masroufy.core

/**
 * نصوص المناطق الثمانية مجمّعة (`Texts.kt` بياخدها مرة واحدة) — **الملف ده ثابت**: كل منطقة بتكتب في `TextsArea<المنطقة>.kt` بتاعها بس.
 * منطقة جديدة = قرار مكتوب (زي `ui/screens/Areas.kt`).
 */
internal val MSA_AREA_TEXTS: Map<UiKey, String> =
    MSA_AREA_HOME_TEXTS +
    MSA_AREA_OPERATIONS_TEXTS +
    MSA_AREA_IMPORTS_TEXTS +
    MSA_AREA_PEOPLE_TEXTS +
    MSA_AREA_DUES_TEXTS +
    MSA_AREA_INVESTMENT_TEXTS +
    MSA_AREA_MORE_TEXTS +
    MSA_AREA_ONBOARDING_TEXTS +
    MSA_AREA_BUDGETS_TEXTS

internal val EGYPTIAN_AREA_TEXTS: Map<UiKey, String> =
    EGYPTIAN_AREA_HOME_TEXTS +
    EGYPTIAN_AREA_OPERATIONS_TEXTS +
    EGYPTIAN_AREA_IMPORTS_TEXTS +
    EGYPTIAN_AREA_PEOPLE_TEXTS +
    EGYPTIAN_AREA_DUES_TEXTS +
    EGYPTIAN_AREA_INVESTMENT_TEXTS +
    EGYPTIAN_AREA_MORE_TEXTS +
    EGYPTIAN_AREA_ONBOARDING_TEXTS +
    EGYPTIAN_AREA_BUDGETS_TEXTS

internal val ENGLISH_AREA_TEXTS: Map<UiKey, String> =
    ENGLISH_AREA_HOME_TEXTS +
    ENGLISH_AREA_OPERATIONS_TEXTS +
    ENGLISH_AREA_IMPORTS_TEXTS +
    ENGLISH_AREA_PEOPLE_TEXTS +
    ENGLISH_AREA_DUES_TEXTS +
    ENGLISH_AREA_INVESTMENT_TEXTS +
    ENGLISH_AREA_MORE_TEXTS +
    ENGLISH_AREA_ONBOARDING_TEXTS +
    ENGLISH_AREA_BUDGETS_TEXTS
