package app.masroufy.core

/** «العمليات» بالمصري — الجزء التاني: «اربطها بـ» (شخص · مشروع أو حدث) · صفحة التاجر. */
internal val EGYPTIAN_OPERATIONS_LINK_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.LINK_PERSON_CARD to "شخص",
    UiKey.LINK_PERSON_SUB to "قسّمها على حد: دين عليه أو هدية ليه",
    UiKey.LINK_PERSON_SUB_MORE to "تقدر تقسّمها على حد تاني",
    UiKey.LINK_PERSON_LOCKED to "تحويل بين بلدينك — ما بيتربطش بشخص.",
    UiKey.LINK_PERSON_TRANSFER_SOON to "ربط الحوالة بشخص (سلفة ولا دعم ولا سداد) لسه مش متاح.",
    UiKey.LINK_PERSON_OPEN to "اربطها",
    UiKey.LINK_PERSON_ANOTHER to "حد تاني",
    UiKey.LINK_PERSON_LINE to "{0} — {1}",
    UiKey.LINK_PERSON_KIND_RECEIVABLE to "دين عليه",
    UiKey.LINK_PERSON_KIND_GIFT to "هدية ليه",
    UiKey.LINK_PERSON_TITLE to "اربطها بشخص",
    UiKey.LINK_PERSON_WHO to "مين؟",
    UiKey.LINK_PERSON_SEARCH to "دوّر أو اكتب اسم جديد",
    UiKey.LINK_PERSON_ADD_NEW to "+ ضيف «{0}»",
    UiKey.LINK_PERSON_WILL_ADD to "هيتضاف للأشخاص بالاسم ده.",
    UiKey.LINK_PERSON_OWES_YOU to "ليك عنده {0}",
    UiKey.LINK_PERSON_YOU_OWE to "عليك ليه {0}",
    UiKey.LINK_PERSON_CUSTODY to "أمانة ليه عندك {0}",
    UiKey.LINK_PERSON_NO_BALANCE to "مفيش رصيد بينكم",
    UiKey.LINK_PERSON_KIND to "نوع الربط",
    UiKey.LINK_PERSON_NOTE_RECEIVABLE to "دفعتها عنه، وبتتسجل دين عليه في «ليك».",
    UiKey.LINK_PERSON_NOTE_GIFT to "هدية مش هترجع — بتفضل من مصروفك وبتبان في سجله.",
    UiKey.LINK_PERSON_NOTE_NONE to "اختار النوع وهتشوف أثره تحت.",
    UiKey.LINK_PERSON_AMOUNT to "نصيبه من العملية",
    UiKey.LINK_PERSON_EFFECT_TITLE to "هيأثر إزاي؟",
    UiKey.LINK_PERSON_EFFECT_SPEND to "مصروفك من العملية",
    UiKey.LINK_PERSON_EFFECT_OWES to "ليك عند {0}",
    UiKey.LINK_PERSON_EFFECT_DEBT_ON to "دين على {0}",
    UiKey.LINK_PERSON_SAME to "زي ما هو",
    UiKey.LINK_PERSON_NOTHING to "ولا حاجة",
    UiKey.LINK_PERSON_PICK_BOTH to "اختار الشخص والنوع",
    UiKey.LINK_PERSON_PICK_KIND to "اختار النوع",
    UiKey.LINK_PERSON_WRITE_AMOUNT to "اكتب المبلغ",
    UiKey.LINK_PERSON_EFFECT_HERE to "وهيظهر الأثر هنا",
    UiKey.LINK_PERSON_ERR_PERSON to "اختار الشخص أو اكتب اسم جديد.",
    UiKey.LINK_PERSON_ERR_KIND to "اختار: دين عليه ولا هدية ليه.",
    UiKey.LINK_PERSON_ERR_AMOUNT to "اكتب مبلغ أكبر من صفر.",
    UiKey.LINK_PERSON_SAVE to "احفظ الربط",
    UiKey.LINK_PROJECT_EVENT_CARD to "مشروع أو حدث",
    UiKey.LINK_PROJECT_EVENT_SUB_NONE to "لسه ما اتربطتش",
    UiKey.LINK_PROJECT_EVENT_SUB_TAGS to "علامات على العملية — ما بتغيّرش أي مجموع.",
    UiKey.LINK_PROJECT_EVENT_LOCKED to "تحويل بين بلدينك — ما بيتربطش بمشروع ولا حدث.",
    UiKey.LINK_PROJECT_EVENT_PROJECT_TAG to "مشروع:",
    UiKey.LINK_PROJECT_EVENT_EVENT_TAG to "حدث:",
    UiKey.LINK_PROJECT_EVENT_NAME_SHARE to "{0}، {1}",
    UiKey.LINK_PROJECT_EVENT_PERCENT to "{0}٪",
    UiKey.LINK_PROJECT_EVENT_PERCENT_SIGN to "٪",
    UiKey.LINK_PROJECT_EVENT_TITLE to "اربطها بمشروع أو حدث",
    UiKey.LINK_PROJECT_EVENT_PROJECTS to "المشاريع",
    UiKey.LINK_PROJECT_EVENT_PROJECTS_HINT to "ممكن أكتر من مشروع، وكل مشروع بيحسبها مرة واحدة.",
    UiKey.LINK_PROJECT_EVENT_NO_PROJECTS to "مفيش مشاريع لسه — ضيفها من «المشاريع».",
    UiKey.LINK_PROJECT_EVENT_EVENT to "الحدث",
    UiKey.LINK_PROJECT_EVENT_EVENT_HINT to "حدث واحد بس للعملية، وبنسبة من مبلغها.",
    UiKey.LINK_PROJECT_EVENT_EVENT_HINT_IN to "الفلوس الجاية بتتربط بالحدث كنقطة — من صفحة الحدث «سجّل النقوط».",
    UiKey.LINK_PROJECT_EVENT_NONE to "من غير حدث",
    UiKey.LINK_PROJECT_EVENT_HOSTED to "حدث {0}",
    UiKey.LINK_PROJECT_EVENT_MINE to "حدثك",
    UiKey.LINK_PROJECT_EVENT_WHEN to "{0}، {1}",
    UiKey.LINK_PROJECT_EVENT_NOW_LINKED to "، ومربوطة بيه دلوقتي",
    UiKey.LINK_PROJECT_EVENT_NOT_ON_ANY to "العملية مش على أي حدث.",
    UiKey.LINK_PROJECT_EVENT_CONFLICT_TITLE to "مربوطة بـ«{0}» قبل كده",
    UiKey.LINK_PROJECT_EVENT_CONFLICT_BODY to "العملية الواحدة بتتربط بحدث واحد بس. فكّها الأول، وبعدين تتربط بـ«{0}».",
    UiKey.LINK_PROJECT_EVENT_UNLINK to "فك الربط من «{0}»",
    UiKey.LINK_PROJECT_EVENT_SHARE to "نصيب الحدث من العملية",
    UiKey.LINK_PROJECT_EVENT_RANGE to "النسبة من {0} لـ{1}",
    UiKey.LINK_PROJECT_EVENT_ON to "على «{0}»",
    UiKey.LINK_PROJECT_EVENT_OUTSIDE to "الباقي برّه الحدث",
    UiKey.LINK_PROJECT_EVENT_NOTE to "الربط علامة على العملية — مش بيغيّر مصروف الشهر ولا تصنيفها، والنسبة بتتحفظ مع الربط.",
    UiKey.LINK_PROJECT_EVENT_SAVE to "احفظ",
    UiKey.LINK_PROJECT_EVENT_ERR_PENDING to "فك الربط القديم الأول، أو اختار نفس الحدث.",
    UiKey.LINK_PROJECT_EVENT_ERR_SHARE to "نسبة الحدث من العملية لازم تبقى من ١ لـ١٠٠.",
    UiKey.MERCHANT_PROFILE_TITLE to "صفحة التاجر",
    UiKey.MERCHANT_PROFILE_IN_PERIOD to "{0} في {1}",
    UiKey.MERCHANT_PROFILE_RENAME to "غيّر الاسم",
    UiKey.MERCHANT_PROFILE_SPENT_PERIOD to "صرفت عنده في {0}",
    UiKey.MERCHANT_PROFILE_SPENT_ALL to "من أول عملية",
    UiKey.MERCHANT_PROFILE_CATEGORY_IN to "تصنيفه في {0}",
    UiKey.MERCHANT_PROFILE_HINT_SAVED to "بيتطبق على عملياته الجاية قبل أي قاعدة، وفي {0} بس.",
    UiKey.MERCHANT_PROFILE_HINT_SUGGESTED to "من قاعدة عامة — اختار تصنيفه مرة ويتحفظ له على طول.",
    UiKey.MERCHANT_PROFILE_HINT_OTHER_COUNTRY to "التاجر متصنف كده في بلدك التانية — اقتراح، أكّده لو صح.",
    UiKey.MERCHANT_PROFILE_NOT_SAVED to "المحل ده لسه ما اتحفظش، فمش هيتعدل تصنيفه ولا اسمه من هنا.",
    UiKey.MERCHANT_PROFILE_CATEGORY_BODY to "اختيارك بيتحفظ للتاجر ده على طول.",
    UiKey.MERCHANT_PROFILE_ALIASES to "أسامي تانية في الكشف",
    UiKey.MERCHANT_PROFILE_ALIAS_HINT to "زي ما بيظهر في رسالة البنك",
    UiKey.MERCHANT_PROFILE_ALIAS_NOTE to "لما أي اسم منهم يظهر في رسالة أو كشف، العملية بتتنسب للتاجر ده.",
    UiKey.MERCHANT_PROFILE_ALIAS_ADDED to "اتضاف — أي عملية بالاسم ده بتتنسب للتاجر ده",
    UiKey.MERCHANT_PROFILE_ALIAS_EXISTS to "الاسم ده موجود أصلًا",
    UiKey.MERCHANT_PROFILE_LIST to "عملياته",
    UiKey.MERCHANT_PROFILE_NONE_PERIOD to "مفيش عمليات ليه في {0}.",
    UiKey.MERCHANT_PROFILE_RENAME_TITLE to "غيّر اسم التاجر",
    UiKey.MERCHANT_PROFILE_RENAME_BODY to "الاسم ده ليك انت بس. المطابقة مع الكشف بتفضل بالاسم الأصلي.",
    UiKey.MERCHANT_PROFILE_RENAMED to "اتحفظ الاسم",
)
