package app.masroufy.core

/** «العمليات» بالإنجليزي (كتابة Claude — مستني مراجعة المالك §40) — الجزء الأول: القايمة · القايمة السائلة · التفاصيل · التصنيف · الوسوم · التصفية. */
internal val ENGLISH_OPERATIONS_LIST_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.OPERATIONS_FILTER to "Filter operations",
    TextKey.OPERATIONS_PERIOD to "Month",
    TextKey.OPERATIONS_TAB_OPS to "Operations",
    TextKey.OPERATIONS_TAB_BUDGETS to "Budgets",
    TextKey.OPERATIONS_TAB_DUES to "Dues",
    TextKey.OPERATIONS_ERROR_TITLE to "Couldn't load operations",
    TextKey.OPERATIONS_ERROR_BODY to "Check your connection and try again.",
    TextKey.OPERATIONS_EMPTY_TITLE to "No operations in {0}",
    TextKey.OPERATIONS_EMPTY_BODY to "Add an operation or import your statement.",
    TextKey.OPERATIONS_INCOME to "Income this month",
    TextKey.OPERATIONS_EXPENSE to "Real spending",
    TextKey.OPERATIONS_APPROX_NOTE to "Some types are estimates until you confirm them.",
    TextKey.OPERATIONS_TODAY to "Today",
    TextKey.OPERATIONS_YESTERDAY to "Yesterday",
    TextKey.OPERATIONS_ROW_MOVE to "{0}, {1} → {2}",
    TextKey.OPERATIONS_ROW_ACCOUNT to "account ending {0}",
    TextKey.OPERATIONS_ROW_FROM to "From {0}",
    TextKey.OPERATIONS_ROW_TO to "To {0}",
    TextKey.OPERATIONS_ROW_UNCLASSIFIED to "Uncategorized",
    TextKey.OPERATIONS_ROW_ACTIONS to "Actions for {0}",
    TextKey.OPERATIONS_UNRECORDED to "Not recorded",
    TextKey.OPERATIONS_COUNT_ONE to "1 operation",
    TextKey.OPERATIONS_COUNT_TWO to "2 operations",
    TextKey.OPERATIONS_COUNT_FEW to "{0} operations",
    TextKey.OPERATIONS_COUNT_MANY to "{0} operations",
    TextKey.OPERATIONS_SMS_ONE to "1 bank message awaits your confirmation",
    TextKey.OPERATIONS_SMS_TWO to "2 bank messages await your confirmation",
    TextKey.OPERATIONS_SMS_FEW to "{0} bank messages await your confirmation",
    TextKey.OPERATIONS_SMS_MANY to "{0} bank messages await your confirmation",
    TextKey.OPERATIONS_BANNER_REVIEW to "{0} with an unconfirmed type",
    TextKey.OPERATIONS_PARTIES_ONE to "1 party awaits your answer",
    TextKey.OPERATIONS_PARTIES_TWO to "2 parties await your answer",
    TextKey.OPERATIONS_PARTIES_FEW to "{0} parties await your answer",
    TextKey.OPERATIONS_PARTIES_MANY to "{0} parties await your answer",
    TextKey.OPERATIONS_SAVE_FAILED to "Couldn't save — nothing changed. Try again.",
    TextKey.OPERATION_MENU_TITLE to "Operation actions",
    TextKey.OPERATION_MENU_DETAIL to "View details",
    TextKey.OPERATION_MENU_PERSON to "Assign an amount to someone",
    TextKey.OPERATION_MENU_ALL to "All actions",
    TextKey.OPERATION_DETAIL_TITLE to "Operation details",
    TextKey.OPERATION_DETAIL_ERROR_TITLE to "Couldn't load the operation",
    TextKey.OPERATION_DETAIL_SUB to "{0}, {1}",
    TextKey.OPERATION_DETAIL_IN to "money in",
    TextKey.OPERATION_DETAIL_OUT to "money out",
    TextKey.OPERATION_DETAIL_MERCHANT to "Merchant page",
    TextKey.OPERATION_DETAIL_LOCK to "Date and direction come from the source and can't be edited",
    TextKey.OPERATION_DETAIL_LOCK_CASH to "The amount is the cash-count difference",
    TextKey.OPERATION_DETAIL_CASH_TITLE to "This isn't a recorded operation",
    TextKey.OPERATION_DETAIL_CASH_BODY to "This is the cash-count difference. It counts in this month's spending with a red dot until you say what it was for.",
    TextKey.OPERATION_DETAIL_WALLET to "Wallet",
    TextKey.OPERATION_DETAIL_CATEGORY to "Category",
    TextKey.OPERATION_DETAIL_KIND to "Type",
    TextKey.OPERATION_DETAIL_KIND_WAITING to "Waiting for you to set the type",
    TextKey.OPERATION_DETAIL_WAITING_CHIP to "Waiting",
    TextKey.OPERATION_DETAIL_KIND_ESTIMATED to "Estimated until you confirm it",
    TextKey.OPERATION_DETAIL_SUGGESTED to "Suggested",
    TextKey.OPERATION_DETAIL_SUGGESTED_HINT to "Needs your confirmation",
    TextKey.OPERATION_DETAIL_CONFIRMED_CHIP to "Confirmed",
    TextKey.OPERATION_DETAIL_CHANGE to "Change",
    TextKey.OPERATION_DETAIL_CONFIRM to "Confirm",
    TextKey.OPERATION_DETAIL_CATEGORIZE to "Categorize",
    TextKey.OPERATION_DETAIL_CONFIRMED to "Category confirmed",
    TextKey.OPERATION_DETAIL_REMEMBERED to "Done — “{0}” will always be “{1}”",
    TextKey.OPERATION_DETAIL_CATEGORIZED to "Done — categorized as “{0}”",
    TextKey.OPERATION_DETAIL_LINK_TITLE to "Link it to",
    TextKey.CATEGORY_PICKER_CASH_TITLE to "What was it spent on?",
    TextKey.CATEGORY_PICKER_TITLE to "Category of “{0}”",
    TextKey.CATEGORY_PICKER_EMPTY to "No categories yet.",
    TextKey.TAGS_SHEET_LABEL to "Tags",
    TextKey.TAGS_SHEET_NONE to "No tags",
    TextKey.TAGS_SHEET_ADD_TRIGGER to "Add a tag",
    TextKey.TAGS_SHEET_EDIT to "Edit",
    TextKey.TAGS_SHEET_TITLE to "Operation tags",
    TextKey.TAGS_SHEET_BODY to "Tags are for search and reports only — they don't change the amount or count twice. Tags are shared across countries.",
    TextKey.TAGS_SHEET_EMPTY_LINE to "No tags on this operation.",
    TextKey.TAGS_SHEET_INPUT to "New tag or search",
    TextKey.TAGS_SHEET_ADD to "Add",
    TextKey.TAGS_SHEET_COUNTER to "{0}/{1}",
    TextKey.TAGS_SHEET_ALL to "Your tags",
    TextKey.TAGS_SHEET_NO_MATCH to "No tag with this name — “Add” creates it.",
    TextKey.TAGS_SHEET_ALL_ON to "All your tags are on this operation.",
    TextKey.TAGS_SHEET_DONE to "Done",
    TextKey.TAGS_SHEET_REMOVE to "Remove tag {0}",
    TextKey.TAGS_SHEET_ADD_ONE to "Add tag {0}",
    TextKey.TAGS_SHEET_ADDED to "Added “{0}”",
    TextKey.TAGS_SHEET_CREATED to "Created and added “{0}”",
    TextKey.TAGS_SHEET_ALREADY to "“{0}” is already on this operation",
    TextKey.TAGS_SHEET_REMOVED to "Removed “{0}”",
    TextKey.OPERATION_FILTERS_TITLE to "Filter operations",
    TextKey.OPERATION_FILTERS_RESULTS to "Results",
    TextKey.OPERATION_FILTERS_CLEAR to "Clear all",
    TextKey.OPERATION_FILTERS_SEARCH to "Store, person, note…",
    TextKey.OPERATION_FILTERS_AMOUNT to "Amount ({0})",
    TextKey.OPERATION_FILTERS_NEAR to "Close to it ±5%",
    TextKey.OPERATION_FILTERS_NEAR_CHIP to "≈ {0}",
    TextKey.OPERATION_FILTERS_PERIOD to "Period",
    TextKey.OPERATION_FILTERS_THIS to "This month",
    TextKey.OPERATION_FILTERS_LAST to "Last month",
    TextKey.OPERATION_FILTERS_THREE to "Last 3 months",
    TextKey.OPERATION_FILTERS_KIND to "Type",
    TextKey.OPERATION_FILTERS_KIND_OUT to "Spending",
    TextKey.OPERATION_FILTERS_KIND_IN to "Income",
    TextKey.OPERATION_FILTERS_KIND_MOVE to "Between your wallets",
    TextKey.OPERATION_FILTERS_KIND_DEBT to "Debts and installments",
    TextKey.OPERATION_FILTERS_REVIEW to "Review",
    TextKey.OPERATION_FILTERS_REVIEW_ALL to "All",
    TextKey.OPERATION_FILTERS_REVIEW_OK to "Confirmed",
    TextKey.OPERATION_FILTERS_REVIEW_NEEDS to "Needs confirming",
    TextKey.OPERATION_FILTERS_QUOTED to "“{0}”",
    TextKey.OPERATION_FILTERS_DROP to "Remove {0}",
    TextKey.OPERATION_FILTERS_NONE to "No results",
    TextKey.OPERATION_FILTERS_NONE_BODY to "Remove a filter or two and try again.",
    TextKey.OPERATION_FILTERS_SHOW to "Show {0}",
    TextKey.OPERATION_FILTERS_EDIT to "Edit filters",
)
