package app.masroufy.core

/**
 * الاقتراحات تحت مستطيل الكتابة (§78-٥ + النموذج): «بتسأل عنها كتير» · أسئلة المتابعة · اقتراحات الصفحة. كل اقتراح سؤال جاهز
 * (والاقتراح بيتبعت بنيته واسمه مباشرة — مش بيتفهم من النص تاني).
 */
internal val MSA_ASSIST_QUESTION_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_CHIP_VOICE to "أضف عملية بصوتي",
    TextKey.ASSIST_CHIPS_FOLLOW to "أسئلة قريبة",
    TextKey.ASSIST_CHIPS_FREQUENT to "تسأل عنها كثيرًا",
    TextKey.ASSIST_CHIPS_PAGE to "اقتراحات لصفحة {0}",
    TextKey.ASSIST_Q_SPEND_TOTAL to "كم صرفت هذا الشهر؟",
    TextKey.ASSIST_Q_SPEND_BIGGEST to "على ماذا صرفت أكثر؟",
    TextKey.ASSIST_Q_SPEND_COMPARE to "هل صرفت أكثر من الشهر الماضي؟",
    TextKey.ASSIST_Q_INCOME to "كم دخلي هذا الشهر؟",
    TextKey.ASSIST_Q_REMAINING to "كم بقي لي؟",
    TextKey.ASSIST_Q_DAILY to "كم أصرف في اليوم؟",
    TextKey.ASSIST_Q_FORECAST to "كم سأصرف بنهاية الشهر؟",
    TextKey.ASSIST_Q_BUDGET to "هل أنا على الخطة؟",
    TextKey.ASSIST_Q_CASH to "كم معي كاش؟",
    TextKey.ASSIST_Q_ON_HAND to "كم رصيدي الآن؟",
    TextKey.ASSIST_Q_OWED_TO_ME to "من عليه فلوس لي؟",
    TextKey.ASSIST_Q_I_OWE to "لمن عليّ فلوس؟",
    TextKey.ASSIST_Q_OVERDUE to "من تأخر في السداد؟",
    TextKey.ASSIST_Q_NEXT_SALARY to "متى الراتب؟",
    TextKey.ASSIST_Q_SALARY to "كم راتبي؟",
    TextKey.ASSIST_Q_GOAL to "أين وصلت في خطة الادخار؟",
    TextKey.ASSIST_Q_ZAKAT to "كم زكاتي؟",
    TextKey.ASSIST_Q_DUES to "ما المستحق عليّ قبل الراتب؟",
    TextKey.ASSIST_Q_BILLS to "متى فواتيري القادمة؟",
    TextKey.ASSIST_Q_PENDING to "كم عملية تحتاج تأكيدًا؟",
    TextKey.ASSIST_Q_ASSETS to "كم قيمة أصولي؟",
    TextKey.ASSIST_Q_EVENTS to "كم صرفت على المناسبة؟",
    TextKey.ASSIST_Q_PROJECTS to "كم صرفت على المشروع؟",
    TextKey.ASSIST_Q_ROSCA to "متى دوري في الجمعية؟",
    TextKey.ASSIST_Q_INSTALLMENTS to "كم قسطًا بقي؟",
    TextKey.ASSIST_Q_OCCASIONS to "ما المناسبات القادمة؟",
    TextKey.ASSIST_Q_SPLIT to "قسّم فاتورة",
    TextKey.ASSIST_QN_SPEND_ON to "كم صرفت على {0}؟",
    TextKey.ASSIST_QN_CAP to "كم بقي في سقف {0}؟",
    TextKey.ASSIST_QN_SPEND_AT to "كم صرفت عند {0}؟",
    TextKey.ASSIST_QN_LAST_AT to "آخر مرة عند {0}؟",
    TextKey.ASSIST_QN_PERSON to "كم لي عند {0}؟",
    TextKey.ASSIST_QN_GAVE to "كم أعطيت {0}؟",
    TextKey.ASSIST_QN_GOAL to "أين وصلت في {0}؟",
    TextKey.ASSIST_QN_BILL to "متى {0}؟",
    TextKey.ASSIST_QN_RECORD to "سجّل {0}",
    TextKey.ASSIST_QN_COMPARE to "هل صرفت على {0} أكثر من الشهر الماضي؟",
)

internal val EGYPTIAN_ASSIST_QUESTION_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_CHIP_VOICE to "ضيف عملية بصوتي",
    TextKey.ASSIST_CHIPS_FOLLOW to "أسئلة قريبة",
    TextKey.ASSIST_CHIPS_FREQUENT to "بتسأل عنها كتير",
    TextKey.ASSIST_CHIPS_PAGE to "اقتراحات لصفحة {0}",
    TextKey.ASSIST_Q_SPEND_TOTAL to "صرفت كام الشهر ده؟",
    TextKey.ASSIST_Q_SPEND_BIGGEST to "صرفت أكتر على إيه؟",
    TextKey.ASSIST_Q_SPEND_COMPARE to "صرفت أكتر من الشهر اللي فات؟",
    TextKey.ASSIST_Q_INCOME to "دخلي كام الشهر ده؟",
    TextKey.ASSIST_Q_REMAINING to "فاضلي كام؟",
    TextKey.ASSIST_Q_DAILY to "أقدر أصرف كام في اليوم؟",
    TextKey.ASSIST_Q_FORECAST to "هوصل لكام آخر الشهر؟",
    TextKey.ASSIST_Q_BUDGET to "أنا ماشي على الخطة؟",
    TextKey.ASSIST_Q_CASH to "معايا كام كاش؟",
    TextKey.ASSIST_Q_ON_HAND to "معايا كام دلوقتي؟",
    TextKey.ASSIST_Q_OWED_TO_ME to "مين عليه فلوس ليّا؟",
    TextKey.ASSIST_Q_I_OWE to "عليّا فلوس لمين؟",
    TextKey.ASSIST_Q_OVERDUE to "مين اتأخر في السداد؟",
    TextKey.ASSIST_Q_NEXT_SALARY to "إمتى المرتب؟",
    TextKey.ASSIST_Q_SALARY to "مرتبي كام؟",
    TextKey.ASSIST_Q_GOAL to "وصلت لفين في التحويش؟",
    TextKey.ASSIST_Q_ZAKAT to "زكاتي كام؟",
    TextKey.ASSIST_Q_DUES to "إيه اللي عليّا قبل المرتب؟",
    TextKey.ASSIST_Q_BILLS to "فواتيري الجاية إمتى؟",
    TextKey.ASSIST_Q_PENDING to "كام عملية محتاجة تأكيد؟",
    TextKey.ASSIST_Q_ASSETS to "أصولي بكام؟",
    TextKey.ASSIST_Q_EVENTS to "صرفت كام على المناسبة؟",
    TextKey.ASSIST_Q_PROJECTS to "المشروع صرف كام؟",
    TextKey.ASSIST_Q_ROSCA to "دوري في الجمعية إمتى؟",
    TextKey.ASSIST_Q_INSTALLMENTS to "فاضل كام قسط؟",
    TextKey.ASSIST_Q_OCCASIONS to "إيه المناسبات الجاية؟",
    TextKey.ASSIST_Q_SPLIT to "قسّم فاتورة",
    TextKey.ASSIST_QN_SPEND_ON to "صرفت كام على {0}؟",
    TextKey.ASSIST_QN_CAP to "فاضل كام في سقف {0}؟",
    TextKey.ASSIST_QN_SPEND_AT to "صرفت كام عند {0}؟",
    TextKey.ASSIST_QN_LAST_AT to "آخر مرة عند {0}؟",
    TextKey.ASSIST_QN_PERSON to "ليّا كام عند {0}؟",
    TextKey.ASSIST_QN_GAVE to "اديت {0} كام؟",
    TextKey.ASSIST_QN_GOAL to "وصلت لفين في {0}؟",
    TextKey.ASSIST_QN_BILL to "{0} إمتى؟",
    TextKey.ASSIST_QN_RECORD to "سجّل {0}",
    TextKey.ASSIST_QN_COMPARE to "صرفت على {0} أكتر من الشهر اللي فات؟",
)

internal val ENGLISH_ASSIST_QUESTION_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_CHIP_VOICE to "Add by voice",
    TextKey.ASSIST_CHIPS_FOLLOW to "Related",
    TextKey.ASSIST_CHIPS_FREQUENT to "You ask often",
    TextKey.ASSIST_CHIPS_PAGE to "Suggestions for {0}",
    TextKey.ASSIST_Q_SPEND_TOTAL to "How much did I spend this month?",
    TextKey.ASSIST_Q_SPEND_BIGGEST to "Where did most of my money go?",
    TextKey.ASSIST_Q_SPEND_COMPARE to "Am I spending more than last month?",
    TextKey.ASSIST_Q_INCOME to "What's my income this month?",
    TextKey.ASSIST_Q_REMAINING to "How much do I have left?",
    TextKey.ASSIST_Q_DAILY to "How much can I spend a day?",
    TextKey.ASSIST_Q_FORECAST to "Where will I end the month?",
    TextKey.ASSIST_Q_BUDGET to "Am I on budget?",
    TextKey.ASSIST_Q_CASH to "How much cash do I have?",
    TextKey.ASSIST_Q_ON_HAND to "What's my balance now?",
    TextKey.ASSIST_Q_OWED_TO_ME to "Who owes me?",
    TextKey.ASSIST_Q_I_OWE to "Who do I owe?",
    TextKey.ASSIST_Q_OVERDUE to "Who's overdue?",
    TextKey.ASSIST_Q_NEXT_SALARY to "When is payday?",
    TextKey.ASSIST_Q_SALARY to "What's my salary?",
    TextKey.ASSIST_Q_GOAL to "How's my savings plan?",
    TextKey.ASSIST_Q_ZAKAT to "How much zakat do I owe?",
    TextKey.ASSIST_Q_DUES to "What's due before payday?",
    TextKey.ASSIST_Q_BILLS to "When are my next bills?",
    TextKey.ASSIST_Q_PENDING to "How many need confirming?",
    TextKey.ASSIST_Q_ASSETS to "What are my assets worth?",
    TextKey.ASSIST_Q_EVENTS to "How much did the event cost?",
    TextKey.ASSIST_Q_PROJECTS to "How much did the project cost?",
    TextKey.ASSIST_Q_ROSCA to "When is my rosca turn?",
    TextKey.ASSIST_Q_INSTALLMENTS to "How many installments left?",
    TextKey.ASSIST_Q_OCCASIONS to "What occasions are coming?",
    TextKey.ASSIST_Q_SPLIT to "Split a bill",
    TextKey.ASSIST_QN_SPEND_ON to "How much on {0}?",
    TextKey.ASSIST_QN_CAP to "What's left of the {0} cap?",
    TextKey.ASSIST_QN_SPEND_AT to "How much at {0}?",
    TextKey.ASSIST_QN_LAST_AT to "Last time at {0}?",
    TextKey.ASSIST_QN_PERSON to "How much does {0} owe me?",
    TextKey.ASSIST_QN_GAVE to "How much did I give {0}?",
    TextKey.ASSIST_QN_GOAL to "How's {0} going?",
    TextKey.ASSIST_QN_BILL to "When is {0}?",
    TextKey.ASSIST_QN_RECORD to "Record {0}",
    TextKey.ASSIST_QN_COMPARE to "Am I spending more on {0} than last month?",
)
