package app.masroufy.core

/** نصوص «خطط الادخار» (`SavingsGoals`) و«تفاصيل الخطة» (`GoalDetail`) و«خطة جديدة» و«تعديل الخطة» (`GoalEditSheet`) — منطقة الميزانيات. */
internal val MSA_BUDGETS_GOALS: Map<TextKey, String> = mapOf(
    TextKey.GOALS_TITLE to "خطط الادخار",
    TextKey.GOALS_NEW to "خطة جديدة",
    TextKey.GOALS_EMPTY_TITLE to "لا توجد خطط ادخار",
    TextKey.GOALS_EMPTY_BODY to "أنشئ خطة بهدف وموعد، ونخبرك أين يُفترض أن تكون اليوم.",
    TextKey.GOALS_INTRO to "النجمة على خطة واحدة فقط — عليها يقيس المساعد عادات الصرف.",
    TextKey.GOALS_SUB_UNTIL to "حتى {0}، {1}",
    TextKey.GOALS_MANUAL to "إيداعات يدوية",
    TextKey.GOALS_LINKED_OTHER to "حساب مربوط",
    TextKey.GOALS_WALLET_LAST4 to "{0} ⁦•••• {1}⁩",
    TextKey.GOALS_CHIP_REACHED to "اكتملت",
    TextKey.GOALS_CHIP_NEW to "جديدة",
    TextKey.GOALS_CHIP_AHEAD to "متقدّمة",
    TextKey.GOALS_CHIP_BEHIND to "متأخرة",
    TextKey.GOALS_CHIP_OVERDUE to "فات موعدها",
    TextKey.GOALS_OF to "من {0}، {1}٪",
    TextKey.GOALS_OF_ONLY to "من {0}",
    TextKey.GOALS_STAT_EXPECTED to "المفروض اليوم",
    TextKey.GOALS_STAT_AHEAD to "متقدّمة بـ",
    TextKey.GOALS_STAT_BEHIND to "متأخرة بـ",
    TextKey.GOALS_STAT_ON_TIME to "في الموعد",
    TextKey.GOALS_STAT_REQUIRED to "المطلوب شهريًا",
    TextKey.GOALS_STAT_REACH to "ستصل إلى",
    TextKey.GOALS_STAT_AFTER_30 to "بعد ٣٠ يومًا",
    TextKey.GOALS_STAT_LEFT to "الباقي",
    TextKey.GOALS_OPEN_MANUAL to "التفاصيل والإيداعات",
    TextKey.GOALS_OPEN_LINKED to "التفاصيل",
    TextKey.GOALS_STAR_ADD to "ضع النجمة على هذه الخطة",
    TextKey.GOALS_STAR_REMOVE to "أزل النجمة",
    TextKey.GOALS_STARRED to "النجمة على «{0}» — عليها يقيس المساعد عاداتك",
    TextKey.GOALS_UNSTARRED to "أُزيلت النجمة — يقيس المساعد على أقرب خطة نشطة",
    TextKey.GOALS_ARCHIVED to "المؤرشفة ({0})",
    TextKey.GOALS_ARCHIVED_ROW to "{0} / {1}",
    TextKey.GOALS_METHOD to "المفروض اليوم = خط مستقيم بالأيام من البداية إلى الموعد. «ستصل إلى» بمعدلك منذ البداية، ويظهر بعد ٣٠ يومًا.",
    TextKey.GOAL_DETAIL_TITLE to "خطة «{0}»",
    TextKey.GOAL_DETAIL_TITLE_STAR to "★ خطة «{0}»",
    TextKey.GOAL_DETAIL_SUB to "الهدف {0}، {1}",
    TextKey.GOAL_DETAIL_SAVED to "المدّخر",
    TextKey.GOAL_DETAIL_SAVED_LINKED to "المدّخر (رصيد الحساب كله)",
    TextKey.GOAL_DETAIL_PROGRESS to "{0}٪، بقي {1}",
    TextKey.GOAL_DETAIL_REACHED to "{0}٪، اكتملت!",
    TextKey.GOAL_DETAIL_UNKNOWN to "رصيد الحساب غير معروف — كل الأرقام غير متاحة",
    TextKey.GOAL_DETAIL_LINKED to "مربوطة بـ«{0}» — الخطة مربوطة بحساب، والمدّخر يُحسب من رصيده كله.",
    TextKey.GOAL_DETAIL_DEP_LABEL to "مبلغ الإيداع",
    TextKey.GOAL_DETAIL_DEPOSIT to "أودِع",
    TextKey.GOAL_DETAIL_EDIT to "تعديل",
    TextKey.GOAL_DETAIL_ARCHIVE to "أرشفة الخطة",
    TextKey.GOAL_DETAIL_DEPOSITED to "أُودِع {0} في «{1}»",
    TextKey.GOAL_DETAIL_DONE to "أحسنت! اكتملت خطة «{0}»",
    TextKey.GOAL_DETAIL_ARCHIVED_TOAST to "أُرشفت «{0}» — لا تُحذف، وتبقى في المؤرشفة",
    TextKey.GOAL_NEW_SUB to "الخطة تُؤرشف فقط ولا تُحذف.",
    TextKey.GOAL_NEW_NAME to "اسم الخطة",
    TextKey.GOAL_NEW_NAME_HINT to "مثلًا: سيارة",
    TextKey.GOAL_NEW_TARGET to "المبلغ المستهدف ({0})",
    TextKey.GOAL_NEW_WHEN to "حتى متى؟",
    TextKey.GOAL_NEW_YEAR_END to "آخر السنة",
    TextKey.GOAL_NEW_ONE_YEAR to "بعد سنة",
    TextKey.GOAL_NEW_TWO_YEARS to "بعد سنتين",
    TextKey.GOAL_NEW_HOW to "كيف تدّخر؟",
    TextKey.GOAL_NEW_MANUAL to "إيداعات يدوية",
    TextKey.GOAL_NEW_LINKED to "حساب مخصص",
    TextKey.GOAL_NEW_WHICH to "أي حساب؟",
    TextKey.GOAL_NEW_NOTE_LINKED to "رصيد الحساب كله هو المدّخر — اربط حسابًا مخصصًا للهدف.",
    TextKey.GOAL_NEW_NOTE_MANUAL to "تسجّل كل إيداع بنفسك.",
    TextKey.GOAL_NEW_CREATE to "أنشئ الخطة",
    TextKey.GOAL_NEW_PICK_WALLET to "اختر الحساب الذي تدّخر فيه",
    TextKey.GOAL_NEW_NO_WALLETS to "لا حسابات بعملة هذه الخطة بعد.",
    TextKey.GOAL_NEW_CREATED to "أُنشئت خطة «{0}»",
    TextKey.GOAL_EDIT_TITLE to "تعديل الخطة",
    TextKey.GOAL_EDIT_SUB_SAVED to "المدّخر حتى الآن {0}",
    TextKey.GOAL_EDIT_SUB_LINKED to "مربوطة بحساب — المدّخر رصيده كله: {0}",
    TextKey.GOAL_EDIT_SUB_NA to "المدّخر غير متاح — رصيد الحساب المربوط غير معروف.",
    TextKey.GOAL_EDIT_TARGET to "المبلغ المستهدف",
    TextKey.GOAL_EDIT_DATE_VALUE to "{0} {1}",
    TextKey.GOAL_EDIT_NEED to "تحتاج {0} شهريًا",
    TextKey.GOAL_EDIT_NEED_NOTE to "الباقي {0} حتى {1}، مقرّبًا لأعلى.",
    TextKey.GOAL_EDIT_NEED_NA to "المطلوب شهريًا: غير متاح",
    TextKey.GOAL_EDIT_NEED_NA_NOTE to "يظهر حين يُعرف رصيد الحساب — لا نكتب رقمًا من عندنا.",
    TextKey.GOAL_EDIT_NEED_AFTER_SAVE to "يُحسب المطلوب الجديد بعد الحفظ — لا نكتب رقمًا من عندنا.",
    TextKey.GOAL_EDIT_COVERED to "المدّخر يغطي الهدف — تكتمل الخطة",
    TextKey.GOAL_EDIT_ARCHIVE_NOTE to "تختفي من القائمة وتبقى في «المؤرشفة» بإيداعاتها — لا تُحذف.",
    TextKey.GOAL_EDIT_NO_CHANGE to "لم يتغيّر شيء",
    TextKey.GOAL_EDIT_NOTHING_CHANGED to "لم يتغيّر شيء.",
    TextKey.GOAL_EDIT_SAVE to "احفظ التعديل",
    TextKey.GOAL_EDIT_SAVE_ARCHIVE to "احفظ وأرشف",
    TextKey.GOAL_EDIT_SAVED to "حُفظت خطة «{0}»",
    TextKey.GOAL_EDIT_DATE_AFTER to "اختر موعدًا بعد اليوم.",
)

internal val EGYPTIAN_BUDGETS_GOALS: Map<TextKey, String> = mapOf(
    TextKey.GOALS_TITLE to "خطط الادخار",
    TextKey.GOALS_NEW to "خطة جديدة",
    TextKey.GOALS_EMPTY_TITLE to "مفيش خطط ادخار",
    TextKey.GOALS_EMPTY_BODY to "اعمل خطة بهدف وميعاد، وهنقولك المفروض تكون فين النهارده.",
    TextKey.GOALS_INTRO to "النجمة على خطة واحدة بس — عليها المساعد بيقيس عادات الصرف.",
    TextKey.GOALS_SUB_UNTIL to "لحد {0}، {1}",
    TextKey.GOALS_MANUAL to "إيداعات بإيدك",
    TextKey.GOALS_LINKED_OTHER to "حساب مربوط",
    TextKey.GOALS_WALLET_LAST4 to "{0} ⁦•••• {1}⁩",
    TextKey.GOALS_CHIP_REACHED to "كملت",
    TextKey.GOALS_CHIP_NEW to "جديدة",
    TextKey.GOALS_CHIP_AHEAD to "قدّام",
    TextKey.GOALS_CHIP_BEHIND to "ورا",
    TextKey.GOALS_CHIP_OVERDUE to "عدّى ميعادها",
    TextKey.GOALS_OF to "من {0}، {1}٪",
    TextKey.GOALS_OF_ONLY to "من {0}",
    TextKey.GOALS_STAT_EXPECTED to "المفروض النهارده",
    TextKey.GOALS_STAT_AHEAD to "قدّام بـ",
    TextKey.GOALS_STAT_BEHIND to "ورا بـ",
    TextKey.GOALS_STAT_ON_TIME to "في الميعاد",
    TextKey.GOALS_STAT_REQUIRED to "المطلوب في الشهر",
    TextKey.GOALS_STAT_REACH to "هتوصل لكام",
    TextKey.GOALS_STAT_AFTER_30 to "بعد ٣٠ يوم",
    TextKey.GOALS_STAT_LEFT to "الفاضل",
    TextKey.GOALS_OPEN_MANUAL to "التفاصيل والإيداعات",
    TextKey.GOALS_OPEN_LINKED to "التفاصيل",
    TextKey.GOALS_STAR_ADD to "حط النجمة على الخطة دي",
    TextKey.GOALS_STAR_REMOVE to "شيل النجمة",
    TextKey.GOALS_STARRED to "النجمة على «{0}» — عليها المساعد بيقيس عاداتك",
    TextKey.GOALS_UNSTARRED to "اتشالت النجمة — المساعد هيقيس على أقرب خطة شغالة",
    TextKey.GOALS_ARCHIVED to "المتأرشفة ({0})",
    TextKey.GOALS_ARCHIVED_ROW to "{0} / {1}",
    TextKey.GOALS_METHOD to "المفروض النهارده = خط مستقيم بالأيام من البداية للميعاد. «هتوصل لكام» بمعدلك من البداية، وبيظهر بعد ٣٠ يوم.",
    TextKey.GOAL_DETAIL_TITLE to "خطة «{0}»",
    TextKey.GOAL_DETAIL_TITLE_STAR to "★ خطة «{0}»",
    TextKey.GOAL_DETAIL_SUB to "الهدف {0}، {1}",
    TextKey.GOAL_DETAIL_SAVED to "المتحوّش",
    TextKey.GOAL_DETAIL_SAVED_LINKED to "المتحوّش (رصيد الحساب كله)",
    TextKey.GOAL_DETAIL_PROGRESS to "{0}٪، فاضل {1}",
    TextKey.GOAL_DETAIL_REACHED to "{0}٪، كملت!",
    TextKey.GOAL_DETAIL_UNKNOWN to "رصيد الحساب مش معروف — كله غير متاح",
    TextKey.GOAL_DETAIL_LINKED to "مربوطة بـ«{0}» — الخطة مربوطة بحساب، المتحوّش بيتحسب من رصيده كله.",
    TextKey.GOAL_DETAIL_DEP_LABEL to "مبلغ الإيداع",
    TextKey.GOAL_DETAIL_DEPOSIT to "أودِع",
    TextKey.GOAL_DETAIL_EDIT to "تعديل",
    TextKey.GOAL_DETAIL_ARCHIVE to "أرشف الخطة",
    TextKey.GOAL_DETAIL_DEPOSITED to "اتسجّل إيداع {0} في «{1}»",
    TextKey.GOAL_DETAIL_DONE to "برافو! خطة «{0}» كملت",
    TextKey.GOAL_DETAIL_ARCHIVED_TOAST to "اتأرشفت «{0}» — ما بتتمسحش، وموجودة في المتأرشفة",
    TextKey.GOAL_NEW_SUB to "الخطة بتتأرشف بس، عمرها ما بتتمسح.",
    TextKey.GOAL_NEW_NAME to "اسم الخطة",
    TextKey.GOAL_NEW_NAME_HINT to "مثلًا: عربية",
    TextKey.GOAL_NEW_TARGET to "المبلغ المطلوب ({0})",
    TextKey.GOAL_NEW_WHEN to "لحد إمتى؟",
    TextKey.GOAL_NEW_YEAR_END to "آخر السنة",
    TextKey.GOAL_NEW_ONE_YEAR to "بعد سنة",
    TextKey.GOAL_NEW_TWO_YEARS to "بعد سنتين",
    TextKey.GOAL_NEW_HOW to "بتحوّش إزاي؟",
    TextKey.GOAL_NEW_MANUAL to "إيداعات بإيدي",
    TextKey.GOAL_NEW_LINKED to "حساب مخصوص",
    TextKey.GOAL_NEW_WHICH to "أنهي حساب؟",
    TextKey.GOAL_NEW_NOTE_LINKED to "رصيد الحساب كله هو المتحوّش — اربط حساب مخصوص للهدف.",
    TextKey.GOAL_NEW_NOTE_MANUAL to "بتسجّل كل إيداع بنفسك.",
    TextKey.GOAL_NEW_CREATE to "اعمل الخطة",
    TextKey.GOAL_NEW_PICK_WALLET to "اختار الحساب اللي هتحوّش فيه",
    TextKey.GOAL_NEW_NO_WALLETS to "مفيش حسابات بعملة الخطة دي لسه.",
    TextKey.GOAL_NEW_CREATED to "اتعملت خطة «{0}»",
    TextKey.GOAL_EDIT_TITLE to "تعديل الخطة",
    TextKey.GOAL_EDIT_SUB_SAVED to "المتحوّش لحد دلوقتي {0}",
    TextKey.GOAL_EDIT_SUB_LINKED to "مربوطة بحساب — المتحوّش رصيده كله: {0}",
    TextKey.GOAL_EDIT_SUB_NA to "المتحوّش غير متاح — رصيد الحساب المربوط مش معروف.",
    TextKey.GOAL_EDIT_TARGET to "المبلغ المطلوب",
    TextKey.GOAL_EDIT_DATE_VALUE to "{0} {1}",
    TextKey.GOAL_EDIT_NEED to "محتاج {0} في الشهر",
    TextKey.GOAL_EDIT_NEED_NOTE to "الفاضل {0} لحد {1}، متقرّب لفوق.",
    TextKey.GOAL_EDIT_NEED_NA to "المطلوب في الشهر: غير متاح",
    TextKey.GOAL_EDIT_NEED_NA_NOTE to "بيظهر لما رصيد الحساب يتعرف — مش هنكتب رقم من عندنا.",
    TextKey.GOAL_EDIT_NEED_AFTER_SAVE to "المطلوب الجديد بيتحسب بعد الحفظ — مش هنكتب رقم من عندنا.",
    TextKey.GOAL_EDIT_COVERED to "المتحوّش بيغطي الهدف — الخطة هتكمل",
    TextKey.GOAL_EDIT_ARCHIVE_NOTE to "بتختفي من القايمة وتفضل في «المتأرشفة» بإيداعاتها — ما بتتمسحش.",
    TextKey.GOAL_EDIT_NO_CHANGE to "مفيش تغيير",
    TextKey.GOAL_EDIT_NOTHING_CHANGED to "مفيش حاجة اتغيرت.",
    TextKey.GOAL_EDIT_SAVE to "احفظ التعديل",
    TextKey.GOAL_EDIT_SAVE_ARCHIVE to "احفظ وأرشفها",
    TextKey.GOAL_EDIT_SAVED to "اتحفظت خطة «{0}»",
    TextKey.GOAL_EDIT_DATE_AFTER to "اختار ميعاد بعد النهارده.",
)

internal val ENGLISH_BUDGETS_GOALS: Map<TextKey, String> = mapOf(
    TextKey.GOALS_TITLE to "Savings plans",
    TextKey.GOALS_NEW to "New plan",
    TextKey.GOALS_EMPTY_TITLE to "No savings plans",
    TextKey.GOALS_EMPTY_BODY to "Make a plan with a target and a date, and we'll show where you should be today.",
    TextKey.GOALS_INTRO to "Only one plan gets the star — the assistant measures spending habits against it.",
    TextKey.GOALS_SUB_UNTIL to "Until {0}, {1}",
    TextKey.GOALS_MANUAL to "Manual deposits",
    TextKey.GOALS_LINKED_OTHER to "Linked account",
    TextKey.GOALS_WALLET_LAST4 to "{0} ⁦•••• {1}⁩",
    TextKey.GOALS_CHIP_REACHED to "Done",
    TextKey.GOALS_CHIP_NEW to "New",
    TextKey.GOALS_CHIP_AHEAD to "Ahead",
    TextKey.GOALS_CHIP_BEHIND to "Behind",
    TextKey.GOALS_CHIP_OVERDUE to "Past its date",
    TextKey.GOALS_OF to "of {0}, {1}%",
    TextKey.GOALS_OF_ONLY to "of {0}",
    TextKey.GOALS_STAT_EXPECTED to "Expected today",
    TextKey.GOALS_STAT_AHEAD to "Ahead by",
    TextKey.GOALS_STAT_BEHIND to "Behind by",
    TextKey.GOALS_STAT_ON_TIME to "On time",
    TextKey.GOALS_STAT_REQUIRED to "Needed per month",
    TextKey.GOALS_STAT_REACH to "You'll reach",
    TextKey.GOALS_STAT_AFTER_30 to "After 30 days",
    TextKey.GOALS_STAT_LEFT to "Left",
    TextKey.GOALS_OPEN_MANUAL to "Details and deposits",
    TextKey.GOALS_OPEN_LINKED to "Details",
    TextKey.GOALS_STAR_ADD to "Star this plan",
    TextKey.GOALS_STAR_REMOVE to "Remove the star",
    TextKey.GOALS_STARRED to "The star is on “{0}” — the assistant measures your habits against it",
    TextKey.GOALS_UNSTARRED to "Star removed — the assistant uses the nearest active plan",
    TextKey.GOALS_ARCHIVED to "Archived ({0})",
    TextKey.GOALS_ARCHIVED_ROW to "{0} / {1}",
    TextKey.GOALS_METHOD to "Expected today = a straight line in days from the start to the date. “You'll reach” uses your pace since the start and shows after 30 days.",
    TextKey.GOAL_DETAIL_TITLE to "“{0}” plan",
    TextKey.GOAL_DETAIL_TITLE_STAR to "★ “{0}” plan",
    TextKey.GOAL_DETAIL_SUB to "Target {0}, {1}",
    TextKey.GOAL_DETAIL_SAVED to "Saved",
    TextKey.GOAL_DETAIL_SAVED_LINKED to "Saved (the whole account balance)",
    TextKey.GOAL_DETAIL_PROGRESS to "{0}%, {1} left",
    TextKey.GOAL_DETAIL_REACHED to "{0}%, done!",
    TextKey.GOAL_DETAIL_UNKNOWN to "The account balance isn't known — all numbers are unavailable",
    TextKey.GOAL_DETAIL_LINKED to "Linked to “{0}” — the plan is linked to an account, and the saved amount is its whole balance.",
    TextKey.GOAL_DETAIL_DEP_LABEL to "Deposit amount",
    TextKey.GOAL_DETAIL_DEPOSIT to "Deposit",
    TextKey.GOAL_DETAIL_EDIT to "Edit",
    TextKey.GOAL_DETAIL_ARCHIVE to "Archive the plan",
    TextKey.GOAL_DETAIL_DEPOSITED to "Deposited {0} in “{1}”",
    TextKey.GOAL_DETAIL_DONE to "Well done! The “{0}” plan is complete",
    TextKey.GOAL_DETAIL_ARCHIVED_TOAST to "“{0}” archived — it isn't deleted and stays under Archived",
    TextKey.GOAL_NEW_SUB to "Plans are only archived, never deleted.",
    TextKey.GOAL_NEW_NAME to "Plan name",
    TextKey.GOAL_NEW_NAME_HINT to "For example: a car",
    TextKey.GOAL_NEW_TARGET to "Target amount ({0})",
    TextKey.GOAL_NEW_WHEN to "Until when?",
    TextKey.GOAL_NEW_YEAR_END to "End of the year",
    TextKey.GOAL_NEW_ONE_YEAR to "In a year",
    TextKey.GOAL_NEW_TWO_YEARS to "In two years",
    TextKey.GOAL_NEW_HOW to "How do you save?",
    TextKey.GOAL_NEW_MANUAL to "Manual deposits",
    TextKey.GOAL_NEW_LINKED to "A dedicated account",
    TextKey.GOAL_NEW_WHICH to "Which account?",
    TextKey.GOAL_NEW_NOTE_LINKED to "The whole account balance counts as saved — link an account kept for this target.",
    TextKey.GOAL_NEW_NOTE_MANUAL to "You record each deposit yourself.",
    TextKey.GOAL_NEW_CREATE to "Create the plan",
    TextKey.GOAL_NEW_PICK_WALLET to "Pick the account you save in",
    TextKey.GOAL_NEW_NO_WALLETS to "No accounts in this plan's currency yet.",
    TextKey.GOAL_NEW_CREATED to "Created the “{0}” plan",
    TextKey.GOAL_EDIT_TITLE to "Edit the plan",
    TextKey.GOAL_EDIT_SUB_SAVED to "Saved so far {0}",
    TextKey.GOAL_EDIT_SUB_LINKED to "Linked to an account — saved is its whole balance: {0}",
    TextKey.GOAL_EDIT_SUB_NA to "Saved isn't available — the linked account's balance isn't known.",
    TextKey.GOAL_EDIT_TARGET to "Target amount",
    TextKey.GOAL_EDIT_DATE_VALUE to "{0} {1}",
    TextKey.GOAL_EDIT_NEED to "You need {0} a month",
    TextKey.GOAL_EDIT_NEED_NOTE to "{0} left until {1}, rounded up.",
    TextKey.GOAL_EDIT_NEED_NA to "Needed per month: not available",
    TextKey.GOAL_EDIT_NEED_NA_NOTE to "It shows once the account balance is known — we don't make up a number.",
    TextKey.GOAL_EDIT_NEED_AFTER_SAVE to "The new monthly amount is worked out after saving — we don't make up a number.",
    TextKey.GOAL_EDIT_COVERED to "What's saved covers the target — the plan is complete",
    TextKey.GOAL_EDIT_ARCHIVE_NOTE to "It leaves the list and stays under “Archived” with its deposits — it isn't deleted.",
    TextKey.GOAL_EDIT_NO_CHANGE to "Nothing changed",
    TextKey.GOAL_EDIT_NOTHING_CHANGED to "Nothing has changed.",
    TextKey.GOAL_EDIT_SAVE to "Save the changes",
    TextKey.GOAL_EDIT_SAVE_ARCHIVE to "Save and archive",
    TextKey.GOAL_EDIT_SAVED to "Saved the “{0}” plan",
    TextKey.GOAL_EDIT_DATE_AFTER to "Pick a date after today.",
)
