package app.masroufy.core

/**
 * نصوص «المساعد المالي» (خطة الادخار + habitVsGoal · overcommitted · capPace — OVERRIDES §68): فصحى (§66) · مصري · إنجليزي.
 * - `ALERT_LOCK_*` نص شاشة القفل: من غير أي رقم ولا مبلغ ولا اسم بند (§61) — `systemNoticeFor` بيتأكد، والاختبار بيمر على كل الأنواع.
 * - **قرار المالك (§68): البند مكان أو عادة مش صنف** — ممنوع «أكواب» و«وجبات» وأي وحدة؛ الاقتراح بـ«مرات» («قلّل 4 مرات في الأسبوع»).
 *   اختبار بيفحص الجداول التلاتة.
 * الإنجليزي كتابة Claude ومستني مراجعة المالك (§40).
 */
internal val MSA_ADVISOR_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ALERT_GROUP_ADVISOR to "المساعد المالي",
    TextKey.ALERT_LOCK_HABIT to "صرفك على أحد البنود أعلى من المعتاد — التفاصيل داخل التطبيق",
    TextKey.ALERT_LOCK_OVERCOMMITTED to "حجوزاتك أكثر مما معك — راجعها داخل التطبيق",
    TextKey.ALERT_LOCK_CAP_PACE to "بمعدل صرفك الحالي قد تتجاوز إحدى ميزانياتك",
    TextKey.ALERT_WHY_HABIT to "صرفك على هذا البند أعلى من معدله المعتاد، وقد يؤخر خطة الادخار",
    TextKey.ALERT_WHY_OVERCOMMITTED to "ما حجزته أكثر من المال الذي معك",
    TextKey.ALERT_WHY_CAP_PACE to "بمعدل صرفك الحالي يُتوقع تجاوز السقف قبل نهاية الشهر",
    TextKey.ADVISOR_HABIT_TITLE to "«{0}» أعلى من معدله المعتاد",
    TextKey.ADVISOR_HABIT_BODY_YEAR_END to "{0} هذا الشهر {1} — بهذا المعدل ستحوش {2} بدل {3} آخر السنة",
    TextKey.ADVISOR_HABIT_BODY_BY_DATE to "{0} هذا الشهر {1} — بهذا المعدل ستحوش {2} بدل {3} بحلول {4}",
    TextKey.ADVISOR_HABIT_SUGGEST to "قلّل {0} مرات في الأسبوع ليعود إلى معدله المعتاد",
    TextKey.ADVISOR_OVERCOMMIT_TITLE to "حجوزاتك أكثر مما معك",
    TextKey.ADVISOR_OVERCOMMIT_BODY_MONTH to "حجزت {0} لهذا الشهر ومعك {1}. ينقصك {2}",
    TextKey.ADVISOR_OVERCOMMIT_BODY_NEXT_PAY to "حجزت {0} حتى القبض القادم ومعك {1}. ينقصك {2}",
    TextKey.ADVISOR_OVERCOMMIT_BODY_ANY to "حجزت {0} ومعك {1}. ينقصك {2}",
    TextKey.ADVISOR_APPROXIMATE to "(تقريبي: أحد الأرصدة غير مطابق للكشف)",
    TextKey.ADVISOR_CAP_PACE_TITLE to "«{0}»: بهذا المعدل ستتجاوز السقف",
    TextKey.ADVISOR_CAP_PACE_BODY to "صرفت {0} من {1} — المتوقع {2} آخر الشهر، ويُتجاوز السقف نحو {3}",
    TextKey.ADVISOR_TOTAL_BUDGET to "ميزانية الشهر",
    TextKey.GOAL_NAME_REQUIRED to "اكتب اسم الخطة",
    TextKey.GOAL_NAME_LENGTH to "اسم الخطة {0} حرفًا على الأكثر",
    TextKey.GOAL_TARGET_POSITIVE to "مبلغ الخطة يجب أن يكون أكبر من صفر",
    TextKey.GOAL_DATES_ORDER to "تاريخ الهدف يجب أن يكون بعد تاريخ البداية",
    TextKey.GOAL_NOT_FOUND to "الخطة غير موجودة",
    TextKey.GOAL_ARCHIVED to "الخطة مؤرشفة",
    TextKey.GOAL_WALLET_NOT_FOUND to "الحساب المربوط غير موجود",
    TextKey.GOAL_WALLET_CURRENCY to "عملة الحساب المربوط تختلف عن عملة الخطة",
    TextKey.GOAL_CONTRIBUTION_POSITIVE to "مبلغ الإيداع يجب أن يكون أكبر من صفر",
    TextKey.GOAL_CONTRIBUTION_LINKED to "الخطة مربوطة بحساب — المدّخر يُحسب من رصيده",
    TextKey.GOAL_CONTRIBUTION_NOT_FOUND to "الإيداع غير موجود",
    TextKey.GOAL_CONTRIBUTION_DATE to "تاريخ الإيداع غير صحيح",
    TextKey.BACKUP_GROUP_SAVINGS_GOALS to "خطط الادخار",
    TextKey.BACKUP_GROUP_GOAL_CONTRIBUTIONS to "إيداعات خطط الادخار",
)

/** نفس المفاتيح بالمصري — لما البلد الشغالة مصر (§66). مفاتيح جديدة بس (المصري القديم ما اتلمسش). */
internal val EGYPTIAN_ADVISOR_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ALERT_GROUP_ADVISOR to "المساعد المالي",
    TextKey.ALERT_LOCK_HABIT to "صرفك على بند أعلى من العادي — التفاصيل جوه التطبيق",
    TextKey.ALERT_LOCK_OVERCOMMITTED to "حجوزاتك أكتر من اللي معاك — بص عليها لما تفتح",
    TextKey.ALERT_LOCK_CAP_PACE to "بالمعدل ده ممكن تعدّي ميزانية من ميزانياتك",
    TextKey.ALERT_WHY_HABIT to "صرفك على البند ده أعلى من العادي، وده ممكن يأخّر خطة الادخار",
    TextKey.ALERT_WHY_OVERCOMMITTED to "اللي حجزته أكتر من الفلوس اللي معاك",
    TextKey.ALERT_WHY_CAP_PACE to "بمعدل صرفك دلوقتي السقف هيتعدّى قبل آخر الشهر",
    TextKey.ADVISOR_HABIT_TITLE to "«{0}» أعلى من العادي",
    TextKey.ADVISOR_HABIT_BODY_YEAR_END to "{0} الشهر ده {1} — بالمعدل ده هتحوّش {2} بدل {3} آخر السنة",
    TextKey.ADVISOR_HABIT_BODY_BY_DATE to "{0} الشهر ده {1} — بالمعدل ده هتحوّش {2} بدل {3} يوم {4}",
    TextKey.ADVISOR_HABIT_SUGGEST to "قلّل {0} مرات في الأسبوع عشان يرجع لمعدله العادي",
    TextKey.ADVISOR_OVERCOMMIT_TITLE to "حجوزاتك أكتر من اللي معاك",
    TextKey.ADVISOR_OVERCOMMIT_BODY_MONTH to "حجزت {0} للشهر ده ومعاك {1}. ناقصك {2}",
    TextKey.ADVISOR_OVERCOMMIT_BODY_NEXT_PAY to "حجزت {0} لحد القبض الجاي ومعاك {1}. ناقصك {2}",
    TextKey.ADVISOR_OVERCOMMIT_BODY_ANY to "حجزت {0} ومعاك {1}. ناقصك {2}",
    TextKey.ADVISOR_APPROXIMATE to "(تقريبي: فيه رصيد مش مطابق للكشف)",
    TextKey.ADVISOR_CAP_PACE_TITLE to "«{0}»: بالمعدل ده هتعدّي السقف",
    TextKey.ADVISOR_CAP_PACE_BODY to "صرفت {0} من {1} — المتوقع {2} آخر الشهر، والسقف هيتعدّى حوالي {3}",
    TextKey.ADVISOR_TOTAL_BUDGET to "ميزانية الشهر",
    TextKey.GOAL_NAME_REQUIRED to "اكتب اسم الخطة",
    TextKey.GOAL_NAME_LENGTH to "اسم الخطة {0} حرف بالكتير",
    TextKey.GOAL_TARGET_POSITIVE to "مبلغ الخطة لازم يبقى أكبر من صفر",
    TextKey.GOAL_DATES_ORDER to "تاريخ الهدف لازم يبقى بعد تاريخ البداية",
    TextKey.GOAL_NOT_FOUND to "الخطة مش موجودة",
    TextKey.GOAL_ARCHIVED to "الخطة متأرشفة",
    TextKey.GOAL_WALLET_NOT_FOUND to "الحساب المربوط مش موجود",
    TextKey.GOAL_WALLET_CURRENCY to "عملة الحساب المربوط غير عملة الخطة",
    TextKey.GOAL_CONTRIBUTION_POSITIVE to "مبلغ الإيداع لازم يبقى أكبر من صفر",
    TextKey.GOAL_CONTRIBUTION_LINKED to "الخطة مربوطة بحساب — المتحوّش بيتحسب من رصيده",
    TextKey.GOAL_CONTRIBUTION_NOT_FOUND to "الإيداع مش موجود",
    TextKey.GOAL_CONTRIBUTION_DATE to "تاريخ الإيداع مش مظبوط",
    TextKey.BACKUP_GROUP_SAVINGS_GOALS to "خطط الادخار",
    TextKey.BACKUP_GROUP_GOAL_CONTRIBUTIONS to "إيداعات خطط الادخار",
)

internal val ENGLISH_ADVISOR_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ALERT_GROUP_ADVISOR to "Financial advisor",
    TextKey.ALERT_LOCK_HABIT to "Spending in one category is above usual — details inside the app",
    TextKey.ALERT_LOCK_OVERCOMMITTED to "Your reservations are more than you have — take a look inside the app",
    TextKey.ALERT_LOCK_CAP_PACE to "At your current pace you may go over one of your budgets",
    TextKey.ALERT_WHY_HABIT to "Spending in this category is above its usual level and may delay your savings plan",
    TextKey.ALERT_WHY_OVERCOMMITTED to "What you reserved is more than the money you have",
    TextKey.ALERT_WHY_CAP_PACE to "At your current pace the limit is expected to be passed before the month ends",
    TextKey.ADVISOR_HABIT_TITLE to "“{0}” is above its usual level",
    TextKey.ADVISOR_HABIT_BODY_YEAR_END to "{0} this month: {1} — at this rate you will save {2} instead of {3} by the end of the year",
    TextKey.ADVISOR_HABIT_BODY_BY_DATE to "{0} this month: {1} — at this rate you will save {2} instead of {3} by {4}",
    TextKey.ADVISOR_HABIT_SUGGEST to "Go {0} fewer times a week to bring it back to its usual level",
    TextKey.ADVISOR_OVERCOMMIT_TITLE to "Your reservations are more than you have",
    TextKey.ADVISOR_OVERCOMMIT_BODY_MONTH to "You reserved {0} for this month and you have {1}. You are short {2}",
    TextKey.ADVISOR_OVERCOMMIT_BODY_NEXT_PAY to "You reserved {0} until your next pay and you have {1}. You are short {2}",
    TextKey.ADVISOR_OVERCOMMIT_BODY_ANY to "You reserved {0} and you have {1}. You are short {2}",
    TextKey.ADVISOR_APPROXIMATE to "(approximate: one balance does not match its statement)",
    TextKey.ADVISOR_CAP_PACE_TITLE to "“{0}”: at this pace you will pass the limit",
    TextKey.ADVISOR_CAP_PACE_BODY to "Spent {0} of {1} — expected {2} by month end, passing the limit around {3}",
    TextKey.ADVISOR_TOTAL_BUDGET to "This month's budget",
    TextKey.GOAL_NAME_REQUIRED to "Enter a name for the plan",
    TextKey.GOAL_NAME_LENGTH to "The plan name is {0} characters at most",
    TextKey.GOAL_TARGET_POSITIVE to "The plan amount must be more than zero",
    TextKey.GOAL_DATES_ORDER to "The target date must be after the start date",
    TextKey.GOAL_NOT_FOUND to "The plan was not found",
    TextKey.GOAL_ARCHIVED to "The plan is archived",
    TextKey.GOAL_WALLET_NOT_FOUND to "The linked account was not found",
    TextKey.GOAL_WALLET_CURRENCY to "The linked account's currency differs from the plan's currency",
    TextKey.GOAL_CONTRIBUTION_POSITIVE to "The deposit amount must be more than zero",
    TextKey.GOAL_CONTRIBUTION_LINKED to "The plan is linked to an account — the saved amount comes from its balance",
    TextKey.GOAL_CONTRIBUTION_NOT_FOUND to "The deposit was not found",
    TextKey.GOAL_CONTRIBUTION_DATE to "The deposit date is not valid",
    TextKey.BACKUP_GROUP_SAVINGS_GOALS to "Savings plans",
    TextKey.BACKUP_GROUP_GOAL_CONTRIBUTIONS to "Savings plan deposits",
)
