package app.masroufy.core

/**
 * نصوص المساعد «مصروفي» العامة (§78 + `replyVariation` في التصميم): الاسم · بداية المحادثة · الردود المتنوعة · الكلام العادي · الفترات.
 * فصحى للسعودية · مصري لمصر (نفس نصوص النموذج التفاعلي) · إنجليزي. اللهجة اللي المستخدم كتب بيها ما بتغيّرش الرد (§66).
 */
internal val MSA_ASSIST_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_BRAND to "مصروفي",
    TextKey.ASSIST_BRAND_TITLE to "مساعدك المالي الذكي",
    TextKey.ASSIST_GREETING_MORNING to "صباح الخير",
    TextKey.ASSIST_GREETING_EVENING to "مساء الخير",
    TextKey.ASSIST_GREETING_MORNING_NAMED to "صباح الخير، {0}",
    TextKey.ASSIST_GREETING_EVENING_NAMED to "مساء الخير، {0}",
    TextKey.ASSIST_INTRO_1 to "أنا مصروفي، مساعدك المالي الذكي. اسألني عن مالك، أو اطلب مني تسجيل مصروف أو تقسيم فاتورة.",
    TextKey.ASSIST_INTRO_2 to "اكتب سؤالك عن صرفك أو مواعيدك، أو مصروفًا مثل «قهوة 15».",
    TextKey.ASSIST_INTRO_3 to "جاهز. ماذا تريد أن تعرف عن مالك اليوم؟",
    TextKey.ASSIST_INTRO_BEFORE_PAYDAY to "الراتب بعد {0} — اسألني كم بقي معك حتى ذلك اليوم.",
    TextKey.ASSIST_INTRO_MONTH_START to "بدأ شهرك الجديد — اسألني كيف كان الشهر الماضي.",
    TextKey.ASSIST_TODO_TITLE to "أمور لم تُنجزها بعد",
    TextKey.ASSIST_ALL_DONE to "أنجزت كل شيء — لا شيء ينتظرك الآن.",
    TextKey.ASSIST_NOTHING_WAITING to "لا شيء ينتظرك الآن.",
    TextKey.ASSIST_START_BASIS to "من رسائل البنك والفواتير الدورية والميزانيات والديون.",
    TextKey.ASSIST_RECORDED_1 to "سُجّلت في عمليات {0}.",
    TextKey.ASSIST_RECORDED_2 to "تم، أضفتها إلى عمليات {0}.",
    TextKey.ASSIST_RECORDED_3 to "حُفظت في عمليات {0}.",
    TextKey.ASSIST_THANKS_1 to "العفو.",
    TextKey.ASSIST_THANKS_2 to "في خدمتك.",
    TextKey.ASSIST_THANKS_3 to "على الرحب والسعة.",
    TextKey.ASSIST_OFFER_1 to "هل تريد أن تعرف صرفك اليوم؟",
    TextKey.ASSIST_OFFER_2 to "اسألني عن أي مبلغ أو موعد.",
    TextKey.ASSIST_HOW_ARE_YOU_1 to "بخير، شكرًا لسؤالك.",
    TextKey.ASSIST_HOW_ARE_YOU_2 to "بأفضل حال.",
    TextKey.ASSIST_BYE_1 to "في أمان الله.",
    TextKey.ASSIST_BYE_2 to "إلى اللقاء.",
    TextKey.ASSIST_BYE_NIGHT to "تصبح على خير.",
    TextKey.ASSIST_PRAISE_1 to "شكرًا لك!",
    TextKey.ASSIST_PRAISE_2 to "يسعدني ذلك.",
    TextKey.ASSIST_UNKNOWN_1 to "لم أفهم «{0}» بعد، وحفظت سؤالك لأتعلّمه. قد تجد ما تريده هنا:",
    TextKey.ASSIST_UNKNOWN_2 to "لا أعرف إجابة «{0}» حتى الآن، وسجّلته لأتعلّمه. ربما تجده هنا:",
    TextKey.ASSIST_UNKNOWN_SHORTER to "جرّب سؤالًا أقصر، مثل: «{0}»",
    TextKey.ASSIST_SALAM_REPLY to "وعليكم السلام ورحمة الله.",
    TextKey.ASSIST_MORNING_REPLY to "صباح النور.",
    TextKey.ASSIST_EVENING_REPLY to "مساء النور.",
    TextKey.ASSIST_OPENER_SALAM to "وعليكم السلام،",
    TextKey.ASSIST_OPENER_HELLO to "أهلًا،",
    TextKey.ASSIST_OPENER_UNDERSTOOD to "فهمتك الآن.",
    TextKey.ASSIST_OPENER_AGAIN to "الرقم الآن:",
    TextKey.ASSIST_WHO_ARE_YOU to "أنا مصروفي، مساعدك المالي. لست ذكاءً اصطناعيًا بعد: أعمل بقواعد على جوالك، وأجيب من أرقامك أنت فقط، ولا يخرج شيء من حسابك.",
    TextKey.ASSIST_HELP to "أستطيع أن أجيبك عن صرفك ومواعيدك والأشخاص، وأسجّل مصروفًا تكتبه مثل «قهوة 15»، وأقسّم فاتورة، وأدلّك على أي شاشة.",
    TextKey.ASSIST_FRUSTRATION to "آسف إن لم أفهمك. جرّب مثلًا: «{0}»",
    TextKey.ASSIST_ADVICE_BOUNDARY to "لا أنصح بشراء استثمار معيّن أو بيعه. أستطيع أن أريك أصولك وقيمتها، وحاسبات الادخار والتحليلات تساعدك في القرار.",
    TextKey.ASSIST_PERIOD_THIS_MONTH to "هذا الشهر",
    TextKey.ASSIST_PERIOD_LAST_MONTH to "الشهر الماضي",
    TextKey.ASSIST_PERIOD_IN to "في {0}",
    TextKey.ASSIST_PERIOD_THIS_WEEK to "هذا الأسبوع (من السبت)",
    TextKey.ASSIST_PERIOD_LAST_WEEK to "الأسبوع الماضي",
    TextKey.ASSIST_PERIOD_TODAY to "اليوم",
    TextKey.ASSIST_PERIOD_YESTERDAY to "أمس",
    TextKey.ASSIST_PERIOD_DAY_BEFORE to "أول أمس",
    TextKey.ASSIST_PERIOD_THIS_YEAR to "منذ بداية السنة",
    TextKey.ASSIST_PERIOD_LAST_YEAR to "السنة الماضية",
    TextKey.ASSIST_PERIOD_LAST_DAYS to "في آخر {0} يومًا",
    TextKey.ASSIST_PERIOD_LAST_MONTHS to "في آخر {0} أشهر",
    TextKey.ASSIST_PERIOD_DAYS_AGO to "قبل {0} أيام",
    TextKey.ASSIST_PERIOD_ON_DATE to "يوم {0}",
    TextKey.ASSIST_PERIOD_SINCE to "منذ {0}",
    TextKey.ASSIST_MONTHS to "يناير|فبراير|مارس|أبريل|مايو|يونيو|يوليو|أغسطس|سبتمبر|أكتوبر|نوفمبر|ديسمبر",
    TextKey.ASSIST_DATE to "{0} {1}",
    TextKey.ASSIST_DATE_YEAR to "{0} {1} {2}",
    TextKey.ASSIST_DAYS_ONE to "يوم واحد",
    TextKey.ASSIST_DAYS_TWO to "يومين",
    TextKey.ASSIST_DAYS_FEW to "{0} أيام",
    TextKey.ASSIST_DAYS_MANY to "{0} يومًا",
    TextKey.ASSIST_TIMES_ONE to "مرة واحدة",
    TextKey.ASSIST_TIMES_TWO to "مرتين",
    TextKey.ASSIST_TIMES_FEW to "{0} مرات",
    TextKey.ASSIST_TIMES_MANY to "{0} مرة",
    TextKey.ASSIST_LIST_COMMA to "، ",
    TextKey.ASSIST_LIST_AND to " و",
    TextKey.ASSIST_QUOTE to "«{0}»",
    TextKey.ASSIST_OPEN_SCREEN to "افتح {0}",
    TextKey.ASSIST_APPROXIMATE to "(تقريبي)",
)

internal val EGYPTIAN_ASSIST_TEXTS: Map<TextKey, String> = MSA_ASSIST_TEXTS + mapOf(
    TextKey.ASSIST_GREETING_MORNING_NAMED to "صباح الخير يا {0}",
    TextKey.ASSIST_GREETING_EVENING_NAMED to "مساء الخير يا {0}",
    TextKey.ASSIST_INTRO_1 to "أنا مصروفي، مساعدك المالي الذكي. اسألني عن فلوسك، أو قولّي أسجّل مصروف أو أقسّم فاتورة.",
    TextKey.ASSIST_INTRO_2 to "اكتب سؤالك عن صرفك أو مواعيدك، أو مصروف زي «قهوة 15».",
    TextKey.ASSIST_INTRO_3 to "جاهز. عايز تعرف إيه عن فلوسك النهارده؟",
    TextKey.ASSIST_INTRO_BEFORE_PAYDAY to "المرتب بعد {0} — اسألني فاضلك كام لحد ساعتها.",
    TextKey.ASSIST_INTRO_MONTH_START to "شهرك الجديد بدأ — اسألني الشهر اللي فات كان عامل إزاي.",
    TextKey.ASSIST_TODO_TITLE to "حاجات لسه ما عملتهاش",
    TextKey.ASSIST_ALL_DONE to "خلّصت كل حاجة — مفيش حاجة مستنياك دلوقتي.",
    TextKey.ASSIST_NOTHING_WAITING to "مفيش حاجة مستنياك دلوقتي.",
    TextKey.ASSIST_START_BASIS to "من رسايل البنك والفواتير اللي بتتكرر والميزانيات والديون.",
    TextKey.ASSIST_RECORDED_1 to "اتسجّلت في عمليات {0}.",
    TextKey.ASSIST_RECORDED_2 to "تمام، ضفتها لعمليات {0}.",
    TextKey.ASSIST_RECORDED_3 to "اتحفظت في عمليات {0}.",
    TextKey.ASSIST_THANKS_2 to "تحت أمرك.",
    TextKey.ASSIST_THANKS_3 to "ولا يهمك.",
    TextKey.ASSIST_OFFER_1 to "تحب تعرف صرفك النهارده؟",
    TextKey.ASSIST_OFFER_2 to "اسألني عن أي مبلغ أو ميعاد.",
    TextKey.ASSIST_HOW_ARE_YOU_1 to "تمام الحمد لله.",
    TextKey.ASSIST_HOW_ARE_YOU_2 to "كويس، شكرًا إنك سألت.",
    TextKey.ASSIST_BYE_1 to "مع السلامة.",
    TextKey.ASSIST_BYE_2 to "في رعاية الله.",
    TextKey.ASSIST_PRAISE_1 to "تسلم!",
    TextKey.ASSIST_PRAISE_2 to "ده من ذوقك.",
    TextKey.ASSIST_UNKNOWN_1 to "لسه مش فاهم «{0}»، وحفظت سؤالك عشان أتعلمه. ممكن تلاقي اللي عايزه هنا:",
    TextKey.ASSIST_UNKNOWN_2 to "لسه ما بعرفش أرد على «{0}»، وسجّلته عشان أتعلمه. يمكن تلاقيه هنا:",
    TextKey.ASSIST_UNKNOWN_SHORTER to "جرّب سؤال أقصر، زي: «{0}»",
    TextKey.ASSIST_OPENER_HELLO to "أهلًا بيك،",
    TextKey.ASSIST_OPENER_UNDERSTOOD to "كده فهمتك.",
    TextKey.ASSIST_OPENER_AGAIN to "الرقم دلوقتي:",
    TextKey.ASSIST_WHO_ARE_YOU to "أنا مصروفي، مساعدك المالي. لسه مش ذكاء اصطناعي: بشتغل بقواعد على جوالك، وبرد من أرقامك إنت بس، ومفيش حاجة بتطلع برّه حسابك.",
    TextKey.ASSIST_HELP to "أقدر أرد عليك في صرفك ومواعيدك والناس، وأسجّل مصروف تكتبه زي «قهوة 15»، وأقسّم فاتورة، وأوديك لأي شاشة.",
    TextKey.ASSIST_FRUSTRATION to "معلش لو ما فهمتكش. جرّب مثلًا: «{0}»",
    TextKey.ASSIST_ADVICE_BOUNDARY to "مش بنصح بشراء أو بيع استثمار معيّن. أقدر أوريك أصولك وقيمتها، وحاسبات الادخار والتحليلات تساعدك تقرر.",
    TextKey.ASSIST_PERIOD_THIS_MONTH to "الشهر ده",
    TextKey.ASSIST_PERIOD_LAST_MONTH to "الشهر اللي فات",
    TextKey.ASSIST_PERIOD_THIS_WEEK to "الأسبوع ده (من السبت)",
    TextKey.ASSIST_PERIOD_LAST_WEEK to "الأسبوع اللي فات",
    TextKey.ASSIST_PERIOD_TODAY to "النهارده",
    TextKey.ASSIST_PERIOD_YESTERDAY to "امبارح",
    TextKey.ASSIST_PERIOD_DAY_BEFORE to "أول امبارح",
    TextKey.ASSIST_PERIOD_THIS_YEAR to "من أول السنة",
    TextKey.ASSIST_PERIOD_LAST_YEAR to "السنة اللي فاتت",
    TextKey.ASSIST_PERIOD_LAST_DAYS to "في آخر {0} يوم",
    TextKey.ASSIST_PERIOD_LAST_MONTHS to "في آخر {0} شهور",
    TextKey.ASSIST_PERIOD_DAYS_AGO to "من {0} أيام",
    TextKey.ASSIST_PERIOD_ON_DATE to "يوم {0}",
    TextKey.ASSIST_PERIOD_SINCE to "من {0}",
    TextKey.ASSIST_DAYS_MANY to "{0} يوم",
)

internal val ENGLISH_ASSIST_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_BRAND to "Masroufy",
    TextKey.ASSIST_BRAND_TITLE to "Your smart money assistant",
    TextKey.ASSIST_GREETING_MORNING to "Good morning",
    TextKey.ASSIST_GREETING_EVENING to "Good evening",
    TextKey.ASSIST_GREETING_MORNING_NAMED to "Good morning, {0}",
    TextKey.ASSIST_GREETING_EVENING_NAMED to "Good evening, {0}",
    TextKey.ASSIST_INTRO_1 to "I'm Masroufy, your smart money assistant. Ask me about your money, or ask me to record an expense or split a bill.",
    TextKey.ASSIST_INTRO_2 to "Type a question about your spending or due dates, or an expense like “coffee 15”.",
    TextKey.ASSIST_INTRO_3 to "Ready. What would you like to know about your money today?",
    TextKey.ASSIST_INTRO_BEFORE_PAYDAY to "Payday is in {0} — ask me how much you have left until then.",
    TextKey.ASSIST_INTRO_MONTH_START to "Your new month has started — ask me how last month went.",
    TextKey.ASSIST_TODO_TITLE to "Things you haven't done yet",
    TextKey.ASSIST_ALL_DONE to "All done — nothing is waiting for you now.",
    TextKey.ASSIST_NOTHING_WAITING to "Nothing is waiting for you now.",
    TextKey.ASSIST_START_BASIS to "From bank messages, recurring bills, budgets and debts.",
    TextKey.ASSIST_RECORDED_1 to "Recorded in {0}'s transactions.",
    TextKey.ASSIST_RECORDED_2 to "Done, added to {0}'s transactions.",
    TextKey.ASSIST_RECORDED_3 to "Saved in {0}'s transactions.",
    TextKey.ASSIST_THANKS_1 to "You're welcome.",
    TextKey.ASSIST_THANKS_2 to "Happy to help.",
    TextKey.ASSIST_THANKS_3 to "Anytime.",
    TextKey.ASSIST_OFFER_1 to "Would you like to know today's spending?",
    TextKey.ASSIST_OFFER_2 to "Ask me about any amount or due date.",
    TextKey.ASSIST_HOW_ARE_YOU_1 to "I'm well, thanks for asking.",
    TextKey.ASSIST_HOW_ARE_YOU_2 to "Doing great.",
    TextKey.ASSIST_BYE_1 to "Take care.",
    TextKey.ASSIST_BYE_2 to "See you.",
    TextKey.ASSIST_BYE_NIGHT to "Good night.",
    TextKey.ASSIST_PRAISE_1 to "Thank you!",
    TextKey.ASSIST_PRAISE_2 to "Glad to hear it.",
    TextKey.ASSIST_UNKNOWN_1 to "I don't understand “{0}” yet — I saved it so I can learn it. You might find it here:",
    TextKey.ASSIST_UNKNOWN_2 to "I can't answer “{0}” yet — I noted it so I can learn it. Maybe it's here:",
    TextKey.ASSIST_UNKNOWN_SHORTER to "Try a shorter question, like: “{0}”",
    TextKey.ASSIST_SALAM_REPLY to "And peace be upon you.",
    TextKey.ASSIST_MORNING_REPLY to "Good morning.",
    TextKey.ASSIST_EVENING_REPLY to "Good evening.",
    TextKey.ASSIST_OPENER_SALAM to "And peace be upon you,",
    TextKey.ASSIST_OPENER_HELLO to "Hi,",
    TextKey.ASSIST_OPENER_UNDERSTOOD to "Got it now.",
    TextKey.ASSIST_OPENER_AGAIN to "The figure now:",
    TextKey.ASSIST_WHO_ARE_YOU to "I'm Masroufy, your money assistant. I'm not an AI yet: I run on rules on your phone, I answer only from your own numbers, and nothing leaves your account.",
    TextKey.ASSIST_HELP to "I can answer about your spending, due dates and people, record an expense you type like “coffee 15”, split a bill, and take you to any screen.",
    TextKey.ASSIST_FRUSTRATION to "Sorry I didn't get that. Try for example: “{0}”",
    TextKey.ASSIST_ADVICE_BOUNDARY to "I don't recommend buying or selling a specific investment. I can show your assets and their value, and the savings calculators and insights can help you decide.",
    TextKey.ASSIST_PERIOD_THIS_MONTH to "this month",
    TextKey.ASSIST_PERIOD_LAST_MONTH to "last month",
    TextKey.ASSIST_PERIOD_IN to "in {0}",
    TextKey.ASSIST_PERIOD_THIS_WEEK to "this week (from Saturday)",
    TextKey.ASSIST_PERIOD_LAST_WEEK to "last week",
    TextKey.ASSIST_PERIOD_TODAY to "today",
    TextKey.ASSIST_PERIOD_YESTERDAY to "yesterday",
    TextKey.ASSIST_PERIOD_DAY_BEFORE to "the day before yesterday",
    TextKey.ASSIST_PERIOD_THIS_YEAR to "since the start of the year",
    TextKey.ASSIST_PERIOD_LAST_YEAR to "last year",
    TextKey.ASSIST_PERIOD_LAST_DAYS to "in the last {0} days",
    TextKey.ASSIST_PERIOD_LAST_MONTHS to "in the last {0} months",
    TextKey.ASSIST_PERIOD_DAYS_AGO to "{0} days ago",
    TextKey.ASSIST_PERIOD_ON_DATE to "on {0}",
    TextKey.ASSIST_PERIOD_SINCE to "since {0}",
    TextKey.ASSIST_MONTHS to "January|February|March|April|May|June|July|August|September|October|November|December",
    TextKey.ASSIST_DATE to "{0} {1}",
    TextKey.ASSIST_DATE_YEAR to "{0} {1} {2}",
    TextKey.ASSIST_DAYS_ONE to "1 day",
    TextKey.ASSIST_DAYS_TWO to "2 days",
    TextKey.ASSIST_DAYS_FEW to "{0} days",
    TextKey.ASSIST_DAYS_MANY to "{0} days",
    TextKey.ASSIST_TIMES_ONE to "once",
    TextKey.ASSIST_TIMES_TWO to "twice",
    TextKey.ASSIST_TIMES_FEW to "{0} times",
    TextKey.ASSIST_TIMES_MANY to "{0} times",
    TextKey.ASSIST_LIST_COMMA to ", ",
    TextKey.ASSIST_LIST_AND to " and ",
    TextKey.ASSIST_QUOTE to "“{0}”",
    TextKey.ASSIST_OPEN_SCREEN to "Open {0}",
    TextKey.ASSIST_APPROXIMATE to "(approximate)",
)
