package app.masroufy.core

/**
 * «البلدان» (`Spaces`) + «المحافظ» (`Wallets`) — منطقة «المزيد». من النموذج بالحرف، إلا:
 * - رسالة غلط البلدان عامة («تحقق من الاتصال») بدل «تكمل المحاولة التالية الناقص» (مش متأكدين منها في كوتلن — CLAUDE.md #15).
 * - «•••• ١٢٣٤» بعد النوع بفاصل «·» جنب النقط (مش جنب رقم) زي النموذج؛ والعدد قبل «،» دايمًا.
 * - سطر «غير متاح بعد» للإنشاء والأرشفة — كتابة Claude.
 */
internal val MSA_MORE_SPACES_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.SPC_TITLE to "البلدان",
    TextKey.SPC_INTRO to "لكل بلد حساب منفصل بمحافظه وميزانيته وأرقامه، ولا تحويل عملة بينها.",
    TextKey.SPC_ERR_TITLE to "تعذّر حفظ آخر تغيير",
    TextKey.SPC_ERR_BODY to "تحقق من الاتصال ثم أعد المحاولة.",
    TextKey.SPC_ACTIVE_HEAD to "النشطة ({0})",
    TextKey.SPC_ARCHIVED_HEAD to "المؤرشفة ({0})",
    TextKey.SPC_META_AUTO to "أُنشئ تلقائيًا",
    TextKey.SPC_META_ADDED to "أضفتها في {0}",
    TextKey.SPC_META_ARCHIVED to "مؤرشفة: بلا مزامنة ولا تنبيهات",
    TextKey.SPC_DEFAULT_NOTE to "حساب السعودية الأساسي لا يُؤرشف",
    TextKey.SPC_SWITCH to "بدّل إليها",
    TextKey.SPC_ARCHIVE to "أرشفة",
    TextKey.SPC_UNARCHIVE to "أرجعها من الأرشيف",
    TextKey.SPC_UNARCHIVED to "عادت {0} — وعادت المزامنة والتنبيهات",
    TextKey.SPC_ADD to "أضف بلدًا",
    TextKey.SPC_TRANSFER to "التحويل لنفسك بين البلدين",
    TextKey.SPC_SHARED_TITLE to "مشترك بين البلدان",
    TextKey.SPC_SHARED_BODY to "ملفك ويوم الراتب والقفل والأشخاص والتجار والوسوم. والنسخة الاحتياطية واحدة تشمل كل البلدان.",
    TextKey.SPC_ADD_BODY to "يبدأ البلد الجديد بشجرة تصنيفات بلده ومحافظ فارغة. إنشاؤه لا ينقلك إليه تلقائيًا.",
    TextKey.SPC_SUPPORTED to "البلدان المدعومة الآن: السعودية ومصر.",
    TextKey.SPC_ADMIN_NOT_YET to "إنشاء بلد وأرشفته غير متاحين بعد على الجوال.",
    TextKey.SPC_CREATE to "أنشئ الحساب",
    TextKey.SPC_CREATE_NAMED to "أنشئ حساب {0}",
    TextKey.SPC_CREATED to "أُنشئ حساب {0} — بدّل إليه متى شئت",
    TextKey.SPC_TAKEN to "لديك حساب «{0}» سابقًا — لكل بلد حساب واحد",
    TextKey.SPC_TAKEN_ARCHIVED to "مؤرشفة — أرجعها من الأرشيف بدل إنشاء أخرى",
    TextKey.SPC_ARCHIVE_Q to "أرشفة حساب {0}؟",
    TextKey.SPC_ARCHIVE_BODY to "لا يُحذف شيء. تتوقف المزامنة والتنبيهات، وتبقى البيانات في النسخة الاحتياطية، وتعيدها متى شئت.",
    TextKey.SPC_ARCHIVE_BACK_TO_SA to "وستنتقل إلى حساب السعودية.",
    TextKey.SPC_ARCHIVED_DONE to "أُرشفت {0}",
    TextKey.WLIST_TITLE to "المحافظ",
    TextKey.WLIST_BANKS to "البنوك",
    TextKey.WLIST_DIGITAL to "المحافظ الإلكترونية",
    TextKey.WLIST_CASH to "الكاش",
    TextKey.WLIST_KIND_BANK to "حساب بنكي",
    TextKey.WLIST_KIND_DIGITAL to "محفظة إلكترونية",
    TextKey.WLIST_KIND_CASH to "كاش",
    TextKey.WLIST_KIND_ABROAD to "حساب في بلد آخر",
    TextKey.WLIST_META_LAST4 to "{0} · •••• {1}",
    TextKey.WLIST_MAIN to "الأساسية",
    TextKey.WLIST_OPENING to "رصيد البداية {0} في {1}",
    TextKey.WLIST_EMPTY_LINE to "لا محافظ في هذا البلد بعد",
    TextKey.WLIST_UNKNOWN_LINE to "لا يشمل «{0}» — رصيدها غير متاح بعد.",
    TextKey.WLIST_AND to "» و«",
    TextKey.WLIST_TOTAL_LINE to "في {0} في هذا البلد",
    TextKey.WLIST_ONE to "محفظة واحدة",
    TextKey.WLIST_TWO to "محفظتين",
    TextKey.WLIST_FEW to "{0} محافظ",
    TextKey.WLIST_MANY to "{0} محفظة",
)

internal val EGYPTIAN_MORE_SPACES_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.SPC_TITLE to "البلاد",
    TextKey.SPC_INTRO to "كل بلد ليها حساب لوحدها بمحافظها وميزانيتها وأرقامها، ومفيش تحويل عملة بينهم.",
    TextKey.SPC_ERR_TITLE to "ما اتحفظش آخر تغيير",
    TextKey.SPC_ERR_BODY to "اتأكد من النت وجرّب تاني.",
    TextKey.SPC_ACTIVE_HEAD to "الشغالة ({0})",
    TextKey.SPC_ARCHIVED_HEAD to "المؤرشفة ({0})",
    TextKey.SPC_META_AUTO to "اتعمل لوحده",
    TextKey.SPC_META_ADDED to "ضفتها في {0}",
    TextKey.SPC_META_ARCHIVED to "مؤرشفة: من غير مزامنة ولا تنبيهات",
    TextKey.SPC_DEFAULT_NOTE to "حساب السعودية الأساسي ما بيتأرشفش",
    TextKey.SPC_SWITCH to "بدّل لها",
    TextKey.SPC_ARCHIVE to "أرشفة",
    TextKey.SPC_UNARCHIVE to "رجّعها من الأرشيف",
    TextKey.SPC_UNARCHIVED to "رجعت {0} — والمزامنة والتنبيهات شغالة تاني",
    TextKey.SPC_ADD to "ضيف بلد",
    TextKey.SPC_TRANSFER to "تحويلاتك بين البلاد",
    TextKey.SPC_SHARED_TITLE to "مشترك بين البلاد",
    TextKey.SPC_SHARED_BODY to "ملفك ويوم المرتب والقفل والأشخاص والتجار والوسوم. والنسخة الاحتياطية واحدة فيها كل البلاد.",
    TextKey.SPC_ADD_BODY to "البلد الجديدة بتبدأ بشجرة تصنيفات بلدها ومحافظ فاضية. إنشاؤها ما بيبدّلش لها لوحده.",
    TextKey.SPC_SUPPORTED to "البلاد المدعومة دلوقتي: السعودية ومصر.",
    TextKey.SPC_ADMIN_NOT_YET to "إنشاء بلد وأرشفتها لسه مش متاحين على الجوال.",
    TextKey.SPC_CREATE to "اعمل الحساب",
    TextKey.SPC_CREATE_NAMED to "اعمل حساب {0}",
    TextKey.SPC_CREATED to "اتعمل حساب {0} — بدّل له وقت ما تحب",
    TextKey.SPC_TAKEN to "عندك حساب «{0}» قبل كده — كل بلد ليها حساب واحد",
    TextKey.SPC_TAKEN_ARCHIVED to "مؤرشفة — رجّعها من الأرشيف بدل ما تعمل واحدة جديدة",
    TextKey.SPC_ARCHIVE_Q to "أرشفة حساب {0}؟",
    TextKey.SPC_ARCHIVE_BODY to "مفيش حاجة بتتمسح. المزامنة والتنبيهات بتقف، والبيانات بتفضل في النسخة الاحتياطية، وترجّعها وقت ما تحب.",
    TextKey.SPC_ARCHIVE_BACK_TO_SA to "وهترجع لحساب السعودية.",
    TextKey.SPC_ARCHIVED_DONE to "اتأرشفت {0}",
    TextKey.WLIST_TITLE to "المحافظ",
    TextKey.WLIST_BANKS to "البنوك",
    TextKey.WLIST_DIGITAL to "المحافظ الإلكترونية",
    TextKey.WLIST_CASH to "الكاش",
    TextKey.WLIST_KIND_BANK to "حساب بنك",
    TextKey.WLIST_KIND_DIGITAL to "محفظة إلكترونية",
    TextKey.WLIST_KIND_CASH to "كاش",
    TextKey.WLIST_KIND_ABROAD to "حساب في بلد تانية",
    TextKey.WLIST_META_LAST4 to "{0} · •••• {1}",
    TextKey.WLIST_MAIN to "الأساسية",
    TextKey.WLIST_OPENING to "رصيد البداية {0} في {1}",
    TextKey.WLIST_EMPTY_LINE to "مفيش محافظ في البلد دي لسه",
    TextKey.WLIST_UNKNOWN_LINE to "من غير «{0}» — رصيدها مش متاح لسه.",
    TextKey.WLIST_AND to "» و«",
    TextKey.WLIST_TOTAL_LINE to "في {0} في البلد دي",
    TextKey.WLIST_ONE to "محفظة واحدة",
    TextKey.WLIST_TWO to "محفظتين",
    TextKey.WLIST_FEW to "{0} محافظ",
    TextKey.WLIST_MANY to "{0} محفظة",
)

internal val ENGLISH_MORE_SPACES_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.SPC_TITLE to "Countries",
    TextKey.SPC_INTRO to "Each country has its own account with its wallets, budget and figures, and no currency conversion between them.",
    TextKey.SPC_ERR_TITLE to "Your last change wasn't saved",
    TextKey.SPC_ERR_BODY to "Check your connection and try again.",
    TextKey.SPC_ACTIVE_HEAD to "Active ({0})",
    TextKey.SPC_ARCHIVED_HEAD to "Archived ({0})",
    TextKey.SPC_META_AUTO to "Created automatically",
    TextKey.SPC_META_ADDED to "Added on {0}",
    TextKey.SPC_META_ARCHIVED to "Archived: no sync or alerts",
    TextKey.SPC_DEFAULT_NOTE to "The main Saudi account can't be archived",
    TextKey.SPC_SWITCH to "Switch to it",
    TextKey.SPC_ARCHIVE to "Archive",
    TextKey.SPC_UNARCHIVE to "Restore from archive",
    TextKey.SPC_UNARCHIVED to "{0} is back — sync and alerts are on again",
    TextKey.SPC_ADD to "Add a country",
    TextKey.SPC_TRANSFER to "Transfers to yourself between countries",
    TextKey.SPC_SHARED_TITLE to "Shared across countries",
    TextKey.SPC_SHARED_BODY to "Your profile, payday, lock, people, merchants and tags. And one backup covers every country.",
    TextKey.SPC_ADD_BODY to "A new country starts with its own category tree and empty wallets. Creating it doesn't switch you to it.",
    TextKey.SPC_SUPPORTED to "Supported countries now: Saudi Arabia and Egypt.",
    TextKey.SPC_ADMIN_NOT_YET to "Creating and archiving a country isn't available on the phone yet.",
    TextKey.SPC_CREATE to "Create the account",
    TextKey.SPC_CREATE_NAMED to "Create the {0} account",
    TextKey.SPC_CREATED to "The {0} account was created — switch to it any time",
    TextKey.SPC_TAKEN to "You already have a “{0}” account — one account per country",
    TextKey.SPC_TAKEN_ARCHIVED to "Archived — restore it instead of creating another",
    TextKey.SPC_ARCHIVE_Q to "Archive the {0} account?",
    TextKey.SPC_ARCHIVE_BODY to "Nothing is deleted. Sync and alerts stop, the data stays in the backup, and you can bring it back any time.",
    TextKey.SPC_ARCHIVE_BACK_TO_SA to "You'll move to the Saudi account.",
    TextKey.SPC_ARCHIVED_DONE to "{0} was archived",
    TextKey.WLIST_TITLE to "Wallets",
    TextKey.WLIST_BANKS to "Banks",
    TextKey.WLIST_DIGITAL to "E-wallets",
    TextKey.WLIST_CASH to "Cash",
    TextKey.WLIST_KIND_BANK to "Bank account",
    TextKey.WLIST_KIND_DIGITAL to "E-wallet",
    TextKey.WLIST_KIND_CASH to "Cash",
    TextKey.WLIST_KIND_ABROAD to "Account abroad",
    TextKey.WLIST_META_LAST4 to "{0} · •••• {1}",
    TextKey.WLIST_MAIN to "Main",
    TextKey.WLIST_OPENING to "Opening balance {0} on {1}",
    TextKey.WLIST_EMPTY_LINE to "No wallets in this country yet",
    TextKey.WLIST_UNKNOWN_LINE to "Doesn't include “{0}” — its balance isn't available yet.",
    TextKey.WLIST_AND to "” and “",
    TextKey.WLIST_TOTAL_LINE to "Across {0} in this country",
    TextKey.WLIST_ONE to "one wallet",
    TextKey.WLIST_TWO to "two wallets",
    TextKey.WLIST_FEW to "{0} wallets",
    TextKey.WLIST_MANY to "{0} wallets",
)
