package app.masroufy.core

/**
 * نصوص الفلوس والكميات ورسايل البنك والنسخة الاحتياطية والألوان بالعربي — **الأصل** زي ما كان في الكود بالحرف.
 * (الجدول اتقسم لملفين عشان حد الـ300 سطر — CLAUDE.md #7.)
 */
internal val ARABIC_DATA_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.COLOR_RED to "أحمر",
    TextKey.COLOR_ORANGE to "برتقالي",
    TextKey.COLOR_AMBER to "كهرماني",
    TextKey.COLOR_OLIVE to "زيتوني",
    TextKey.COLOR_LIME to "ليموني",
    TextKey.COLOR_GREEN to "أخضر",
    TextKey.COLOR_MINT to "نعناعي",
    TextKey.COLOR_TEAL to "فيروزي",
    TextKey.COLOR_CYAN to "سماوي",
    TextKey.COLOR_BLUE to "أزرق",
    TextKey.COLOR_INDIGO to "نيلي",
    TextKey.COLOR_PURPLE to "بنفسجي",
    TextKey.COLOR_LILAC to "ليلكي",
    TextKey.COLOR_MAGENTA to "أرجواني",
    TextKey.COLOR_FUCHSIA to "فوشيا",
    TextKey.COLOR_ROSE to "وردي",
    TextKey.COLOR_SLATE to "رمادي مزرق",
    TextKey.COLOR_GRAY to "رمادي",
    TextKey.BACKUP_GROUP_WALLETS to "المحافظ",
    TextKey.BACKUP_GROUP_CATEGORIES to "التصنيفات",
    TextKey.BACKUP_GROUP_MERCHANTS to "التجار",
    TextKey.BACKUP_GROUP_RULES to "القواعد",
    TextKey.BACKUP_GROUP_PEOPLE to "الأشخاص",
    TextKey.BACKUP_GROUP_ASSETS to "الأصول",
    TextKey.BACKUP_GROUP_TAGS to "الوسوم",
    TextKey.BACKUP_GROUP_BUDGETS to "الميزانيات",
    TextKey.BACKUP_GROUP_RECURRING_ITEMS to "الاشتراكات والفواتير",
    TextKey.BACKUP_GROUP_IMPORT_BATCHES to "دفعات الاستيراد",
    TextKey.BACKUP_GROUP_TRANSACTIONS to "العمليات",
    TextKey.BACKUP_GROUP_OBLIGATIONS to "الديون والأمانات",
    TextKey.BACKUP_GROUP_ALLOCATIONS to "تخصيصات الأشخاص",
    TextKey.BACKUP_GROUP_SETTLEMENTS to "التسويات",
    TextKey.BACKUP_GROUP_SOURCE_RECORDS to "مصادر العمليات",
    TextKey.BACKUP_GROUP_TRANSACTION_TAGS to "روابط الوسوم",
    TextKey.BACKUP_GROUP_CATEGORY_BUDGETS to "سقوف التصنيفات",
    TextKey.BACKUP_GROUP_ASSET_LOTS to "مشتريات الأصول",
    TextKey.BACKUP_GROUP_ASSET_SALES to "مبيعات الأصول",
    TextKey.BACKUP_GROUP_ASSET_PRICES to "أسعار الأصول",
    TextKey.BACKUP_GROUP_NOTIFICATION_RECEIPTS to "حالات قراءة التنبيهات",
    TextKey.BACKUP_GROUP_PROJECTS to "المشاريع",
    TextKey.BACKUP_GROUP_PROJECT_LINKS to "روابط المشاريع",
    TextKey.BACKUP_GROUP_PROJECT_RULES to "قواعد المشاريع",
    TextKey.AMOUNT_CONTEXT_DEFAULT to "مبلغ",
    TextKey.MONEY_OUT_OF_RANGE_CONTEXT to "{0}: المبلغ خارج المدى الآمن",
    TextKey.MONEY_EMPTY to "المبلغ فارغ",
    TextKey.MONEY_BAD_FORMAT to "صيغة المبلغ غير صالحة",
    TextKey.MONEY_TOO_MANY_DECIMALS to "المبلغ فيه أكثر من {0} خانة كسرية غير صفرية — لا يُقرَّب بصمت",
    TextKey.MONEY_RESULT_OUT_OF_RANGE to "الناتج: المبلغ خارج المدى الآمن",
    TextKey.MONEY_DIVIDE_BY_ZERO to "القسمة على صفر",
    TextKey.MONEY_PARTS_POSITIVE to "عدد الحصص يجب أن يكون عددًا صحيحًا موجبًا",
    TextKey.AMOUNT_CONTEXT_TOTAL to "المجموع",
    TextKey.AMOUNT_CONTEXT_DIFFERENCE to "الفرق",
    TextKey.AMOUNT_CONTEXT_SHARE to "النسبة",
    TextKey.QUANTITY_CONTEXT_DEFAULT to "كمية",
    TextKey.QUANTITY_OUT_OF_RANGE_CONTEXT to "{0}: الكمية أكبر من الحد الآمن للحساب",
    TextKey.QUANTITY_EMPTY to "اكتب الكمية",
    TextKey.QUANTITY_TWO_POINTS to "الكمية فيها أكتر من علامة عشرية",
    TextKey.QUANTITY_INVALID to "«{0}» مش كمية صالحة",
    TextKey.QUANTITY_TOO_MANY_DECIMALS to "الكمية بأكتر من {0} أرقام عشرية. التطبيق مش هيقرّبها من ورا ظهرك — قصّرها بنفسك.",
    TextKey.QUANTITY_NOT_A_NUMBER to "«{0}»: القيمة مش رقم صالح",
    TextKey.QUANTITY_OUT_OF_RANGE to "«{0}»: الكمية أكبر من الحد الآمن للحساب",
    TextKey.QUANTITY_CONTEXT_TOTAL to "مجموع الكميات",
    TextKey.QUANTITY_DIVIDE_BY_ZERO to "قسمة على صفر",
    TextKey.QUANTITY_RESULT_OUT_OF_RANGE to "النتيجة أكبر من الحد الآمن للحساب",
    TextKey.QUANTITY_CONTEXT_PART to "الكمية الجزئية",
    TextKey.QUANTITY_CONTEXT_WHOLE to "الكمية الكلية",
    TextKey.QUANTITY_WHOLE_POSITIVE to "الكمية الكلية لازم تكون أكبر من صفر",
    TextKey.QUANTITY_PART_NEGATIVE to "الكمية الجزئية لا تكون سالبة",
    TextKey.QUANTITY_PART_OVER_WHOLE to "الكمية الجزئية ({0}) أكبر من الكلية ({1})",
    TextKey.SMS_AMOUNT_INVALID to "المبلغ غير صالح",
    TextKey.SMS_MULTIPLE_AMOUNTS to "يوجد أكثر من مبلغ عملية في الرسالة",
    TextKey.SMS_CURRENCY_UNCLEAR to "عملة المبلغ غير مذكورة بوضوح",
    TextKey.SMS_AMOUNT_UNCLEAR to "مبلغ العملية غير واضح",
    TextKey.SMS_OFFER to "عرض أو حركة مستقبلية وليست عملية مكتملة",
    TextKey.SMS_SENSITIVE to "رسالة تحقق أو كلمة سر؛ تم تجاهلها",
    TextKey.SMS_DECLINED to "عملية مرفوضة أو غير مكتملة",
    TextKey.SMS_DIRECTION_UNCLEAR to "اتجاه الحركة غير واضح؛ لم نفترض أنها دخل أو مصروف",
    TextKey.SMS_FOREIGN_CURRENCY to "النسخة الحالية تدعم رسائل الريال السعودي فقط",
    TextKey.SMS_DATE_UNCLEAR to "تاريخ العملية غير واضح؛ تاريخ وصول الرسالة لا يكفي",
    TextKey.PDF_DEBIT_AND_CREDIT to "العملية فيها مدين ودائن مع بعض — مش واضح اتجاهها",
    TextKey.PDF_ZERO_AMOUNT to "العملية مبلغها صفر في المدين والدائن",
    TextKey.BACKUP_PROFILE_INVALID to "ملف الحساب في النسخة غير صالح",
    TextKey.BACKUP_PROFILE_INVALID_FIELD to "ملف الحساب في النسخة غير صالح: {0}",
    TextKey.BACKUP_DATA_INVALID to "بيانات النسخة غير صالحة",
    TextKey.BACKUP_GROUP_MISSING to "مجموعة ناقصة: {0}",
    TextKey.BACKUP_ROW_INVALID to "سجل غير صالح: {0}",
    TextKey.BACKUP_ID_INVALID to "معرّف غير صالح أو مكرر: {0}",
    TextKey.BACKUP_FIELD_MISSING to "حقل ناقص: {0}.{1}",
    TextKey.BACKUP_IMPORT_UNFINISHED to "فيه استيراد غير مكتمل. افتح التطبيق واستكمل تنظيفه قبل النسخ",
    TextKey.BACKUP_BUDGET_ID to "معرّف الميزانية مختلف عن الفترة",
    TextKey.BACKUP_RELATION_MISSING to "علاقة ناقصة: {0}.{1}",
    TextKey.BACKUP_TEXT_INVALID to "نص غير صالح: {0}.{1}",
    TextKey.BACKUP_NUMBER_INVALID to "مبلغ أو عدد غير صحيح: {0}",
    TextKey.BACKUP_NEGATIVE_AMOUNT to "مبلغ سالب: {0}",
    TextKey.BACKUP_BOOLEAN_INVALID to "قيمة منطقية غير صالحة: {0}",
    TextKey.BACKUP_DATE_INVALID to "تاريخ غير صالح: {0}",
    TextKey.BACKUP_CURRENCY_INVALID to "عملة غير صالحة",
    TextKey.BACKUP_LAST_FOUR_ONLY to "المسموح آخر أربعة أرقام فقط",
    TextKey.BACKUP_DIRECTION_INVALID to "اتجاه عملية غير صالح",
    TextKey.BACKUP_AMOUNT_POSITIVE to "مبلغ العملية لازم يكون موجبًا",
    TextKey.BACKUP_CYCLE_INVALID to "دورة اشتراك غير صالحة",
    TextKey.BACKUP_KIND_INVALID to "نوع اقتصادي غير صالح",
    TextKey.BACKUP_VALUE_UNSUPPORTED to "قيمة غير مدعومة: {0}.{1}",
    TextKey.BACKUP_COUNTER_INVALID to "عداد استيراد غير صالح",
    TextKey.BACKUP_ALLOCATION_CURRENCY to "عملة تخصيص الشخص مختلفة عن العملية",
    TextKey.BACKUP_ALLOCATIONS_EXCEED to "تخصيصات الأشخاص تتجاوز مبلغ العملية",
    TextKey.BACKUP_OBLIGATION_POSITIVE to "الدين القديم لازم مبلغه يكون موجب",
    TextKey.BACKUP_OBLIGATION_MISMATCH to "الدين غير متوافق مع العملية الأصلية",
    TextKey.BACKUP_SETTLEMENT_MISMATCH to "تسوية غير متوافقة مع عملة أو مبلغ العملية",
    TextKey.BACKUP_SETTLEMENTS_EXCEED to "التسويات تتجاوز الدين الأصلي",

    TextKey.RECONCILE_FIRST_GAP_MANY to "أول فرق في {0}، واليوم ده فيه {1} حركة. ترتيب حركات اليوم الواحد مش مثبت في الكشف، فمش أكيد إن دي بالذات هي أول عملية فيها مشكلة.",
    TextKey.RECONCILE_FIRST_GAP_ONE to "أول فرق في {0}، واليوم ده فيه حركة واحدة، فالفرق يخصها هي.",

    TextKey.SMS_NOT_EGP to "النسخة الحالية تدعم رسائل الجنيه المصري فقط",
)
