package app.masroufy.core

/**
 * نصوص حاسبة الورث (OVERRIDES §69): فصحى (§66) · مصري. الإنجليزي في `TextsInheritanceEnglish.kt`.
 * - **كلام بسيط** (§66 — الكلمات الثقيلة): المصطلح الفقهي (العَوْل · الرَّدّ · الحَجْب …) بيتكتب **بين قوسين بعد شرح بسيط**، مش لوحده.
 * - التنبيه تحت كل نتيجة بنص المالك بالحرف (§69).
 */
internal val MSA_INHERITANCE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INHERIT_LAW_SA to "نظام الأحوال الشخصية (1443هـ)",
    TextKey.INHERIT_LAW_EG_77 to "قانون المواريث رقم 77 لسنة 1943",
    TextKey.INHERIT_LAW_EG_71 to "قانون الوصية رقم 71 لسنة 1946",
    TextKey.INHERIT_CITATION to "المادة {0} من {1}",
    TextKey.INHERIT_DISCLAIMER to "حساب تقريبي للتخطيط، والقسمة الرسمية بصك حصر الورثة من المحكمة",
    TextKey.INHERIT_HEIR_HUSBAND to "الزوج",
    TextKey.INHERIT_HEIR_WIFE to "الزوجة",
    TextKey.INHERIT_HEIR_SON to "الابن",
    TextKey.INHERIT_HEIR_DAUGHTER to "البنت",
    TextKey.INHERIT_HEIR_FATHER to "الأب",
    TextKey.INHERIT_HEIR_MOTHER to "الأم",
    TextKey.INHERIT_HEIR_GRANDFATHER to "الجد (أبو الأب)",
    TextKey.INHERIT_HEIR_PATERNAL_GRANDMOTHER to "الجدة (أم الأب)",
    TextKey.INHERIT_HEIR_MATERNAL_GRANDMOTHER to "الجدة (أم الأم)",
    TextKey.INHERIT_HEIR_SON_SON to "ابن الابن",
    TextKey.INHERIT_HEIR_SON_DAUGHTER to "بنت الابن",
    TextKey.INHERIT_HEIR_FULL_BROTHER to "الأخ الشقيق",
    TextKey.INHERIT_HEIR_FULL_SISTER to "الأخت الشقيقة",
    TextKey.INHERIT_HEIR_PATERNAL_BROTHER to "الأخ من الأب",
    TextKey.INHERIT_HEIR_PATERNAL_SISTER to "الأخت من الأب",
    TextKey.INHERIT_HEIR_MATERNAL_BROTHER to "الأخ من الأم",
    TextKey.INHERIT_HEIR_MATERNAL_SISTER to "الأخت من الأم",
    TextKey.INHERIT_HEIR_FULL_NEPHEW to "ابن الأخ الشقيق",
    TextKey.INHERIT_HEIR_PATERNAL_NEPHEW to "ابن الأخ من الأب",
    TextKey.INHERIT_HEIR_FULL_UNCLE to "العم الشقيق",
    TextKey.INHERIT_HEIR_PATERNAL_UNCLE to "العم من الأب",
    TextKey.INHERIT_HEIR_FULL_COUSIN to "ابن العم الشقيق",
    TextKey.INHERIT_HEIR_PATERNAL_COUSIN to "ابن العم من الأب",
    TextKey.INHERIT_NOTE_ORDER to "الترتيب: تجهيز الميت، ثم الديون، ثم الوصية، ثم الورثة",
    TextKey.INHERIT_NOTE_BLOCKED to "{0} لا يرث لوجود {1} (الحَجْب)",
    TextKey.INHERIT_NOTE_AWL to "الأنصبة أكثر من التركة، فنقص نصيب كل وارث بالنسبة نفسها (العَوْل): من {0} إلى {1}",
    TextKey.INHERIT_NOTE_RADD to "بقي جزء من التركة ولا يوجد من يأخذ الباقي، فرُدّ على أصحاب الأنصبة غير الزوجين بنسبة أنصبتهم (الرَّدّ)",
    TextKey.INHERIT_NOTE_RADD_SPOUSE to "لا وارث غير {0} ولا أقارب آخرون، فأخذ التركة كلها (الرَّدّ)",
    TextKey.INHERIT_NOTE_UMARIYYA to "الورثة هم الأب والأم و{0} فقط، فتأخذ الأم ثلث الباقي بعد نصيب {0} (العُمَرية)",
    TextKey.INHERIT_NOTE_GF_MOTHER_THIRD to "مع الجد تأخذ الأم ثلث التركة كلها لا ثلث الباقي",
    TextKey.INHERIT_NOTE_TAKMILA to "{0} تأخذ السدس مع {1} ليكتمل الثلثان",
    TextKey.INHERIT_NOTE_WITH_DAUGHTERS to "{0} تأخذ الباقي مع البنات (عصبة مع الغير)",
    TextKey.INHERIT_NOTE_RESIDUE_NONE to "الأنصبة المحددة أخذت التركة كلها، فلم يبق شيء لـ{0}",
    TextKey.INHERIT_NOTE_MUSHTARAKA_SHARED to "الإخوة الأشقاء يشاركون الإخوة من الأم في الثلث بالتساوي (المُشرَّكة)",
    TextKey.INHERIT_NOTE_MUSHTARAKA_DROPPED to "الإخوة الأشقاء لا يشاركون الإخوة من الأم في الثلث، ولم يبق لهم شيء (المُشرَّكة لا يُعمل بها)",
    TextKey.INHERIT_NOTE_GF_BLOCKS_SIBLINGS to "الجد يمنع الإخوة والأخوات من الإرث مثل الأب",
    TextKey.INHERIT_NOTE_GF_SHARES to "الجد يقاسم الإخوة كأنه أخ",
    TextKey.INHERIT_NOTE_GF_RESIDUE to "الجد يأخذ الباقي بعد نصيب الأخوات",
    TextKey.INHERIT_NOTE_GF_SIXTH to "القسمة مع الإخوة كانت ستنقص الجد عن السدس، فأخذ السدس",
    TextKey.INHERIT_NOTE_DEBTS_EXCEED to "التجهيز والديون ({0}) أكثر من التركة ({1})، فلا يبقى شيء للوصية ولا للورثة",
    TextKey.INHERIT_NOTE_BEQUEST_CAPPED to "الوصية ({0}) أكثر من الثلث المتاح، فنُفّذ منها {1} فقط",
    TextKey.INHERIT_NOTE_BEQUEST_EXCESS_CONSENTED to "الوصية أكثر من الثلث، ونُفّذت لأن الورثة كلهم وافقوا بعد الوفاة",
    TextKey.INHERIT_NOTE_BEQUEST_HEIR_VOID to "الوصية لوارث لا تنفذ إلا إذا وافق باقي الورثة بعد الوفاة، فلم تُحسب",
    TextKey.INHERIT_NOTE_BEQUEST_HEIR_CONSENTED to "الوصية لوارث نُفّذت لأن باقي الورثة وافقوا",
    TextKey.INHERIT_NOTE_BEQUEST_HEIR_VALID to "الوصية لوارث جائزة في حدود الثلث دون موافقة الورثة",
    TextKey.INHERIT_NOTE_WAJIBA to "لأولاد {0} المتوفى قبله وصية واجبة قدرها {1}، تُخرج قبل قسمة الباقي",
    TextKey.INHERIT_NOTE_WAJIBA_CAPPED to "نصيب الأولاد المتوفين قبله أكثر من الثلث، فأُعطي أولادهم الثلث فقط",
    TextKey.INHERIT_NOTE_WAJIBA_GIFT to "خُصم ما أعطاهم إياه في حياته ({0})",
    TextKey.INHERIT_NOTE_NO_WAJIBA to "لا توجد وصية واجبة في النظام السعودي؛ أولاد الابن أو البنت المتوفى قبله لا يأخذون إلا بوصية",
    TextKey.INHERIT_NO_TEXT to "لا نص — اسأل المحكمة: {0}",
    TextKey.INHERIT_NO_TEXT_GF_MIXED to "الجد مع إخوة أشقاء وإخوة من الأب معًا، والمادة 22 لا تبيّن طريقة القسمة في هذه الحالة",
    TextKey.INHERIT_UNSUPPORTED_COUNTRY to "حاسبة الورث متاحة للسعودية ومصر فقط",
    TextKey.INHERIT_UNSUPPORTED_DISTANT to "يرث هنا أقارب آخرون (مثل أولاد البنات والخال والعمة)، وهذه النسخة لا تحسب أنصبتهم",
    TextKey.INHERIT_UNSUPPORTED_ASK_DISTANT to "هل للمتوفى أقارب آخرون مثل أولاد البنات أو الخال أو العمة؟ الجواب يغيّر القسمة",
    TextKey.INHERIT_UNSUPPORTED_NO_HEIRS to "لا يوجد وارث من الورثة المكتوبين؛ التركة لأقارب آخرين أو لبيت المال، وهذه النسخة لا تحسبها",
    TextKey.INHERIT_UNSUPPORTED_PREGNANCY to "وجود حمل يحتاج حفظ نصيب له حتى الولادة، وهذه النسخة لا تحسبه",
    TextKey.INHERIT_UNSUPPORTED_MISSING to "وجود وارث مفقود يحتاج حفظ نصيبه، وهذه النسخة لا تحسبه",
    TextKey.INHERIT_UNSUPPORTED_SUCCESSIVE to "وفاة وارث قبل القسمة تحتاج حساب تركتين معًا، وهذه النسخة لا تحسبه",
    TextKey.INHERIT_UNSUPPORTED_TAKHARUJ to "اتفاق الورثة على خروج أحدهم بمقابل (التخارج) لا تحسبه هذه النسخة",
    TextKey.INHERIT_UNSUPPORTED_PREDECEASED_SON to "لا يوجد ابن على قيد الحياة، فأولاد الابن المتوفى قبله قد يرثون بأنفسهم؛ اكتبهم أبناء ابن وبنات ابن",
    TextKey.INHERIT_INVALID_COUNT to "عدد {0} يجب أن يكون من 0 إلى {1}",
    TextKey.INHERIT_INVALID_WIVES to "الزوجات أربع على الأكثر",
    TextKey.INHERIT_INVALID_HUSBAND_WIFE to "لا يجتمع زوج وزوجة في مسألة واحدة",
    TextKey.INHERIT_INVALID_ONLY_ONE to "{0} واحد فقط",
    TextKey.INHERIT_INVALID_NO_ITEMS to "أضف شيئًا واحدًا على الأقل من التركة",
    TextKey.INHERIT_INVALID_ITEM_NAME to "اكتب اسم كل شيء في التركة",
    TextKey.INHERIT_INVALID_NEGATIVE to "المبالغ لا تكون بالسالب",
    TextKey.INHERIT_INVALID_TOO_LARGE to "الأرقام أكبر من المسموح",
    TextKey.INHERIT_INVALID_PREDECEASED to "اكتب عدد أولاد الابن أو البنت المتوفى قبله",
    TextKey.INHERIT_CLAIMANT_FUNERAL to "تجهيز الميت",
    TextKey.INHERIT_CLAIMANT_DEBTS to "الديون",
    TextKey.INHERIT_CLAIMANT_BEQUEST to "الوصية",
    TextKey.INHERIT_CLAIMANT_WAJIBA to "الوصية الواجبة",
)

/** نفس المفاتيح بالمصري (§66) — مفاتيح جديدة بس، والمصري القديم ما اتلمسش. */
internal val EGYPTIAN_INHERITANCE_TEXTS: Map<TextKey, String> = MSA_INHERITANCE_TEXTS + mapOf(
    TextKey.INHERIT_NOTE_ORDER to "الترتيب: تجهيز الميت، وبعدين الديون، وبعدين الوصية، وبعدين الورثة",
    TextKey.INHERIT_NOTE_BLOCKED to "{0} مش بيورث عشان فيه {1} (الحَجْب)",
    TextKey.INHERIT_NOTE_AWL to "الأنصبة طلعت أكتر من التركة، فنصيب كل وارث نقص بنفس النسبة (العَوْل): من {0} لـ{1}",
    TextKey.INHERIT_NOTE_RADD to "فضل جزء من التركة ومفيش حد ياخد الباقي، فرجع لأصحاب الأنصبة غير الزوجين بنسبة أنصبتهم (الرَّدّ)",
    TextKey.INHERIT_NOTE_RADD_SPOUSE to "مفيش وارث غير {0} ولا قرايب تانيين، فخد التركة كلها (الرَّدّ)",
    TextKey.INHERIT_NOTE_UMARIYYA to "الورثة الأب والأم و{0} بس، فالأم بتاخد تلت الباقي بعد نصيب {0} (العُمَرية)",
    TextKey.INHERIT_NOTE_GF_MOTHER_THIRD to "مع الجد الأم بتاخد تلت التركة كلها مش تلت الباقي",
    TextKey.INHERIT_NOTE_TAKMILA to "{0} بتاخد السدس مع {1} عشان يكمل التلتين",
    TextKey.INHERIT_NOTE_WITH_DAUGHTERS to "{0} بتاخد الباقي مع البنات (عصبة مع الغير)",
    TextKey.INHERIT_NOTE_RESIDUE_NONE to "الأنصبة المحددة خدت التركة كلها، فمفضلش حاجة لـ{0}",
    TextKey.INHERIT_NOTE_MUSHTARAKA_SHARED to "الإخوة الأشقاء بيشاركوا الإخوة من الأم في التلت بالتساوي (المُشرَّكة)",
    TextKey.INHERIT_NOTE_MUSHTARAKA_DROPPED to "الإخوة الأشقاء مش بيشاركوا الإخوة من الأم في التلت، ومفضلش ليهم حاجة (المُشرَّكة مش معمول بيها)",
    TextKey.INHERIT_NOTE_GF_BLOCKS_SIBLINGS to "الجد بيمنع الإخوة والأخوات من الورث زي الأب",
    TextKey.INHERIT_NOTE_GF_SHARES to "الجد بيقاسم الإخوة كأنه أخ",
    TextKey.INHERIT_NOTE_GF_RESIDUE to "الجد بياخد الباقي بعد نصيب الأخوات",
    TextKey.INHERIT_NOTE_GF_SIXTH to "القسمة مع الإخوة كانت هتنزّل الجد عن السدس، فخد السدس",
    TextKey.INHERIT_NOTE_DEBTS_EXCEED to "التجهيز والديون ({0}) أكتر من التركة ({1})، فمش هيفضل حاجة للوصية ولا للورثة",
    TextKey.INHERIT_NOTE_BEQUEST_CAPPED to "الوصية ({0}) أكتر من التلت المتاح، فاتنفذ منها {1} بس",
    TextKey.INHERIT_NOTE_BEQUEST_EXCESS_CONSENTED to "الوصية أكتر من التلت، واتنفذت عشان الورثة كلهم وافقوا بعد الوفاة",
    TextKey.INHERIT_NOTE_BEQUEST_HEIR_VOID to "الوصية لوارث مش بتتنفذ إلا لو باقي الورثة وافقوا بعد الوفاة، فمتحسبتش",
    TextKey.INHERIT_NOTE_BEQUEST_HEIR_CONSENTED to "الوصية لوارث اتنفذت عشان باقي الورثة وافقوا",
    TextKey.INHERIT_NOTE_BEQUEST_HEIR_VALID to "الوصية لوارث جايزة في حدود التلت من غير موافقة الورثة",
    TextKey.INHERIT_NOTE_WAJIBA to "لأولاد {0} اللي اتوفى قبله وصية واجبة قدرها {1}، بتطلع قبل قسمة الباقي",
    TextKey.INHERIT_NOTE_WAJIBA_CAPPED to "نصيب الأولاد اللي اتوفوا قبله أكتر من التلت، فأولادهم خدوا التلت بس",
    TextKey.INHERIT_NOTE_WAJIBA_GIFT to "اتخصم اللي اداهولهم في حياته ({0})",
    TextKey.INHERIT_NOTE_NO_WAJIBA to "مفيش وصية واجبة في النظام السعودي؛ أولاد الابن أو البنت اللي اتوفى قبله مش بياخدوا إلا بوصية",
    TextKey.INHERIT_NO_TEXT to "مفيش نص — اسأل المحكمة: {0}",
    TextKey.INHERIT_NO_TEXT_GF_MIXED to "الجد مع إخوة أشقاء وإخوة من الأب مع بعض، والمادة 22 مش بتقول القسمة إزاي في الحالة دي",
    TextKey.INHERIT_UNSUPPORTED_COUNTRY to "حاسبة الورث متاحة للسعودية ومصر بس",
    TextKey.INHERIT_UNSUPPORTED_DISTANT to "هنا فيه قرايب تانيين بيورثوا (زي أولاد البنات والخال والعمة)، والنسخة دي مش بتحسب أنصبتهم",
    TextKey.INHERIT_UNSUPPORTED_ASK_DISTANT to "المتوفى ليه قرايب تانيين زي أولاد البنات أو الخال أو العمة؟ الإجابة بتغيّر القسمة",
    TextKey.INHERIT_UNSUPPORTED_NO_HEIRS to "مفيش وارث من الورثة المكتوبين؛ التركة لقرايب تانيين أو للخزانة العامة، والنسخة دي مش بتحسبها",
    TextKey.INHERIT_UNSUPPORTED_PREGNANCY to "وجود حمل محتاج نصيب يتحفظ له لحد الولادة، والنسخة دي مش بتحسبه",
    TextKey.INHERIT_UNSUPPORTED_MISSING to "وجود وارث مفقود محتاج نصيبه يتحفظ، والنسخة دي مش بتحسبه",
    TextKey.INHERIT_UNSUPPORTED_SUCCESSIVE to "وفاة وارث قبل القسمة محتاجة حساب تركتين مع بعض، والنسخة دي مش بتحسبه",
    TextKey.INHERIT_UNSUPPORTED_TAKHARUJ to "اتفاق الورثة إن حد فيهم يخرج بمقابل (التخارج) النسخة دي مش بتحسبه",
    TextKey.INHERIT_UNSUPPORTED_PREDECEASED_SON to "مفيش ابن عايش، فأولاد الابن اللي اتوفى قبله ممكن يورثوا بنفسهم؛ اكتبهم أبناء ابن وبنات ابن",
    TextKey.INHERIT_INVALID_COUNT to "عدد {0} لازم يكون من 0 لـ{1}",
    TextKey.INHERIT_INVALID_WIVES to "الزوجات أربعة بالكتير",
    TextKey.INHERIT_INVALID_HUSBAND_WIFE to "مينفعش زوج وزوجة في نفس المسألة",
    TextKey.INHERIT_INVALID_ONLY_ONE to "{0} واحد بس",
    TextKey.INHERIT_INVALID_NO_ITEMS to "ضيف حاجة واحدة على الأقل من التركة",
    TextKey.INHERIT_INVALID_ITEM_NAME to "اكتب اسم كل حاجة في التركة",
    TextKey.INHERIT_INVALID_NEGATIVE to "المبالغ مينفعش تبقى بالسالب",
    TextKey.INHERIT_INVALID_TOO_LARGE to "الأرقام أكبر من المسموح",
    TextKey.INHERIT_INVALID_PREDECEASED to "اكتب عدد أولاد الابن أو البنت اللي اتوفى قبله",
)
