package app.masroufy.core

/**
 * منطقة «المستحقات» — الجزء الأول بالإنجليزي (كتابة Claude — مستني مراجعة المالك §40). نفس مفاتيح ومتغيرات `TextsAreaDuesDebts.kt`.
 */
internal val ENGLISH_DUES_DEBTS_TEXTS: Map<TextKey, String> = mapOf(
    // ── Dues panel and shared words
    TextKey.DUES_FOR_YOU to "Owed to you",
    TextKey.DUES_ON_YOU to "You owe",
    TextKey.DUES_LINE_RECEIVABLE to "Debts owed to you",
    TextKey.DUES_LINE_ROSCA_SAVED to "Saved in ROSCAs",
    TextKey.DUES_LINE_LOANS to "Debts you owe",
    TextKey.DUES_LINE_CUSTODY to "Held in trust",
    TextKey.DUES_LINE_INSTALLMENTS to "Installments left",
    TextKey.DUES_LINE_ROSCA_OWED to "Owed to ROSCAs",
    TextKey.DUES_NO_NETTING to "Each number stands alone — what you owe is never netted against what is owed to you",
    TextKey.DUES_MONTH_LINE to "You pay {0} · you receive {1}",
    TextKey.DUES_LIST_TITLE to "By due date",
    TextKey.DUES_CHIP_LATE to "Late",
    TextKey.DUES_CHIP_SOON to "Soon",
    TextKey.DUES_CHIP_NEXT to "Upcoming",
    TextKey.DUES_DIR_IN to "You receive",
    TextKey.DUES_DIR_OUT to "You pay",
    TextKey.DUES_ROW_YOUR_TURN to "your turn",
    TextKey.DUES_TILE_DEBTS to "Debts",
    TextKey.DUES_TILE_ROSCAS to "ROSCAs",
    TextKey.DUES_TILE_INSTALLMENTS to "Installments",
    TextKey.DUES_TILE_SUBSCRIPTIONS to "Subscriptions",
    TextKey.DUES_FINANCING to "Financing profit this period {0} — for information only; the whole installment counts as spending.",
    TextKey.DUES_EMPTY_TITLE to "Nothing due",
    TextKey.DUES_EMPTY_BODY to "Debts, ROSCAs, installments and subscriptions show up here.",
    TextKey.DUES_SHOW_ALL to "Show all",
    TextKey.DUES_SHOW_LESS to "Show less",
    TextKey.DUES_AGO_ONE to "1 day ago",
    TextKey.DUES_AGO_TWO to "2 days ago",
    TextKey.DUES_AGO_FEW to "{0} days ago",
    TextKey.DUES_AGO_MANY to "{0} days ago",
    TextKey.DUES_DATE_WITH_YEAR to "{0} {1}",
    TextKey.DUES_COMMA to ", ",
    TextKey.DUES_COMMA_JOIN to "{0}, {1}",
    TextKey.DUES_DASH to "—",
    TextKey.DUES_CYCLE_WEEKS to "Every {0} weeks",
    TextKey.DUES_CYCLE_MONTHS to "Every {0} months",
    TextKey.DUES_CYCLE_YEAR to "Every year",
    TextKey.DUES_INST_NONE to "No installments",
    TextKey.DUES_INST_ONE to "1 installment",
    TextKey.DUES_INST_TWO to "2 installments",
    TextKey.DUES_INST_FEW to "{0} installments",
    TextKey.DUES_INST_MANY to "{0} installments",
    TextKey.DUES_INTEREST_Q to "Does it carry interest?",
    TextKey.DUES_INTEREST_SAVED to "Your answer is saved",
    TextKey.DUES_INTEREST_UNSET to "Not answered yet",
    TextKey.DUES_YES to "Yes",
    TextKey.DUES_NO to "No",
    TextKey.DUES_CANCEL to "Cancel",
    TextKey.DUES_ERR_FORMAT to "Type the amount in digits, like 1200.50",
    TextKey.DUES_ERR_POSITIVE to "Type an amount above zero.",
    TextKey.DUES_SAVE_FAILED to "Could not save — try again.",
    TextKey.DUES_UNLINK_BODY to "The transaction goes back to «unclassified» and shows up in review.",
    TextKey.DUES_UNLINK_YES to "Unlink",
    TextKey.DUES_UNLINKED to "Unlinked — the transaction is in review",

    // ── Debts
    TextKey.DEBTS_TITLE to "Debts",
    TextKey.DEBTS_SUB to "With people, owed to you and by you, each on its own",
    TextKey.DEBTS_FOR_YOU_HINT to "Debts people owe you",
    TextKey.DEBTS_ON_YOU_HINT to "Debts you owe people",
    TextKey.DEBTS_NOBODY to "Nobody",
    TextKey.DEBTS_AT_ONE to "With 1 person",
    TextKey.DEBTS_AT_TWO to "With 2 people",
    TextKey.DEBTS_AT_FEW to "With {0} people",
    TextKey.DEBTS_AT_MANY to "With {0} people",
    TextKey.DEBTS_TO_ONE to "To 1 person",
    TextKey.DEBTS_TO_TWO to "To 2 people",
    TextKey.DEBTS_TO_FEW to "To {0} people",
    TextKey.DEBTS_TO_MANY to "To {0} people",
    TextKey.DEBTS_SEARCH_HINT to "Search by name",
    TextKey.DEBTS_SEARCH_CLEAR to "Clear search",
    TextKey.DEBTS_ORDER_FOR_YOU to "Most urgent first: overdue, then the nearest due date",
    TextKey.DEBTS_ORDER_ON_YOU to "By due date",
    TextKey.DEBTS_CUSTODY_TITLE to "Held in trust",
    TextKey.DEBTS_ORDER_CUSTODY to "Kept apart from debts, by due date",
    TextKey.DEBTS_REASON_RECEIVABLE to "Owed to you from a transaction",
    TextKey.DEBTS_REASON_LOAN to "You owe from a transaction",
    TextKey.DEBTS_REASON_OPENING to "Old debt from before the app",
    TextKey.DEBTS_REASON_CUSTODY to "Held in trust",
    TextKey.DEBTS_DUE_ON to "Due {0}",
    TextKey.DEBTS_NO_DUE to "No due date",
    TextKey.DEBTS_SIG_OVERDUE to "Overdue, {0}",
    TextKey.DEBTS_SIG_SOON to "Due soon: {0}",
    TextKey.DEBTS_ARIA_FOR to "{0}, owes you {1}",
    TextKey.DEBTS_ARIA_ON to "{0}, you owe {1}",
    TextKey.DEBTS_EMPTY_TITLE to "No debts with anyone",
    TextKey.DEBTS_EMPTY_BODY to "When you split a bill or record a loan to someone, it shows up here.",
    TextKey.DEBTS_EMPTY_GO to "Open People",
    TextKey.DEBTS_NO_HITS_NAME to "Nobody named «{0}»",
    TextKey.DEBTS_NO_HITS to "Nothing here",
    TextKey.DEBTS_NO_HITS_IN_SIDE to "Searching in «{0}» only.",
    TextKey.DEBTS_NO_HITS_TRY to "Try part of the name.",
    TextKey.DEBTS_FOOT to "Tap a debt to see where it came from and record a payment.",

    // ── Debt detail
    TextKey.DEBT_TITLE to "Debt details",
    TextKey.DEBT_REMAIN_FOR to "Still owed to you",
    TextKey.DEBT_REMAIN_ON to "You still owe",
    TextKey.DEBT_OF_ORIGINAL to "Out of {0}",
    TextKey.DEBT_OF_ORIGINAL_NONE to "Out of {0}, nothing paid yet",
    TextKey.DEBT_DONE to "Fully paid ✓",
    TextKey.DEBT_NOT_OPEN to "This debt does not exist or is fully paid.",
    TextKey.DEBT_ORIGIN_TITLE to "Where it came from",
    TextKey.DEBT_ORIGIN_LABEL to "Source",
    TextKey.DEBT_ORIGIN_TXN to "A recorded transaction",
    TextKey.DEBT_ORIGIN_BEFORE_APP to "From before the app",
    TextKey.DEBT_ORIGIN_OLD_CHIP to "Old debt",
    TextKey.DEBT_ORIGIN_OLD_HINT to "No transaction — not spending, not income, not cash",
    TextKey.DEBT_ORIGINAL to "Original amount",
    TextKey.DEBT_TYPE to "Type",
    TextKey.DEBT_TYPE_RECEIVABLE to "Owed to you",
    TextKey.DEBT_TYPE_LOAN to "A loan you owe",
    TextKey.DEBT_TYPE_OLD_ON_YOU to "Old debt you owe",
    TextKey.DEBT_TYPE_CUSTODY to "Held in trust",
    TextKey.DEBT_TYPE_HINT to "Separate from trust money — and never netted against «{0}»",
    TextKey.DEBT_TERMS_TITLE to "Due date",
    TextKey.DEBT_TERMS_ONE_PAYMENT to "{0}, one payment",
    TextKey.DEBT_TERMS_SET to "Set a due date",
    TextKey.DEBT_TERMS_CHANGE to "Change",
    TextKey.DEBT_TERMS_REMOVE to "Remove",
    TextKey.DEBT_TERMS_PICK to "One payment of the full remainder on:",
    TextKey.DEBT_TERMS_SAVED to "Due {0} — it shows up in Dues",
    TextKey.DEBT_TERMS_REMOVED to "Due date removed — the debt stays as it is",
    TextKey.DEBT_INTEREST_SAVED to "Your answer is saved",

    // ── Settle sheet
    TextKey.SETTLE_SHEET_TITLE_GENERIC to "Settle the debt",
    TextKey.SETTLE_TRIGGER_FOR to "Record a collection",
    TextKey.SETTLE_TRIGGER_ON to "Record a payment",
    TextKey.SETTLE_DONE_WHY to "This debt is fully paid.",
    TextKey.SETTLE_TITLE_FOR to "Collect from {0}",
    TextKey.SETTLE_TITLE_ON to "Pay {0}",
    TextKey.SETTLE_REMAINING to "{0} left",
    TextKey.SETTLE_HOW_FREE to "No transaction",
    TextKey.SETTLE_HOW_LINK to "Existing transaction",
    TextKey.SETTLE_NO_CAND to "No transaction waiting to be linked",
    TextKey.SETTLE_NO_CAND_SUB to "When a transfer from or to {0} arrives, we will ask you about it.",
    TextKey.SETTLE_AMOUNT to "Amount",
    TextKey.SETTLE_FILL to "The full {0}",
    TextKey.SETTLE_ERR_OVER to "It cannot be more than what is left ({0}).",
    TextKey.SETTLE_SAVE_FOR to "Record the collection",
    TextKey.SETTLE_SAVE_ON to "Record the payment",
    TextKey.SETTLE_SAVE_FOR_AMOUNT to "Record the collection · {0}",
    TextKey.SETTLE_SAVE_ON_AMOUNT to "Record the payment · {0}",
    TextKey.SETTLE_SAVED_FULL to "The debt is fully paid",
    TextKey.SETTLE_SAVED_FOR to "Collection from {0} recorded",
    TextKey.SETTLE_SAVED_ON to "Payment to {0} recorded",

    // ── Old debt (opening debt)
    TextKey.OPENING_DEBT_CARD_TITLE to "An old debt with {0} from before the app?",
    TextKey.OPENING_DEBT_CARD_BODY to "No transaction, and it touches no wallet.",
    TextKey.OPENING_DEBT_OPEN to "Record it",
    TextKey.OPENING_DEBT_TITLE to "Old debt with {0}",
    TextKey.OPENING_DEBT_BODY to "For cash you exchanged before the app, with no record. It is not spending, income or cash balance, and it is paid off like any debt.",
    TextKey.OPENING_DEBT_FOR to "They owe me",
    TextKey.OPENING_DEBT_ON to "I owe them",
    TextKey.OPENING_DEBT_SAVE to "Save the debt",
    TextKey.OPENING_DEBT_SAVED to "Old debt recorded — this is its page",
    TextKey.OPENING_ERR_SIDE to "Choose: they owe you, or you owe them.",
    TextKey.OPENING_ERR_CURRENCY to "Old debts in a currency other than riyals are not available yet.",
)
