package app.masroufy.core

/**
 * «مصادر الدخل» و«تفاصيل المصدر» (`IncomeSources` · `IncomeSourceDetail`) — منطقة «المزيد». من النموذج بالحرف، إلا:
 * - «٣ أكتوبر، من …» بفاصلة بدل «·» جنب الرقم (KOTLIN-MAP §٣)، و«النوع، الموعد» كذلك.
 * - الجهة المحوِّلة «معروفة» من غير اسمها (المحفوظ مفتاح مطابقة مش اسم).
 * - سطر «غير متاح بعد» للعمليات المنسوبة (مالهاش حالة استخدام) — كتابة Claude.
 */
internal val MSA_MORE_INCOME_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INCSRC_TITLE to "مصادر الدخل",
    TextKey.INCSRC_INTRO to "سجّل أين تعمل ومتى بدأت. لا يستنتج التطبيق شيئًا من تغيّر المبلغ — بل يسأل.",
    TextKey.INCSRC_KIND_JOB to "وظيفة",
    TextKey.INCSRC_KIND_PART_TIME to "دوام جزئي",
    TextKey.INCSRC_KIND_CLIENT to "عميل",
    TextKey.INCSRC_KIND_RENT to "إيجار",
    TextKey.INCSRC_KIND_INVESTMENT to "استثمار",
    TextKey.INCSRC_KIND_PENSION to "معاش",
    TextKey.INCSRC_KIND_OTHER to "أخرى",
    TextKey.INCSRC_META to "{0}، {1}",
    TextKey.INCSRC_PAY_WEEKLY to "كل {0}",
    TextKey.INCSRC_PAY_WEEKLY_UNSET to "كل أسبوع",
    TextKey.INCSRC_PAY_MONTHLY to "يوم {0} شهريًا",
    TextKey.INCSRC_PAY_UNSET to "الموعد غير محدد",
    TextKey.INCSRC_PAY_NONE to "بلا موعد ثابت",
    TextKey.INCSRC_PERIOD_RANGE to "{0} – {1}",
    TextKey.INCSRC_PERIOD_SINCE to "منذ {0}",
    TextKey.INCSRC_CURRENT to "الحالية ({0})",
    TextKey.INCSRC_PAST to "السابقة ({0})",
    TextKey.INCSRC_EXPECTED to "المتوقع",
    TextKey.INCSRC_EMPTY_TITLE to "لا مصادر دخل بعد",
    TextKey.INCSRC_EMPTY_BODY to "أضف عملك الحالي ليعرف التطبيق متى ينزل راتبك.",
    TextKey.INCSRC_CHANGE to "غيّرت عملي",
    TextKey.INCSRC_ADD to "أضف مصدر دخل",
    TextKey.INCSRC_PAYER_Q to "هل هذا راتب من «{0}»؟",
    TextKey.INCSRC_PAYER_FROM to "{0}، من «{1}»",
    TextKey.INCSRC_PAYER_FROM_LAST4 to "{0}، من «{1}» حساب ينتهي بـ {2}",
    TextKey.INCSRC_PAYER_YES_DONE to "تم — أي تحويل منها يُسجَّل راتبًا تلقائيًا",
    TextKey.INCSRC_PAYER_NO_DONE to "لن نسأل عنها مجددًا لهذا المصدر",
    TextKey.INCSRC_DETAIL_TITLE to "تفاصيل المصدر",
    TextKey.INCSRC_GONE to "هذا المصدر لم يعد موجودًا.",
    TextKey.INCSRC_ONGOING to "مستمر",
    TextKey.INCSRC_ENDED to "انتهى",
    TextKey.INCSRC_IN_SAR to "بالريال",
    TextKey.INCSRC_IN_EGP to "بالجنيه",
    TextKey.INCSRC_PAY_DAY to "موعد القبض",
    TextKey.INCSRC_EXPECTED_NONE to "لم تكتبه (اختياري)",
    TextKey.INCSRC_PAYER to "الجهة المحوِّلة",
    TextKey.INCSRC_PAYER_KNOWN to "معروفة — تُنسب إيداعاتها تلقائيًا",
    TextKey.INCSRC_PAYER_UNKNOWN to "لم تُعرف بعد",
    TextKey.INCSRC_PAYER_NOT_ASKED to "لا نسأل عنها لهذا النوع",
    TextKey.INCSRC_TX_TITLE to "العمليات المنسوبة إليه",
    TextKey.INCSRC_TX_NOT_YET to "عرض العمليات المنسوبة غير متاح بعد في هذه النسخة.",
    TextKey.INCSRC_CMP_TITLE to "قبل البداية وبعدها",
    TextKey.INCSRC_CMP_PARTIAL to "الأرقام ناقصة",
    TextKey.INCSRC_CMP_PARTIAL_NOTE to "بعض عمليات الأشهر الستة نوعها غير محدد بعد.",
    TextKey.INCSRC_CMP_NA to "تظهر بعد انتهاء ٣ أشهر مالية كاملة من البداية، ولا تظهر إن خلا شهر من الستة من أي عملية.",
    TextKey.INCSRC_CMP_NO_PCT to "لا دخل قبلها، فلا نسبة.",
    TextKey.INCSRC_CMP_NOTE to "بعملة المصدر، بلا النقوط ومكافأة نهاية الخدمة. الشهر الذي بدأ في منتصفه خارج المقارنة.",
    TextKey.INCSRC_CMP_INCOME to "الدخل",
    TextKey.INCSRC_CMP_EXPENSE to "المصروف",
    TextKey.INCSRC_CMP_BEFORE to "متوسط ٣ أشهر قبل",
    TextKey.INCSRC_CMP_AFTER to "متوسط ٣ أشهر بعد",
    TextKey.INCSRC_DECIMAL_SEP to "٫",
    TextKey.INCSRC_EDIT to "تعديل",
    TextKey.INCSRC_CLOSE to "إنهاء المصدر",
)

internal val EGYPTIAN_MORE_INCOME_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INCSRC_TITLE to "مصادر الدخل",
    TextKey.INCSRC_INTRO to "قول بتشتغل فين ومن إمتى. البرنامج ما بيستنتجش حاجة من تغيّر المبلغ — بيسأل.",
    TextKey.INCSRC_KIND_JOB to "وظيفة",
    TextKey.INCSRC_KIND_PART_TIME to "بارت تايم",
    TextKey.INCSRC_KIND_CLIENT to "عميل",
    TextKey.INCSRC_KIND_RENT to "إيجار",
    TextKey.INCSRC_KIND_INVESTMENT to "استثمار",
    TextKey.INCSRC_KIND_PENSION to "معاش",
    TextKey.INCSRC_KIND_OTHER to "غيره",
    TextKey.INCSRC_META to "{0}، {1}",
    TextKey.INCSRC_PAY_WEEKLY to "كل {0}",
    TextKey.INCSRC_PAY_WEEKLY_UNSET to "كل أسبوع",
    TextKey.INCSRC_PAY_MONTHLY to "يوم {0} كل شهر",
    TextKey.INCSRC_PAY_UNSET to "الميعاد مش محدد",
    TextKey.INCSRC_PAY_NONE to "من غير ميعاد ثابت",
    TextKey.INCSRC_PERIOD_RANGE to "{0} – {1}",
    TextKey.INCSRC_PERIOD_SINCE to "من {0}",
    TextKey.INCSRC_CURRENT to "الشغالة ({0})",
    TextKey.INCSRC_PAST to "اللي فاتت ({0})",
    TextKey.INCSRC_EXPECTED to "المتوقع",
    TextKey.INCSRC_EMPTY_TITLE to "مفيش مصادر دخل لسه",
    TextKey.INCSRC_EMPTY_BODY to "ضيف شغلك الحالي عشان نعرف المرتب بينزل إمتى.",
    TextKey.INCSRC_CHANGE to "غيّرت شغلي",
    TextKey.INCSRC_ADD to "ضيف مصدر دخل",
    TextKey.INCSRC_PAYER_Q to "ده مرتب من «{0}»؟",
    TextKey.INCSRC_PAYER_FROM to "{0}، من «{1}»",
    TextKey.INCSRC_PAYER_FROM_LAST4 to "{0}، من «{1}» حساب آخره {2}",
    TextKey.INCSRC_PAYER_YES_DONE to "تمام — أي تحويل منها هيتسجل مرتب لوحده",
    TextKey.INCSRC_PAYER_NO_DONE to "مش هنسأل عنها تاني للمصدر ده",
    TextKey.INCSRC_DETAIL_TITLE to "تفاصيل المصدر",
    TextKey.INCSRC_GONE to "المصدر ده مش موجود.",
    TextKey.INCSRC_ONGOING to "شغال",
    TextKey.INCSRC_ENDED to "خلص",
    TextKey.INCSRC_IN_SAR to "بالريال",
    TextKey.INCSRC_IN_EGP to "بالجنيه",
    TextKey.INCSRC_PAY_DAY to "ميعاد القبض",
    TextKey.INCSRC_EXPECTED_NONE to "ما كتبتوش (اختياري)",
    TextKey.INCSRC_PAYER to "اللي بيحوّل",
    TextKey.INCSRC_PAYER_KNOWN to "معروفة — إيداعاتها بتتنسب لوحدها",
    TextKey.INCSRC_PAYER_UNKNOWN to "لسه ما اتعرفش",
    TextKey.INCSRC_PAYER_NOT_ASKED to "مش بنسأل عنها للنوع ده",
    TextKey.INCSRC_TX_TITLE to "العمليات المنسوبة له",
    TextKey.INCSRC_TX_NOT_YET to "عرض العمليات المنسوبة لسه مش متاح في النسخة دي.",
    TextKey.INCSRC_CMP_TITLE to "قبل وبعد البداية",
    TextKey.INCSRC_CMP_PARTIAL to "الأرقام ناقصة",
    TextKey.INCSRC_CMP_PARTIAL_NOTE to "فيه عمليات في الشهور الستة نوعها لسه ما اتحددش.",
    TextKey.INCSRC_CMP_NA to "بتظهر بعد ما تخلص ٣ شهور مالية كاملة من البداية، ومش بتظهر لو فيه شهر من الستة مفيهوش ولا عملية.",
    TextKey.INCSRC_CMP_NO_PCT to "مفيش دخل قبلها، فمفيش نسبة.",
    TextKey.INCSRC_CMP_NOTE to "بعملة المصدر، من غير النقوط ومكافأة نهاية الخدمة. الشهر اللي بدأ في نصه برا المقارنة.",
    TextKey.INCSRC_CMP_INCOME to "الدخل",
    TextKey.INCSRC_CMP_EXPENSE to "المصروف",
    TextKey.INCSRC_CMP_BEFORE to "متوسط ٣ شهور قبل",
    TextKey.INCSRC_CMP_AFTER to "متوسط ٣ شهور بعد",
    TextKey.INCSRC_DECIMAL_SEP to "٫",
    TextKey.INCSRC_EDIT to "تعديل",
    TextKey.INCSRC_CLOSE to "المصدر ده خلص",
)

internal val ENGLISH_MORE_INCOME_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INCSRC_TITLE to "Income sources",
    TextKey.INCSRC_INTRO to "Record where you work and when you started. The app infers nothing from a change in the amount — it asks.",
    TextKey.INCSRC_KIND_JOB to "Job",
    TextKey.INCSRC_KIND_PART_TIME to "Part-time",
    TextKey.INCSRC_KIND_CLIENT to "Client",
    TextKey.INCSRC_KIND_RENT to "Rent",
    TextKey.INCSRC_KIND_INVESTMENT to "Investment",
    TextKey.INCSRC_KIND_PENSION to "Pension",
    TextKey.INCSRC_KIND_OTHER to "Other",
    TextKey.INCSRC_META to "{0} · {1}",
    TextKey.INCSRC_PAY_WEEKLY to "Every {0}",
    TextKey.INCSRC_PAY_WEEKLY_UNSET to "Weekly",
    TextKey.INCSRC_PAY_MONTHLY to "Day {0} monthly",
    TextKey.INCSRC_PAY_UNSET to "Pay day not set",
    TextKey.INCSRC_PAY_NONE to "No fixed date",
    TextKey.INCSRC_PERIOD_RANGE to "{0} – {1}",
    TextKey.INCSRC_PERIOD_SINCE to "Since {0}",
    TextKey.INCSRC_CURRENT to "Current ({0})",
    TextKey.INCSRC_PAST to "Past ({0})",
    TextKey.INCSRC_EXPECTED to "Expected",
    TextKey.INCSRC_EMPTY_TITLE to "No income sources yet",
    TextKey.INCSRC_EMPTY_BODY to "Add your current job so the app knows when your salary arrives.",
    TextKey.INCSRC_CHANGE to "I changed jobs",
    TextKey.INCSRC_ADD to "Add an income source",
    TextKey.INCSRC_PAYER_Q to "Is this salary from “{0}”?",
    TextKey.INCSRC_PAYER_FROM to "{0}, from “{1}”",
    TextKey.INCSRC_PAYER_FROM_LAST4 to "{0}, from “{1}”, account ending {2}",
    TextKey.INCSRC_PAYER_YES_DONE to "Done — any transfer from them is recorded as salary automatically",
    TextKey.INCSRC_PAYER_NO_DONE to "We won't ask about them again for this source",
    TextKey.INCSRC_DETAIL_TITLE to "Source details",
    TextKey.INCSRC_GONE to "This source no longer exists.",
    TextKey.INCSRC_ONGOING to "Ongoing",
    TextKey.INCSRC_ENDED to "Ended",
    TextKey.INCSRC_IN_SAR to "in SAR",
    TextKey.INCSRC_IN_EGP to "in EGP",
    TextKey.INCSRC_PAY_DAY to "Pay day",
    TextKey.INCSRC_EXPECTED_NONE to "Not written (optional)",
    TextKey.INCSRC_PAYER to "Who pays it",
    TextKey.INCSRC_PAYER_KNOWN to "Known — their deposits are linked automatically",
    TextKey.INCSRC_PAYER_UNKNOWN to "Not known yet",
    TextKey.INCSRC_PAYER_NOT_ASKED to "We don't ask for this type",
    TextKey.INCSRC_TX_TITLE to "Transactions linked to it",
    TextKey.INCSRC_TX_NOT_YET to "Showing linked transactions isn't available in this version yet.",
    TextKey.INCSRC_CMP_TITLE to "Before and after the start",
    TextKey.INCSRC_CMP_PARTIAL to "Figures incomplete",
    TextKey.INCSRC_CMP_PARTIAL_NOTE to "Some transactions in the six months don't have a type yet.",
    TextKey.INCSRC_CMP_NA to "Shows after 3 full financial months from the start, and not if any of the six months has no transactions.",
    TextKey.INCSRC_CMP_NO_PCT to "No income before it, so no percentage.",
    TextKey.INCSRC_CMP_NOTE to "In the source's currency, without gifts or end-of-service pay. The month it started mid-way is left out.",
    TextKey.INCSRC_CMP_INCOME to "Income",
    TextKey.INCSRC_CMP_EXPENSE to "Spending",
    TextKey.INCSRC_CMP_BEFORE to "3-month average before",
    TextKey.INCSRC_CMP_AFTER to "3-month average after",
    TextKey.INCSRC_DECIMAL_SEP to ".",
    TextKey.INCSRC_EDIT to "Edit",
    TextKey.INCSRC_CLOSE to "End this source",
)
