package app.masroufy.core

/**
 * نصوص الواجهة المشتركة (الهيكل · شريطي التنقل والسؤال · لوحة الإضافة · الجرس · البلد · «معك الآن» · «القادم» · التقويم · الدخول · القفل ·
 * التواريخ) — **بالفصحى المختصرة** للسعودية والافتراضي (OVERRIDES §66). منقولة من نصوص النموذج التفاعلي (`design-source/prototype` على
 * فرع التصميم) بالحرف، إلا المكتوب جنبه. المصري في `TextsShellEgyptian.kt` والإنجليزي في `TextsShellEnglish.kt` (كتابة Claude — مستني
 * مراجعة المالك §40). **ممنوع «·» جنب رقم عربي** (KOTLIN-MAP §3) ⇒ «،».
 */
internal val MSA_SHELL_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.TAB_HOME to "الرئيسية",
    UiKey.TAB_OPERATIONS to "العمليات",
    UiKey.TAB_PEOPLE to "الأشخاص",
    UiKey.TAB_INVESTMENT to "الاستثمار",
    UiKey.SHELL_NAV to "التنقل",
    UiKey.SHELL_GEAR to "المزيد والإعدادات",
    UiKey.SHELL_BACK to "رجوع",
    UiKey.SHELL_CLOSE to "إغلاق",
    UiKey.SHELL_NEW_DOT to "يوجد جديد",
    UiKey.SHELL_TAB_WITH_NEW to "{0} — يوجد جديد",
    UiKey.SHELL_OFFLINE to "لا اتصال بالإنترنت — المعروض محفوظ على جهازك وقد لا يكون الأحدث.",
    UiKey.SHELL_OPENING to "نجهّز بياناتك…",
    UiKey.SHELL_OPENING_PROGRESS to "{0} من {1}",
    UiKey.SHELL_PENDING_SCREEN to "هذه الشاشة قيد البناء.",
    UiKey.SHELL_LOADING to "جارٍ التحميل",
    UiKey.SHELL_RETRY to "أعد المحاولة",
    UiKey.SHELL_LOAD_FAILED to "تعذّر التحميل.",
    UiKey.BADGE_APPROX to "تقريبي",
    UiKey.GREETING_MORNING_NAME to "صباح الخير، {0}",
    UiKey.GREETING_EVENING_NAME to "مساء الخير، {0}",
    UiKey.GREETING_MORNING to "صباح الخير",
    UiKey.GREETING_EVENING to "مساء الخير",
    UiKey.ME_PROFILE to "ملفك",
    UiKey.ME_PROFILE_PERCENT to "ملفك — مكتمل {0}%",
    UiKey.WEEKDAY_MON to "الإثنين",
    UiKey.WEEKDAY_TUE to "الثلاثاء",
    UiKey.WEEKDAY_WED to "الأربعاء",
    UiKey.WEEKDAY_THU to "الخميس",
    UiKey.WEEKDAY_FRI to "الجمعة",
    UiKey.WEEKDAY_SAT to "السبت",
    UiKey.WEEKDAY_SUN to "الأحد",
    UiKey.WEEKDAY_SHORT_MON to "اثنين",
    UiKey.WEEKDAY_SHORT_TUE to "ثلاثاء",
    UiKey.WEEKDAY_SHORT_WED to "أربعاء",
    UiKey.WEEKDAY_SHORT_THU to "خميس",
    UiKey.WEEKDAY_SHORT_FRI to "جمعة",
    UiKey.WEEKDAY_SHORT_SAT to "سبت",
    UiKey.WEEKDAY_SHORT_SUN to "أحد",
    UiKey.MONTH_1 to "يناير",
    UiKey.MONTH_2 to "فبراير",
    UiKey.MONTH_3 to "مارس",
    UiKey.MONTH_4 to "أبريل",
    UiKey.MONTH_5 to "مايو",
    UiKey.MONTH_6 to "يونيو",
    UiKey.MONTH_7 to "يوليو",
    UiKey.MONTH_8 to "أغسطس",
    UiKey.MONTH_9 to "سبتمبر",
    UiKey.MONTH_10 to "أكتوبر",
    UiKey.MONTH_11 to "نوفمبر",
    UiKey.MONTH_12 to "ديسمبر",
    UiKey.DATE_DAY_MONTH to "{0} {1}",
    UiKey.DATE_WEEKDAY_DAY_MONTH to "{0}، {1}",
    UiKey.DATE_MONTH_YEAR to "{0} {1}",
    UiKey.ASK_BAR to "اسأل مصروفي أو اطلب منه أي شيء…",
    UiKey.ASK_MIC to "أضف بالصوت",
    // اسم المساعد = «مصروفي» ولقبه «مساعدك المالي الذكي» (اختيار المالك — آخر §76)
    UiKey.ASK_TITLE to "مصروفي",
    UiKey.ASK_BRAND_TITLE to "مساعدك المالي الذكي",
    UiKey.ASK_DIALOG to "محادثة مع {0}",
    UiKey.ASK_HISTORY to "سجل المحادثات",
    UiKey.ASK_NEW to "محادثة جديدة",
    UiKey.ASK_NEW_STARTED to "بدأت محادثة جديدة — السابقة في السجل",
    UiKey.ASK_INTRO to "أنا {0}، {1}. اسألني عن مالك، أو اطلب مني تسجيل مصروف أو تقسيم فاتورة.",
    UiKey.ASK_TODO_TITLE to "أمور لم تُنجزها بعد",
    // اختيار Claude: القايمة دي مالهاش حالة استخدام في كوتلن لسه (آخر §76) ⇒ بتقول كده بدل كروت بأرقام مخترعة
    UiKey.ASK_TODO_NOT_READY to "غير متاح بعد — هذه القائمة لم تُربط ببياناتك في هذه النسخة.",
    UiKey.ASK_TODO_BASIS to "من رسائل البنك والفواتير الدورية والميزانيات والديون.",
    UiKey.ASK_INPUT_HINT to "اكتب سؤالك أو اطلب أي شيء…",
    UiKey.ASK_INPUT_LABEL to "رسالتك إلى {0}",
    UiKey.ASK_SEND to "أرسل",
    UiKey.ASK_TALK to "تكلّم",
    UiKey.ASK_CLOSE to "إغلاق المحادثة",
    UiKey.ASK_CHIPS_FOR to "اقتراحات لصفحة «{0}»",
    // اختيار Claude: النموذج بيرد بإجابات جاهزة؛ التطبيق ما عندوش مساعد (باقة Spark ومفيش مزوّد معتمد — OVERRIDES §73) ⇒ بيقول كده بصراحة
    UiKey.ASK_NOT_READY to "المساعد غير متاح بعد — يحتاج خدمة ذكاء اصطناعي لم يُعتمد مزوّدها. يمكنك تصفّح بياناتك من التبويبات.",
    UiKey.ASK_VOICE_NOT_READY to "الإضافة بالصوت غير متاحة بعد.",
    UiKey.ASK_CHIP_SPENT to "كم صرفت هذا الشهر؟",
    UiKey.ASK_CHIP_VOICE to "أضف عملية بصوتي",
    UiKey.ASK_CHIP_SPLIT to "قسّم فاتورة مع أصدقائي",
    UiKey.ASK_CHIP_PLAN to "هل أنا على الخطة؟",
    UiKey.ASK_CHIP_OWED to "كم لي عند الناس؟",
    UiKey.ASK_CHIP_LOCK to "أين أغيّر القفل؟",
    UiKey.ASK_TYPING to "مصروفي يكتب",
    UiKey.ASK_LISTENING to "أستمع إليك…",
    UiKey.ASK_HISTORY_CLOSE to "إغلاق السجل",
    UiKey.ASK_HISTORY_SEARCH to "ابحث في محادثاتك",
    UiKey.ASK_HISTORY_TODAY to "اليوم",
    UiKey.ASK_HISTORY_CURRENT to "الحالية",
    UiKey.ASK_HISTORY_EMPTY to "لا توجد محادثات بعد.",
    UiKey.ASK_HISTORY_NO_MATCH to "لا توجد محادثات بهذا البحث.",
    UiKey.ASK_HISTORY_DELETE to "احذف «{0}»",
    UiKey.ASK_HISTORY_DELETED to "حُذفت «{0}»",
    UiKey.ASK_HISTORY_UNDO to "تراجع",
    UiKey.ADD_LABEL to "أضف عملية",
    UiKey.ADD_TITLE to "عملية جديدة",
    UiKey.ADD_VOICE to "بصوتك",
    UiKey.ADD_KIND_TABS to "نوع العملية",
    UiKey.ADD_TYPE_OUT to "صرف",
    UiKey.ADD_TYPE_IN to "دخل",
    UiKey.ADD_TYPE_MOVE to "تحويل",
    UiKey.ADD_AMOUNT to "المبلغ",
    UiKey.ADD_CATEGORY to "التصنيف",
    UiKey.ADD_INCOME_KIND to "النوع",
    UiKey.ADD_FROM to "من أين؟",
    UiKey.ADD_TO to "إلى أين؟",
    UiKey.ADD_SAVE to "احفظ",
    UiKey.ADD_SAVING to "جارٍ الحفظ…",
    UiKey.ADD_SAVED to "سُجّلت: {0}",
    UiKey.ADD_NO_WALLET to "أضف محفظة أولًا من «المزيد ← المحافظ».",
    UiKey.ADD_AMOUNT_INVALID to "اكتب مبلغًا أكبر من صفر.",
    UiKey.BELL_TITLE to "الإشعارات",
    UiKey.BELL_LABEL_NEW to "الإشعارات — يوجد جديد",
    UiKey.BELL_NEW_COUNT to "{0} جديدة",
    UiKey.BELL_ALL_READ to "كلها مقروءة",
    UiKey.BELL_MARK_READ to "تعليم الكل كمقروء",
    UiKey.BELL_ALL to "كل الإشعارات",
    UiKey.BELL_EMPTY to "لا إشعارات الآن.",
    UiKey.BELL_CLOSE to "إغلاق الإشعارات",
    UiKey.SPACE_SWITCH_TITLE to "تبديل البلد",
    UiKey.SPACE_SWITCH_BODY to "لكل بلد حساب منفصل بمحافظه وأرقامه وعملته. التبديل على هذا الجوال فقط، ولا يغيّر شيئًا في بياناتك.",
    UiKey.SPACE_ACTIVE to "الحالية",
    UiKey.SPACE_WITH_YOU to "معك الآن",
    UiKey.SPACE_OPENING to "جارٍ الفتح…",
    UiKey.SPACE_SHARED_NOTE to "مشترك بين البلدان: ملفك ويوم الراتب والأشخاص والتجار والوسوم.",
    UiKey.SPACE_MANAGE to "إدارة البلدان",
    UiKey.SPACE_TRIGGER to "البلد: {0} — اضغط للتبديل",
    UiKey.SPACE_SWITCHED to "انتقلت إلى حساب {0}",
    UiKey.SPACE_SUB to "{0}، {1}",
    UiKey.CURRENCY_NAME_SAR to "ريال سعودي",
    UiKey.CURRENCY_NAME_EGP to "جنيه مصري",
    UiKey.HERO_WITH_YOU to "معك الآن",
    UiKey.HERO_CASH_CHIP to "يشمل {0} كاش",
    UiKey.HERO_BANKS_TITLE to "أين ما معك الآن؟",
    UiKey.HERO_BANKS_LABEL to "البنوك المشمولة في «معك الآن»: {0}",
    UiKey.HERO_BANK_SUB to "حساب بنكي",
    UiKey.HERO_DIGITAL_SUB to "محفظة إلكترونية",
    UiKey.HERO_CASH_SUB to "الذي معك",
    UiKey.HERO_LOGO_NOTE to "يحل شعار كل بنك محل الحرف بعد اعتماد بحث الشعارات.",
    UiKey.HERO_NA_LINE to "رصيد إحدى المحافظ غير متاح بعد — يبدأ من يوم فتحها في التطبيق.",
)
