package app.masroufy.core

/**
 * نصوص الأحداث ومناسبات الشخص (OVERRIDES §44.1 و§64) باللغتين — بيتدمجوا في `ARABIC_TEXTS` و`ENGLISH_TEXTS`.
 * التنبيهات بتاعتهم (`ALERT_*OCCASION*`) في `TextsAlerts.kt` مع باقي نصوص المحرك.
 * الإنجليزي كتابة Claude ومستني مراجعة المالك زي باقي الجدول (§40).
 */
internal val ARABIC_EVENT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.EVENT_KIND_WEDDING to "فرح",
    TextKey.EVENT_KIND_ENGAGEMENT to "خطوبة",
    TextKey.EVENT_KIND_CONDOLENCE to "عزا",
    TextKey.EVENT_KIND_BIRTH to "ولادة",
    TextKey.EVENT_KIND_TRAVEL to "سفر",
    TextKey.EVENT_KIND_MEDICAL to "عملية",
    TextKey.EVENT_KIND_EID to "عيد",
    TextKey.EVENT_KIND_SCHOOL to "دخول مدرسة",
    TextKey.EVENT_KIND_OTHER to "غيره",
    TextKey.EVENT_NAME_LENGTH to "اسم الحدث لازم يبقى من حرف لـ{0} حرف",
    TextKey.EVENT_NAME_DUPLICATE to "فيه حدث بنفس الاسم",
    TextKey.EVENT_NOT_FOUND to "الحدث مش موجود",
    TextKey.EVENT_DATE_INVALID to "تاريخ الحدث مش صالح",
    TextKey.EVENT_HOST_ONLY_OTHERS to "صاحب الحدث بيتحدد لحدث حد تاني بس — ده حدثك إنت",
    TextKey.EVENT_PERSON_NOT_FOUND to "الشخص مش موجود",
    TextKey.EVENT_TXN_NOT_FOUND to "العملية مش موجودة",
    TextKey.EVENT_TXN_ALREADY_LINKED to "العملية دي متربطة بحدث قبل كده — العملية الواحدة بتتربط بحدث واحد بس",
    TextKey.EVENT_TXN_NEEDS_IN to "النقطة اللي جاتلك لازم تبقى عملية داخلة",
    TextKey.EVENT_TXN_NEEDS_OUT to "المصروف والنقطة اللي اديتها لازم يبقوا عملية طالعة",
    TextKey.EVENT_GIFT_NEEDS_PERSON to "النقطة لازم يتحدد معاها الشخص",
    TextKey.EVENT_GIFT_IN_NOT_MINE to "النقوط اللي جاتلك بتتسجل في حدثك إنت بس",
    TextKey.EVENT_TXN_IN_DUES to "العملية دي متربطة بالمستحقات أو بالزكاة — ما ينفعش تبقى نقطة كمان",
    TextKey.EVENT_LINK_NOT_FOUND to "العملية دي مش متربطة بالحدث",
    TextKey.EVENT_GIFTS_EMPTY to "ضيف نقطة واحدة على الأقل بمبلغ أكبر من صفر",
    TextKey.EVENT_GIFT_PERSON_TWICE to "نفس الشخص متكرر — كل نقطة لاسم واحد",
    TextKey.EVENT_BADGE_IN to "نقّطك {0} في «{1}»",
    TextKey.EVENT_BADGE_OUT to "نقّطته {0} في «{1}»",
    TextKey.OCCASION_KIND_BIRTHDAY to "عيد ميلاد",
    TextKey.OCCASION_KIND_WEDDING_ANNIVERSARY to "عيد جواز",
    TextKey.OCCASION_KIND_WEDDING to "فرح",
    TextKey.OCCASION_KIND_OTHER to "مناسبة تانية",
    TextKey.OCCASION_DATE_INVALID to "تاريخ المناسبة مش صالح",
    TextKey.OCCASION_YEAR_REQUIRED to "المناسبة اللي مرة واحدة محتاجة السنة",
    TextKey.OCCASION_LEAD_RANGE to "التذكير يبقى قبلها بيوم لـ{0} يوم",
    TextKey.OCCASION_LABEL_LENGTH to "اسم المناسبة أطول من {0} حرف",
    TextKey.OCCASION_NOT_FOUND to "المناسبة مش موجودة",
    TextKey.OCCASION_EVENT_NOT_MINE to "التذكير السنوي للحدث اللي بتاعك إنت بس",
    TextKey.OCCASION_TITLE_LABEL_OF to "{0} — {1}",
    TextKey.OCCASION_TITLE_FROM_EVENT to "ذكرى «{0}»",
    TextKey.OCCASION_TITLE_BIRTHDAY_OF to "عيد ميلاد {0}",
    TextKey.OCCASION_TITLE_BIRTHDAY_OWN to "عيد ميلادك",
    TextKey.OCCASION_TITLE_ANNIVERSARY_OF to "عيد جواز {0}",
    TextKey.OCCASION_TITLE_ANNIVERSARY_OWN to "عيد جوازك",
    TextKey.OCCASION_TITLE_WEDDING_OF to "فرح {0}",
    TextKey.OCCASION_TITLE_WEDDING_OWN to "فرحك",
    TextKey.OCCASION_TITLE_OTHER_OF to "مناسبة {0}",
    TextKey.OCCASION_TITLE_OTHER_OWN to "مناسبتك",
    TextKey.BACKUP_GROUP_LIFE_EVENTS to "الأحداث",
    TextKey.BACKUP_GROUP_EVENT_LINKS to "روابط الأحداث",
    TextKey.BACKUP_GROUP_OCCASIONS to "المناسبات",
    TextKey.CATEGORY_GIFTS to "هدايا",
    TextKey.CATEGORY_EVENT_GIFTS to "نقوط",
    TextKey.EVENT_SHARE_RANGE to "نسبة الحدث من العملية لازم تبقى من 1 لـ100",
    TextKey.EVENT_GIFT_SHARE_WHOLE to "النقطة بتتربط بالعملية كلها — النسبة للمصروف بس",
)

internal val ENGLISH_EVENT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.EVENT_KIND_WEDDING to "Wedding",
    TextKey.EVENT_KIND_ENGAGEMENT to "Engagement",
    TextKey.EVENT_KIND_CONDOLENCE to "Condolence",
    TextKey.EVENT_KIND_BIRTH to "Birth",
    TextKey.EVENT_KIND_TRAVEL to "Travel",
    TextKey.EVENT_KIND_MEDICAL to "Surgery",
    TextKey.EVENT_KIND_EID to "Eid",
    TextKey.EVENT_KIND_SCHOOL to "Starting school",
    TextKey.EVENT_KIND_OTHER to "Other",
    TextKey.EVENT_NAME_LENGTH to "The event name must be 1 to {0} characters",
    TextKey.EVENT_NAME_DUPLICATE to "An event with this name already exists",
    TextKey.EVENT_NOT_FOUND to "Event not found",
    TextKey.EVENT_DATE_INVALID to "The event date is not valid",
    TextKey.EVENT_HOST_ONLY_OTHERS to "The host is set only for someone else's event — this one is yours",
    TextKey.EVENT_PERSON_NOT_FOUND to "Person not found",
    TextKey.EVENT_TXN_NOT_FOUND to "Transaction not found",
    TextKey.EVENT_TXN_ALREADY_LINKED to "This transaction is already linked to an event — one transaction, one event",
    TextKey.EVENT_TXN_NEEDS_IN to "A gift you received must be an incoming transaction",
    TextKey.EVENT_TXN_NEEDS_OUT to "Spending and gifts you gave must be outgoing transactions",
    TextKey.EVENT_GIFT_NEEDS_PERSON to "A gift needs a person",
    TextKey.EVENT_GIFT_IN_NOT_MINE to "Gifts you received are recorded on your own events only",
    TextKey.EVENT_TXN_IN_DUES to "This transaction is linked to dues or zakat — it cannot be a gift too",
    TextKey.EVENT_LINK_NOT_FOUND to "This transaction is not linked to the event",
    TextKey.EVENT_GIFTS_EMPTY to "Add at least one gift with an amount above zero",
    TextKey.EVENT_GIFT_PERSON_TWICE to "The same person is listed twice — one gift per name",
    TextKey.EVENT_BADGE_IN to "Gave you {0} at “{1}”",
    TextKey.EVENT_BADGE_OUT to "You gave {0} at “{1}”",
    TextKey.OCCASION_KIND_BIRTHDAY to "Birthday",
    TextKey.OCCASION_KIND_WEDDING_ANNIVERSARY to "Wedding anniversary",
    TextKey.OCCASION_KIND_WEDDING to "Wedding",
    TextKey.OCCASION_KIND_OTHER to "Other occasion",
    TextKey.OCCASION_DATE_INVALID to "The occasion date is not valid",
    TextKey.OCCASION_YEAR_REQUIRED to "A one-time occasion needs the year",
    TextKey.OCCASION_LEAD_RANGE to "The reminder can be 1 to {0} days before",
    TextKey.OCCASION_LABEL_LENGTH to "The occasion name is longer than {0} characters",
    TextKey.OCCASION_NOT_FOUND to "Occasion not found",
    TextKey.OCCASION_EVENT_NOT_MINE to "A yearly reminder is only for your own event",
    TextKey.OCCASION_TITLE_LABEL_OF to "{0} — {1}",
    TextKey.OCCASION_TITLE_FROM_EVENT to "Anniversary of “{0}”",
    TextKey.OCCASION_TITLE_BIRTHDAY_OF to "{0}'s birthday",
    TextKey.OCCASION_TITLE_BIRTHDAY_OWN to "Your birthday",
    TextKey.OCCASION_TITLE_ANNIVERSARY_OF to "{0}'s wedding anniversary",
    TextKey.OCCASION_TITLE_ANNIVERSARY_OWN to "Your wedding anniversary",
    TextKey.OCCASION_TITLE_WEDDING_OF to "{0}'s wedding",
    TextKey.OCCASION_TITLE_WEDDING_OWN to "Your wedding",
    TextKey.OCCASION_TITLE_OTHER_OF to "{0}'s occasion",
    TextKey.OCCASION_TITLE_OTHER_OWN to "Your occasion",
    TextKey.BACKUP_GROUP_LIFE_EVENTS to "Events",
    TextKey.BACKUP_GROUP_EVENT_LINKS to "Event links",
    TextKey.BACKUP_GROUP_OCCASIONS to "Occasions",
    TextKey.CATEGORY_GIFTS to "Gifts",
    TextKey.CATEGORY_EVENT_GIFTS to "Event gifts",
    TextKey.EVENT_SHARE_RANGE to "The event share of a transaction must be 1 to 100 percent",
    TextKey.EVENT_GIFT_SHARE_WHOLE to "A gift is linked as the whole transaction — the percentage is for spending only",
)
