package app.masroufy.core

/**
 * إجابات المساعد «مصروفي» (§78): الناس والديون · الراتب · المحلات · الخطط والزكاة · المستحقات والفواتير · الأصول والأحداث والجمعيات.
 * **مفيش «ذكّره»** في أي نص (رد المالك ٣ — الدين المتأخر معلومة بس).
 */
internal val MSA_ASSIST_ANSWER2_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_OWED_TO_ME to "لك عند الناس {0} — منهم: {1}.",
    TextKey.ASSIST_OWED_NONE to "لا أحد مدين لك بشيء.",
    TextKey.ASSIST_I_OWE to "عليك للناس {0} — منهم: {1}.",
    TextKey.ASSIST_I_OWE_NONE to "لست مدينًا لأحد.",
    TextKey.ASSIST_PERSON_OWES_ME to "لك عند {0} {1}.",
    TextKey.ASSIST_I_OWE_PERSON to "عليك لـ{0} {1}.",
    TextKey.ASSIST_CUSTODY to "وعندك أمانة لـ{0} {1}.",
    TextKey.ASSIST_PERSON_NONE to "لا ديون بينك وبين {0}.",
    TextKey.ASSIST_OVERDUE to "متأخرون في السداد: {0}.",
    TextKey.ASSIST_OVERDUE_ITEM to "{0} ({1}) منذ {2}",
    TextKey.ASSIST_OVERDUE_NONE to "لا أحد متأخر في السداد.",
    TextKey.ASSIST_NEXT_SALARY to "الراتب يوم {0} — بعد {1}.",
    TextKey.ASSIST_SALARY_TODAY to "الراتب اليوم.",
    TextKey.ASSIST_SALARY_DAY_NA to "موعد الراتب غير متاح: لم يُحدَّد يومه.",
    TextKey.ASSIST_NO_SALARY to "لا يوجد راتب نشط في {0} الآن.",
    TextKey.ASSIST_SPACE_INCOME to "دخل {0}: {1}.",
    TextKey.ASSIST_SALARY_AMOUNT to "راتبك المتوقع {0}.",
    TextKey.ASSIST_SALARY_NA to "راتبك غير متاح: لم تُسجّل مبلغه المتوقع.",
    TextKey.ASSIST_LAST_AT to "آخر مرة عند {0}: {1} يوم {2}{3}.",
    TextKey.ASSIST_FROM_WALLET to " من {0}",
    TextKey.ASSIST_LAST_NONE to "لا توجد عمليات عند {0}.",
    TextKey.ASSIST_GOAL to "{0}: ادّخرت {1} من {2}.",
    TextKey.ASSIST_GOAL_AHEAD to "متقدم عن الخطة بـ{0}.",
    TextKey.ASSIST_GOAL_BEHIND to "متأخر عن الخطة بـ{0}.",
    TextKey.ASSIST_GOAL_PER_MONTH to "تحتاج {0} شهريًا لتصل في موعدك.",
    TextKey.ASSIST_GOAL_NA to "تقدّم {0} غير متاح: رصيده غير معروف.",
    TextKey.ASSIST_NO_GOALS to "لا توجد خطط ادخار بعد.",
    TextKey.ASSIST_ZAKAT_HIDDEN to "الزكاة مخفية — تظهر من «المحتوى الإسلامي» في الإعدادات.",
    TextKey.ASSIST_ZAKAT_NO_YEAR to "لم تحدد بداية الحول بعد.",
    TextKey.ASSIST_ZAKAT_SUGGEST to "لم تحدد بداية الحول بعد. المقترح: يبدأ {0} وتستحق الزكاة {1}.",
    TextKey.ASSIST_ZAKAT_NA to "مبلغ الزكاة غير متاح الآن (الأسعار أو بعض الأصول غير معروفة). موعدها {0}.",
    TextKey.ASSIST_ZAKAT_DUE to "زكاتك {0}، وموعدها {1}.",
    TextKey.ASSIST_ZAKAT_PAID to "دفعت {0}، والمتبقي {1}.",
    TextKey.ASSIST_DUES_UNTIL_PAYDAY to "قبل الراتب ({0}) عليك {1} — عددها {2}.",
    TextKey.ASSIST_DUES_UNKNOWN_AMOUNT to "و{0} بلا مبلغ معروف.",
    TextKey.ASSIST_DUES_LIST to "القادم: {0}.",
    TextKey.ASSIST_DUES_NONE to "لا مستحقات عليك في الثلاثين يومًا القادمة.",
    TextKey.ASSIST_BILL to "{0}: عادةً {1}، والموعد القادم {2}.",
    TextKey.ASSIST_BILLS_LIST to "فواتيرك واشتراكاتك: {0}.",
    TextKey.ASSIST_NO_BILLS to "لا توجد فواتير أو اشتراكات مسجّلة.",
    TextKey.ASSIST_PENDING to "{0} رسالة بنك تنتظر، و{1} عملية تحتاج تأكيدًا.",
    TextKey.ASSIST_PENDING_REVIEW to "{0} عملية تحتاج تأكيدًا.",
    TextKey.ASSIST_PENDING_NONE to "لا شيء ينتظر تأكيدك.",
    TextKey.ASSIST_ASSETS to "قيمة أصولك {0}.",
    TextKey.ASSIST_ASSETS_PARTIAL to "({0} أصل بلا سعر غير محسوب.)",
    TextKey.ASSIST_ASSETS_NA to "قيمة أصولك غير متاحة: لا أسعار معروفة.",
    TextKey.ASSIST_NO_ASSETS to "لا توجد أصول مسجّلة.",
    TextKey.ASSIST_EVENT to "صرفت على {0} {1} ({2}).",
    TextKey.ASSIST_EVENT_NONE to "لا مصروف مربوط بـ{0}.",
    TextKey.ASSIST_WHICH_EVENT to "أي حدث؟ اختره من «الأحداث».",
    TextKey.ASSIST_PROJECT to "مشروع {0}: صرفت {1} ({2}).",
    TextKey.ASSIST_WHICH_PROJECT to "أي مشروع؟ اختره من «المشاريع».",
    TextKey.ASSIST_ROSCA to "{0}: دفعت {1} من {2} أقساط.",
    TextKey.ASSIST_NEXT_PAYMENT to "القسط القادم {0} يوم {1}.",
    TextKey.ASSIST_ROSCA_PAYOUT to "دورك في القبض {0}.",
    TextKey.ASSIST_NO_ROSCAS to "لا توجد جمعيات.",
    TextKey.ASSIST_INSTALLMENT to "{0}: بقي {1} — {2} من {3} أقساط.",
    TextKey.ASSIST_NO_INSTALLMENTS to "لا توجد أقساط متبقية.",
    TextKey.ASSIST_OCCASIONS to "المناسبات القادمة: {0}.",
    TextKey.ASSIST_NO_OCCASIONS to "لا مناسبات في الثلاثين يومًا القادمة.",
)

internal val EGYPTIAN_ASSIST_ANSWER2_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_OWED_TO_ME to "ليك عند الناس {0} — منهم: {1}.",
    TextKey.ASSIST_OWED_NONE to "محدش عليه فلوس ليك.",
    TextKey.ASSIST_I_OWE to "عليك للناس {0} — منهم: {1}.",
    TextKey.ASSIST_I_OWE_NONE to "مش عليك فلوس لحد.",
    TextKey.ASSIST_PERSON_OWES_ME to "ليك عند {0} {1}.",
    TextKey.ASSIST_I_OWE_PERSON to "عليك لـ{0} {1}.",
    TextKey.ASSIST_CUSTODY to "وعندك أمانة لـ{0} {1}.",
    TextKey.ASSIST_PERSON_NONE to "مفيش ديون بينك وبين {0}.",
    TextKey.ASSIST_OVERDUE to "اتأخروا في السداد: {0}.",
    TextKey.ASSIST_OVERDUE_ITEM to "{0} ({1}) من {2}",
    TextKey.ASSIST_OVERDUE_NONE to "محدش متأخر في السداد.",
    TextKey.ASSIST_NEXT_SALARY to "المرتب يوم {0} — بعد {1}.",
    TextKey.ASSIST_SALARY_TODAY to "المرتب النهارده.",
    TextKey.ASSIST_SALARY_DAY_NA to "ميعاد المرتب مش متاح: يومه مش متحدد.",
    TextKey.ASSIST_NO_SALARY to "مفيش مرتب شغال في {0} دلوقتي.",
    TextKey.ASSIST_SPACE_INCOME to "دخل {0}: {1}.",
    TextKey.ASSIST_SALARY_AMOUNT to "مرتبك المتوقع {0}.",
    TextKey.ASSIST_SALARY_NA to "مرتبك مش متاح: ما سجلتش مبلغه المتوقع.",
    TextKey.ASSIST_LAST_AT to "آخر مرة عند {0}: {1} يوم {2}{3}.",
    TextKey.ASSIST_FROM_WALLET to " من {0}",
    TextKey.ASSIST_LAST_NONE to "مفيش عمليات عند {0}.",
    TextKey.ASSIST_GOAL to "{0}: حوّشت {1} من {2}.",
    TextKey.ASSIST_GOAL_AHEAD to "سابق الخطة بـ{0}.",
    TextKey.ASSIST_GOAL_BEHIND to "متأخر عن الخطة بـ{0}.",
    TextKey.ASSIST_GOAL_PER_MONTH to "محتاج {0} في الشهر عشان توصل في ميعادك.",
    TextKey.ASSIST_GOAL_NA to "{0} مش متاح: رصيدها مش معروف.",
    TextKey.ASSIST_NO_GOALS to "لسه مفيش خطط تحويش.",
    TextKey.ASSIST_ZAKAT_HIDDEN to "الزكاة مخفية — بتظهر من «المحتوى الإسلامي» في الإعدادات.",
    TextKey.ASSIST_ZAKAT_NO_YEAR to "لسه ما حددتش بداية الحول.",
    TextKey.ASSIST_ZAKAT_SUGGEST to "لسه ما حددتش بداية الحول. المقترح: يبدأ {0} والزكاة تستحق {1}.",
    TextKey.ASSIST_ZAKAT_NA to "مبلغ الزكاة مش متاح دلوقتي (الأسعار أو شوية أصول مش معروفة). ميعادها {0}.",
    TextKey.ASSIST_ZAKAT_DUE to "زكاتك {0}، وميعادها {1}.",
    TextKey.ASSIST_ZAKAT_PAID to "دفعت {0}، وفاضل {1}.",
    TextKey.ASSIST_DUES_UNTIL_PAYDAY to "قبل المرتب ({0}) عليك {1} — عددهم {2}.",
    TextKey.ASSIST_DUES_UNKNOWN_AMOUNT to "و{0} من غير مبلغ معروف.",
    TextKey.ASSIST_DUES_LIST to "الجاي: {0}.",
    TextKey.ASSIST_DUES_NONE to "مفيش مستحقات عليك في التلاتين يوم الجايين.",
    TextKey.ASSIST_BILL to "{0}: عادةً {1}، والميعاد الجاي {2}.",
    TextKey.ASSIST_BILLS_LIST to "فواتيرك واشتراكاتك: {0}.",
    TextKey.ASSIST_NO_BILLS to "مفيش فواتير ولا اشتراكات متسجلة.",
    TextKey.ASSIST_PENDING to "{0} رسالة بنك مستنية، و{1} عملية محتاجة تأكيد.",
    TextKey.ASSIST_PENDING_REVIEW to "{0} عملية محتاجة تأكيد.",
    TextKey.ASSIST_PENDING_NONE to "مفيش حاجة مستنية تأكيدك.",
    TextKey.ASSIST_ASSETS to "قيمة أصولك {0}.",
    TextKey.ASSIST_ASSETS_PARTIAL to "({0} أصل من غير سعر مش محسوب.)",
    TextKey.ASSIST_ASSETS_NA to "قيمة أصولك مش متاحة: مفيش أسعار معروفة.",
    TextKey.ASSIST_NO_ASSETS to "مفيش أصول متسجلة.",
    TextKey.ASSIST_EVENT to "صرفت على {0} {1} ({2}).",
    TextKey.ASSIST_EVENT_NONE to "مفيش مصروف مربوط بـ{0}.",
    TextKey.ASSIST_WHICH_EVENT to "أنهي حدث؟ اختاره من «الأحداث».",
    TextKey.ASSIST_PROJECT to "مشروع {0}: صرفت {1} ({2}).",
    TextKey.ASSIST_WHICH_PROJECT to "أنهي مشروع؟ اختاره من «المشاريع».",
    TextKey.ASSIST_ROSCA to "{0}: دفعت {1} من {2} أقساط.",
    TextKey.ASSIST_NEXT_PAYMENT to "القسط الجاي {0} يوم {1}.",
    TextKey.ASSIST_ROSCA_PAYOUT to "دورك تقبض {0}.",
    TextKey.ASSIST_NO_ROSCAS to "مفيش جمعيات.",
    TextKey.ASSIST_INSTALLMENT to "{0}: فاضل {1} — {2} من {3} أقساط.",
    TextKey.ASSIST_NO_INSTALLMENTS to "مفيش أقساط فاضلة.",
    TextKey.ASSIST_OCCASIONS to "المناسبات الجاية: {0}.",
    TextKey.ASSIST_NO_OCCASIONS to "مفيش مناسبات في التلاتين يوم الجايين.",
)

internal val ENGLISH_ASSIST_ANSWER2_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_OWED_TO_ME to "People owe you {0} — including: {1}.",
    TextKey.ASSIST_OWED_NONE to "Nobody owes you money.",
    TextKey.ASSIST_I_OWE to "You owe people {0} — including: {1}.",
    TextKey.ASSIST_I_OWE_NONE to "You don't owe anyone money.",
    TextKey.ASSIST_PERSON_OWES_ME to "{0} owes you {1}.",
    TextKey.ASSIST_I_OWE_PERSON to "You owe {0} {1}.",
    TextKey.ASSIST_CUSTODY to "You also hold {1} in trust for {0}.",
    TextKey.ASSIST_PERSON_NONE to "No debts between you and {0}.",
    TextKey.ASSIST_OVERDUE to "Overdue: {0}.",
    TextKey.ASSIST_OVERDUE_ITEM to "{0} ({1}) for {2}",
    TextKey.ASSIST_OVERDUE_NONE to "Nobody is overdue.",
    TextKey.ASSIST_NEXT_SALARY to "Payday is {0} — in {1}.",
    TextKey.ASSIST_SALARY_TODAY to "Payday is today.",
    TextKey.ASSIST_SALARY_DAY_NA to "Payday is not available: its day isn't set.",
    TextKey.ASSIST_NO_SALARY to "There is no active salary in {0} now.",
    TextKey.ASSIST_SPACE_INCOME to "{0} income: {1}.",
    TextKey.ASSIST_SALARY_AMOUNT to "Your expected salary is {0}.",
    TextKey.ASSIST_SALARY_NA to "Your salary is not available: its expected amount isn't recorded.",
    TextKey.ASSIST_LAST_AT to "Last time at {0}: {1} on {2}{3}.",
    TextKey.ASSIST_FROM_WALLET to " from {0}",
    TextKey.ASSIST_LAST_NONE to "No transactions at {0}.",
    TextKey.ASSIST_GOAL to "{0}: saved {1} of {2}.",
    TextKey.ASSIST_GOAL_AHEAD to "Ahead of plan by {0}.",
    TextKey.ASSIST_GOAL_BEHIND to "Behind plan by {0}.",
    TextKey.ASSIST_GOAL_PER_MONTH to "You need {0} a month to make it on time.",
    TextKey.ASSIST_GOAL_NA to "{0} progress is not available: its balance is unknown.",
    TextKey.ASSIST_NO_GOALS to "No savings plans yet.",
    TextKey.ASSIST_ZAKAT_HIDDEN to "Zakat is hidden — turn on “Islamic content” in settings.",
    TextKey.ASSIST_ZAKAT_NO_YEAR to "You haven't set the start of your zakat year yet.",
    TextKey.ASSIST_ZAKAT_SUGGEST to "You haven't set the start of your zakat year yet. Suggested: starting {0}, zakat due {1}.",
    TextKey.ASSIST_ZAKAT_NA to "The zakat amount isn't available now (prices or some assets are unknown). It's due {0}.",
    TextKey.ASSIST_ZAKAT_DUE to "Your zakat is {0}, due {1}.",
    TextKey.ASSIST_ZAKAT_PAID to "You paid {0}; {1} remains.",
    TextKey.ASSIST_DUES_UNTIL_PAYDAY to "Before payday ({0}) you have {1} due — {2} items.",
    TextKey.ASSIST_DUES_UNKNOWN_AMOUNT to "Plus {0} with no known amount.",
    TextKey.ASSIST_DUES_LIST to "Coming up: {0}.",
    TextKey.ASSIST_DUES_NONE to "Nothing due in the next thirty days.",
    TextKey.ASSIST_BILL to "{0}: usually {1}, next due {2}.",
    TextKey.ASSIST_BILLS_LIST to "Your bills and subscriptions: {0}.",
    TextKey.ASSIST_NO_BILLS to "No bills or subscriptions recorded.",
    TextKey.ASSIST_PENDING to "{0} bank messages waiting, and {1} transactions need confirming.",
    TextKey.ASSIST_PENDING_REVIEW to "{0} transactions need confirming.",
    TextKey.ASSIST_PENDING_NONE to "Nothing is waiting for you.",
    TextKey.ASSIST_ASSETS to "Your assets are worth {0}.",
    TextKey.ASSIST_ASSETS_PARTIAL to "({0} assets without a price are not counted.)",
    TextKey.ASSIST_ASSETS_NA to "Your assets' value is not available: no known prices.",
    TextKey.ASSIST_NO_ASSETS to "No assets recorded.",
    TextKey.ASSIST_EVENT to "You spent {1} on {0} ({2}).",
    TextKey.ASSIST_EVENT_NONE to "No spending linked to {0}.",
    TextKey.ASSIST_WHICH_EVENT to "Which event? Pick it from “Events”.",
    TextKey.ASSIST_PROJECT to "Project {0}: spent {1} ({2}).",
    TextKey.ASSIST_WHICH_PROJECT to "Which project? Pick it from “Projects”.",
    TextKey.ASSIST_ROSCA to "{0}: paid {1} of {2} contributions.",
    TextKey.ASSIST_NEXT_PAYMENT to "Next payment {0} on {1}.",
    TextKey.ASSIST_ROSCA_PAYOUT to "Your payout turn is {0}.",
    TextKey.ASSIST_NO_ROSCAS to "No roscas.",
    TextKey.ASSIST_INSTALLMENT to "{0}: {1} left — {2} of {3} payments.",
    TextKey.ASSIST_NO_INSTALLMENTS to "No installments left.",
    TextKey.ASSIST_OCCASIONS to "Upcoming occasions: {0}.",
    TextKey.ASSIST_NO_OCCASIONS to "No occasions in the next thirty days.",
)
