package app.masroufy.core

/**
 * نصوص «حاسبة التقاعد» (`RetirementCalculator` + `RetirementSaudi`) — من النموذج بالحرف (الفصحى للسعودية والمصري لمصر)؛ الإنجليزي كتابة
 * Claude (مستني مراجعة المالك §40). أسباب «غير متاح» نفسها من `TextsCalculators.kt`/`TextsRetirement.kt` (حالة الاستخدام).
 */
internal val MSA_CALC_RETIRE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.RETCALC_TITLE to "حاسبة التقاعد",
    TextKey.RETCALC_LAW_SA to "السعودية، نظام التأمينات الاجتماعية",
    TextKey.RETCALC_LAW_EG to "مصر، قانون التأمينات والمعاشات ١٤٨ لسنة ٢٠١٩",
    TextKey.RETCALC_INTRO to "تجيب عن سؤالين: كم سيكون معاشك، وكم تدّخر شهريًا لتعيش بالمبلغ الذي تريده.",
    TextKey.RETCALC_COUNTRY_NA to "حاسبة التقاعد متاحة للسعودية ومصر فقط",
    TextKey.RETCALC_FILL to "أكمل البيانات",
    TextKey.RETCALC_FILL_SUB to "تظهر النتيجة حين تصح الخانات.",
    TextKey.RETCALC_NO_PENSION to "لا معاش",
    TextKey.RETCALC_EOS to "مكافأة نهاية الخدمة",
    TextKey.RETCALC_GAP to "كم تدّخر شهريًا حتى التقاعد",
    TextKey.RETCALC_NOT_APPLICABLE to "لا تنطبق",
    TextKey.RETCALC_NOT_COUNTED to "لا يُحسب",
    TextKey.RETCALC_EOS_PICK_END to "اختر كيف سينتهي عملك",
    TextKey.RETCALC_EOS_SUB to "{0} سنة و{1} يومًا، {2}",
    TextKey.RETCALC_EOS_NONE to "لا شيء",
    TextKey.RETCALC_EOS_THIRD to "ثلثها (استقالة)",
    TextKey.RETCALC_EOS_TWO_THIRDS to "ثلثاها (استقالة)",
    TextKey.RETCALC_EOS_FULL to "كاملة",
    TextKey.RETCALC_GAP_NEED_WANT to "اكتب المبلغ الشهري الذي تريد العيش به",
    TextKey.RETCALC_GAP_SUB to "ينقصك {0} شهريًا بعد المعاش × {1} شهرًا = {2} − المكافأة − ما معك = {3} ÷ {4} شهرًا، بلا أرباح",
    TextKey.RETCALC_HOW_SHOW to "كيف حُسب المعاش؟",
    TextKey.RETCALC_HOW_HIDE to "إخفاء طريقة الحساب",
    TextKey.RETCALC_HOW_APPLIED to " ← طُبّق",
    TextKey.RETCALC_SEC_CONTRIB to "اشتراكك",
    TextKey.RETCALC_BIRTH to "تاريخ الميلاد",
    TextKey.RETCALC_SO_FAR to "شهور الاشتراك حتى اليوم",
    TextKey.RETCALC_SO_FAR_NOTE to "من كشف التأمينات",
    TextKey.RETCALC_SOFAR_RANGE to "المدة من ٠ حتى ١٢٠٠ شهر",
    TextKey.RETCALC_RETIRE to "السن الذي تنوي التقاعد فيه (اختياري)",
    TextKey.RETCALC_RETIRE_NOTE to "فارغ = السن النظامية",
    TextKey.RETCALC_RETIRE_NOTE_LEGAL to "فارغ = السن النظامية لك: {0}",
    TextKey.RETCALC_MANY_JOBS to "لك أكثر من عمل حالي في مصادر الدخل — اكتب أجرك بنفسك",
    TextKey.RETCALC_SEC_LIVING to "ما تريد العيش به",
    TextKey.RETCALC_WANT to "المبلغ الشهري الذي تريد العيش به",
    TextKey.RETCALC_YEARS to "كم سنة يكفيك مال التقاعد؟",
    TextKey.RETCALC_YEARS_NOTE to "مطلوب — لا رقم افتراضي له",
    TextKey.RETCALC_HAVE to "كم معك الآن للتقاعد؟",
    TextKey.RETCALC_HAVE_NOTE to "فارغ = صفر",
    TextKey.RETSA_QUESTION to "هل اشتركت في التأمينات قبل يوليو ٢٠٢٤؟",
    TextKey.RETSA_LAW_LINE_OLD to "النظام القديم (م/٣٣) — وسن التقاعد من جدول البند «خامسًا» في المرسوم م/٢٧٣",
    TextKey.RETSA_LAW_LINE_NEW to "النظام الجديد (م/٢٧٣) — السن النظامية ٦٥",
    TextKey.RETSA_LAW_OLD to "النظام القديم",
    TextKey.RETSA_LAW_NEW to "النظام الجديد",
    TextKey.RETSA_HERO_LABEL to "المعاش المتوقع شهريًا",
    TextKey.RETSA_HERO_SUB to "{0}، التقاعد عند {1} في {2}، {3} شهر اشتراك",
    TextKey.RETSA_AT_2024 to "شهور اشتراكك في ٣ يوليو ٢٠٢٤",
    TextKey.RETSA_AT_2024_NOTE to "سن تقاعدك في النظام القديم يتحدد منها",
    TextKey.RETSA_M_1422 to "منها قبل ١٤٢٢هـ (اختياري)",
    TextKey.RETSA_M_1422_NOTE to "تُحسب على ٦٠٠ بدل ٤٨٠",
    TextKey.RETSA_SEC_WAGE to "أجرك الخاضع للاشتراك",
    TextKey.RETSA_BASIC to "الأجر الأساسي الشهري",
    TextKey.RETSA_BASIC_NOTE to "اكتب أجرك الأساسي الشهري",
    TextKey.RETSA_BASIC_NOTE_SUGGEST to "فارغ = راتبك في مصادر الدخل ({0}) — عدّله إن كان فيه بدلات",
    TextKey.RETSA_HOUSING to "بدل السكن الشهري",
    TextKey.RETSA_HOUSING_NOTE to "اكتب صفرًا إن لم يكن لك بدل سكن",
    TextKey.RETSA_JOB to "بداية عملك الحالي",
    TextKey.RETSA_JOB_NOTE to "اختر تاريخ بداية عملك الحالي",
    TextKey.RETSA_JOB_NOTE_SUGGEST to "من مصادر الدخل: {0} — غيّره إن لزم",
    TextKey.RETSA_EOS_WAGE to "أجرك الأخير كاملًا",
    TextKey.RETSA_EOS_WAGE_NOTE to "الأساسي مع كل البدلات (نظام العمل م٢)",
    TextKey.RETSA_EOS_WAGE_NOTE_SUGGEST to "فارغ = راتبك في مصادر الدخل ({0}) — الأساسي مع كل البدلات (نظام العمل م٢)",
    TextKey.RETSA_END to "كيف سينتهي عملك؟",
    TextKey.RETSA_END_NOTE to "نسألك كل مرة — الاستقالة تُنقص المكافأة (م٨٥)",
    TextKey.RETSA_END_CONTRACT to "انتهاء العقد أو السن",
    TextKey.RETSA_END_RESIGN to "استقالة",
    TextKey.RETSA_END_ART80 to "فسخ (م٨٠)",
    TextKey.RETSA_HOW_NEW_WAGE to "متوسط الأجر (الأساسي + السكن، بسقف ٤٥٬٠٠٠): {0}",
    TextKey.RETSA_HOW_NEW_ACCRUED to "× ٢٫٢٥٪ × {0} شهرًا ÷ ١٢ = {1}",
    TextKey.RETSA_HOW_CAPPED to " ← بسقف ١٠٠٪ من المتوسط",
    TextKey.RETSA_HOW_NEW_MIN to "الحد الأدنى لمدتك: {0}",
    TextKey.RETSA_HOW_NEW_REDUCE to "التخفيض المبكر: −{0} (٣٪ عن كل ١٢ شهرًا من {1} شهرًا — بعد الحد الأدنى، فقد ينزل تحته)",
    TextKey.RETSA_HOW_NEW_INCREASE to "الزيادة بعد السن: +{0} (٣٪ عن كل ١٢ شهرًا)",
    TextKey.RETSA_HOW_NEW_NONE to "لا تخفيض ولا زيادة: التقاعد في السن النظامية",
    TextKey.RETSA_HOW_OLD_WAGE to "متوسط أجر آخر سنتين (الأساسي + السكن): {0}",
    TextKey.RETSA_HOW_OLD_ACCRUED to "× {0} ÷ ٤٨٠ = {1}",
    TextKey.RETSA_HOW_OLD_ACCRUED_1422 to "× {0} ÷ ٤٨٠ + {1} ÷ ٦٠٠ = {2}",
    TextKey.RETSA_HOW_OLD_MIN to "الحد الأدنى {0}",
    TextKey.RETSA_HOW_OLD_AGE_FIFTH to "سن تقاعدك: {0} — من جدول البند «خامسًا» في المرسوم م/٢٧٣",
    TextKey.RETSA_HOW_OLD_AGE_60 to "سن تقاعدك: {0} — البند «خامسًا» لا ينطبق عليك",
    TextKey.RETSA_ASSUME to "فرض الحساب: الاشتراك والأجر مستمران كما هما حتى التقاعد، وما تدّخره بلا أرباح. حساب تقريبي للتخطيط، والرقم الرسمي من التأمينات.",
    TextKey.RETSA_SOURCES to "المصادر: نظام التأمينات الاجتماعية (م/٢٧٣) المواد ٨ و١٦–١٧ و٢٦ وقرار مجلس الوزراء ١٠٢٢، صفحة المعاش في التأمينات (النظام القديم)، نظام العمل المواد ٢ و٨٤–٨٥ و٨٧.",
)

internal val EGYPTIAN_CALC_RETIRE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.RETCALC_TITLE to "حاسبة التقاعد",
    TextKey.RETCALC_LAW_SA to "السعودية، نظام التأمينات الاجتماعية",
    TextKey.RETCALC_LAW_EG to "مصر، قانون التأمينات والمعاشات ١٤٨ لسنة ٢٠١٩",
    TextKey.RETCALC_INTRO to "بتجاوب على سؤالين: معاشك هيبقى كام، وتحوّش كام في الشهر عشان تعيش بالمبلغ اللي عايزه.",
    TextKey.RETCALC_COUNTRY_NA to "حاسبة التقاعد متاحة للسعودية ومصر بس",
    TextKey.RETCALC_FILL to "كمّل البيانات",
    TextKey.RETCALC_FILL_SUB to "الحساب بيظهر أول ما الخانات تبقى صح.",
    TextKey.RETCALC_NO_PENSION to "مفيش معاش",
    TextKey.RETCALC_EOS to "مكافأة نهاية الخدمة",
    TextKey.RETCALC_GAP to "تحوّش كام في الشهر لحد التقاعد",
    TextKey.RETCALC_NOT_APPLICABLE to "مش منطبقة",
    TextKey.RETCALC_NOT_COUNTED to "مش بتتحسب",
    TextKey.RETCALC_EOS_PICK_END to "اختار شغلك هيخلص إزاي",
    TextKey.RETCALC_EOS_SUB to "{0} سنة و{1} يوم، {2}",
    TextKey.RETCALC_EOS_NONE to "ولا حاجة",
    TextKey.RETCALC_EOS_THIRD to "تلتها (استقالة)",
    TextKey.RETCALC_EOS_TWO_THIRDS to "تلتينها (استقالة)",
    TextKey.RETCALC_EOS_FULL to "كاملة",
    TextKey.RETCALC_GAP_NEED_WANT to "اكتب المبلغ اللي عايز تعيش بيه في الشهر",
    TextKey.RETCALC_GAP_SUB to "ناقصك {0} في الشهر بعد المعاش × {1} شهر = {2} − المكافأة − اللي معاك = {3} ÷ {4} شهر، من غير أرباح",
    TextKey.RETCALC_HOW_SHOW to "المعاش اتحسب إزاي؟",
    TextKey.RETCALC_HOW_HIDE to "اخفي طريقة الحساب",
    TextKey.RETCALC_HOW_APPLIED to " ← اتطبّق",
    TextKey.RETCALC_SEC_CONTRIB to "اشتراكك",
    TextKey.RETCALC_BIRTH to "تاريخ الميلاد",
    TextKey.RETCALC_SO_FAR to "شهور الاشتراك لحد النهارده",
    TextKey.RETCALC_SO_FAR_NOTE to "من كشف التأمينات",
    TextKey.RETCALC_SOFAR_RANGE to "المدة من ٠ لحد ١٢٠٠ شهر",
    TextKey.RETCALC_RETIRE to "السن اللي ناوي تتقاعد فيه (اختياري)",
    TextKey.RETCALC_RETIRE_NOTE to "فاضي = سن المعاش",
    TextKey.RETCALC_RETIRE_NOTE_LEGAL to "فاضي = سن المعاش بتاعك: {0}",
    TextKey.RETCALC_MANY_JOBS to "ليك أكتر من شغل حالي في مصادر الدخل — اكتب أجرك بنفسك",
    TextKey.RETCALC_SEC_LIVING to "اللي عايز تعيش بيه",
    TextKey.RETCALC_WANT to "عايز تعيش بكام في الشهر؟",
    TextKey.RETCALC_YEARS to "فلوس التقاعد تكفيك كام سنة؟",
    TextKey.RETCALC_YEARS_NOTE to "مطلوب — مفيش رقم افتراضي له",
    TextKey.RETCALC_HAVE to "معاك كام للتقاعد دلوقتي؟",
    TextKey.RETCALC_HAVE_NOTE to "فاضي = صفر",
    TextKey.RETSA_QUESTION to "اشتركت في التأمينات قبل يوليو ٢٠٢٤؟",
    TextKey.RETSA_LAW_LINE_OLD to "النظام القديم (م/٣٣) — وسن التقاعد من جدول البند «خامسًا» في المرسوم م/٢٧٣",
    TextKey.RETSA_LAW_LINE_NEW to "النظام الجديد (م/٢٧٣) — سن المعاش ٦٥",
    TextKey.RETSA_LAW_OLD to "النظام القديم",
    TextKey.RETSA_LAW_NEW to "النظام الجديد",
    TextKey.RETSA_HERO_LABEL to "المعاش المتوقع في الشهر",
    TextKey.RETSA_HERO_SUB to "{0}، التقاعد على {1} في {2}، {3} شهر اشتراك",
    TextKey.RETSA_AT_2024 to "شهور اشتراكك يوم ٣ يوليو ٢٠٢٤",
    TextKey.RETSA_AT_2024_NOTE to "سن تقاعدك في النظام القديم بيتحدد منها",
    TextKey.RETSA_M_1422 to "منهم قبل ١٤٢٢هـ (اختياري)",
    TextKey.RETSA_M_1422_NOTE to "بتتحسب على ٦٠٠ بدل ٤٨٠",
    TextKey.RETSA_SEC_WAGE to "أجرك اللي عليه اشتراك",
    TextKey.RETSA_BASIC to "المرتب الأساسي في الشهر",
    TextKey.RETSA_BASIC_NOTE to "اكتب مرتبك الأساسي في الشهر",
    TextKey.RETSA_BASIC_NOTE_SUGGEST to "فاضي = مرتبك في مصادر الدخل ({0}) — عدّله لو فيه بدلات",
    TextKey.RETSA_HOUSING to "بدل السكن في الشهر",
    TextKey.RETSA_HOUSING_NOTE to "اكتب صفر لو مالكش بدل سكن",
    TextKey.RETSA_JOB to "بداية شغلك الحالي",
    TextKey.RETSA_JOB_NOTE to "اختار تاريخ بداية شغلك الحالي",
    TextKey.RETSA_JOB_NOTE_SUGGEST to "من مصادر الدخل: {0} — غيّره لو محتاج",
    TextKey.RETSA_EOS_WAGE to "أجرك الأخير كله",
    TextKey.RETSA_EOS_WAGE_NOTE to "الأساسي مع كل البدلات (نظام العمل م٢)",
    TextKey.RETSA_EOS_WAGE_NOTE_SUGGEST to "فاضي = مرتبك في مصادر الدخل ({0}) — الأساسي مع كل البدلات (نظام العمل م٢)",
    TextKey.RETSA_END to "شغلك هيخلص إزاي؟",
    TextKey.RETSA_END_NOTE to "بنسألك كل مرة — الاستقالة بتقلّل المكافأة (م٨٥)",
    TextKey.RETSA_END_CONTRACT to "انتهاء العقد أو السن",
    TextKey.RETSA_END_RESIGN to "استقالة",
    TextKey.RETSA_END_ART80 to "فسخ (م٨٠)",
    TextKey.RETSA_HOW_NEW_WAGE to "متوسط الأجر (الأساسي + السكن، بسقف ٤٥٬٠٠٠): {0}",
    TextKey.RETSA_HOW_NEW_ACCRUED to "× ٢٫٢٥٪ × {0} شهر ÷ ١٢ = {1}",
    TextKey.RETSA_HOW_CAPPED to " ← بسقف ١٠٠٪ من المتوسط",
    TextKey.RETSA_HOW_NEW_MIN to "الحد الأدنى لمدتك: {0}",
    TextKey.RETSA_HOW_NEW_REDUCE to "التخفيض المبكر: −{0} (٣٪ عن كل ١٢ شهر من {1} شهر — بعد الحد الأدنى، فممكن ينزل تحته)",
    TextKey.RETSA_HOW_NEW_INCREASE to "الزيادة بعد السن: +{0} (٣٪ عن كل ١٢ شهر)",
    TextKey.RETSA_HOW_NEW_NONE to "مفيش تخفيض ولا زيادة: التقاعد في سن المعاش",
    TextKey.RETSA_HOW_OLD_WAGE to "متوسط أجر آخر سنتين (الأساسي + السكن): {0}",
    TextKey.RETSA_HOW_OLD_ACCRUED to "× {0} ÷ ٤٨٠ = {1}",
    TextKey.RETSA_HOW_OLD_ACCRUED_1422 to "× {0} ÷ ٤٨٠ + {1} ÷ ٦٠٠ = {2}",
    TextKey.RETSA_HOW_OLD_MIN to "الحد الأدنى {0}",
    TextKey.RETSA_HOW_OLD_AGE_FIFTH to "سن تقاعدك: {0} — من جدول البند «خامسًا» في المرسوم م/٢٧٣",
    TextKey.RETSA_HOW_OLD_AGE_60 to "سن تقاعدك: {0} — البند «خامسًا» مش بينطبق عليك",
    TextKey.RETSA_ASSUME to "فرض الحسبة: الاشتراك والأجر مستمرين زي ما هم لحد التقاعد، واللي بتحوّشه من غير أرباح. حساب تقريبي للتخطيط، والرقم الرسمي من التأمينات.",
    TextKey.RETSA_SOURCES to "المصادر: نظام التأمينات الاجتماعية (م/٢٧٣) مواد ٨ و١٦–١٧ و٢٦ وقرار مجلس الوزراء ١٠٢٢، صفحة المعاش في التأمينات (النظام القديم)، نظام العمل مواد ٢ و٨٤–٨٥ و٨٧.",
)

internal val ENGLISH_CALC_RETIRE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.RETCALC_TITLE to "Retirement calculator",
    TextKey.RETCALC_LAW_SA to "Saudi Arabia, Social Insurance Law",
    TextKey.RETCALC_LAW_EG to "Egypt, Social Insurance and Pensions Law 148 of 2019",
    TextKey.RETCALC_INTRO to "Answers two questions: what your pension will be, and how much to save each month to live on the amount you want.",
    TextKey.RETCALC_COUNTRY_NA to "The retirement calculator is available for Saudi Arabia and Egypt only",
    TextKey.RETCALC_FILL to "Complete the fields",
    TextKey.RETCALC_FILL_SUB to "The result shows once the fields are valid.",
    TextKey.RETCALC_NO_PENSION to "No pension",
    TextKey.RETCALC_EOS to "End-of-service award",
    TextKey.RETCALC_GAP to "Monthly saving until retirement",
    TextKey.RETCALC_NOT_APPLICABLE to "Not applicable",
    TextKey.RETCALC_NOT_COUNTED to "Not calculated",
    TextKey.RETCALC_EOS_PICK_END to "Choose how your job will end",
    TextKey.RETCALC_EOS_SUB to "{0} years and {1} days, {2}",
    TextKey.RETCALC_EOS_NONE to "nothing",
    TextKey.RETCALC_EOS_THIRD to "a third (resignation)",
    TextKey.RETCALC_EOS_TWO_THIRDS to "two thirds (resignation)",
    TextKey.RETCALC_EOS_FULL to "full",
    TextKey.RETCALC_GAP_NEED_WANT to "Enter the monthly amount you want to live on",
    TextKey.RETCALC_GAP_SUB to "{0} a month short after the pension × {1} months = {2} − the award − what you have = {3} ÷ {4} months, without returns",
    TextKey.RETCALC_HOW_SHOW to "How was the pension calculated?",
    TextKey.RETCALC_HOW_HIDE to "Hide the calculation",
    TextKey.RETCALC_HOW_APPLIED to " ← applied",
    TextKey.RETCALC_SEC_CONTRIB to "Your contributions",
    TextKey.RETCALC_BIRTH to "Date of birth",
    TextKey.RETCALC_SO_FAR to "Contribution months to date",
    TextKey.RETCALC_SO_FAR_NOTE to "From your social insurance statement",
    TextKey.RETCALC_SOFAR_RANGE to "From 0 to 1200 months",
    TextKey.RETCALC_RETIRE to "The age you plan to retire at (optional)",
    TextKey.RETCALC_RETIRE_NOTE to "Empty = the statutory age",
    TextKey.RETCALC_RETIRE_NOTE_LEGAL to "Empty = your statutory age: {0}",
    TextKey.RETCALC_MANY_JOBS to "You have more than one current job in your income sources — enter your wage yourself",
    TextKey.RETCALC_SEC_LIVING to "What you want to live on",
    TextKey.RETCALC_WANT to "The monthly amount you want to live on",
    TextKey.RETCALC_YEARS to "How many years should the retirement money last?",
    TextKey.RETCALC_YEARS_NOTE to "Required — there is no default for it",
    TextKey.RETCALC_HAVE to "How much do you have for retirement now?",
    TextKey.RETCALC_HAVE_NOTE to "Empty = zero",
    TextKey.RETSA_QUESTION to "Did you join social insurance before July 2024?",
    TextKey.RETSA_LAW_LINE_OLD to "Old system (M/33) — retirement age from the table in clause Five of decree M/273",
    TextKey.RETSA_LAW_LINE_NEW to "New system (M/273) — statutory age 65",
    TextKey.RETSA_LAW_OLD to "Old system",
    TextKey.RETSA_LAW_NEW to "New system",
    TextKey.RETSA_HERO_LABEL to "Expected monthly pension",
    TextKey.RETSA_HERO_SUB to "{0}, retiring at {1} in {2}, {3} contribution months",
    TextKey.RETSA_AT_2024 to "Your contribution months on 3 July 2024",
    TextKey.RETSA_AT_2024_NOTE to "Your retirement age in the old system depends on it",
    TextKey.RETSA_M_1422 to "Of which before 1422 AH (optional)",
    TextKey.RETSA_M_1422_NOTE to "Counted over 600 instead of 480",
    TextKey.RETSA_SEC_WAGE to "Your contributory wage",
    TextKey.RETSA_BASIC to "Basic monthly wage",
    TextKey.RETSA_BASIC_NOTE to "Enter your basic monthly wage",
    TextKey.RETSA_BASIC_NOTE_SUGGEST to "Empty = your salary in income sources ({0}) — edit it if it includes allowances",
    TextKey.RETSA_HOUSING to "Monthly housing allowance",
    TextKey.RETSA_HOUSING_NOTE to "Enter zero if you have no housing allowance",
    TextKey.RETSA_JOB to "Start of your current job",
    TextKey.RETSA_JOB_NOTE to "Pick the start date of your current job",
    TextKey.RETSA_JOB_NOTE_SUGGEST to "From income sources: {0} — change it if needed",
    TextKey.RETSA_EOS_WAGE to "Your full last wage",
    TextKey.RETSA_EOS_WAGE_NOTE to "Basic plus all allowances (Labor Law art. 2)",
    TextKey.RETSA_EOS_WAGE_NOTE_SUGGEST to "Empty = your salary in income sources ({0}) — basic plus all allowances (Labor Law art. 2)",
    TextKey.RETSA_END to "How will your job end?",
    TextKey.RETSA_END_NOTE to "Asked every time — resigning reduces the award (art. 85)",
    TextKey.RETSA_END_CONTRACT to "Contract end or age",
    TextKey.RETSA_END_RESIGN to "Resignation",
    TextKey.RETSA_END_ART80 to "Dismissal (art. 80)",
    TextKey.RETSA_HOW_NEW_WAGE to "Average wage (basic + housing, capped at 45,000): {0}",
    TextKey.RETSA_HOW_NEW_ACCRUED to "× 2.25% × {0} months ÷ 12 = {1}",
    TextKey.RETSA_HOW_CAPPED to " ← capped at 100% of the average",
    TextKey.RETSA_HOW_NEW_MIN to "Minimum for your service: {0}",
    TextKey.RETSA_HOW_NEW_REDUCE to "Early reduction: −{0} (3% per 12 months over {1} months — after the minimum, so it may go below it)",
    TextKey.RETSA_HOW_NEW_INCREASE to "Increase after the age: +{0} (3% per 12 months)",
    TextKey.RETSA_HOW_NEW_NONE to "No reduction or increase: retiring at the statutory age",
    TextKey.RETSA_HOW_OLD_WAGE to "Average wage of the last two years (basic + housing): {0}",
    TextKey.RETSA_HOW_OLD_ACCRUED to "× {0} ÷ 480 = {1}",
    TextKey.RETSA_HOW_OLD_ACCRUED_1422 to "× {0} ÷ 480 + {1} ÷ 600 = {2}",
    TextKey.RETSA_HOW_OLD_MIN to "Minimum {0}",
    TextKey.RETSA_HOW_OLD_AGE_FIFTH to "Your retirement age: {0} — from the table in clause Five of decree M/273",
    TextKey.RETSA_HOW_OLD_AGE_60 to "Your retirement age: {0} — clause Five does not apply to you",
    TextKey.RETSA_ASSUME to "Assumption: contributions and wage continue as they are until retirement, and savings earn no returns. An approximate planning estimate; the official figure comes from social insurance.",
    TextKey.RETSA_SOURCES to "Sources: Social Insurance Law (M/273) arts. 8, 16–17 and 26 and Council of Ministers decision 1022, the GOSI pension page (old system), Labor Law arts. 2, 84–85 and 87.",
)
