package app.masroufy.core

/**
 * النصوص بالعربي — **الأصل**. أي قيمة هنا هي نفس النص اللي كان مكتوب جوه الكود بالحرف،
 * فملفات المرجع (golden) بتفضل مطابقة. تغيير أي نص هنا = تغيير في شاشة المالك.
 */
internal val ARABIC_SCREEN_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.KIND_SALARY to "مرتب",
    TextKey.KIND_BONUS to "بونص",
    TextKey.KIND_COMMISSION to "عمولة",
    TextKey.KIND_OVERTIME to "أوفر تايم",
    TextKey.KIND_FREELANCE to "فري لانس",
    TextKey.KIND_PERSONAL_SALE to "بيع شخصي",
    TextKey.KIND_LOAN_RECEIVED to "قرض مستلم",
    TextKey.KIND_DEBT_COLLECTED to "تحصيل دين لك",
    TextKey.KIND_CUSTODY_RECEIVED to "أمانة مستلمة",
    TextKey.KIND_PURCHASE to "شراء / فاتورة",
    TextKey.KIND_SUPPORT_GIFT to "دعم / هدية",
    TextKey.KIND_FEE to "رسوم",
    TextKey.KIND_LOAN_GRANTED to "قرض ممنوح",
    TextKey.KIND_DEBT_REPAID to "سداد دين عليك",
    TextKey.KIND_CUSTODY_RETURNED to "رد أمانة",
    TextKey.KIND_INTERNAL_TRANSFER to "تحويل داخلي",
    TextKey.KIND_ASSET_BUY to "شراء أصل",
    TextKey.KIND_ASSET_SELL to "بيع أصل",
    TextKey.KIND_UNCLASSIFIED to "غير محدد",
    TextKey.KIND_UNKNOWN_WIRE to "نوع اقتصادي غير معروف: {0}",

    TextKey.CURRENCY_SAR to "ر.س",
    TextKey.CURRENCY_EGP to "ج.م",
    TextKey.CURRENCY_USD to "$",
    TextKey.CURRENCY_EUR to "€",
    TextKey.CURRENCY_GBP to "£",
    TextKey.CURRENCY_AED to "د.إ",

    TextKey.NOT_AVAILABLE to "غير متاح",

    TextKey.AMOUNT_CONTEXT_DISPLAY to "مبلغ للعرض",
    TextKey.AMOUNT_CONTEXT_INCOME to "الدخل",
    TextKey.AMOUNT_CONTEXT_REMAINING to "المتبقي",

    TextKey.SUGGEST_CASH_WITHDRAWAL to "سحب نقدي: الفلوس اتنقلت من البنك لمحفظة الكاش، مش اتصرفت",
    TextKey.SUGGEST_INVESTMENT_BUY to "«{0}»: شراء أصل استثماري، مش استهلاك",
    TextKey.SUGGEST_BANK_FEES to "رسوم بنكية: مصروف مستقل",
    TextKey.SUGGEST_INSTALLMENT to
        "تقسيط: سداد جزء من التزام سابق. لو الشراء الأصلي مسجَّل كمصروف، احتسابه تاني هيبقى عدّ مزدوج.",
    TextKey.SUGGEST_DEBT_PAYMENT to
        "سداد: ممكن يكون سداد دين عليك (مش مصروف) وممكن يكون دفع فاتورة (مصروف). الكشف مش بيفرّق، فمحتاج قرارك.",
    TextKey.SUGGEST_DIGITAL_WALLET to
        "محفظة رقمية (زي برق): الفلوس خرجت من الراجحي، بس الكشف مش بيقول راحت فين. ممكن تكون محفظتك انت، وممكن تكون دعم أو قرض لحد.",
    TextKey.SUGGEST_TRANSFER_OUT to
        "تحويل صادر: الكشف بيقول الفلوس خرجت بس مش بيقول ليه. ممكن تحويل لحسابك، دعم، قرض، أو سداد.",
    TextKey.SUGGEST_BARQ to "برق وسيلة تحويل مش نوع مصروف. لازم تحدد الغرض: حسابك، دعم، قرض، ولا سداد.",
    TextKey.SUGGEST_PURCHASE to "«{0}»: شراء أو فاتورة",
    TextKey.SUGGEST_OUT_NO_CATEGORY to "صادر بلا تصنيف واضح. محتاج تحدد ده شراء ولا نقل فلوس.",
    TextKey.SUGGEST_INVESTMENT_SELL to "وارد من الاستثمار: حصيلة بيع أصل، والربح المحقق فقط هو المكسب",
    TextKey.SUGGEST_REFUND to
        "استرداد: ده رجوع فلوس دفعتها، مش دخل جديد. الأنسب تربطه بالعملية الأصلية بدل ما تعدّه دخلًا.",
    TextKey.SUGGEST_IN_UNKNOWN to
        "وارد: الكشف بيقول الفلوس دخلت بس مش بيقول منين. راتب؟ قرض استلمته؟ تحصيل دين لك؟ أمانة؟ الفرق بينهم كبير في الحساب.",
    TextKey.SUGGEST_IN_WITH_CATEGORY to "وارد بتصنيف «{0}»: محتاج تحدد نوعه الاقتصادي.",
    TextKey.ASSET_KIND_GOLD to "ذهب",
    TextKey.ASSET_KIND_STOCK to "سهم",
    TextKey.ASSET_KIND_FUND to "صندوق",
    TextKey.ASSET_KIND_DIGITAL to "أصل رقمي",
    TextKey.ASSET_KIND_OTHER to "أصل آخر",
    TextKey.AMOUNT_EDIT_INVALID to "اكتب مبلغ صحيح أكبر من صفر، زي 180 أو 180.50",
    TextKey.AMOUNT_EDIT_BELOW_ALLOCATIONS to "المبلغ أقل من اللي متوزع على أشخاص من العملية دي ({0}). عدّل التوزيع الأول.",
    TextKey.AMOUNT_EDIT_BELOW_SETTLEMENTS to "المبلغ أقل من اللي اتسدد بيه دين من العملية دي ({0}). عدّل التسوية الأول.",
    TextKey.ALLOWANCE_PERIOD_ENDED to "الفترة دي خلصت، فمفيش أيام باقية يتوزع عليها.",
    TextKey.ALLOWANCE_NO_LIMIT_NO_REMAINING to "مفيش سقف للفترة دي، والمتبقي نفسه لسه غير معروف.",
    TextKey.ALLOWANCE_NO_LIMIT_SPENT to "تقريبي — مفيش سقف ميزانية، والمتبقي خلص.",
    TextKey.ALLOWANCE_NO_LIMIT to "تقريبي — مفيش سقف ميزانية، فده المتبقي موزّع على {0} يوم باقيين.",
    TextKey.ALLOWANCE_LIMIT_SPENT to "خلصت السقف بتاع الفترة دي.",
    TextKey.ALLOWANCE_LIMIT to "المتبقي من السقف موزّع على {0} يوم باقيين.",
    TextKey.FORECAST_TOO_EARLY to "عدى {0} يوم بس — التوقع محتاج {1} أيام على الأقل.",
    TextKey.FORECAST_PERIOD_ENDED to "الفترة خلصت، فده المصروف الفعلي مش توقع.",
    TextKey.FORECAST_RATE to "لو باقي الفترة مشي بنفس المعدل ({0} يوم عدوا).",
    TextKey.COVERAGE_ALL_UNCLASSIFIED to "كل الـ{0} عملية لسه محتاجة تحديد نوعها، فالمجاميع غير متاحة.",
    TextKey.COVERAGE_SOME_UNCLASSIFIED to "{0} عملية من {1} لسه محتاجة تحديد نوعها، فالأرقام دي ناقصة.",
    TextKey.BUDGET_LIMIT_POSITIVE to "السقف لازم يكون أكبر من صفر",
    TextKey.PERIOD_EXCLUDED_UNRELIABLE to "فيها عمليات لسه محتاجة تحديد نوعها، فمصروفها ناقص",
    TextKey.PERIOD_EXCLUDED_EMPTY to "مفيش فيها عمليات — مش واضح ده صفر حقيقي ولا بيانات ناقصة",
    TextKey.AVERAGE_NEEDS_PERIODS to "المتوسط محتاج {0} فترات مكتملة على الأقل، والمتاح {1}.",
    TextKey.AVERAGE_OF_PERIODS to "متوسط {0} فترة مكتملة.",
    TextKey.ANOMALY_NEEDS_HISTORY to "الحكم على الشذوذ محتاج {0} فترات سابقة على الأقل، والمتاح {1}.",
    TextKey.ANOMALY_MEDIAN_ZERO to "الوسيط التاريخي صفر، فالمقارنة النسبية مالهاش معنى.",
    TextKey.ANOMALY_WITHIN_TWENTY to "الفرق عن المعتاد أقل من ٢٠٪، فمش شذوذ.",
    TextKey.ANOMALY_HIGHER to "أعلى",
    TextKey.ANOMALY_LOWER to "أقل",
    TextKey.ANOMALY_OUTSIDE to "{0} من المعتاد بـ{1}٪ — خارج تقلب الفترات السابقة.",
    TextKey.ANOMALY_INSIDE to "{0} من المعتاد بـ{1}٪، لكن ده داخل تقلب الفترات السابقة العادي.",
    TextKey.CATEGORY_NO_LIMIT to "مفيش سقف للتصنيف ده. تقدر تحدده من هنا.",
    TextKey.CATEGORIZED_USER_CONFIRMED to "أنت أكّدت التصنيف ده بنفسك",
    TextKey.CATEGORIZED_MERCHANT to "التاجر «{0}» له تصنيف مؤكد",
    TextKey.CATEGORIZED_RULE to "قاعدة «{0}» طابقت",
    TextKey.CATEGORIZED_SOURCE_COLUMN to "التصنيف جه من عمود التصنيف في الملف: «{0}»",
    TextKey.CATEGORIZED_NONE to "مفيش قاعدة ولا تاجر مؤكد طابق العملية دي",
    TextKey.ASSET_BUY_QUANTITY_POSITIVE to "كمية الشراء لازم تكون أكبر من صفر",
    TextKey.ASSET_SELL_QUANTITY_POSITIVE to "كمية البيع لازم تكون أكبر من صفر",
    TextKey.ASSET_SELL_OVER_HELD to "بيع {0} والمملوك وقتها {1} فقط. مفيش رصيد سالب صامت.",
    TextKey.PRICE_MISSING to "مفيش سعر متسجل. القيمة الحالية غير متاحة",
    TextKey.PRICE_FRESH to "السعر {0} بتاريخ {1}",
    TextKey.PRICE_FUTURE to "السعر بتاريخ {0} — تاريخ في المستقبل، راجعه",
    TextKey.PRICE_STALE to "السعر {0} بتاريخ {1} — بقاله {2} يوم",
    TextKey.FEED_BAD_SHAPE to "ملف الأسعار مش بالشكل المتوقع",
    TextKey.FEED_NO_GENERATED_AT to "ملف الأسعار مالوش تاريخ توليد",
    TextKey.FEED_NO_CURRENCY to "ملف الأسعار مش قايل عملته",
    TextKey.FEED_NO_PRICES to "ملف الأسعار مفيهوش أسعار",
    TextKey.FEED_ENTRY_NOT_OBJECT to "المدخل مش كائن",
    TextKey.FEED_PRICE_NOT_INTEGER to "السعر مش عددًا صحيحًا موجبًا بالهللة",
    TextKey.FEED_NO_VALID_DATE to "مفيش تاريخ صالح للسعر",
    TextKey.FEED_NO_SOURCE to "مفيش مصدر مكتوب للسعر",
    TextKey.FEED_UNKNOWN_SOURCE to "مصدر غير معروف",
    TextKey.FEED_NO_REASON to "سبب غير مكتوب",
    TextKey.FEED_SUMMARY to "{0} سعر محدَّث يوم {1}",
    TextKey.FEED_SUMMARY_WITH_MISSING to "{0}، و{1} مصدر مجابش سعر",
    TextKey.JOIN_AND to " و",
    TextKey.GROUP_FOOD to "الأكل والشرب",
    TextKey.GROUP_HOME to "البيت والالتزامات",
    TextKey.GROUP_TRANSPORT to "التنقل",
    TextKey.GROUP_PERSONAL to "الحياة الشخصية",
    TextKey.GROUP_SAVING to "الادخار والاستثمار",
    TextKey.GROUP_MOVEMENT to "حركة فلوس مش مصروف",
    TextKey.REQ_HAS_CAR to "لو عنده سيارة",
    TextKey.REQ_DEPENDENTS to "لو بيعول زوجة أو أولاد",
    TextKey.REQ_RENTER to "لو ساكن بإيجار",
    TextKey.REQ_DOMESTIC_WORKER to "لو عنده عمالة منزلية",
    TextKey.REQ_BUSINESS to "لو عنده شغل خاص",
    TextKey.DIFF_DATE to "التاريخ",
    TextKey.DIFF_AMOUNT to "المبلغ",
    TextKey.DIFF_DIRECTION to "اتجاه الحركة",
    TextKey.DIFF_MERCHANT to "اسم التاجر",
    TextKey.DEDUPE_SMS_SIMILAR to "فيه عملية بنفس اليوم والمبلغ والاتجاه في نفس المحفظة، وأحد المصدرين رسالة بنك. قد تكون نفس العملية باسم مختلف؛ غير مختارة للإضافة حتى تراجعها.",
    TextKey.DEDUPE_SAME_REFERENCE to "نفس المرجع «{0}» ونفس التفاصيل — العملية دي متسجلة قبل كده",
    TextKey.DEDUPE_REFERENCE_CONFLICT to "نفس المرجع «{0}» بس {1} مختلف. مش هنكتب فوق القديم من غير قرارك.",
    TextKey.DEDUPE_SAME_STATEMENT_LINE to "نفس سطر الكشف: نفس اليوم والمبلغ والاتجاه والرصيد بعد العملية في نفس الحساب — متسجلة قبل كده حتى لو الاسم مقروء بشكل مختلف",
    TextKey.DEDUPE_NEW_REFERENCE to "مرجع جديد مش موجود قبل كده",
    TextKey.DEDUPE_SIMILAR_NO_REFERENCE to "نفس التاجر والمبلغ والتاريخ والاتجاه، ومفيش مرجع بنكي يأكد. ممكن تكون نفس العملية وممكن تكون عملية تانية حقيقية — محتاجة قرارك.",
    TextKey.DEDUPE_NEW to "عملية جديدة، مفيش ما يشبهها",
    TextKey.NOTICE_SPENT_OVER to "صرفت {0} من {1} — زيادة {2}",
    TextKey.NOTICE_SPENT_LEFT to "صرفت {0} من {1} — فاضل {2}",
    TextKey.NOTICE_BUDGET_EXCEEDED to "عدّيت الميزانية",
    TextKey.NOTICE_BUDGET_THRESHOLD to "وصلت {0}٪ من الميزانية",
    TextKey.NOTICE_CATEGORY_EXCEEDED to "عدّيت سقف «{0}»",
    TextKey.NOTICE_CATEGORY_THRESHOLD to "«{0}» وصل {1}٪",
    TextKey.LEDGER_ALLOCATIONS_EXCEED to "مجموع التخصيصات ({0}) أكبر من قيمة العملية ({1})",
    TextKey.LEDGER_SETTLEMENTS_EXCEED to "تسويات الالتزام {0} تجاوزت أصله — رصيد سالب صامت ممنوع",
    TextKey.SETTLEMENT_AMOUNT_POSITIVE to "مبلغ التسوية لازم يكون أكبر من صفر",
    TextKey.SETTLEMENT_FULLY_PAID to "الالتزام ده متسدد بالكامل. مفيش متبقي يتسوّى",
    TextKey.OBLIGATION_CUSTODY to "الأمانة",
    TextKey.OBLIGATION_LOAN to "الدين",
    TextKey.OBLIGATION_RECEIVABLE to "المستحق",
    TextKey.SETTLEMENT_OVER_REMAINING to "المبلغ أكبر من المتبقي. {0} المتبقي {1} والمبلغ اللي كتبته {2}. تقدر تسوّي {1} وتسجّل الباقي {3} كأمانة مستقلة بإجراء صريح.",
    TextKey.LEDGER_FEE_NEGATIVE to "الرسوم لا تكون سالبة",
    TextKey.LEDGER_FEE_OVER_GROSS to "الرسوم ({0}) أكبر من الإجمالي المخصوم ({1})",
    TextKey.SCHEMA_UNKNOWN_COLUMNS to "الأعمدة مش متطابقة مع أي مخطط معروف.\nالموجود: {0}\nالمتوقع إما: {1}\nأو: {2}\nلو الملف بأعمدة مختلفة، محتاج تعيين أعمدة يدوي — مش هنخمّن أعمدة مالية.",
    TextKey.ROW_DATE_INVALID to "التاريخ «{0}» مش صالح. المتوقع YYYY-MM-DD بتاريخ موجود فعلًا",
    TextKey.ROW_AMOUNT_INVALID to "المبلغ «{0}» مش رقم صالح",
    TextKey.ROW_AMOUNT_NEGATIVE to "المبلغ «{0}» سالب. الاتجاه بيتحدد من عمود type",
    TextKey.ROW_AMOUNT_ZERO to "المبلغ صفر — العملية دي مالهاش أثر مالي",
    TextKey.ROW_TYPE_UNKNOWN to "نوع العملية «{0}» مش معروف. المتوقع expense أو income أو transfer",
    TextKey.ROW_LEGACY_DATE_INVALID to "التاريخ «{0}» مش صالح. المتوقع YYYY/MM/DD بتاريخ موجود",
    TextKey.ROW_DEBIT_INVALID to "قيمة المدين «{0}» مش رقم صالح",
    TextKey.ROW_CREDIT_INVALID to "قيمة الدائن «{0}» مش رقم صالح",
    TextKey.ROW_DEBIT_CREDIT_NEGATIVE to "المدين والدائن لازم يكونوا موجبين",
    TextKey.ROW_DEBIT_AND_CREDIT to "الصف فيه مدين ودائن في نفس الوقت — مش واضح اتجاه الحركة",
    TextKey.ROW_NO_DEBIT_NO_CREDIT to "الصف مفيهوش مدين ولا دائن — مالهوش أثر مالي",
    TextKey.CSV_TOO_LARGE to "الملف أكبر من الحد المسموح (12 ميجابايت)",
    TextKey.CSV_TOO_MANY_ROWS to "الملف فيه أكتر من {0} صف",
    TextKey.CSV_CELL_TOO_LONG to "خانة في السطر {0} أطول من الحد المسموح",
    TextKey.CSV_UNCLOSED_QUOTE to "اقتباس مفتوح ولم يُغلق — الملف ناقص أو تالف عند السطر {0}",
    TextKey.CSV_EMPTY to "الملف فاضي",
    TextKey.PERIOD_BAD_MONTH to "شهر غير صالح: {0}",
    TextKey.PERIOD_BAD_DATE_FORMAT to "صيغة التاريخ غير صالحة: {0}",
    TextKey.PERIOD_BAD_MONTH_IN to "شهر غير صالح في: {0}",
    TextKey.PERIOD_BAD_DAY to "يوم غير موجود: {0} ({1} فيه {2} يوم)",
    TextKey.PERIOD_BAD_PAYDAY to "يوم الراتب لازم يكون بين 1 و31، مش {0}",
    TextKey.PROJECT_NAME_LENGTH to "اكتب اسم المشروع بحد أقصى {0} حرف.",
    TextKey.PROJECT_NAME_DUPLICATE to "فيه مشروع بنفس الاسم.",
    TextKey.PROJECT_RULE_TEXT_LENGTH to "اكتب نص القاعدة من حرفين لـ {0} حرف.",
    TextKey.PROJECT_RULE_DIRECTION to "الاتجاه مش معروف.",
    TextKey.PROFILE_NAME_TOO_LONG to "الاسم أطول من {0} حرف",
    TextKey.PROFILE_SALARY_INVALID to "المرتب لازم يكون مبلغ صحيح مش سالب",
    TextKey.PROFILE_PAYDAY_RANGE to "يوم الراتب لازم يكون من 1 لـ 31",
    TextKey.PROFILE_GENDER to "اختار ذكر أو أنثى، أو سيبها فاضية",
    TextKey.PROFILE_DEPENDENTS to "اختار الزوج أو الزوجة أو الأولاد أو الأهل، أو سيبها فاضية",
    TextKey.RECURRING_DETECTED to "٣ دورات متتابعة لخدمة مناسبة، بمبلغ متقارب ±٥٪ وموعد متقارب ±٧ أيام.",
    TextKey.RECURRING_NAME to "اكتب اسم الخدمة، بحد أقصى ١٢٠ حرف.",
    TextKey.RECURRING_CYCLE to "اختار دورة شهرية أو كل ٣ شهور أو سنوية.",
    TextKey.RECURRING_KIND to "نوع الالتزام غير صالح.",
    TextKey.RECURRING_AMOUNT to "قيمة الدورة لازم تكون أكبر من صفر.",
    TextKey.RECURRING_LINK to "ربط الخدمة غير صالح.",
    TextKey.CATEGORY_NOT_FOUND to "التصنيف مش موجود.",
    TextKey.CATEGORY_NAME_LENGTH to "اكتب اسم التصنيف بحد أقصى ٨٠ حرف.",
    TextKey.CATEGORY_NAME_DUPLICATE to "فيه تصنيف بنفس الاسم.",
    TextKey.CATEGORY_ICON_REQUIRED to "اختار رمز من القايمة.",
    TextKey.CATEGORY_SELF_PARENT to "التصنيف مينفعش يبقى فرعي تحت نفسه.",
    TextKey.CATEGORY_PARENT_MISSING to "التصنيف الأساسي اللي اخترته مش موجود.",
    TextKey.CATEGORY_PARENT_NOT_MAIN to "اختار تصنيف أساسي، مش فرعي.",
    TextKey.CATEGORY_HAS_SUBS to "التصنيف ده تحته فرعيات، فمينفعش يتنقل تحت تصنيف تاني.",
    TextKey.CATEGORY_GROUP_UNKNOWN to "المجموعة اللي اخترتها مش معروفة.",
    TextKey.CATEGORY_COLOR_REQUIRED to "اختار لون من القايمة.",
    TextKey.GROUP_UNGROUPED to "التصنيفات",
    TextKey.GROUP_NO_GROUP to "بلا مجموعة",
    TextKey.GROUP_HIDDEN to "المخفية",
    TextKey.SETTLEMENT_OBLIGATION_MISSING to "الالتزام ده مش موجود للشخص ده",
    TextKey.SETTLEMENT_AMOUNT_HALALAS to "مبلغ التسوية لازم يكون عدد صحيح بالهللة وأكبر من صفر",
    TextKey.SETTLEMENT_REQUEST_CONFLICT to "الطلب ده اتحفظ قبل كده ببيانات مختلفة. راجع التسوية المسجلة",
    TextKey.SETTLEMENT_REJECTED to "التسوية مرفوضة",
)
