package app.masroufy.core

/**
 * «ملفك» (`Account` — منطقة «المزيد»): من النموذج التفاعلي بالحرف، إلا:
 * - نص الخروج من غير «تُمسح النسخة التي على هذا الجوال» — الخروج في كوتلن ما بيمسحش نسخة الجهاز (CLAUDE.md #15).
 * - رسالة الغلط: «تحقق من الاتصال ثم أعد المحاولة» بدل «سنعيد المحاولة تلقائيًا» (مفيش إعادة لوحدها في الشاشة).
 * - سطور «غير متاح بعد» للي مالوش منطق (نطاق الراتب · بداية الشهر من الشهر القادم بس) — كتابة Claude.
 */
internal val MSA_MORE_ACCOUNT_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ACC_TITLE to "ملفك",
    UiKey.ACC_ERR_TITLE to "تعذّر حفظ آخر تعديل",
    UiKey.ACC_ERR_BODY to "تحقق من الاتصال ثم أعد المحاولة.",
    UiKey.ACC_NO_NAME to "بلا اسم",
    UiKey.ACC_PERCENT_LABEL to "اكتمال ملفك",
    UiKey.ACC_LOOK_SOON to "الكاركتر النهائي قيد التصميم.",
    UiKey.ACC_GROUP_ABOUT to "عنك",
    UiKey.ACC_NAME to "الاسم",
    UiKey.ACC_GENDER to "النوع",
    UiKey.ACC_DEPENDENTS to "من تعول",
    UiKey.ACC_GROUP_INCOME to "الدخل",
    UiKey.ACC_SALARY to "الراتب",
    UiKey.ACC_SALARY_HINT to "نطاق تقريبي يكفي",
    UiKey.ACC_PAYDAY to "يوم الراتب",
    UiKey.ACC_DAY_N to "يوم {0}",
    UiKey.ACC_PAYDAY_HINT to "واحد للحساب كله، ومنه يبدأ شهرك المالي",
    UiKey.ACC_GROUP_LIFE to "حياتك",
    UiKey.ACC_LIFE_NOTE to "بناءً عليها تظهر لك التصنيفات التي تخصك فقط.",
    UiKey.ACC_CAR to "هل لديك سيارة؟",
    UiKey.ACC_RENTER to "هل تسكن بالإيجار؟",
    UiKey.ACC_MAID to "هل لديك عمالة منزلية؟",
    UiKey.ACC_BUSINESS to "هل لديك عمل خاص؟",
    UiKey.ACC_GROUP_BUDGET to "الميزانية",
    UiKey.ACC_DUES_TITLE to "المستحقات ضمن حد الميزانية",
    UiKey.ACC_DUES_UNSET to "لم تحدده بعد، فتُحسب احتياطًا. الأقساط في مصروف الشهر دائمًا.",
    UiKey.ACC_DUES_ON to "أقساط الجمعيات والتمويل تُحسب من حد الميزانية.",
    UiKey.ACC_DUES_OFF to "خارج الحد، وتبقى في مصروف الشهر.",
    UiKey.ACC_GROUP_ACCOUNT to "الحساب",
    UiKey.ACC_EMAIL to "البريد الإلكتروني",
    UiKey.ACC_EMAIL_HINT to "للعرض فقط",
    UiKey.ACC_SIGN_OUT to "تسجيل الخروج",
    UiKey.ACC_NOT_ANSWERED to "لم تُجب بعد",
    UiKey.ACC_GENDER_MALE to "ذكر",
    UiKey.ACC_GENDER_FEMALE to "أنثى",
    UiKey.ACC_DEP_SPOUSE to "الزوج أو الزوجة",
    UiKey.ACC_DEP_CHILDREN to "الأولاد",
    UiKey.ACC_DEP_PARENTS to "الأهل",
    UiKey.ACC_DEP_NONE to "لا أحد",
    UiKey.ACC_CAR_WITH_WORK to "{0} · {1}",
    UiKey.ACC_CAR_TO_WORK to "أذهب بها للدوام",
    UiKey.ACC_CAR_NOT_WORK to "ليست للدوام",
    UiKey.ACC_SAL_SA_R1 to "أقل من ٥ آلاف",
    UiKey.ACC_SAL_SA_R2 to "٥–١٠ آلاف",
    UiKey.ACC_SAL_SA_R3 to "١٠–٢٠ ألفًا",
    UiKey.ACC_SAL_SA_R4 to "أكثر من ٢٠ ألفًا",
    UiKey.ACC_SAL_EG_R1 to "أقل من ١٥ ألفًا",
    UiKey.ACC_SAL_EG_R2 to "١٥–٣٠ ألفًا",
    UiKey.ACC_SAL_EG_R3 to "٣٠–٦٠ ألفًا",
    UiKey.ACC_SAL_EG_R4 to "أكثر من ٦٠ ألفًا",
    UiKey.ACC_SAL_SKIP to "أفضّل ألا أقول",
    UiKey.ACC_SALARY_TITLE to "الراتب الشهري ({0})",
    UiKey.ACC_SALARY_BODY to "يكفي نطاق تقريبي، ولن نطلب رقمًا.",
    UiKey.ACC_SALARY_NOT_YET to "حفظ النطاق غير متاح بعد: ملفك يحفظ الراتب رقمًا فقط حتى الآن.",
    UiKey.ACC_PAYDAY_TITLE to "في أي يوم ينزل الراتب؟",
    UiKey.ACC_PAYDAY_BODY to "يبدأ شهرك المالي من هذا اليوم في البلدين.",
    UiKey.ACC_PAYDAY_NOTE to "الأيام ٢٩–٣١ تُحسب آخر يوم في الشهر القصير.",
    UiKey.ACC_PAYDAY_NEXT_ONLY to "التطبيق من الشهر القادم فقط غير متاح بعد: الحفظ الآن يغيّر بداية كل الشهور.",
    UiKey.ACC_PAYDAY_SAVED to "أصبح شهرك المالي يبدأ يوم {0}",
    UiKey.ACC_NAME_BODY to "اختياري. يظهر في التحية فقط.",
    UiKey.ACC_GENDER_BODY to "اختر ذكرًا أو أنثى، أو اتركه فارغًا",
    UiKey.ACC_DEP_TITLE to "من تعول؟",
    UiKey.ACC_DEP_BODY to "اختر ما ينطبق، أو «لا أحد».",
    UiKey.ACC_SAVE_WITH to "حفظ: {0}",
    UiKey.ACC_CAR_TO_WORK_Q to "هل تذهب بها إلى الدوام؟",
    UiKey.ACC_CAR_TO_WORK_BODY to "لنحسب مصاريف السيارة بدقة. لن نسأل مجددًا إلا إن تغيّرت سيارتك.",
    UiKey.ACC_CAR_TO_WORK_SAVED to "سُجّل: تذهب بها إلى الدوام",
    UiKey.ACC_SIGN_OUT_Q to "تسجيل الخروج؟",
    UiKey.ACC_SIGN_OUT_BODY to "بياناتك محفوظة في حسابك وتعود كاملة عند الدخول مجددًا.",
    UiKey.ACC_SIGN_OUT_GO to "خروج",
)

internal val EGYPTIAN_MORE_ACCOUNT_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ACC_TITLE to "ملفك",
    UiKey.ACC_ERR_TITLE to "ما اتحفظش آخر تعديل",
    UiKey.ACC_ERR_BODY to "اتأكد من النت وجرّب تاني.",
    UiKey.ACC_NO_NAME to "من غير اسم",
    UiKey.ACC_PERCENT_LABEL to "اكتمال ملفك",
    UiKey.ACC_LOOK_SOON to "الكاركتر النهائي لسه بيتصمم.",
    UiKey.ACC_GROUP_ABOUT to "عنك",
    UiKey.ACC_NAME to "الاسم",
    UiKey.ACC_GENDER to "النوع",
    UiKey.ACC_DEPENDENTS to "بتعول مين",
    UiKey.ACC_GROUP_INCOME to "الدخل",
    UiKey.ACC_SALARY to "المرتب",
    UiKey.ACC_SALARY_HINT to "نطاق تقريبي كفاية",
    UiKey.ACC_PAYDAY to "يوم المرتب",
    UiKey.ACC_DAY_N to "يوم {0}",
    UiKey.ACC_PAYDAY_HINT to "واحد للحساب كله، ومنه بيبدأ شهرك المالي",
    UiKey.ACC_GROUP_LIFE to "حياتك",
    UiKey.ACC_LIFE_NOTE to "على أساسها بتظهرلك التصنيفات اللي تخصك بس.",
    UiKey.ACC_CAR to "عندك عربية؟",
    UiKey.ACC_RENTER to "ساكن بإيجار؟",
    UiKey.ACC_MAID to "عندك عمالة منزلية؟",
    UiKey.ACC_BUSINESS to "عندك شغل خاص؟",
    UiKey.ACC_GROUP_BUDGET to "الميزانية",
    UiKey.ACC_DUES_TITLE to "المستحقات جوه حد الميزانية",
    UiKey.ACC_DUES_UNSET to "لسه ما حددتش، فبتتحسب احتياطًا. الأقساط في مصروف الشهر دايمًا.",
    UiKey.ACC_DUES_ON to "أقساط الجمعيات والتمويل بتاكل من حد الميزانية.",
    UiKey.ACC_DUES_OFF to "برا الحد، بس فاضلة في مصروف الشهر.",
    UiKey.ACC_GROUP_ACCOUNT to "الحساب",
    UiKey.ACC_EMAIL to "الإيميل",
    UiKey.ACC_EMAIL_HINT to "للعرض بس",
    UiKey.ACC_SIGN_OUT to "اخرج من الحساب",
    UiKey.ACC_NOT_ANSWERED to "لسه ما جاوبتش",
    UiKey.ACC_GENDER_MALE to "ذكر",
    UiKey.ACC_GENDER_FEMALE to "أنثى",
    UiKey.ACC_DEP_SPOUSE to "الزوج أو الزوجة",
    UiKey.ACC_DEP_CHILDREN to "العيال",
    UiKey.ACC_DEP_PARENTS to "الأهل",
    UiKey.ACC_DEP_NONE to "محدش",
    UiKey.ACC_CAR_WITH_WORK to "{0} · {1}",
    UiKey.ACC_CAR_TO_WORK to "بروح بيها الشغل",
    UiKey.ACC_CAR_NOT_WORK to "مش للشغل",
    UiKey.ACC_SAL_SA_R1 to "أقل من ٥ آلاف",
    UiKey.ACC_SAL_SA_R2 to "٥–١٠ آلاف",
    UiKey.ACC_SAL_SA_R3 to "١٠–٢٠ ألف",
    UiKey.ACC_SAL_SA_R4 to "أكتر من ٢٠ ألف",
    UiKey.ACC_SAL_EG_R1 to "أقل من ١٥ ألف",
    UiKey.ACC_SAL_EG_R2 to "١٥–٣٠ ألف",
    UiKey.ACC_SAL_EG_R3 to "٣٠–٦٠ ألف",
    UiKey.ACC_SAL_EG_R4 to "أكتر من ٦٠ ألف",
    UiKey.ACC_SAL_SKIP to "مش عايز أقول",
    UiKey.ACC_SALARY_TITLE to "المرتب في الشهر ({0})",
    UiKey.ACC_SALARY_BODY to "نطاق تقريبي كفاية، ومش هنطلب رقم.",
    UiKey.ACC_SALARY_NOT_YET to "حفظ النطاق لسه مش متاح: ملفك لسه بيحفظ المرتب رقم بس.",
    UiKey.ACC_PAYDAY_TITLE to "المرتب بينزل يوم كام؟",
    UiKey.ACC_PAYDAY_BODY to "شهرك المالي بيبدأ من اليوم ده في البلدين.",
    UiKey.ACC_PAYDAY_NOTE to "الأيام ٢٩–٣١ بتتحسب آخر يوم في الشهر القصير.",
    UiKey.ACC_PAYDAY_NEXT_ONLY to "التغيير من الشهر الجاي بس لسه مش متاح: الحفظ دلوقتي بيغيّر بداية كل الشهور.",
    UiKey.ACC_PAYDAY_SAVED to "شهرك المالي بقى يبدأ يوم {0}",
    UiKey.ACC_NAME_BODY to "اختياري. بيظهر في التحية بس.",
    UiKey.ACC_GENDER_BODY to "اختار ذكر أو أنثى، أو سيبها فاضية",
    UiKey.ACC_DEP_TITLE to "بتعول مين؟",
    UiKey.ACC_DEP_BODY to "اختار اللي ينطبق، أو «محدش».",
    UiKey.ACC_SAVE_WITH to "احفظ: {0}",
    UiKey.ACC_CAR_TO_WORK_Q to "هتروح بيها الشغل؟",
    UiKey.ACC_CAR_TO_WORK_BODY to "عشان نحسب مصاريف العربية صح. مش هنسأل تاني غير لو غيّرت عربيتك.",
    UiKey.ACC_CAR_TO_WORK_SAVED to "اتسجل: بتروح بيها الشغل",
    UiKey.ACC_SIGN_OUT_Q to "تخرج من الحساب؟",
    UiKey.ACC_SIGN_OUT_BODY to "بياناتك محفوظة في حسابك وبترجع كاملة لما تدخل تاني.",
    UiKey.ACC_SIGN_OUT_GO to "اخرج",
)

internal val ENGLISH_MORE_ACCOUNT_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ACC_TITLE to "Your profile",
    UiKey.ACC_ERR_TITLE to "Your last change wasn't saved",
    UiKey.ACC_ERR_BODY to "Check your connection and try again.",
    UiKey.ACC_NO_NAME to "No name",
    UiKey.ACC_PERCENT_LABEL to "Profile completion",
    UiKey.ACC_LOOK_SOON to "The final character is still being designed.",
    UiKey.ACC_GROUP_ABOUT to "About you",
    UiKey.ACC_NAME to "Name",
    UiKey.ACC_GENDER to "Gender",
    UiKey.ACC_DEPENDENTS to "Who you support",
    UiKey.ACC_GROUP_INCOME to "Income",
    UiKey.ACC_SALARY to "Salary",
    UiKey.ACC_SALARY_HINT to "A rough range is enough",
    UiKey.ACC_PAYDAY to "Payday",
    UiKey.ACC_DAY_N to "Day {0}",
    UiKey.ACC_PAYDAY_HINT to "One for the whole account; your financial month starts on it",
    UiKey.ACC_GROUP_LIFE to "Your life",
    UiKey.ACC_LIFE_NOTE to "Based on these, you only see the categories that fit you.",
    UiKey.ACC_CAR to "Do you have a car?",
    UiKey.ACC_RENTER to "Do you rent your home?",
    UiKey.ACC_MAID to "Do you have domestic help?",
    UiKey.ACC_BUSINESS to "Do you have your own business?",
    UiKey.ACC_GROUP_BUDGET to "Budget",
    UiKey.ACC_DUES_TITLE to "Dues count toward the budget limit",
    UiKey.ACC_DUES_UNSET to "Not set yet, so they count to be safe. Installments are always in the month's spending.",
    UiKey.ACC_DUES_ON to "Rosca and financing installments count toward the budget limit.",
    UiKey.ACC_DUES_OFF to "Outside the limit, but still in the month's spending.",
    UiKey.ACC_GROUP_ACCOUNT to "Account",
    UiKey.ACC_EMAIL to "Email",
    UiKey.ACC_EMAIL_HINT to "For display only",
    UiKey.ACC_SIGN_OUT to "Sign out",
    UiKey.ACC_NOT_ANSWERED to "Not answered yet",
    UiKey.ACC_GENDER_MALE to "Male",
    UiKey.ACC_GENDER_FEMALE to "Female",
    UiKey.ACC_DEP_SPOUSE to "Spouse",
    UiKey.ACC_DEP_CHILDREN to "Children",
    UiKey.ACC_DEP_PARENTS to "Parents",
    UiKey.ACC_DEP_NONE to "No one",
    UiKey.ACC_CAR_WITH_WORK to "{0} · {1}",
    UiKey.ACC_CAR_TO_WORK to "I drive it to work",
    UiKey.ACC_CAR_NOT_WORK to "Not for work",
    UiKey.ACC_SAL_SA_R1 to "Under 5,000",
    UiKey.ACC_SAL_SA_R2 to "5,000–10,000",
    UiKey.ACC_SAL_SA_R3 to "10,000–20,000",
    UiKey.ACC_SAL_SA_R4 to "Over 20,000",
    UiKey.ACC_SAL_EG_R1 to "Under 15,000",
    UiKey.ACC_SAL_EG_R2 to "15,000–30,000",
    UiKey.ACC_SAL_EG_R3 to "30,000–60,000",
    UiKey.ACC_SAL_EG_R4 to "Over 60,000",
    UiKey.ACC_SAL_SKIP to "I'd rather not say",
    UiKey.ACC_SALARY_TITLE to "Monthly salary ({0})",
    UiKey.ACC_SALARY_BODY to "A rough range is enough; we won't ask for a number.",
    UiKey.ACC_SALARY_NOT_YET to "Saving a range isn't available yet: your profile only stores the salary as a number so far.",
    UiKey.ACC_PAYDAY_TITLE to "What day does your salary arrive?",
    UiKey.ACC_PAYDAY_BODY to "Your financial month starts on this day in both countries.",
    UiKey.ACC_PAYDAY_NOTE to "Days 29–31 count as the last day of a short month.",
    UiKey.ACC_PAYDAY_NEXT_ONLY to "Applying from next month only isn't available yet: saving now moves the start of every month.",
    UiKey.ACC_PAYDAY_SAVED to "Your financial month now starts on day {0}",
    UiKey.ACC_NAME_BODY to "Optional. Only shown in the greeting.",
    UiKey.ACC_GENDER_BODY to "Choose male or female, or leave it empty",
    UiKey.ACC_DEP_TITLE to "Who do you support?",
    UiKey.ACC_DEP_BODY to "Pick what applies, or “No one”.",
    UiKey.ACC_SAVE_WITH to "Save: {0}",
    UiKey.ACC_CAR_TO_WORK_Q to "Do you drive it to work?",
    UiKey.ACC_CAR_TO_WORK_BODY to "So we count car costs right. We won't ask again unless your car changes.",
    UiKey.ACC_CAR_TO_WORK_SAVED to "Saved: you drive it to work",
    UiKey.ACC_SIGN_OUT_Q to "Sign out?",
    UiKey.ACC_SIGN_OUT_BODY to "Your data stays in your account and comes back in full when you sign in again.",
    UiKey.ACC_SIGN_OUT_GO to "Sign out",
)
