package app.masroufy.core

/**
 * نصوص منطقة «الرئيسية» — التقويم (`Calendar` — رد المالك آخر §76: ملخص أحداث + «حدث جديد» + الشبكة). مضمومة في `TextsAreaHome.kt`.
 * العدّ بقواعد العربي: واحد · اتنين · ٣–١٠ جمع · ١١+ مفرد منصوب.
 */
internal val MSA_AREA_HOME_CALENDAR_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.CALENDAR_TITLE to "التقويم",
    TextKey.CALENDAR_UPCOMING to "الأحداث القادمة",
    TextKey.CALENDAR_ALL to "كل القادم ({0})",
    TextKey.CALENDAR_LESS to "عرض أقل",
    TextKey.CALENDAR_ADD_EVENT to "حدث جديد",
    TextKey.CALENDAR_EMPTY_TITLE to "لا أحداث قادمة",
    TextKey.CALENDAR_EMPTY_BODY to "أضف حدثًا، أو تظهر هنا تلقائيًا مواعيد اشتراكاتك وأقساطك وجمعياتك ومناسبات أشخاصك.",
    TextKey.CALENDAR_PICK_DAY to "اضغط يومًا لترى مواعيده",
    TextKey.CALENDAR_DAY_TITLE to "يوم {0}",
    TextKey.CALENDAR_CLEAR to "إلغاء الاختيار",
    TextKey.CALENDAR_DAY_EMPTY to "لا مواعيد في هذا اليوم — يمكنك إضافة حدث فيه من الزر أعلاه.",
    TextKey.CALENDAR_SUB to "{0}، {1}",
    TextKey.CALENDAR_WITH_AMOUNT to "، {0}",
    TextKey.CALENDAR_LATE to "فات موعده",
    TextKey.CALENDAR_PASSED to "مضى",
    TextKey.CALENDAR_INCOMING to "ستستلمه",
    TextKey.CALENDAR_NO_AMOUNT to "بلا مبلغ",
    TextKey.CALENDAR_HELD to "محجوز ✓",
    TextKey.CALENDAR_NOT_HELD to "غير محجوز",
    TextKey.CALENDAR_WHEN_TODAY to "اليوم",
    TextKey.CALENDAR_WHEN_TOMORROW to "غدًا",
    TextKey.CALENDAR_WHEN_TWO to "بعد يومين",
    TextKey.CALENDAR_WHEN_FEW to "بعد {0} أيام",
    TextKey.CALENDAR_WHEN_MANY to "بعد {0} يومًا",
    TextKey.CALENDAR_AGO_ONE to "أمس",
    TextKey.CALENDAR_AGO_TWO to "منذ يومين",
    TextKey.CALENDAR_AGO_FEW to "منذ {0} أيام",
    TextKey.CALENDAR_AGO_MANY to "منذ {0} يومًا",
    TextKey.CALENDAR_COUNT_ONE to "موعد واحد",
    TextKey.CALENDAR_COUNT_TWO to "موعدان",
    TextKey.CALENDAR_COUNT_FEW to "{0} مواعيد",
    TextKey.CALENDAR_COUNT_MANY to "{0} موعدًا",
    TextKey.CALENDAR_SMART_NEAREST to "الأقرب: {0} {1}",
    TextKey.CALENDAR_SMART_WINDOW to "في الـ٣٠ يومًا القادمة {0}",
    TextKey.CALENDAR_SMART_WINDOW_OPEN to "في الـ٣٠ يومًا القادمة {0}، منها {1} غير محجوزة",
    TextKey.CALENDAR_SMART_BEFORE_PAY to "{0} قبل الراتب بأيام",
    TextKey.CALENDAR_SMART_BEFORE_PAY_ONE to "{0} قبل الراتب بيوم",
    TextKey.CALENDAR_SMART_JOIN to ". ",
    TextKey.CALENDAR_SMART_END to ".",
    TextKey.CALENDAR_TYPE_SUB to "اشتراك",
    TextKey.CALENDAR_TYPE_INST to "قسط",
    TextKey.CALENDAR_TYPE_ROSCA to "جمعية",
    TextKey.CALENDAR_TYPE_DEBT to "دين",
    TextKey.CALENDAR_TYPE_EVENT to "حدث",
    TextKey.CALENDAR_TYPE_OCCASION to "مناسبة",
    TextKey.CALENDAR_TYPE_PAY to "دخل متوقع",
    TextKey.CALENDAR_TYPE_ZAKAT to "الزكاة",
)

internal val EGYPTIAN_AREA_HOME_CALENDAR_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.CALENDAR_TITLE to "التقويم",
    TextKey.CALENDAR_UPCOMING to "الأحداث الجاية",
    TextKey.CALENDAR_ALL to "كل الجاي ({0})",
    TextKey.CALENDAR_LESS to "أقل",
    TextKey.CALENDAR_ADD_EVENT to "حدث جديد",
    TextKey.CALENDAR_EMPTY_TITLE to "مفيش أحداث جاية",
    TextKey.CALENDAR_EMPTY_BODY to "ضيف حدث، أو هتظهر هنا لوحدها مواعيد اشتراكاتك وأقساطك وجمعياتك ومناسبات أشخاصك.",
    TextKey.CALENDAR_PICK_DAY to "دوس على يوم تشوف مواعيده",
    TextKey.CALENDAR_DAY_TITLE to "يوم {0}",
    TextKey.CALENDAR_CLEAR to "إلغاء الاختيار",
    TextKey.CALENDAR_DAY_EMPTY to "مفيش مواعيد في اليوم ده — تقدر تضيف حدث فيه من الزرار اللي فوق.",
    TextKey.CALENDAR_SUB to "{0}، {1}",
    TextKey.CALENDAR_WITH_AMOUNT to "، {0}",
    TextKey.CALENDAR_LATE to "فات ميعاده",
    TextKey.CALENDAR_PASSED to "عدّى",
    TextKey.CALENDAR_INCOMING to "هتستلمه",
    TextKey.CALENDAR_NO_AMOUNT to "من غير مبلغ",
    TextKey.CALENDAR_HELD to "محجوز ✓",
    TextKey.CALENDAR_NOT_HELD to "مش محجوز",
    TextKey.CALENDAR_WHEN_TODAY to "النهارده",
    TextKey.CALENDAR_WHEN_TOMORROW to "بكرة",
    TextKey.CALENDAR_WHEN_TWO to "بعد يومين",
    TextKey.CALENDAR_WHEN_FEW to "بعد {0} أيام",
    TextKey.CALENDAR_WHEN_MANY to "بعد {0} يوم",
    TextKey.CALENDAR_AGO_ONE to "امبارح",
    TextKey.CALENDAR_AGO_TWO to "من يومين",
    TextKey.CALENDAR_AGO_FEW to "من {0} أيام",
    TextKey.CALENDAR_AGO_MANY to "من {0} يوم",
    TextKey.CALENDAR_COUNT_ONE to "ميعاد واحد",
    TextKey.CALENDAR_COUNT_TWO to "ميعادين",
    TextKey.CALENDAR_COUNT_FEW to "{0} مواعيد",
    TextKey.CALENDAR_COUNT_MANY to "{0} ميعاد",
    TextKey.CALENDAR_SMART_NEAREST to "الأقرب: {0} {1}",
    TextKey.CALENDAR_SMART_WINDOW to "في الـ٣٠ يوم الجايين {0}",
    TextKey.CALENDAR_SMART_WINDOW_OPEN to "في الـ٣٠ يوم الجايين {0}، منهم {1} مش محجوزين",
    TextKey.CALENDAR_SMART_BEFORE_PAY to "{0} قبل المرتب بكام يوم",
    TextKey.CALENDAR_SMART_BEFORE_PAY_ONE to "{0} قبل المرتب بيوم",
    TextKey.CALENDAR_SMART_JOIN to ". ",
    TextKey.CALENDAR_SMART_END to ".",
    TextKey.CALENDAR_TYPE_SUB to "اشتراك",
    TextKey.CALENDAR_TYPE_INST to "قسط",
    TextKey.CALENDAR_TYPE_ROSCA to "جمعية",
    TextKey.CALENDAR_TYPE_DEBT to "دين",
    TextKey.CALENDAR_TYPE_EVENT to "حدث",
    TextKey.CALENDAR_TYPE_OCCASION to "مناسبة",
    TextKey.CALENDAR_TYPE_PAY to "فلوس جاية",
    TextKey.CALENDAR_TYPE_ZAKAT to "الزكاة",
)

internal val ENGLISH_AREA_HOME_CALENDAR_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.CALENDAR_TITLE to "Calendar",
    TextKey.CALENDAR_UPCOMING to "Coming up",
    TextKey.CALENDAR_ALL to "Everything coming ({0})",
    TextKey.CALENDAR_LESS to "Show less",
    TextKey.CALENDAR_ADD_EVENT to "New event",
    TextKey.CALENDAR_EMPTY_TITLE to "Nothing coming up",
    TextKey.CALENDAR_EMPTY_BODY to "Add an event — your subscriptions, installments, savings circles and people's occasions also show up here automatically.",
    TextKey.CALENDAR_PICK_DAY to "Tap a day to see its dates",
    TextKey.CALENDAR_DAY_TITLE to "{0}",
    TextKey.CALENDAR_CLEAR to "Clear",
    TextKey.CALENDAR_DAY_EMPTY to "No dates on this day — you can add an event on it with the button above.",
    TextKey.CALENDAR_SUB to "{0}, {1}",
    TextKey.CALENDAR_WITH_AMOUNT to ", {0}",
    TextKey.CALENDAR_LATE to "Overdue",
    TextKey.CALENDAR_PASSED to "Passed",
    TextKey.CALENDAR_INCOMING to "Incoming",
    TextKey.CALENDAR_NO_AMOUNT to "No amount",
    TextKey.CALENDAR_HELD to "Reserved ✓",
    TextKey.CALENDAR_NOT_HELD to "Not reserved",
    TextKey.CALENDAR_WHEN_TODAY to "today",
    TextKey.CALENDAR_WHEN_TOMORROW to "tomorrow",
    TextKey.CALENDAR_WHEN_TWO to "in 2 days",
    TextKey.CALENDAR_WHEN_FEW to "in {0} days",
    TextKey.CALENDAR_WHEN_MANY to "in {0} days",
    TextKey.CALENDAR_AGO_ONE to "yesterday",
    TextKey.CALENDAR_AGO_TWO to "2 days ago",
    TextKey.CALENDAR_AGO_FEW to "{0} days ago",
    TextKey.CALENDAR_AGO_MANY to "{0} days ago",
    TextKey.CALENDAR_COUNT_ONE to "one date",
    TextKey.CALENDAR_COUNT_TWO to "two dates",
    TextKey.CALENDAR_COUNT_FEW to "{0} dates",
    TextKey.CALENDAR_COUNT_MANY to "{0} dates",
    TextKey.CALENDAR_SMART_NEAREST to "Next: {0} {1}",
    TextKey.CALENDAR_SMART_WINDOW to "{0} in the next 30 days",
    TextKey.CALENDAR_SMART_WINDOW_OPEN to "{0} in the next 30 days, {1} not reserved",
    TextKey.CALENDAR_SMART_BEFORE_PAY to "{0} a few days before payday",
    TextKey.CALENDAR_SMART_BEFORE_PAY_ONE to "{0} the day before payday",
    TextKey.CALENDAR_SMART_JOIN to ". ",
    TextKey.CALENDAR_SMART_END to ".",
    TextKey.CALENDAR_TYPE_SUB to "Subscription",
    TextKey.CALENDAR_TYPE_INST to "Installment",
    TextKey.CALENDAR_TYPE_ROSCA to "Savings circle",
    TextKey.CALENDAR_TYPE_DEBT to "Debt",
    TextKey.CALENDAR_TYPE_EVENT to "Event",
    TextKey.CALENDAR_TYPE_OCCASION to "Occasion",
    TextKey.CALENDAR_TYPE_PAY to "Expected income",
    TextKey.CALENDAR_TYPE_ZAKAT to "Zakat",
)
