package app.masroufy.core

/**
 * منطقة «المستحقات» — الجزء الثاني: «الأقساط» · «تفاصيل القسط» · «خطة جديدة/تعديل» · «الجمعيات» · «تفاصيل الجمعية» · معالج الجمعية ·
 * «الاشتراكات» · «تفاصيل الاشتراك». **الفصحى** (السعودية والافتراضي) من لوحات النموذج بنسخة `space = السعودية` (OVERRIDES §66).
 * المصري في `TextsAreaDuesPlansEgyptian.kt` والإنجليزي في `TextsAreaDuesPlansEnglish.kt` — بنفس المتغيرات. **ممنوع «·» جنب رقم عربي** ⇒ «،»؛
 * والأرقام الثابتة بالكلام («كل ثلاثة أشهر») عشان ما تخرجش عن طريقة كتابة الأرقام في التطبيق.
 */
internal val MSA_DUES_PLANS_TEXTS: Map<TextKey, String> = mapOf(
    // ── «الأقساط»
    TextKey.INSTALLMENTS_TITLE to "الأقساط",
    TextKey.INSTALLMENTS_NEW to "خطة جديدة",
    TextKey.INSTALLMENTS_LEFT to "المتبقي عليك في الأقساط",
    TextKey.INSTALLMENTS_NOTE to "يُحسب القسط كاملًا مصروفًا عند دفعه.",
    TextKey.INSTALLMENTS_RECEIVED to "المبلغ المستلم",
    TextKey.INSTALLMENTS_EMPTY_TITLE to "لا توجد أقساط",
    TextKey.INSTALLMENTS_EMPTY_BODY to "أضف قسطًا بنكيًا أو تقسيط مشتريات لنتابع مواعيده.",
    TextKey.INST_PLANS_ONE to "خطة واحدة",
    TextKey.INST_PLANS_TWO to "خطتان",
    TextKey.INST_PLANS_FEW to "{0} خطط",
    TextKey.INST_PLANS_MANY to "{0} خطة",
    TextKey.INST_KIND_FINANCING to "تمويل بنكي",
    TextKey.INST_KIND_PURCHASE to "تقسيط مشتريات",
    TextKey.INST_WITH_PROFIT to "بأرباح",
    TextKey.INST_PAID_OF to "دفعت {0} من {1}",
    TextKey.INST_NEXT to "القادم {0}",
    TextKey.INST_NEXT_N to "القادم {0}، القسط {1}",
    TextKey.INST_LATE_SINCE to "متأخر منذ {0}",
    TextKey.INST_DONE to "اكتملت الأقساط",
    TextKey.INST_NOT_LINKED to "لم يُربط بعد",

    // ── «تفاصيل القسط»
    TextKey.INST_EDIT to "عدّل الخطة",
    TextKey.INST_LEFT to "المتبقي عليك",
    TextKey.INST_DONE_HERO to "اكتملت الأقساط",
    TextKey.INST_LINE to "القسط {0} {1} · الإجمالي {2}",
    TextKey.INST_SCHEDULE to "الجدول",
    TextKey.INST_YEAR_LABEL to "السنة {0}، {1} – {2}",
    TextKey.INST_RANGE to "{0} – {1}",
    TextKey.INST_LEG_PAID to "مدفوع",
    TextKey.INST_LEG_LATE to "متأخر",
    TextKey.INST_LEG_NEXT to "القادم",
    TextKey.INST_LEG_UP to "متبقٍ",
    TextKey.INST_SCHED_ARIA to "مدفوع {0} من {1}، ومتأخر {2}",
    TextKey.INST_SCHED_ARIA_NOLATE to "مدفوع {0} من {1}",
    TextKey.INST_LAST_LINE to "آخر قسط {0}، {1} يوم {2}",
    TextKey.INST_RECV_HINT to "اربط عملية الإيداع ليظهر ما وصلك فعلًا.",
    TextKey.INST_RECV_NA to "لا ينطبق",
    TextKey.INST_RECV_NA_SUB to "تقسيط مشتريات — لا تستلم فيه مبلغًا.",
    TextKey.INST_UNLINK to "فك الربط",
    TextKey.INST_UNLINK_RECV_TITLE to "فك ربط مبلغ التمويل؟",
    TextKey.INST_PROFIT_TITLE to "أرباح التمويل",
    TextKey.INST_INFO_ONLY to "للعلم فقط",
    TextKey.INST_TOTAL_PAY to "إجمالي ما ستدفعه",
    TextKey.INST_PRINCIPAL to "المبلغ الأصلي",
    TextKey.INST_PROFIT to "أرباح التمويل",
    TextKey.INST_PROFIT_PAID to "المدفوع منها حتى الآن",
    TextKey.INST_PROFIT_LEFT to "المتبقي منها",
    TextKey.INST_PROFIT_PER to "في كل قسط تقريبًا",
    TextKey.INST_NOTE_FIN to "القسط كاملًا ({0}) يُحسب مصروفًا في «المستحقات ← تمويل»، فلا تُضاف الأرباح إلى المصروف مرة أخرى.",
    TextKey.INST_NOTE_BUY to "يُحسب القسط كاملًا مصروفًا في «المستحقات ← تقسيط مشتريات».",

    // ── «خطة جديدة» / «تعديل الخطة»
    TextKey.INST_EDIT_TITLE_NEW to "خطة جديدة",
    TextKey.INST_EDIT_TITLE to "تعديل الخطة",
    TextKey.INST_EDIT_SUB_NEW to "قسط بنكي أو تقسيط مشتريات",
    TextKey.INST_F_NAME to "الاسم",
    TextKey.INST_F_NAME_HINT to "مثلًا: قسط السيارة",
    TextKey.INST_F_PROVIDER to "الجهة",
    TextKey.INST_F_PROVIDER_HINT to "البنك أو المتجر",
    TextKey.INST_F_KIND to "النوع",
    TextKey.INST_KIND_FIN_HINT to "استلمت مبلغًا من الجهة",
    TextKey.INST_KIND_BUY_HINT to "اشتريت شيئًا بالتقسيط",
    TextKey.INST_F_CURRENCY to "العملة",
    TextKey.INST_F_CURRENCY_HINT to "عملة هذه المساحة",
    TextKey.INST_F_PRINCIPAL_FIN to "المبلغ الأصلي (الذي استلمته)",
    TextKey.INST_F_PRINCIPAL_BUY to "سعر الشيء",
    TextKey.INST_F_TOTAL to "إجمالي ما ستدفعه",
    TextKey.INST_F_INSTALLMENT to "القسط",
    TextKey.INST_F_CYCLE to "كل كم شهر",
    TextKey.INST_F_FIRST to "أول موعد",
    TextKey.INST_EDIT_NOTE_FIN to "القسط كاملًا يُحسب مصروفًا في «المستحقات ← تمويل»، والأرباح للعلم فقط.",
    TextKey.INST_EDIT_NOTE_BUY to "القسط كاملًا يُحسب مصروفًا في «المستحقات ← تقسيط مشتريات».",
    TextKey.INST_SAVE_NEW to "أضف الخطة",
    TextKey.INST_SAVE to "احفظ التعديلات",
    TextKey.INST_SAVE_ERR to "راجع الخانات المعلّمة بالأحمر.",
    TextKey.INST_SAVED_NEW to "أُضيفت «{0}» — تجدها في الأقساط",
    TextKey.INST_SAVED to "حُفظت التعديلات — الجدول يتحدّث من أول موعد",
    TextKey.INST_DONE_NEW to "إلى الأقساط",
    TextKey.INST_DONE_EDIT to "ارجع للخطة",

    // ── «الجمعيات» و«تفاصيل الجمعية»
    TextKey.ROSCAS_TITLE to "الجمعيات",
    TextKey.ROSCAS_NEW to "جمعية جديدة",
    TextKey.ROSCAS_EMPTY_TITLE to "لا توجد جمعيات",
    TextKey.ROSCAS_EMPTY_BODY to "أضف جمعية لنحسب ما دفعت وما قبضت.",
    TextKey.ROSCAS_TERMS to "{0} · {1} {2}",
    TextKey.ROSCA_TERMS_TO to "{0} · تدفع إلى {1}",
    TextKey.ROSCAS_PAID to "دفعت",
    TextKey.ROSCAS_GOT to "قبضت",
    TextKey.ROSCAS_GAIN to "الربح",
    TextKey.ROSCA_TURNS_ONE to "دور واحد",
    TextKey.ROSCA_TURNS_TWO to "دوران",
    TextKey.ROSCA_TURNS_FEW to "{0} أدوار",
    TextKey.ROSCA_TURNS_MANY to "{0} دورًا",
    TextKey.ROSCA_TURN_N to "الدور رقم {0}",
    TextKey.ROSCA_TURNS_N2 to "الدوران {0} و{1}",
    TextKey.ROSCA_TURN_UNKNOWN_LINE to "دورك غير معروف بعد",
    TextKey.ROSCA_PHASE_SAVING to "ادخار",
    TextKey.ROSCA_PHASE_REPAYING to "سداد",
    TextKey.ROSCA_PHASE_DONE to "انتهت",
    TextKey.ROSCA_POS_SAVED to "الجمعية تحفظ لك {0}",
    TextKey.ROSCA_POS_OWED to "عليك للجمعية {0}",
    TextKey.ROSCA_POS_DONE to "انتهت بلا ربح ولا خسارة",
    TextKey.ROSCA_POS_ZERO to "لا لك ولا عليك",
    TextKey.ROSCA_GAIN_NONE to "لا شيء",
    TextKey.ROSCA_HERO_SAVED to "الجمعية تحفظ لك",
    TextKey.ROSCA_HERO_OWED to "عليك للجمعية",
    TextKey.ROSCA_KIND_NOTE to "قسط الجمعية يُحسب مصروفًا، والقبض دخلًا — كلاهما تحت «المستحقات».",
    TextKey.ROSCA_TURNS_TITLE to "الأدوار ومواعيدها",
    TextKey.ROSCA_ALL_TURNS to "كل الأدوار ({0})",
    TextKey.ROSCA_ROW_MINE to "دورك · ستقبض {0}",
    TextKey.ROSCA_ROW_MINE_GOT to "دورك · قبضت {0}",
    TextKey.ROSCA_ROW_PAID to "دُفع",
    TextKey.ROSCA_ROW_SAVED to "تحفظ لك {0}",
    TextKey.ROSCA_ROW_OWED to "عليك {0}",
    TextKey.ROSCA_ROW_EVEN to "لا لك ولا عليك",
    TextKey.ROSCA_ANALYSIS to "التحليل",
    TextKey.ROSCA_AND to " و",
    TextKey.ROSCA_ST_PAYOUT_DATE to "موعد قبضك",
    TextKey.ROSCA_ST_GAIN to "الربح مقارنة بالادخار وحدك",
    TextKey.ROSCA_ST_GAIN_NEEDS_TURN to "يحتاج دورك",
    TextKey.ROSCA_ST_GAIN_EVEN to "تقبض بقدر ما تدفع",
    TextKey.ROSCA_ST_GAIN_PROFIT to "ربح",
    TextKey.ROSCA_ST_GAIN_FEES to "رسوم عليك",
    TextKey.ROSCA_ST_TOTAL_PAY to "إجمالي ما تدفعه",
    TextKey.ROSCA_ST_UNTIL to "حتى {0}",
    TextKey.ROSCA_ST_TOTAL_GET to "إجمالي ما تقبضه",
    TextKey.ROSCA_ST_IN to "في {0}",
    TextKey.ROSCA_ST_BEFORE to "أقساط قبل القبض",
    TextKey.ROSCA_ST_BEFORE_NOTE to "الجمعية تدّخر لك",
    TextKey.ROSCA_ST_AFTER to "أقساط بعد القبض",
    TextKey.ROSCA_ST_AFTER_NOTE to "تسدّد للجمعية",
    TextKey.ROSCA_ST_PEAK_SAVED to "أكبر مبلغ تحفظه لك",
    TextKey.ROSCA_ST_PEAK_SAVED_NOTE to "قبيل دورك",
    TextKey.ROSCA_ST_PEAK_OWED to "أكبر دين عليك",
    TextKey.ROSCA_ST_PEAK_OWED_NOTE to "بعد القبض مباشرة",
    TextKey.ROSCA_NOTE_KNOWN to "محسوب من بيانات الجمعية: قسطك وعدد الأدوار ودورك.",
    TextKey.ROSCA_NOTE_UNKNOWN to "حين يُعرف دورك (بالقرعة مثلًا) يظهر موعد القبض والربح. ربط قبض الدور متوقف حتى تحديد دورك.",

    // ── معالج «جمعية جديدة»
    TextKey.RW_TITLE to "جمعية جديدة",
    TextKey.RW_STEP to "السؤال {0} من {1}",
    TextKey.RW_SUMMARY_STEP to "التحليل قبل الحفظ",
    TextKey.RW_FIRST_HINT to "موعد أول دفعة هو موعد قبض الدور الأول.",
    TextKey.RW_TURN_HINT to "إن كان بالقرعة فاختر «غير معروف بعد».",
    TextKey.RW_PAYOUT_HINT to "قيمة الدور لا تنقسم بالتساوي على أدوارك — أدخلها بنفسك.",
    TextKey.RW_FREQ_COMMON to "الأكثر شيوعًا",
    TextKey.RW_COUNT_UP to "زِد دورًا",
    TextKey.RW_COUNT_DOWN to "أنقص دورًا",
    TextKey.RW_ERR_FIRST to "اختر يوم أول دفعة.",
    TextKey.RW_ERR_TURN to "اختر دورك، أو «غير معروف بعد».",
    TextKey.RW_HERO_GET to "ستقبض",
    TextKey.RW_HERO_WHEN to "موعد قبضك",
    TextKey.RW_HERO_EACH to "{0} في كل دور",
    TextKey.RW_HERO_UNKNOWN_SUB to "يظهر الموعد والربح حين يُعرف دورك.",
    TextKey.RW_LAST to "آخر قسط",
    TextKey.RW_ANSWERS to "إجاباتك — اضغط أيًّا منها لتغييرها",
    TextKey.RW_A_NAME to "الاسم",
    TextKey.RW_A_COUNT to "الأدوار",
    TextKey.RW_A_AMOUNT to "القسط",
    TextKey.RW_A_FREQ to "الدورية",
    TextKey.RW_A_FIRST to "أول دفعة",
    TextKey.RW_A_SHARE to "الأسهم",
    TextKey.RW_A_TURN to "دورك",
    TextKey.RW_A_PAYOUT to "قيمة الدور",
    TextKey.RW_EDIT to "غيّر {0}",
    TextKey.RW_PREV to "السابق",
    TextKey.RW_NEXT to "التالي",
    TextKey.RW_SAVE to "احفظ الجمعية",
    TextKey.RW_SAVED to "حُفظت «{0}» — تجدها في الجمعيات",
    TextKey.RW_DONE to "إلى الجمعيات",

    // ── «الاشتراكات والفواتير» و«تفاصيل الاشتراك»
    TextKey.SUBS_TITLE to "الاشتراكات والفواتير",
    TextKey.SUBS_NOTE to "تُحسب المدفوعات تلقائيًا من عمليات التاجر نفسه.",
    TextKey.SUBS_EMPTY_TITLE to "لا توجد اشتراكات",
    TextKey.SUBS_EMPTY_BODY to "حين يتكرر خصم من التاجر نفسه نقترحه هنا.",
    TextKey.SUBS_CAND_TITLE to "وجدنا ما يشبه اشتراكًا",
    TextKey.SUBS_CAND_YES to "نعم، اشتراك",
    TextKey.SUBS_CAND_ADDED to "أُضيف «{0}» إلى الاشتراكات",
    TextKey.SUBS_KIND_SUB to "اشتراك",
    TextKey.SUBS_KIND_BILL to "فاتورة",
    TextKey.SUBS_CYCLE_MONTHLY to "شهري",
    TextKey.SUBS_CYCLE_QUARTERLY to "كل ثلاثة أشهر",
    TextKey.SUBS_CYCLE_YEARLY to "سنوي",
    TextKey.SUBS_CHIP_LATE to "متأخرة",
    TextKey.SUBS_CHIP_SOON to "قريبة",
    TextKey.SUBS_CHIP_NEXT to "قادمة",
    TextKey.SUBS_CHIP_STOPPED to "متوقف",
    TextKey.SUBS_F_NEXT to "الموعد القادم",
    TextKey.SUBS_STOPPED_LABEL to "المتابعة متوقفة",
    TextKey.SUBS_STOPPED_SUB to "لن يظهر في المستحقات ولن ننبّهك بموعده.",
    TextKey.SUBS_LATE_BY to "متأخرة {0}",
    TextKey.SUBS_NEXT_SUB to "{0}، المتوقع {1}",
    TextKey.SUBS_PAID_12 to "المدفوع في آخر سنة",
    TextKey.SUBS_PAYMENTS_NONE to "لا دفعات بعد",
    TextKey.SUBS_PAYMENTS_ONE to "دفعة واحدة",
    TextKey.SUBS_PAYMENTS_TWO to "دفعتان",
    TextKey.SUBS_PAYMENTS_FEW to "{0} دفعات",
    TextKey.SUBS_PAYMENTS_MANY to "{0} دفعة",
    TextKey.SUBS_ANNUAL to "المتوقع سنويًا",
    TextKey.SUBS_ANNUAL_NOTE to "{0} × {1}",
    TextKey.SUBS_OUT_OF_CALC to "خارج الحساب",
    TextKey.SUBS_DATES to "المواعيد",
    TextKey.SUBS_F_CYCLE to "الدورة",
    TextKey.SUBS_F_EXPECTED to "المبلغ المتوقع",
    TextKey.SUBS_F_AMOUNT to "المبلغ المتوقع لكل دورة",
    TextKey.SUBS_EDIT to "عدّل المبلغ والدورة والموعد",
    TextKey.SUBS_EDIT_LOCKED to "استأنف المتابعة أولًا لتعديله",
    TextKey.SUBS_EDIT_TITLE to "تعديل «{0}»",
    TextKey.SUBS_EDIT_SAVED to "حُفظ التعديل",
    TextKey.SUBS_SAVE to "احفظ",
    TextKey.SUBS_PAY_NOTE to "تُحسب تلقائيًا من عمليات «{0}» — دون تسجيل دفعات يدويًا.",
    TextKey.SUBS_STOP to "أوقف المتابعة",
    TextKey.SUBS_STOP_NOTE to "تبقى العمليات السابقة كما هي.",
    TextKey.SUBS_STOP_TITLE to "إيقاف متابعة «{0}»؟",
    TextKey.SUBS_STOP_BODY to "لن يظهر في المستحقات ولن ننبّهك بموعده. يمكنك استئنافه في أي وقت.",
    TextKey.SUBS_STOP_YES to "أوقفه",
    TextKey.SUBS_STOPPED to "أُوقفت المتابعة",
    TextKey.SUBS_RESUME to "استأنف المتابعة",
    TextKey.SUBS_RESUMED to "استؤنفت المتابعة",
)
