package app.masroufy.core

/**
 * منطقة «المستحقات» — الجزء الأول بالمصري (مصر — OVERRIDES §66): من لوحات النموذج بنسخة `space = مصر` بالحرف.
 * نفس مفاتيح ومتغيرات `TextsAreaDuesDebts.kt`. **ممنوع «·» جنب رقم عربي** ⇒ «،».
 */
internal val EGYPTIAN_DUES_DEBTS_TEXTS: Map<UiKey, String> = mapOf(
    // ── خانة «المستحقات» والكلام المشترك
    UiKey.DUES_FOR_YOU to "ليك",
    UiKey.DUES_ON_YOU to "عليك",
    UiKey.DUES_LINE_RECEIVABLE to "ديون ليك",
    UiKey.DUES_LINE_ROSCA_SAVED to "متحوّش في الجمعيات",
    UiKey.DUES_LINE_LOANS to "ديون عليك",
    UiKey.DUES_LINE_CUSTODY to "أمانات عندك",
    UiKey.DUES_LINE_INSTALLMENTS to "أقساط باقية",
    UiKey.DUES_LINE_ROSCA_OWED to "عليك للجمعيات",
    UiKey.DUES_NO_NETTING to "كل رقم لوحده — مفيش خصم «ليك» من «عليك»",
    UiKey.DUES_MONTH_LINE to "هتدفع {0} · هتستلم {1}",
    UiKey.DUES_LIST_TITLE to "بالترتيب",
    UiKey.DUES_CHIP_LATE to "متأخر",
    UiKey.DUES_CHIP_SOON to "قرّب",
    UiKey.DUES_CHIP_NEXT to "جاي",
    UiKey.DUES_DIR_IN to "هتستلم",
    UiKey.DUES_DIR_OUT to "هتدفع",
    UiKey.DUES_ROW_YOUR_TURN to "وده دورك",
    UiKey.DUES_TILE_DEBTS to "الديون",
    UiKey.DUES_TILE_ROSCAS to "الجمعيات",
    UiKey.DUES_TILE_INSTALLMENTS to "الأقساط",
    UiKey.DUES_TILE_SUBSCRIPTIONS to "الاشتراكات",
    UiKey.DUES_FINANCING to "أرباح التمويل في الفترة دي {0} — معلومة بس، القسط كله محسوب مصروف.",
    UiKey.DUES_EMPTY_TITLE to "مفيش مستحقات",
    UiKey.DUES_EMPTY_BODY to "الديون والجمعيات والأقساط والاشتراكات هتظهر هنا.",
    UiKey.DUES_SHOW_ALL to "اعرض الكل",
    UiKey.DUES_SHOW_LESS to "اعرض أقل",
    UiKey.DUES_AGO_ONE to "من يوم",
    UiKey.DUES_AGO_TWO to "من يومين",
    UiKey.DUES_AGO_FEW to "من {0} أيام",
    UiKey.DUES_AGO_MANY to "من {0} يوم",
    UiKey.DUES_DATE_WITH_YEAR to "{0} {1}",
    UiKey.DUES_COMMA to "، ",
    UiKey.DUES_COMMA_JOIN to "{0}، {1}",
    UiKey.DUES_DASH to "—",
    UiKey.DUES_CYCLE_WEEKS to "كل {0} أسابيع",
    UiKey.DUES_CYCLE_MONTHS to "كل {0} شهور",
    UiKey.DUES_CYCLE_YEAR to "كل سنة",
    UiKey.DUES_INST_NONE to "مفيش أقساط",
    UiKey.DUES_INST_ONE to "قسط واحد",
    UiKey.DUES_INST_TWO to "قسطين",
    UiKey.DUES_INST_FEW to "{0} أقساط",
    UiKey.DUES_INST_MANY to "{0} قسط",
    UiKey.DUES_INTEREST_Q to "فيها فوايد؟",
    UiKey.DUES_INTEREST_SAVED to "اتحفظت إجابتك",
    UiKey.DUES_INTEREST_UNSET to "لسه ما قلتش",
    UiKey.DUES_YES to "أيوه",
    UiKey.DUES_NO to "لأ",
    UiKey.DUES_CANCEL to "سيبها",
    UiKey.DUES_ERR_FORMAT to "اكتب المبلغ بالأرقام، زي 1200.50",
    UiKey.DUES_ERR_POSITIVE to "اكتب مبلغ أكبر من صفر.",
    UiKey.DUES_SAVE_FAILED to "ما اتحفظش — جرّب تاني.",
    UiKey.DUES_UNLINK_BODY to "العملية هترجع «لسه ما اتحددش» وهتظهر في المراجعات.",
    UiKey.DUES_UNLINK_YES to "فك الربط",
    UiKey.DUES_UNLINKED to "اتفك الربط — العملية في المراجعات",

    // ── «الديون»
    UiKey.DEBTS_TITLE to "الديون",
    UiKey.DEBTS_SUB to "مع الناس، ليك وعليك كل واحد لوحده",
    UiKey.DEBTS_FOR_YOU_HINT to "ديون ليك عند الناس",
    UiKey.DEBTS_ON_YOU_HINT to "ديون عليك للناس",
    UiKey.DEBTS_NOBODY to "مفيش حد",
    UiKey.DEBTS_AT_ONE to "عند شخص واحد",
    UiKey.DEBTS_AT_TWO to "عند اتنين",
    UiKey.DEBTS_AT_FEW to "عند {0} أشخاص",
    UiKey.DEBTS_AT_MANY to "عند {0} شخص",
    UiKey.DEBTS_TO_ONE to "لشخص واحد",
    UiKey.DEBTS_TO_TWO to "لاتنين",
    UiKey.DEBTS_TO_FEW to "{0} أشخاص",
    UiKey.DEBTS_TO_MANY to "{0} شخص",
    UiKey.DEBTS_SEARCH_HINT to "دوّر باسم الشخص",
    UiKey.DEBTS_SEARCH_CLEAR to "امسح البحث",
    UiKey.DEBTS_ORDER_FOR_YOU to "الأهم الأول: اللي ميعاده فات، وبعده الأقرب ميعاد",
    UiKey.DEBTS_ORDER_ON_YOU to "بالميعاد",
    UiKey.DEBTS_CUSTODY_TITLE to "أمانات عندك",
    UiKey.DEBTS_ORDER_CUSTODY to "لوحدها بعيد عن الديون، بالميعاد",
    UiKey.DEBTS_REASON_RECEIVABLE to "دين ليك من عملية",
    UiKey.DEBTS_REASON_LOAN to "دين عليك من عملية",
    UiKey.DEBTS_REASON_OPENING to "دين قديم من قبل التطبيق",
    UiKey.DEBTS_REASON_CUSTODY to "أمانة عندك",
    UiKey.DEBTS_DUE_ON to "ميعادها {0}",
    UiKey.DEBTS_NO_DUE to "من غير ميعاد",
    UiKey.DEBTS_SIG_OVERDUE to "ميعادها فات {0}",
    UiKey.DEBTS_SIG_SOON to "ميعادها قرّب، {0}",
    UiKey.DEBTS_ARIA_FOR to "{0}، ليك {1}",
    UiKey.DEBTS_ARIA_ON to "{0}، عليك {1}",
    UiKey.DEBTS_EMPTY_TITLE to "مفيش ديون مع حد",
    UiKey.DEBTS_EMPTY_BODY to "لما تقسم فاتورة أو تسجّل سلفة على حد هتظهر هنا.",
    UiKey.DEBTS_EMPTY_GO to "افتح الناس",
    UiKey.DEBTS_NO_HITS_NAME to "مفيش حد اسمه «{0}»",
    UiKey.DEBTS_NO_HITS to "مفيش حاجة هنا",
    UiKey.DEBTS_NO_HITS_IN_SIDE to "البحث جوه «{0}» بس.",
    UiKey.DEBTS_NO_HITS_TRY to "جرّب حتة من الاسم.",
    UiKey.DEBTS_FOOT to "دوس على الدين عشان تشوف أصله وتسجّل تحصيل أو سداد.",

    // ── «تفاصيل الدين»
    UiKey.DEBT_TITLE to "تفاصيل الدين",
    UiKey.DEBT_REMAIN_FOR to "فاضل ليك عنده",
    UiKey.DEBT_REMAIN_ON to "فاضل عليك ليه",
    UiKey.DEBT_OF_ORIGINAL to "من أصل {0}",
    UiKey.DEBT_OF_ORIGINAL_NONE to "من أصل {0}، لسه ما اتسددش حاجة",
    UiKey.DEBT_DONE to "خلص بالكامل ✓",
    UiKey.DEBT_NOT_OPEN to "الدين ده مش موجود أو خلص بالكامل.",
    UiKey.DEBT_ORIGIN_TITLE to "أصل الدين",
    UiKey.DEBT_ORIGIN_LABEL to "جه منين",
    UiKey.DEBT_ORIGIN_TXN to "عملية متسجلة",
    UiKey.DEBT_ORIGIN_BEFORE_APP to "من قبل التطبيق",
    UiKey.DEBT_ORIGIN_OLD_CHIP to "دين قديم",
    UiKey.DEBT_ORIGIN_OLD_HINT to "من غير عملية — ما بيدخلش المصروف ولا الدخل ولا الكاش",
    UiKey.DEBT_ORIGINAL to "المبلغ الأصلي",
    UiKey.DEBT_TYPE to "النوع",
    UiKey.DEBT_TYPE_RECEIVABLE to "دين ليك",
    UiKey.DEBT_TYPE_LOAN to "سلفة عليك",
    UiKey.DEBT_TYPE_OLD_ON_YOU to "دين قديم عليك",
    UiKey.DEBT_TYPE_CUSTODY to "أمانة عندك",
    UiKey.DEBT_TYPE_HINT to "لوحده بعيد عن الأمانات — ومن غير خصم من «{0}»",
    UiKey.DEBT_TERMS_TITLE to "الميعاد",
    UiKey.DEBT_TERMS_ONE_PAYMENT to "{0}، دفعة واحدة",
    UiKey.DEBT_TERMS_SET to "حدّد ميعاد",
    UiKey.DEBT_TERMS_CHANGE to "غيّر",
    UiKey.DEBT_TERMS_REMOVE to "شيله",
    UiKey.DEBT_TERMS_PICK to "دفعة واحدة بالمتبقي كله في:",
    UiKey.DEBT_TERMS_SAVED to "الميعاد بقى {0} — هيظهر في المستحقات",
    UiKey.DEBT_TERMS_REMOVED to "اتشال الميعاد — والدين فاضل زي ما هو",
    UiKey.DEBT_INTEREST_SAVED to "اتحفظت إجابتك",

    // ── لوحة «سجّل تحصيل/سداد»
    UiKey.SETTLE_SHEET_TITLE_GENERIC to "تسوية الدين",
    UiKey.SETTLE_TRIGGER_FOR to "سجّل تحصيل",
    UiKey.SETTLE_TRIGGER_ON to "سجّل سداد",
    UiKey.SETTLE_DONE_WHY to "الدين ده خلص.",
    UiKey.SETTLE_TITLE_FOR to "تحصيل من {0}",
    UiKey.SETTLE_TITLE_ON to "سداد لـ{0}",
    UiKey.SETTLE_REMAINING to "المتبقي {0}",
    UiKey.SETTLE_HOW_FREE to "من غير عملية",
    UiKey.SETTLE_HOW_LINK to "عملية موجودة",
    UiKey.SETTLE_NO_CAND to "مفيش عملية مستنية",
    UiKey.SETTLE_NO_CAND_SUB to "لما توصل حوالة من {0} أو ليه هنسألك عليها.",
    UiKey.SETTLE_AMOUNT to "المبلغ",
    UiKey.SETTLE_FILL to "المتبقي كله {0}",
    UiKey.SETTLE_ERR_OVER to "المبلغ ما يزيدش عن المتبقي ({0}).",
    UiKey.SETTLE_SAVE_FOR to "سجّل التحصيل",
    UiKey.SETTLE_SAVE_ON to "سجّل السداد",
    UiKey.SETTLE_SAVE_FOR_AMOUNT to "سجّل التحصيل · {0}",
    UiKey.SETTLE_SAVE_ON_AMOUNT to "سجّل السداد · {0}",
    UiKey.SETTLE_SAVED_FULL to "الدين خلص بالكامل",
    UiKey.SETTLE_SAVED_FOR to "اتسجّل التحصيل من {0}",
    UiKey.SETTLE_SAVED_ON to "اتسجّل السداد لـ{0}",

    // ── «دين قديم»
    UiKey.OPENING_DEBT_CARD_TITLE to "فيه دين قديم مع {0} من قبل التطبيق؟",
    UiKey.OPENING_DEBT_CARD_BODY to "من غير عملية، وما بيلمسش أي محفظة.",
    UiKey.OPENING_DEBT_OPEN to "سجّله",
    UiKey.OPENING_DEBT_TITLE to "دين قديم مع {0}",
    UiKey.OPENING_DEBT_BODY to "لفلوس كاش اتبادلت قبل التطبيق ومالهاش سجل. ما بيدخلش المصروف ولا الدخل ولا رصيد الكاش، وبيتسدد عادي.",
    UiKey.OPENING_DEBT_FOR to "ليا عنده",
    UiKey.OPENING_DEBT_ON to "عليا ليه",
    UiKey.OPENING_DEBT_SAVE to "احفظ الدين",
    UiKey.OPENING_DEBT_SAVED to "اتسجّل الدين القديم — دي صفحته",
    UiKey.OPENING_ERR_SIDE to "اختار: ليك عنده ولا عليك ليه.",
    UiKey.OPENING_ERR_CURRENCY to "تسجيل الدين القديم بالجنيه لسه مش متاح.",
)
