package app.masroufy.core

/**
 * «إعدادات الإشعارات» (`NotificationSettings`) + «القفل واللغة والمحتوى» (`AppSettings`) — منطقة «المزيد». من النموذج بالحرف، إلا:
 * - شرح «الأسئلة» من غير «سلفة أم دعم؟ · هل هي سداد؟ · كم بالريال؟»: مجموعة الأسئلة في كوتلن فيها أطراف التحويلات بس (§75 «يسأل» مش متبني).
 * - «ملفك» مجموعة في المحرك (`AlertGroup.PROFILE`) مش مرسومة في النموذج — اتضافت آخر حاجة عشان تتقفل (اختيار Claude).
 * - سطور «غير متاح بعد» (سؤال الكاش · حفظ اللغة) — كتابة Claude.
 */
internal val MSA_MORE_SETTINGS_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.NSET_TITLE to "إعدادات الإشعارات",
    TextKey.NSET_INTRO to "أغلق أي مجموعة وحدها.",
    TextKey.NSET_NEW to "جديد",
    TextKey.NSET_BANK to "رسائل البنك",
    TextKey.NSET_BANK_DESC to "فقط عند وجود رسائل بانتظار تأكيدك. ما يُسجَّل تلقائيًا لا يصدر عنه إشعار.",
    TextKey.NSET_BANK_OFF_DESC to "مغلقة: الرسائل المنتظرة تظهر في صفحة الإشعارات فقط، بلا إشعار جوال.",
    TextKey.NSET_DUES to "المستحقات",
    TextKey.NSET_DUES_DESC to "الأقساط والاشتراكات والديون: قبل الموعد ويومه وعند تجاوزه",
    TextKey.NSET_BUDGET to "الميزانية",
    TextKey.NSET_BUDGET_DESC to "عند الاقتراب من السقف أو تجاوزه، ولو بسبب عملية سُجّلت تلقائيًا",
    TextKey.NSET_ASK to "الأسئلة",
    TextKey.NSET_ASK_DESC to "أطراف التحويلات بانتظار قرارك — وإن لم تردّ تبقى في المراجعة",
    TextKey.NSET_CASH to "سؤال الكاش",
    TextKey.NSET_CASH_DESC to "يسألك «كم معك كاش؟» ليبقى رصيد الكاش صحيحًا",
    TextKey.NSET_CASH_NOTE to "صباح الجمعة (مقترح). إن عددت الكاش بنفسك قبلها يتأجل السؤال.",
    TextKey.NSET_CASH_NOT_YET to "سؤال الكاش غير متاح بعد: لا تنبيه له في التطبيق حتى الآن.",
    TextKey.NSET_EVERY_WEEK to "كل أسبوع",
    TextKey.NSET_EVERY_2WEEKS to "كل أسبوعين",
    TextKey.NSET_EVERY_MONTH to "كل شهر",
    TextKey.NSET_INCOME to "الدخل",
    TextKey.NSET_INCOME_DESC to "إذا تأخر الراتب عن موعده",
    TextKey.NSET_OCC to "المناسبات",
    TextKey.NSET_OCC_DESC to "أعياد ميلاد أشخاصك ومناسباتهم",
    TextKey.NSET_ZAKAT to "الزكاة",
    TextKey.NSET_ZAKAT_DESC to "قبل موعدها بـ١٠ أيام ويومه",
    TextKey.NSET_BALANCE to "الرصيد",
    TextKey.NSET_BALANCE_DESC to "إذا لم يطابق رصيد محفظة الكشف",
    TextKey.NSET_ADVISOR to "المساعد",
    TextKey.NSET_ADVISOR_DESC to "التحليلات الذكية من المساعد المالي",
    TextKey.NSET_PROFILE to "ملفك",
    TextKey.NSET_PROFILE_DESC to "تذكير لطيف بإكمال أسئلة ملفك",
    TextKey.NSET_LATER_TITLE to "لاحقًا",
    TextKey.NSET_LATER_BODY to "الأمان · الحسابات المرتبطة · البريد الإلكتروني — تُضاف لاحقًا.",
    TextKey.NSET_LOCK_NOTE to "شاشة القفل تعرض نوع التنبيه فقط: بلا مبالغ ولا أسماء ولا أعداد.",
    TextKey.APPS_TITLE to "القفل واللغة والمحتوى",
    TextKey.APPS_LOCK_HEAD to "القفل",
    TextKey.APPS_LOCK_TITLE to "قفل البصمة",
    TextKey.APPS_LOCK_DESC to "يُقفل عند فتح التطبيق، وبعد ٥ دقائق في الخلفية.",
    TextKey.APPS_LOCK_FACT_1 to "العودة قبل ٥ دقائق لا تطلب البصمة.",
    TextKey.APPS_LOCK_FACT_2 to "إن تعذّرت البصمة: رمز قفل الجوال.",
    TextKey.APPS_LOCK_FACT_3 to "يبقى التطبيق خلف ضبابية حتى التحقق.",
    TextKey.APPS_LOCK_NA to "لا قفل شاشة ولا بصمة مسجلة في الجوال. فعّل قفل الشاشة من إعدادات الجوال أولًا.",
    TextKey.APPS_LOCK_ON_DONE to "تم تفعيل القفل",
    TextKey.APPS_LOCK_OFF_DONE to "تم إيقاف القفل",
    TextKey.APPS_LANG_HEAD to "اللغة",
    TextKey.APPS_LANG_AR to "العربية",
    TextKey.APPS_LANG_AR_DESC to "تلقائيًا حسب البلد: السعودية بالفصحى المختصرة، ومصر باللهجة المصرية. الآن: {0}.",
    TextKey.APPS_LANG_MSA to "الفصحى المختصرة",
    TextKey.APPS_LANG_EGYPTIAN to "اللهجة المصرية",
    TextKey.APPS_LANG_EN to "English",
    TextKey.APPS_LANG_EN_ALT to "الإنجليزية",
    TextKey.APPS_LANG_EN_DESC to "تنقلب الشاشة فتبدأ من اليسار.",
    TextKey.APPS_LANG_NEXT_OPEN to "تُطبَّق اللغة عند فتح التطبيق مرة أخرى.",
    TextKey.APPS_LANG_NOT_YET to "حفظ اختيار اللغة غير متاح بعد: يبدأ التطبيق بالعربية حاليًا.",
    TextKey.APPS_DIR_RTL to "اتجاه الشاشة: من اليمين إلى اليسار.",
    TextKey.APPS_DIR_LTR to "اتجاه الشاشة: من اليسار إلى اليمين.",
    TextKey.APPS_ISL_HEAD to "المحتوى الإسلامي",
    TextKey.APPS_ISL_TITLE to "إظهار المحتوى الإسلامي",
    TextKey.APPS_ISL_SHOWN to "ظاهر",
    TextKey.APPS_ISL_HIDDEN to "مخفي",
    TextKey.APPS_ISL_SHOWN_DONE to "أصبح المحتوى الإسلامي ظاهرًا",
    TextKey.APPS_ISL_HIDDEN_DONE to "أُخفي المحتوى الإسلامي",
    TextKey.APPS_ISL_LIST_ON to "يظهر:",
    TextKey.APPS_ISL_LIST_OFF to "مخفي الآن:",
    TextKey.APPS_ISL_ZAKAT to "الزكاة في الاستثمار وموعدها وتنبيهاتها",
    TextKey.APPS_ISL_CALENDAR to "رمضان والعيدان في التقويم",
    TextKey.APPS_ISL_NOTE to "إخفاء فقط — لا يُحذف شيء، ويعود كما كان عند إظهاره.",
)

internal val EGYPTIAN_MORE_SETTINGS_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.NSET_TITLE to "إعدادات الإشعارات",
    TextKey.NSET_INTRO to "كل مجموعة بتتقفل لوحدها.",
    TextKey.NSET_NEW to "جديد",
    TextKey.NSET_BANK to "رسايل البنك",
    TextKey.NSET_BANK_DESC to "بس لما فيه رسايل مستنية تأكيدك. اللي بيتسجل لوحده مالوش إشعار.",
    TextKey.NSET_BANK_OFF_DESC to "مقفولة: الرسايل المستنية بتبان في صفحة الإشعارات بس، من غير إشعار جوال.",
    TextKey.NSET_DUES to "المستحقات",
    TextKey.NSET_DUES_DESC to "الأقساط والاشتراكات والديون: قبل الميعاد ويومه ولو عدّى",
    TextKey.NSET_BUDGET to "الميزانية",
    TextKey.NSET_BUDGET_DESC to "لما تقرب من السقف أو تعدّيه، حتى لو بسبب عملية اتسجلت لوحدها",
    TextKey.NSET_ASK to "الأسئلة",
    TextKey.NSET_ASK_DESC to "أطراف التحويلات المستنية قرارك — ولو ما رديتش بتفضل في المراجعة",
    TextKey.NSET_CASH to "سؤال الكاش",
    TextKey.NSET_CASH_DESC to "يسألك «معاك كام كاش؟» عشان رصيد الكاش يفضل صح",
    TextKey.NSET_CASH_NOTE to "يوم الجمعة الصبح (اقتراح). لو عدّيت الكاش بنفسك قبلها، السؤال بيتأجل.",
    TextKey.NSET_CASH_NOT_YET to "سؤال الكاش لسه مش متاح: مالوش تنبيه في البرنامج لسه.",
    TextKey.NSET_EVERY_WEEK to "كل أسبوع",
    TextKey.NSET_EVERY_2WEEKS to "كل أسبوعين",
    TextKey.NSET_EVERY_MONTH to "كل شهر",
    TextKey.NSET_INCOME to "الدخل",
    TextKey.NSET_INCOME_DESC to "لو المرتب اتأخر عن ميعاده",
    TextKey.NSET_OCC to "المناسبات",
    TextKey.NSET_OCC_DESC to "أعياد ميلاد ومناسبات أشخاصك",
    TextKey.NSET_ZAKAT to "الزكاة",
    TextKey.NSET_ZAKAT_DESC to "قبل ميعادها بـ١٠ أيام ويومه",
    TextKey.NSET_BALANCE to "الرصيد",
    TextKey.NSET_BALANCE_DESC to "لو رصيد محفظة ما طابقش الكشف",
    TextKey.NSET_ADVISOR to "المساعد",
    TextKey.NSET_ADVISOR_DESC to "التحليلات الذكية من المساعد المالي",
    TextKey.NSET_PROFILE to "ملفك",
    TextKey.NSET_PROFILE_DESC to "تذكير خفيف تكمّل أسئلة ملفك",
    TextKey.NSET_LATER_TITLE to "بعدين",
    TextKey.NSET_LATER_BODY to "الأمان · الحسابات المربوطة · الإيميل — بتيجي بعدين.",
    TextKey.NSET_LOCK_NOTE to "شاشة القفل بتعرض نوع التنبيه بس: من غير مبالغ ولا أسامي ولا عدد.",
    TextKey.APPS_TITLE to "القفل واللغة والمحتوى",
    TextKey.APPS_LOCK_HEAD to "القفل",
    TextKey.APPS_LOCK_TITLE to "قفل البصمة",
    TextKey.APPS_LOCK_DESC to "بيتقفل لما تفتح البرنامج، وبعد ٥ دقايق في الخلفية.",
    TextKey.APPS_LOCK_FACT_1 to "الرجوع قبل ٥ دقايق مش بيسأل.",
    TextKey.APPS_LOCK_FACT_2 to "لو البصمة ما نفعتش: رمز قفل الجوال.",
    TextKey.APPS_LOCK_FACT_3 to "البرنامج بيفضل متغطي ببلور لحد ما تتأكد.",
    TextKey.APPS_LOCK_NA to "الجوال مالوش قفل شاشة ولا بصمة متسجلة. اعمل قفل شاشة من إعدادات الجوال الأول.",
    TextKey.APPS_LOCK_ON_DONE to "القفل اشتغل",
    TextKey.APPS_LOCK_OFF_DONE to "القفل اتوقف",
    TextKey.APPS_LANG_HEAD to "اللغة",
    TextKey.APPS_LANG_AR to "العربية",
    TextKey.APPS_LANG_AR_DESC to "لوحده حسب البلد: السعودية بالفصحى المختصرة، ومصر بالمصري. دلوقتي: {0}.",
    TextKey.APPS_LANG_MSA to "الفصحى المختصرة",
    TextKey.APPS_LANG_EGYPTIAN to "المصري",
    TextKey.APPS_LANG_EN to "English",
    TextKey.APPS_LANG_EN_ALT to "الإنجليزي",
    TextKey.APPS_LANG_EN_DESC to "الشاشة بتتعكس وتبدأ من الشمال.",
    TextKey.APPS_LANG_NEXT_OPEN to "اللغة بتتطبق لما تفتح البرنامج تاني.",
    TextKey.APPS_LANG_NOT_YET to "حفظ اختيار اللغة لسه مش متاح: البرنامج بيبدأ بالعربي دلوقتي.",
    TextKey.APPS_DIR_RTL to "اتجاه الشاشة: من اليمين للشمال.",
    TextKey.APPS_DIR_LTR to "اتجاه الشاشة: من الشمال لليمين.",
    TextKey.APPS_ISL_HEAD to "المحتوى الإسلامي",
    TextKey.APPS_ISL_TITLE to "اظهر المحتوى الإسلامي",
    TextKey.APPS_ISL_SHOWN to "ظاهر",
    TextKey.APPS_ISL_HIDDEN to "مخفي",
    TextKey.APPS_ISL_SHOWN_DONE to "المحتوى الإسلامي ظاهر",
    TextKey.APPS_ISL_HIDDEN_DONE to "المحتوى الإسلامي اتخفى",
    TextKey.APPS_ISL_LIST_ON to "بيظهر:",
    TextKey.APPS_ISL_LIST_OFF to "مخفي دلوقتي:",
    TextKey.APPS_ISL_ZAKAT to "الزكاة في الاستثمار وميعادها وإشعاراتها",
    TextKey.APPS_ISL_CALENDAR to "رمضان والعيدين في التقويم",
    TextKey.APPS_ISL_NOTE to "إخفا بس — مفيش حاجة بتتمسح، ولما ترجّعه بيرجع زي ما كان.",
)

internal val ENGLISH_MORE_SETTINGS_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.NSET_TITLE to "Notification settings",
    TextKey.NSET_INTRO to "Turn off any group on its own.",
    TextKey.NSET_NEW to "New",
    TextKey.NSET_BANK to "Bank messages",
    TextKey.NSET_BANK_DESC to "Only when messages are waiting for your confirmation. What's recorded automatically sends no notification.",
    TextKey.NSET_BANK_OFF_DESC to "Off: waiting messages only show on the notifications page, with no phone notification.",
    TextKey.NSET_DUES to "Dues",
    TextKey.NSET_DUES_DESC to "Installments, subscriptions and debts: before the date, on it, and when it passes",
    TextKey.NSET_BUDGET to "Budget",
    TextKey.NSET_BUDGET_DESC to "When you near or pass the limit, even because of an automatically recorded transaction",
    TextKey.NSET_ASK to "Questions",
    TextKey.NSET_ASK_DESC to "Transfer parties waiting for your decision — unanswered ones stay in review",
    TextKey.NSET_CASH to "Cash question",
    TextKey.NSET_CASH_DESC to "Asks “How much cash do you have?” so your cash balance stays right",
    TextKey.NSET_CASH_NOTE to "Friday morning (suggested). If you count your cash before then, the question waits.",
    TextKey.NSET_CASH_NOT_YET to "The cash question isn't available yet: the app has no alert for it so far.",
    TextKey.NSET_EVERY_WEEK to "Every week",
    TextKey.NSET_EVERY_2WEEKS to "Every two weeks",
    TextKey.NSET_EVERY_MONTH to "Every month",
    TextKey.NSET_INCOME to "Income",
    TextKey.NSET_INCOME_DESC to "If your salary is late",
    TextKey.NSET_OCC to "Occasions",
    TextKey.NSET_OCC_DESC to "Your people's birthdays and occasions",
    TextKey.NSET_ZAKAT to "Zakat",
    TextKey.NSET_ZAKAT_DESC to "10 days before it's due, and on the day",
    TextKey.NSET_BALANCE to "Balance",
    TextKey.NSET_BALANCE_DESC to "If a wallet's balance doesn't match the statement",
    TextKey.NSET_ADVISOR to "Assistant",
    TextKey.NSET_ADVISOR_DESC to "Smart insights from the financial assistant",
    TextKey.NSET_PROFILE to "Your profile",
    TextKey.NSET_PROFILE_DESC to "A gentle reminder to finish your profile questions",
    TextKey.NSET_LATER_TITLE to "Later",
    TextKey.NSET_LATER_BODY to "Security · linked accounts · email — coming later.",
    TextKey.NSET_LOCK_NOTE to "The lock screen shows only the kind of alert: no amounts, names or counts.",
    TextKey.APPS_TITLE to "Lock, language and content",
    TextKey.APPS_LOCK_HEAD to "Lock",
    TextKey.APPS_LOCK_TITLE to "Fingerprint lock",
    TextKey.APPS_LOCK_DESC to "Locks when you open the app, and after 5 minutes in the background.",
    TextKey.APPS_LOCK_FACT_1 to "Coming back within 5 minutes doesn't ask.",
    TextKey.APPS_LOCK_FACT_2 to "If the fingerprint fails: your phone's lock code.",
    TextKey.APPS_LOCK_FACT_3 to "The app stays blurred until you confirm.",
    TextKey.APPS_LOCK_NA to "The phone has no screen lock or registered fingerprint. Turn on a screen lock in the phone's settings first.",
    TextKey.APPS_LOCK_ON_DONE to "Lock turned on",
    TextKey.APPS_LOCK_OFF_DONE to "Lock turned off",
    TextKey.APPS_LANG_HEAD to "Language",
    TextKey.APPS_LANG_AR to "العربية",
    TextKey.APPS_LANG_AR_DESC to "Automatic by country: Saudi Arabia in concise Standard Arabic, Egypt in Egyptian Arabic. Now: {0}.",
    TextKey.APPS_LANG_MSA to "Concise Standard Arabic",
    TextKey.APPS_LANG_EGYPTIAN to "Egyptian Arabic",
    TextKey.APPS_LANG_EN to "English",
    TextKey.APPS_LANG_EN_ALT to "الإنجليزية",
    TextKey.APPS_LANG_EN_DESC to "The screen flips to start from the left.",
    TextKey.APPS_LANG_NEXT_OPEN to "The language applies when you open the app again.",
    TextKey.APPS_LANG_NOT_YET to "Saving the language choice isn't available yet: the app starts in Arabic for now.",
    TextKey.APPS_DIR_RTL to "Screen direction: right to left.",
    TextKey.APPS_DIR_LTR to "Screen direction: left to right.",
    TextKey.APPS_ISL_HEAD to "Islamic content",
    TextKey.APPS_ISL_TITLE to "Show Islamic content",
    TextKey.APPS_ISL_SHOWN to "Shown",
    TextKey.APPS_ISL_HIDDEN to "Hidden",
    TextKey.APPS_ISL_SHOWN_DONE to "Islamic content is shown",
    TextKey.APPS_ISL_HIDDEN_DONE to "Islamic content is hidden",
    TextKey.APPS_ISL_LIST_ON to "Shows:",
    TextKey.APPS_ISL_LIST_OFF to "Hidden now:",
    TextKey.APPS_ISL_ZAKAT to "Zakat in Investment, its date and alerts",
    TextKey.APPS_ISL_CALENDAR to "Ramadan and the two Eids in the calendar",
    TextKey.APPS_ISL_NOTE to "Hiding only — nothing is deleted, and it comes back as it was.",
)
