package app.masroufy.core

/**
 * نصوص شاشات منطقة «الرئيسية» (`ui/screens/home/`) — **الملف ده بتاع المنطقة بس** (المناطق بتتبني بالتوازي، ARCHITECTURE §31.31).
 * المفاتيح في `TextKeys.kt` **تحت سطر «منطقة الرئيسية»** بس. الفصحى للسعودية والافتراضي · المصري لمصر (OVERRIDES §66) · الإنجليزي
 * (كتابة Claude — مستني مراجعة المالك §40). النص من النموذج التفاعلي بالحرف (الفصحى من `space = السعودية` والمصري من `مصر`).
 * **ممنوع «·» جنب رقم عربي** ⇒ «،». الملف قرّب على 300 سطر ⇒ الباقي في `TextsAreaHomeNotify.kt` · `TextsAreaHomeCalendar.kt` ·
 * `TextsAreaHomeProfile.kt` · `TextsAreaHomeReview.kt` ومضمومين هنا بـ`+`.
 * هنا: الرئيسية · لوحة الكاش · القفل · «اختر شكلك».
 */
internal val MSA_AREA_HOME_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.HOME_SPENT_MONTH to "صرفت هذا الشهر {0}",
    TextKey.HOME_SALARY_TODAY to "الراتب اليوم",
    TextKey.HOME_SALARY_TOMORROW to "الراتب غدًا",
    TextKey.HOME_SALARY_TWO_DAYS to "الراتب بعد يومين",
    TextKey.HOME_SALARY_FEW_DAYS to "الراتب بعد {0} أيام",
    TextKey.HOME_SALARY_MANY_DAYS to "الراتب بعد {0} يومًا",
    TextKey.HOME_NA_CASH_ONLY to "الكاش وحده {0}.",
    TextKey.HOME_EMPTY_TITLE to "لا توجد عمليات هذا الشهر",
    TextKey.HOME_EMPTY_BODY to "أضف أول عملية أو فعّل قراءة رسائل البنك.",
    TextKey.HOME_ERROR_TITLE to "تعذّر تحميل بياناتك",
    TextKey.HOME_ERROR_BODY to "تحقّق من الاتصال ثم أعد المحاولة.",
    TextKey.HOME_ADVISOR_OPEN to "التفاصيل في المساعد",
    TextKey.HOME_PROFILE_TITLE to "أكمل ملفك",
    TextKey.HOME_PROFILE_BODY to "سؤال واحد في ١٠ ثوانٍ، وتصبح الأرقام أدق",
    TextKey.CASH_DETAILS_OPEN to "تفاصيل الكاش",
    TextKey.CASH_DETAILS_TITLE to "الكاش الذي معك",
    TextKey.CASH_DETAILS_SINCE to "منذ رصيد البداية في {0}",
    TextKey.CASH_DETAILS_SPENT to "صرفت كاش هذا الشهر",
    TextKey.CASH_DETAILS_OPS to "عمليات الكاش هذا الشهر",
    TextKey.CASH_DETAILS_NO_OPS to "لا عمليات كاش هذا الشهر.",
    TextKey.CASH_DETAILS_NOTE to "«صرفت هذا الشهر» في الرئيسية يشمل ما دفعته كاش.",
    TextKey.CASH_DETAILS_NO_WALLET_TITLE to "لا توجد محفظة كاش",
    TextKey.CASH_DETAILS_NO_WALLET_BODY to "أضف محفظة كاش من «المحافظ» ليظهر رصيدها هنا.",
    TextKey.LOCK_SCREEN_RETRY to "إعادة المحاولة",
    TextKey.LOCK_SCREEN_RELEASED_TITLE to "أُوقف قفل التطبيق",
    TextKey.LOCK_SCREEN_RELEASED_BODY to "لا قفل شاشة ولا بصمة مسجلة في الجوال. فعّل قفل الشاشة من إعدادات الجوال أولًا، ثم شغّل القفل من جديد من الإعدادات.",
    TextKey.LOCK_SCREEN_CONTINUE to "متابعة",
    TextKey.LOOK_SHEET_TITLE to "اختر شكلك",
    TextKey.LOOK_SHEET_ITEM to "الشكل {0}",
    TextKey.LOOK_SHEET_NOTE to "أشكال مؤقتة — الكاركتر النهائي قيد التصميم.",
    TextKey.LOOK_SHEET_SAVE to "احفظ",
    TextKey.ADD_FROM_USUAL to "من أين تصرف عادةً؟",
    TextKey.ADD_SAVED_MAIN to "{0} — وصار «{1}» الأساسي",
) + MSA_AREA_HOME_NOTIFY_TEXTS + MSA_AREA_HOME_CALENDAR_TEXTS + MSA_AREA_HOME_PROFILE_TEXTS + MSA_AREA_HOME_REVIEW_TEXTS

internal val EGYPTIAN_AREA_HOME_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.HOME_SPENT_MONTH to "صرفت الشهر ده {0}",
    TextKey.HOME_SALARY_TODAY to "المرتب النهارده",
    TextKey.HOME_SALARY_TOMORROW to "المرتب بكرة",
    TextKey.HOME_SALARY_TWO_DAYS to "المرتب بعد يومين",
    TextKey.HOME_SALARY_FEW_DAYS to "المرتب بعد {0} أيام",
    TextKey.HOME_SALARY_MANY_DAYS to "المرتب بعد {0} يوم",
    TextKey.HOME_NA_CASH_ONLY to "الكاش لوحده {0}.",
    TextKey.HOME_EMPTY_TITLE to "مفيش عمليات الشهر ده",
    TextKey.HOME_EMPTY_BODY to "ضيف أول عملية أو شغّل قراية رسايل البنك.",
    TextKey.HOME_ERROR_TITLE to "ما قدرناش نحمّل بياناتك",
    TextKey.HOME_ERROR_BODY to "اتأكد من النت وجرّب تاني.",
    TextKey.HOME_ADVISOR_OPEN to "التفاصيل في المساعد",
    TextKey.HOME_PROFILE_TITLE to "كمّل ملفك",
    TextKey.HOME_PROFILE_BODY to "سؤال واحد، ١٠ ثواني، والأرقام بتبقى أدق",
    TextKey.CASH_DETAILS_OPEN to "تفاصيل الكاش",
    TextKey.CASH_DETAILS_TITLE to "الكاش اللي معاك",
    TextKey.CASH_DETAILS_SINCE to "من رصيد البداية في {0}",
    TextKey.CASH_DETAILS_SPENT to "صرفت كاش الشهر ده",
    TextKey.CASH_DETAILS_OPS to "عمليات الكاش الشهر ده",
    TextKey.CASH_DETAILS_NO_OPS to "مفيش عمليات كاش الشهر ده.",
    TextKey.CASH_DETAILS_NOTE to "«صرفت الشهر ده» في الرئيسية فيه اللي دفعته كاش.",
    TextKey.CASH_DETAILS_NO_WALLET_TITLE to "مفيش محفظة كاش",
    TextKey.CASH_DETAILS_NO_WALLET_BODY to "ضيف محفظة كاش من «المحافظ» عشان رصيدها يظهر هنا.",
    TextKey.LOCK_SCREEN_RETRY to "جرّب تاني",
    TextKey.LOCK_SCREEN_RELEASED_TITLE to "القفل اتوقف",
    TextKey.LOCK_SCREEN_RELEASED_BODY to "الجوال مالوش قفل شاشة ولا بصمة متسجلة. اعمل قفل شاشة من إعدادات الجوال الأول، وبعدين شغّل القفل تاني من الإعدادات.",
    TextKey.LOCK_SCREEN_CONTINUE to "كمّل",
    TextKey.LOOK_SHEET_TITLE to "اختر شكلك",
    TextKey.LOOK_SHEET_ITEM to "الشكل {0}",
    TextKey.LOOK_SHEET_NOTE to "أشكال مؤقتة — الكاركتر النهائي لسه بيتصمم.",
    TextKey.LOOK_SHEET_SAVE to "احفظ",
    TextKey.ADD_FROM_USUAL to "بتصرف عادةً منين؟",
    TextKey.ADD_SAVED_MAIN to "{0} — و«{1}» بقى الأساسي",
) + EGYPTIAN_AREA_HOME_NOTIFY_TEXTS + EGYPTIAN_AREA_HOME_CALENDAR_TEXTS + EGYPTIAN_AREA_HOME_PROFILE_TEXTS + EGYPTIAN_AREA_HOME_REVIEW_TEXTS

internal val ENGLISH_AREA_HOME_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.HOME_SPENT_MONTH to "Spent this month {0}",
    TextKey.HOME_SALARY_TODAY to "Payday is today",
    TextKey.HOME_SALARY_TOMORROW to "Payday is tomorrow",
    TextKey.HOME_SALARY_TWO_DAYS to "Payday in 2 days",
    TextKey.HOME_SALARY_FEW_DAYS to "Payday in {0} days",
    TextKey.HOME_SALARY_MANY_DAYS to "Payday in {0} days",
    TextKey.HOME_NA_CASH_ONLY to "Cash alone: {0}.",
    TextKey.HOME_EMPTY_TITLE to "No transactions this month",
    TextKey.HOME_EMPTY_BODY to "Add your first transaction or turn on bank message reading.",
    TextKey.HOME_ERROR_TITLE to "Couldn't load your data",
    TextKey.HOME_ERROR_BODY to "Check your connection, then try again.",
    TextKey.HOME_ADVISOR_OPEN to "Details in the assistant",
    TextKey.HOME_PROFILE_TITLE to "Complete your profile",
    TextKey.HOME_PROFILE_BODY to "One question, 10 seconds, sharper numbers",
    TextKey.CASH_DETAILS_OPEN to "Cash details",
    TextKey.CASH_DETAILS_TITLE to "Your cash",
    TextKey.CASH_DETAILS_SINCE to "Since the opening balance on {0}",
    TextKey.CASH_DETAILS_SPENT to "Cash spent this month",
    TextKey.CASH_DETAILS_OPS to "Cash transactions this month",
    TextKey.CASH_DETAILS_NO_OPS to "No cash transactions this month.",
    TextKey.CASH_DETAILS_NOTE to "“Spent this month” on Home includes what you paid in cash.",
    TextKey.CASH_DETAILS_NO_WALLET_TITLE to "No cash wallet",
    TextKey.CASH_DETAILS_NO_WALLET_BODY to "Add a cash wallet in Wallets to see its balance here.",
    TextKey.LOCK_SCREEN_RETRY to "Try again",
    TextKey.LOCK_SCREEN_RELEASED_TITLE to "App lock turned off",
    TextKey.LOCK_SCREEN_RELEASED_BODY to "Your phone has no screen lock or fingerprint. Set a screen lock in the phone settings first, then turn the lock on again in Settings.",
    TextKey.LOCK_SCREEN_CONTINUE to "Continue",
    TextKey.LOOK_SHEET_TITLE to "Choose your look",
    TextKey.LOOK_SHEET_ITEM to "Look {0}",
    TextKey.LOOK_SHEET_NOTE to "Temporary looks — the final character is still being designed.",
    TextKey.LOOK_SHEET_SAVE to "Save",
    TextKey.ADD_FROM_USUAL to "Where do you usually spend from?",
    TextKey.ADD_SAVED_MAIN to "{0} — and “{1}” is now your main wallet",
) + ENGLISH_AREA_HOME_NOTIFY_TEXTS + ENGLISH_AREA_HOME_CALENDAR_TEXTS + ENGLISH_AREA_HOME_PROFILE_TEXTS + ENGLISH_AREA_HOME_REVIEW_TEXTS
