package app.masroufy.core

/**
 * نصوص «حاسبة التقاعد» في مصر (`RetirementEgypt` — قانون 148/2019): المصري من النموذج بالحرف؛ الفصحى بنفس المعنى (المفاتيح لازم ليها
 * الثلاثة)؛ الإنجليزي كتابة Claude (مستني مراجعة المالك §40).
 */
internal val MSA_CALC_RETIRE_EG_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.RETEG_HERO_LABEL to "المعاش المتوقع شهريًا",
    TextKey.RETEG_HERO_SUB to "التقاعد عند {0} في {1}، {2} شهر اشتراك",
    TextKey.RETEG_GAP_SUB to "ينقصك {0} شهريًا بعد المعاش × {1} شهرًا = {2} − ما معك = {3} ÷ {4} شهرًا، بلا أرباح",
    TextKey.RETEG_CATEGORY to "كيف أنت مؤمَّن عليك؟",
    TextKey.RETEG_CATEGORY_NOTE to "تحدد سن المعاش (المادة ١ بند ١٠)",
    TextKey.RETEG_CAT_EMPLOYEE to "أعمل لدى غيري",
    TextKey.RETEG_CAT_SELF to "صاحب عمل أو أعمل خارج مصر",
    TextKey.RETEG_PRE to "منها قبل ٢٠٢٠",
    TextKey.RETEG_PRE_NOTE to "أي شهر قبل ٢٠٢٠ يجعل الحساب «غير متاح» (المادة ١٥٦)",
    TextKey.RETEG_LEGAL to "سن المعاش (٦٠–٦٥)",
    TextKey.RETEG_LEGAL_NOTE_TYPED to "من ٦٠ إلى ٦٥",
    TextKey.RETEG_LEGAL_NOTE_REQUIRED to "مطلوب: سنك غير مؤكد من القانون حتى يُنشر قرار التدرّج",
    TextKey.RETEG_LEGAL_NOTE_AUTO_SELF to "فارغ = {0} تلقائيًا (صاحب عمل أو خارج مصر)",
    TextKey.RETEG_LEGAL_NOTE_AUTO_2040 to "فارغ = {0} تلقائيًا (تبلغ ٦٠ بعد يوليو ٢٠٤٠)",
    TextKey.RETEG_RETIRE_NOTE to "فارغ = سن المعاش",
    TextKey.RETEG_SEC_WAGE to "أجرك",
    TextKey.RETEG_WAGE to "متوسط أجرك في التأمينات (أجر التسوية)",
    TextKey.RETEG_SEC_LIMITS to "حدود أجر الاشتراك سنة تقاعدك",
    TextKey.RETEG_MIN to "الحد الأدنى (اختياري)",
    TextKey.RETEG_MIN_NOTE to "يُحسب منه الحد الأدنى للمعاش",
    TextKey.RETEG_MAX to "الحد الأقصى (اختياري)",
    TextKey.RETEG_MAX_NOTE to "يُحسب منه سقف المعاش وسقف أجر التسوية",
    TextKey.RETEG_SUGGEST to "اقتراح فقط: آخر رقم رسمي {0} / {1} ({2}) — اكتبه في الخانتين",
    TextKey.RETEG_HOW_WAGE to "أجر التسوية: {0}",
    TextKey.RETEG_HOW_WAGE_CAPPED to " (قُصّ إلى الحد الأقصى لأجر الاشتراك — المادة ٢٢)",
    TextKey.RETEG_HOW_ACCRUED to "× {0} شهرًا ÷ ١٢ ÷ معامل {1} (جدول ٥: سنك {2} وسن المعاش {3}) = {4}",
    TextKey.RETEG_HOW_CAP to "السقف ٨٠٪ من أجر التسوية: {0}",
    TextKey.RETEG_HOW_MAX_CAP to "، و٨٠٪ من الحد الأقصى: {0}",
    TextKey.RETEG_HOW_EARLY to "معاش مبكر: لا يُرفع إلى الحد الأدنى (شرطه نصف أجر التسوية)",
    TextKey.RETEG_HOW_FLOOR to "الحد الأدنى: {0}",
    TextKey.RETEG_HOW_FLOOR_900_ONLY to " (٩٠٠ جنيه فقط — رقم سنة تقاعدك لم يُعلن بعد)",
    TextKey.RETEG_HOW_FLOOR_RULE to " (٦٥٪ من الحد الأدنى لأجر الاشتراك، ولا يقل عن ٩٠٠)",
    TextKey.RETEG_ASSUME to "فرض الحساب: الاشتراك والأجر مستمران كما هما حتى التقاعد، وما تدّخره بلا أرباح. حساب تقريبي للتخطيط، والرقم الرسمي من التأمينات.",
    TextKey.RETEG_SOURCES to "المصادر: قانون التأمينات الاجتماعية والمعاشات ١٤٨ لسنة ٢٠١٩ المواد ١ و٢١–٢٤ و٤١ وجدول ٥، اللائحة التنفيذية (قرار رئيس الوزراء ٢٤٣٧ لسنة ٢٠٢١) المواد ٥٣ و١٠٢–١٠٥، أرقام الهيئة القومية للتأمين الاجتماعي ٢٠٢١–٢٠٢٦.",
)

internal val EGYPTIAN_CALC_RETIRE_EG_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.RETEG_HERO_LABEL to "المعاش المتوقع في الشهر",
    TextKey.RETEG_HERO_SUB to "التقاعد على {0} في {1}، {2} شهر اشتراك",
    TextKey.RETEG_GAP_SUB to "ناقصك {0} في الشهر بعد المعاش × {1} شهر = {2} − اللي معاك = {3} ÷ {4} شهر، من غير أرباح",
    TextKey.RETEG_CATEGORY to "إنت مؤمَّن عليك إزاي؟",
    TextKey.RETEG_CATEGORY_NOTE to "بتحدد سن المعاش (مادة ١ بند ١٠)",
    TextKey.RETEG_CAT_EMPLOYEE to "بشتغل عند حد",
    TextKey.RETEG_CAT_SELF to "صاحب عمل أو شغال برّه مصر",
    TextKey.RETEG_PRE to "منهم قبل ٢٠٢٠",
    TextKey.RETEG_PRE_NOTE to "أي شهر قبل ٢٠٢٠ بيخلّي الحسبة «غير متاح» (مادة ١٥٦)",
    TextKey.RETEG_LEGAL to "سن المعاش (٦٠–٦٥)",
    TextKey.RETEG_LEGAL_NOTE_TYPED to "من ٦٠ لـ٦٥",
    TextKey.RETEG_LEGAL_NOTE_REQUIRED to "مطلوب: سنك مش مؤكد من القانون لحد ما قرار التدرّج يتنشر",
    TextKey.RETEG_LEGAL_NOTE_AUTO_SELF to "فاضي = {0} تلقائي (صاحب عمل أو برّه مصر)",
    TextKey.RETEG_LEGAL_NOTE_AUTO_2040 to "فاضي = {0} تلقائي (هتتم ٦٠ بعد يوليو ٢٠٤٠)",
    TextKey.RETEG_RETIRE_NOTE to "فاضي = سن المعاش",
    TextKey.RETEG_SEC_WAGE to "أجرك",
    TextKey.RETEG_WAGE to "متوسط مرتبك في التأمينات (أجر التسوية)",
    TextKey.RETEG_SEC_LIMITS to "حدود أجر الاشتراك سنة تقاعدك",
    TextKey.RETEG_MIN to "الحد الأدنى (اختياري)",
    TextKey.RETEG_MIN_NOTE to "ليه الحد الأدنى للمعاش",
    TextKey.RETEG_MAX to "الحد الأقصى (اختياري)",
    TextKey.RETEG_MAX_NOTE to "ليه سقف المعاش وسقف أجر التسوية",
    TextKey.RETEG_SUGGEST to "اقتراح بس: آخر رقم رسمي {0} / {1} ({2}) — اكتبه في الخانتين",
    TextKey.RETEG_HOW_WAGE to "أجر التسوية: {0}",
    TextKey.RETEG_HOW_WAGE_CAPPED to " (اتقص للحد الأقصى لأجر الاشتراك — مادة ٢٢)",
    TextKey.RETEG_HOW_ACCRUED to "× {0} شهر ÷ ١٢ ÷ معامل {1} (جدول ٥: سنك {2} وسن المعاش {3}) = {4}",
    TextKey.RETEG_HOW_CAP to "السقف ٨٠٪ من أجر التسوية: {0}",
    TextKey.RETEG_HOW_MAX_CAP to "، و٨٠٪ من الحد الأقصى: {0}",
    TextKey.RETEG_HOW_EARLY to "معاش مبكر: ما بيترفعش للحد الأدنى (شرطه نص أجر التسوية)",
    TextKey.RETEG_HOW_FLOOR to "الحد الأدنى: {0}",
    TextKey.RETEG_HOW_FLOOR_900_ONLY to " (٩٠٠ جنيه بس — رقم سنة تقاعدك لسه ما اتعلنش)",
    TextKey.RETEG_HOW_FLOOR_RULE to " (٦٥٪ من الحد الأدنى لأجر الاشتراك، ومش أقل من ٩٠٠)",
    TextKey.RETEG_ASSUME to "فرض الحسبة: الاشتراك والأجر مستمرين زي ما هم لحد التقاعد، واللي بتحوّشه من غير أرباح. حساب تقريبي للتخطيط، والرقم الرسمي من التأمينات.",
    TextKey.RETEG_SOURCES to "المصادر: قانون التأمينات الاجتماعية والمعاشات ١٤٨ لسنة ٢٠١٩ م١ و٢١–٢٤ و٤١ وجدول ٥، اللايحة التنفيذية (قرار رئيس الوزراء ٢٤٣٧ لسنة ٢٠٢١) م٥٣ و١٠٢–١٠٥، أرقام الهيئة القومية للتأمين الاجتماعي ٢٠٢١–٢٠٢٦.",
)

internal val ENGLISH_CALC_RETIRE_EG_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.RETEG_HERO_LABEL to "Expected monthly pension",
    TextKey.RETEG_HERO_SUB to "Retiring at {0} in {1}, {2} contribution months",
    TextKey.RETEG_GAP_SUB to "{0} a month short after the pension × {1} months = {2} − what you have = {3} ÷ {4} months, without returns",
    TextKey.RETEG_CATEGORY to "How are you insured?",
    TextKey.RETEG_CATEGORY_NOTE to "Sets the pension age (art. 1 item 10)",
    TextKey.RETEG_CAT_EMPLOYEE to "I work for an employer",
    TextKey.RETEG_CAT_SELF to "Business owner or working abroad",
    TextKey.RETEG_PRE to "Of which before 2020",
    TextKey.RETEG_PRE_NOTE to "Any month before 2020 makes the calculation “not available” (art. 156)",
    TextKey.RETEG_LEGAL to "Pension age (60–65)",
    TextKey.RETEG_LEGAL_NOTE_TYPED to "From 60 to 65",
    TextKey.RETEG_LEGAL_NOTE_REQUIRED to "Required: your age is not certain from the law until the phase-in decision is published",
    TextKey.RETEG_LEGAL_NOTE_AUTO_SELF to "Empty = {0} automatically (business owner or abroad)",
    TextKey.RETEG_LEGAL_NOTE_AUTO_2040 to "Empty = {0} automatically (you turn 60 after July 2040)",
    TextKey.RETEG_RETIRE_NOTE to "Empty = the pension age",
    TextKey.RETEG_SEC_WAGE to "Your wage",
    TextKey.RETEG_WAGE to "Your average insured wage (settlement wage)",
    TextKey.RETEG_SEC_LIMITS to "Contribution wage limits in your retirement year",
    TextKey.RETEG_MIN to "Minimum (optional)",
    TextKey.RETEG_MIN_NOTE to "Used for the minimum pension",
    TextKey.RETEG_MAX to "Maximum (optional)",
    TextKey.RETEG_MAX_NOTE to "Used for the pension cap and the settlement wage cap",
    TextKey.RETEG_SUGGEST to "Suggestion only: latest official figures {0} / {1} ({2}) — fill both fields",
    TextKey.RETEG_HOW_WAGE to "Settlement wage: {0}",
    TextKey.RETEG_HOW_WAGE_CAPPED to " (cut to the maximum contribution wage — art. 22)",
    TextKey.RETEG_HOW_ACCRUED to "× {0} months ÷ 12 ÷ factor {1} (table 5: your age {2}, pension age {3}) = {4}",
    TextKey.RETEG_HOW_CAP to "Cap of 80% of the settlement wage: {0}",
    TextKey.RETEG_HOW_MAX_CAP to ", and 80% of the maximum: {0}",
    TextKey.RETEG_HOW_EARLY to "Early pension: not raised to the minimum (its condition is half the settlement wage)",
    TextKey.RETEG_HOW_FLOOR to "Minimum: {0}",
    TextKey.RETEG_HOW_FLOOR_900_ONLY to " (EGP 900 only — your retirement year's figure is not announced yet)",
    TextKey.RETEG_HOW_FLOOR_RULE to " (65% of the minimum contribution wage, and not below 900)",
    TextKey.RETEG_ASSUME to "Assumption: contributions and wage continue as they are until retirement, and savings earn no returns. An approximate planning estimate; the official figure comes from social insurance.",
    TextKey.RETEG_SOURCES to "Sources: Social Insurance and Pensions Law 148 of 2019 arts. 1, 21–24 and 41 and table 5, executive regulations (Prime Minister's decree 2437 of 2021) arts. 53 and 102–105, National Organization for Social Insurance figures 2021–2026.",
)
