package app.masroufy.core

/** منطقة «الأشخاص» بالفصحى (السعودية والافتراضي) — المناسبات · الأحداث · التجهيزات · ربط المصروف · النقوط · المشاريع. */
internal val MSA_PEOPLE_AREA_2: Map<UiKey, String> = mapOf(
    // ── المناسبة (OccasionSheet)
    UiKey.OCC_ADD to "+ أضف مناسبة",
    UiKey.OCC_ADD_FOR to "+ أضف مناسبة لـ{0}",
    UiKey.OCC_CHIP_BIRTHDAY to "عيد ميلاد",
    UiKey.OCC_CHIP_ANNIV to "ذكرى زواج",
    UiKey.OCC_CHIP_WEDDING to "زواج",
    UiKey.OCC_CHIP_OTHER to "أخرى",
    UiKey.OCC_CHIP_DAY to "بيوم",
    UiKey.OCC_CHIP_WEEK to "بأسبوع",
    UiKey.OCC_CHIP_TWO_WEEKS to "بأسبوعين",
    UiKey.OCC_CHIP_MONTH to "بشهر",
    UiKey.OCC_EDIT to "تعديل",
    UiKey.OCC_LABEL_PH to "اسمها، مثلًا: تخرّجه",
    UiKey.OCC_LEAD_DAYS to "قبلها بـ{0}",
    UiKey.OCC_LEAD_LABEL to "متى نذكّرك؟",
    UiKey.OCC_LEAD_MONTH to "قبلها بشهر",
    UiKey.OCC_LEAD_ONE to "قبلها بيوم",
    UiKey.OCC_LEAD_TWO to "قبلها بيومين",
    UiKey.OCC_LEAD_TWO_WEEKS to "قبلها بأسبوعين",
    UiKey.OCC_LEAD_WEEK to "قبلها بأسبوع",
    UiKey.OCC_LESS to "يوم أقل",
    UiKey.OCC_MORE to "يوم إضافي",
    UiKey.OCC_NEED_DAY to "اكتب اليوم (من 1 إلى 31).",
    UiKey.OCC_NEED_LABEL to "اكتب اسم المناسبة.",
    UiKey.OCC_NEED_MONTH to "اختر الشهر.",
    UiKey.OCC_NEXT to "المرة القادمة: {0}",
    UiKey.OCC_ONCE to "مرة واحدة",
    UiKey.OCC_YEARLY to "كل سنة",
    UiKey.OCC_PAST to "هذا التاريخ مضى — ولمرة واحدة لن تتكرر.",
    UiKey.OCC_PICK to "اختر الشهر واليوم.",
    UiKey.OCC_REMIND_NOW to "ضمن مدة التذكير — تظهر في التنبيهات مباشرة.",
    UiKey.OCC_REMIND_PLAIN to "يصلك التذكير في وقتك المعتاد.",
    UiKey.OCC_REMIND_PREFIX to "التذكير {0}",
    UiKey.OCC_REMIND_USUAL to "يصلك التذكير في وقتك المعتاد، {0}.",
    UiKey.OCC_REMOVE to "احذف المناسبة",
    UiKey.OCC_REMOVE_CONFIRM to "اضغط مرة أخرى للحذف",
    UiKey.OCC_SAVE_NEW to "أضفها",
    UiKey.OCC_TITLE_EDIT to "تعديل المناسبة",
    UiKey.OCC_TITLE_FOR to "مناسبة لـ{0}",
    UiKey.OCC_TITLE_OWN to "مناسبة لك",
    // ── الأحداث (Events)
    UiKey.EVENTS_TITLE to "الأحداث",
    UiKey.EVENTS_NEW to "حدث جديد",
    UiKey.EVENTS_ACTIVE to "النشطة ({0})",
    UiKey.EVENTS_ARCHIVED to "المؤرشفة ({0})",
    UiKey.EVENTS_EMPTY_TITLE to "لا أحداث بعد",
    UiKey.EVENTS_EMPTY_BODY to "أضف زواجًا أو سفرًا أو مناسبة لنجمع مصروفها ونقوطها.",
    UiKey.EVENTS_GAVE to "ما نقّطته",
    UiKey.EVENTS_GAVE_CONDOLENCE to "ما قدّمته",
    UiKey.EVENTS_GIFTS_IN to "النقوط التي جاءتك",
    UiKey.EVENTS_NEXT to "أقرب حدث",
    UiKey.EVENTS_NOT_LINKED to "لم يُربط بعد",
    UiKey.EVENTS_NOT_YET to "لم تنقّطه بعد",
    UiKey.EVENTS_OTHER_OWNER to "حدث شخص آخر",
    UiKey.EVENTS_SPEND to "المصروف",
    // ── صفحة الحدث (EventDetail)
    UiKey.EVENT_DETAIL_GIFTS_NONE to "لا شيء بعد",
    UiKey.EVENT_DETAIL_HOST to "صاحبه: {0}",
    UiKey.EVENT_DETAIL_NOTE_MINE to "النقوط للمعلومية فقط — لا تُطرح من المصروف.",
    UiKey.EVENT_DETAIL_NOTE_OTHER to "حدث {0} — نقوطه لا تظهر هنا، بل ما قدّمته أنت.",
    UiKey.EVENT_DETAIL_NO_GIFTS_MINE to "لا نقوط مسجّلة بعد.",
    UiKey.EVENT_DETAIL_NO_GIFTS_OTHER to "لم تسجّل شيئًا بعد.",
    UiKey.EVENT_DETAIL_NO_PREP_CONDOLENCE to "لا تجهيزات للعزاء.",
    UiKey.EVENT_DETAIL_NO_PREP_PAST to "التجهيزات للأحداث القادمة فقط.",
    UiKey.EVENT_DETAIL_NO_SPEND to "لا مصروف مربوطًا بهذا الحدث بعد.",
    UiKey.EVENT_DETAIL_PREP to "التجهيزات",
    UiKey.EVENT_DETAIL_PREP_DONE to "اكتمل {0}",
    UiKey.EVENT_DETAIL_PREP_NONE_DONE to "لم يكتمل أي بند",
    UiKey.EVENT_DETAIL_REMIND to "ذكّرني به كل سنة",
    UiKey.EVENT_DETAIL_REMIND_WEDDING to "ذكّرني بذكرى الزواج كل سنة",
    UiKey.EVENT_DETAIL_REMIND_OFF to "أُوقف التذكير",
    UiKey.EVENT_DETAIL_REMIND_ON to "سنذكّرك {0} كل سنة",
    UiKey.EVENT_DETAIL_REMIND_SUB to "{0} — لهدية أو احتفال",
    UiKey.EVENT_DETAIL_SHARE_OF to "{0}% من {1}",
    UiKey.EVENT_DETAIL_SPEND to "المصروف عليه",
    UiKey.EVENT_DETAIL_SPEND_TITLE to "المصروف",
    UiKey.EVENT_DETAIL_WHOLE to "العملية كاملة",
    // ── إضافة الحدث وتعديله (EventAddSheet · EventEditSheet)
    UiKey.EVENT_FORM_ADD to "أضفه",
    UiKey.EVENT_FORM_ADDED to "أُضيف «{0}»",
    UiKey.EVENT_FORM_ARCHIVED_SUB to "يختفي من النشطة، وتبقى عملياته ونقوطه — لا يُحذف.",
    UiKey.EVENT_FORM_DATE_NOTE to "يظهر في التقويم في يومه، ويذكّرك قبله.",
    UiKey.EVENT_FORM_EDIT_OPEN to "تعديل الحدث",
    UiKey.EVENT_FORM_EDIT_TITLE to "تعديل الحدث",
    UiKey.EVENT_FORM_HINT to "بلا مبلغ الآن — التجهيزات ومبالغها والنقوط من صفحة الحدث.",
    UiKey.EVENT_FORM_HOST_NOTE to "حدث {0}: يظهر فيه ما نقّطته أنت فقط، لا النقوط التي جاءته.",
    UiKey.EVENT_FORM_KIND to "نوعه",
    UiKey.EVENT_FORM_LOCK_MINE to "عليه نقوط جاءتك — يبقى حدثك، لأن النقوط التي جاءتك تُسجَّل في حدثك فقط.",
    UiKey.EVENT_FORM_ME to "حدثي",
    UiKey.EVENT_FORM_NAME to "اسم الحدث",
    UiKey.EVENT_FORM_NAME_PH to "مثلًا: خطوبة يوسف",
    UiKey.EVENT_FORM_NEED_NAME to "اكتب اسم الحدث.",
    UiKey.EVENT_FORM_NEW to "حدث جديد",
    UiKey.EVENT_FORM_SCHOOL_NOTE to "بداية الدراسة تضيفها أنت حدثًا — لا من تقويم رسمي.",
    UiKey.EVENT_FORM_WHEN to "متى؟",
    UiKey.EVENT_FORM_WHO to "حدث مَن؟",
    // ── التجهيزات (EventPrep)
    UiKey.EVENT_PREP_TITLE to "تجهيزات {0}",
    UiKey.EVENT_PREP_ADD to "أضف",
    UiKey.EVENT_PREP_ALL_DONE to "اكتملت كل البنود ✓",
    UiKey.EVENT_PREP_ALL_PRICED to "كل البنود لها مبلغ",
    UiKey.EVENT_PREP_AMOUNT_ERR to "يجب أن يكون المبلغ أكبر من صفر — أو اتركه بلا مبلغ.",
    UiKey.EVENT_PREP_ASSIGN to "وزّعه على:",
    UiKey.EVENT_PREP_ASSIGNED to "وُزّع على «{0}»",
    UiKey.EVENT_PREP_BLOCK_CONDOLENCE_TITLE to "لا تجهيزات للعزاء",
    UiKey.EVENT_PREP_BLOCK_CONDOLENCE_BODY to "مصروفه وما قدّمته في صفحة الحدث.",
    UiKey.EVENT_PREP_BLOCK_PAST_TITLE to "انتهى هذا الحدث",
    UiKey.EVENT_PREP_DONE_LABEL to "اكتمل: {0}",
    UiKey.EVENT_PREP_ITEMS to "البنود ({0})",
    UiKey.EVENT_PREP_LEFT to "باقٍ {0}",
    UiKey.EVENT_PREP_LOOSE_LINE to "ليس على بند: {0}",
    UiKey.EVENT_PREP_LOOSE_TITLE to "مصروف ليس على بند",
    UiKey.EVENT_PREP_NEW to "بند جديد",
    UiKey.EVENT_PREP_NOT_SPENT to "لم يُصرف بعد",
    UiKey.EVENT_PREP_NO_AMOUNT to "بلا مبلغ",
    UiKey.EVENT_PREP_NO_ITEMS to "لا بنود بعد",
    UiKey.EVENT_PREP_NO_PRICED to "لا مبلغ لأي بند",
    UiKey.EVENT_PREP_OTHER_CURRENCY to "{0} بعملة أخرى خارج المجموع",
    UiKey.EVENT_PREP_OVER to "تجاوز",
    UiKey.EVENT_PREP_PLANNED to "المخطط",
    UiKey.EVENT_PREP_PLANNED_INPUT to "المبلغ المخطط",
    UiKey.EVENT_PREP_PLANNED_OF to "مخطط {0}",
    UiKey.EVENT_PREP_REMOVE to "احذف البند",
    UiKey.EVENT_PREP_REMOVED to "حُذف البند",
    UiKey.EVENT_PREP_REMOVED_SPENT to "حُذف البند — وبقي مصروفه على الحدث بلا بند",
    UiKey.EVENT_PREP_SPENT to "المصروف",
    UiKey.EVENT_PREP_SPENT_OF to "صُرف {0}",
    UiKey.EVENT_PREP_SUG_TITLE to "بنود مقترحة",
    UiKey.EVENT_PREP_SUG_BODY to "اختر ما يخصك — بلا مبالغ، وتضيف المبلغ لاحقًا إن شئت.",
    UiKey.EVENT_PREP_SUG_PICK to "اختر بندًا واحدًا على الأقل",
    UiKey.EVENT_PREP_SUG_SAVE to "احفظ {0}",
    UiKey.EVENT_PREP_SUG_SAVED to "حُفظ {0} بلا مبالغ",
    UiKey.EVENT_PREP_UNPRICED to "+ {0} بلا مبلغ",
    // ── ربط مصروف بالحدث (EventSpendLinkSheet)
    UiKey.SPEND_LINK_OPEN to "اربط مصروفًا بنسبة",
    UiKey.SPEND_LINK_TITLE to "اربط مصروفًا بـ«{0}»",
    UiKey.SPEND_LINK_INTRO to "اختر عملية أو أكثر، وحدّد نصيب الحدث من كل واحدة.",
    UiKey.SPEND_LINK_SEARCH to "ابحث باسم المتجر أو المبلغ",
    UiKey.SPEND_LINK_LIST to "مصروفك الأخير",
    UiKey.SPEND_LINK_HINT to "آخر 30 يومًا، والأحدث أولًا. تُربط العملية بحدث واحد فقط.",
    UiKey.SPEND_LINK_HERE to "مربوطة بهذا الحدث",
    UiKey.SPEND_LINK_OTHER_EVENT to "مربوطة بـ«{0}» — فكّها من صفحة العملية أولًا",
    UiKey.SPEND_LINK_NONE to "لا مصروف في آخر 30 يومًا.",
    UiKey.SPEND_LINK_NO_MATCH to "لا عمليات تطابق «{0}»",
    UiKey.SPEND_LINK_PART to "نصيب الحدث، ويبقى الباقي عاديًا",
    UiKey.SPEND_LINK_WHOLE to "العملية كاملة على الحدث",
    UiKey.SPEND_LINK_RANGE to "النسبة من 1 إلى 100",
    UiKey.SPEND_LINK_TAG_NOTE to "الربط علامة على العملية — لا يغيّر مصروف الشهر ولا تصنيفها، وتُحفظ النسبة مع الربط.",
    UiKey.SPEND_LINK_TOTAL to "يُضاف إلى مصروف الحدث",
    UiKey.SPEND_LINK_NOT_PICKED to "لم تختر بعد",
    UiKey.SPEND_LINK_PICK_HINT to "اختر عملية من القائمة.",
    UiKey.SPEND_LINK_EACH to "{0} — كلٌّ منها بنصيبه.",
    UiKey.SPEND_LINK_BAD_PCT_SUB to "إحدى النسب خارج 1–100.",
    UiKey.SPEND_LINK_SAVE to "اربط {0}",
    UiKey.SPEND_LINK_SAVE_EMPTY to "اربط بالحدث",
    UiKey.SPEND_LINK_NEED_ONE to "اختر عملية واحدة على الأقل.",
    UiKey.SPEND_LINK_NEED_PCT to "نسبة كل عملية يجب أن تكون من 1 إلى 100.",
    UiKey.SPEND_LINK_DONE to "رُبطت {0} بـ«{1}» — أُضيف {2} إلى مصروفه",
    // ── النقوط (NuqootSheet)
    UiKey.NUQOOT_OPEN_MINE to "سجّل النقوط التي جاءتك",
    UiKey.NUQOOT_OPEN_OTHER to "سجّل {0}",
    UiKey.NUQOOT_MODE_CASH to "نقوط كاش",
    UiKey.NUQOOT_MODE_LINK to "عملية موجودة",
    UiKey.NUQOOT_WALLET to "في أي محفظة؟",
    UiKey.NUQOOT_ROWS to "لكل اسم مبلغه",
    UiKey.NUQOOT_NAME to "الاسم",
    UiKey.NUQOOT_ADD_ROW to "+ اسم آخر",
    UiKey.NUQOOT_SUM to "المجموع {0}، {1} في «{2}»",
    UiKey.NUQOOT_EACH to "كل اسم يصبح عملية مستقلة في المحفظة.",
    UiKey.NUQOOT_KIND_NOTE to "تُصنَّف «هدايا › نقوط» تلقائيًا، ولن تُسأل عنها في المراجعات.",
    UiKey.NUQOOT_SAVE to "سجّل",
    UiKey.NUQOOT_SAVE_N to "سجّل {0}",
    UiKey.NUQOOT_SAVE_LINK to "اربطها نقطةً",
    UiKey.NUQOOT_NEED_ONE to "أضف نقطة واحدة على الأقل بمبلغ أكبر من صفر.",
    UiKey.NUQOOT_FILL_ROWS to "أكمل الاسم والمبلغ في كل سطر.",
    UiKey.NUQOOT_DUP to "الاسم نفسه مكرر — كل نقطة لاسم واحد.",
    UiKey.NUQOOT_NEED_TXN to "اختر العملية أولًا.",
    UiKey.NUQOOT_NEED_WHO to "اختر الشخص.",
    UiKey.NUQOOT_NO_CANDIDATES to "لا عمليات مناسبة في آخر 30 يومًا.",
    UiKey.NUQOOT_NO_WALLET to "أضف محفظة أولًا.",
    UiKey.NUQOOT_LINKED to "رُبطت العملية نقطةً",
    UiKey.NUQOOT_DONE to "سُجّلت {0} — عملية لكل اسم في «{1}»",
    // ── المشاريع (Projects)
    UiKey.PROJECTS_TITLE to "المشاريع",
    UiKey.PROJECTS_NEW to "مشروع جديد",
    UiKey.PROJECTS_INTRO to "المشروع وسم إضافي: تبقى العملية بتصنيفها، ولا يتغير أي مجموع عام.",
    UiKey.PROJECTS_EMPTY_TITLE to "لا مشاريع بعد",
    UiKey.PROJECTS_EMPTY_BODY to "رحلة أو تجهيز أو عمل جانبي: أنشئ مشروعًا لتعرف كم كلّفك أو كم كسبت.",
    UiKey.PROJECTS_KIND_PERSONAL to "شخصي",
    UiKey.PROJECTS_KIND_WORK to "عمل",
    UiKey.PROJECTS_Q_PERSONAL to "كم كلّفني؟",
    UiKey.PROJECTS_Q_WORK to "كم كسبت منه؟",
    UiKey.PROJECTS_LINE to "صرفت {0}، جاءك {1}",
    UiKey.PROJECTS_NO_OPS to "لا عمليات بعد",
    UiKey.PROJECTS_NO_DEADLINE to "بلا موعد",
    UiKey.PROJECTS_PASSED to "فات",
    UiKey.PROJECTS_APPROX to "تقريبي، {0} بانتظار تأكيد النوع",
    UiKey.PROJECTS_ARCHIVED to "المؤرشفة ({0})",
    UiKey.PROJECTS_RESTORE to "إرجاع",
    UiKey.PROJECTS_RESTORED to "عاد «{0}» إلى النشطة",
    UiKey.PROJECTS_ARCH_NOTE to "المؤرشف مغلق: قواعده متوقفة، ولا حذف.",
    UiKey.PROJECTS_ASK_KIND to "هل المشروع شخصي أم عمل؟",
    UiKey.PROJECTS_EX_PERSONAL to "زواج، سفر، تجهيز منزل — الوارد يُنقص الكلفة",
    UiKey.PROJECTS_EX_WORK to "عميل، دوام جزئي، عمل جانبي — الصافي قد يكون سالبًا",
    UiKey.PROJECTS_NAME to "الاسم",
    UiKey.PROJECTS_NAME_PH to "مثلًا: رحلة العيد",
    UiKey.PROJECTS_DEADLINE to "آخر موعد (اختياري)",
    UiKey.PROJECTS_DEADLINE_NOTE to "إن حدّدته يظهر المشروع في التقويم يومها.",
    UiKey.PROJECTS_CREATE to "أنشئ المشروع",
    UiKey.PROJECTS_CREATED to "أُنشئ «{0}»",
    UiKey.PROJECTS_EDIT_TITLE to "تعديل المشروع",
    // ── صفحة المشروع (ProjectDetail)
    UiKey.PROJECT_DETAIL_EDIT to "تعديل الاسم والموعد",
    UiKey.PROJECT_DETAIL_ARCHIVE to "أرشفة المشروع",
    UiKey.PROJECT_DETAIL_ARCHIVED to "أُرشف «{0}» — لم يُحذف شيء",
    UiKey.PROJECT_DETAIL_UNTIL to "حتى {0}",
    UiKey.PROJECT_DETAIL_OUT to "صرفت (نصيبك)",
    UiKey.PROJECT_DETAIL_IN to "جاءك",
    UiKey.PROJECT_DETAIL_FORMULA_WORK to "الصافي = ما جاءك − ما صرفت، وقد يكون سالبًا.",
    UiKey.PROJECT_DETAIL_FORMULA_PERSONAL to "ما جاءك (نقوط أو هدايا) يُنقص الكلفة.",
    UiKey.PROJECT_DETAIL_TAB_OPS to "العمليات ({0})",
    UiKey.PROJECT_DETAIL_TAB_RULES to "القواعد ({0})",
    UiKey.PROJECT_DETAIL_NO_OPS to "لا عمليات في المشروع بعد",
    UiKey.PROJECT_DETAIL_SRC_RULE to "بقاعدة",
    UiKey.PROJECT_DETAIL_SRC_MANUAL to "أضفتها بنفسك",
    UiKey.PROJECT_DETAIL_UNSURE to "نوعها غير مؤكد",
    UiKey.PROJECT_DETAIL_REMOVE_OP to "أزل {0} من المشروع",
    UiKey.PROJECT_DETAIL_ADD_HINT to "لإضافة عملية بنفسك: من نقاطها الثلاث ← «أضف إلى مشروع». ويمكن أن تكون العملية في أكثر من مشروع.",
    UiKey.PROJECT_DETAIL_RULES_INTRO to "تضيف القاعدة الجديد تلقائيًا، ونسألك عن السابق عند إنشائها.",
    UiKey.PROJECT_DETAIL_MODE_CONTAINS to "يحتوي",
    UiKey.PROJECT_DETAIL_MODE_STARTS to "يبدأ بـ",
    UiKey.PROJECT_DETAIL_MODE_EXACT to "مطابق",
    UiKey.PROJECT_DETAIL_QUOTED to "«{0}»",
    UiKey.PROJECT_DETAIL_DIR to "الاتجاه: {0}",
    UiKey.PROJECT_DETAIL_DIR_OUT to "صادر",
    UiKey.PROJECT_DETAIL_DIR_IN to "وارد",
    UiKey.PROJECT_DETAIL_DIR_ANY to "كلاهما",
    UiKey.PROJECT_DETAIL_RULE_SWITCH to "تشغيل قاعدة {0}",
    UiKey.PROJECT_DETAIL_NEW_RULE to "قاعدة جديدة",
    UiKey.PROJECT_DETAIL_RULE_TITLE to "قاعدة للمشروع",
    UiKey.PROJECT_DETAIL_RULE_TEXT to "النص في اسم التاجر أو الوصف",
    UiKey.PROJECT_DETAIL_RULE_PH to "مثلًا: العلا",
    UiKey.PROJECT_DETAIL_RULE_ERR to "نص القاعدة من حرفين إلى 60 حرفًا.",
    UiKey.PROJECT_DETAIL_MODE_LABEL to "طريقة المطابقة",
    UiKey.PROJECT_DETAIL_DIR_LABEL to "الاتجاه",
    UiKey.PROJECT_DETAIL_NEXT to "التالي",
    UiKey.PROJECT_DETAIL_OLD_TITLE to "هل نضيف السابق أيضًا؟",
    UiKey.PROJECT_DETAIL_OLD_BODY to "من العمليات السابقة (آخر 3 سنوات) تطابقها: {0}",
    UiKey.PROJECT_DETAIL_OLD_NONE to "لا عمليات سابقة تطابقها. ستُضاف الجديدة تلقائيًا.",
    UiKey.PROJECT_DETAIL_ADD_OLD to "نعم، أضف السابقة أيضًا",
    UiKey.PROJECT_DETAIL_NEW_ONLY to "لا، الجديدة فقط",
    UiKey.PROJECT_DETAIL_OK to "تم",
    UiKey.PROJECT_DETAIL_OLD_ADDED to "أُضيف إلى المشروع: {0}",
)
