package app.masroufy.core

/**
 * «الاستيراد» ١/٥: المشترك (العدّ · غير مصنّف) + `BankSms` + `SmsWaiting` + `CategoryPicker`. النص من النموذج التفاعلي بالحرف (الفصحى من
 * `space = السعودية` والمصري من `مصر`)، واللي مالوش مقابل في النموذج (حالات المنطق الزيادة) كتابة Claude بنفس النبرة.
 */
internal val MSA_IMPORTS_SMS_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.IMPORTS_DRAFT_GONE to "لم نعد نجد هذا الملف",
    TextKey.IMPORTS_DRAFT_GONE_BODY to "أُغلق التطبيق قبل التأكيد، ولم يُسجَّل شيء. اختر الملف من جديد.",
    TextKey.IMPORTS_LOAD_FAILED to "تعذّر التحميل",
    TextKey.IMPORTS_RETRY to "أعد المحاولة",
    TextKey.IMPORTS_SEP to "، ",
    TextKey.IMPORTS_QUOTED to "«{0}»",
    TextKey.IMPORTS_UNCATEGORIZED to "غير مصنّف",
    TextKey.IMPORTS_OPS_ONE to "عملية واحدة",
    TextKey.IMPORTS_OPS_TWO to "عمليتان",
    TextKey.IMPORTS_OPS_FEW to "{0} عمليات",
    TextKey.IMPORTS_OPS_MANY to "{0} عملية",
    TextKey.IMPORTS_MSGS_ONE to "رسالة واحدة",
    TextKey.IMPORTS_MSGS_TWO to "رسالتان",
    TextKey.IMPORTS_MSGS_FEW to "{0} رسائل",
    TextKey.IMPORTS_MSGS_MANY to "{0} رسالة",
    TextKey.IMPORTS_LINES_ONE to "سطر واحد",
    TextKey.IMPORTS_LINES_TWO to "سطران",
    TextKey.IMPORTS_LINES_FEW to "{0} أسطر",
    TextKey.IMPORTS_LINES_MANY to "{0} سطرًا",
    TextKey.IMPORTS_PAGES_ONE to "صفحة واحدة",
    TextKey.IMPORTS_PAGES_TWO to "صفحتان",
    TextKey.IMPORTS_PAGES_FEW to "{0} صفحات",
    TextKey.IMPORTS_PAGES_MANY to "{0} صفحة",
    TextKey.BANK_SMS_TITLE to "رسائل البنك",
    TextKey.BANK_SMS_GEAR to "إعداد القراءة",
    TextKey.BANK_SMS_STATUS_OK to "القراءة تعمل",
    TextKey.BANK_SMS_STATUS_OK_BODY to "الرسالة المفهومة تُسجَّل وتُصنَّف تلقائيًا.",
    TextKey.BANK_SMS_STATUS_STOPPED to "القراءة متوقفة",
    TextKey.BANK_SMS_STATUS_PERM_BODY to "سُحب إذن الرسائل من إعدادات الجوال.",
    TextKey.BANK_SMS_STATUS_OFF_BODY to "أوقفتَ القراءة التلقائية. شغّلها من إعداد القراءة.",
    TextKey.BANK_SMS_STATUS_IOS to "الآيفون لا يسمح",
    TextKey.BANK_SMS_STATUS_IOS_BODY to "لا تسمح أبل بقراءة الرسائل. يمكنك لصق الرسالة يدويًا.",
    TextKey.BANK_SMS_REGRANT to "أعد الإذن",
    TextKey.BANK_SMS_OPEN_SETTINGS to "الإعداد",
    TextKey.BANK_SMS_PASTE to "الصق رسالة",
    TextKey.BANK_SMS_EMPTY_TITLE to "لا رسائل اليوم",
    TextKey.BANK_SMS_EMPTY_BODY to "حين تصل رسالة من البنك ستُسجَّل هنا تلقائيًا.",
    TextKey.BANK_SMS_AUTO_TITLE to "سُجّلت تلقائيًا اليوم",
    TextKey.BANK_SMS_SUGGESTED to "مقترح",
    TextKey.BANK_SMS_NEW_SHOP to "متجر جديد",
    TextKey.BANK_SMS_CONFIRM to "تأكيد",
    TextKey.BANK_SMS_CATEGORIZE to "صنّفها",
    TextKey.BANK_SMS_FOOTER to "يصلك إشعار الجوال فقط للرسائل التي تنتظر تأكيدك، من مجموعة",
    TextKey.BANK_SMS_FOOTER_LINK to "«رسائل البنك»",
    TextKey.BANK_SMS_REMEMBERED to "تم — «{0}» سيُصنَّف «{1}» دائمًا",
    TextKey.BANK_SMS_RECORDED to "سُجّلت {0}",
    TextKey.BANK_SMS_DROPPED to "حُذفت الرسالة",
    TextKey.BANK_SMS_HAND_SAVED to "سُجّلت — بقي تصنيفها",
    TextKey.BANK_SMS_WALLET_SAVED to "سُجّلت {0} في «{1}»",
    TextKey.SMS_WAITING_TITLE to "بانتظار تأكيدك",
    TextKey.SMS_WAITING_ALL_DONE to "لا شيء بانتظارك — سُجّل كل شيء.",
    TextKey.SMS_WAITING_BANK_TITLE to "رسائل من بنك جديد",
    TextKey.SMS_WAITING_BANK_BODY to "وصلتك {0} من «{1}». في أي محفظة تُسجَّل؟",
    TextKey.SMS_WAITING_BANK_ONCE to "تختار مرة واحدة فقط، ثم تُسجَّل رسائل هذا البنك تلقائيًا.",
    TextKey.SMS_WAITING_PICK_WALLET to "اختر المحفظة",
    TextKey.SMS_WAITING_CONFIRM_TITLE to "رسائل تحتاج تأكيدك",
    TextKey.SMS_WAITING_SIMILAR_TITLE to "تشبه عملية موجودة",
    TextKey.SMS_WAITING_CONFLICT_TITLE to "المرجع نفسه بتفاصيل مختلفة",
    TextKey.SMS_WAITING_FROM_MESSAGE to "من الرسالة",
    TextKey.SMS_WAITING_SAME_DROP to "هي نفسها — احذفها",
    TextKey.SMS_WAITING_RECORD_IT to "لا، سجّلها",
    TextKey.SMS_WAITING_WILL_RECORD to "ستُسجَّل مع الكل",
    TextKey.SMS_WAITING_UNCLEAR_TITLE to "رسالة لم تُفهم",
    TextKey.SMS_WAITING_REASON to "السبب: {0}",
    TextKey.SMS_WAITING_FOREIGN_NOTE to "بعملة أجنبية: سؤال المبلغ بعملتك لم يُبنَ بعد — سجّلها يدويًا.",
    TextKey.SMS_WAITING_DROP to "احذفها",
    TextKey.SMS_WAITING_BY_HAND to "سجّلها يدويًا",
    TextKey.SMS_WAITING_SAVE to "سجّل",
    TextKey.SMS_WAITING_RECORD to "سجّل {0}",
    TextKey.SMS_WAITING_SHEET_TITLE to "رسائل «{0}» أين تُسجَّل؟",
    TextKey.SMS_WAITING_SHEET_BODY to "مرة واحدة فقط. يُسجَّل المنتظر من رسائله فور اختيارك.",
    TextKey.SMS_WAITING_SHEET_BANK to "حساب بنكي",
    TextKey.SMS_WAITING_SHEET_SAVE to "سجّلها هنا",
    TextKey.SMS_CATPICK_TITLE to "تصنيف «{0}»",
    TextKey.SMS_CATPICK_SEARCH to "ابحث عن تصنيف",
    TextKey.SMS_CATPICK_EMPTY to "لا نتائج",
)

internal val EGYPTIAN_IMPORTS_SMS_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.IMPORTS_DRAFT_GONE to "الملف ده مش موجود تاني",
    TextKey.IMPORTS_DRAFT_GONE_BODY to "البرنامج اتقفل قبل ما تأكد، ومفيش حاجة اتسجلت. اختار الملف تاني.",
    TextKey.IMPORTS_LOAD_FAILED to "ما قدرناش نحمّل",
    TextKey.IMPORTS_RETRY to "جرّب تاني",
    TextKey.IMPORTS_SEP to "، ",
    TextKey.IMPORTS_QUOTED to "«{0}»",
    TextKey.IMPORTS_UNCATEGORIZED to "غير مصنف",
    TextKey.IMPORTS_OPS_ONE to "عملية واحدة",
    TextKey.IMPORTS_OPS_TWO to "عمليتين",
    TextKey.IMPORTS_OPS_FEW to "{0} عمليات",
    TextKey.IMPORTS_OPS_MANY to "{0} عملية",
    TextKey.IMPORTS_MSGS_ONE to "رسالة واحدة",
    TextKey.IMPORTS_MSGS_TWO to "رسالتين",
    TextKey.IMPORTS_MSGS_FEW to "{0} رسايل",
    TextKey.IMPORTS_MSGS_MANY to "{0} رسالة",
    TextKey.IMPORTS_LINES_ONE to "سطر واحد",
    TextKey.IMPORTS_LINES_TWO to "سطرين",
    TextKey.IMPORTS_LINES_FEW to "{0} سطور",
    TextKey.IMPORTS_LINES_MANY to "{0} سطر",
    TextKey.IMPORTS_PAGES_ONE to "صفحة واحدة",
    TextKey.IMPORTS_PAGES_TWO to "صفحتين",
    TextKey.IMPORTS_PAGES_FEW to "{0} صفحات",
    TextKey.IMPORTS_PAGES_MANY to "{0} صفحة",
    TextKey.BANK_SMS_TITLE to "رسايل البنك",
    TextKey.BANK_SMS_GEAR to "إعداد القراية",
    TextKey.BANK_SMS_STATUS_OK to "القراية شغالة",
    TextKey.BANK_SMS_STATUS_OK_BODY to "الرسالة المفهومة بتتسجل وتتصنف لوحدها.",
    TextKey.BANK_SMS_STATUS_STOPPED to "القراية واقفة",
    TextKey.BANK_SMS_STATUS_PERM_BODY to "إذن الرسايل اتسحب من إعدادات الجوال.",
    TextKey.BANK_SMS_STATUS_OFF_BODY to "إنت وقّفت القراية التلقائية. شغّلها من إعداد القراية.",
    TextKey.BANK_SMS_STATUS_IOS to "الآيفون ما بيسمحش",
    TextKey.BANK_SMS_STATUS_IOS_BODY to "أبل ما بتسمحش للبرامج تقرا الرسايل. تقدر تلصق الرسالة بإيدك.",
    TextKey.BANK_SMS_REGRANT to "رجّع الإذن",
    TextKey.BANK_SMS_OPEN_SETTINGS to "الإعداد",
    TextKey.BANK_SMS_PASTE to "الصق رسالة",
    TextKey.BANK_SMS_EMPTY_TITLE to "مفيش رسايل النهارده",
    TextKey.BANK_SMS_EMPTY_BODY to "أول ما رسالة من البنك توصل، هتتسجل هنا لوحدها.",
    TextKey.BANK_SMS_AUTO_TITLE to "اتسجلت لوحدها النهارده",
    TextKey.BANK_SMS_SUGGESTED to "مقترح",
    TextKey.BANK_SMS_NEW_SHOP to "محل جديد",
    TextKey.BANK_SMS_CONFIRM to "تمام كده",
    TextKey.BANK_SMS_CATEGORIZE to "صنّفها",
    TextKey.BANK_SMS_FOOTER to "إشعار الجوال بيوصلك بس للرسايل المستنية تأكيدك، من مجموعة",
    TextKey.BANK_SMS_FOOTER_LINK to "«رسايل البنك»",
    TextKey.BANK_SMS_REMEMBERED to "تمام — «{0}» هيتصنّف «{1}» على طول",
    TextKey.BANK_SMS_RECORDED to "اتسجلت {0}",
    TextKey.BANK_SMS_DROPPED to "الرسالة اتشالت",
    TextKey.BANK_SMS_HAND_SAVED to "اتسجّلت — فاضل تصنّفها",
    TextKey.BANK_SMS_WALLET_SAVED to "اتسجلت {0} في «{1}»",
    TextKey.SMS_WAITING_TITLE to "مستنية تأكيدك",
    TextKey.SMS_WAITING_ALL_DONE to "مفيش حاجة مستنية — كله اتسجّل.",
    TextKey.SMS_WAITING_BANK_TITLE to "رسايل من بنك جديد",
    TextKey.SMS_WAITING_BANK_BODY to "«{1}» بعتلك {0}. تتسجل في أنهي محفظة؟",
    TextKey.SMS_WAITING_BANK_ONCE to "هتختار مرة واحدة بس. بعد كده رسايل البنك ده بتتسجل لوحدها.",
    TextKey.SMS_WAITING_PICK_WALLET to "اختار المحفظة",
    TextKey.SMS_WAITING_CONFIRM_TITLE to "رسايل محتاجة تأكيدك",
    TextKey.SMS_WAITING_SIMILAR_TITLE to "شبه عملية موجودة",
    TextKey.SMS_WAITING_CONFLICT_TITLE to "نفس المرجع بتفاصيل مختلفة",
    TextKey.SMS_WAITING_FROM_MESSAGE to "من الرسالة",
    TextKey.SMS_WAITING_SAME_DROP to "هي نفسها — شيلها",
    TextKey.SMS_WAITING_RECORD_IT to "لأ، سجّلها",
    TextKey.SMS_WAITING_WILL_RECORD to "هتتسجل مع الكل",
    TextKey.SMS_WAITING_UNCLEAR_TITLE to "رسالة ما اتفهمتش",
    TextKey.SMS_WAITING_REASON to "السبب: {0}",
    TextKey.SMS_WAITING_FOREIGN_NOTE to "بعملة تانية: سؤال المبلغ بعملتك لسه ما اتعملش — سجّلها بإيدك.",
    TextKey.SMS_WAITING_DROP to "شيلها",
    TextKey.SMS_WAITING_BY_HAND to "سجّلها بإيدك",
    TextKey.SMS_WAITING_SAVE to "سجّل",
    TextKey.SMS_WAITING_RECORD to "سجّل {0}",
    TextKey.SMS_WAITING_SHEET_TITLE to "رسايل «{0}» تتسجل فين؟",
    TextKey.SMS_WAITING_SHEET_BODY to "مرة واحدة بس. المستني من رسايله بيتسجل أول ما تختار.",
    TextKey.SMS_WAITING_SHEET_BANK to "حساب بنك",
    TextKey.SMS_WAITING_SHEET_SAVE to "سجّلها هنا",
    TextKey.SMS_CATPICK_TITLE to "تصنيف «{0}»",
    TextKey.SMS_CATPICK_SEARCH to "دوّر على تصنيف",
    TextKey.SMS_CATPICK_EMPTY to "مفيش نتايج",
)

internal val ENGLISH_IMPORTS_SMS_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.IMPORTS_DRAFT_GONE to "This file is no longer open",
    TextKey.IMPORTS_DRAFT_GONE_BODY to "The app closed before you confirmed, so nothing was saved. Choose the file again.",
    TextKey.IMPORTS_LOAD_FAILED to "Couldn't load",
    TextKey.IMPORTS_RETRY to "Try again",
    TextKey.IMPORTS_SEP to ", ",
    TextKey.IMPORTS_QUOTED to "“{0}”",
    TextKey.IMPORTS_UNCATEGORIZED to "Uncategorised",
    TextKey.IMPORTS_OPS_ONE to "1 transaction",
    TextKey.IMPORTS_OPS_TWO to "2 transactions",
    TextKey.IMPORTS_OPS_FEW to "{0} transactions",
    TextKey.IMPORTS_OPS_MANY to "{0} transactions",
    TextKey.IMPORTS_MSGS_ONE to "1 message",
    TextKey.IMPORTS_MSGS_TWO to "2 messages",
    TextKey.IMPORTS_MSGS_FEW to "{0} messages",
    TextKey.IMPORTS_MSGS_MANY to "{0} messages",
    TextKey.IMPORTS_LINES_ONE to "1 line",
    TextKey.IMPORTS_LINES_TWO to "2 lines",
    TextKey.IMPORTS_LINES_FEW to "{0} lines",
    TextKey.IMPORTS_LINES_MANY to "{0} lines",
    TextKey.IMPORTS_PAGES_ONE to "1 page",
    TextKey.IMPORTS_PAGES_TWO to "2 pages",
    TextKey.IMPORTS_PAGES_FEW to "{0} pages",
    TextKey.IMPORTS_PAGES_MANY to "{0} pages",
    TextKey.BANK_SMS_TITLE to "Bank messages",
    TextKey.BANK_SMS_GEAR to "Reading settings",
    TextKey.BANK_SMS_STATUS_OK to "Reading is on",
    TextKey.BANK_SMS_STATUS_OK_BODY to "Understood messages are recorded and categorised automatically.",
    TextKey.BANK_SMS_STATUS_STOPPED to "Reading is stopped",
    TextKey.BANK_SMS_STATUS_PERM_BODY to "The messages permission was removed in the phone settings.",
    TextKey.BANK_SMS_STATUS_OFF_BODY to "You turned automatic reading off. Turn it on in reading settings.",
    TextKey.BANK_SMS_STATUS_IOS to "iPhone doesn't allow it",
    TextKey.BANK_SMS_STATUS_IOS_BODY to "Apple doesn't let apps read messages. You can paste a message yourself.",
    TextKey.BANK_SMS_REGRANT to "Allow again",
    TextKey.BANK_SMS_OPEN_SETTINGS to "Settings",
    TextKey.BANK_SMS_PASTE to "Paste a message",
    TextKey.BANK_SMS_EMPTY_TITLE to "No messages today",
    TextKey.BANK_SMS_EMPTY_BODY to "When a bank message arrives it will be recorded here automatically.",
    TextKey.BANK_SMS_AUTO_TITLE to "Recorded automatically today",
    TextKey.BANK_SMS_SUGGESTED to "Suggested",
    TextKey.BANK_SMS_NEW_SHOP to "New shop",
    TextKey.BANK_SMS_CONFIRM to "Confirm",
    TextKey.BANK_SMS_CATEGORIZE to "Categorise",
    TextKey.BANK_SMS_FOOTER to "You only get a phone notification for messages waiting for you, from the group",
    TextKey.BANK_SMS_FOOTER_LINK to "“Bank messages”",
    TextKey.BANK_SMS_REMEMBERED to "Done — “{0}” will always be “{1}”",
    TextKey.BANK_SMS_RECORDED to "Recorded {0}",
    TextKey.BANK_SMS_DROPPED to "Message removed",
    TextKey.BANK_SMS_HAND_SAVED to "Recorded — just categorise it",
    TextKey.BANK_SMS_WALLET_SAVED to "Recorded {0} in “{1}”",
    TextKey.SMS_WAITING_TITLE to "Waiting for you",
    TextKey.SMS_WAITING_ALL_DONE to "Nothing waiting — everything is recorded.",
    TextKey.SMS_WAITING_BANK_TITLE to "Messages from a new bank",
    TextKey.SMS_WAITING_BANK_BODY to "“{1}” sent you {0}. Which wallet should they go to?",
    TextKey.SMS_WAITING_BANK_ONCE to "You choose once; after that this bank's messages are recorded automatically.",
    TextKey.SMS_WAITING_PICK_WALLET to "Choose the wallet",
    TextKey.SMS_WAITING_CONFIRM_TITLE to "Messages to confirm",
    TextKey.SMS_WAITING_SIMILAR_TITLE to "Looks like an existing transaction",
    TextKey.SMS_WAITING_CONFLICT_TITLE to "Same reference, different details",
    TextKey.SMS_WAITING_FROM_MESSAGE to "From the message",
    TextKey.SMS_WAITING_SAME_DROP to "Same one — remove it",
    TextKey.SMS_WAITING_RECORD_IT to "No, record it",
    TextKey.SMS_WAITING_WILL_RECORD to "Will be recorded",
    TextKey.SMS_WAITING_UNCLEAR_TITLE to "A message we couldn't read",
    TextKey.SMS_WAITING_REASON to "Reason: {0}",
    TextKey.SMS_WAITING_FOREIGN_NOTE to "In a foreign currency: asking for the local amount isn't built yet — record it yourself.",
    TextKey.SMS_WAITING_DROP to "Remove",
    TextKey.SMS_WAITING_BY_HAND to "Record it yourself",
    TextKey.SMS_WAITING_SAVE to "Save",
    TextKey.SMS_WAITING_RECORD to "Record {0}",
    TextKey.SMS_WAITING_SHEET_TITLE to "Where should “{0}” messages go?",
    TextKey.SMS_WAITING_SHEET_BODY to "Only once. Its waiting messages are recorded as soon as you choose.",
    TextKey.SMS_WAITING_SHEET_BANK to "Bank account",
    TextKey.SMS_WAITING_SHEET_SAVE to "Record them here",
    TextKey.SMS_CATPICK_TITLE to "Category for “{0}”",
    TextKey.SMS_CATPICK_SEARCH to "Search categories",
    TextKey.SMS_CATPICK_EMPTY to "No results",
)
