package app.masroufy.core

/** منطقة «الأشخاص» بالإنجليزي (كتابة Claude — مستنية مراجعة المالك §40) — العام · الأشخاص · «لك/عليك» · ملف الشخص · الإضافة · الديون القديمة. */
internal val ENGLISH_PEOPLE_AREA_1: Map<UiKey, String> = mapOf(
    // ── General
    UiKey.PPL_AGO_DAYS to "{0} ago",
    UiKey.PPL_IN_DAYS to "in {0}",
    UiKey.PPL_ARCHIVED to "Archived",
    UiKey.PPL_CANCEL to "Cancel",
    UiKey.PPL_DASH to "—",
    UiKey.PPL_DATE_INVALID to "The occasion date isn't valid.",
    UiKey.PPL_DATE_WITH_YEAR to "{0} {1}",
    UiKey.PPL_DAYS_ONE to "1 day",
    UiKey.PPL_DAYS_TWO to "2 days",
    UiKey.PPL_DAYS_FEW to "{0} days",
    UiKey.PPL_DAYS_MANY to "{0} days",
    UiKey.PPL_DAY_LABEL to "Day",
    UiKey.PPL_GIFTS_ONE to "1 gift",
    UiKey.PPL_GIFTS_TWO to "2 gifts",
    UiKey.PPL_GIFTS_TWO_OBJ to "2 gifts",
    UiKey.PPL_GIFTS_FEW to "{0} gifts",
    UiKey.PPL_GIFTS_MANY to "{0} gifts",
    UiKey.PPL_HOST_OF to "{0}'s",
    UiKey.PPL_ITEMS_ONE to "1 item",
    UiKey.PPL_ITEMS_TWO to "2 items",
    UiKey.PPL_ITEMS_TWO_OBJ to "2 items",
    UiKey.PPL_ITEMS_FEW to "{0} items",
    UiKey.PPL_ITEMS_MANY to "{0} items",
    UiKey.PPL_LOAD_FAILED to "Couldn't load.",
    UiKey.PPL_MINE to "Your event",
    UiKey.PPL_MONTH_LABEL to "Month (Gregorian)",
    UiKey.PPL_NOT_BUILT to "Not available yet — coming in a later step.",
    UiKey.PPL_ONCE_NEEDS_YEAR to "A one-time occasion needs the year.",
    UiKey.PPL_OPS_ONE to "1 transaction",
    UiKey.PPL_OPS_TWO to "2 transactions",
    UiKey.PPL_OPS_TWO_OBJ to "2 transactions",
    UiKey.PPL_OPS_FEW to "{0} transactions",
    UiKey.PPL_OPS_MANY to "{0} transactions",
    UiKey.PPL_OPTIONAL to "optional",
    UiKey.PPL_PEOPLE_ONE to "1 person",
    UiKey.PPL_PEOPLE_TWO to "2 people",
    UiKey.PPL_PEOPLE_FEW to "{0} people",
    UiKey.PPL_PEOPLE_MANY to "{0} people",
    UiKey.PPL_PERCENT to "{0}%",
    UiKey.PPL_PERCENT_SIGN to "%",
    UiKey.PPL_PICK_DATE to "Pick a date",
    UiKey.PPL_REMOVE_NAMED to "Remove {0}",
    UiKey.PPL_REMOVE_ROW to "Remove row",
    UiKey.PPL_RETRY to "Try again",
    UiKey.PPL_SAR_ONLY to "Old debts are in riyals only for now — not available in this country's currency yet.",
    UiKey.PPL_SAVE to "Save",
    UiKey.PPL_SAVED to "Saved",
    UiKey.PPL_SAVE_EDIT to "Save changes",
    UiKey.PPL_SEP to ", ",
    UiKey.PPL_SWITCH_OFF to "Off",
    UiKey.PPL_SWITCH_ON to "On",
    UiKey.PPL_TXN_NO_NAME to "Unnamed transaction",
    UiKey.PPL_YEAR to "Year",
    UiKey.PPL_YEAR_OPTIONAL to "Year (optional)",
    UiKey.PPL_YEAR_UNKNOWN to "Unknown",
    // ── People
    UiKey.PEOPLE_ADD to "Add",
    UiKey.PEOPLE_ADD_PERSON to "Add person",
    UiKey.PEOPLE_ALL to "All ({0})",
    UiKey.PEOPLE_BACK to "Back",
    UiKey.PEOPLE_CHARACTER_SLOT to "Your character goes here",
    UiKey.PEOPLE_CHIP_OWE to "You owe {0}",
    UiKey.PEOPLE_CHIP_OWED to "Owes you {0}",
    UiKey.PEOPLE_EMPTY_TITLE to "No one added yet",
    UiKey.PEOPLE_EMPTY_BODY to "Add the people you deal with to track what they owe you and what you owe them.",
    UiKey.PEOPLE_ERROR_TITLE to "Couldn't load balances",
    UiKey.PEOPLE_ERROR_BODY to "People are shown; amounts appear after a refresh.",
    UiKey.PEOPLE_EVENTS to "Events",
    UiKey.PEOPLE_ORBIT_NOTE to "People with balances first",
    UiKey.PEOPLE_OWED_BOX to "Owed to you",
    UiKey.PEOPLE_OWE_BOX to "You owe",
    UiKey.PEOPLE_OWED_COUNT to "with {0}",
    UiKey.PEOPLE_OWE_COUNT to "to {0}",
    UiKey.PEOPLE_OWE_TWO to "to 2 people",
    UiKey.PEOPLE_YOU to "You",
    // ── Owed to you · You owe
    UiKey.OWED_TITLE_OWED to "Owed to you",
    UiKey.OWED_TITLE_OWE to "You owe",
    UiKey.OWED_TOTAL_OWED to "Total owed to you",
    UiKey.OWED_TOTAL_OWE to "Total you owe",
    UiKey.OWED_SUB_OWED to "With {0}, not netted against “You owe”",
    UiKey.OWED_SUB_OWE to "To {0}, not netted against “Owed to you”",
    UiKey.OWED_ORDER_NOTE to "Most urgent first: overdue, then due soon",
    UiKey.OWED_FOOT to "Tap anyone to see your history and record a payment.",
    UiKey.OWED_EMPTY_OWED to "Nobody owes you anything.",
    UiKey.OWED_EMPTY_OWE to "You don't owe anyone.",
    UiKey.OWED_DUE_ON to "Due {0}",
    UiKey.OWED_NO_DUE to "No due date",
    UiKey.OWED_REASON_OPENING to "Old debt",
    UiKey.OWED_REASON_RECEIVABLE to "A loan or a share you paid for them",
    UiKey.OWED_REASON_LOAN to "Borrowed from them",
    UiKey.OWED_REASON_CUSTODY to "Held in trust for them",
    UiKey.OWED_SIGNAL_OVERDUE to "Overdue by {0}",
    UiKey.OWED_SIGNAL_SOON to "Due soon, {0}",
    // ── Person profile
    UiKey.PERSON_PAGE_LAK to "They owe you",
    UiKey.PERSON_PAGE_ALEK to "You owe them",
    UiKey.PERSON_PAGE_NOTHING to "Nothing",
    UiKey.PERSON_PAGE_NO_NETTING to "The two amounts aren't netted",
    UiKey.PERSON_PAGE_NOT_FOUND to "Person not found.",
    UiKey.PERSON_PAGE_TOGETHER to "Together",
    UiKey.PERSON_PAGE_ACT_ROSCA to "Savings circle",
    UiKey.PERSON_PAGE_ACT_PROJECT to "Shared project",
    UiKey.PERSON_PAGE_ACT_LINK to "Connect",
    UiKey.PERSON_PAGE_ACT_SPLIT to "Split a bill",
    UiKey.PERSON_PAGE_FUTURE to "Soon: when {0} uses Masroufy, you can build things together from both accounts.",
    UiKey.PERSON_PAGE_ROSCA_TITLE to "Savings circle with {0}",
    UiKey.PERSON_PAGE_ROSCA_BODY to "Set the monthly payment to record the circle. {0} gets the invite once account linking is on.",
    UiKey.PERSON_PAGE_ROSCA_AMOUNT to "Monthly payment",
    UiKey.PERSON_PAGE_ROSCA_GO to "Record circle",
    UiKey.PERSON_PAGE_PROJECT_TITLE to "Project with {0}",
    UiKey.PERSON_PAGE_PROJECT_BODY to "Create a project for your shared spending, with each person's share.",
    UiKey.PERSON_PAGE_PROJECT_GO to "Create project",
    UiKey.PERSON_PAGE_LINK_TITLE to "Link your account with {0}'s",
    UiKey.PERSON_PAGE_LINK_BODY to "Once linked, loans and bills are recorded for both of you at once.",
    UiKey.PERSON_PAGE_LINK_GO to "Send request",
    UiKey.PERSON_PAGE_LINK_NOTE to "Needs account linking, which comes in a later phase.",
    UiKey.PERSON_PAGE_SPLIT_TITLE to "Split a bill with {0}",
    UiKey.PERSON_PAGE_SPLIT_BODY to "Enter the bill amount to split it equally; their share goes under “Owed to you”.",
    UiKey.PERSON_PAGE_SPLIT_AMOUNT to "Bill amount",
    UiKey.PERSON_PAGE_SPLIT_GO to "Record split",
    UiKey.PERSON_PAGE_HISTORY to "History between you",
    UiKey.PERSON_PAGE_HISTORY_EMPTY to "No open debts between you.",
    UiKey.PERSON_PAGE_DEBT_RECEIVABLE to "You lent",
    UiKey.PERSON_PAGE_DEBT_LOAN to "They lent you",
    UiKey.PERSON_PAGE_DEBT_CUSTODY to "Held for them",
    UiKey.PERSON_PAGE_REMAINING to "{0} left of {1}",
    UiKey.PERSON_PAGE_BADGES to "Gifts between you",
    // ── Add person
    UiKey.ADD_PERSON_TITLE to "New person",
    UiKey.ADD_PERSON_NAME to "Name",
    UiKey.ADD_PERSON_NAME_PH to "What you call them",
    UiKey.ADD_PERSON_CIRCLE to "Circle (optional)",
    UiKey.ADD_PERSON_REL to "How you know them (optional)",
    UiKey.ADD_PERSON_REL_PH to "e.g. my brother, a colleague",
    UiKey.ADD_PERSON_OCC to "An occasion for them",
    UiKey.ADD_PERSON_OCC_NOTE_ONCE to "Once; we'll remind you a week before.",
    UiKey.ADD_PERSON_OCC_NOTE_YEARLY to "Every year; we'll remind you a week before — change it from their profile.",
    UiKey.ADD_PERSON_DEBT to "An old debt between you",
    UiKey.ADD_PERSON_SIDE_LAK to "They owe me",
    UiKey.ADD_PERSON_SIDE_ALEK to "I owe them",
    UiKey.ADD_PERSON_AMOUNT to "Amount",
    UiKey.ADD_PERSON_DEBT_NOTE to "No transaction; it doesn't touch any wallet, spending or income.",
    UiKey.ADD_PERSON_SAVE to "Add",
    UiKey.ADD_PERSON_ADDED to "{0} added",
    UiKey.ADD_PERSON_NEED_NAME to "Enter the person's name.",
    UiKey.ADD_PERSON_NEED_MONTH to "Pick the occasion's month, or close that section.",
    UiKey.ADD_PERSON_NEED_SIDE to "Choose: they owe you, or you owe them.",
    UiKey.ADD_PERSON_NEED_AMOUNT to "Enter a debt amount above zero, or close that section.",
    // ── Old debts
    UiKey.PROFILE_DEBT_TITLE to "Add old debts",
    UiKey.PROFILE_DEBT_NOTE to "They show under People and get repaid as usual; they don't count in spending, income or cash balance.",
    UiKey.PROFILE_DEBT_WHO to "Who?",
    UiKey.PROFILE_DEBT_NEW to "Or type a new person's name",
    UiKey.PROFILE_DEBT_DIR_LAK to "They owe you",
    UiKey.PROFILE_DEBT_DIR_ALEK to "You owe them",
    UiKey.PROFILE_DEBT_HOW_MUCH_LAK to "How much do they owe you?",
    UiKey.PROFILE_DEBT_HOW_MUCH_ALEK to "How much do you owe them?",
    UiKey.PROFILE_DEBT_NEED_NAME to "Enter each person's name",
    UiKey.PROFILE_DEBT_NEED_AMOUNT_OF to "The debt amount for “{0}” must be above zero",
    UiKey.PROFILE_DEBT_NEED_AMOUNT to "The amount must be above zero",
    UiKey.PROFILE_DEBT_ADD_ANOTHER to "Add another person",
    UiKey.PROFILE_DEBT_DONE to "Done",
)
