package app.masroufy.core

/**
 * منطقة «المستحقات» — الجزء الأول: خانة «المستحقات» · «الديون» · «تفاصيل الدين» · لوحة السداد/التحصيل · «دين قديم». **الفصحى** (السعودية والافتراضي)
 * من لوحات النموذج بنسخة `space = السعودية` بالحرف (OVERRIDES §66). **ممنوع «·» جنب رقم عربي** ⇒ «،».
 * المصري في `TextsAreaDuesDebtsEgyptian.kt` والإنجليزي في `TextsAreaDuesDebtsEnglish.kt` — بنفس المتغيرات.
 */
internal val MSA_DUES_DEBTS_TEXTS: Map<TextKey, String> = mapOf(
    // ── خانة «المستحقات» (لوحة Dues) والكلام المشترك
    TextKey.DUES_FOR_YOU to "لك",
    TextKey.DUES_ON_YOU to "عليك",
    TextKey.DUES_LINE_RECEIVABLE to "ديون لك",
    TextKey.DUES_LINE_ROSCA_SAVED to "مدّخر في الجمعيات",
    TextKey.DUES_LINE_LOANS to "ديون عليك",
    TextKey.DUES_LINE_CUSTODY to "أمانات عندك",
    TextKey.DUES_LINE_INSTALLMENTS to "أقساط متبقية",
    TextKey.DUES_LINE_ROSCA_OWED to "عليك للجمعيات",
    TextKey.DUES_NO_NETTING to "كل رقم مستقل — بلا مقاصة بين «لك» و«عليك»",
    TextKey.DUES_MONTH_LINE to "ستدفع {0} · ستستلم {1}",
    TextKey.DUES_LIST_TITLE to "حسب الموعد",
    TextKey.DUES_CHIP_LATE to "متأخر",
    TextKey.DUES_CHIP_SOON to "قريب",
    TextKey.DUES_CHIP_NEXT to "قادم",
    TextKey.DUES_DIR_IN to "ستستلم",
    TextKey.DUES_DIR_OUT to "ستدفع",
    TextKey.DUES_ROW_YOUR_TURN to "وفيه دورك",
    TextKey.DUES_TILE_DEBTS to "الديون",
    TextKey.DUES_TILE_ROSCAS to "الجمعيات",
    TextKey.DUES_TILE_INSTALLMENTS to "الأقساط",
    TextKey.DUES_TILE_SUBSCRIPTIONS to "الاشتراكات",
    TextKey.DUES_FINANCING to "أرباح التمويل في هذه الفترة {0} — للعلم فقط، والقسط كله محسوب مصروفًا.",
    TextKey.DUES_EMPTY_TITLE to "لا توجد مستحقات",
    TextKey.DUES_EMPTY_BODY to "تظهر هنا الديون والجمعيات والأقساط والاشتراكات.",
    TextKey.DUES_SHOW_ALL to "اعرض الكل",
    TextKey.DUES_SHOW_LESS to "اعرض أقل",
    TextKey.DUES_AGO_ONE to "منذ يوم واحد",
    TextKey.DUES_AGO_TWO to "منذ يومين",
    TextKey.DUES_AGO_FEW to "منذ {0} أيام",
    TextKey.DUES_AGO_MANY to "منذ {0} يومًا",
    TextKey.DUES_DATE_WITH_YEAR to "{0} {1}",
    TextKey.DUES_COMMA to "، ",
    TextKey.DUES_COMMA_JOIN to "{0}، {1}",
    TextKey.DUES_DASH to "—",
    TextKey.DUES_CYCLE_WEEKS to "كل {0} أسابيع",
    TextKey.DUES_CYCLE_MONTHS to "كل {0} أشهر",
    TextKey.DUES_CYCLE_YEAR to "كل سنة",
    TextKey.DUES_INST_NONE to "لا أقساط",
    TextKey.DUES_INST_ONE to "قسط واحد",
    TextKey.DUES_INST_TWO to "قسطان",
    TextKey.DUES_INST_FEW to "{0} أقساط",
    TextKey.DUES_INST_MANY to "{0} قسطًا",
    TextKey.DUES_INTEREST_Q to "هل فيها فوائد؟",
    TextKey.DUES_INTEREST_SAVED to "حُفظت إجابتك",
    TextKey.DUES_INTEREST_UNSET to "لم تحدّد بعد",
    TextKey.DUES_YES to "نعم",
    TextKey.DUES_NO to "لا",
    TextKey.DUES_CANCEL to "إلغاء",
    TextKey.DUES_ERR_FORMAT to "اكتب المبلغ بالأرقام، مثل 1200.50",
    TextKey.DUES_ERR_POSITIVE to "اكتب مبلغًا أكبر من صفر.",
    TextKey.DUES_SAVE_FAILED to "تعذّر الحفظ — أعد المحاولة.",
    TextKey.DUES_UNLINK_BODY to "تعود العملية «غير محددة» وتظهر في المراجعات.",
    TextKey.DUES_UNLINK_YES to "فُكّ الربط",
    TextKey.DUES_UNLINKED to "فُكّ الربط — العملية في المراجعات",

    // ── «الديون» (لوحة DuesDebts)
    TextKey.DEBTS_TITLE to "الديون",
    TextKey.DEBTS_SUB to "مع الأشخاص، لك وعليك كلٌّ على حدة",
    TextKey.DEBTS_FOR_YOU_HINT to "ديون لك عند الناس",
    TextKey.DEBTS_ON_YOU_HINT to "ديون عليك للناس",
    TextKey.DEBTS_NOBODY to "لا أحد",
    TextKey.DEBTS_AT_ONE to "عند شخص واحد",
    TextKey.DEBTS_AT_TWO to "عند شخصين",
    TextKey.DEBTS_AT_FEW to "عند {0} أشخاص",
    TextKey.DEBTS_AT_MANY to "عند {0} شخصًا",
    TextKey.DEBTS_TO_ONE to "لشخص واحد",
    TextKey.DEBTS_TO_TWO to "لشخصين",
    TextKey.DEBTS_TO_FEW to "{0} أشخاص",
    TextKey.DEBTS_TO_MANY to "{0} شخصًا",
    TextKey.DEBTS_SEARCH_HINT to "ابحث باسم الشخص",
    TextKey.DEBTS_SEARCH_CLEAR to "امسح البحث",
    TextKey.DEBTS_ORDER_FOR_YOU to "الأهم أولًا: ما فات موعده، ثم الأقرب موعدًا",
    TextKey.DEBTS_ORDER_ON_YOU to "حسب الموعد",
    TextKey.DEBTS_CUSTODY_TITLE to "أمانات عندك",
    TextKey.DEBTS_ORDER_CUSTODY to "منفصلة عن الديون، حسب الموعد",
    TextKey.DEBTS_REASON_RECEIVABLE to "دين لك من عملية",
    TextKey.DEBTS_REASON_LOAN to "دين عليك من عملية",
    TextKey.DEBTS_REASON_OPENING to "دين قديم من قبل التطبيق",
    TextKey.DEBTS_REASON_CUSTODY to "أمانة عندك",
    TextKey.DEBTS_DUE_ON to "موعدها {0}",
    TextKey.DEBTS_NO_DUE to "بلا موعد",
    TextKey.DEBTS_SIG_OVERDUE to "فات موعدها {0}",
    TextKey.DEBTS_SIG_SOON to "اقترب موعدها، {0}",
    TextKey.DEBTS_ARIA_FOR to "{0}، لك {1}",
    TextKey.DEBTS_ARIA_ON to "{0}، عليك {1}",
    TextKey.DEBTS_EMPTY_TITLE to "لا ديون مع أحد",
    TextKey.DEBTS_EMPTY_BODY to "حين تقسّم فاتورة أو تسجّل سلفة على شخص تظهر هنا.",
    TextKey.DEBTS_EMPTY_GO to "افتح الأشخاص",
    TextKey.DEBTS_NO_HITS_NAME to "لا أحد باسم «{0}»",
    TextKey.DEBTS_NO_HITS to "لا شيء هنا",
    TextKey.DEBTS_NO_HITS_IN_SIDE to "البحث داخل «{0}» فقط.",
    TextKey.DEBTS_NO_HITS_TRY to "جرّب جزءًا من الاسم.",
    TextKey.DEBTS_FOOT to "اضغط على الدين لترى أصله وتسجّل تحصيلًا أو سدادًا.",

    // ── «تفاصيل الدين» (لوحة DebtDetail)
    TextKey.DEBT_TITLE to "تفاصيل الدين",
    TextKey.DEBT_REMAIN_FOR to "المتبقي لك عنده",
    TextKey.DEBT_REMAIN_ON to "المتبقي عليك له",
    TextKey.DEBT_OF_ORIGINAL to "من أصل {0}",
    TextKey.DEBT_OF_ORIGINAL_NONE to "من أصل {0}، لم يُسدَّد شيء بعد",
    TextKey.DEBT_DONE to "سُدّد بالكامل ✓",
    TextKey.DEBT_NOT_OPEN to "هذا الدين غير موجود أو سُدّد بالكامل.",
    TextKey.DEBT_ORIGIN_TITLE to "أصل الدين",
    TextKey.DEBT_ORIGIN_LABEL to "المصدر",
    TextKey.DEBT_ORIGIN_TXN to "عملية مسجّلة",
    TextKey.DEBT_ORIGIN_BEFORE_APP to "من قبل التطبيق",
    TextKey.DEBT_ORIGIN_OLD_CHIP to "دين قديم",
    TextKey.DEBT_ORIGIN_OLD_HINT to "بلا عملية — لا يدخل المصروف ولا الدخل ولا الكاش",
    TextKey.DEBT_ORIGINAL to "المبلغ الأصلي",
    TextKey.DEBT_TYPE to "النوع",
    TextKey.DEBT_TYPE_RECEIVABLE to "دين لك",
    TextKey.DEBT_TYPE_LOAN to "دين عليك",
    TextKey.DEBT_TYPE_OLD_ON_YOU to "دين قديم عليك",
    TextKey.DEBT_TYPE_CUSTODY to "أمانة عندك",
    TextKey.DEBT_TYPE_HINT to "منفصل عن الأمانات — وبلا مقاصة مع «{0}»",
    TextKey.DEBT_TERMS_TITLE to "الموعد",
    TextKey.DEBT_TERMS_ONE_PAYMENT to "{0}، دفعة واحدة",
    TextKey.DEBT_TERMS_SET to "حدّد موعدًا",
    TextKey.DEBT_TERMS_CHANGE to "غيّر",
    TextKey.DEBT_TERMS_REMOVE to "إزالة",
    TextKey.DEBT_TERMS_PICK to "دفعة واحدة بكامل المتبقي في:",
    TextKey.DEBT_TERMS_SAVED to "الموعد: {0} — يظهر في المستحقات",
    TextKey.DEBT_TERMS_REMOVED to "أُزيل الموعد — والدين باقٍ كما هو",
    TextKey.DEBT_INTEREST_SAVED to "حُفظت إجابتك",

    // ── لوحة «سجّل تحصيلًا/سدادًا» (SettleSheet)
    TextKey.SETTLE_SHEET_TITLE_GENERIC to "تسوية الدين",
    TextKey.SETTLE_TRIGGER_FOR to "سجّل تحصيلًا",
    TextKey.SETTLE_TRIGGER_ON to "سجّل سدادًا",
    TextKey.SETTLE_DONE_WHY to "سُدّد هذا الدين بالكامل.",
    TextKey.SETTLE_TITLE_FOR to "تحصيل من {0}",
    TextKey.SETTLE_TITLE_ON to "سداد لـ{0}",
    TextKey.SETTLE_REMAINING to "المتبقي {0}",
    TextKey.SETTLE_HOW_FREE to "بلا عملية",
    TextKey.SETTLE_HOW_LINK to "عملية موجودة",
    TextKey.SETTLE_NO_CAND to "لا عملية بانتظار الربط",
    TextKey.SETTLE_NO_CAND_SUB to "حين تصل حوالة من {0} أو إليه نسألك عنها.",
    TextKey.SETTLE_AMOUNT to "المبلغ",
    TextKey.SETTLE_FILL to "المتبقي كاملًا {0}",
    TextKey.SETTLE_ERR_OVER to "يجب ألا يتجاوز المبلغ المتبقي ({0}).",
    TextKey.SETTLE_SAVE_FOR to "سجّل التحصيل",
    TextKey.SETTLE_SAVE_ON to "سجّل السداد",
    TextKey.SETTLE_SAVE_FOR_AMOUNT to "سجّل التحصيل · {0}",
    TextKey.SETTLE_SAVE_ON_AMOUNT to "سجّل السداد · {0}",
    TextKey.SETTLE_SAVED_FULL to "سُدّد الدين بالكامل",
    TextKey.SETTLE_SAVED_FOR to "سُجّل التحصيل من {0}",
    TextKey.SETTLE_SAVED_ON to "سُجّل السداد لـ{0}",

    // ── «دين قديم» (OpeningDebtSheet — §27)
    TextKey.OPENING_DEBT_CARD_TITLE to "دين قديم مع {0} قبل التطبيق؟",
    TextKey.OPENING_DEBT_CARD_BODY to "بلا عملية، ولا يمسّ أي محفظة.",
    TextKey.OPENING_DEBT_OPEN to "سجّله",
    TextKey.OPENING_DEBT_TITLE to "دين قديم مع {0}",
    TextKey.OPENING_DEBT_BODY to "لمبالغ كاش تبادلتماها قبل التطبيق بلا سجل. لا يدخل المصروف ولا الدخل ولا رصيد الكاش، ويُسدَّد كأي دين.",
    TextKey.OPENING_DEBT_FOR to "لي عنده",
    TextKey.OPENING_DEBT_ON to "عليّ له",
    TextKey.OPENING_DEBT_SAVE to "احفظ الدين",
    TextKey.OPENING_DEBT_SAVED to "سُجّل الدين القديم — هذه صفحته",
    TextKey.OPENING_ERR_SIDE to "اختر: لك عنده أم عليك له.",
    TextKey.OPENING_ERR_CURRENCY to "تسجيل الدين القديم بغير الريال غير متاح بعد.",
)
