package app.masroufy.core

/** رسايل حالات الاستخدام بالإنجليزي (OVERRIDES §66 — كتابة Claude ومستنية مراجعة المالك زي باقي الجدول §40). */
internal val ENGLISH_USECASE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.TXN_AMOUNT_POSITIVE to "The amount must be greater than zero. The direction comes from the transaction type.",
    TextKey.TXN_AMOUNT_LABEL to "Transaction amount",
    TextKey.TXN_DATE_INVALID to "The date isn't valid",
    TextKey.TXN_WALLET_REQUIRED to "Pick an existing wallet",
    TextKey.TXN_KIND_REQUIRED to "Set the transaction type — you know whether you bought or transferred",
    TextKey.TXN_KIND_DIRECTION to "This type doesn't match the direction",
    TextKey.TXN_TRANSFER_TARGET_REQUIRED to "An internal transfer needs the receiving wallet",
    TextKey.TXN_TRANSFER_SAME_WALLET to "You can't transfer from a wallet to itself",
    TextKey.TXN_TRANSFER_TARGET_MISSING to "The receiving wallet doesn't exist",
    TextKey.TXN_TRANSFER_CURRENCY to "A transfer between two currencies needs a documented exchange rate — not supported yet (spec/02)",
    TextKey.TXN_TRANSFER_TARGET_ONLY_INTERNAL to "A receiving wallet is only for internal transfers",
    TextKey.TXN_MERCHANT_TOO_LONG to "The store name is longer than 120 characters",
    TextKey.LOCK_CANCELLED to "Confirmation cancelled — nothing changed.",
    TextKey.LOCK_FAILED to "Couldn't confirm you own this phone — nothing changed.",
    TextKey.LOCK_UNAVAILABLE to "This phone has no screen lock or fingerprint. Set a screen lock in the phone settings first.",
    TextKey.LOCK_NOT_ANDROID to "Fingerprint lock is only available in the Android app.",
    TextKey.LOCK_NO_HARDWARE to "This phone has no fingerprint or supported lock.",
    TextKey.LOCK_HW_UNAVAILABLE to "The fingerprint sensor isn't available now. Try again shortly.",
    TextKey.LOCK_SECURITY_UPDATE to "The phone needs a security update before it allows fingerprint unlock.",
    TextKey.LOCK_CONFIRM_ENABLE to "Confirm to turn on the Masroufy lock",
    TextKey.LOCK_CONFIRM_DISABLE to "Confirm to turn off the Masroufy lock",
    TextKey.LOCK_UNLOCK_TITLE to "Open Masroufy",
    TextKey.LOCK_UNLOCK_SUBTITLE to "With your fingerprint or phone code",
    TextKey.TXN_NOT_FOUND to "This transaction doesn't exist",
    TextKey.CATEGORY_THIS_NOT_FOUND to "This category doesn't exist",
    TextKey.NOTE_TOO_LONG to "The note is longer than {0} characters",
    TextKey.TAG_NAME_REQUIRED to "Enter the tag name",
    TextKey.TAG_NAME_TOO_LONG to "The tag name is longer than {0} characters",
    TextKey.BACKUP_TOO_LARGE to "The backup is larger than the supported limit (40 MB)",
    TextKey.BACKUP_NOT_JSON to "The file isn't valid JSON",
    TextKey.BACKUP_NEEDS_V2 to "Pick a full backup of version 2; for older backups use the old-backup restore",
    TextKey.BACKUP_COUNT_MISMATCH to "Record count doesn't match: {0}",
    TextKey.BACKUP_CHECKSUM_MISMATCH to "The backup checksum doesn't match; the file was changed or damaged",
    TextKey.BACKUP_NOTE_KEEP_EXISTING to "Existing data stays as is. Links of repeated transactions move to the existing transactions' ids.",
    TextKey.BACKUP_NOTE_PROFILE to "The account profile (name, salary, payday) is only added if the account has none — it never overwrites.",
    TextKey.BACKUP_NOTE_BATCHES to "Restore runs in batches: if the connection drops, part may be saved; restore the same backup again to complete it without overwriting. Avoid editing from another device during backup and restore.",
    TextKey.BACKUP_NOTE_SCOPE to "The backup holds account data; phone permissions, local review messages and appearance settings aren't restored from it.",
    TextKey.BACKUP_NEEDS_SPACES to "This backup has other countries — restoring needs the countries' storage",
    TextKey.IMPORT_SAME_REFERENCE_IN_FILE to "The reference “{0}” repeats in this same file (row {1})",
    TextKey.IMPORT_ROW_CONFLICT to "Row {0} has a conflict to resolve first. {1}",
    TextKey.IMPORT_COMMIT_RUNNING to "An import is being saved; wait for it to finish",
    TextKey.IMPORT_DATA_CHANGED to "The import data changed; preview again",
    TextKey.IMPORT_CHANGED_AFTER_PREVIEW to "Data changed after the preview; preview again to avoid duplicates",
    TextKey.IMPORT_LINE_NOT_ADDABLE to "A duplicate or invalid transaction can't be added",
    TextKey.ASSET_FIELD_NOT_DATE to "{0} isn't a valid date",
    TextKey.ASSET_FIELD_NEGATIVE to "{0} can't be negative",
    TextKey.ASSET_FIELD_POSITIVE to "{0} must be greater than zero",
    TextKey.ASSET_QUANTITY_POSITIVE to "The quantity must be greater than zero",
    TextKey.ASSET_NOT_FOUND to "This asset doesn't exist",
    TextKey.ASSET_NAME_REQUIRED to "Enter the asset name",
    TextKey.ASSET_NAME_DUPLICATE to "An asset named “{0}” already exists",
    TextKey.ASSET_LABEL_PURCHASE_DATE to "Purchase date",
    TextKey.ASSET_LABEL_PURCHASE_VALUE to "Purchase value",
    TextKey.ASSET_LABEL_FEES to "Fees",
    TextKey.ASSET_LABEL_SALE_DATE to "Sale date",
    TextKey.ASSET_LABEL_PROCEEDS to "Sale proceeds",
    TextKey.ASSET_FEES_OVER_PROCEEDS to "Fees ({0}) are larger than the proceeds ({1})",
    TextKey.ASSET_LABEL_PRICE to "Price",
    TextKey.ASSET_LABEL_PRICE_DATE to "Price date",
    TextKey.PERSON_NAME_REQUIRED to "Enter the person's name",
    TextKey.PERSON_NAME_DUPLICATE to "A person named “{0}” already exists",
    TextKey.PERSON_NOT_FOUND to "This person doesn't exist",
    TextKey.AMOUNT_POSITIVE to "The amount must be greater than zero",
    TextKey.SETTLEMENT_REQUEST_ID_INVALID to "The settlement request id is malformed",
    TextKey.RECURRING_NOT_FOUND to "The commitment doesn't exist. Refresh the page.",
    TextKey.RECURRING_DUPLICATE to "This service is already recorded in the same currency. Edit it from your list.",
    TextKey.CATEGORY_DELETED to "Deleted category",
    TextKey.RULE_TEXT_REQUIRED to "Enter the text the rule looks for",
    TextKey.TEXT_TOO_LONG to "The text is longer than {0} characters",
    TextKey.RULE_DUPLICATE to "A rule with the text “{0}” and the same match mode already exists",
    TextKey.RULE_NOT_FOUND to "This rule doesn't exist",
    TextKey.RULE_TEXT_EMPTY to "The rule text can't be empty",
    TextKey.MERCHANT_NOT_FOUND to "This merchant doesn't exist",
    TextKey.MERCHANT_NAME_REQUIRED to "Enter the merchant name",
    TextKey.MERCHANT_ALIAS_LENGTH to "Enter a name of at most 120 characters.",
    TextKey.MERCHANT_PICK_EXISTING to "Pick an existing merchant.",
    TextKey.MERCHANT_ALIAS_TAKEN to "The name is already linked to another merchant; we won't silently change the old link.",
    TextKey.SMS_SENDER_REQUIRED_MANY to "Enter the bank sender name as it appears in messages (up to 10 names)",
    TextKey.ONBOARD_CASH_INVALID to "The cash amount must be a non-negative number",
    TextKey.ONBOARD_DEBT_NAME_REQUIRED to "Enter each person's name",
    TextKey.ONBOARD_DEBT_AMOUNT to "The debt amount for “{0}” must be greater than zero",
    TextKey.ONBOARD_NO_CASH_WALLET to "There is no cash wallet in the account",
    TextKey.SMS_PERIOD_INVALID to "Pick a valid period",
    TextKey.SMS_PERIOD_TOO_LONG to "Pick at most one year",
    TextKey.SMS_SENDER_REQUIRED to "Enter the bank sender name as it appears in messages",
    TextKey.PDF_NO_TRANSACTIONS to "We read {0} pages but found no transactions. The reader knows Al Rajhi and QNB Egypt statements only — another bank's statement won't work yet.",
    TextKey.WALLET_NOT_FOUND_ID to "Wallet not found: {0}",
    TextKey.RECONCILE_INCOMING_PREFIX to "Incoming transfer — ",
    TextKey.BATCH_NOT_FOUND to "Batch not found: {0}",
    TextKey.BATCH_NOT_STAGED to "This batch is “{0}”, not “staged”. Cleanup only works on pending batches.",
    TextKey.REVERT_BLOCKED to "We couldn't find this import's transactions; its ids were probably saved incomplete by an older version. In Settings tap “Check old data”, fix it, then try reverting again.",
    TextKey.BATCH_ALREADY_REVERTED to "This batch was already reverted",
    TextKey.REVERT_KEPT_SETTLEMENT to "A settlement was recorded on this transaction after the import, so it won't be deleted",
    TextKey.REVERT_KEPT_ALLOCATION to "This transaction is linked to a person (allocation or obligation), so it won't be deleted",
    TextKey.REVERT_KEPT_OTHER_SOURCE to "This transaction has another source besides this batch (a message, say), so it won't be deleted",
    TextKey.REVERT_DELETED to "This batch is its only source and it has no settlements",
    TextKey.REVIEW_RANGE to "Pick a valid range of at most five years.",
    TextKey.REVIEW_CHANGED to "Transactions or rules changed after the preview. Show the preview again.",
    TextKey.REVIEW_KIND_NOT_BULK to "Debts and transfers need the person or wallet linked per transaction.",
    TextKey.REVIEW_PICK_ROWS to "Pick transactions to review.",
    TextKey.REVIEW_SAME_GROUP to "The group must share the same name, currency and direction.",
    TextKey.REVIEW_KIND_DIRECTION to "The type doesn't match the direction.",
    TextKey.SEED_WALLETS_EXIST to "Wallets already exist. We won't overwrite your edits.",
    TextKey.SEED_WALLETS_DONE to "Two wallets were created with a zero balance — set the opening balance in Settings.",
    TextKey.SEED_REFS_EXIST to "References are already set up. We won't overwrite your edits.",
    TextKey.SEED_REFS_DONE to "Categories, rules and merchants are ready as an editable starting point.",
    TextKey.BUDGET_THRESHOLD_RANGE to "The alert threshold must be a whole number between 1 and 100",
    TextKey.BUDGET_NOTHING_TO_COPY to "There's no budget for period {0} to copy",
    TextKey.TXN_NOT_FOUND_ID to "Transaction not found: {0}",
    TextKey.DIRECTION_IN_WORD to "incoming",
    TextKey.DIRECTION_OUT_WORD to "outgoing",
    TextKey.KIND_DIRECTION_OBSERVED to "This type doesn't match the direction. The statement says this transaction is “{0}”.",
    TextKey.PRICE_SYMBOL_MISSING to "The symbol “{0}” isn't in today's price file",
    TextKey.BACKUP_SAVED_PARTIAL to "The backup was saved incomplete ({0} of {1} bytes) — no document was touched",
    TextKey.SETTLEMENT_CHANGED_DURING_SAVE to "Settlements changed while saving. Try again with the same request",
    TextKey.SETTLEMENT_STATE_INVALID to "The settlements state is invalid and needs review",
    TextKey.MONEY_OUT_OF_SAFE_RANGE to "The amount is outside the safe range",
    TextKey.FILE_EMPTY to "The file is empty.",
    TextKey.FILE_IS_PDF to "This is a PDF — it's read by a different reader than CSV.",
    TextKey.SMS_READ_ARGS to "Pick a period of at most a year and the bank sender name",
    TextKey.SMS_PERMISSION_MISSING to "Permission to read messages isn't available. You can paste a single message instead.",
    TextKey.SMS_PERMISSION_REVOKED to "The messages permission was revoked. Check the app permissions or use paste.",
    TextKey.SMS_INBOX_PERMISSION_REVOKED to "The messages permission was revoked. Check Android permissions; pending messages are kept.",
    TextKey.SMS_SENDERS_REQUIRED to "Enter the bank sender names (up to 10)",
    TextKey.SMS_INBOX_PERMISSION_MISSING to "The messages permission isn't available. Turn it on in Android permissions or use paste.",
    TextKey.FILE_NAME_INVALID to "The file name or content isn't valid",
    TextKey.BACKUP_DEVICE_SAVE_FAILED to "Couldn't save the backup on the device",
    TextKey.PDF_PASSWORD to "The file is password-protected — open it, save it without a password and try again",
    TextKey.PDF_INVALID to "This file isn't a PDF or it's damaged",
    TextKey.FILE_NOT_TEXT to "This isn't a text file{0}. A CSV file is expected — text with comma-separated columns.",
)
