package app.masroufy.core

/**
 * نصوص «تفاصيل الأصل» (`AssetDetail`) — جزء من نصوص منطقة الاستثمار (بتتضم في `TextsAreaInvestment.kt`). الفصحى · المصري · الإنجليزي.
 * «الحصيلة» اتكتبت «مبلغ البيع» (تبسيط الكلمات — `PlainWords.kt`).
 */
internal val MSA_INVEST_ASSET_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ASSET_DETAIL_STALE_BODY to "المعروض بسعر آخر تحديث ناجح.",
    UiKey.ASSET_DETAIL_ARCHIVED to "مؤرشف — سجله باقٍ ويظهر آخر القائمة.",
    UiKey.ASSET_DETAIL_UNARCHIVE to "أعِده",
    UiKey.ASSET_DETAIL_UNARCHIVED to "عاد إلى أملاكك",
    UiKey.ASSET_DETAIL_HERO to "قيمته اليوم بسعر السوق",
    UiKey.ASSET_DETAIL_NA_PRICE to "لا سعر مسجّل. القيمة الحالية غير متاحة",
    UiKey.ASSET_DETAIL_NA_RE to "قيمة الأصل اليوم غير متاحة: اكتب سعره، أو المساحة وسعر المتر",
    UiKey.ASSET_DETAIL_WRITE_PRICE to "اكتب سعرًا يدويًا",
    UiKey.ASSET_DETAIL_WRITE_AREA to "اكتب المساحة وسعر المتر",
    UiKey.ASSET_DETAIL_PRICE_LINE to "السعر {0} لل{1}، {2}",
    UiKey.ASSET_DETAIL_PRICE_NONE to "لم يصل سعر اليوم",
    UiKey.ASSET_DETAIL_AREA_LINE to "{0} م² × {1} للمتر، {2}",
    UiKey.ASSET_DETAIL_AREA_NONE to "سعر المتر غير مسجّل",
    UiKey.ASSET_DETAIL_CHIP_FRESH to "حديث",
    UiKey.ASSET_DETAIL_CHIP_STALE to "قديم",
    UiKey.ASSET_DETAIL_CHIP_MANUAL to "يدوي",
    UiKey.ASSET_DETAIL_CHIP_MISSING to "ناقص",
    UiKey.ASSET_DETAIL_TODAY to "اليوم",
    UiKey.ASSET_DETAIL_QTY to "الكمية",
    UiKey.ASSET_DETAIL_AVG to "متوسط التكلفة",
    UiKey.ASSET_DETAIL_AVG_SUB to "لل{0}، متوسط مرجّح",
    UiKey.ASSET_DETAIL_COST to "التكلفة",
    UiKey.ASSET_DETAIL_COST_SUB to "تشمل رسوم الشراء",
    UiKey.ASSET_DETAIL_NO_SALES to "لا مبيعات",
    UiKey.ASSET_DETAIL_NOT_SOLD to "لم تبع بعد",
    UiKey.ASSET_DETAIL_FROM_SALES to "من عمليات البيع ({0})",
    UiKey.ASSET_DETAIL_FULL_TITLE to "الصورة كاملة",
    UiKey.ASSET_DETAIL_FULL_BODY to "كم ستساوي لو بعتها؟ السعر عند البيع + الإيجار + المكسب منذ الشراء",
    UiKey.ASSET_DETAIL_BUY to "شراء",
    UiKey.ASSET_DETAIL_SELL to "بيع",
    UiKey.ASSET_DETAIL_RECORD_ONLY to "تسجيل فقط — لا يشتري التطبيق ولا يبيع.",
    UiKey.ASSET_DETAIL_LOG to "المشتريات والمبيعات",
    UiKey.ASSET_DETAIL_LOG_EMPTY to "لا مشتريات مسجّلة بعد",
    UiKey.ASSET_DETAIL_LINE_FEE to "{0}، رسوم {1}",
    UiKey.ASSET_DETAIL_LINE_NO_FEE to "{0}، بلا رسوم",
    UiKey.ASSET_DETAIL_LINKED to "مربوط بعملية",
    UiKey.ASSET_DETAIL_METHOD to "التكلفة بالمتوسط المرجّح: رسوم الشراء تدخل فيها، ورسوم البيع تُخصم من مبلغ البيع.",
    UiKey.ASSET_DETAIL_SRC_LINKED to "مربوط بالسعر اليومي",
    UiKey.ASSET_DETAIL_SRC_MANUAL to "سعر يدوي",
    UiKey.ASSET_DETAIL_SRC_SQM to "سعر المتر يدوي",
    UiKey.ASSET_DETAIL_SRC_LINKED_BODY to "السعر من ملف الأسعار ({0})، يتحدّث كل يوم. إن تعطّل المصدر لا يُختلق سعر.",
    UiKey.ASSET_DETAIL_SRC_MANUAL_BODY to "لا يتحدّث وحده. يبقى آخر سعر حتى تكتب غيره.",
    UiKey.ASSET_DETAIL_SRC_SQM_BODY to "لا مصدر تلقائي لسعر المتر بعد — حدّثه من «الصورة كاملة».",
    UiKey.ASSET_DETAIL_ACT_MANUAL to "سعر يدوي",
    UiKey.ASSET_DETAIL_ACT_UNLINK to "فك الربط",
    UiKey.ASSET_DETAIL_ACT_LINK to "اربطه بالسعر اليومي",
    UiKey.ASSET_DETAIL_UNLINKED to "فُكّ الربط — يبقى السعر كما هو حتى تكتب غيره",
    UiKey.ASSET_DETAIL_LINKED_TO to "رُبط بسعر «{0}» اليومي",
    UiKey.ASSET_DETAIL_PICK_FEED to "اختر السعر اليومي",
    UiKey.ASSET_DETAIL_PICK_FEED_EMPTY to "لا أسعار بعملة الأصل في ملف الأسعار.",
    UiKey.ASSET_DETAIL_ARCHIVE to "أرشفة الأصل",
    UiKey.ASSET_DETAIL_ARCHIVED_TOAST to "أُرشف — سجله باقٍ",
)

internal val EGYPTIAN_INVEST_ASSET_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ASSET_DETAIL_STALE_BODY to "المعروض بسعر آخر تحديث نجح.",
    UiKey.ASSET_DETAIL_ARCHIVED to "متأرشف — سجله موجود وبيظهر آخر القايمة.",
    UiKey.ASSET_DETAIL_UNARCHIVE to "رجّعه",
    UiKey.ASSET_DETAIL_UNARCHIVED to "رجع لأملاكك",
    UiKey.ASSET_DETAIL_HERO to "قيمته النهارده بسعر السوق",
    UiKey.ASSET_DETAIL_NA_PRICE to "مفيش سعر متسجّل. القيمة دلوقتي غير متاحة",
    UiKey.ASSET_DETAIL_NA_RE to "قيمة الأصل النهارده غير متاحة: اكتب سعره، أو المساحة وسعر المتر",
    UiKey.ASSET_DETAIL_WRITE_PRICE to "اكتب سعر بإيدك",
    UiKey.ASSET_DETAIL_WRITE_AREA to "اكتب المساحة وسعر المتر",
    UiKey.ASSET_DETAIL_PRICE_LINE to "السعر {0} لل{1}، {2}",
    UiKey.ASSET_DETAIL_PRICE_NONE to "سعر النهارده ما وصلش",
    UiKey.ASSET_DETAIL_AREA_LINE to "{0} م² × {1} للمتر، {2}",
    UiKey.ASSET_DETAIL_AREA_NONE to "سعر المتر مش متسجّل",
    UiKey.ASSET_DETAIL_CHIP_FRESH to "جديد",
    UiKey.ASSET_DETAIL_CHIP_STALE to "قديم",
    UiKey.ASSET_DETAIL_CHIP_MANUAL to "بإيدك",
    UiKey.ASSET_DETAIL_CHIP_MISSING to "ناقص",
    UiKey.ASSET_DETAIL_TODAY to "النهارده",
    UiKey.ASSET_DETAIL_QTY to "الكمية",
    UiKey.ASSET_DETAIL_AVG to "متوسط التكلفة",
    UiKey.ASSET_DETAIL_AVG_SUB to "لل{0}، متوسط مرجّح",
    UiKey.ASSET_DETAIL_COST to "التكلفة",
    UiKey.ASSET_DETAIL_COST_SUB to "فيها رسوم الشراء",
    UiKey.ASSET_DETAIL_NO_SALES to "مفيش بيع",
    UiKey.ASSET_DETAIL_NOT_SOLD to "لسه ما بعتش",
    UiKey.ASSET_DETAIL_FROM_SALES to "من البيع ({0})",
    UiKey.ASSET_DETAIL_FULL_TITLE to "الصورة كاملة",
    UiKey.ASSET_DETAIL_FULL_BODY to "هتساوي كام لو بعتها؟ السعر وقت البيع + الإيجار + المكسب من يوم الشراء",
    UiKey.ASSET_DETAIL_BUY to "شراء",
    UiKey.ASSET_DETAIL_SELL to "بيع",
    UiKey.ASSET_DETAIL_RECORD_ONLY to "تسجيل بس — التطبيق مش بيشتري ولا بيبيع.",
    UiKey.ASSET_DETAIL_LOG to "الشراء والبيع",
    UiKey.ASSET_DETAIL_LOG_EMPTY to "مفيش شراء متسجّل لسه",
    UiKey.ASSET_DETAIL_LINE_FEE to "{0}، رسوم {1}",
    UiKey.ASSET_DETAIL_LINE_NO_FEE to "{0}، من غير رسوم",
    UiKey.ASSET_DETAIL_LINKED to "مربوط بعملية",
    UiKey.ASSET_DETAIL_METHOD to "التكلفة بالمتوسط المرجّح: رسوم الشراء بتدخل فيها، ورسوم البيع بتتخصم من الفلوس اللي قبضتها.",
    UiKey.ASSET_DETAIL_SRC_LINKED to "مربوط بالسعر اليومي",
    UiKey.ASSET_DETAIL_SRC_MANUAL to "سعر بإيدك",
    UiKey.ASSET_DETAIL_SRC_SQM to "سعر المتر بإيدك",
    UiKey.ASSET_DETAIL_SRC_LINKED_BODY to "السعر من ملف الأسعار ({0})، بيتحدّث كل يوم. لو المصدر وقع، مفيش سعر بيتألّف.",
    UiKey.ASSET_DETAIL_SRC_MANUAL_BODY to "مش بيتحدّث لوحده. بيفضل آخر سعر لحد ما تكتب غيره.",
    UiKey.ASSET_DETAIL_SRC_SQM_BODY to "مفيش مصدر تلقائي لسعر المتر لسه — حدّثه من «الصورة كاملة».",
    UiKey.ASSET_DETAIL_ACT_MANUAL to "سعر بإيدك",
    UiKey.ASSET_DETAIL_ACT_UNLINK to "فك الربط",
    UiKey.ASSET_DETAIL_ACT_LINK to "اربطه بالسعر اليومي",
    UiKey.ASSET_DETAIL_UNLINKED to "اتفك الربط — السعر بيفضل زي ما هو لحد ما تكتب غيره",
    UiKey.ASSET_DETAIL_LINKED_TO to "اتربط بسعر «{0}» اليومي",
    UiKey.ASSET_DETAIL_PICK_FEED to "اختار السعر اليومي",
    UiKey.ASSET_DETAIL_PICK_FEED_EMPTY to "مفيش أسعار بعملة الأصل في ملف الأسعار.",
    UiKey.ASSET_DETAIL_ARCHIVE to "أرشف الأصل",
    UiKey.ASSET_DETAIL_ARCHIVED_TOAST to "اتأرشف — سجله موجود",
)

internal val ENGLISH_INVEST_ASSET_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ASSET_DETAIL_STALE_BODY to "Showing the price from the last successful update.",
    UiKey.ASSET_DETAIL_ARCHIVED to "Archived — its record stays, at the end of the list.",
    UiKey.ASSET_DETAIL_UNARCHIVE to "Restore",
    UiKey.ASSET_DETAIL_UNARCHIVED to "Back in your assets",
    UiKey.ASSET_DETAIL_HERO to "Its value today at market price",
    UiKey.ASSET_DETAIL_NA_PRICE to "No price recorded. The current value isn't available",
    UiKey.ASSET_DETAIL_NA_RE to "The asset's value today isn't available: enter its price, or the area and the price per m²",
    UiKey.ASSET_DETAIL_WRITE_PRICE to "Enter a price yourself",
    UiKey.ASSET_DETAIL_WRITE_AREA to "Enter the area and the price per m²",
    UiKey.ASSET_DETAIL_PRICE_LINE to "Price {0} per {1}, {2}",
    UiKey.ASSET_DETAIL_PRICE_NONE to "Today's price hasn't arrived",
    UiKey.ASSET_DETAIL_AREA_LINE to "{0} m² × {1} per m², {2}",
    UiKey.ASSET_DETAIL_AREA_NONE to "No price per m² recorded",
    UiKey.ASSET_DETAIL_CHIP_FRESH to "Fresh",
    UiKey.ASSET_DETAIL_CHIP_STALE to "Old",
    UiKey.ASSET_DETAIL_CHIP_MANUAL to "Manual",
    UiKey.ASSET_DETAIL_CHIP_MISSING to "Missing",
    UiKey.ASSET_DETAIL_TODAY to "today",
    UiKey.ASSET_DETAIL_QTY to "Quantity",
    UiKey.ASSET_DETAIL_AVG to "Average cost",
    UiKey.ASSET_DETAIL_AVG_SUB to "Per {0}, weighted average",
    UiKey.ASSET_DETAIL_COST to "Cost",
    UiKey.ASSET_DETAIL_COST_SUB to "Includes purchase fees",
    UiKey.ASSET_DETAIL_NO_SALES to "No sales",
    UiKey.ASSET_DETAIL_NOT_SOLD to "Not sold yet",
    UiKey.ASSET_DETAIL_FROM_SALES to "From sales ({0})",
    UiKey.ASSET_DETAIL_FULL_TITLE to "The full picture",
    UiKey.ASSET_DETAIL_FULL_BODY to "What would it be worth if you sold it? Sale price + rent + gain since purchase",
    UiKey.ASSET_DETAIL_BUY to "Buy",
    UiKey.ASSET_DETAIL_SELL to "Sell",
    UiKey.ASSET_DETAIL_RECORD_ONLY to "Record only — the app doesn't buy or sell.",
    UiKey.ASSET_DETAIL_LOG to "Purchases and sales",
    UiKey.ASSET_DETAIL_LOG_EMPTY to "No purchases recorded yet",
    UiKey.ASSET_DETAIL_LINE_FEE to "{0}, fees {1}",
    UiKey.ASSET_DETAIL_LINE_NO_FEE to "{0}, no fees",
    UiKey.ASSET_DETAIL_LINKED to "Linked to a transaction",
    UiKey.ASSET_DETAIL_METHOD to "Cost uses the weighted average: purchase fees are part of it, and sale fees come out of the sale amount.",
    UiKey.ASSET_DETAIL_SRC_LINKED to "Linked to the daily price",
    UiKey.ASSET_DETAIL_SRC_MANUAL to "Manual price",
    UiKey.ASSET_DETAIL_SRC_SQM to "Manual price per m²",
    UiKey.ASSET_DETAIL_SRC_LINKED_BODY to "The price comes from the prices file ({0}) and updates every day. If the source fails, no price is made up.",
    UiKey.ASSET_DETAIL_SRC_MANUAL_BODY to "It doesn't update by itself. The last price stays until you enter another.",
    UiKey.ASSET_DETAIL_SRC_SQM_BODY to "There's no automatic source for the price per m² yet — update it from “The full picture”.",
    UiKey.ASSET_DETAIL_ACT_MANUAL to "Manual price",
    UiKey.ASSET_DETAIL_ACT_UNLINK to "Unlink",
    UiKey.ASSET_DETAIL_ACT_LINK to "Link to the daily price",
    UiKey.ASSET_DETAIL_UNLINKED to "Unlinked — the price stays as it is until you enter another",
    UiKey.ASSET_DETAIL_LINKED_TO to "Linked to the daily “{0}” price",
    UiKey.ASSET_DETAIL_PICK_FEED to "Pick the daily price",
    UiKey.ASSET_DETAIL_PICK_FEED_EMPTY to "There are no prices in the asset's currency in the prices file.",
    UiKey.ASSET_DETAIL_ARCHIVE to "Archive the asset",
    UiKey.ASSET_DETAIL_ARCHIVED_TOAST to "Archived — its record stays",
)
