package app.masroufy.core

/** باقي نصوص الواجهة المشتركة **بالمصري** — نفس مفاتيح `TextsShellAuth.kt` (ملف لوحده عشان حد الـ300 سطر). */
internal val EGYPTIAN_SHELL_AUTH_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.UPCOMING_TITLE to "القادم",
    UiKey.UPCOMING_LIST to "المواعيد الجاية",
    UiKey.UPCOMING_TODAY to "النهارده",
    UiKey.UPCOMING_TOMORROW to "بكرة",
    UiKey.UPCOMING_TWO_DAYS to "بعد يومين",
    UiKey.UPCOMING_FEW_DAYS to "بعد {0} أيام",
    UiKey.UPCOMING_MANY_DAYS to "بعد {0} يوم",
    UiKey.UPCOMING_HELD to "محجوز",
    UiKey.UPCOMING_OPEN to "مش محجوز",
    UiKey.UPCOMING_NO_AMOUNT to "من غير مبلغ",
    UiKey.UPCOMING_INCOMING to "فلوس جاية",
    UiKey.UPCOMING_LATE to "فات ميعاده",
    UiKey.UPCOMING_EMPTY to "مفيش مواعيد جاية.",
    UiKey.CALENDAR_OPEN to "التقويم",
    UiKey.QUICK_TITLE to "متوقعة الشهر ده ولسه ما اتسجلتش",
    UiKey.QUICK_SHEET_BODY to "المبلغ المعتاد جاهز — غيّره لو اختلف الشهر ده.",
    UiKey.QUICK_USUAL to "عادةً {0}، يوم {1}",
    UiKey.QUICK_FROM to "دفعتها منين؟",
    UiKey.QUICK_SAVE to "سجّلها",
    UiKey.QUICK_SKIP to "مش هدفعها الشهر ده",
    UiKey.QUICK_RECORDED to "اتسجّل «{0}» {1}",
    UiKey.QUICK_SKIPPED to "تمام — مش هنسألك عنها تاني الشهر ده.",
    UiKey.CAL_PREV to "الشهر اللي فات",
    UiKey.CAL_NEXT to "الشهر الجاي",
    UiKey.CAL_TODAY to "النهارده",
    UiKey.CAL_NO_DATES to "مفيش مواعيد",
    UiKey.CAL_LEGEND_SUB to "اشتراكات وفواتير",
    UiKey.CAL_LEGEND_INST to "أقساط",
    UiKey.CAL_LEGEND_ROSCA to "جمعيات",
    UiKey.CAL_LEGEND_DEBT to "ديون",
    UiKey.CAL_LEGEND_EVENT to "أحداث ومناسبات",
    UiKey.CAL_LEGEND_PAY to "المرتب",
    UiKey.CAL_LEGEND_LATE to "فات ميعاده",
    UiKey.CAL_MORE to "+{0}",
    UiKey.SIGNIN_WELCOME_TITLE to "أهلًا بيك في مصروفي",
    UiKey.SIGNIN_WELCOME_SUB to "دقيقة واحدة نجهّز فيها حسابك، والباقي وقت ما تحب.",
    UiKey.SIGNIN_HOW to "عايز تدخل إزاي؟",
    UiKey.SIGNIN_HOW_SUB to "حسابك بيحفظ بياناتك ويزامنها على كل أجهزتك.",
    UiKey.SIGNIN_GOOGLE to "الدخول بحساب Google",
    UiKey.SIGNIN_WITH_EMAIL to "الدخول بالإيميل",
    UiKey.SIGNIN_TITLE to "الدخول بالإيميل",
    UiKey.SIGNIN_MODES to "نوع الدخول",
    UiKey.SIGNIN_MODE_IN to "تسجيل الدخول",
    UiKey.SIGNIN_MODE_NEW to "حساب جديد",
    UiKey.SIGNIN_EMAIL to "الإيميل",
    UiKey.SIGNIN_PASSWORD to "كلمة السر",
    UiKey.SIGNIN_PASS_HINT to "6 حروف على الأقل.",
    UiKey.SIGNIN_SHOW_PASS to "اظهر كلمة السر",
    UiKey.SIGNIN_HIDE_PASS to "اخفي كلمة السر",
    UiKey.SIGNIN_SUBMIT_IN to "دخول",
    UiKey.SIGNIN_SUBMIT_NEW to "اعمل الحساب",
    UiKey.SIGNIN_BUSY_IN to "بيدخل…",
    UiKey.SIGNIN_BUSY_NEW to "الحساب بيتعمل…",
    UiKey.SIGNIN_DONE_IN to "دخلت",
    UiKey.SIGNIN_DONE_NEW to "حسابك اتعمل",
    UiKey.SIGNIN_DONE_LINE to "هنكمّل تجهيز حسابك من مكان ما وقفت.",
    UiKey.SIGNIN_OFFLINE_NOTE to "الدخول محتاج نت.",
    UiKey.SIGNIN_EMULATOR_NOTE to "نسخة اختبار على محاكي فايربيز في الكمبيوتر — بيانات وهمية بس.",
    UiKey.RESET_TRIGGER to "نسيت كلمة السر؟",
    UiKey.RESET_TITLE to "نسيت كلمة السر",
    UiKey.RESET_BODY to "اكتب إيميلك وهنبعتلك عليه لينك تعمل بيه كلمة سر جديدة.",
    UiKey.RESET_EMAIL_EMPTY to "اكتب الإيميل",
    UiKey.RESET_SEND to "ابعت لينك التغيير",
    UiKey.RESET_SENDING to "بيتبعت…",
    UiKey.RESET_PRIVACY to "علشان نحمي الحسابات، مش بنقول إذا كان الإيميل متسجل عندنا ولا لأ.",
    UiKey.RESET_SENT_TITLE to "بص على إيميلك",
    UiKey.RESET_SENT_BODY to "لو {0} متسجل عندنا، هيوصله لينك تعمل بيه كلمة سر جديدة خلال دقايق.",
    UiKey.RESET_SPAM to "موصلش؟ بص في الرسايل المزعجة، أو ابعته تاني.",
    UiKey.RESET_RESEND to "ابعته تاني",
    UiKey.RESET_AGAIN to "اتبعت تاني.",
    UiKey.RESET_WAIT_ONE to "تقدر تبعته تاني بعد ثانية.",
    UiKey.RESET_WAIT_TWO to "تقدر تبعته تاني بعد ثانيتين.",
    UiKey.RESET_WAIT_FEW to "تقدر تبعته تاني بعد {0} ثواني.",
    UiKey.RESET_WAIT_MANY to "تقدر تبعته تاني بعد {0} ثانية.",
    UiKey.RESET_CHANGE to "غيّر الإيميل",
    UiKey.RESET_FINISH to "ارجع لتسجيل الدخول",
    UiKey.RESET_OFFLINE to "إعادة الإرسال محتاجة نت.",
    UiKey.LOCK_SCREEN_TITLE to "مصروفي مقفول",
    UiKey.LOCK_SCREEN_BODY to "افتحه ببصمتك أو رمز الموبايل.",
    UiKey.LOCK_SCREEN_OPEN to "افتح",
    UiKey.LOCK_RELEASED to "الموبايل مالوش قفل، فقفل التطبيق اتوقف. شغّله من «المزيد ← الإعدادات» بعد ما تعمل قفل للموبايل.",
    UiKey.FEED_OFFLINE to "مفيش نت — ما عرفناش نحدّث الأسعار.",
    UiKey.FEED_HTTP_FAILED to "ما عرفناش ننزّل الملف (الرد {0}).",
    UiKey.FEED_UPDATED_AT to "آخر تحديث {0}",
    UiKey.AUTH_GOOGLE_NO_ACCOUNT to "مفيش حساب Google على الموبايل ده. ضيفه من إعدادات الموبايل أو ادخل بالإيميل.",
    UiKey.AUTH_GOOGLE_FAILED to "ما عرفناش ندخل بحساب Google دلوقتي. جرّب تاني أو ادخل بالإيميل.",
)
