package app.masroufy.core

/**
 * النصوص بالإنجليزي — كتابة Claude ومراجعة المالك (OVERRIDES §40).
 * أي مفتاح ناقص هنا بيرجع بالعربي، فالشاشة ما بتفضاش أبدًا.
 */
internal val ENGLISH_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.KIND_SALARY to "Salary",
    TextKey.KIND_BONUS to "Bonus",
    TextKey.KIND_COMMISSION to "Commission",
    TextKey.KIND_OVERTIME to "Overtime",
    TextKey.KIND_FREELANCE to "Freelance",
    TextKey.KIND_PERSONAL_SALE to "Personal sale",
    TextKey.KIND_LOAN_RECEIVED to "Loan received",
    TextKey.KIND_DEBT_COLLECTED to "Debt collected",
    TextKey.KIND_CUSTODY_RECEIVED to "Custody received",
    TextKey.KIND_PURCHASE to "Purchase / bill",
    TextKey.KIND_SUPPORT_GIFT to "Support / gift",
    TextKey.KIND_FEE to "Fee",
    TextKey.KIND_LOAN_GRANTED to "Loan granted",
    TextKey.KIND_DEBT_REPAID to "Debt repaid",
    TextKey.KIND_CUSTODY_RETURNED to "Custody returned",
    TextKey.KIND_INTERNAL_TRANSFER to "Internal transfer",
    TextKey.KIND_ASSET_BUY to "Asset purchase",
    TextKey.KIND_ASSET_SELL to "Asset sale",
    TextKey.KIND_UNCLASSIFIED to "Undecided",
    TextKey.KIND_UNKNOWN_WIRE to "Unknown economic kind: {0}",

    TextKey.CURRENCY_SAR to "SAR",
    TextKey.CURRENCY_EGP to "EGP",
    TextKey.CURRENCY_USD to "$",
    TextKey.CURRENCY_EUR to "€",
    TextKey.CURRENCY_GBP to "£",
    TextKey.CURRENCY_AED to "AED",

    TextKey.NOT_AVAILABLE to "Not available",

    TextKey.AMOUNT_CONTEXT_DISPLAY to "amount to display",
    TextKey.AMOUNT_CONTEXT_INCOME to "income",
    TextKey.AMOUNT_CONTEXT_REMAINING to "remaining",

    TextKey.SUGGEST_CASH_WITHDRAWAL to
        "Cash withdrawal: the money moved from the bank to your cash wallet — it was not spent",
    TextKey.SUGGEST_INVESTMENT_BUY to "“{0}”: buying an investment asset, not consumption",
    TextKey.SUGGEST_BANK_FEES to "Bank fees: an expense in its own right",
    TextKey.SUGGEST_INSTALLMENT to
        "Installment: paying part of an earlier commitment. If the original purchase is already recorded as an expense, counting it again would be double counting.",
    TextKey.SUGGEST_DEBT_PAYMENT to
        "Payment: this can be repaying a debt you owe (not an expense) or paying a bill (an expense). The statement does not tell them apart, so it needs your decision.",
    TextKey.SUGGEST_DIGITAL_WALLET to
        "Digital wallet (such as Barq): the money left the bank, but the statement does not say where it went. It may be your own wallet, or support or a loan to someone.",
    TextKey.SUGGEST_TRANSFER_OUT to
        "Outgoing transfer: the statement says money left but not why. It may be a transfer to your own account, support, a loan, or a repayment.",
    TextKey.SUGGEST_BARQ to
        "Barq is a way to transfer, not a kind of expense. You need to set the purpose: your account, support, a loan, or a repayment.",
    TextKey.SUGGEST_PURCHASE to "“{0}”: a purchase or a bill",
    TextKey.SUGGEST_OUT_NO_CATEGORY to
        "Outgoing with no clear category. You need to say whether this is a purchase or moving money.",
    TextKey.SUGGEST_INVESTMENT_SELL to
        "Incoming from investment: proceeds of an asset sale, and only the realized profit is a gain",
    TextKey.SUGGEST_REFUND to
        "Refund: this is money you paid coming back, not new income. It is better linked to the original transaction than counted as income.",
    TextKey.SUGGEST_IN_UNKNOWN to
        "Incoming: the statement says money came in but not from where. Salary? A loan you received? A debt collected? Custody? The difference matters a great deal.",
    TextKey.SUGGEST_IN_WITH_CATEGORY to "Incoming under “{0}”: you need to set its economic kind.",
    TextKey.ASSET_KIND_GOLD to "Gold",
    TextKey.ASSET_KIND_STOCK to "Stock",
    TextKey.ASSET_KIND_FUND to "Fund",
    TextKey.ASSET_KIND_DIGITAL to "Digital asset",
    TextKey.ASSET_KIND_OTHER to "Other asset",
    TextKey.AMOUNT_EDIT_INVALID to "Enter a valid amount greater than zero, such as 180 or 180.50",
    TextKey.AMOUNT_EDIT_BELOW_ALLOCATIONS to "The amount is less than what is already split with people on this transaction ({0}). Adjust the split first.",
    TextKey.AMOUNT_EDIT_BELOW_SETTLEMENTS to "The amount is less than what has already been settled against a debt from this transaction ({0}). Adjust the settlement first.",
    TextKey.ALLOWANCE_PERIOD_ENDED to "This period is over, so there are no days left to spread it over.",
    TextKey.ALLOWANCE_NO_LIMIT_NO_REMAINING to "This period has no limit, and what is left is not known yet either.",
    TextKey.ALLOWANCE_NO_LIMIT_SPENT to "Approximate — no budget limit, and nothing is left.",
    TextKey.ALLOWANCE_NO_LIMIT to "Approximate — no budget limit, so this is what is left spread over the {0} days remaining.",
    TextKey.ALLOWANCE_LIMIT_SPENT to "The limit for this period is used up.",
    TextKey.ALLOWANCE_LIMIT to "What is left of the limit, spread over the {0} days remaining.",
    TextKey.FORECAST_TOO_EARLY to "Only {0} days have passed — a forecast needs at least {1} days.",
    TextKey.FORECAST_PERIOD_ENDED to "The period is over, so this is the actual spending, not a forecast.",
    TextKey.FORECAST_RATE to "If the rest of the period goes at the same rate ({0} days so far).",
    TextKey.COVERAGE_ALL_UNCLASSIFIED to "All {0} transactions still need their kind set, so the totals are not available.",
    TextKey.COVERAGE_SOME_UNCLASSIFIED to "{0} of {1} transactions still need their kind set, so these figures are incomplete.",
    TextKey.BUDGET_LIMIT_POSITIVE to "The limit has to be greater than zero",
    TextKey.PERIOD_EXCLUDED_UNRELIABLE to "It has transactions that still need their kind set, so its spending is incomplete",
    TextKey.PERIOD_EXCLUDED_EMPTY to "It has no transactions — unclear whether that is a real zero or missing data",
    TextKey.AVERAGE_NEEDS_PERIODS to "An average needs at least {0} complete periods, and {1} are available.",
    TextKey.AVERAGE_OF_PERIODS to "Average of {0} complete periods.",
    TextKey.ANOMALY_NEEDS_HISTORY to "Judging an anomaly needs at least {0} earlier periods, and {1} are available.",
    TextKey.ANOMALY_MEDIAN_ZERO to "The historical median is zero, so a relative comparison means nothing.",
    TextKey.ANOMALY_WITHIN_TWENTY to "The difference from usual is under 20%, so it is not an anomaly.",
    TextKey.ANOMALY_HIGHER to "higher",
    TextKey.ANOMALY_LOWER to "lower",
    TextKey.ANOMALY_OUTSIDE to "{1}% {0} than usual — outside the swing of the earlier periods.",
    TextKey.ANOMALY_INSIDE to "{1}% {0} than usual, but that is within the normal swing of the earlier periods.",
    TextKey.CATEGORY_NO_LIMIT to "This category has no limit. You can set one here.",
    TextKey.CATEGORIZED_USER_CONFIRMED to "You confirmed this category yourself",
    TextKey.CATEGORIZED_MERCHANT to "The store “{0}” has a confirmed category",
    TextKey.CATEGORIZED_RULE to "Rule “{0}” matched",
    TextKey.CATEGORIZED_SOURCE_COLUMN to "The category came from the category column in the file: “{0}”",
    TextKey.CATEGORIZED_NONE to "No rule and no confirmed store matched this transaction",
    TextKey.ASSET_BUY_QUANTITY_POSITIVE to "The purchase quantity has to be greater than zero",
    TextKey.ASSET_SELL_QUANTITY_POSITIVE to "The sale quantity has to be greater than zero",
    TextKey.ASSET_SELL_OVER_HELD to "Selling {0} while only {1} was held at the time. No silent negative balance.",
    TextKey.PRICE_MISSING to "No price recorded. The current value is not available",
    TextKey.PRICE_FRESH to "Price {0} as of {1}",
    TextKey.PRICE_FUTURE to "Price as of {0} — a date in the future, check it",
    TextKey.PRICE_STALE to "Price {0} as of {1} — {2} days old",
    TextKey.FEED_BAD_SHAPE to "The price file is not in the expected shape",
    TextKey.FEED_NO_GENERATED_AT to "The price file has no generation date",
    TextKey.FEED_NO_CURRENCY to "The price file does not say its currency",
    TextKey.FEED_NO_PRICES to "The price file has no prices",
    TextKey.FEED_ENTRY_NOT_OBJECT to "The entry is not an object",
    TextKey.FEED_PRICE_NOT_INTEGER to "The price is not a positive whole number in the smallest currency unit",
    TextKey.FEED_NO_VALID_DATE to "No valid date for the price",
    TextKey.FEED_NO_SOURCE to "No source written for the price",
    TextKey.FEED_UNKNOWN_SOURCE to "Unknown source",
    TextKey.FEED_NO_REASON to "No reason written",
    TextKey.FEED_SUMMARY to "{0} prices updated on {1}",
    TextKey.FEED_SUMMARY_WITH_MISSING to "{0}, and {1} sources returned no price",
    TextKey.JOIN_AND to " and ",
    TextKey.GROUP_FOOD to "Food and drink",
    TextKey.GROUP_HOME to "Home and commitments",
    TextKey.GROUP_TRANSPORT to "Getting around",
    TextKey.GROUP_PERSONAL to "Personal life",
    TextKey.GROUP_SAVING to "Saving and investing",
    TextKey.GROUP_MOVEMENT to "Money moves, not spending",
    TextKey.REQ_HAS_CAR to "If they have a car",
    TextKey.REQ_DEPENDENTS to "If they support a spouse or children",
    TextKey.REQ_RENTER to "If they live in a rental",
    TextKey.REQ_DOMESTIC_WORKER to "If they have domestic help",
    TextKey.REQ_BUSINESS to "If they have their own business",
    TextKey.DIFF_DATE to "the date",
    TextKey.DIFF_AMOUNT to "the amount",
    TextKey.DIFF_DIRECTION to "the direction",
    TextKey.DIFF_MERCHANT to "the store name",
    TextKey.DEDUPE_SMS_SIMILAR to "There is a transaction with the same day, amount and direction in the same wallet, and one of the two sources is a bank message. It may be the same transaction under a different name; not selected for adding until you review it.",
    TextKey.DEDUPE_SAME_REFERENCE to "Same reference “{0}” and the same details — this transaction is already recorded",
    TextKey.DEDUPE_REFERENCE_CONFLICT to "Same reference “{0}” but {1} is different. We will not overwrite the old one without your decision.",
    TextKey.DEDUPE_SAME_STATEMENT_LINE to "Same statement line: same day, amount, direction and balance after the transaction in the same account — already recorded even if the name reads differently",
    TextKey.DEDUPE_NEW_REFERENCE to "A new reference that was not there before",
    TextKey.DEDUPE_SIMILAR_NO_REFERENCE to "Same store, amount, date and direction, with no bank reference to confirm it. It may be the same transaction or a real second one — it needs your decision.",
    TextKey.DEDUPE_NEW to "A new transaction, nothing like it",
    TextKey.NOTICE_SPENT_OVER to "Spent {0} of {1} — {2} over",
    TextKey.NOTICE_SPENT_LEFT to "Spent {0} of {1} — {2} left",
    TextKey.NOTICE_BUDGET_EXCEEDED to "You went over the budget",
    TextKey.NOTICE_BUDGET_THRESHOLD to "You reached {0}% of the budget",
    TextKey.NOTICE_CATEGORY_EXCEEDED to "You went over the limit for “{0}”",
    TextKey.NOTICE_CATEGORY_THRESHOLD to "“{0}” reached {1}%",
    TextKey.LEDGER_ALLOCATIONS_EXCEED to "The splits add up to ({0}), more than the transaction itself ({1})",
    TextKey.LEDGER_SETTLEMENTS_EXCEED to "Settlements for obligation {0} went past its original amount — a silent negative balance is not allowed",
    TextKey.SETTLEMENT_AMOUNT_POSITIVE to "The settlement amount has to be greater than zero",
    TextKey.SETTLEMENT_FULLY_PAID to "This obligation is fully paid. There is nothing left to settle",
    TextKey.OBLIGATION_CUSTODY to "The custody",
    TextKey.OBLIGATION_LOAN to "The debt",
    TextKey.OBLIGATION_RECEIVABLE to "The receivable",
    TextKey.SETTLEMENT_OVER_REMAINING to "The amount is more than what is left. {0} left is {1} and the amount you entered is {2}. You can settle {1} and record the remaining {3} as a separate custody with an explicit step.",
    TextKey.LEDGER_FEE_NEGATIVE to "Fees cannot be negative",
    TextKey.LEDGER_FEE_OVER_GROSS to "The fees ({0}) are more than the total deducted ({1})",
    TextKey.SCHEMA_UNKNOWN_COLUMNS to "The columns do not match any known layout.\nFound: {0}\nExpected either: {1}\nor: {2}\nIf the file has different columns, it needs a manual column mapping — we do not guess financial columns.",
    TextKey.ROW_DATE_INVALID to "The date “{0}” is not valid. Expected YYYY-MM-DD with a date that really exists",
    TextKey.ROW_AMOUNT_INVALID to "The amount “{0}” is not a valid number",
    TextKey.ROW_AMOUNT_NEGATIVE to "The amount “{0}” is negative. The direction comes from the type column",
    TextKey.ROW_AMOUNT_ZERO to "The amount is zero — this transaction has no financial effect",
    TextKey.ROW_TYPE_UNKNOWN to "The transaction type “{0}” is not known. Expected expense, income or transfer",
    TextKey.ROW_LEGACY_DATE_INVALID to "The date “{0}” is not valid. Expected YYYY/MM/DD with a date that exists",
    TextKey.ROW_DEBIT_INVALID to "The debit value “{0}” is not a valid number",
    TextKey.ROW_CREDIT_INVALID to "The credit value “{0}” is not a valid number",
    TextKey.ROW_DEBIT_CREDIT_NEGATIVE to "Debit and credit both have to be positive",
    TextKey.ROW_DEBIT_AND_CREDIT to "The row has a debit and a credit at the same time — the direction is unclear",
    TextKey.ROW_NO_DEBIT_NO_CREDIT to "The row has neither a debit nor a credit — it has no financial effect",
    TextKey.CSV_TOO_LARGE to "The file is larger than the limit (12 MB)",
    TextKey.CSV_TOO_MANY_ROWS to "The file has more than {0} rows",
    TextKey.CSV_CELL_TOO_LONG to "A cell on line {0} is longer than the limit",
    TextKey.CSV_UNCLOSED_QUOTE to "A quote was opened and never closed — the file is cut short or damaged at line {0}",
    TextKey.CSV_EMPTY to "The file is empty",
    TextKey.PERIOD_BAD_MONTH to "Invalid month: {0}",
    TextKey.PERIOD_BAD_DATE_FORMAT to "Invalid date format: {0}",
    TextKey.PERIOD_BAD_MONTH_IN to "Invalid month in: {0}",
    TextKey.PERIOD_BAD_DAY to "That day does not exist: {0} (month {1} has {2} days)",
    TextKey.PERIOD_BAD_PAYDAY to "Payday has to be between 1 and 31, not {0}",
    TextKey.PROJECT_NAME_LENGTH to "Enter a project name, {0} characters at most.",
    TextKey.PROJECT_NAME_DUPLICATE to "A project with the same name already exists.",
    TextKey.PROJECT_RULE_TEXT_LENGTH to "Enter rule text between two and {0} characters.",
    TextKey.PROJECT_RULE_DIRECTION to "The direction is not known.",
    TextKey.PROFILE_NAME_TOO_LONG to "The name is longer than {0} characters",
    TextKey.PROFILE_SALARY_INVALID to "The salary has to be a whole amount that is not negative",
    TextKey.PROFILE_PAYDAY_RANGE to "Payday has to be from 1 to 31",
    TextKey.PROFILE_GENDER to "Choose male or female, or leave it empty",
    TextKey.PROFILE_DEPENDENTS to "Choose spouse, children or parents, or leave it empty",
    TextKey.RECURRING_DETECTED to "3 cycles in a row for a service that fits, with a close amount (±5%) and a close date (±7 days).",
    TextKey.RECURRING_NAME to "Enter the service name, 120 characters at most.",
    TextKey.RECURRING_CYCLE to "Choose monthly, every 3 months, or yearly.",
    TextKey.RECURRING_KIND to "The commitment type is not valid.",
    TextKey.RECURRING_AMOUNT to "The cycle amount has to be greater than zero.",
    TextKey.RECURRING_LINK to "The service link is not valid.",
    TextKey.CATEGORY_NOT_FOUND to "The category does not exist.",
    TextKey.CATEGORY_NAME_LENGTH to "Enter a category name, 80 characters at most.",
    TextKey.CATEGORY_NAME_DUPLICATE to "A category with the same name already exists.",
    TextKey.CATEGORY_ICON_REQUIRED to "Pick an icon from the list.",
    TextKey.CATEGORY_SELF_PARENT to "A category cannot sit under itself.",
    TextKey.CATEGORY_PARENT_MISSING to "The main category you picked does not exist.",
    TextKey.CATEGORY_PARENT_NOT_MAIN to "Pick a main category, not a sub one.",
    TextKey.CATEGORY_HAS_SUBS to "This category has sub categories, so it cannot move under another one.",
    TextKey.CATEGORY_GROUP_UNKNOWN to "The group you picked is not known.",
    TextKey.CATEGORY_COLOR_REQUIRED to "Pick a color from the list.",
    TextKey.GROUP_UNGROUPED to "Categories",
    TextKey.GROUP_NO_GROUP to "No group",
    TextKey.GROUP_HIDDEN to "Hidden",
    TextKey.SETTLEMENT_OBLIGATION_MISSING to "This obligation does not exist for this person",
    TextKey.SETTLEMENT_AMOUNT_HALALAS to "The settlement amount has to be a whole number in the smallest currency unit and greater than zero",
    TextKey.SETTLEMENT_REQUEST_CONFLICT to "This request was already saved with different details. Check the settlement that is recorded",
    TextKey.SETTLEMENT_REJECTED to "The settlement was rejected",
)
