package app.masroufy.core

/**
 * نصوص شاشة «الزكاة» (`Zakat`) ولوحة الوقائع (`ZakatFactsSheet`) — جزء من نصوص منطقة الاستثمار. القواعد ومصادرها والسطور من
 * `TextsZakat.kt` (حالة الاستخدام)؛ هنا كلام الشاشة بس.
 */
internal val MSA_INVEST_ZAKAT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ZAKAT_SCREEN_TITLE to "الزكاة",
    TextKey.ZAKAT_SCREEN_HIDDEN_TITLE to "الزكاة مخفية",
    TextKey.ZAKAT_SCREEN_HIDDEN_BODY to "«المحتوى الإسلامي» مخفي في إعداداتك، فلا تظهر الزكاة ولا تنبيهاتها ولا مدخلها في «الاستثمار».",
    TextKey.ZAKAT_SCREEN_HIDDEN_ACTION to "افتح الإعدادات",
    TextKey.ZAKAT_SCREEN_REF to "المرجع: {0}",
    TextKey.ZAKAT_SCREEN_REF_BODY to "يُطبَّق مرجع البلد إلزاميًا، ومصدره بجانب كل سطر — تُدخل أنت الوقائع فقط لا الآراء. إرشادي، وليس فتوى.",
    TextKey.ZAKAT_SCREEN_HERO to "زكاة هذه السنة",
    TextKey.ZAKAT_SCREEN_DUE to "واجبة",
    TextKey.ZAKAT_SCREEN_BELOW to "دون النصاب",
    TextKey.ZAKAT_SCREEN_PARTIAL to "تنقصها واقعة",
    TextKey.ZAKAT_SCREEN_RESTARTED to "بدأ الحول من جديد",
    TextKey.ZAKAT_SCREEN_SUB_DUE to "على {0} تجب فيها الزكاة",
    TextKey.ZAKAT_SCREEN_SUB_BELOW to "ما تجب فيه الزكاة {0} — دون النصاب، لا زكاة مستحقة.",
    TextKey.ZAKAT_SCREEN_SUB_PARTIAL to "المعروف حتى الآن {0} تجب فيها الزكاة — تنقص واقعة، فالإجمالي غير متاح.",
    TextKey.ZAKAT_SCREEN_SUB_NA to "تنقص واقعة أو سعر، ودونها لا يُعرف بلوغ النصاب.",
    TextKey.ZAKAT_SCREEN_SUB_RESTARTED to "نزلت أموالك تحت النصاب خلال السنة، فبدأ الحول من جديد.",
    TextKey.ZAKAT_SCREEN_SUB_NO_NISAB to "سعر الذهب أو الفضة اليوم غير متاح، فالنصاب غير معروف.",
    TextKey.ZAKAT_SCREEN_NISAB to "النصاب",
    TextKey.ZAKAT_SCREEN_PRICE_GOLD to "الذهب الخالص {0} للجرام",
    TextKey.ZAKAT_SCREEN_PRICE_SILVER to "الفضة {0} للجرام",
    TextKey.ZAKAT_SCREEN_PRICE_DATE to "بتاريخ {0}",
    TextKey.ZAKAT_SCREEN_HAWL to "يوم زكاتك",
    TextKey.ZAKAT_SCREEN_SUGGESTED to "مقترح",
    TextKey.ZAKAT_SCREEN_CONFIRMED to "مؤكَّد",
    TextKey.ZAKAT_SCREEN_HAWL_DATE to "{0} — {1}",
    TextKey.ZAKAT_SCREEN_REL_TODAY to "اليوم",
    TextKey.ZAKAT_SCREEN_REL_TOMORROW to "غدًا",
    TextKey.ZAKAT_SCREEN_REL_TWO to "بعد يومين",
    TextKey.ZAKAT_SCREEN_REL_FEW to "بعد {0} أيام",
    TextKey.ZAKAT_SCREEN_REL_MANY to "بعد {0} يومًا",
    TextKey.ZAKAT_SCREEN_REL_PAST to "مضى موعدها",
    TextKey.ZAKAT_SCREEN_HAWL_WHY_SUGGESTED to "اقترحناه من سلسلة رصيدك: بداية آخر فترة بقيت فيها أموالك فوق النصاب دون انقطاع.",
    TextKey.ZAKAT_SCREEN_HAWL_WHY_CONFIRMED to "أكّدته أنت — يوم ثابت كل سنة هجرية.",
    TextKey.ZAKAT_SCREEN_HAWL_NA to "لا يمكن اقتراح يوم الآن: النصاب غير معروف، أو أموالك دونه اليوم.",
    TextKey.ZAKAT_SCREEN_RULE_SRC to "{0} — {1}",
    TextKey.ZAKAT_SCREEN_CONFIRM to "أكّده",
    TextKey.ZAKAT_SCREEN_CONFIRMED_TOAST to "تأكّد يوم زكاتك — ننبهك قبله بـ١٠ أيام",
    TextKey.ZAKAT_SCREEN_FACTS to "الوقائع — ليست آراء",
    TextKey.ZAKAT_SCREEN_FACTS_SUB to "للبس أم للادخار، مضاربة أم طويل الأجل، الدين يُرجى أم مشكوك",
    TextKey.ZAKAT_SCREEN_FACTS_MISSING to "ينقص {0}",
    TextKey.ZAKAT_SCREEN_FACTS_DONE to "{0} مُجابة",
    TextKey.ZAKAT_SCREEN_FACTS_NONE to "لا أسئلة",
    TextKey.ZAKAT_SCREEN_LINES to "تجب فيه الزكاة",
    TextKey.ZAKAT_SCREEN_AMOUNT_RULE to "{0}، {1}",
    TextKey.ZAKAT_SCREEN_LINES_EMPTY to "لا شيء تجب فيه الزكاة الآن.",
    TextKey.ZAKAT_SCREEN_MISSING_PURPOSE to "تنقصه واقعة: هل هو للبس أم للادخار؟",
    TextKey.ZAKAT_SCREEN_MISSING_HOLDING to "تنقصه واقعة: مضاربة أم طويل الأجل؟",
    TextKey.ZAKAT_SCREEN_MISSING_SAUDI to "تنقصه واقعة: هل الشركة سعودية؟",
    TextKey.ZAKAT_SCREEN_MISSING_COLLECT to "تنقصه واقعة: هل يُرجى سداده؟",
    TextKey.ZAKAT_SCREEN_MISSING_KARAT to "ينقصه العيار.",
    TextKey.ZAKAT_SCREEN_MISSING_FINENESS to "تنقصه نقاوة الفضة.",
    TextKey.ZAKAT_SCREEN_MISSING_PRICE to "سعره اليوم غير متاح.",
    TextKey.ZAKAT_SCREEN_OUT to "خارج الحساب",
    TextKey.ZAKAT_SCREEN_CLOSE to "ثبّت حساب هذه السنة",
    TextKey.ZAKAT_SCREEN_CLOSE_NOTE to "التثبيت يحفظ السطور والنصاب فلا يغيّر سعر الغد زكاة اليوم. يجوز قبل الموعد.",
    TextKey.ZAKAT_SCREEN_CLOSED_TOAST to "ثُبّت حساب السنة — سجّل الدفع أدناه",
    TextKey.ZAKAT_SCREEN_NO_YEAR to "أكّد يوم زكاتك أولًا لتظهر سطور السنة.",
    TextKey.ZAKAT_FACTS_INTRO to "اختر ما هو واقع فعلًا، وتُطبَّق القاعدة على الواقعة وحدها وفق مرجع البلد.",
    TextKey.ZAKAT_FACTS_ASK_PURPOSE to "هل هو للبس أم للادخار؟",
    TextKey.ZAKAT_FACTS_WEAR to "للبس",
    TextKey.ZAKAT_FACTS_SAVING to "للادخار",
    TextKey.ZAKAT_FACTS_ASK_HOLDING to "مضاربة أم طويل الأجل؟",
    TextKey.ZAKAT_FACTS_TRADING to "مضاربة",
    TextKey.ZAKAT_FACTS_LONG to "طويل الأجل",
    TextKey.ZAKAT_FACTS_ASK_SAUDI to "هل الشركة سعودية؟",
    TextKey.ZAKAT_FACTS_YES to "نعم",
    TextKey.ZAKAT_FACTS_NO to "لا",
    TextKey.ZAKAT_FACTS_ASK_COLLECT to "هل يُرجى سداده؟",
    TextKey.ZAKAT_FACTS_STRONG to "يُرجى سداده",
    TextKey.ZAKAT_FACTS_DOUBT to "مشكوك فيه",
    TextKey.ZAKAT_FACTS_DEBT_ON to "دين على {0}، {1}",
    TextKey.ZAKAT_FACTS_ASK_KARAT to "كم عياره؟",
    TextKey.ZAKAT_FACTS_KARAT to "عيار {0}",
    TextKey.ZAKAT_FACTS_ASK_FINENESS to "كم نقاوتها في الألف؟",
    TextKey.ZAKAT_FACTS_FINENESS to "{0} من ألف",
    TextKey.ZAKAT_FACTS_DONE to "تم",
    TextKey.ZAKAT_FACTS_EMPTY to "لا وقائع مطلوبة الآن.",
    TextKey.ZAKAT_FACTS_METAL_TITLE to "{0} ({1} جرام)",
)

internal val EGYPTIAN_INVEST_ZAKAT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ZAKAT_SCREEN_TITLE to "الزكاة",
    TextKey.ZAKAT_SCREEN_HIDDEN_TITLE to "الزكاة مستخبية",
    TextKey.ZAKAT_SCREEN_HIDDEN_BODY to "«المحتوى الإسلامي» مقفول في إعداداتك، فالزكاة وتنبيهاتها ومدخلها في «الاستثمار» مش بيظهروا.",
    TextKey.ZAKAT_SCREEN_HIDDEN_ACTION to "افتح الإعدادات",
    TextKey.ZAKAT_SCREEN_REF to "المرجع: {0}",
    TextKey.ZAKAT_SCREEN_REF_BODY to "بنمشي على مرجع البلد إجباري، ومكتوب مصدره جنب كل سطر — إنت بتدخل وقائع بس، مش آراء. إرشادي، مش فتوى.",
    TextKey.ZAKAT_SCREEN_HERO to "زكاة السنة دي",
    TextKey.ZAKAT_SCREEN_DUE to "واجبة",
    TextKey.ZAKAT_SCREEN_BELOW to "تحت النصاب",
    TextKey.ZAKAT_SCREEN_PARTIAL to "ناقصة واقعة",
    TextKey.ZAKAT_SCREEN_RESTARTED to "الحول بدأ من جديد",
    TextKey.ZAKAT_SCREEN_SUB_DUE to "على {0} عليها زكاة",
    TextKey.ZAKAT_SCREEN_SUB_BELOW to "اللي عليه زكاة {0} — تحت النصاب، مفيش زكاة مطلوبة.",
    TextKey.ZAKAT_SCREEN_SUB_PARTIAL to "المعروف لحد دلوقتي {0} عليها زكاة — فيه واقعة ناقصة، فالإجمالي غير متاح.",
    TextKey.ZAKAT_SCREEN_SUB_NA to "فيه واقعة أو سعر ناقص، ومن غيرهم مش معروف إذا كانت فوق النصاب.",
    TextKey.ZAKAT_SCREEN_SUB_RESTARTED to "فلوسك نزلت تحت النصاب جوه السنة، فالحول بدأ من جديد.",
    TextKey.ZAKAT_SCREEN_SUB_NO_NISAB to "سعر الدهب أو الفضة النهارده غير متاح، فالنصاب مش معروف.",
    TextKey.ZAKAT_SCREEN_NISAB to "النصاب",
    TextKey.ZAKAT_SCREEN_PRICE_GOLD to "الدهب الصافي {0} للجرام",
    TextKey.ZAKAT_SCREEN_PRICE_SILVER to "الفضة {0} للجرام",
    TextKey.ZAKAT_SCREEN_PRICE_DATE to "بتاريخ {0}",
    TextKey.ZAKAT_SCREEN_HAWL to "يوم زكاتك",
    TextKey.ZAKAT_SCREEN_SUGGESTED to "مقترح",
    TextKey.ZAKAT_SCREEN_CONFIRMED to "متأكد",
    TextKey.ZAKAT_SCREEN_HAWL_DATE to "{0} — {1}",
    TextKey.ZAKAT_SCREEN_REL_TODAY to "النهارده",
    TextKey.ZAKAT_SCREEN_REL_TOMORROW to "بكرة",
    TextKey.ZAKAT_SCREEN_REL_TWO to "كمان يومين",
    TextKey.ZAKAT_SCREEN_REL_FEW to "كمان {0} أيام",
    TextKey.ZAKAT_SCREEN_REL_MANY to "كمان {0} يوم",
    TextKey.ZAKAT_SCREEN_REL_PAST to "ميعادها عدّى",
    TextKey.ZAKAT_SCREEN_HAWL_WHY_SUGGESTED to "اقترحناه من سلسلة رصيدك: أول يوم فلوسك وصلت فيه للنصاب. العبرة بأول السنة وآخرها.",
    TextKey.ZAKAT_SCREEN_HAWL_WHY_CONFIRMED to "إنت أكدته — يوم ثابت كل سنة هجرية.",
    TextKey.ZAKAT_SCREEN_HAWL_NA to "مش ممكن نقترح يوم دلوقتي: النصاب مش معروف، أو فلوسك تحته النهارده.",
    TextKey.ZAKAT_SCREEN_RULE_SRC to "{0} — {1}",
    TextKey.ZAKAT_SCREEN_CONFIRM to "أكّده",
    TextKey.ZAKAT_SCREEN_CONFIRMED_TOAST to "اتأكد يوم زكاتك — هننبهك قبله بـ١٠ أيام",
    TextKey.ZAKAT_SCREEN_FACTS to "الوقائع — مش آراء",
    TextKey.ZAKAT_SCREEN_FACTS_SUB to "لبس ولا ادخار، مضاربة ولا طويل الأجل",
    TextKey.ZAKAT_SCREEN_FACTS_MISSING to "ناقصة {0}",
    TextKey.ZAKAT_SCREEN_FACTS_DONE to "{0} متجاوبة",
    TextKey.ZAKAT_SCREEN_FACTS_NONE to "مفيش أسئلة",
    TextKey.ZAKAT_SCREEN_LINES to "عليه زكاة",
    TextKey.ZAKAT_SCREEN_AMOUNT_RULE to "{0}، {1}",
    TextKey.ZAKAT_SCREEN_LINES_EMPTY to "مفيش حاجة عليها زكاة دلوقتي.",
    TextKey.ZAKAT_SCREEN_MISSING_PURPOSE to "ناقصة واقعة: القطعة دي للبس ولا ادخار؟",
    TextKey.ZAKAT_SCREEN_MISSING_HOLDING to "ناقصة واقعة: مضاربة ولا طويل الأجل؟",
    TextKey.ZAKAT_SCREEN_MISSING_SAUDI to "ناقصة واقعة: الشركة سعودية؟",
    TextKey.ZAKAT_SCREEN_MISSING_COLLECT to "ناقصة واقعة: الفلوس دي هترجع؟",
    TextKey.ZAKAT_SCREEN_MISSING_KARAT to "ناقص العيار.",
    TextKey.ZAKAT_SCREEN_MISSING_FINENESS to "ناقصة نقاوة الفضة.",
    TextKey.ZAKAT_SCREEN_MISSING_PRICE to "سعره النهارده غير متاح.",
    TextKey.ZAKAT_SCREEN_OUT to "برّه الحساب",
    TextKey.ZAKAT_SCREEN_CLOSE to "ثبّت حساب السنة دي",
    TextKey.ZAKAT_SCREEN_CLOSE_NOTE to "التثبيت بيحفظ السطور والنصاب عشان سعر بكرة ما يغيّرش زكاة النهارده. مسموح قبل الميعاد.",
    TextKey.ZAKAT_SCREEN_CLOSED_TOAST to "اتثبّت حساب السنة — سجّل الدفع تحت",
    TextKey.ZAKAT_SCREEN_NO_YEAR to "أكّد يوم زكاتك الأول عشان سطور السنة تظهر.",
    TextKey.ZAKAT_FACTS_INTRO to "اختار اللي حصل فعلًا، والقاعدة بتتطبق على الواقعة لوحدها حسب مرجع البلد.",
    TextKey.ZAKAT_FACTS_ASK_PURPOSE to "القطعة دي للبس ولا ادخار؟",
    TextKey.ZAKAT_FACTS_WEAR to "للبس",
    TextKey.ZAKAT_FACTS_SAVING to "ادخار",
    TextKey.ZAKAT_FACTS_ASK_HOLDING to "مضاربة ولا طويل الأجل؟",
    TextKey.ZAKAT_FACTS_TRADING to "مضاربة",
    TextKey.ZAKAT_FACTS_LONG to "طويل الأجل",
    TextKey.ZAKAT_FACTS_ASK_SAUDI to "الشركة سعودية؟",
    TextKey.ZAKAT_FACTS_YES to "أيوه",
    TextKey.ZAKAT_FACTS_NO to "لأ",
    TextKey.ZAKAT_FACTS_ASK_COLLECT to "الفلوس دي هترجع؟",
    TextKey.ZAKAT_FACTS_STRONG to "هترجع",
    TextKey.ZAKAT_FACTS_DOUBT to "مشكوك فيها",
    TextKey.ZAKAT_FACTS_DEBT_ON to "دين على {0}، {1}",
    TextKey.ZAKAT_FACTS_ASK_KARAT to "عياره كام؟",
    TextKey.ZAKAT_FACTS_KARAT to "عيار {0}",
    TextKey.ZAKAT_FACTS_ASK_FINENESS to "نقاوتها كام في الألف؟",
    TextKey.ZAKAT_FACTS_FINENESS to "{0} من ألف",
    TextKey.ZAKAT_FACTS_DONE to "تمام",
    TextKey.ZAKAT_FACTS_EMPTY to "مفيش وقائع مطلوبة دلوقتي.",
    TextKey.ZAKAT_FACTS_METAL_TITLE to "{0} ({1} جرام)",
)

internal val ENGLISH_INVEST_ZAKAT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ZAKAT_SCREEN_TITLE to "Zakat",
    TextKey.ZAKAT_SCREEN_HIDDEN_TITLE to "Zakat is hidden",
    TextKey.ZAKAT_SCREEN_HIDDEN_BODY to "“Islamic content” is hidden in your settings, so zakat, its alerts and its entry in “Investment” don't show.",
    TextKey.ZAKAT_SCREEN_HIDDEN_ACTION to "Open settings",
    TextKey.ZAKAT_SCREEN_REF to "Reference: {0}",
    TextKey.ZAKAT_SCREEN_REF_BODY to "The country's reference is applied as is, with its source next to every line — you enter facts only, not opinions. For guidance, not a fatwa.",
    TextKey.ZAKAT_SCREEN_HERO to "This year's zakat",
    TextKey.ZAKAT_SCREEN_DUE to "Due",
    TextKey.ZAKAT_SCREEN_BELOW to "Below nisab",
    TextKey.ZAKAT_SCREEN_PARTIAL to "A fact is missing",
    TextKey.ZAKAT_SCREEN_RESTARTED to "The year started again",
    TextKey.ZAKAT_SCREEN_SUB_DUE to "On {0} subject to zakat",
    TextKey.ZAKAT_SCREEN_SUB_BELOW to "Subject to zakat: {0} — below the nisab, no zakat is due.",
    TextKey.ZAKAT_SCREEN_SUB_PARTIAL to "Known so far: {0} subject to zakat — a fact is missing, so the total isn't available.",
    TextKey.ZAKAT_SCREEN_SUB_NA to "A fact or a price is missing, and without it we can't tell whether you reached the nisab.",
    TextKey.ZAKAT_SCREEN_SUB_RESTARTED to "Your wealth dropped below the nisab during the year, so the year started again.",
    TextKey.ZAKAT_SCREEN_SUB_NO_NISAB to "Today's gold or silver price isn't available, so the nisab is unknown.",
    TextKey.ZAKAT_SCREEN_NISAB to "Nisab",
    TextKey.ZAKAT_SCREEN_PRICE_GOLD to "Pure gold {0} per gram",
    TextKey.ZAKAT_SCREEN_PRICE_SILVER to "Silver {0} per gram",
    TextKey.ZAKAT_SCREEN_PRICE_DATE to "as of {0}",
    TextKey.ZAKAT_SCREEN_HAWL to "Your zakat day",
    TextKey.ZAKAT_SCREEN_SUGGESTED to "Suggested",
    TextKey.ZAKAT_SCREEN_CONFIRMED to "Confirmed",
    TextKey.ZAKAT_SCREEN_HAWL_DATE to "{0} — {1}",
    TextKey.ZAKAT_SCREEN_REL_TODAY to "today",
    TextKey.ZAKAT_SCREEN_REL_TOMORROW to "tomorrow",
    TextKey.ZAKAT_SCREEN_REL_TWO to "in two days",
    TextKey.ZAKAT_SCREEN_REL_FEW to "in {0} days",
    TextKey.ZAKAT_SCREEN_REL_MANY to "in {0} days",
    TextKey.ZAKAT_SCREEN_REL_PAST to "its date has passed",
    TextKey.ZAKAT_SCREEN_HAWL_WHY_SUGGESTED to "Suggested from your balance history: the start of the latest unbroken stretch above the nisab.",
    TextKey.ZAKAT_SCREEN_HAWL_WHY_CONFIRMED to "You confirmed it — a fixed day every Hijri year.",
    TextKey.ZAKAT_SCREEN_HAWL_NA to "No day can be suggested now: the nisab is unknown, or you are below it today.",
    TextKey.ZAKAT_SCREEN_RULE_SRC to "{0} — {1}",
    TextKey.ZAKAT_SCREEN_CONFIRM to "Confirm it",
    TextKey.ZAKAT_SCREEN_CONFIRMED_TOAST to "Your zakat day is confirmed — we'll remind you 10 days before",
    TextKey.ZAKAT_SCREEN_FACTS to "The facts — not opinions",
    TextKey.ZAKAT_SCREEN_FACTS_SUB to "Worn or saved, trading or long term, will the debt be repaid",
    TextKey.ZAKAT_SCREEN_FACTS_MISSING to "{0} missing",
    TextKey.ZAKAT_SCREEN_FACTS_DONE to "{0} answered",
    TextKey.ZAKAT_SCREEN_FACTS_NONE to "No questions",
    TextKey.ZAKAT_SCREEN_LINES to "Subject to zakat",
    TextKey.ZAKAT_SCREEN_AMOUNT_RULE to "{0}, {1}",
    TextKey.ZAKAT_SCREEN_LINES_EMPTY to "Nothing is subject to zakat right now.",
    TextKey.ZAKAT_SCREEN_MISSING_PURPOSE to "A fact is missing: worn or kept as savings?",
    TextKey.ZAKAT_SCREEN_MISSING_HOLDING to "A fact is missing: trading or long term?",
    TextKey.ZAKAT_SCREEN_MISSING_SAUDI to "A fact is missing: is the company Saudi?",
    TextKey.ZAKAT_SCREEN_MISSING_COLLECT to "A fact is missing: will it be repaid?",
    TextKey.ZAKAT_SCREEN_MISSING_KARAT to "The karat is missing.",
    TextKey.ZAKAT_SCREEN_MISSING_FINENESS to "The silver's fineness is missing.",
    TextKey.ZAKAT_SCREEN_MISSING_PRICE to "Its price today isn't available.",
    TextKey.ZAKAT_SCREEN_OUT to "Outside the calculation",
    TextKey.ZAKAT_SCREEN_CLOSE to "Lock this year's calculation",
    TextKey.ZAKAT_SCREEN_CLOSE_NOTE to "Locking keeps the lines and the nisab, so tomorrow's price doesn't change today's zakat. Allowed before the date.",
    TextKey.ZAKAT_SCREEN_CLOSED_TOAST to "This year's calculation is locked — record the payment below",
    TextKey.ZAKAT_SCREEN_NO_YEAR to "Confirm your zakat day first to see this year's lines.",
    TextKey.ZAKAT_FACTS_INTRO to "Pick what is actually the case; the rule applies to each fact on its own, per the country's reference.",
    TextKey.ZAKAT_FACTS_ASK_PURPOSE to "Worn or kept as savings?",
    TextKey.ZAKAT_FACTS_WEAR to "Worn",
    TextKey.ZAKAT_FACTS_SAVING to "Savings",
    TextKey.ZAKAT_FACTS_ASK_HOLDING to "Trading or long term?",
    TextKey.ZAKAT_FACTS_TRADING to "Trading",
    TextKey.ZAKAT_FACTS_LONG to "Long term",
    TextKey.ZAKAT_FACTS_ASK_SAUDI to "Is the company Saudi?",
    TextKey.ZAKAT_FACTS_YES to "Yes",
    TextKey.ZAKAT_FACTS_NO to "No",
    TextKey.ZAKAT_FACTS_ASK_COLLECT to "Will it be repaid?",
    TextKey.ZAKAT_FACTS_STRONG to "Will be repaid",
    TextKey.ZAKAT_FACTS_DOUBT to "Doubtful",
    TextKey.ZAKAT_FACTS_DEBT_ON to "Owed by {0}, {1}",
    TextKey.ZAKAT_FACTS_ASK_KARAT to "What karat is it?",
    TextKey.ZAKAT_FACTS_KARAT to "{0} karat",
    TextKey.ZAKAT_FACTS_ASK_FINENESS to "What is its fineness per thousand?",
    TextKey.ZAKAT_FACTS_FINENESS to "{0} per thousand",
    TextKey.ZAKAT_FACTS_DONE to "Done",
    TextKey.ZAKAT_FACTS_EMPTY to "No facts are needed right now.",
    TextKey.ZAKAT_FACTS_METAL_TITLE to "{0} ({1} g)",
)
