package app.masroufy.core

/**
 * نصوص الحاسبات (`ui/screens/investment/calc/`) — المشترك (`CALCUI_*`) + «حاسبة الادخار» (`SavingsCalculator`) + «لو وضعتها في…»
 * (`SavingsGrowth`). النص من النموذج التفاعلي بالحرف (الفصحى من `space = السعودية` والمصري من `مصر`)؛ الإنجليزي كتابة Claude (مستني
 * مراجعة المالك §40). **ممنوع «·» جنب رقم عربي** ⇒ «،». مضمومة في `TextsAreaCalc.kt`.
 */
internal val MSA_CALC_SAVINGS_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.CALCUI_MONTHS_ONE to "شهر واحد",
    UiKey.CALCUI_MONTHS_TWO to "شهران",
    UiKey.CALCUI_MONTHS_FEW to "{0} أشهر",
    UiKey.CALCUI_MONTHS_MANY to "{0} شهرًا",
    UiKey.CALCUI_YEARS_ONE to "سنة",
    UiKey.CALCUI_YEARS_TWO to "سنتان",
    UiKey.CALCUI_YEARS_FEW to "{0} سنوات",
    UiKey.CALCUI_YEARS_MANY to "{0} سنة",
    UiKey.CALCUI_DAY_MONTH_YEAR to "{0} {1}",
    UiKey.CALCUI_AGE to "{0} سنة",
    UiKey.CALCUI_AGE_MONTHS to "{0} سنة و{1}",
    UiKey.CALCUI_MONTHS_UNIT to "شهرًا",
    UiKey.CALCUI_YEARS_UNIT to "سنة",
    UiKey.CALCUI_PICK_DATE to "اختر التاريخ",
    UiKey.CALCUI_PREV_YEAR to "السنة السابقة",
    UiKey.CALCUI_NEXT_YEAR to "السنة التالية",
    UiKey.CALCUI_YES to "نعم",
    UiKey.CALCUI_NO to "لا",
    UiKey.CALCUI_PERCENT_SIGN to "%",
    UiKey.CALCUI_WHOLE_NUMBER to "اكتب عددًا صحيحًا",
    UiKey.SAVCALC_TITLE to "حاسبة الادخار",
    UiKey.SAVCALC_MODE_TARGET to "أصل إلى مبلغ بتاريخ",
    UiKey.SAVCALC_MODE_MONTHLY to "أدّخر مبلغًا كل شهر لمدة",
    UiKey.SAVCALC_TARGET_LABEL to "كم تريد أن تجمع؟",
    UiKey.SAVCALC_DATE_LABEL to "بحلول أي تاريخ؟",
    UiKey.SAVCALC_HAVE_LABEL to "كم معك الآن؟",
    UiKey.SAVCALC_HAVE_NOTE to "فارغ = صفر",
    UiKey.SAVCALC_MONTHLY_LABEL to "كم تدّخر شهريًا؟",
    UiKey.SAVCALC_MONTHS_LABEL to "لمدة كم شهرًا؟",
    UiKey.SAVCALC_HERO_TARGET to "تحتاج أن تدّخر شهريًا",
    UiKey.SAVCALC_HERO_REACH to "ستصل إلى",
    UiKey.SAVCALC_FILL to "أكمل البيانات",
    UiKey.SAVCALC_FILL_SUB to "تظهر النتيجة حين تصح الخانات.",
    UiKey.SAVCALC_SUB_TARGET to "لمدة {0} حتى {1}، المتبقي {2}، دون أرباح",
    UiKey.SAVCALC_SUB_HAVE_ALL to "معك المبلغ كاملًا.",
    UiKey.SAVCALC_SUB_REACH to "في {0}، {1} × {2} + ما معك، دون أرباح",
    UiKey.SAVCALC_COMPARE_TITLE to "مقارنة بما تدّخره فعلًا",
    UiKey.SAVCALC_VERDICT_UNKNOWN to "غير معروف",
    UiKey.SAVCALC_VERDICT_ENOUGH to "كافٍ",
    UiKey.SAVCALC_VERDICT_SHORT to "ينقصك {0}",
    UiKey.SAVCALC_MONTH_UNKNOWN to "غير معروف",
    UiKey.SAVCALC_COMPARE_LINE to "متوسط ادخارك: {0} شهريًا، المطلوب {1}",
    UiKey.SAVCALC_COMPARE_EXTRA to " — يزيد {0}",
    UiKey.SAVCALC_COMPARE_NOTE to "آخر 3 أشهر مالية مكتملة (تبدأ يوم {0}): الدخل الحقيقي ناقص المصروف الحقيقي. التحويل بين محافظك والسلف وشراء الأصول خارج الحساب.",
    UiKey.SAVCALC_COMPARE_NOTE_PLAIN to "آخر 3 أشهر مالية مكتملة: الدخل الحقيقي ناقص المصروف الحقيقي. التحويل بين محافظك والسلف وشراء الأصول خارج الحساب.",
    UiKey.SAVCALC_REVIEW to "حدّد نوع هذه العمليات",
    UiKey.SAVCALC_GOAL to "حوّلها لخطة ادخار",
    UiKey.SAVCALC_GOAL_DONE to "أُنشئت الخطة ✓",
    UiKey.SAVCALC_GOAL_NOTE to "بالمبلغ والتاريخ نفسيهما، وما معك يُسجَّل أول إيداع فيها اليوم.",
    UiKey.SAVCALC_GOAL_TOAST to "أُنشئت خطة «{0}»، {1} شهريًا حتى {2}",
    UiKey.SAVCALC_GOAL_FAILED to "تعذّر إنشاء الخطة",
    UiKey.SAVGROW_TITLE to "لو وضعتها في…",
    UiKey.SAVGROW_PAID to "من جيبك: {0} خلال {1}",
    UiKey.SAVGROW_TODAY to "بقيمة المال اليوم",
    UiKey.SAVGROW_TODAY_SUB to "نخصم التضخم الرسمي {0} سنويًا",
    UiKey.SAVGROW_RATE_YEARLY to "{0} سنويًا",
    UiKey.SAVGROW_INFO to "{0}: {1} — معلومة فقط",
    UiKey.SAVGROW_CASH_FIXED to "ثابت: صفر",
    UiKey.SAVGROW_TYPE_RATE to "اكتب النسبة",
    UiKey.SAVGROW_EDIT_RATE to "عدّل النسبة",
    UiKey.SAVGROW_RESET to "ارجع للمتوسط",
    UiKey.SAVGROW_FOOT to "الذهب والعقار والأسهم بمتوسط زيادة سنوية مركّبة، والوديعة بفائدة البنك كل شهر. هذا متوسط ما مضى، وليس وعدًا بما سيأتي.",
    UiKey.SAVGROW_SHEET_TITLE to "نسبة الزيادة السنوية — {0}",
    UiKey.SAVGROW_SHEET_BODY to "اكتب النسبة السنوية التي تتوقعها. ما تكتبه يغلب المتوسط.",
    UiKey.SAVGROW_SHEET_BODY_DEPOSIT to "اكتب فائدة بنكك على الوديعة.",
    UiKey.SAVGROW_SAVE to "احسب بها",
)

internal val EGYPTIAN_CALC_SAVINGS_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.CALCUI_MONTHS_ONE to "شهر واحد",
    UiKey.CALCUI_MONTHS_TWO to "شهرين",
    UiKey.CALCUI_MONTHS_FEW to "{0} شهور",
    UiKey.CALCUI_MONTHS_MANY to "{0} شهر",
    UiKey.CALCUI_YEARS_ONE to "سنة",
    UiKey.CALCUI_YEARS_TWO to "سنتين",
    UiKey.CALCUI_YEARS_FEW to "{0} سنين",
    UiKey.CALCUI_YEARS_MANY to "{0} سنة",
    UiKey.CALCUI_DAY_MONTH_YEAR to "{0} {1}",
    UiKey.CALCUI_AGE to "{0} سنة",
    UiKey.CALCUI_AGE_MONTHS to "{0} سنة و{1}",
    UiKey.CALCUI_MONTHS_UNIT to "شهر",
    UiKey.CALCUI_YEARS_UNIT to "سنة",
    UiKey.CALCUI_PICK_DATE to "اختار التاريخ",
    UiKey.CALCUI_PREV_YEAR to "السنة اللي فاتت",
    UiKey.CALCUI_NEXT_YEAR to "السنة الجاية",
    UiKey.CALCUI_YES to "أيوه",
    UiKey.CALCUI_NO to "لأ",
    UiKey.CALCUI_PERCENT_SIGN to "%",
    UiKey.CALCUI_WHOLE_NUMBER to "اكتب رقم صحيح",
    UiKey.SAVCALC_TITLE to "حاسبة التحويش",
    UiKey.SAVCALC_MODE_TARGET to "عايز أوصل لمبلغ بتاريخ",
    UiKey.SAVCALC_MODE_MONTHLY to "بحوّش كام في الشهر لمدة",
    UiKey.SAVCALC_TARGET_LABEL to "عايز توصل لكام؟",
    UiKey.SAVCALC_DATE_LABEL to "لحد إمتى؟",
    UiKey.SAVCALC_HAVE_LABEL to "معاك كام دلوقتي؟",
    UiKey.SAVCALC_HAVE_NOTE to "فاضي = صفر",
    UiKey.SAVCALC_MONTHLY_LABEL to "بتحوّش كام في الشهر؟",
    UiKey.SAVCALC_MONTHS_LABEL to "لمدة كام شهر؟",
    UiKey.SAVCALC_HERO_TARGET to "محتاج تحوّش في الشهر",
    UiKey.SAVCALC_HERO_REACH to "هتوصل لـ",
    UiKey.SAVCALC_FILL to "كمّل البيانات",
    UiKey.SAVCALC_FILL_SUB to "الحساب بيظهر أول ما الخانات تبقى صح.",
    UiKey.SAVCALC_SUB_TARGET to "لمدة {0} لحد {1}، فاضلك {2}، من غير أرباح",
    UiKey.SAVCALC_SUB_HAVE_ALL to "معاك المبلغ كله خلاص.",
    UiKey.SAVCALC_SUB_REACH to "يوم {0}، {1} × {2} + اللي معاك، من غير أرباح",
    UiKey.SAVCALC_COMPARE_TITLE to "قدام اللي بتحوّشه فعلًا",
    UiKey.SAVCALC_VERDICT_UNKNOWN to "مش معروف",
    UiKey.SAVCALC_VERDICT_ENOUGH to "كفاية",
    UiKey.SAVCALC_VERDICT_SHORT to "ناقصك {0}",
    UiKey.SAVCALC_MONTH_UNKNOWN to "مش معروف",
    UiKey.SAVCALC_COMPARE_LINE to "متوسط تحويشك: {0} في الشهر، المطلوب {1}",
    UiKey.SAVCALC_COMPARE_EXTRA to " — زيادة {0}",
    UiKey.SAVCALC_COMPARE_NOTE to "آخر 3 شهور مالية خلصت (بتبدأ يوم {0}): الدخل الحقيقي ناقص المصروف الحقيقي. التحويل بين محافظك والسلف وشراء الأصول برّه الحسبة.",
    UiKey.SAVCALC_COMPARE_NOTE_PLAIN to "آخر 3 شهور مالية خلصت: الدخل الحقيقي ناقص المصروف الحقيقي. التحويل بين محافظك والسلف وشراء الأصول برّه الحسبة.",
    UiKey.SAVCALC_REVIEW to "حدّد نوع العمليات دي",
    UiKey.SAVCALC_GOAL to "حوّلها لخطة تحويش",
    UiKey.SAVCALC_GOAL_DONE to "اتعملت الخطة ✓",
    UiKey.SAVCALC_GOAL_NOTE to "بنفس المبلغ والتاريخ، واللي معاك بيتسجّل أول إيداع فيها النهارده.",
    UiKey.SAVCALC_GOAL_TOAST to "اتعملت خطة «{0}»، {1} في الشهر لحد {2}",
    UiKey.SAVCALC_GOAL_FAILED to "الخطة ما اتعملتش",
    UiKey.SAVGROW_TITLE to "لو حطّيتها في…",
    UiKey.SAVGROW_PAID to "من جيبك: {0} على {1}",
    UiKey.SAVGROW_TODAY to "بقيمة فلوس النهارده",
    UiKey.SAVGROW_TODAY_SUB to "بنخصم التضخم الرسمي {0} في السنة",
    UiKey.SAVGROW_RATE_YEARLY to "{0} في السنة",
    UiKey.SAVGROW_INFO to "{0}: {1} — معلومة بس",
    UiKey.SAVGROW_CASH_FIXED to "ثابت: صفر",
    UiKey.SAVGROW_TYPE_RATE to "اكتب النسبة",
    UiKey.SAVGROW_EDIT_RATE to "عدّل النسبة",
    UiKey.SAVGROW_RESET to "رجّع المتوسط",
    UiKey.SAVGROW_FOOT to "الدهب والعقار والأسهم بمتوسط زيادة سنوية مركّبة، والوديعة بفايدة البنك كل شهر. ده متوسط اللي فات، مش وعد باللي جاي.",
    UiKey.SAVGROW_SHEET_TITLE to "نسبة الزيادة في السنة — {0}",
    UiKey.SAVGROW_SHEET_BODY to "اكتب النسبة اللي تتوقعها. الرقم اللي تكتبه بيغلب المتوسط.",
    UiKey.SAVGROW_SHEET_BODY_DEPOSIT to "اكتب فايدة بنكك على الوديعة.",
    UiKey.SAVGROW_SAVE to "احسب بيها",
)

internal val ENGLISH_CALC_SAVINGS_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.CALCUI_MONTHS_ONE to "1 month",
    UiKey.CALCUI_MONTHS_TWO to "2 months",
    UiKey.CALCUI_MONTHS_FEW to "{0} months",
    UiKey.CALCUI_MONTHS_MANY to "{0} months",
    UiKey.CALCUI_YEARS_ONE to "1 year",
    UiKey.CALCUI_YEARS_TWO to "2 years",
    UiKey.CALCUI_YEARS_FEW to "{0} years",
    UiKey.CALCUI_YEARS_MANY to "{0} years",
    UiKey.CALCUI_DAY_MONTH_YEAR to "{0} {1}",
    UiKey.CALCUI_AGE to "{0} years",
    UiKey.CALCUI_AGE_MONTHS to "{0} years and {1}",
    UiKey.CALCUI_MONTHS_UNIT to "months",
    UiKey.CALCUI_YEARS_UNIT to "years",
    UiKey.CALCUI_PICK_DATE to "Pick a date",
    UiKey.CALCUI_PREV_YEAR to "Previous year",
    UiKey.CALCUI_NEXT_YEAR to "Next year",
    UiKey.CALCUI_YES to "Yes",
    UiKey.CALCUI_NO to "No",
    UiKey.CALCUI_PERCENT_SIGN to "%",
    UiKey.CALCUI_WHOLE_NUMBER to "Enter a whole number",
    UiKey.SAVCALC_TITLE to "Savings calculator",
    UiKey.SAVCALC_MODE_TARGET to "Reach an amount by a date",
    UiKey.SAVCALC_MODE_MONTHLY to "Save monthly for a period",
    UiKey.SAVCALC_TARGET_LABEL to "How much do you want to reach?",
    UiKey.SAVCALC_DATE_LABEL to "By what date?",
    UiKey.SAVCALC_HAVE_LABEL to "How much do you have now?",
    UiKey.SAVCALC_HAVE_NOTE to "Empty = zero",
    UiKey.SAVCALC_MONTHLY_LABEL to "How much do you save a month?",
    UiKey.SAVCALC_MONTHS_LABEL to "For how many months?",
    UiKey.SAVCALC_HERO_TARGET to "You need to save each month",
    UiKey.SAVCALC_HERO_REACH to "You will reach",
    UiKey.SAVCALC_FILL to "Complete the fields",
    UiKey.SAVCALC_FILL_SUB to "The result shows once the fields are valid.",
    UiKey.SAVCALC_SUB_TARGET to "For {0} until {1}, {2} left, without returns",
    UiKey.SAVCALC_SUB_HAVE_ALL to "You already have the full amount.",
    UiKey.SAVCALC_SUB_REACH to "On {0}: {1} × {2} + what you have, without returns",
    UiKey.SAVCALC_COMPARE_TITLE to "Compared with what you actually save",
    UiKey.SAVCALC_VERDICT_UNKNOWN to "Unknown",
    UiKey.SAVCALC_VERDICT_ENOUGH to "Enough",
    UiKey.SAVCALC_VERDICT_SHORT to "{0} short",
    UiKey.SAVCALC_MONTH_UNKNOWN to "Unknown",
    UiKey.SAVCALC_COMPARE_LINE to "Your average saving: {0} a month, needed {1}",
    UiKey.SAVCALC_COMPARE_EXTRA to " — {0} extra",
    UiKey.SAVCALC_COMPARE_NOTE to "The last 3 complete financial months (starting on day {0}): real income minus real spending. Transfers between your wallets, loans and asset purchases are left out.",
    UiKey.SAVCALC_COMPARE_NOTE_PLAIN to "The last 3 complete financial months: real income minus real spending. Transfers between your wallets, loans and asset purchases are left out.",
    UiKey.SAVCALC_REVIEW to "Set the type of these operations",
    UiKey.SAVCALC_GOAL to "Turn it into a savings plan",
    UiKey.SAVCALC_GOAL_DONE to "Plan created ✓",
    UiKey.SAVCALC_GOAL_NOTE to "Same amount and date; what you have is recorded as its first deposit today.",
    UiKey.SAVCALC_GOAL_TOAST to "Plan “{0}” created: {1} a month until {2}",
    UiKey.SAVCALC_GOAL_FAILED to "Could not create the plan",
    UiKey.SAVGROW_TITLE to "If you put it in…",
    UiKey.SAVGROW_PAID to "From your pocket: {0} over {1}",
    UiKey.SAVGROW_TODAY to "In today's money",
    UiKey.SAVGROW_TODAY_SUB to "Official inflation of {0} a year is taken out",
    UiKey.SAVGROW_RATE_YEARLY to "{0} a year",
    UiKey.SAVGROW_INFO to "{0}: {1} — for information only",
    UiKey.SAVGROW_CASH_FIXED to "Fixed: zero",
    UiKey.SAVGROW_TYPE_RATE to "Enter the rate",
    UiKey.SAVGROW_EDIT_RATE to "Edit the rate",
    UiKey.SAVGROW_RESET to "Back to the average",
    UiKey.SAVGROW_FOOT to "Gold, real estate and stocks use a compound average yearly increase; the deposit uses the bank's interest each month. This is a past average, not a promise.",
    UiKey.SAVGROW_SHEET_TITLE to "Yearly increase — {0}",
    UiKey.SAVGROW_SHEET_BODY to "Enter the yearly rate you expect. What you enter overrides the average.",
    UiKey.SAVGROW_SHEET_BODY_DEPOSIT to "Enter your bank's interest on the deposit.",
    UiKey.SAVGROW_SAVE to "Calculate with it",
)
