package app.masroufy.core

/** باقي نصوص الواجهة المشتركة **بالمصري** — نفس مفاتيح `TextsShellAuth.kt` (ملف لوحده عشان حد الـ300 سطر). */
internal val EGYPTIAN_SHELL_AUTH_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.UPCOMING_TITLE to "القادم",
    TextKey.UPCOMING_LIST to "المواعيد الجاية",
    TextKey.UPCOMING_TODAY to "النهارده",
    TextKey.UPCOMING_TOMORROW to "بكرة",
    TextKey.UPCOMING_TWO_DAYS to "بعد يومين",
    TextKey.UPCOMING_FEW_DAYS to "بعد {0} أيام",
    TextKey.UPCOMING_MANY_DAYS to "بعد {0} يوم",
    TextKey.UPCOMING_HELD to "محجوز",
    TextKey.UPCOMING_OPEN to "مش محجوز",
    TextKey.UPCOMING_NO_AMOUNT to "من غير مبلغ",
    TextKey.UPCOMING_INCOMING to "فلوس جاية",
    TextKey.UPCOMING_LATE to "فات ميعاده",
    TextKey.UPCOMING_EMPTY to "مفيش مواعيد جاية.",
    TextKey.CALENDAR_OPEN to "التقويم",
    TextKey.QUICK_TITLE to "متوقعة الشهر ده ولسه ما اتسجلتش",
    TextKey.QUICK_SHEET_BODY to "المبلغ المعتاد جاهز — غيّره لو اختلف الشهر ده.",
    TextKey.QUICK_USUAL to "عادةً {0}، يوم {1}",
    TextKey.QUICK_FROM to "دفعتها منين؟",
    TextKey.QUICK_SAVE to "سجّلها",
    TextKey.QUICK_SKIP to "مش هدفعها الشهر ده",
    TextKey.QUICK_RECORDED to "اتسجّل «{0}» {1}",
    TextKey.QUICK_SKIPPED to "تمام — مش هنسألك عنها تاني الشهر ده.",
    TextKey.CAL_PREV to "الشهر اللي فات",
    TextKey.CAL_NEXT to "الشهر الجاي",
    TextKey.CAL_TODAY to "النهارده",
    TextKey.CAL_NO_DATES to "مفيش مواعيد",
    TextKey.CAL_LEGEND_SUB to "اشتراكات وفواتير",
    TextKey.CAL_LEGEND_INST to "أقساط",
    TextKey.CAL_LEGEND_ROSCA to "جمعيات",
    TextKey.CAL_LEGEND_DEBT to "ديون",
    TextKey.CAL_LEGEND_EVENT to "أحداث ومناسبات",
    TextKey.CAL_LEGEND_PAY to "المرتب",
    TextKey.CAL_LEGEND_LATE to "فات ميعاده",
    TextKey.CAL_MORE to "+{0}",
    TextKey.SIGNIN_WELCOME_TITLE to "أهلًا بيك في مصروفي",
    TextKey.SIGNIN_WELCOME_SUB to "دقيقة واحدة نجهّز فيها حسابك، والباقي وقت ما تحب.",
    TextKey.SIGNIN_HOW to "عايز تدخل إزاي؟",
    TextKey.SIGNIN_HOW_SUB to "حسابك بيحفظ بياناتك ويزامنها على كل أجهزتك.",
    TextKey.SIGNIN_GOOGLE to "الدخول بحساب Google",
    TextKey.SIGNIN_WITH_EMAIL to "الدخول بالإيميل",
    TextKey.SIGNIN_TITLE to "الدخول بالإيميل",
    TextKey.SIGNIN_MODES to "نوع الدخول",
    TextKey.SIGNIN_MODE_IN to "تسجيل الدخول",
    TextKey.SIGNIN_MODE_NEW to "حساب جديد",
    TextKey.SIGNIN_EMAIL to "الإيميل",
    TextKey.SIGNIN_PASSWORD to "كلمة السر",
    TextKey.SIGNIN_PASS_HINT to "٦ حروف على الأقل.",
    TextKey.SIGNIN_SHOW_PASS to "اظهر كلمة السر",
    TextKey.SIGNIN_HIDE_PASS to "اخفي كلمة السر",
    TextKey.SIGNIN_SUBMIT_IN to "دخول",
    TextKey.SIGNIN_SUBMIT_NEW to "اعمل الحساب",
    TextKey.SIGNIN_BUSY_IN to "بيدخل…",
    TextKey.SIGNIN_BUSY_NEW to "الحساب بيتعمل…",
    TextKey.SIGNIN_OFFLINE_NOTE to "الدخول محتاج نت.",
    TextKey.SIGNIN_EMULATOR_NOTE to "نسخة اختبار على محاكي فايربيز في الكمبيوتر — بيانات وهمية بس.",
    TextKey.RESET_TRIGGER to "نسيت كلمة السر؟",
    TextKey.RESET_TITLE to "نسيت كلمة السر",
    TextKey.RESET_BODY to "اكتب إيميلك وهنبعتلك عليه لينك تعمل بيه كلمة سر جديدة.",
    TextKey.RESET_EMAIL_EMPTY to "اكتب الإيميل",
    TextKey.RESET_SEND to "ابعت لينك التغيير",
    TextKey.RESET_SENDING to "بيتبعت…",
    TextKey.RESET_PRIVACY to "علشان نحمي الحسابات، مش بنقول إذا كان الإيميل متسجل عندنا ولا لأ.",
    TextKey.RESET_SENT_TITLE to "بص على إيميلك",
    TextKey.RESET_SENT_BODY to "لو {0} متسجل عندنا، هيوصله لينك تعمل بيه كلمة سر جديدة خلال دقايق.",
    TextKey.RESET_SPAM to "موصلش؟ بص في الرسايل المزعجة، أو ابعته تاني.",
    TextKey.RESET_RESEND to "ابعته تاني",
    TextKey.RESET_AGAIN to "اتبعت تاني.",
    TextKey.RESET_WAIT_ONE to "تقدر تبعته تاني بعد ثانية.",
    TextKey.RESET_WAIT_TWO to "تقدر تبعته تاني بعد ثانيتين.",
    TextKey.RESET_WAIT_FEW to "تقدر تبعته تاني بعد {0} ثواني.",
    TextKey.RESET_WAIT_MANY to "تقدر تبعته تاني بعد {0} ثانية.",
    TextKey.RESET_CHANGE to "غيّر الإيميل",
    TextKey.RESET_FINISH to "ارجع لتسجيل الدخول",
    TextKey.RESET_OFFLINE to "إعادة الإرسال محتاجة نت.",
    TextKey.LOCK_SCREEN_TITLE to "مصروفي مقفول",
    TextKey.LOCK_SCREEN_BODY to "افتحه ببصمتك أو رمز الموبايل.",
    TextKey.LOCK_SCREEN_OPEN to "افتح",
    TextKey.LOCK_RELEASED to "الموبايل مالوش قفل، فقفل التطبيق اتوقف. شغّله من «المزيد ← الإعدادات» بعد ما تعمل قفل للموبايل.",
    TextKey.FEED_OFFLINE to "مفيش نت — ما عرفناش نحدّث الأسعار.",
    TextKey.FEED_HTTP_FAILED to "ما عرفناش ننزّل الملف (الرد {0}).",
    TextKey.FEED_UPDATED_AT to "آخر تحديث {0}",
    TextKey.AUTH_GOOGLE_NO_ACCOUNT to "مفيش حساب Google على الموبايل ده. ضيفه من إعدادات الموبايل أو ادخل بالإيميل.",
    TextKey.AUTH_GOOGLE_FAILED to "ما عرفناش ندخل بحساب Google دلوقتي. جرّب تاني أو ادخل بالإيميل.",
)
