package app.masroufy.core

/**
 * النصوص بالفصحى المختصرة (OVERRIDES §66) — للسعودية والافتراضي لأي بلد غير مصر. نفس مفاتيح المصري ونفس `{0}` `{1}` بنفس المعنى.
 * **القاعدة:** أقصر كلام صحيح — العنوان والزر من كلمة لأربع، والرسالة جملة قصيرة. ممنوع أي صيغة مصرية (اختبار بيمسح الجدول).
 * ترجمة Claude ومستنية مراجعة المالك (§66).
 */
internal val MSA_SCREEN_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.KIND_SALARY to "راتب",
    TextKey.KIND_BONUS to "مكافأة",
    TextKey.KIND_COMMISSION to "عمولة",
    TextKey.KIND_OVERTIME to "دوام إضافي",
    TextKey.KIND_FREELANCE to "عمل حر",
    TextKey.KIND_PERSONAL_SALE to "بيع شخصي",
    TextKey.KIND_LOAN_RECEIVED to "قرض مستلم",
    TextKey.KIND_DEBT_COLLECTED to "تحصيل دين لك",
    TextKey.KIND_CUSTODY_RECEIVED to "أمانة مستلمة",
    TextKey.KIND_PURCHASE to "شراء / فاتورة",
    TextKey.KIND_SUPPORT_GIFT to "دعم / هدية",
    TextKey.KIND_FEE to "رسوم",
    TextKey.KIND_LOAN_GRANTED to "قرض ممنوح",
    TextKey.KIND_DEBT_REPAID to "سداد دين عليك",
    TextKey.KIND_CUSTODY_RETURNED to "رد أمانة",
    TextKey.KIND_INTERNAL_TRANSFER to "تحويل داخلي",
    TextKey.KIND_ASSET_BUY to "شراء أصل",
    TextKey.KIND_ASSET_SELL to "بيع أصل",
    TextKey.KIND_UNCLASSIFIED to "غير محدد",
    TextKey.KIND_UNKNOWN_WIRE to "نوع اقتصادي غير معروف: {0}",

    TextKey.CURRENCY_SAR to "ر.س",
    TextKey.CURRENCY_EGP to "ج.م",
    TextKey.CURRENCY_USD to "$",
    TextKey.CURRENCY_EUR to "€",
    TextKey.CURRENCY_GBP to "£",
    TextKey.CURRENCY_AED to "د.إ",

    TextKey.NOT_AVAILABLE to "غير متاح",

    TextKey.AMOUNT_CONTEXT_DISPLAY to "مبلغ للعرض",
    TextKey.AMOUNT_CONTEXT_INCOME to "الدخل",
    TextKey.AMOUNT_CONTEXT_REMAINING to "المتبقي",

    TextKey.SUGGEST_CASH_WITHDRAWAL to "سحب نقدي: انتقل المبلغ من البنك إلى محفظة الكاش، ولم يُصرف",
    TextKey.SUGGEST_INVESTMENT_BUY to "«{0}»: شراء أصل استثماري، لا استهلاك",
    TextKey.SUGGEST_BANK_FEES to "رسوم بنكية: مصروف مستقل",
    TextKey.SUGGEST_INSTALLMENT to "تقسيط: سداد جزء من التزام سابق. إن سُجّل الشراء الأصلي مصروفًا فاحتسابه مجددًا عدّ مزدوج.",
    TextKey.SUGGEST_DEBT_PAYMENT to "سداد: قد يكون سداد دين عليك (ليس مصروفًا) أو دفع فاتورة (مصروف). الكشف لا يفرّق، فالقرار لك.",
    TextKey.SUGGEST_DIGITAL_WALLET to "محفظة رقمية (مثل برق): خرج المبلغ من الراجحي دون بيان وجهته. قد تكون محفظتك، أو دعمًا أو قرضًا لشخص.",
    TextKey.SUGGEST_TRANSFER_OUT to "تحويل صادر: الكشف لا يبيّن سببه. قد يكون لحسابك، أو دعمًا، أو قرضًا، أو سدادًا.",
    TextKey.SUGGEST_BARQ to "برق وسيلة تحويل لا نوع مصروف. حدّد الغرض: حسابك، أو دعم، أو قرض، أو سداد.",
    TextKey.SUGGEST_PURCHASE to "«{0}»: شراء أو فاتورة",
    TextKey.SUGGEST_OUT_NO_CATEGORY to "صادر دون تصنيف واضح. حدّد: شراء أم نقل أموال؟",
    TextKey.SUGGEST_INVESTMENT_SELL to "وارد من الاستثمار: حصيلة بيع أصل، والمكسب هو الربح المحقق فقط",
    TextKey.SUGGEST_REFUND to "استرداد: مبلغ دفعته عاد إليك، وليس دخلًا جديدًا. الأفضل ربطه بالعملية الأصلية.",
    TextKey.SUGGEST_IN_UNKNOWN to "وارد: الكشف لا يبيّن مصدره. راتب؟ قرض مستلم؟ تحصيل دين؟ أمانة؟ الفرق كبير في الحساب.",
    TextKey.SUGGEST_IN_WITH_CATEGORY to "وارد بتصنيف «{0}»: حدّد نوعه الاقتصادي.",
    TextKey.ASSET_KIND_GOLD to "ذهب",
    TextKey.ASSET_KIND_STOCK to "سهم",
    TextKey.ASSET_KIND_FUND to "صندوق",
    TextKey.ASSET_KIND_DIGITAL to "أصل رقمي",
    TextKey.ASSET_KIND_OTHER to "أصل آخر",
    TextKey.AMOUNT_EDIT_INVALID to "أدخل مبلغًا صحيحًا أكبر من صفر، مثل 180 أو 180.50",
    TextKey.AMOUNT_EDIT_BELOW_ALLOCATIONS to "المبلغ أقل من الموزّع على أشخاص من هذه العملية ({0}). عدّل التوزيع أولًا.",
    TextKey.AMOUNT_EDIT_BELOW_SETTLEMENTS to "المبلغ أقل من المسدَّد منه دين من هذه العملية ({0}). عدّل التسوية أولًا.",
    TextKey.ALLOWANCE_PERIOD_ENDED to "انتهت الفترة، فلا أيام متبقية للتوزيع.",
    TextKey.ALLOWANCE_NO_LIMIT_NO_REMAINING to "لا سقف لهذه الفترة، والمتبقي غير معروف بعد.",
    TextKey.ALLOWANCE_NO_LIMIT_SPENT to "تقريبي — لا سقف للميزانية، والمتبقي نفد.",
    TextKey.ALLOWANCE_NO_LIMIT to "تقريبي — لا سقف للميزانية، فهذا المتبقي موزعًا على {0} يومًا متبقيًا.",
    TextKey.ALLOWANCE_LIMIT_SPENT to "استنفدت سقف هذه الفترة.",
    TextKey.ALLOWANCE_LIMIT to "المتبقي من السقف موزعًا على {0} يومًا متبقيًا.",
    TextKey.FORECAST_TOO_EARLY to "مضى {0} يومًا فقط — التوقع يحتاج {1} أيام على الأقل.",
    TextKey.FORECAST_PERIOD_ENDED to "انتهت الفترة، فهذا المصروف الفعلي لا توقع.",
    TextKey.FORECAST_RATE to "إن استمر باقي الفترة بالمعدل نفسه (مضى {0} يومًا).",
    TextKey.COVERAGE_ALL_UNCLASSIFIED to "العمليات الـ{0} كلها تحتاج تحديد نوعها، فالمجاميع غير متاحة.",
    TextKey.COVERAGE_SOME_UNCLASSIFIED to "{0} عملية من {1} تحتاج تحديد نوعها، فهذه الأرقام ناقصة.",
    TextKey.BUDGET_LIMIT_POSITIVE to "يجب أن يكون السقف أكبر من صفر",
    TextKey.BUDGET_SPENT_NEEDS_REVIEW to "تقريبي: {0} عملية تحتاج تأكيد نوعها، ويُضبط الرقم بعد تأكيدها.",
    TextKey.BUDGET_SPENT_ESTIMATED to "تقريبي: {0} عملية حُدّد نوعها تلقائيًا.",
    TextKey.PERIOD_EXCLUDED_UNRELIABLE to "فيها عمليات تحتاج تحديد نوعها، فمصروفها ناقص",
    TextKey.PERIOD_EXCLUDED_EMPTY to "لا عمليات فيها — لا يُعرف هل هو صفر فعلي أم بيانات ناقصة",
    TextKey.AVERAGE_NEEDS_PERIODS to "المتوسط يحتاج {0} فترات مكتملة على الأقل، والمتاح {1}.",
    TextKey.AVERAGE_OF_PERIODS to "متوسط {0} فترة مكتملة.",
    TextKey.ANOMALY_NEEDS_HISTORY to "الحكم على الصرف غير المعتاد يحتاج {0} فترات سابقة على الأقل، والمتاح {1}.",
    TextKey.ANOMALY_MEDIAN_ZERO to "الوسيط التاريخي صفر، فلا معنى للمقارنة النسبية.",
    TextKey.ANOMALY_WITHIN_TWENTY to "الفرق عن المعتاد أقل من ٢٠٪، فهو ضمن المعتاد.",
    TextKey.ANOMALY_HIGHER to "أعلى",
    TextKey.ANOMALY_LOWER to "أقل",
    TextKey.ANOMALY_OUTSIDE to "{0} من المعتاد بنسبة {1}٪ — خارج تقلّب الفترات السابقة.",
    TextKey.ANOMALY_INSIDE to "{0} من المعتاد بنسبة {1}٪، لكنه ضمن التقلّب المعتاد للفترات السابقة.",
    TextKey.CATEGORY_NO_LIMIT to "لا سقف لهذا التصنيف. يمكنك تحديده من هنا.",
    TextKey.CATEGORIZED_USER_CONFIRMED to "أكّدت هذا التصنيف بنفسك",
    TextKey.CATEGORIZED_MERCHANT to "للتاجر «{0}» تصنيف مؤكد",
    TextKey.CATEGORIZED_RULE to "طابقت قاعدة «{0}»",
    TextKey.CATEGORIZED_SOURCE_COLUMN to "التصنيف من عمود التصنيف في الملف: «{0}»",
    TextKey.CATEGORIZED_NONE to "لم تطابق هذه العملية قاعدةً ولا تاجرًا مؤكدًا",
    TextKey.ASSET_BUY_QUANTITY_POSITIVE to "يجب أن تكون كمية الشراء أكبر من صفر",
    TextKey.ASSET_SELL_QUANTITY_POSITIVE to "يجب أن تكون كمية البيع أكبر من صفر",
    TextKey.ASSET_SELL_OVER_HELD to "بيع {0} والمملوك حينها {1} فقط. لا رصيد سالب دون تنبيه.",
    TextKey.PRICE_MISSING to "لا سعر مسجل. القيمة الحالية غير متاحة",
    TextKey.PRICE_FRESH to "السعر {0} بتاريخ {1}",
    TextKey.PRICE_FUTURE to "السعر بتاريخ {0} — تاريخ مستقبلي، راجعه",
    TextKey.PRICE_STALE to "السعر {0} بتاريخ {1} — مضى عليه {2} يومًا",
    TextKey.FEED_BAD_SHAPE to "ملف الأسعار بغير الشكل المتوقع",
    TextKey.FEED_NO_GENERATED_AT to "ملف الأسعار بلا تاريخ توليد",
    TextKey.FEED_NO_CURRENCY to "ملف الأسعار لا يذكر عملته",
    TextKey.FEED_NO_PRICES to "ملف الأسعار خالٍ من الأسعار",
    TextKey.FEED_ENTRY_NOT_OBJECT to "المدخل ليس كائنًا",
    TextKey.FEED_PRICE_NOT_INTEGER to "السعر ليس عددًا صحيحًا موجبًا بالهللة",
    TextKey.FEED_NO_VALID_DATE to "لا تاريخ صالح للسعر",
    TextKey.FEED_NO_SOURCE to "لا مصدر مكتوب للسعر",
    TextKey.FEED_UNKNOWN_SOURCE to "مصدر غير معروف",
    TextKey.FEED_NO_REASON to "سبب غير مكتوب",
    TextKey.FEED_SUMMARY to "{0} سعر محدَّث في {1}",
    TextKey.FEED_SUMMARY_WITH_MISSING to "{0}، و{1} مصدر بلا سعر",
    TextKey.JOIN_AND to " و",
    TextKey.GROUP_FOOD to "الطعام والشراب",
    TextKey.GROUP_HOME to "المنزل والالتزامات",
    TextKey.GROUP_TRANSPORT to "التنقل",
    TextKey.GROUP_PERSONAL to "الحياة الشخصية",
    TextKey.GROUP_SAVING to "الادخار والاستثمار",
    TextKey.GROUP_MOVEMENT to "حركة أموال لا مصروف",
    TextKey.REQ_HAS_CAR to "لمن لديه سيارة",
    TextKey.REQ_DEPENDENTS to "لمن يعول زوجة أو أولادًا",
    TextKey.REQ_RENTER to "لمن يسكن بالإيجار",
    TextKey.REQ_DOMESTIC_WORKER to "لمن لديه عمالة منزلية",
    TextKey.REQ_BUSINESS to "لمن لديه عمل خاص",
    TextKey.DIFF_DATE to "التاريخ",
    TextKey.DIFF_AMOUNT to "المبلغ",
    TextKey.DIFF_DIRECTION to "اتجاه الحركة",
    TextKey.DIFF_MERCHANT to "اسم التاجر",
    TextKey.DEDUPE_SMS_SIMILAR to "عملية بنفس اليوم والمبلغ والاتجاه في المحفظة نفسها، وأحد المصدرين رسالة بنك. قد تكون العملية نفسها باسم مختلف؛ لن تُضاف حتى تراجعها.",
    TextKey.DEDUPE_SAME_REFERENCE to "المرجع «{0}» نفسه والتفاصيل نفسها — العملية مسجلة سابقًا",
    TextKey.DEDUPE_REFERENCE_CONFLICT to "المرجع «{0}» نفسه لكن {1} مختلف. لن نستبدل القديم دون قرارك.",
    TextKey.DEDUPE_SAME_STATEMENT_LINE to "سطر الكشف نفسه: اليوم والمبلغ والاتجاه والرصيد بعد العملية في الحساب نفسه — مسجلة سابقًا ولو قُرئ الاسم بشكل مختلف",
    TextKey.DEDUPE_NEW_REFERENCE to "مرجع جديد لم يسبق",
    TextKey.DEDUPE_SIMILAR_NO_REFERENCE to "التاجر والمبلغ والتاريخ والاتجاه نفسها، ولا مرجع بنكي يؤكد. قد تكون العملية نفسها أو عملية أخرى فعلية — القرار لك.",
    TextKey.DEDUPE_NEW to "عملية جديدة لا يشبهها شيء",
    TextKey.NOTICE_SPENT_OVER to "صرفت {0} من {1} — بزيادة {2}",
    TextKey.NOTICE_SPENT_LEFT to "صرفت {0} من {1} — المتبقي {2}",
    TextKey.NOTICE_BUDGET_EXCEEDED to "تجاوزت الميزانية",
    TextKey.NOTICE_BUDGET_THRESHOLD to "بلغت {0}٪ من الميزانية",
    TextKey.NOTICE_CATEGORY_EXCEEDED to "تجاوزت سقف «{0}»",
    TextKey.NOTICE_CATEGORY_THRESHOLD to "«{0}» بلغ {1}٪",
    TextKey.LEDGER_ALLOCATIONS_EXCEED to "مجموع التخصيصات ({0}) أكبر من قيمة العملية ({1})",
    TextKey.LEDGER_SETTLEMENTS_EXCEED to "تسويات الالتزام {0} تجاوزت أصله — يُمنع الرصيد السالب دون تنبيه",
    TextKey.SETTLEMENT_AMOUNT_POSITIVE to "يجب أن يكون مبلغ التسوية أكبر من صفر",
    TextKey.SETTLEMENT_FULLY_PAID to "هذا الالتزام مسدد بالكامل. لا متبقي للتسوية",
    TextKey.OBLIGATION_CUSTODY to "الأمانة",
    TextKey.OBLIGATION_LOAN to "الدين",
    TextKey.OBLIGATION_RECEIVABLE to "المستحق",
    TextKey.SETTLEMENT_OVER_REMAINING to "المبلغ أكبر من المتبقي. {0} المتبقي {1} والمبلغ المُدخل {2}. يمكنك تسوية {1} وتسجيل الباقي {3} أمانةً مستقلة بإجراء صريح.",
    TextKey.LEDGER_FEE_NEGATIVE to "الرسوم لا تكون سالبة",
    TextKey.LEDGER_FEE_OVER_GROSS to "الرسوم ({0}) أكبر من الإجمالي المخصوم ({1})",
    TextKey.SCHEMA_UNKNOWN_COLUMNS to "الأعمدة لا تطابق أي مخطط معروف.\nالموجود: {0}\nالمتوقع إما: {1}\nأو: {2}\nإن اختلفت أعمدة الملف فيلزم تعيينها يدويًا — لن نخمّن أعمدة مالية.",
    TextKey.ROW_DATE_INVALID to "التاريخ «{0}» غير صالح. المتوقع YYYY-MM-DD لتاريخ موجود فعلًا",
    TextKey.ROW_AMOUNT_INVALID to "المبلغ «{0}» ليس رقمًا صالحًا",
    TextKey.ROW_AMOUNT_NEGATIVE to "المبلغ «{0}» سالب. الاتجاه يُحدَّد من عمود type",
    TextKey.ROW_AMOUNT_ZERO to "المبلغ صفر — لا أثر ماليًا لهذه العملية",
    TextKey.ROW_TYPE_UNKNOWN to "نوع العملية «{0}» غير معروف. المتوقع expense أو income أو transfer",
    TextKey.ROW_LEGACY_DATE_INVALID to "التاريخ «{0}» غير صالح. المتوقع YYYY/MM/DD لتاريخ موجود",
    TextKey.ROW_DEBIT_INVALID to "قيمة المدين «{0}» ليست رقمًا صالحًا",
    TextKey.ROW_CREDIT_INVALID to "قيمة الدائن «{0}» ليست رقمًا صالحًا",
    TextKey.ROW_DEBIT_CREDIT_NEGATIVE to "يجب أن يكون المدين والدائن موجبين",
    TextKey.ROW_DEBIT_AND_CREDIT to "في الصف مدين ودائن معًا — اتجاه الحركة غير واضح",
    TextKey.ROW_NO_DEBIT_NO_CREDIT to "الصف بلا مدين ولا دائن — لا أثر ماليًا له",
    TextKey.CSV_TOO_LARGE to "الملف أكبر من الحد المسموح (12 ميجابايت)",
    TextKey.CSV_TOO_MANY_ROWS to "الملف يتجاوز {0} صف",
    TextKey.CSV_CELL_TOO_LONG to "خانة في السطر {0} أطول من الحد المسموح",
    TextKey.CSV_UNCLOSED_QUOTE to "علامة اقتباس لم تُغلق — الملف ناقص أو تالف عند السطر {0}",
    TextKey.CSV_EMPTY to "الملف فارغ",
    TextKey.PERIOD_BAD_MONTH to "شهر غير صالح: {0}",
    TextKey.PERIOD_BAD_DATE_FORMAT to "صيغة التاريخ غير صالحة: {0}",
    TextKey.PERIOD_BAD_MONTH_IN to "شهر غير صالح في: {0}",
    TextKey.PERIOD_BAD_DAY to "يوم غير موجود: {0} ({1} فيه {2} يومًا)",
    TextKey.PERIOD_BAD_PAYDAY to "يجب أن يكون يوم الراتب بين 1 و31، لا {0}",
    TextKey.PROJECT_NAME_LENGTH to "اسم المشروع {0} حرفًا كحد أقصى.",
    TextKey.PROJECT_NAME_DUPLICATE to "يوجد مشروع بالاسم نفسه.",
    TextKey.PROJECT_RULE_TEXT_LENGTH to "نص القاعدة من حرفين إلى {0} حرفًا.",
    TextKey.PROJECT_RULE_DIRECTION to "الاتجاه غير معروف.",
    TextKey.PROJECT_NOT_FOUND to "المشروع غير موجود.",
    TextKey.PROJECT_RULE_NOT_FOUND to "القاعدة غير موجودة.",
    TextKey.PROFILE_NAME_TOO_LONG to "الاسم أطول من {0} حرفًا",
    TextKey.PROFILE_SALARY_INVALID to "يجب أن يكون الراتب مبلغًا صحيحًا غير سالب",
    TextKey.PROFILE_PAYDAY_RANGE to "يجب أن يكون يوم الراتب من 1 إلى 31",
    TextKey.PROFILE_GENDER to "اختر ذكرًا أو أنثى، أو اتركه فارغًا",
    TextKey.PROFILE_DEPENDENTS to "اختر الزوج أو الزوجة أو الأولاد أو الأهل، أو اتركه فارغًا",
    TextKey.RECURRING_DETECTED to "٣ دورات متتالية لخدمة مناسبة، بمبلغ متقارب ±٥٪ وموعد متقارب ±٧ أيام.",
    TextKey.RECURRING_NAME to "اسم الخدمة ١٢٠ حرفًا كحد أقصى.",
    TextKey.RECURRING_CYCLE to "اختر دورة شهرية أو ربع سنوية أو سنوية.",
    TextKey.RECURRING_KIND to "نوع الالتزام غير صالح.",
    TextKey.RECURRING_AMOUNT to "يجب أن تكون قيمة الدورة أكبر من صفر.",
    TextKey.RECURRING_LINK to "ربط الخدمة غير صالح.",
    TextKey.CATEGORY_NOT_FOUND to "التصنيف غير موجود.",
    TextKey.CATEGORY_NAME_LENGTH to "اسم التصنيف ٨٠ حرفًا كحد أقصى.",
    TextKey.CATEGORY_NAME_DUPLICATE to "يوجد تصنيف بالاسم نفسه.",
    TextKey.CATEGORY_ICON_REQUIRED to "اختر رمزًا من القائمة.",
    TextKey.CATEGORY_SELF_PARENT to "لا يكون التصنيف فرعيًا لنفسه.",
    TextKey.CATEGORY_PARENT_MISSING to "التصنيف الرئيسي المختار غير موجود.",
    TextKey.CATEGORY_PARENT_NOT_MAIN to "اختر تصنيفًا رئيسيًا لا فرعيًا.",
    TextKey.CATEGORY_HAS_SUBS to "لهذا التصنيف فروع، فلا يُنقل تحت تصنيف آخر.",
    TextKey.CATEGORY_GROUP_UNKNOWN to "المجموعة المختارة غير معروفة.",
    TextKey.CATEGORY_COLOR_REQUIRED to "اختر لونًا من القائمة.",
    TextKey.GROUP_UNGROUPED to "التصنيفات",
    TextKey.GROUP_NO_GROUP to "بلا مجموعة",
    TextKey.GROUP_HIDDEN to "المخفية",
    TextKey.SETTLEMENT_OBLIGATION_MISSING to "هذا الالتزام غير موجود لهذا الشخص",
    TextKey.SETTLEMENT_AMOUNT_HALALAS to "يجب أن يكون مبلغ التسوية عددًا صحيحًا بالهللة وأكبر من صفر",
    TextKey.SETTLEMENT_REQUEST_CONFLICT to "حُفظ هذا الطلب سابقًا ببيانات مختلفة. راجع التسوية المسجلة",
    TextKey.SETTLEMENT_REJECTED to "التسوية مرفوضة",
    TextKey.REVERT_KEPT_DUE to "هذه العملية مرتبطة بالمستحقات أو بدفعة زكاة سُجّلت بعد الاستيراد، فلن تُحذف",
    TextKey.REVERT_KEPT_INVESTMENT to "هذه العملية مرتبطة بشراء استثمار أو بيعه، فلن تُحذف",
    TextKey.REVERT_KEPT_GIFT to "هذه العملية نقوط مرتبطة بشخص في حدث، فلن تُحذف",
)
