package app.masroufy.core

/**
 * «محفظة جديدة» و«رصيد البداية» (`WalletAddSheet` بوضعين) — منطقة «المزيد». من النموذج بالحرف، إلا:
 * - «اسمها مكرر» من غير اقتراح اسم (الاقتراح كان مبني على الاسم المكتوب).
 * - سطر «غير متاح بعد» (مفيش حالة استخدام لإضافة محفظة ولا لتعديل رصيد البداية) — كتابة Claude.
 * أسماء البنوك والمحافظ الإلكترونية في القايمة القصيرة اختيار النموذج (§76 — مستنية تأكيد المالك).
 */
internal val MSA_MORE_WALLET_ADD_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.WADD_OPEN to "أضف محفظة",
    TextKey.WADD_EDIT_OPEN to "تعديل رصيد البداية",
    TextKey.WADD_TITLE to "محفظة جديدة",
    TextKey.WADD_EDIT_TITLE to "رصيد البداية",
    TextKey.WADD_SUB to "{0} — عملة هذا البلد.",
    TextKey.WADD_SUB_SA to "في السعودية، بالريال السعودي (ر.س)",
    TextKey.WADD_SUB_EG to "في مصر، بالجنيه المصري (ج.م)",
    TextKey.WADD_KIND to "نوعها",
    TextKey.WADD_BANK to "البنك",
    TextKey.WADD_WALLET to "المحفظة",
    TextKey.WADD_SUGGESTED to "اسم مقترح",
    TextKey.WADD_SA_RAJHI to "مصرف الراجحي",
    TextKey.WADD_SA_SNB to "البنك الأهلي السعودي",
    TextKey.WADD_SA_INMA to "مصرف الإنماء",
    TextKey.WADD_SA_RIYAD to "بنك الرياض",
    TextKey.WADD_SA_ANB to "البنك العربي الوطني",
    TextKey.WADD_SA_STCPAY to "stc pay",
    TextKey.WADD_SA_URPAY to "urpay",
    TextKey.WADD_EG_NBE to "البنك الأهلي المصري",
    TextKey.WADD_EG_QNB to "QNB مصر",
    TextKey.WADD_EG_MISR to "بنك مصر",
    TextKey.WADD_EG_CIB to "البنك التجاري الدولي",
    TextKey.WADD_EG_ALEX to "بنك الإسكندرية",
    TextKey.WADD_EG_VODAFONE to "فودافون كاش",
    TextKey.WADD_EG_ORANGE to "أورانج كاش",
    TextKey.WADD_OTHER_BANK to "بنك آخر",
    TextKey.WADD_OTHER_WALLET to "محفظة أخرى",
    TextKey.WADD_CASH_HOME to "كاش البيت",
    TextKey.WADD_CASH_WORK to "كاش الشغل",
    TextKey.WADD_CASH_TRAVEL to "كاش السفر",
    TextKey.WADD_CASH_CAR to "كاش السيارة",
    TextKey.WADD_CASH_HEAD to "الكاش بلا بنك ولا رقم حساب",
    TextKey.WADD_CASH_NOTE to "رصيده تقريبي — لا يظهر فيه الكاش الذي صُرف ولم يُسجَّل. سمّه باسم مكانه لتميّز محافظ الكاش.",
    TextKey.WADD_NAME to "اسمها في التطبيق",
    TextKey.WADD_NAME_PH to "مثلًا: حساب الادخار",
    TextKey.WADD_NAME_PH_CASH to "مثلًا: كاش البيت",
    TextKey.WADD_LAST4_BANK to "آخر ٤ أرقام من الحساب (اختياري)",
    TextKey.WADD_LAST4_WALLET to "آخر ٤ أرقام من رقم المحفظة (اختياري)",
    TextKey.WADD_LAST4_CUT to "أخذنا آخر ٤ أرقام فقط.",
    TextKey.WADD_LAST4_NOTE_BANK to "لا نحفظ رقم الحساب كاملًا أبدًا — هذه الأربعة تميّز الحساب في رسائل البنك.",
    TextKey.WADD_LAST4_NOTE_WALLET to "لا نحفظ رقم المحفظة كاملًا أبدًا — هذه الأربعة تميّزها في رسائلها.",
    TextKey.WADD_AMOUNT to "رصيد البداية (اختياري)",
    TextKey.WADD_DATE to "في تاريخ",
    TextKey.WADD_EFFECT_NONE to "بلا رصيد بداية: رصيدها «غير متاح»",
    TextKey.WADD_EFFECT_NONE_CASH to "حتى تحدّده من صفحتها — لا نكتب صفرًا مكانه.",
    TextKey.WADD_EFFECT_NONE_BANK to "حتى تصل رسالة فيها الرصيد أو تستورد كشفًا — لا نكتب صفرًا مكانه.",
    TextKey.WADD_EFFECT_NEED to "اكتب المبلغ وتاريخه لنحسب رصيدها.",
    TextKey.WADD_EFFECT_FROM to "يبدأ رصيدها من {0} في {1}",
    TextKey.WADD_EFFECT_RECALC to "يُعاد حساب رصيدها من {0}",
    TextKey.WADD_EFFECT_LATER to "الحركات قبل هذا التاريخ تبقى مسجّلة، لكنها لا تدخل في رصيدها.",
    TextKey.WADD_NOT_YET to "إضافة محفظة وتعديل رصيد البداية غير متاحين بعد في هذه النسخة.",
    TextKey.WADD_ERR_BANK to "اختر البنك.",
    TextKey.WADD_ERR_WALLET to "اختر المحفظة.",
    TextKey.WADD_ERR_NAME to "اكتب اسمها.",
    TextKey.WADD_ERR_DUP to "لديك محفظة بهذا الاسم — ميّزها باسم آخر.",
    TextKey.WADD_ERR_LAST4 to "اكتب ٤ أرقام، أو اتركها فارغة.",
    TextKey.WADD_ERR_AMOUNT to "اكتب المبلغ بالأرقام، مثل 1250.50",
    TextKey.WADD_ERR_AMOUNT_REQUIRED to "اكتب رصيد البداية.",
    TextKey.WADD_ERR_DATE to "لا يكون التاريخ بعد اليوم.",
    TextKey.WADD_ERR_UNCHANGED to "لم يتغيّر شيء — عدّل المبلغ أو التاريخ.",
    TextKey.WADD_ERR_SUMMARY to "أكمل الناقص أعلاه.",
    TextKey.WADD_SAVE to "أضفها",
    TextKey.WADD_SAVE_OPENING to "احفظ رصيد البداية",
    TextKey.WADD_UNCHANGED to "لم يتغيّر شيء",
    TextKey.WADD_ADDED to "أُضيفت «{0}»",
    TextKey.WADD_OPENING_SAVED to "حُفظ رصيد البداية",
)

internal val EGYPTIAN_MORE_WALLET_ADD_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.WADD_OPEN to "ضيف محفظة",
    TextKey.WADD_EDIT_OPEN to "عدّل رصيد البداية",
    TextKey.WADD_TITLE to "محفظة جديدة",
    TextKey.WADD_EDIT_TITLE to "رصيد البداية",
    TextKey.WADD_SUB to "{0} — عملة البلد دي.",
    TextKey.WADD_SUB_SA to "في السعودية، بالريال السعودي (ر.س)",
    TextKey.WADD_SUB_EG to "في مصر، بالجنيه المصري (ج.م)",
    TextKey.WADD_KIND to "نوعها",
    TextKey.WADD_BANK to "البنك",
    TextKey.WADD_WALLET to "المحفظة",
    TextKey.WADD_SUGGESTED to "اسم مقترح",
    TextKey.WADD_SA_RAJHI to "مصرف الراجحي",
    TextKey.WADD_SA_SNB to "البنك الأهلي السعودي",
    TextKey.WADD_SA_INMA to "مصرف الإنماء",
    TextKey.WADD_SA_RIYAD to "بنك الرياض",
    TextKey.WADD_SA_ANB to "البنك العربي الوطني",
    TextKey.WADD_SA_STCPAY to "stc pay",
    TextKey.WADD_SA_URPAY to "urpay",
    TextKey.WADD_EG_NBE to "البنك الأهلي المصري",
    TextKey.WADD_EG_QNB to "QNB مصر",
    TextKey.WADD_EG_MISR to "بنك مصر",
    TextKey.WADD_EG_CIB to "البنك التجاري الدولي",
    TextKey.WADD_EG_ALEX to "بنك الإسكندرية",
    TextKey.WADD_EG_VODAFONE to "فودافون كاش",
    TextKey.WADD_EG_ORANGE to "أورانج كاش",
    TextKey.WADD_OTHER_BANK to "بنك تاني",
    TextKey.WADD_OTHER_WALLET to "محفظة تانية",
    TextKey.WADD_CASH_HOME to "كاش البيت",
    TextKey.WADD_CASH_WORK to "كاش الشغل",
    TextKey.WADD_CASH_TRAVEL to "كاش السفر",
    TextKey.WADD_CASH_CAR to "كاش العربية",
    TextKey.WADD_CASH_HEAD to "الكاش من غير بنك ولا رقم حساب",
    TextKey.WADD_CASH_NOTE to "رصيده تقريبي — الكاش اللي اتصرف ومااتسجلش مش باين فيه. سمّيه باسم مكانه عشان تفرّق بين محافظ الكاش.",
    TextKey.WADD_NAME to "اسمها في البرنامج",
    TextKey.WADD_NAME_PH to "مثلًا: حساب التوفير",
    TextKey.WADD_NAME_PH_CASH to "مثلًا: كاش البيت",
    TextKey.WADD_LAST4_BANK to "آخر ٤ أرقام من الحساب (مش لازم)",
    TextKey.WADD_LAST4_WALLET to "آخر ٤ أرقام من رقم المحفظة (مش لازم)",
    TextKey.WADD_LAST4_CUT to "خدنا آخر ٤ أرقام بس.",
    TextKey.WADD_LAST4_NOTE_BANK to "مش بنحفظ رقم الحساب كامل أبدًا — الأربعة دول بيميّزوا الحساب في رسايل البنك.",
    TextKey.WADD_LAST4_NOTE_WALLET to "مش بنحفظ رقم المحفظة كامل أبدًا — الأربعة دول بيميّزوها في رسايلها.",
    TextKey.WADD_AMOUNT to "رصيد البداية (مش لازم)",
    TextKey.WADD_DATE to "في يوم",
    TextKey.WADD_EFFECT_NONE to "من غير رصيد بداية: رصيدها «غير متاح»",
    TextKey.WADD_EFFECT_NONE_CASH to "لحد ما تحدده من صفحتها — مش هنكتب صفر مكانه.",
    TextKey.WADD_EFFECT_NONE_BANK to "لحد ما توصل رسالة فيها الرصيد أو تستورد كشف — مش هنكتب صفر مكانه.",
    TextKey.WADD_EFFECT_NEED to "اكتب المبلغ وتاريخه عشان نحسب رصيدها.",
    TextKey.WADD_EFFECT_FROM to "رصيدها بيبدأ من {0} في {1}",
    TextKey.WADD_EFFECT_RECALC to "رصيدها هيتحسب من جديد من {0}",
    TextKey.WADD_EFFECT_LATER to "الحركات اللي قبل التاريخ ده بتفضل متسجّلة، بس مش بتدخل في رصيدها.",
    TextKey.WADD_NOT_YET to "إضافة محفظة وتعديل رصيد البداية لسه مش متاحين في النسخة دي.",
    TextKey.WADD_ERR_BANK to "اختار البنك.",
    TextKey.WADD_ERR_WALLET to "اختار المحفظة.",
    TextKey.WADD_ERR_NAME to "اكتب اسمها.",
    TextKey.WADD_ERR_DUP to "عندك محفظة بالاسم ده — ميّزها باسم تاني.",
    TextKey.WADD_ERR_LAST4 to "اكتب ٤ أرقام، أو سيبها فاضية.",
    TextKey.WADD_ERR_AMOUNT to "اكتب المبلغ بالأرقام، مثلًا 1250.50",
    TextKey.WADD_ERR_AMOUNT_REQUIRED to "اكتب رصيد البداية.",
    TextKey.WADD_ERR_DATE to "التاريخ ما ينفعش يبقى بعد النهارده.",
    TextKey.WADD_ERR_UNCHANGED to "مفيش حاجة اتغيرت — عدّل المبلغ أو التاريخ.",
    TextKey.WADD_ERR_SUMMARY to "كمّل الناقص فوق.",
    TextKey.WADD_SAVE to "ضيفها",
    TextKey.WADD_SAVE_OPENING to "احفظ رصيد البداية",
    TextKey.WADD_UNCHANGED to "مفيش تغيير",
    TextKey.WADD_ADDED to "اتضافت «{0}»",
    TextKey.WADD_OPENING_SAVED to "اتحفظ رصيد البداية",
)

internal val ENGLISH_MORE_WALLET_ADD_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.WADD_OPEN to "Add a wallet",
    TextKey.WADD_EDIT_OPEN to "Edit opening balance",
    TextKey.WADD_TITLE to "New wallet",
    TextKey.WADD_EDIT_TITLE to "Opening balance",
    TextKey.WADD_SUB to "{0} — this country's currency.",
    TextKey.WADD_SUB_SA to "In Saudi Arabia, in Saudi riyals (ر.س)",
    TextKey.WADD_SUB_EG to "In Egypt, in Egyptian pounds (ج.م)",
    TextKey.WADD_KIND to "Type",
    TextKey.WADD_BANK to "Bank",
    TextKey.WADD_WALLET to "Wallet",
    TextKey.WADD_SUGGESTED to "Suggested name",
    TextKey.WADD_SA_RAJHI to "Al Rajhi Bank",
    TextKey.WADD_SA_SNB to "Saudi National Bank",
    TextKey.WADD_SA_INMA to "Alinma Bank",
    TextKey.WADD_SA_RIYAD to "Riyad Bank",
    TextKey.WADD_SA_ANB to "Arab National Bank",
    TextKey.WADD_SA_STCPAY to "stc pay",
    TextKey.WADD_SA_URPAY to "urpay",
    TextKey.WADD_EG_NBE to "National Bank of Egypt",
    TextKey.WADD_EG_QNB to "QNB Egypt",
    TextKey.WADD_EG_MISR to "Banque Misr",
    TextKey.WADD_EG_CIB to "CIB",
    TextKey.WADD_EG_ALEX to "Bank of Alexandria",
    TextKey.WADD_EG_VODAFONE to "Vodafone Cash",
    TextKey.WADD_EG_ORANGE to "Orange Cash",
    TextKey.WADD_OTHER_BANK to "Another bank",
    TextKey.WADD_OTHER_WALLET to "Another wallet",
    TextKey.WADD_CASH_HOME to "Home cash",
    TextKey.WADD_CASH_WORK to "Work cash",
    TextKey.WADD_CASH_TRAVEL to "Travel cash",
    TextKey.WADD_CASH_CAR to "Car cash",
    TextKey.WADD_CASH_HEAD to "Cash has no bank or account number",
    TextKey.WADD_CASH_NOTE to "Its balance is approximate — cash spent but not recorded doesn't show. Name it after its place to tell cash wallets apart.",
    TextKey.WADD_NAME to "Its name in the app",
    TextKey.WADD_NAME_PH to "e.g. Savings account",
    TextKey.WADD_NAME_PH_CASH to "e.g. Home cash",
    TextKey.WADD_LAST4_BANK to "Last 4 digits of the account (optional)",
    TextKey.WADD_LAST4_WALLET to "Last 4 digits of the wallet number (optional)",
    TextKey.WADD_LAST4_CUT to "We kept only the last 4 digits.",
    TextKey.WADD_LAST4_NOTE_BANK to "We never store the full account number — these four tell the account apart in bank messages.",
    TextKey.WADD_LAST4_NOTE_WALLET to "We never store the full wallet number — these four tell it apart in its messages.",
    TextKey.WADD_AMOUNT to "Opening balance (optional)",
    TextKey.WADD_DATE to "On date",
    TextKey.WADD_EFFECT_NONE to "No opening balance: its balance is “Not available”",
    TextKey.WADD_EFFECT_NONE_CASH to "Until you set it from its page — we never write zero in its place.",
    TextKey.WADD_EFFECT_NONE_BANK to "Until a message with the balance arrives or you import a statement — we never write zero in its place.",
    TextKey.WADD_EFFECT_NEED to "Write the amount and its date so we can work out its balance.",
    TextKey.WADD_EFFECT_FROM to "Its balance starts at {0} on {1}",
    TextKey.WADD_EFFECT_RECALC to "Its balance will be recalculated from {0}",
    TextKey.WADD_EFFECT_LATER to "Movements before this date stay recorded, but don't count toward its balance.",
    TextKey.WADD_NOT_YET to "Adding a wallet and editing the opening balance aren't available in this version yet.",
    TextKey.WADD_ERR_BANK to "Choose the bank.",
    TextKey.WADD_ERR_WALLET to "Choose the wallet.",
    TextKey.WADD_ERR_NAME to "Write its name.",
    TextKey.WADD_ERR_DUP to "You already have a wallet with this name — give it a different one.",
    TextKey.WADD_ERR_LAST4 to "Write 4 digits, or leave it empty.",
    TextKey.WADD_ERR_AMOUNT to "Write the amount in digits, e.g. 1250.50",
    TextKey.WADD_ERR_AMOUNT_REQUIRED to "Write the opening balance.",
    TextKey.WADD_ERR_DATE to "The date can't be after today.",
    TextKey.WADD_ERR_UNCHANGED to "Nothing changed — edit the amount or the date.",
    TextKey.WADD_ERR_SUMMARY to "Complete what's missing above.",
    TextKey.WADD_SAVE to "Add it",
    TextKey.WADD_SAVE_OPENING to "Save opening balance",
    TextKey.WADD_UNCHANGED to "Nothing changed",
    TextKey.WADD_ADDED to "“{0}” added",
    TextKey.WADD_OPENING_SAVED to "Opening balance saved",
)
