package app.masroufy.core

/**
 * رسايل حالات الاستخدام (app) والجهاز (device) وطبقة فايربيز اللي كانت مكتوبة جوه الكود — اتنقلت للجدول عشان تتعرض
 * بالفصحى في السعودية (OVERRIDES §66). **المصري = نفس النص اللي كان في الكود بالحرف** (اتنقل ببرنامج من سطور الكود نفسها،
 * وملفات المرجع بتتأكد)، والفصحى ترجمة Claude. الإنجليزي في `TextsUseCasesEnglish.kt` (حد الـ300 سطر).
 * **اللي فضل في الكود عن قصد:** لغة البيانات (كلمات رسايل البنك · عناوين الأعمدة · أسماء بتتخزن زي «بلا اسم» و«نص ملصق») ·
 * رسايل المطور (سلامة ملفات المراجع · حالات داخلية مستحيلة · مستودعات الاختبار).
 */
internal val EGYPTIAN_USECASE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.TXN_AMOUNT_POSITIVE to "المبلغ لازم يكون أكبر من صفر. الاتجاه بيتحدد من نوع العملية.",
    TextKey.TXN_AMOUNT_LABEL to "مبلغ العملية",
    TextKey.TXN_DATE_INVALID to "التاريخ مش صالح",
    TextKey.TXN_WALLET_REQUIRED to "اختار محفظة موجودة",
    TextKey.TXN_KIND_REQUIRED to "لازم تحدد نوع العملية — انت عارف اشتريت ولا حوّلت",
    TextKey.TXN_KIND_DIRECTION to "النوع ده ما يتوافقش مع اتجاه الحركة",
    TextKey.TXN_TRANSFER_TARGET_REQUIRED to "التحويل الداخلي لازم تحدد راح لأنهي محفظة",
    TextKey.TXN_TRANSFER_SAME_WALLET to "مينفعش تحوّل من محفظة لنفسها",
    TextKey.TXN_TRANSFER_TARGET_MISSING to "المحفظة المستقبِلة مش موجودة",
    TextKey.TXN_TRANSFER_CURRENCY to "التحويل بين عملتين مختلفتين محتاج سعر صرف موثّق — لسه مش مدعوم (spec/02)",
    TextKey.TXN_TRANSFER_TARGET_ONLY_INTERNAL to "المحفظة المستقبِلة تتحدد للتحويل الداخلي بس",
    TextKey.TXN_MERCHANT_TOO_LONG to "اسم المتجر أطول من 120 حرف",
    TextKey.LOCK_CANCELLED to "اتلغى التأكيد — ما اتغيّرش حاجة.",
    TextKey.LOCK_FAILED to "ما اتأكدش إنك صاحب الجوال — ما اتغيّرش حاجة.",
    TextKey.LOCK_UNAVAILABLE to "الجوال مالوش قفل شاشة ولا بصمة متسجلة. اعمل قفل شاشة من إعدادات الجوال الأول.",
    TextKey.LOCK_NOT_ANDROID to "القفل بالبصمة متاح في تطبيق أندرويد بس.",
    TextKey.LOCK_NO_HARDWARE to "الجوال ده مافيهوش بصمة ولا قفل مدعوم.",
    TextKey.LOCK_HW_UNAVAILABLE to "حساس البصمة مش متاح دلوقتي. جرّب تاني بعد شوية.",
    TextKey.LOCK_SECURITY_UPDATE to "الجوال محتاج تحديث أمان قبل ما يسمح بالبصمة.",
    TextKey.LOCK_CONFIRM_ENABLE to "أكّد علشان تشغّل قفل مصروفي",
    TextKey.LOCK_CONFIRM_DISABLE to "أكّد علشان توقف قفل مصروفي",
    TextKey.LOCK_UNLOCK_TITLE to "افتح مصروفي",
    TextKey.LOCK_UNLOCK_SUBTITLE to "بالبصمة أو برمز الجوال",
    TextKey.TXN_NOT_FOUND to "العملية دي مش موجودة",
    TextKey.CATEGORY_THIS_NOT_FOUND to "التصنيف ده مش موجود",
    TextKey.NOTE_TOO_LONG to "الملاحظة أطول من {0} حرف",
    TextKey.TAG_NAME_REQUIRED to "اكتب اسم الوسم",
    TextKey.TAG_NAME_TOO_LONG to "اسم الوسم أطول من {0} حرف",
    TextKey.BACKUP_TOO_LARGE to "النسخة أكبر من الحد المدعوم (40 ميجابايت)",
    TextKey.BACKUP_NOT_JSON to "الملف مش JSON صالح",
    TextKey.BACKUP_NEEDS_V2 to "اختر نسخة شاملة بإصدار 2؛ للنسخ القديمة استخدم استعادة النسخة القديمة",
    TextKey.BACKUP_COUNT_MISMATCH to "عدد السجلات غير مطابق: {0}",
    TextKey.BACKUP_CHECKSUM_MISMATCH to "بصمة سلامة النسخة غير مطابقة؛ الملف اتغير أو اتلف",
    TextKey.BACKUP_NOTE_KEEP_EXISTING to "الموجود يفضل كما هو. روابط العمليات المتكررة تُنقل لمعرّفات العمليات الموجودة.",
    TextKey.BACKUP_NOTE_PROFILE to "ملف الحساب (الاسم والمرتب ويوم الراتب) بيتضاف بس لو الحساب مالوش ملف — ما بيتكتبش فوق الموجود.",
    TextKey.BACKUP_NOTE_BATCHES to "الاستعادة على دفعات: لو الاتصال انقطع قد يُحفظ جزء؛ أعد نفس النسخة لاستكمال الناقص دون الكتابة فوق الموجود. تجنب التعديل من جهاز آخر أثناء النسخ والاستعادة.",
    TextKey.BACKUP_NOTE_SCOPE to "النسخة تشمل بيانات الحساب؛ أذونات الهاتف ورسائل المراجعة المحلية وإعدادات المظهر لا تُستعاد منها.",
    TextKey.BACKUP_NEEDS_SPACES to "النسخة دي فيها بلاد تانية — الاستعادة محتاجة مكان البلاد",
    TextKey.IMPORT_SAME_REFERENCE_IN_FILE to "نفس المرجع «{0}» اتكرر في الملف ده نفسه (صف {1})",
    TextKey.IMPORT_ROW_CONFLICT to "الصف {0} فيه تعارض ولازم تحسمه الأول. {1}",
    TextKey.IMPORT_COMMIT_RUNNING to "فيه استيراد بيتحفظ حاليًا؛ استنى اكتماله",
    TextKey.IMPORT_DATA_CHANGED to "بيانات الاستيراد اتغيرت؛ اعمل معاينة جديدة",
    TextKey.IMPORT_CHANGED_AFTER_PREVIEW to "فيه بيانات اتغيرت بعد المعاينة؛ اعمل معاينة جديدة علشان نمنع التكرار",
    TextKey.IMPORT_LINE_NOT_ADDABLE to "العملية المكررة أو غير الصالحة مش قابلة للإضافة",
    TextKey.ASSET_FIELD_NOT_DATE to "{0} مش تاريخ صالح",
    TextKey.ASSET_FIELD_NEGATIVE to "{0} لا يكون سالبًا",
    TextKey.ASSET_FIELD_POSITIVE to "{0} لازم يكون أكبر من صفر",
    TextKey.ASSET_QUANTITY_POSITIVE to "الكمية لازم تكون أكبر من صفر",
    TextKey.ASSET_NOT_FOUND to "الأصل ده مش موجود",
    TextKey.ASSET_NAME_REQUIRED to "اكتب اسم الأصل",
    TextKey.ASSET_NAME_DUPLICATE to "فيه أصل اسمه «{0}» موجود قبل كده",
    TextKey.ASSET_LABEL_PURCHASE_DATE to "تاريخ الشراء",
    TextKey.ASSET_LABEL_PURCHASE_VALUE to "قيمة الشراء",
    TextKey.ASSET_LABEL_FEES to "الرسوم",
    TextKey.ASSET_LABEL_SALE_DATE to "تاريخ البيع",
    TextKey.ASSET_LABEL_PROCEEDS to "حصيلة البيع",
    TextKey.ASSET_FEES_OVER_PROCEEDS to "الرسوم ({0}) أكبر من الحصيلة ({1})",
    TextKey.ASSET_LABEL_PRICE to "السعر",
    TextKey.ASSET_LABEL_PRICE_DATE to "تاريخ السعر",
    TextKey.PERSON_NAME_REQUIRED to "اكتب اسم الشخص",
    TextKey.PERSON_NAME_DUPLICATE to "فيه شخص اسمه «{0}» موجود قبل كده",
    TextKey.PERSON_NOT_FOUND to "الشخص ده مش موجود",
    TextKey.AMOUNT_POSITIVE to "المبلغ لازم يكون أكبر من صفر",
    TextKey.SETTLEMENT_REQUEST_ID_INVALID to "معرّف طلب التسوية غير سليم",
    TextKey.RECURRING_NOT_FOUND to "الالتزام مش موجود. حدّث الصفحة.",
    TextKey.RECURRING_DUPLICATE to "الخدمة دي مسجلة بالفعل بنفس العملة. عدّلها من قائمتك.",
    TextKey.CATEGORY_DELETED to "تصنيف محذوف",
    TextKey.RULE_TEXT_REQUIRED to "اكتب النص اللي القاعدة تدوّر عليه",
    TextKey.TEXT_TOO_LONG to "النص أطول من {0} حرف",
    TextKey.RULE_DUPLICATE to "فيه قاعدة بنفس النص «{0}» ونفس طريقة المطابقة",
    TextKey.RULE_NOT_FOUND to "القاعدة دي مش موجودة",
    TextKey.RULE_TEXT_EMPTY to "نص القاعدة مايبقاش فاضي",
    TextKey.MERCHANT_NOT_FOUND to "التاجر ده مش موجود",
    TextKey.MERCHANT_NAME_REQUIRED to "اكتب اسم التاجر",
    TextKey.MERCHANT_ALIAS_LENGTH to "اكتب اسمًا بحد أقصى ١٢٠ حرف.",
    TextKey.MERCHANT_PICK_EXISTING to "اختار تاجرًا موجودًا.",
    TextKey.MERCHANT_ALIAS_TAKEN to "الاسم مربوط بتاجر تاني بالفعل؛ مش هنغيّر الربط القديم ضمنيًا.",
    TextKey.SMS_SENDER_REQUIRED_MANY to "اكتب اسم مرسل البنك كما يظهر في الرسائل (حتى 10 أسماء)",
    TextKey.ONBOARD_CASH_INVALID to "مبلغ الكاش لازم يكون رقم مش سالب",
    TextKey.ONBOARD_DEBT_NAME_REQUIRED to "اكتب اسم كل شخص",
    TextKey.ONBOARD_DEBT_AMOUNT to "مبلغ دين «{0}» لازم يكون أكبر من صفر",
    TextKey.ONBOARD_NO_CASH_WALLET to "مفيش محفظة كاش في الحساب",
    TextKey.SMS_PERIOD_INVALID to "اختار فترة صحيحة",
    TextKey.SMS_PERIOD_TOO_LONG to "اختار سنة واحدة بحد أقصى",
    TextKey.SMS_SENDER_REQUIRED to "اكتب اسم مرسل البنك كما يظهر في الرسائل",
    TextKey.PDF_NO_TRANSACTIONS to "قرينا {0} صفحة بس ملقيناش أي عملية. القارئ بيعرف كشف مصرف الراجحي وكشف QNB مصر بس — لو ده كشف بنك تاني، مش هينفع دلوقتي.",
    TextKey.WALLET_NOT_FOUND_ID to "محفظة غير موجودة: {0}",
    TextKey.RECONCILE_INCOMING_PREFIX to "وارد تحويل — ",
    TextKey.BATCH_NOT_FOUND to "دفعة غير موجودة: {0}",
    TextKey.BATCH_NOT_STAGED to "الدفعة دي حالتها «{0}» مش «staged». التنظيف بيشتغل على المعلّق بس.",
    TextKey.REVERT_BLOCKED to "مقدرناش نلاقي عمليات الاستيراد ده. غالبًا معرّفاته اتحفظت ناقصة في نسخة قديمة. من الإعدادات دوس «افحص البيانات القديمة» وصلّح، وبعدين جرّب التراجع تاني.",
    TextKey.BATCH_ALREADY_REVERTED to "الدفعة دي متراجَع عنها قبل كده",
    TextKey.REVERT_KEPT_SETTLEMENT to "العملية دي دخلت عليها تسوية بعد الاستيراد، فمش هتتحذف",
    TextKey.REVERT_KEPT_ALLOCATION to "العملية دي متربطة بشخص (تخصيص أو التزام)، فمش هتتحذف",
    TextKey.REVERT_KEPT_OTHER_SOURCE to "العملية دي ليها مصدر تاني غير الدفعة دي (رسالة مثلًا)، فمش هتتحذف",
    TextKey.REVERT_DELETED to "الدفعة دي هي المصدر الوحيد ومفيش عليها تسويات",
    TextKey.REVIEW_RANGE to "اختار نطاق صحيح لا يزيد عن خمس سنين.",
    TextKey.REVIEW_CHANGED to "العمليات أو القواعد اتغيرت بعد المعاينة. اعرض المعاينة من جديد.",
    TextKey.REVIEW_KIND_NOT_BULK to "الديون والتحويلات تحتاج ربط الشخص أو المحفظة لكل عملية.",
    TextKey.REVIEW_PICK_ROWS to "اختار عمليات للمراجعة.",
    TextKey.REVIEW_SAME_GROUP to "المجموعة لازم تكون لنفس الاسم والعملة والاتجاه.",
    TextKey.REVIEW_KIND_DIRECTION to "النوع لا يطابق اتجاه الحركة.",
    TextKey.SEED_WALLETS_EXIST to "المحافظ موجودة قبل كده. مش هنكتب فوق تعديلاتك.",
    TextKey.SEED_WALLETS_DONE to "اتزرعت محفظتان برصيد صفر — عدّل الرصيد الافتتاحي من الإعدادات.",
    TextKey.SEED_REFS_EXIST to "المراجع متزروعة قبل كده. مش هنكتب فوق تعديلاتك.",
    TextKey.SEED_REFS_DONE to "اكتمل تجهيز التصنيفات والقواعد والتجار كمرجع أولي تقدر تعدّله.",
    TextKey.BUDGET_THRESHOLD_RANGE to "عتبة التنبيه لازم تكون رقم صحيح بين 1 و100",
    TextKey.BUDGET_NOTHING_TO_COPY to "مفيش ميزانية للفترة {0} تتنسخ",
    TextKey.TXN_NOT_FOUND_ID to "عملية غير موجودة: {0}",
    TextKey.DIRECTION_IN_WORD to "وارد",
    TextKey.DIRECTION_OUT_WORD to "صادر",
    TextKey.KIND_DIRECTION_OBSERVED to "النوع ده ما يتوافقش مع اتجاه الحركة. الكشف بيقول العملية دي «{0}».",
    TextKey.PRICE_SYMBOL_MISSING to "الرمز «{0}» مش موجود في ملف الأسعار النهارده",
    TextKey.BACKUP_SAVED_PARTIAL to "النسخة الاحتياطية اتحفظت ناقصة ({0} من {1} بايت) — ما اتلمسش ولا مستند",
    TextKey.SETTLEMENT_CHANGED_DURING_SAVE to "التسويات اتغيرت أثناء الحفظ. جرّب تاني بنفس الطلب",
    TextKey.SETTLEMENT_STATE_INVALID to "حالة التسويات غير سليمة وتحتاج مراجعة",
    TextKey.MONEY_OUT_OF_SAFE_RANGE to "المبلغ خارج المدى الآمن",
    TextKey.FILE_EMPTY to "الملف فاضي.",
    TextKey.FILE_IS_PDF to "ده ملف PDF — بنقراه بقارئ مختلف عن الـCSV.",
    TextKey.SMS_READ_ARGS to "اختار فترة لا تتجاوز سنة واسم مرسل البنك",
    TextKey.SMS_PERMISSION_MISSING to "إذن قراءة الرسائل مش متاح. تقدر تلصق رسالة واحدة بدل القراءة.",
    TextKey.SMS_PERMISSION_REVOKED to "إذن الرسائل اتسحب. راجع أذونات التطبيق أو استخدم اللصق.",
    TextKey.SMS_INBOX_PERMISSION_REVOKED to "إذن الرسائل اتسحب. راجع أذونات أندرويد؛ الرسائل المعلقة محفوظة.",
    TextKey.SMS_SENDERS_REQUIRED to "اكتب أسماء مرسلي البنك (حتى 10)",
    TextKey.SMS_INBOX_PERMISSION_MISSING to "إذن الرسائل غير متاح. فعّله من أذونات أندرويد أو استخدم اللصق.",
    TextKey.FILE_NAME_INVALID to "اسم الملف أو محتواه غير صالح",
    TextKey.BACKUP_DEVICE_SAVE_FAILED to "تعذر حفظ النسخة على الجهاز",
    TextKey.PDF_PASSWORD to "الملف محمي بكلمة سر — افتحه واحفظه من غير كلمة سر وجرّب تاني",
    TextKey.PDF_INVALID to "الملف ده مش PDF أو تالف",
    TextKey.FILE_NOT_TEXT to "الملف ده مش ملف نصي{0}. المتوقع ملف CSV — يعني نص فيه أعمدة مفصولة بفواصل.",
)

internal val MSA_USECASE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.TXN_AMOUNT_POSITIVE to "يجب أن يكون المبلغ أكبر من صفر. الاتجاه يُحدَّد من نوع العملية.",
    TextKey.TXN_AMOUNT_LABEL to "مبلغ العملية",
    TextKey.TXN_DATE_INVALID to "التاريخ غير صالح",
    TextKey.TXN_WALLET_REQUIRED to "اختر محفظة موجودة",
    TextKey.TXN_KIND_REQUIRED to "حدّد نوع العملية — شراء أم تحويل",
    TextKey.TXN_KIND_DIRECTION to "هذا النوع لا يتوافق مع اتجاه الحركة",
    TextKey.TXN_TRANSFER_TARGET_REQUIRED to "حدّد المحفظة المستقبِلة للتحويل الداخلي",
    TextKey.TXN_TRANSFER_SAME_WALLET to "لا يمكن التحويل من محفظة إلى نفسها",
    TextKey.TXN_TRANSFER_TARGET_MISSING to "المحفظة المستقبِلة غير موجودة",
    TextKey.TXN_TRANSFER_CURRENCY to "التحويل بين عملتين يحتاج سعر صرف موثّقًا — غير مدعوم بعد (spec/02)",
    TextKey.TXN_TRANSFER_TARGET_ONLY_INTERNAL to "المحفظة المستقبِلة للتحويل الداخلي فقط",
    TextKey.TXN_MERCHANT_TOO_LONG to "اسم المتجر أطول من 120 حرفًا",
    TextKey.LOCK_CANCELLED to "أُلغي التأكيد — لم يتغير شيء.",
    TextKey.LOCK_FAILED to "تعذّر التحقق من أنك صاحب الجوال — لم يتغير شيء.",
    TextKey.LOCK_UNAVAILABLE to "لا قفل شاشة ولا بصمة مسجلة في الجوال. فعّل قفل الشاشة من إعدادات الجوال أولًا.",
    TextKey.LOCK_NOT_ANDROID to "القفل بالبصمة متاح في تطبيق أندرويد فقط.",
    TextKey.LOCK_NO_HARDWARE to "لا بصمة ولا قفل مدعوم في هذا الجوال.",
    TextKey.LOCK_HW_UNAVAILABLE to "مستشعر البصمة غير متاح الآن. أعد المحاولة بعد قليل.",
    TextKey.LOCK_SECURITY_UPDATE to "يحتاج الجوال تحديث أمان قبل السماح بالبصمة.",
    TextKey.LOCK_CONFIRM_ENABLE to "أكّد لتفعيل قفل مصروفي",
    TextKey.LOCK_CONFIRM_DISABLE to "أكّد لإيقاف قفل مصروفي",
    TextKey.LOCK_UNLOCK_TITLE to "افتح مصروفي",
    TextKey.LOCK_UNLOCK_SUBTITLE to "بالبصمة أو برمز الجوال",
    TextKey.TXN_NOT_FOUND to "هذه العملية غير موجودة",
    TextKey.CATEGORY_THIS_NOT_FOUND to "هذا التصنيف غير موجود",
    TextKey.NOTE_TOO_LONG to "الملاحظة أطول من {0} حرف",
    TextKey.TAG_NAME_REQUIRED to "أدخل اسم الوسم",
    TextKey.TAG_NAME_TOO_LONG to "اسم الوسم أطول من {0} حرفًا",
    TextKey.BACKUP_TOO_LARGE to "النسخة أكبر من الحد المدعوم (40 ميجابايت)",
    TextKey.BACKUP_NOT_JSON to "الملف ليس JSON صالحًا",
    TextKey.BACKUP_NEEDS_V2 to "اختر نسخة شاملة بالإصدار 2؛ وللنسخ القديمة استخدم استعادة النسخة القديمة",
    TextKey.BACKUP_COUNT_MISMATCH to "عدد السجلات غير مطابق: {0}",
    TextKey.BACKUP_CHECKSUM_MISMATCH to "بصمة سلامة النسخة غير مطابقة؛ الملف تغيّر أو تلف",
    TextKey.BACKUP_NOTE_KEEP_EXISTING to "يبقى الموجود كما هو. وتُنقل روابط العمليات المكررة إلى معرّفات العمليات الموجودة.",
    TextKey.BACKUP_NOTE_PROFILE to "ملف الحساب (الاسم والراتب ويوم الراتب) يُضاف فقط إن لم يكن للحساب ملف — دون الكتابة فوق الموجود.",
    TextKey.BACKUP_NOTE_BATCHES to "الاستعادة على دفعات: إن انقطع الاتصال فقد يُحفظ جزء؛ أعد النسخة نفسها لإكمال الناقص دون الكتابة فوق الموجود. تجنّب التعديل من جهاز آخر أثناء النسخ والاستعادة.",
    TextKey.BACKUP_NOTE_SCOPE to "النسخة تشمل بيانات الحساب؛ أذونات الجوال ورسائل المراجعة المحلية وإعدادات المظهر لا تُستعاد منها.",
    TextKey.BACKUP_NEEDS_SPACES to "هذه النسخة تضم بلدانًا أخرى — الاستعادة تحتاج مكان البلدان",
    TextKey.IMPORT_SAME_REFERENCE_IN_FILE to "تكرر المرجع «{0}» في الملف نفسه (الصف {1})",
    TextKey.IMPORT_ROW_CONFLICT to "في الصف {0} تعارض يجب حسمه أولًا. {1}",
    TextKey.IMPORT_COMMIT_RUNNING to "يوجد استيراد قيد الحفظ؛ انتظر اكتماله",
    TextKey.IMPORT_DATA_CHANGED to "تغيّرت بيانات الاستيراد؛ أعد المعاينة",
    TextKey.IMPORT_CHANGED_AFTER_PREVIEW to "تغيّرت بيانات بعد المعاينة؛ أعد المعاينة لمنع التكرار",
    TextKey.IMPORT_LINE_NOT_ADDABLE to "العملية المكررة أو غير الصالحة لا تُضاف",
    TextKey.ASSET_FIELD_NOT_DATE to "{0}: تاريخ غير صالح",
    TextKey.ASSET_FIELD_NEGATIVE to "{0}: لا يكون سالبًا",
    TextKey.ASSET_FIELD_POSITIVE to "{0}: يجب أن يكون أكبر من صفر",
    TextKey.ASSET_QUANTITY_POSITIVE to "يجب أن تكون الكمية أكبر من صفر",
    TextKey.ASSET_NOT_FOUND to "هذا الأصل غير موجود",
    TextKey.ASSET_NAME_REQUIRED to "أدخل اسم الأصل",
    TextKey.ASSET_NAME_DUPLICATE to "يوجد أصل باسم «{0}» سابقًا",
    TextKey.ASSET_LABEL_PURCHASE_DATE to "تاريخ الشراء",
    TextKey.ASSET_LABEL_PURCHASE_VALUE to "قيمة الشراء",
    TextKey.ASSET_LABEL_FEES to "الرسوم",
    TextKey.ASSET_LABEL_SALE_DATE to "تاريخ البيع",
    TextKey.ASSET_LABEL_PROCEEDS to "حصيلة البيع",
    TextKey.ASSET_FEES_OVER_PROCEEDS to "الرسوم ({0}) أكبر من الحصيلة ({1})",
    TextKey.ASSET_LABEL_PRICE to "السعر",
    TextKey.ASSET_LABEL_PRICE_DATE to "تاريخ السعر",
    TextKey.PERSON_NAME_REQUIRED to "أدخل اسم الشخص",
    TextKey.PERSON_NAME_DUPLICATE to "يوجد شخص باسم «{0}» سابقًا",
    TextKey.PERSON_NOT_FOUND to "هذا الشخص غير موجود",
    TextKey.AMOUNT_POSITIVE to "يجب أن يكون المبلغ أكبر من صفر",
    TextKey.SETTLEMENT_REQUEST_ID_INVALID to "معرّف طلب التسوية غير سليم",
    TextKey.RECURRING_NOT_FOUND to "الالتزام غير موجود. حدّث الصفحة.",
    TextKey.RECURRING_DUPLICATE to "هذه الخدمة مسجلة بالعملة نفسها. عدّلها من قائمتك.",
    TextKey.CATEGORY_DELETED to "تصنيف محذوف",
    TextKey.RULE_TEXT_REQUIRED to "أدخل النص الذي تبحث عنه القاعدة",
    TextKey.TEXT_TOO_LONG to "النص أطول من {0} حرفًا",
    TextKey.RULE_DUPLICATE to "توجد قاعدة بالنص «{0}» وطريقة المطابقة نفسها",
    TextKey.RULE_NOT_FOUND to "هذه القاعدة غير موجودة",
    TextKey.RULE_TEXT_EMPTY to "لا يكون نص القاعدة فارغًا",
    TextKey.MERCHANT_NOT_FOUND to "هذا التاجر غير موجود",
    TextKey.MERCHANT_NAME_REQUIRED to "أدخل اسم التاجر",
    TextKey.MERCHANT_ALIAS_LENGTH to "أدخل اسمًا لا يتجاوز ١٢٠ حرفًا.",
    TextKey.MERCHANT_PICK_EXISTING to "اختر تاجرًا موجودًا.",
    TextKey.MERCHANT_ALIAS_TAKEN to "الاسم مربوط بتاجر آخر؛ لن نغيّر الربط القديم ضمنيًا.",
    TextKey.SMS_SENDER_REQUIRED_MANY to "أدخل اسم مرسل البنك كما يظهر في الرسائل (حتى 10 أسماء)",
    TextKey.ONBOARD_CASH_INVALID to "يجب أن يكون مبلغ الكاش رقمًا غير سالب",
    TextKey.ONBOARD_DEBT_NAME_REQUIRED to "أدخل اسم كل شخص",
    TextKey.ONBOARD_DEBT_AMOUNT to "يجب أن يكون مبلغ دين «{0}» أكبر من صفر",
    TextKey.ONBOARD_NO_CASH_WALLET to "لا توجد محفظة كاش في الحساب",
    TextKey.SMS_PERIOD_INVALID to "اختر فترة صحيحة",
    TextKey.SMS_PERIOD_TOO_LONG to "اختر سنة واحدة كحد أقصى",
    TextKey.SMS_SENDER_REQUIRED to "أدخل اسم مرسل البنك كما يظهر في الرسائل",
    TextKey.PDF_NO_TRANSACTIONS to "قرأنا {0} صفحة دون أي عملية. القارئ يدعم كشف مصرف الراجحي وكشف QNB مصر فقط — كشوف البنوك الأخرى غير مدعومة الآن.",
    TextKey.WALLET_NOT_FOUND_ID to "محفظة غير موجودة: {0}",
    TextKey.RECONCILE_INCOMING_PREFIX to "وارد تحويل — ",
    TextKey.BATCH_NOT_FOUND to "دفعة غير موجودة: {0}",
    TextKey.BATCH_NOT_STAGED to "حالة هذه الدفعة «{0}» لا «staged». التنظيف للمعلّق فقط.",
    TextKey.REVERT_BLOCKED to "تعذّر إيجاد عمليات هذا الاستيراد؛ غالبًا حُفظت معرّفاته ناقصة في نسخة قديمة. من الإعدادات اضغط «افحص البيانات القديمة» وأصلحها، ثم أعد محاولة التراجع.",
    TextKey.BATCH_ALREADY_REVERTED to "تم التراجع عن هذه الدفعة سابقًا",
    TextKey.REVERT_KEPT_SETTLEMENT to "سُجّلت على هذه العملية تسوية بعد الاستيراد، فلن تُحذف",
    TextKey.REVERT_KEPT_ALLOCATION to "هذه العملية مرتبطة بشخص (تخصيص أو التزام)، فلن تُحذف",
    TextKey.REVERT_KEPT_OTHER_SOURCE to "لهذه العملية مصدر آخر غير هذه الدفعة (رسالة مثلًا)، فلن تُحذف",
    TextKey.REVERT_DELETED to "هذه الدفعة مصدرها الوحيد ولا تسويات عليها",
    TextKey.REVIEW_RANGE to "اختر نطاقًا صحيحًا لا يتجاوز خمس سنوات.",
    TextKey.REVIEW_CHANGED to "تغيّرت العمليات أو القواعد بعد المعاينة. اعرض المعاينة مجددًا.",
    TextKey.REVIEW_KIND_NOT_BULK to "الديون والتحويلات تحتاج ربط الشخص أو المحفظة لكل عملية.",
    TextKey.REVIEW_PICK_ROWS to "اختر عمليات للمراجعة.",
    TextKey.REVIEW_SAME_GROUP to "يجب أن تكون المجموعة للاسم والعملة والاتجاه نفسها.",
    TextKey.REVIEW_KIND_DIRECTION to "النوع لا يطابق اتجاه الحركة.",
    TextKey.SEED_WALLETS_EXIST to "المحافظ موجودة سابقًا. لن نكتب فوق تعديلاتك.",
    TextKey.SEED_WALLETS_DONE to "أُنشئت محفظتان برصيد صفر — عدّل الرصيد الافتتاحي من الإعدادات.",
    TextKey.SEED_REFS_EXIST to "المراجع مُجهّزة سابقًا. لن نكتب فوق تعديلاتك.",
    TextKey.SEED_REFS_DONE to "اكتمل تجهيز التصنيفات والقواعد والتجار مرجعًا أوليًا قابلًا للتعديل.",
    TextKey.BUDGET_THRESHOLD_RANGE to "يجب أن تكون نسبة التنبيه عددًا صحيحًا بين 1 و100",
    TextKey.BUDGET_NOTHING_TO_COPY to "لا ميزانية للفترة {0} لنسخها",
    TextKey.TXN_NOT_FOUND_ID to "عملية غير موجودة: {0}",
    TextKey.DIRECTION_IN_WORD to "وارد",
    TextKey.DIRECTION_OUT_WORD to "صادر",
    TextKey.KIND_DIRECTION_OBSERVED to "هذا النوع لا يتوافق مع اتجاه الحركة. الكشف يقول إن العملية «{0}».",
    TextKey.PRICE_SYMBOL_MISSING to "الرمز «{0}» غير موجود في ملف أسعار اليوم",
    TextKey.BACKUP_SAVED_PARTIAL to "حُفظت النسخة الاحتياطية ناقصة ({0} من {1} بايت) — لم يُمس أي مستند",
    TextKey.SETTLEMENT_CHANGED_DURING_SAVE to "تغيّرت التسويات أثناء الحفظ. أعد المحاولة بالطلب نفسه",
    TextKey.SETTLEMENT_STATE_INVALID to "حالة التسويات غير سليمة وتحتاج مراجعة",
    TextKey.MONEY_OUT_OF_SAFE_RANGE to "المبلغ خارج المدى الآمن",
    TextKey.FILE_EMPTY to "الملف فارغ.",
    TextKey.FILE_IS_PDF to "هذا ملف PDF — يُقرأ بقارئ غير قارئ CSV.",
    TextKey.SMS_READ_ARGS to "اختر فترة لا تتجاوز سنة واسم مرسل البنك",
    TextKey.SMS_PERMISSION_MISSING to "إذن قراءة الرسائل غير متاح. يمكنك لصق رسالة واحدة بدل القراءة.",
    TextKey.SMS_PERMISSION_REVOKED to "سُحب إذن الرسائل. راجع أذونات التطبيق أو استخدم اللصق.",
    TextKey.SMS_INBOX_PERMISSION_REVOKED to "سُحب إذن الرسائل. راجع أذونات أندرويد؛ الرسائل المعلّقة محفوظة.",
    TextKey.SMS_SENDERS_REQUIRED to "أدخل أسماء مرسلي البنك (حتى 10)",
    TextKey.SMS_INBOX_PERMISSION_MISSING to "إذن الرسائل غير متاح. فعّله من أذونات أندرويد أو استخدم اللصق.",
    TextKey.FILE_NAME_INVALID to "اسم الملف أو محتواه غير صالح",
    TextKey.BACKUP_DEVICE_SAVE_FAILED to "تعذّر حفظ النسخة على الجهاز",
    TextKey.PDF_PASSWORD to "الملف محمي بكلمة مرور — افتحه واحفظه دون كلمة مرور ثم أعد المحاولة",
    TextKey.PDF_INVALID to "هذا الملف ليس PDF أو تالف",
    TextKey.FILE_NOT_TEXT to "هذا ليس ملفًا نصيًا{0}. المتوقع ملف CSV — أي نص بأعمدة مفصولة بفواصل.",
)
