package app.masroufy.core

/**
 * «العمليات» بالفصحى (للسعودية والافتراضي — OVERRIDES §66) — الجزء الأول: القايمة · القايمة السائلة · التفاصيل · التصنيف · الوسوم · التصفية.
 * النص من النموذج التفاعلي (`space = السعودية`) بالحرف قدر الإمكان. **ممنوع «·» جنب رقم عربي** ⇒ «،».
 */
internal val MSA_OPERATIONS_LIST_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.OPERATIONS_FILTER to "تصفية العمليات",
    UiKey.OPERATIONS_PERIOD to "الشهر",
    UiKey.OPERATIONS_TAB_OPS to "العمليات",
    UiKey.OPERATIONS_TAB_BUDGETS to "الميزانيات",
    UiKey.OPERATIONS_TAB_DUES to "المستحقات",
    UiKey.OPERATIONS_ERROR_TITLE to "تعذّر تحميل العمليات",
    UiKey.OPERATIONS_ERROR_BODY to "تحقق من الاتصال ثم أعد المحاولة.",
    UiKey.OPERATIONS_EMPTY_TITLE to "لا توجد عمليات في {0}",
    UiKey.OPERATIONS_EMPTY_BODY to "أضف عملية أو استورد كشف حسابك.",
    UiKey.OPERATIONS_INCOME to "دخل الشهر",
    UiKey.OPERATIONS_EXPENSE to "المصروف الحقيقي",
    UiKey.OPERATIONS_APPROX_NOTE to "بعض الأنواع تقديرية حتى تؤكدها.",
    UiKey.OPERATIONS_TODAY to "اليوم",
    UiKey.OPERATIONS_YESTERDAY to "أمس",
    UiKey.OPERATIONS_ROW_MOVE to "{0}، {1} ← {2}",
    UiKey.OPERATIONS_ROW_ACCOUNT to "حساب ينتهي بـ {0}",
    UiKey.OPERATIONS_ROW_FROM to "من {0}",
    UiKey.OPERATIONS_ROW_TO to "إلى {0}",
    UiKey.OPERATIONS_ROW_UNCLASSIFIED to "بلا تصنيف",
    UiKey.OPERATIONS_ROW_ACTIONS to "إجراءات {0}",
    UiKey.OPERATIONS_UNRECORDED to "غير مسجّلة",
    UiKey.OPERATIONS_COUNT_ONE to "عملية واحدة",
    UiKey.OPERATIONS_COUNT_TWO to "عمليتان",
    UiKey.OPERATIONS_COUNT_FEW to "{0} عمليات",
    UiKey.OPERATIONS_COUNT_MANY to "{0} عملية",
    UiKey.OPERATIONS_SMS_ONE to "رسالة من البنك بانتظار تأكيدك",
    UiKey.OPERATIONS_SMS_TWO to "رسالتان من البنك بانتظار تأكيدك",
    UiKey.OPERATIONS_SMS_FEW to "{0} رسائل من البنك بانتظار تأكيدك",
    UiKey.OPERATIONS_SMS_MANY to "{0} رسالة من البنك بانتظار تأكيدك",
    UiKey.OPERATIONS_BANNER_REVIEW to "{0} نوعها غير مؤكد",
    UiKey.OPERATIONS_PARTIES_ONE to "طرف بانتظار ردك",
    UiKey.OPERATIONS_PARTIES_TWO to "طرفان بانتظار ردك",
    UiKey.OPERATIONS_PARTIES_FEW to "{0} أطراف بانتظار ردك",
    UiKey.OPERATIONS_PARTIES_MANY to "{0} طرفًا بانتظار ردك",
    UiKey.OPERATIONS_SAVE_FAILED to "تعذّر الحفظ — لم يتغير شيء. حاول مرة أخرى.",
    UiKey.OPERATION_MENU_TITLE to "إجراءات العملية",
    UiKey.OPERATION_MENU_DETAIL to "عرض التفاصيل",
    UiKey.OPERATION_MENU_PERSON to "تخصيص مبلغ لشخص",
    UiKey.OPERATION_MENU_ALL to "كل الإجراءات",
    UiKey.OPERATION_DETAIL_TITLE to "تفاصيل العملية",
    UiKey.OPERATION_DETAIL_ERROR_TITLE to "تعذّر تحميل العملية",
    UiKey.OPERATION_DETAIL_SUB to "{0}، {1}",
    UiKey.OPERATION_DETAIL_IN to "دائن",
    UiKey.OPERATION_DETAIL_OUT to "مدين",
    UiKey.OPERATION_DETAIL_MERCHANT to "صفحة التاجر",
    UiKey.OPERATION_DETAIL_LOCK to "التاريخ والاتجاه من المصدر ولا يُعدَّلان",
    UiKey.OPERATION_DETAIL_LOCK_CASH to "المبلغ من فرق العدّ",
    UiKey.OPERATION_DETAIL_CASH_TITLE to "هذه ليست عملية مسجّلة",
    UiKey.OPERATION_DETAIL_CASH_BODY to "هذا فرق عدّ الكاش. يدخل في صرف الشهر بنقطة حمراء حتى تحدد فيمَ صُرف.",
    UiKey.OPERATION_DETAIL_WALLET to "المحفظة",
    UiKey.OPERATION_DETAIL_CATEGORY to "التصنيف",
    UiKey.OPERATION_DETAIL_KIND to "النوع",
    UiKey.OPERATION_DETAIL_KIND_WAITING to "بانتظار تحديد النوع",
    UiKey.OPERATION_DETAIL_WAITING_CHIP to "بانتظارك",
    UiKey.OPERATION_DETAIL_KIND_ESTIMATED to "تقديري حتى تؤكده",
    UiKey.OPERATION_DETAIL_SUGGESTED to "مقترح",
    UiKey.OPERATION_DETAIL_SUGGESTED_HINT to "يحتاج تأكيدك",
    UiKey.OPERATION_DETAIL_CONFIRMED_CHIP to "مؤكد",
    UiKey.OPERATION_DETAIL_CHANGE to "غيّر",
    UiKey.OPERATION_DETAIL_CONFIRM to "تأكيد",
    UiKey.OPERATION_DETAIL_CATEGORIZE to "صنّفها",
    UiKey.OPERATION_DETAIL_CONFIRMED to "تأكّد التصنيف",
    UiKey.OPERATION_DETAIL_REMEMBERED to "تم — «{0}» سيُصنَّف «{1}» دائمًا",
    UiKey.OPERATION_DETAIL_CATEGORIZED to "تم — صُنّفت «{0}»",
    UiKey.OPERATION_DETAIL_LINK_TITLE to "اربطها بـ",
    UiKey.CATEGORY_PICKER_CASH_TITLE to "فيمَ صُرف؟",
    UiKey.CATEGORY_PICKER_TITLE to "تصنيف «{0}»",
    UiKey.CATEGORY_PICKER_EMPTY to "لا تصنيفات بعد.",
    UiKey.TAGS_SHEET_LABEL to "الوسوم",
    UiKey.TAGS_SHEET_NONE to "بلا وسوم",
    UiKey.TAGS_SHEET_ADD_TRIGGER to "أضف وسمًا",
    UiKey.TAGS_SHEET_EDIT to "تعديل",
    UiKey.TAGS_SHEET_TITLE to "وسوم العملية",
    UiKey.TAGS_SHEET_BODY to "الوسم للبحث والتقارير فقط — لا يغيّر المبلغ ولا يُحسب مرتين. والوسوم مشتركة بين البلدان.",
    UiKey.TAGS_SHEET_EMPTY_LINE to "لا وسوم على هذه العملية.",
    UiKey.TAGS_SHEET_INPUT to "وسم جديد أو ابحث",
    UiKey.TAGS_SHEET_ADD to "أضف",
    UiKey.TAGS_SHEET_COUNTER to "{0}/{1}",
    UiKey.TAGS_SHEET_ALL to "وسومك",
    UiKey.TAGS_SHEET_NO_MATCH to "لا وسم بهذا الاسم — «أضف» ينشئه جديدًا.",
    UiKey.TAGS_SHEET_ALL_ON to "كل وسومك على هذه العملية.",
    UiKey.TAGS_SHEET_DONE to "تم",
    UiKey.TAGS_SHEET_REMOVE to "إزالة وسم {0}",
    UiKey.TAGS_SHEET_ADD_ONE to "إضافة وسم {0}",
    UiKey.TAGS_SHEET_ADDED to "أُضيف «{0}»",
    UiKey.TAGS_SHEET_CREATED to "أُنشئ وسم جديد «{0}» وأُضيف",
    UiKey.TAGS_SHEET_ALREADY to "«{0}» موجود على العملية",
    UiKey.TAGS_SHEET_REMOVED to "أُزيل «{0}»",
    UiKey.OPERATION_FILTERS_TITLE to "تصفية العمليات",
    UiKey.OPERATION_FILTERS_RESULTS to "النتائج",
    UiKey.OPERATION_FILTERS_CLEAR to "مسح الكل",
    UiKey.OPERATION_FILTERS_SEARCH to "اسم متجر، شخص، ملاحظة…",
    UiKey.OPERATION_FILTERS_AMOUNT to "المبلغ ({0})",
    UiKey.OPERATION_FILTERS_NEAR to "قريب منه ±5%",
    UiKey.OPERATION_FILTERS_NEAR_CHIP to "≈ {0}",
    UiKey.OPERATION_FILTERS_PERIOD to "الفترة",
    UiKey.OPERATION_FILTERS_THIS to "هذا الشهر",
    UiKey.OPERATION_FILTERS_LAST to "الشهر الماضي",
    UiKey.OPERATION_FILTERS_THREE to "آخر 3 أشهر",
    UiKey.OPERATION_FILTERS_KIND to "النوع",
    UiKey.OPERATION_FILTERS_KIND_OUT to "مصروف",
    UiKey.OPERATION_FILTERS_KIND_IN to "دخل",
    UiKey.OPERATION_FILTERS_KIND_MOVE to "بين محافظك",
    UiKey.OPERATION_FILTERS_KIND_DEBT to "ديون وأقساط",
    UiKey.OPERATION_FILTERS_REVIEW to "المراجعة",
    UiKey.OPERATION_FILTERS_REVIEW_ALL to "الكل",
    UiKey.OPERATION_FILTERS_REVIEW_OK to "مؤكدة",
    UiKey.OPERATION_FILTERS_REVIEW_NEEDS to "تحتاج تأكيد",
    UiKey.OPERATION_FILTERS_QUOTED to "«{0}»",
    UiKey.OPERATION_FILTERS_DROP to "إزالة {0}",
    UiKey.OPERATION_FILTERS_NONE to "لا نتائج",
    UiKey.OPERATION_FILTERS_NONE_BODY to "أزل فلترًا أو أكثر وحاول مجددًا.",
    UiKey.OPERATION_FILTERS_SHOW to "اعرض {0}",
    UiKey.OPERATION_FILTERS_EDIT to "عدّل التصفية",
)
