package app.masroufy.core

/** نصوص [AskKey] — الفصحى (السعودية). الأرقام إنجليزي بس (§79.1). */
internal val MSA_ASK_TEXTS: Map<AskKey, String> = mapOf(
    AskKey.CHAT_CARD_SAVE to "احفظ",
    AskKey.CHAT_CARD_EDIT to "تعديل",
    AskKey.CHAT_CARD_CANCEL to "إلغاء",
    AskKey.CHAT_CARD_DONE to "سُجّلت",
    AskKey.CHAT_CARD_DROPPED to "عُدّلت في الأسفل",
    AskKey.CHAT_CARD_CANCELLED to "أُلغيت",
    AskKey.CHAT_SPLIT_SAVE to "سجّل التقسيم",
    AskKey.CHAT_SIMILAR_TODAY to "توجد عملية مشابهة اليوم",
    AskKey.CHAT_SIMILAR_RECORD to "سجّلها على أي حال",
    AskKey.CHAT_SIMILAR_KEEP to "هي نفسها، اتركها",
    AskKey.CHAT_SIMILAR_KEPT to "حسنًا، تركت العملية المسجّلة كما هي.",
    AskKey.CHAT_SUB_INCOME to "دخل",
    AskKey.CHAT_SUB_LENT to "لك عند {0}",
    AskKey.CHAT_SUB_BORROWED to "عليك لـ{0}",
    AskKey.CHAT_SUB_MOVE to "من {0} إلى {1}",
    AskKey.CHAT_START_CLOSE to "أغلق: {0}",
    AskKey.CHAT_START_CLOSED to "أُغلق الكارت",
    AskKey.CHAT_UNDO to "تراجع",
    AskKey.CHAT_NOTIF_DELETE to "احذف الإشعار: {0}",
    AskKey.CHAT_NOTIF_DELETED to "حُذف الإشعار",
    AskKey.CHAT_HISTORY_TODAY to "اليوم",
    AskKey.CHAT_HISTORY_YESTERDAY to "أمس",
    AskKey.CHAT_HISTORY_THIS_WEEK to "هذا الأسبوع",
    AskKey.CHAT_HISTORY_OLDER to "أقدم",
    AskKey.CHAT_HISTORY_VIEWING to "محادثة من السجل",
    AskKey.CHAT_HISTORY_BACK to "ارجع للمحادثة الحالية",
    AskKey.CHAT_HISTORY_AUTO_DELETE to "تُحذف المحادثات تلقائيًا بعد 3 أشهر.",
    AskKey.CHAT_MEMORY_TITLE to "ما تعلّمته عنك",
    AskKey.CHAT_MEMORY_LEARNING to "التعلّم من أسئلتي",
    AskKey.CHAT_MEMORY_LEARNING_NOTE to "عند الإيقاف لا تظهر اقتراحات من أسئلتك، وتبقى الأسئلة غير المفهومة محفوظة لتعليمي.",
    AskKey.CHAT_MEMORY_EMPTY to "لم أتعلّم شيئًا عنك بعد.",
    AskKey.CHAT_MEMORY_FORGET to "احذف: {0}",
    AskKey.CHAT_MEMORY_CLEAR_ALL to "امسح الكل",
    AskKey.CHAT_MEMORY_CLEAR_TITLE to "مسح كل ما تعلّمته؟",
    AskKey.CHAT_MEMORY_CLEAR_BODY to "تُحذف الموضوعات التي تسأل عنها كثيرًا، ولا يظهر ما أكدته بنفسك إلا إذا تغيّر. بياناتك نفسها لا تُمس.",
    AskKey.CHAT_MEMORY_CLEAR_YES to "امسح",
    AskKey.CHAT_MEMORY_CLEAR_NO to "إلغاء",
    AskKey.CHAT_UNKNOWN_TITLE to "أسئلة لم أفهمها بعد ({0})",
    AskKey.CHAT_UNKNOWN_REMOVE to "احذف السؤال: {0}",
    AskKey.CHAT_UNKNOWN_REMOVED to "حُذف السؤال",
    AskKey.CHAT_UNKNOWN_COPY to "انسخ القائمة",
    AskKey.CHAT_UNKNOWN_COPIED to "نُسخت القائمة",
    AskKey.CHAT_VOICE_UNAVAILABLE to "التعرّف على الكلام غير متاح على هذا الجهاز.",
    AskKey.CHAT_VOICE_FAILED to "لم أسمع شيئًا — جرّب مرة أخرى.",
    AskKey.CHAT_MAIN_BADGE to "الأساسية",
    AskKey.CHAT_MAKE_MAIN to "اجعلها الأساسية",
    AskKey.CHAT_IS_MAIN to "محفظة الصرف الأساسية",
    AskKey.CHAT_MAIN_DONE to "صارت «{0}» الأساسية",
    AskKey.CHAT_EDIT_HOW to "ماذا أعدّل؟ اكتب المبلغ الصحيح، أو «كاش» أو «البنك» لتغيير المحفظة.",
    AskKey.CHAT_CARD_INCOME to "أسجّله دخلًا هكذا؟",
    AskKey.CHAT_CARD_LENT to "أسجّلها سلفة لـ{0}؟ ستظهر في «لك».",
    AskKey.CHAT_CARD_BORROWED to "أسجّلها سلفة من {0}؟ ستظهر في «عليك».",
    AskKey.CHAT_CARD_MOVE to "أسجّله تحويلًا بين محافظك؟ لا يُحسب مصروفًا ولا دخلًا.",
    AskKey.CHAT_NEEDS_PERSON to "لمن السلفة؟ اكتب اسمه كما في «الأشخاص»، مثل: سلفت أحمد 200.",
    AskKey.CHAT_MOVE_NEEDS_WALLETS to "من أي محفظة إلى أي محفظة؟ اكتبها هكذا: حوّلت 500 من الكاش للبنك.",
    AskKey.CHAT_UNTIL_SALARY to "ومعك تقريبًا {0} حتى الراتب ({1}).",
    AskKey.CHAT_INCOME_TITLE to "دخل",
    AskKey.CHAT_LENT_TITLE to "سلفة لـ{0}",
    AskKey.CHAT_BORROWED_TITLE to "سلفة من {0}",
    AskKey.CHAT_MOVE_TITLE to "تحويل بين محافظي",
)

/** نصوص [AskKey] — المصري. */
internal val EGYPTIAN_ASK_TEXTS: Map<AskKey, String> = mapOf(
    AskKey.CHAT_CARD_SAVE to "سجّلها",
    AskKey.CHAT_CARD_EDIT to "عدّل",
    AskKey.CHAT_CARD_CANCEL to "إلغي",
    AskKey.CHAT_CARD_DONE to "اتسجّلت",
    AskKey.CHAT_CARD_DROPPED to "اتعدّلت تحت",
    AskKey.CHAT_CARD_CANCELLED to "اتلغت",
    AskKey.CHAT_SPLIT_SAVE to "سجّل التقسيم",
    AskKey.CHAT_SIMILAR_TODAY to "فيه عملية شبهها النهارده",
    AskKey.CHAT_SIMILAR_RECORD to "سجّلها برضه",
    AskKey.CHAT_SIMILAR_KEEP to "دي هي، سيبها",
    AskKey.CHAT_SIMILAR_KEPT to "تمام، سبت العملية المتسجلة زي ما هي.",
    AskKey.CHAT_SUB_INCOME to "دخل",
    AskKey.CHAT_SUB_LENT to "ليك عند {0}",
    AskKey.CHAT_SUB_BORROWED to "عليك لـ{0}",
    AskKey.CHAT_SUB_MOVE to "من {0} لـ{1}",
    AskKey.CHAT_START_CLOSE to "اقفل: {0}",
    AskKey.CHAT_START_CLOSED to "اتقفل الكارت",
    AskKey.CHAT_UNDO to "رجّعه",
    AskKey.CHAT_NOTIF_DELETE to "امسح الإشعار: {0}",
    AskKey.CHAT_NOTIF_DELETED to "اتمسح الإشعار",
    AskKey.CHAT_HISTORY_TODAY to "النهارده",
    AskKey.CHAT_HISTORY_YESTERDAY to "امبارح",
    AskKey.CHAT_HISTORY_THIS_WEEK to "الأسبوع ده",
    AskKey.CHAT_HISTORY_OLDER to "أقدم",
    AskKey.CHAT_HISTORY_VIEWING to "محادثة من السجل",
    AskKey.CHAT_HISTORY_BACK to "ارجع للمحادثة الحالية",
    AskKey.CHAT_HISTORY_AUTO_DELETE to "المحادثات بتتمسح لوحدها بعد 3 شهور.",
    AskKey.CHAT_MEMORY_TITLE to "اللي اتعلمته عنك",
    AskKey.CHAT_MEMORY_LEARNING to "يتعلّم من أسئلتي",
    AskKey.CHAT_MEMORY_LEARNING_NOTE to "لو قفلته مش هتظهر اقتراحات من أسئلتك، والأسئلة اللي ما اتفهمتش بتفضل تتحفظ عشان أتعلّمها.",
    AskKey.CHAT_MEMORY_EMPTY to "لسه ما اتعلمتش حاجة عنك.",
    AskKey.CHAT_MEMORY_FORGET to "امسح: {0}",
    AskKey.CHAT_MEMORY_CLEAR_ALL to "امسح الكل",
    AskKey.CHAT_MEMORY_CLEAR_TITLE to "تمسح كل اللي اتعلمته؟",
    AskKey.CHAT_MEMORY_CLEAR_BODY to "المواضيع اللي بتسأل عنها كتير هتتمسح، واللي أكدته بنفسك مش هيظهر تاني غير لو اتغير. بياناتك نفسها مش هتتلمس.",
    AskKey.CHAT_MEMORY_CLEAR_YES to "امسح",
    AskKey.CHAT_MEMORY_CLEAR_NO to "لا، سيبه",
    AskKey.CHAT_UNKNOWN_TITLE to "أسئلة ما فهمتهاش لسه ({0})",
    AskKey.CHAT_UNKNOWN_REMOVE to "امسح السؤال: {0}",
    AskKey.CHAT_UNKNOWN_REMOVED to "اتمسح السؤال",
    AskKey.CHAT_UNKNOWN_COPY to "انسخ القايمة",
    AskKey.CHAT_UNKNOWN_COPIED to "اتنسخت القايمة",
    AskKey.CHAT_VOICE_UNAVAILABLE to "التعرّف على الكلام مش متاح على الجهاز ده.",
    AskKey.CHAT_VOICE_FAILED to "ما سمعتش حاجة — جرّب تاني.",
    AskKey.CHAT_MAIN_BADGE to "الأساسية",
    AskKey.CHAT_MAKE_MAIN to "خلّيها الأساسية",
    AskKey.CHAT_IS_MAIN to "محفظة الصرف الأساسية",
    AskKey.CHAT_MAIN_DONE to "بقت «{0}» الأساسية",
    AskKey.CHAT_EDIT_HOW to "تعدّل إيه؟ اكتب المبلغ الصح، أو «كاش» أو «البنك» عشان تغيّر المحفظة.",
    AskKey.CHAT_CARD_INCOME to "أسجّله دخل كده؟",
    AskKey.CHAT_CARD_LENT to "أسجّلها سلفة لـ{0}؟ هتظهر في «ليك».",
    AskKey.CHAT_CARD_BORROWED to "أسجّلها سلفة من {0}؟ هتظهر في «عليك».",
    AskKey.CHAT_CARD_MOVE to "أسجّله تحويل بين محافظك؟ مش هيتحسب مصروف ولا دخل.",
    AskKey.CHAT_NEEDS_PERSON to "السلفة لمين؟ اكتب اسمه زي ما هو في «الأشخاص»، مثلًا: سلفت أحمد 200.",
    AskKey.CHAT_MOVE_NEEDS_WALLETS to "من أنهي محفظة لأنهي محفظة؟ اكتبها كده: حولت 500 من الكاش للبنك.",
    AskKey.CHAT_UNTIL_SALARY to "ومعاك تقريبًا {0} لحد المرتب ({1}).",
    AskKey.CHAT_INCOME_TITLE to "دخل",
    AskKey.CHAT_LENT_TITLE to "سلفة لـ{0}",
    AskKey.CHAT_BORROWED_TITLE to "سلفة من {0}",
    AskKey.CHAT_MOVE_TITLE to "تحويل بين محافظي",
)

/** نصوص [AskKey] — الإنجليزي. */
internal val ENGLISH_ASK_TEXTS: Map<AskKey, String> = mapOf(
    AskKey.CHAT_CARD_SAVE to "Save",
    AskKey.CHAT_CARD_EDIT to "Edit",
    AskKey.CHAT_CARD_CANCEL to "Cancel",
    AskKey.CHAT_CARD_DONE to "Recorded",
    AskKey.CHAT_CARD_DROPPED to "Edited below",
    AskKey.CHAT_CARD_CANCELLED to "Cancelled",
    AskKey.CHAT_SPLIT_SAVE to "Record the split",
    AskKey.CHAT_SIMILAR_TODAY to "There's a similar transaction today",
    AskKey.CHAT_SIMILAR_RECORD to "Record it anyway",
    AskKey.CHAT_SIMILAR_KEEP to "That's the one, leave it",
    AskKey.CHAT_SIMILAR_KEPT to "OK, I left the recorded one as it is.",
    AskKey.CHAT_SUB_INCOME to "Income",
    AskKey.CHAT_SUB_LENT to "{0} owes you",
    AskKey.CHAT_SUB_BORROWED to "You owe {0}",
    AskKey.CHAT_SUB_MOVE to "From {0} to {1}",
    AskKey.CHAT_START_CLOSE to "Dismiss: {0}",
    AskKey.CHAT_START_CLOSED to "Card dismissed",
    AskKey.CHAT_UNDO to "Undo",
    AskKey.CHAT_NOTIF_DELETE to "Delete notification: {0}",
    AskKey.CHAT_NOTIF_DELETED to "Notification deleted",
    AskKey.CHAT_HISTORY_TODAY to "Today",
    AskKey.CHAT_HISTORY_YESTERDAY to "Yesterday",
    AskKey.CHAT_HISTORY_THIS_WEEK to "This week",
    AskKey.CHAT_HISTORY_OLDER to "Older",
    AskKey.CHAT_HISTORY_VIEWING to "A past conversation",
    AskKey.CHAT_HISTORY_BACK to "Back to the current conversation",
    AskKey.CHAT_HISTORY_AUTO_DELETE to "Conversations are deleted automatically after 3 months.",
    AskKey.CHAT_MEMORY_TITLE to "What I learned about you",
    AskKey.CHAT_MEMORY_LEARNING to "Learn from my questions",
    AskKey.CHAT_MEMORY_LEARNING_NOTE to "When off, no suggestions come from your questions; questions I didn't understand are still saved so I can learn them.",
    AskKey.CHAT_MEMORY_EMPTY to "I haven't learned anything about you yet.",
    AskKey.CHAT_MEMORY_FORGET to "Forget: {0}",
    AskKey.CHAT_MEMORY_CLEAR_ALL to "Clear all",
    AskKey.CHAT_MEMORY_CLEAR_TITLE to "Clear everything I learned?",
    AskKey.CHAT_MEMORY_CLEAR_BODY to "Topics you ask about often are deleted, and facts you confirmed won't show again unless they change. Your data itself is not touched.",
    AskKey.CHAT_MEMORY_CLEAR_YES to "Clear",
    AskKey.CHAT_MEMORY_CLEAR_NO to "Cancel",
    AskKey.CHAT_UNKNOWN_TITLE to "Questions I didn't understand yet ({0})",
    AskKey.CHAT_UNKNOWN_REMOVE to "Remove question: {0}",
    AskKey.CHAT_UNKNOWN_REMOVED to "Question removed",
    AskKey.CHAT_UNKNOWN_COPY to "Copy the list",
    AskKey.CHAT_UNKNOWN_COPIED to "List copied",
    AskKey.CHAT_VOICE_UNAVAILABLE to "Speech recognition isn't available on this device.",
    AskKey.CHAT_VOICE_FAILED to "I didn't hear anything — try again.",
    AskKey.CHAT_MAIN_BADGE to "Main",
    AskKey.CHAT_MAKE_MAIN to "Make it the main wallet",
    AskKey.CHAT_IS_MAIN to "Main spending wallet",
    AskKey.CHAT_MAIN_DONE to "“{0}” is now the main wallet",
    AskKey.CHAT_EDIT_HOW to "What should I change? Type the right amount, or “cash” or “bank” to change the wallet.",
    AskKey.CHAT_CARD_INCOME to "Record it as income like this?",
    AskKey.CHAT_CARD_LENT to "Record it as a loan to {0}? It will show under “Owed to you”.",
    AskKey.CHAT_CARD_BORROWED to "Record it as a loan from {0}? It will show under “You owe”.",
    AskKey.CHAT_CARD_MOVE to "Record it as a move between your wallets? It counts as neither spending nor income.",
    AskKey.CHAT_NEEDS_PERSON to "Who is the loan with? Type the name as it is in “People”, e.g. lent Ahmed 200.",
    AskKey.CHAT_MOVE_NEEDS_WALLETS to "From which wallet to which? Write it like: moved 500 from cash to the bank.",
    AskKey.CHAT_UNTIL_SALARY to "And you have about {0} until payday ({1}).",
    AskKey.CHAT_INCOME_TITLE to "Income",
    AskKey.CHAT_LENT_TITLE to "Loan to {0}",
    AskKey.CHAT_BORROWED_TITLE to "Loan from {0}",
    AskKey.CHAT_MOVE_TITLE to "Move between my wallets",
)
