package app.masroufy.core

/**
 * نصوص «حاسبة الورث» — قبل القسمة والنتيجة والقسمة والمحفوظة (`InheritanceBefore` · `InheritanceResult` · `InheritanceSplit` ·
 * `InheritanceSaved`): من النموذج بالحرف؛ الإنجليزي كتابة Claude (مستني مراجعة المالك §40).
 */
internal val MSA_CALC_INHERIT_RESULT_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.INHBEFORE_TITLE to "قبل القسمة",
    UiKey.INHBEFORE_INTRO to "تُخرج أولًا بالترتيب: تجهيز الميت، ثم الديون، ثم الوصية — ثم يُقسم الباقي على الورثة.",
    UiKey.INHBEFORE_FUNERAL to "تجهيز الميت",
    UiKey.INHBEFORE_FUNERAL_NOTE to "تكاليف الغسل والتكفين والدفن بالمعروف",
    UiKey.INHBEFORE_FUNERAL_NOTE_EG to "ومعه تجهيز من كان ينفق عليهم إن ماتوا قبل الدفن (المادة 4)",
    UiKey.INHBEFORE_DEBTS to "الديون",
    UiKey.INHBEFORE_DEBTS_NOTE to "ومنها الرصيد بالسالب في أي حساب",
    UiKey.INHBEFORE_BEQUEST to "الوصية",
    UiKey.INHBEFORE_BEQUEST_NOTE to "حتى الثلث — ما زاد يحتاج موافقة الورثة كلهم بعد الوفاة",
    UiKey.INHBEFORE_TO_HEIR to "الوصية لأحد الورثة",
    UiKey.INHBEFORE_TO_HEIR_NOTE_SA to "لا تنفذ إلا بموافقة باقي الورثة بعد الوفاة (م179)",
    UiKey.INHBEFORE_TO_HEIR_NOTE_EG to "جائزة في حدود الثلث دون موافقة (قانون 71 م37)",
    UiKey.INHBEFORE_CONSENT to "الورثة كلهم وافقوا بعد الوفاة",
    UiKey.INHBEFORE_CONSENT_NOTE to "تُنفذ الوصية كاملة ولو زادت على الثلث",
    UiKey.INHBEFORE_PRE_Q to "هل للمتوفى ابن أو بنت توفّي قبله وله أولاد؟",
    UiKey.INHBEFORE_PRE_SON to "ابن",
    UiKey.INHBEFORE_PRE_DAUGHTER to "بنت",
    UiKey.INHBEFORE_PRE_SONS to "أولاده الذكور",
    UiKey.INHBEFORE_PRE_DAUGHTERS to "بناته",
    UiKey.INHBEFORE_PRE_GIFT to "ما أعطاهم في حياته (اختياري)",
    UiKey.INHBEFORE_SPECIAL to "ظروف خاصة",
    UiKey.INHBEFORE_SP_PREGNANCY to "يوجد حمل",
    UiKey.INHBEFORE_SP_MISSING to "وارث مفقود",
    UiKey.INHBEFORE_SP_SUCCESSIVE to "وارث توفي قبل القسمة",
    UiKey.INHBEFORE_SP_TAKHARUJ to "تخارج بين الورثة",
    UiKey.INHBEFORE_SPECIAL_NOTE to "أي واحدة منها تجعل الحساب «غير مدعوم» في هذه النسخة — بدل التخمين.",
    UiKey.INHRES_HERO_LABEL to "يُقسَم على الورثة",
    UiKey.INHRES_HERO_SUB_CLAIMS to "من تركة {0} بعد ما يُخرج قبل القسمة، {1}",
    UiKey.INHRES_HERO_SUB_PLAIN to "من تركة {0}، لا تجهيز ولا ديون ولا وصية، {1}",
    UiKey.INHRES_WAJIBA_FOR to "الوصية الواجبة لأولاد {0}",
    UiKey.INHRES_HEIR_COUNT to "{0} ({1})",
    UiKey.INHRES_HEIR_NUMBER to "{0} {1}",
    UiKey.INHRES_EACH to "لكل واحد {0}",
    UiKey.INHRES_EXTRA_HALALA to " (الهللة الزائدة للأول)",
    UiKey.INHRES_EXTRA_PIASTRE to " (القرش الزائد للأول)",
    UiKey.INHRES_BASIS_FARD to "فرض محدد",
    UiKey.INHRES_AFTER_AWL to " — بعد العَوْل",
    UiKey.INHRES_BASIS_REST to "الباقي",
    UiKey.INHRES_BASIS_REST_MF to "الباقي، للذكر مثل حظ الأنثيين",
    UiKey.INHRES_BASIS_FARD_REST to "فرض + الباقي",
    UiKey.INHRES_BASIS_RADD to "فرض + الرَّدّ",
    UiKey.INHRES_BASIS_BLOCKED to "لا يرث (محجوب)",
    UiKey.INHRES_BASIS_NOTHING to "لم يبق له شيء",
    UiKey.INHRES_BASIS_DISTANT to "من ذوي الأرحام",
    UiKey.INHRES_FRAC_HALF to "النصف",
    UiKey.INHRES_FRAC_QUARTER to "الربع",
    UiKey.INHRES_FRAC_EIGHTH to "الثمن",
    UiKey.INHRES_FRAC_THIRD to "الثلث",
    UiKey.INHRES_FRAC_TWO_THIRDS to "الثلثان",
    UiKey.INHRES_FRAC_SIXTH to "السدس",
    UiKey.INHRES_COURT_TITLE to "لا نص — اسأل المحكمة",
    UiKey.INHRES_KIND_INVALID to "مدخلات غير صحيحة",
    UiKey.INHRES_KIND_UNSUPPORTED to "غير مدعوم في هذه النسخة",
    UiKey.INHRES_KIND_COURT to "حالة بلا نص في القانون",
    UiKey.INHRES_GRANDSON to "حفيد",
    UiKey.INHRES_GRANDDAUGHTER to "حفيدة",
    UiKey.INHRES_WAJIBA_PERSON to "{0} {1} (الوصية الواجبة)",
    UiKey.INHSPLIT_TITLE to "قسمة كل شيء",
    UiKey.INHSPLIT_SUM to "المجموع",
    UiKey.INHSPLIT_NOTE to "كل شيء يحمل من الديون والوصية بنسبة قيمته، والمجاميع مضبوطة بالهللة.",
    UiKey.INHSPLIT_NOTE_EG to "كل شيء يحمل من الديون والوصية بنسبة قيمته، والمجاميع مضبوطة بالقرش.",
    UiKey.INHSPLIT_NOTES to "ملاحظات",
    UiKey.INHSAVED_TITLE to "الحسبات المحفوظة",
    UiKey.INHSAVED_INTRO to "على حسابك كله وتظهر على كل أجهزتك. كل حسبة تُحسب بقانون البلد الذي عُملت فيه، والنتيجة تُحسب من جديد عند الفتح.",
    UiKey.INHSAVED_EMPTY_TITLE to "لا توجد حسبات محفوظة",
    UiKey.INHSAVED_EMPTY_BODY to "احسب تركة واحفظها لترجع لها لاحقًا.",
    UiKey.INHSAVED_EMPTY_ACTION to "احسب تركة",
    UiKey.INHSAVED_LOAD_FAILED to "تعذّر تحميل الحسبات المحفوظة",
    UiKey.INHSAVED_LAW_SA to "بقانون السعودية",
    UiKey.INHSAVED_LAW_EG to "بقانون مصر",
    UiKey.INHSAVED_DRAFT to "بلا ورثة بعد (مسودة)",
    UiKey.INHSAVED_WHEN to "عُدّلت {0}، أُنشئت {1}",
    UiKey.INHSAVED_OPEN to "افتح",
    UiKey.INHSAVED_RENAME to "إعادة تسمية",
    UiKey.INHSAVED_RENAME_BODY to "الاسم فقط يتغير، والمدخلات كما هي.",
    UiKey.INHSAVED_RENAMED to "تغيّر الاسم إلى «{0}»",
    UiKey.INHSAVED_DELETE_ONE to "احذف {0}",
    UiKey.INHSAVED_DELETE_TITLE to "حذف «{0}»؟",
    UiKey.INHSAVED_DELETE_BODY to "هذه حسبة للتخطيط وليست بيانات مالية، فحذفها لا يغيّر شيئًا في حساباتك.",
    UiKey.INHSAVED_DELETE to "احذف",
    UiKey.INHSAVED_DELETED to "حُذفت «{0}»",
    UiKey.INHSAVED_UNDO to "تراجع",
    UiKey.INHSAVED_RESTORED to "أُعيدت «{0}»",
)

internal val EGYPTIAN_CALC_INHERIT_RESULT_TEXTS: Map<UiKey, String> = MSA_CALC_INHERIT_RESULT_TEXTS + mapOf(
    UiKey.INHBEFORE_INTRO to "بتطلع الأول بالترتيب: تجهيز الميت، وبعدين الديون، وبعدين الوصية — وبعدين الباقي يتقسم على الورثة.",
    UiKey.INHBEFORE_FUNERAL_NOTE_EG to "ومعاه تجهيز اللي كان بيصرف عليهم لو ماتوا قبل الدفن (مادة 4)",
    UiKey.INHBEFORE_BEQUEST_NOTE to "لحد التلت — الزيادة محتاجة موافقة الورثة كلهم بعد الوفاة",
    UiKey.INHBEFORE_TO_HEIR to "الوصية لحد من الورثة",
    UiKey.INHBEFORE_TO_HEIR_NOTE_SA to "مش بتتنفذ إلا بموافقة باقي الورثة بعد الوفاة (م179)",
    UiKey.INHBEFORE_TO_HEIR_NOTE_EG to "جايزة في حدود التلت من غير موافقة (قانون 71 مادة 37)",
    UiKey.INHBEFORE_CONSENT_NOTE to "الوصية بتتنفذ كلها حتى لو زادت عن التلت",
    UiKey.INHBEFORE_PRE_Q to "فيه ابن أو بنت توفّى قبله وله أولاد؟",
    UiKey.INHBEFORE_PRE_SONS to "ولاده الذكور",
    UiKey.INHBEFORE_PRE_GIFT to "اللي اداهولهم في حياته (اختياري)",
    UiKey.INHBEFORE_SP_PREGNANCY to "فيه حمل",
    UiKey.INHBEFORE_SP_SUCCESSIVE to "وارث اتوفى قبل القسمة",
    UiKey.INHBEFORE_SPECIAL_NOTE to "أي واحدة منهم بتخلّي الحساب «مش مدعوم» في النسخة دي — بدل التخمين.",
    UiKey.INHRES_HERO_LABEL to "بيتقسم على الورثة",
    UiKey.INHRES_HERO_SUB_CLAIMS to "من تركة {0} بعد اللي بيطلع قبل القسمة، {1}",
    UiKey.INHRES_HERO_SUB_PLAIN to "من تركة {0}، مفيش تجهيز ولا ديون ولا وصية، {1}",
    UiKey.INHRES_EXTRA_HALALA to " (الهللة الزيادة للأول)",
    UiKey.INHRES_EXTRA_PIASTRE to " (القرش الزيادة للأول)",
    UiKey.INHRES_BASIS_BLOCKED to "مش بيورث (محجوب)",
    UiKey.INHRES_BASIS_NOTHING to "مفضلش له حاجة",
    UiKey.INHRES_COURT_TITLE to "مفيش نص — اسأل المحكمة",
    UiKey.INHRES_KIND_INVALID to "مدخلات غلط",
    UiKey.INHRES_KIND_UNSUPPORTED to "مش مدعوم في النسخة دي",
    UiKey.INHRES_KIND_COURT to "حالة من غير نص في القانون",
    UiKey.INHSPLIT_TITLE to "قسمة كل حاجة",
    UiKey.INHSPLIT_NOTE to "كل حاجة شايلة من الديون والوصية بنسبة قيمتها، والمجاميع مظبوطة بالهللة.",
    UiKey.INHSPLIT_NOTE_EG to "كل حاجة شايلة من الديون والوصية بنسبة قيمتها، والمجاميع مظبوطة بالقرش.",
    UiKey.INHSAVED_TITLE to "الحسبات المتحفظة",
    UiKey.INHSAVED_INTRO to "على حسابك كله وبتبان على كل أجهزتك. كل حسبة بتتحسب بقانون البلد اللي اتعملت فيه، والنتيجة بتتحسب من جديد وقت الفتح.",
    UiKey.INHSAVED_EMPTY_TITLE to "مفيش حسبات متحفظة",
    UiKey.INHSAVED_EMPTY_BODY to "احسب تركة واحفظها عشان ترجعلها بعدين.",
    UiKey.INHSAVED_LOAD_FAILED to "الحسبات المتحفظة ما اتحمّلتش",
    UiKey.INHSAVED_DRAFT to "من غير ورثة لسه (مسودة)",
    UiKey.INHSAVED_WHEN to "اتعدّلت {0}، اتعملت {1}",
    UiKey.INHSAVED_RENAME to "غيّر الاسم",
    UiKey.INHSAVED_RENAME_BODY to "الاسم بس اللي بيتغير، والمدخلات زي ما هي.",
    UiKey.INHSAVED_RENAMED to "الاسم بقى «{0}»",
    UiKey.INHSAVED_DELETE_ONE to "امسح {0}",
    UiKey.INHSAVED_DELETE_TITLE to "مسح «{0}»؟",
    UiKey.INHSAVED_DELETE_BODY to "دي حسبة للتخطيط مش بيانات فلوس، فمسحها مش بيغيّر حاجة في حساباتك.",
    UiKey.INHSAVED_DELETE to "امسح",
    UiKey.INHSAVED_DELETED to "اتمسحت «{0}»",
    UiKey.INHSAVED_UNDO to "رجّعها",
    UiKey.INHSAVED_RESTORED to "رجعت «{0}»",
)

internal val ENGLISH_CALC_INHERIT_RESULT_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.INHBEFORE_TITLE to "Before division",
    UiKey.INHBEFORE_INTRO to "Taken out first, in order: funeral costs, then debts, then the bequest — then the rest is divided among the heirs.",
    UiKey.INHBEFORE_FUNERAL to "Funeral costs",
    UiKey.INHBEFORE_FUNERAL_NOTE to "Washing, shrouding and burial at a reasonable cost",
    UiKey.INHBEFORE_FUNERAL_NOTE_EG to "Including the funeral of dependants who died before the burial (art. 4)",
    UiKey.INHBEFORE_DEBTS to "Debts",
    UiKey.INHBEFORE_DEBTS_NOTE to "Including any negative account balance",
    UiKey.INHBEFORE_BEQUEST to "Bequest",
    UiKey.INHBEFORE_BEQUEST_NOTE to "Up to a third — anything above needs every heir's consent after the death",
    UiKey.INHBEFORE_TO_HEIR to "Bequest to one of the heirs",
    UiKey.INHBEFORE_TO_HEIR_NOTE_SA to "Valid only with the other heirs' consent after the death (art. 179)",
    UiKey.INHBEFORE_TO_HEIR_NOTE_EG to "Valid within a third without consent (law 71 art. 37)",
    UiKey.INHBEFORE_CONSENT to "All heirs consented after the death",
    UiKey.INHBEFORE_CONSENT_NOTE to "The bequest is paid in full even above a third",
    UiKey.INHBEFORE_PRE_Q to "Did a son or daughter of the deceased die before them, leaving children?",
    UiKey.INHBEFORE_PRE_SON to "Son",
    UiKey.INHBEFORE_PRE_DAUGHTER to "Daughter",
    UiKey.INHBEFORE_PRE_SONS to "Their sons",
    UiKey.INHBEFORE_PRE_DAUGHTERS to "Their daughters",
    UiKey.INHBEFORE_PRE_GIFT to "What was given to them during life (optional)",
    UiKey.INHBEFORE_SPECIAL to "Special circumstances",
    UiKey.INHBEFORE_SP_PREGNANCY to "Pregnancy",
    UiKey.INHBEFORE_SP_MISSING to "Missing heir",
    UiKey.INHBEFORE_SP_SUCCESSIVE to "An heir died before division",
    UiKey.INHBEFORE_SP_TAKHARUJ to "Heirs' buy-out agreement",
    UiKey.INHBEFORE_SPECIAL_NOTE to "Any of these makes the calculation “not supported” in this version — instead of guessing.",
    UiKey.INHRES_HERO_LABEL to "Divided among the heirs",
    UiKey.INHRES_HERO_SUB_CLAIMS to "From an estate of {0} after what comes out before division, {1}",
    UiKey.INHRES_HERO_SUB_PLAIN to "From an estate of {0}, no funeral costs, debts or bequest, {1}",
    UiKey.INHRES_WAJIBA_FOR to "Obligatory bequest for the children of the {0}",
    UiKey.INHRES_HEIR_COUNT to "{0} ({1})",
    UiKey.INHRES_HEIR_NUMBER to "{0} {1}",
    UiKey.INHRES_EACH to "{0} each",
    UiKey.INHRES_EXTRA_HALALA to " (the extra halala goes to the first)",
    UiKey.INHRES_EXTRA_PIASTRE to " (the extra piastre goes to the first)",
    UiKey.INHRES_BASIS_FARD to "Fixed share",
    UiKey.INHRES_AFTER_AWL to " — after proportional reduction (awl)",
    UiKey.INHRES_BASIS_REST to "The residue",
    UiKey.INHRES_BASIS_REST_MF to "The residue, a male gets twice a female",
    UiKey.INHRES_BASIS_FARD_REST to "Fixed share + residue",
    UiKey.INHRES_BASIS_RADD to "Fixed share + return (radd)",
    UiKey.INHRES_BASIS_BLOCKED to "Does not inherit (excluded)",
    UiKey.INHRES_BASIS_NOTHING to "Nothing was left for them",
    UiKey.INHRES_BASIS_DISTANT to "Distant relative",
    UiKey.INHRES_FRAC_HALF to "One half",
    UiKey.INHRES_FRAC_QUARTER to "One quarter",
    UiKey.INHRES_FRAC_EIGHTH to "One eighth",
    UiKey.INHRES_FRAC_THIRD to "One third",
    UiKey.INHRES_FRAC_TWO_THIRDS to "Two thirds",
    UiKey.INHRES_FRAC_SIXTH to "One sixth",
    UiKey.INHRES_COURT_TITLE to "No text — ask the court",
    UiKey.INHRES_KIND_INVALID to "Invalid inputs",
    UiKey.INHRES_KIND_UNSUPPORTED to "Not supported in this version",
    UiKey.INHRES_KIND_COURT to "A case the law does not cover",
    UiKey.INHRES_GRANDSON to "Grandson",
    UiKey.INHRES_GRANDDAUGHTER to "Granddaughter",
    UiKey.INHRES_WAJIBA_PERSON to "{0} {1} (obligatory bequest)",
    UiKey.INHSPLIT_TITLE to "Division of each item",
    UiKey.INHSPLIT_SUM to "Total",
    UiKey.INHSPLIT_NOTE to "Each item carries part of the debts and bequest in proportion to its value; totals are exact to the halala.",
    UiKey.INHSPLIT_NOTE_EG to "Each item carries part of the debts and bequest in proportion to its value; totals are exact to the piastre.",
    UiKey.INHSPLIT_NOTES to "Notes",
    UiKey.INHSAVED_TITLE to "Saved calculations",
    UiKey.INHSAVED_INTRO to "On your whole account and shown on all your devices. Each calculation uses the law of the country it was made in, and is recalculated when opened.",
    UiKey.INHSAVED_EMPTY_TITLE to "No saved calculations",
    UiKey.INHSAVED_EMPTY_BODY to "Calculate an estate and save it to come back to it later.",
    UiKey.INHSAVED_EMPTY_ACTION to "Calculate an estate",
    UiKey.INHSAVED_LOAD_FAILED to "Could not load the saved calculations",
    UiKey.INHSAVED_LAW_SA to "Saudi law",
    UiKey.INHSAVED_LAW_EG to "Egyptian law",
    UiKey.INHSAVED_DRAFT to "No heirs yet (draft)",
    UiKey.INHSAVED_WHEN to "Edited {0}, created {1}",
    UiKey.INHSAVED_OPEN to "Open",
    UiKey.INHSAVED_RENAME to "Rename",
    UiKey.INHSAVED_RENAME_BODY to "Only the name changes; the inputs stay as they are.",
    UiKey.INHSAVED_RENAMED to "Renamed to “{0}”",
    UiKey.INHSAVED_DELETE_ONE to "Delete {0}",
    UiKey.INHSAVED_DELETE_TITLE to "Delete “{0}”?",
    UiKey.INHSAVED_DELETE_BODY to "This is a planning calculation, not financial data, so deleting it changes nothing in your accounts.",
    UiKey.INHSAVED_DELETE to "Delete",
    UiKey.INHSAVED_DELETED to "Deleted “{0}”",
    UiKey.INHSAVED_UNDO to "Undo",
    UiKey.INHSAVED_RESTORED to "Restored “{0}”",
)
