package app.masroufy.core

/**
 * نصوص «حاسبة الورث» — الخطوات (`InheritanceCalculator` + `InheritanceHeirs`): من النموذج بالحرف (الفصحى للسعودية والمصري لمصر)؛
 * الإنجليزي كتابة Claude (مستني مراجعة المالك §40). أسماء الورثة والملاحظات وأسباب التوقف من `TextsInheritance.kt` (المحرك).
 */
internal val MSA_CALC_INHERIT_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.INHCALC_TITLE to "حاسبة الورث",
    UiKey.INHCALC_SAVED to "المحفوظة",
    UiKey.INHCALC_WHOSE_LINE_START to "خطوة بخطوة، والقانون من البلد تلقائيًا",
    UiKey.INHCALC_MINE to "تركتي أنا",
    UiKey.INHCALC_MINE_SUB to "تستطيع جلب أملاكك من مصروفي بلمسة",
    UiKey.INHCALC_OTHER to "تركة شخص آخر",
    UiKey.INHCALC_OTHER_SUB to "من أشخاصك أو اسم جديد — الحساب نفسه",
    UiKey.INHCALC_OF to "تركة {0}",
    UiKey.INHCALC_LAW_SA to "بقانون السعودية: نظام الأحوال الشخصية (1443هـ)",
    UiKey.INHCALC_LAW_EG to "بقانون مصر: قانون المواريث 77 لسنة 1943 والوصية 71 لسنة 1946",
    UiKey.INHCALC_LAW_FOREIGN to " — حسبة محفوظة من {0}",
    UiKey.INHCALC_COUNTRY_SA to "السعودية",
    UiKey.INHCALC_COUNTRY_EG to "مصر",
    UiKey.INHCALC_STEPS to "خطوات الحسبة",
    UiKey.INHCALC_STEP_WHOSE to "تركة مَن",
    UiKey.INHCALC_STEP_ITEMS to "الأملاك",
    UiKey.INHCALC_STEP_HEIRS to "الورثة",
    UiKey.INHCALC_STEP_BEFORE to "قبل القسمة",
    UiKey.INHCALC_WHOSE_Q to "تركة مَن تحسب؟",
    UiKey.INHCALC_NEW_NAME to "أو اكتب اسمًا جديدًا",
    UiKey.INHCALC_PICK_PERSON to "اختر شخصًا من أشخاصك أو اكتب اسمًا",
    UiKey.INHCALC_ITEMS_Q to "ماذا يترك؟",
    UiKey.INHCALC_ITEMS_INTRO to "اكتب اسم كل شيء وقيمته التقريبية. كل رقم يتعدّل.",
    UiKey.INHCALC_BRING to "هات أملاكي من مصروفي",
    UiKey.INHCALC_BRING_NOTE to "الأرصدة الموجبة والذهب والأسهم والعقار بأسعار اليوم. الرصيد بالسالب يُكتب في الديون.",
    UiKey.INHCALC_BRING_ONLY_MINE to "جلب الأملاك لتركتك أنت فقط.",
    UiKey.INHCALC_BROUGHT to "جُلبت {0} بأسعار اليوم — كل رقم يتعدّل",
    UiKey.INHCALC_BRING_ALREADY to "أملاكك موجودة في القائمة بالفعل",
    UiKey.INHCALC_BRING_NONE to "لا أرصدة موجبة ولا أصول بعملة هذا البلد في مصروفي",
    UiKey.INHCALC_ITEM_NAME to "اسم الشيء",
    UiKey.INHCALC_VALUE_UNKNOWN to "غير معروف",
    UiKey.INHCALC_VALUE_MISSING to "غير معروف — اكتب قيمته",
    UiKey.INHCALC_REMOVE to "احذف {0}",
    UiKey.INHCALC_THIS_THING to "هذا الشيء",
    UiKey.INHCALC_ADD_ITEM to "+ أضف شيئًا",
    UiKey.INHCALC_ITEM_VALUE to "اكتب قيمة تقريبية لكل شيء، أو احذفه",
    UiKey.INHCALC_PREV to "السابق",
    UiKey.INHCALC_EDIT to "عدّل",
    UiKey.INHCALC_NEXT to "التالي",
    UiKey.INHCALC_CALC to "احسب",
    UiKey.INHCALC_SAVE to "احفظ الحسبة",
    UiKey.INHCALC_SAVE_TITLE to "اسم الحسبة",
    UiKey.INHCALC_SAVE_BODY to "تُحفظ على حسابك وتظهر على كل أجهزتك. نحفظ المدخلات فقط، والنتيجة تُحسب من جديد عند الفتح.",
    UiKey.INHCALC_SAVE_BUTTON to "احفظ",
    UiKey.INHCALC_SAVED_TOAST to "حُفظت «{0}» — تجدها في «المحفوظة»",
    UiKey.INHCALC_NAME_MINE to "تركتي — {0}",
    UiKey.INHCALC_NAME_OTHER to "تركة {0} — {1}",
    UiKey.INHCALC_THINGS_ONE to "شيء واحد",
    UiKey.INHCALC_THINGS_TWO to "شيئان",
    UiKey.INHCALC_THINGS_FEW to "{0} أشياء",
    UiKey.INHCALC_THINGS_MANY to "{0} شيئًا",
    UiKey.INHHEIRS_TITLE to "مَن الورثة؟",
    UiKey.INHHEIRS_INTRO to "اكتب العدد فقط، والأسماء اختيارية.",
    UiKey.INHHEIRS_NONE to "لم تُضف ورثة بعد",
    UiKey.INHHEIRS_MORE to "ورثة آخرون: الجد والجدات والأحفاد والإخوة والأعمام",
    UiKey.INHHEIRS_LESS to "أنقص {0}",
    UiKey.INHHEIRS_MORE_ONE to "أضف {0}",
    UiKey.INHHEIRS_NAMES to "الأسماء (اختياري)",
    UiKey.INHHEIRS_FOOT to "الأقارب الأبعد (أولاد البنات، الخال، العمة…) نسألك عنهم في النتيجة عند الحاجة. الحمل والمفقود في الخطوة التالية.",
)

internal val EGYPTIAN_CALC_INHERIT_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.INHCALC_TITLE to "حاسبة الورث",
    UiKey.INHCALC_SAVED to "المتحفظة",
    UiKey.INHCALC_WHOSE_LINE_START to "خطوة خطوة، والقانون من البلد لوحده",
    UiKey.INHCALC_MINE to "تركتي أنا",
    UiKey.INHCALC_MINE_SUB to "تقدر تجيب أملاكك من مصروفي بلمسة",
    UiKey.INHCALC_OTHER to "تركة حد تاني",
    UiKey.INHCALC_OTHER_SUB to "من أشخاصك أو اسم جديد — نفس الحساب",
    UiKey.INHCALC_OF to "تركة {0}",
    UiKey.INHCALC_LAW_SA to "بقانون السعودية: نظام الأحوال الشخصية (1443هـ)",
    UiKey.INHCALC_LAW_EG to "بقانون مصر: قانون المواريث 77 لسنة 1943 والوصية 71 لسنة 1946",
    UiKey.INHCALC_LAW_FOREIGN to " — حسبة متحفظة من {0}",
    UiKey.INHCALC_COUNTRY_SA to "السعودية",
    UiKey.INHCALC_COUNTRY_EG to "مصر",
    UiKey.INHCALC_STEPS to "خطوات الحسبة",
    UiKey.INHCALC_STEP_WHOSE to "تركة مين",
    UiKey.INHCALC_STEP_ITEMS to "الحاجات",
    UiKey.INHCALC_STEP_HEIRS to "الورثة",
    UiKey.INHCALC_STEP_BEFORE to "قبل القسمة",
    UiKey.INHCALC_WHOSE_Q to "بتحسب تركة مين؟",
    UiKey.INHCALC_NEW_NAME to "أو اكتب اسم جديد",
    UiKey.INHCALC_PICK_PERSON to "اختار حد من أشخاصك أو اكتب اسم",
    UiKey.INHCALC_ITEMS_Q to "سايب إيه؟",
    UiKey.INHCALC_ITEMS_INTRO to "اكتب اسم كل حاجة وقيمتها التقريبية. كل رقم بيتعدّل.",
    UiKey.INHCALC_BRING to "هات أملاكي من مصروفي",
    UiKey.INHCALC_BRING_NOTE to "الأرصدة الموجبة والدهب والأسهم والعقار بأسعار النهارده. الرصيد بالسالب يتكتب في الديون.",
    UiKey.INHCALC_BRING_ONLY_MINE to "جلب الأملاك لتركتك إنت بس.",
    UiKey.INHCALC_BROUGHT to "اتجابت {0} بأسعار النهارده — كل رقم بيتعدّل",
    UiKey.INHCALC_BRING_ALREADY to "أملاكك موجودة في القايمة خلاص",
    UiKey.INHCALC_BRING_NONE to "مفيش أرصدة موجبة ولا أصول بعملة البلد دي في مصروفي",
    UiKey.INHCALC_ITEM_NAME to "اسم الحاجة",
    UiKey.INHCALC_VALUE_UNKNOWN to "مش معروف",
    UiKey.INHCALC_VALUE_MISSING to "مش معروف — اكتب قيمته",
    UiKey.INHCALC_REMOVE to "امسح {0}",
    UiKey.INHCALC_THIS_THING to "الحاجة دي",
    UiKey.INHCALC_ADD_ITEM to "+ ضيف حاجة",
    UiKey.INHCALC_ITEM_VALUE to "اكتب قيمة تقريبية لكل حاجة، أو امسحها",
    UiKey.INHCALC_PREV to "اللي قبله",
    UiKey.INHCALC_EDIT to "عدّل",
    UiKey.INHCALC_NEXT to "التالي",
    UiKey.INHCALC_CALC to "احسب",
    UiKey.INHCALC_SAVE to "احفظ الحسبة",
    UiKey.INHCALC_SAVE_TITLE to "اسم الحسبة",
    UiKey.INHCALC_SAVE_BODY to "بتتحفظ على حسابك وتبان على كل أجهزتك. بنحفظ المدخلات بس، والنتيجة بتتحسب من جديد وقت الفتح.",
    UiKey.INHCALC_SAVE_BUTTON to "احفظ",
    UiKey.INHCALC_SAVED_TOAST to "اتحفظت «{0}» — هتلاقيها في «المتحفظة»",
    UiKey.INHCALC_NAME_MINE to "تركتي — {0}",
    UiKey.INHCALC_NAME_OTHER to "تركة {0} — {1}",
    UiKey.INHCALC_THINGS_ONE to "حاجة واحدة",
    UiKey.INHCALC_THINGS_TWO to "حاجتين",
    UiKey.INHCALC_THINGS_FEW to "{0} حاجات",
    UiKey.INHCALC_THINGS_MANY to "{0} حاجة",
    UiKey.INHHEIRS_TITLE to "مين الورثة؟",
    UiKey.INHHEIRS_INTRO to "اكتب العدد بس، والأسامي اختيارية.",
    UiKey.INHHEIRS_NONE to "لسه ما ضفتش ورثة",
    UiKey.INHHEIRS_MORE to "ورثة تانيين: الجد والجدات والأحفاد والإخوة والأعمام",
    UiKey.INHHEIRS_LESS to "قلّل {0}",
    UiKey.INHHEIRS_MORE_ONE to "زوّد {0}",
    UiKey.INHHEIRS_NAMES to "الأسامي (اختياري)",
    UiKey.INHHEIRS_FOOT to "القرايب الأبعد (أولاد البنات، الخال، العمة…) بنسألك عنهم في النتيجة لو محتاجين. الحمل والمفقود في الخطوة الجاية.",
)

internal val ENGLISH_CALC_INHERIT_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.INHCALC_TITLE to "Inheritance calculator",
    UiKey.INHCALC_SAVED to "Saved",
    UiKey.INHCALC_WHOSE_LINE_START to "Step by step; the law follows the country automatically",
    UiKey.INHCALC_MINE to "My own estate",
    UiKey.INHCALC_MINE_SUB to "You can bring your holdings from Masroufy in one tap",
    UiKey.INHCALC_OTHER to "Someone else's estate",
    UiKey.INHCALC_OTHER_SUB to "One of your people or a new name — the same calculation",
    UiKey.INHCALC_OF to "{0}'s estate",
    UiKey.INHCALC_LAW_SA to "Under Saudi law: Personal Status Law (1443 AH)",
    UiKey.INHCALC_LAW_EG to "Under Egyptian law: Inheritance Law 77 of 1943 and Bequest Law 71 of 1946",
    UiKey.INHCALC_LAW_FOREIGN to " — saved calculation from {0}",
    UiKey.INHCALC_COUNTRY_SA to "Saudi Arabia",
    UiKey.INHCALC_COUNTRY_EG to "Egypt",
    UiKey.INHCALC_STEPS to "Calculation steps",
    UiKey.INHCALC_STEP_WHOSE to "Whose estate",
    UiKey.INHCALC_STEP_ITEMS to "Holdings",
    UiKey.INHCALC_STEP_HEIRS to "Heirs",
    UiKey.INHCALC_STEP_BEFORE to "Before division",
    UiKey.INHCALC_WHOSE_Q to "Whose estate are you calculating?",
    UiKey.INHCALC_NEW_NAME to "Or type a new name",
    UiKey.INHCALC_PICK_PERSON to "Pick one of your people or type a name",
    UiKey.INHCALC_ITEMS_Q to "What does the estate hold?",
    UiKey.INHCALC_ITEMS_INTRO to "Enter each item's name and approximate value. Every number can be edited.",
    UiKey.INHCALC_BRING to "Bring my holdings from Masroufy",
    UiKey.INHCALC_BRING_NOTE to "Positive balances, gold, stocks and real estate at today's prices. A negative balance goes under debts.",
    UiKey.INHCALC_BRING_ONLY_MINE to "Holdings can be brought for your own estate only.",
    UiKey.INHCALC_BROUGHT to "{0} brought at today's prices — every number can be edited",
    UiKey.INHCALC_BRING_ALREADY to "Your holdings are already in the list",
    UiKey.INHCALC_BRING_NONE to "No positive balances or assets in this country's currency in Masroufy",
    UiKey.INHCALC_ITEM_NAME to "Item name",
    UiKey.INHCALC_VALUE_UNKNOWN to "Unknown",
    UiKey.INHCALC_VALUE_MISSING to "Unknown — enter its value",
    UiKey.INHCALC_REMOVE to "Remove {0}",
    UiKey.INHCALC_THIS_THING to "this item",
    UiKey.INHCALC_ADD_ITEM to "+ Add an item",
    UiKey.INHCALC_ITEM_VALUE to "Enter an approximate value for every item, or remove it",
    UiKey.INHCALC_PREV to "Back",
    UiKey.INHCALC_EDIT to "Edit",
    UiKey.INHCALC_NEXT to "Next",
    UiKey.INHCALC_CALC to "Calculate",
    UiKey.INHCALC_SAVE to "Save the calculation",
    UiKey.INHCALC_SAVE_TITLE to "Calculation name",
    UiKey.INHCALC_SAVE_BODY to "Saved to your account and shown on all your devices. Only the inputs are saved; the result is recalculated when opened.",
    UiKey.INHCALC_SAVE_BUTTON to "Save",
    UiKey.INHCALC_SAVED_TOAST to "Saved “{0}” — find it under “Saved”",
    UiKey.INHCALC_NAME_MINE to "My estate — {0}",
    UiKey.INHCALC_NAME_OTHER to "{0}'s estate — {1}",
    UiKey.INHCALC_THINGS_ONE to "1 item",
    UiKey.INHCALC_THINGS_TWO to "2 items",
    UiKey.INHCALC_THINGS_FEW to "{0} items",
    UiKey.INHCALC_THINGS_MANY to "{0} items",
    UiKey.INHHEIRS_TITLE to "Who are the heirs?",
    UiKey.INHHEIRS_INTRO to "Enter the number only; names are optional.",
    UiKey.INHHEIRS_NONE to "No heirs added yet",
    UiKey.INHHEIRS_MORE to "Other heirs: grandparents, grandchildren, siblings and uncles",
    UiKey.INHHEIRS_LESS to "Fewer: {0}",
    UiKey.INHHEIRS_MORE_ONE to "More: {0}",
    UiKey.INHHEIRS_NAMES to "Names (optional)",
    UiKey.INHHEIRS_FOOT to "More distant relatives (daughters' children, maternal uncles, aunts…) are asked about in the result when needed. Pregnancy and missing heirs are in the next step.",
)
