package app.masroufy.core

/** نصوص الواجهة المشتركة **بالإنجليزي** — كتابة Claude ومستنية مراجعة المالك (OVERRIDES §40). نفس مفاتيح `TextsShell.kt` و`TextsShellAuth.kt`. */
internal val ENGLISH_SHELL_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.TAB_HOME to "Home",
    TextKey.TAB_OPERATIONS to "Transactions",
    TextKey.TAB_PEOPLE to "People",
    TextKey.TAB_INVESTMENT to "Investment",
    TextKey.SHELL_NAV to "Navigation",
    TextKey.SHELL_GEAR to "More and settings",
    TextKey.SHELL_BACK to "Back",
    TextKey.SHELL_CLOSE to "Close",
    TextKey.SHELL_NEW_DOT to "New",
    TextKey.SHELL_TAB_WITH_NEW to "{0} — new",
    TextKey.SHELL_OFFLINE to "No internet — showing what's saved on your phone, which may not be the latest.",
    TextKey.SHELL_OPENING to "Getting your data ready…",
    TextKey.SHELL_OPENING_PROGRESS to "{0} of {1}",
    TextKey.SHELL_PENDING_SCREEN to "This screen is being built.",
    TextKey.SHELL_LOADING to "Loading",
    TextKey.SHELL_RETRY to "Try again",
    TextKey.SHELL_LOAD_FAILED to "Couldn't load.",
    TextKey.BADGE_APPROX to "Approx.",
    TextKey.GREETING_MORNING_NAME to "Good morning, {0}",
    TextKey.GREETING_EVENING_NAME to "Good evening, {0}",
    TextKey.GREETING_MORNING to "Good morning",
    TextKey.GREETING_EVENING to "Good evening",
    TextKey.ME_PROFILE to "Your profile",
    TextKey.ME_PROFILE_PERCENT to "Your profile — {0}% complete",
    TextKey.WEEKDAY_MON to "Monday",
    TextKey.WEEKDAY_TUE to "Tuesday",
    TextKey.WEEKDAY_WED to "Wednesday",
    TextKey.WEEKDAY_THU to "Thursday",
    TextKey.WEEKDAY_FRI to "Friday",
    TextKey.WEEKDAY_SAT to "Saturday",
    TextKey.WEEKDAY_SUN to "Sunday",
    TextKey.WEEKDAY_SHORT_MON to "Mon",
    TextKey.WEEKDAY_SHORT_TUE to "Tue",
    TextKey.WEEKDAY_SHORT_WED to "Wed",
    TextKey.WEEKDAY_SHORT_THU to "Thu",
    TextKey.WEEKDAY_SHORT_FRI to "Fri",
    TextKey.WEEKDAY_SHORT_SAT to "Sat",
    TextKey.WEEKDAY_SHORT_SUN to "Sun",
    TextKey.MONTH_1 to "January",
    TextKey.MONTH_2 to "February",
    TextKey.MONTH_3 to "March",
    TextKey.MONTH_4 to "April",
    TextKey.MONTH_5 to "May",
    TextKey.MONTH_6 to "June",
    TextKey.MONTH_7 to "July",
    TextKey.MONTH_8 to "August",
    TextKey.MONTH_9 to "September",
    TextKey.MONTH_10 to "October",
    TextKey.MONTH_11 to "November",
    TextKey.MONTH_12 to "December",
    TextKey.DATE_DAY_MONTH to "{1} {0}",
    TextKey.DATE_WEEKDAY_DAY_MONTH to "{0}, {1}",
    TextKey.DATE_MONTH_YEAR to "{0} {1}",
    TextKey.ASK_BAR to "Ask Masroufy or tell it to do anything…",
    TextKey.ASK_MIC to "Add by voice",
    TextKey.ASK_TITLE to "Masroufy",
    TextKey.ASK_CONTEXT to "New chat · you're in “{0}”",
    TextKey.ASK_GREETING_NAME to "Hi {0}. Ask me about your money, or ask me to do something: add a transaction by voice, split a bill with friends, or remind you of a date.",
    TextKey.ASK_GREETING to "Hi. Ask me about your money, or ask me to do something: add a transaction by voice, split a bill with friends, or remind you of a date.",
    TextKey.ASK_INPUT_HINT to "Type or tap the mic",
    TextKey.ASK_INPUT_LABEL to "Your message",
    TextKey.ASK_SEND to "Send",
    TextKey.ASK_TALK to "Speak",
    TextKey.ASK_CLOSE to "Close chat",
    TextKey.ASK_NOT_READY to "The assistant isn't available yet — it needs an AI service whose provider hasn't been approved. You can browse your data from the tabs.",
    TextKey.ASK_VOICE_NOT_READY to "Adding by voice isn't available yet.",
    TextKey.ASK_CHIP_SPENT to "How much did I spend this month?",
    TextKey.ASK_CHIP_VOICE to "Add a transaction by voice",
    TextKey.ASK_CHIP_SPLIT to "Split a bill with friends",
    TextKey.ASK_CHIP_PLAN to "Am I on plan?",
    TextKey.ASK_CHIP_OWED to "How much do people owe me?",
    TextKey.ASK_CHIP_LOCK to "Where do I change the lock?",
    TextKey.ASK_TYPING to "Masroufy is typing",
    TextKey.ASK_LISTENING to "Listening…",
    TextKey.ADD_LABEL to "Add a transaction",
    TextKey.ADD_TITLE to "New transaction",
    TextKey.ADD_VOICE to "By voice",
    TextKey.ADD_KIND_TABS to "Transaction type",
    TextKey.ADD_TYPE_OUT to "Spend",
    TextKey.ADD_TYPE_IN to "Income",
    TextKey.ADD_TYPE_MOVE to "Transfer",
    TextKey.ADD_AMOUNT to "Amount",
    TextKey.ADD_CATEGORY to "Category",
    TextKey.ADD_INCOME_KIND to "Type",
    TextKey.ADD_FROM to "From?",
    TextKey.ADD_TO to "To?",
    TextKey.ADD_SAVE to "Save",
    TextKey.ADD_SAVING to "Saving…",
    TextKey.ADD_SAVED to "Saved: {0}",
    TextKey.ADD_NO_WALLET to "Add a wallet first from “More ← Wallets”.",
    TextKey.ADD_AMOUNT_INVALID to "Enter an amount above zero.",
    TextKey.BELL_TITLE to "Notifications",
    TextKey.BELL_LABEL_NEW to "Notifications — new",
    TextKey.BELL_NEW_COUNT to "{0} new",
    TextKey.BELL_ALL_READ to "All read",
    TextKey.BELL_MARK_READ to "Mark all as read",
    TextKey.BELL_ALL to "All notifications",
    TextKey.BELL_EMPTY to "No notifications now.",
    TextKey.BELL_CLOSE to "Close notifications",
    TextKey.SPACE_SWITCH_TITLE to "Switch country",
    TextKey.SPACE_SWITCH_BODY to "Each country has its own account with its wallets, numbers and currency. Switching is on this phone only and changes nothing in your data.",
    TextKey.SPACE_ACTIVE to "Current",
    TextKey.SPACE_WITH_YOU to "With you now",
    TextKey.SPACE_OPENING to "Opening…",
    TextKey.SPACE_SHARED_NOTE to "Shared across countries: your profile, payday, people, stores and tags.",
    TextKey.SPACE_MANAGE to "Manage countries",
    TextKey.SPACE_TRIGGER to "Country: {0} — tap to switch",
    TextKey.SPACE_SWITCHED to "Switched to the {0} account",
    TextKey.SPACE_SUB to "{0}, {1}",
    TextKey.CURRENCY_NAME_SAR to "Saudi riyal",
    TextKey.CURRENCY_NAME_EGP to "Egyptian pound",
    TextKey.HERO_WITH_YOU to "With you now",
    TextKey.HERO_CASH_CHIP to "Includes {0} cash",
    TextKey.HERO_BANKS_TITLE to "Where is your money now?",
    TextKey.HERO_BANKS_LABEL to "Banks in “With you now”: {0}",
    TextKey.HERO_BANK_SUB to "Bank account",
    TextKey.HERO_DIGITAL_SUB to "Digital wallet",
    TextKey.HERO_CASH_SUB to "In your pocket",
    TextKey.HERO_LOGO_NOTE to "Each bank's logo replaces the letter once the logo research is approved.",
    TextKey.HERO_NA_LINE to "A wallet's balance isn't available yet — it starts from the day it was opened in the app.",
)
