package app.masroufy.core

/**
 * إجابات المساعد «مصروفي» (§78): الصرف · الدخل · الميزانية · الكاش والأرصدة. كل `{n}` رقم أو اسم جاي من حالة استخدام زي ما هو —
 * النص بس هو اللي هنا. «غير متاح» لما الرقم مجهول (القاعدة 10). فصحى للسعودية · مصري لمصر · إنجليزي.
 */
internal val MSA_ASSIST_ANSWER_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_NA to "غير متاح.",
    TextKey.ASSIST_SPENT to "صرفت {0} {1}.",
    TextKey.ASSIST_SPENT_UNKNOWN to "صرفك {0} غير متاح: {1} عملية تحتاج تأكيدًا أولًا.",
    TextKey.ASSIST_SPENT_NA to "صرفك {0} غير متاح: بعض العمليات غير مصنّفة.",
    TextKey.ASSIST_PARTIAL to "(تقريبي — {0} عملية تحتاج تأكيدًا.)",
    TextKey.ASSIST_EXCLUDED to "و{0} مستبعدة من المصروف.",
    TextKey.ASSIST_SPENT_CATEGORY to "صرفت {0} على {1} {2} ({3}).",
    TextKey.ASSIST_CATEGORY_UNKNOWN to "صرفك على {0} {1} غير متاح: العمليات غير مصنّفة.",
    TextKey.ASSIST_OF_CAP to "من سقف {0} ({1}%).",
    TextKey.ASSIST_SPENT_MERCHANT to "دفعت {0} عند {1} {2} ({3}).",
    TextKey.ASSIST_MERCHANT_UNKNOWN to "صرفك عند {0} {1} غير متاح.",
    TextKey.ASSIST_PERSON_SPEND to "{0}: هدايا لـ{1} {2} ({3})، وسلف {4} ({5}).",
    TextKey.ASSIST_BIGGEST to "أكثر ما صرفت عليه {0}: {1}.",
    TextKey.ASSIST_BIGGEST_NONE to "لا يوجد مصروف مصنّف {0}.",
    TextKey.ASSIST_COMPARE_MORE to "صرفت {0} {1} مقابل {2} {3} — أكثر بـ{4}.",
    TextKey.ASSIST_COMPARE_LESS to "صرفت {0} {1} مقابل {2} {3} — أقل بـ{4}.",
    TextKey.ASSIST_COMPARE_SAME to "صرفت {0} {1}، مثل {3} تمامًا.",
    TextKey.ASSIST_COMPARE_NA to "المقارنة غير متاحة: صرف إحدى الفترتين غير معروف.",
    TextKey.ASSIST_PERIOD_BEFORE_IT to "في الفترة السابقة",
    TextKey.ASSIST_INCOME to "دخلك {0}: {1}.",
    TextKey.ASSIST_INCOME_NA to "دخلك {0} غير متاح: {1} عملية تحتاج تأكيدًا.",
    TextKey.ASSIST_INCOME_UNKNOWN to "دخلك {0} غير متاح.",
    TextKey.ASSIST_CASH_FLOW to "حركة الفلوس: دخل {0} وخرج {1} — وهي غير الدخل الحقيقي.",
    TextKey.ASSIST_REMAINING_CAP to "بقي {0} من ميزانية {1}.",
    TextKey.ASSIST_OVER_CAP to "تجاوزت ميزانية {0} بـ{1}.",
    TextKey.ASSIST_PER_DAY to "نحو {0} في اليوم لـ{1}.",
    TextKey.ASSIST_LEFTOVER to "يتبقى لك تقريبًا {0} حتى {1}.",
    TextKey.ASSIST_PERIOD_END to "نهاية الشهر",
    TextKey.ASSIST_REMAINING_NA to "المتبقي غير متاح: لا توجد ميزانية، والرصيد أو المصروف غير معروف.",
    TextKey.ASSIST_ALLOWANCE to "تستطيع أن تصرف نحو {0} في اليوم لـ{1}.",
    TextKey.ASSIST_ALLOWANCE_NA to "المتاح في اليوم غير متاح: {0}",
    TextKey.ASSIST_FORECAST to "بهذا المعدل يصل صرفك إلى نحو {0} بنهاية الشهر.",
    TextKey.ASSIST_NO_BUDGET to "لا توجد ميزانية لهذا الشهر.",
    TextKey.ASSIST_BUDGET_UNDER to "أنت على الخطة: صرفت {0} من {1}.",
    TextKey.ASSIST_BUDGET_NEAR to "اقتربت من الحد: صرفت {0} من {1}.",
    TextKey.ASSIST_BUDGET_OVER to "تجاوزت الميزانية: صرفت {0} من {1}.",
    TextKey.ASSIST_AT_THRESHOLD to "وصلت حد التنبيه: {0}.",
    TextKey.ASSIST_CATEGORY_CAP to "{0}: صرفت {1} من {2}، وبقي {3}.",
    TextKey.ASSIST_CATEGORY_CAP_OVER to "{0}: صرفت {1} من {2}، وتجاوزته بـ{3}.",
    TextKey.ASSIST_NO_CATEGORY_CAP to "لا سقف لـ{0} هذا الشهر.",
    TextKey.ASSIST_CASH to "معك كاش {0}، وصرفت منه {1} {2}.",
    TextKey.ASSIST_NO_CASH to "لا توجد محفظة كاش.",
    TextKey.ASSIST_ON_HAND to "معك الآن {0} في حساباتك.",
    TextKey.ASSIST_ON_HAND_NA to "رصيدك الآن غير متاح: رصيد حساب واحد على الأقل غير معروف.",
    TextKey.ASSIST_WALLET_BALANCE to "رصيد {0}: {1}.",
    TextKey.ASSIST_WALLET_NA to "رصيد {0} غير متاح.",
)

internal val EGYPTIAN_ASSIST_ANSWER_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_NA to "مش متاح.",
    TextKey.ASSIST_SPENT to "صرفت {0} {1}.",
    TextKey.ASSIST_SPENT_UNKNOWN to "صرفك {0} مش متاح: فيه {1} عملية محتاجة تأكيد الأول.",
    TextKey.ASSIST_SPENT_NA to "صرفك {0} مش متاح: فيه عمليات مش متصنفة.",
    TextKey.ASSIST_PARTIAL to "(تقريبي — {0} عملية محتاجة تأكيد.)",
    TextKey.ASSIST_EXCLUDED to "و{0} متشالة من المصروف.",
    TextKey.ASSIST_SPENT_CATEGORY to "صرفت {0} على {1} {2} ({3}).",
    TextKey.ASSIST_CATEGORY_UNKNOWN to "صرفك على {0} {1} مش متاح: العمليات مش متصنفة.",
    TextKey.ASSIST_OF_CAP to "من سقف {0} ({1}%).",
    TextKey.ASSIST_SPENT_MERCHANT to "دفعت {0} عند {1} {2} ({3}).",
    TextKey.ASSIST_MERCHANT_UNKNOWN to "صرفك عند {0} {1} مش متاح.",
    TextKey.ASSIST_PERSON_SPEND to "{0}: هدايا لـ{1} {2} ({3})، وسلف {4} ({5}).",
    TextKey.ASSIST_BIGGEST to "أكتر حاجة صرفت عليها {0}: {1}.",
    TextKey.ASSIST_BIGGEST_NONE to "مفيش مصروف متصنف {0}.",
    TextKey.ASSIST_COMPARE_MORE to "صرفت {0} {1} قصاد {2} {3} — أكتر بـ{4}.",
    TextKey.ASSIST_COMPARE_LESS to "صرفت {0} {1} قصاد {2} {3} — أقل بـ{4}.",
    TextKey.ASSIST_COMPARE_SAME to "صرفت {0} {1}، زي {3} بالظبط.",
    TextKey.ASSIST_COMPARE_NA to "المقارنة مش متاحة: صرف واحدة من الفترتين مش معروف.",
    TextKey.ASSIST_PERIOD_BEFORE_IT to "في اللي قبله",
    TextKey.ASSIST_INCOME to "دخلك {0}: {1}.",
    TextKey.ASSIST_INCOME_NA to "دخلك {0} مش متاح: فيه {1} عملية محتاجة تأكيد.",
    TextKey.ASSIST_INCOME_UNKNOWN to "دخلك {0} مش متاح.",
    TextKey.ASSIST_CASH_FLOW to "حركة الفلوس: دخل {0} وطلع {1} — ودي غير الدخل الحقيقي.",
    TextKey.ASSIST_REMAINING_CAP to "فاضل {0} من ميزانية {1}.",
    TextKey.ASSIST_OVER_CAP to "عدّيت ميزانية {0} بـ{1}.",
    TextKey.ASSIST_PER_DAY to "حوالي {0} في اليوم لـ{1}.",
    TextKey.ASSIST_LEFTOVER to "فاضلك تقريبًا {0} لحد {1}.",
    TextKey.ASSIST_PERIOD_END to "آخر الشهر",
    TextKey.ASSIST_REMAINING_NA to "الفاضل مش متاح: مفيش ميزانية، والرصيد أو المصروف مش معروف.",
    TextKey.ASSIST_ALLOWANCE to "تقدر تصرف حوالي {0} في اليوم لـ{1}.",
    TextKey.ASSIST_ALLOWANCE_NA to "المتاح في اليوم مش متاح: {0}",
    TextKey.ASSIST_FORECAST to "بالمعدل ده صرفك هيوصل لحوالي {0} آخر الشهر.",
    TextKey.ASSIST_NO_BUDGET to "مفيش ميزانية للشهر ده.",
    TextKey.ASSIST_BUDGET_UNDER to "إنت ماشي على الخطة: صرفت {0} من {1}.",
    TextKey.ASSIST_BUDGET_NEAR to "قرّبت من الحد: صرفت {0} من {1}.",
    TextKey.ASSIST_BUDGET_OVER to "عدّيت الميزانية: صرفت {0} من {1}.",
    TextKey.ASSIST_AT_THRESHOLD to "وصلوا حد التنبيه: {0}.",
    TextKey.ASSIST_CATEGORY_CAP to "{0}: صرفت {1} من {2}، وفاضل {3}.",
    TextKey.ASSIST_CATEGORY_CAP_OVER to "{0}: صرفت {1} من {2}، وعدّيته بـ{3}.",
    TextKey.ASSIST_NO_CATEGORY_CAP to "مفيش سقف لـ{0} الشهر ده.",
    TextKey.ASSIST_CASH to "معاك كاش {0}، وصرفت منه {1} {2}.",
    TextKey.ASSIST_NO_CASH to "مفيش محفظة كاش.",
    TextKey.ASSIST_ON_HAND to "معاك دلوقتي {0} في حساباتك.",
    TextKey.ASSIST_ON_HAND_NA to "رصيدك دلوقتي مش متاح: رصيد حساب واحد على الأقل مش معروف.",
    TextKey.ASSIST_WALLET_BALANCE to "رصيد {0}: {1}.",
    TextKey.ASSIST_WALLET_NA to "رصيد {0} مش متاح.",
)

internal val ENGLISH_ASSIST_ANSWER_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ASSIST_NA to "Not available.",
    TextKey.ASSIST_SPENT to "You spent {0} {1}.",
    TextKey.ASSIST_SPENT_UNKNOWN to "Your spending {0} is not available: {1} transactions need confirming first.",
    TextKey.ASSIST_SPENT_NA to "Your spending {0} is not available: some transactions are not classified.",
    TextKey.ASSIST_PARTIAL to "(approximate — {0} transactions need confirming.)",
    TextKey.ASSIST_EXCLUDED to "Plus {0} excluded from spending.",
    TextKey.ASSIST_SPENT_CATEGORY to "You spent {0} on {1} {2} ({3}).",
    TextKey.ASSIST_CATEGORY_UNKNOWN to "Your spending on {0} {1} is not available: transactions are not classified.",
    TextKey.ASSIST_OF_CAP to "Of a {0} cap ({1}%).",
    TextKey.ASSIST_SPENT_MERCHANT to "You paid {0} at {1} {2} ({3}).",
    TextKey.ASSIST_MERCHANT_UNKNOWN to "Your spending at {0} {1} is not available.",
    TextKey.ASSIST_PERSON_SPEND to "{0}: gifts to {1} {2} ({3}), loans {4} ({5}).",
    TextKey.ASSIST_BIGGEST to "Where most of your money went {0}: {1}.",
    TextKey.ASSIST_BIGGEST_NONE to "No classified spending {0}.",
    TextKey.ASSIST_COMPARE_MORE to "You spent {0} {1} against {2} {3} — {4} more.",
    TextKey.ASSIST_COMPARE_LESS to "You spent {0} {1} against {2} {3} — {4} less.",
    TextKey.ASSIST_COMPARE_SAME to "You spent {0} {1}, exactly as {3}.",
    TextKey.ASSIST_COMPARE_NA to "The comparison is not available: one period's spending is unknown.",
    TextKey.ASSIST_PERIOD_BEFORE_IT to "the period before",
    TextKey.ASSIST_INCOME to "Your income {0}: {1}.",
    TextKey.ASSIST_INCOME_NA to "Your income {0} is not available: {1} transactions need confirming.",
    TextKey.ASSIST_INCOME_UNKNOWN to "Your income {0} is not available.",
    TextKey.ASSIST_CASH_FLOW to "Money movement: {0} in and {1} out — not the same as real income.",
    TextKey.ASSIST_REMAINING_CAP to "{0} left of a {1} budget.",
    TextKey.ASSIST_OVER_CAP to "You went over the {0} budget by {1}.",
    TextKey.ASSIST_PER_DAY to "About {0} a day for {1}.",
    TextKey.ASSIST_LEFTOVER to "You have about {0} left until {1}.",
    TextKey.ASSIST_PERIOD_END to "the end of the month",
    TextKey.ASSIST_REMAINING_NA to "What's left is not available: no budget, and the balance or spending is unknown.",
    TextKey.ASSIST_ALLOWANCE to "You can spend about {0} a day for {1}.",
    TextKey.ASSIST_ALLOWANCE_NA to "The daily allowance is not available: {0}",
    TextKey.ASSIST_FORECAST to "At this pace your spending reaches about {0} by the end of the month.",
    TextKey.ASSIST_NO_BUDGET to "There is no budget for this month.",
    TextKey.ASSIST_BUDGET_UNDER to "You're on plan: spent {0} of {1}.",
    TextKey.ASSIST_BUDGET_NEAR to "You're close to the limit: spent {0} of {1}.",
    TextKey.ASSIST_BUDGET_OVER to "You're over budget: spent {0} of {1}.",
    TextKey.ASSIST_AT_THRESHOLD to "At their alert threshold: {0}.",
    TextKey.ASSIST_CATEGORY_CAP to "{0}: spent {1} of {2}, {3} left.",
    TextKey.ASSIST_CATEGORY_CAP_OVER to "{0}: spent {1} of {2}, over by {3}.",
    TextKey.ASSIST_NO_CATEGORY_CAP to "{0} has no cap this month.",
    TextKey.ASSIST_CASH to "You have {0} in cash, and spent {1} of it {2}.",
    TextKey.ASSIST_NO_CASH to "There is no cash wallet.",
    TextKey.ASSIST_ON_HAND to "You have {0} across your accounts now.",
    TextKey.ASSIST_ON_HAND_NA to "Your balance now is not available: at least one account balance is unknown.",
    TextKey.ASSIST_WALLET_BALANCE to "{0} balance: {1}.",
    TextKey.ASSIST_WALLET_NA to "{0} balance is not available.",
)
