package app.masroufy.core

/**
 * نصوص «حساب لكل بلد» (OVERRIDES §41 · §64) باللغتين — بيتدمجوا في `EGYPTIAN_TEXTS` و`ENGLISH_TEXTS`.
 * اسم البلد بيظهر **جوه التطبيق بس** — نصوص شاشة القفل ما اتغيرتش (مفيش اسم بلد عليها). الإنجليزي كتابة Claude ومستني مراجعة المالك (§40).
 */
internal val EGYPTIAN_SPACE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.COUNTRY_SA to "السعودية",
    TextKey.COUNTRY_EG to "مصر",
    TextKey.SPACE_COUNTRY_UNKNOWN to "البلد دي لسه مش مدعومة",
    TextKey.SPACE_COUNTRY_TAKEN to "عندك حساب «{0}» قبل كده — كل بلد ليها حساب واحد",
    TextKey.SPACE_NOT_FOUND to "الحساب ده مش موجود",
    TextKey.SPACE_DEFAULT_FIXED to "حساب السعودية الأساسي ما بيتأرشفش",
    TextKey.BACKUP_GROUP_MERCHANT_CATEGORIES to "تصنيفات التجار في البلد",
    TextKey.SPACE_TRANSFER_SAME_SPACE to "التحويل لنفسك بيبقى بين بلدين مختلفين",
    TextKey.SPACE_TRANSFER_NEEDS_OUT to "العملية في البلد اللي الفلوس طلعت منها لازم تكون صادرة",
    TextKey.SPACE_TRANSFER_NEEDS_IN to "العملية في البلد اللي الفلوس وصلت لها لازم تكون واردة",
    TextKey.SPACE_TRANSFER_AMOUNT to "المبلغ لازم يكون أكبر من صفر",
    TextKey.SPACE_TRANSFER_WALLET to "اختار محفظة موجودة في البلد دي",
    TextKey.SPACE_TRANSFER_CURRENCY to "عملة العملية لازم تبقى نفس عملة محفظتها",
    TextKey.SPACE_TRANSFER_ALREADY to "العملية دي متربطة بتحويل لنفسك قبل كده",
    TextKey.SPACE_TRANSFER_LINKED to "العملية دي متربطة بحاجة تانية (مستحقات أو زكاة أو حدث أو مشروع أو شخص) — فكّها الأول",
    TextKey.SPACE_TRANSFER_NOT_FOUND to "التحويل ده مش موجود",
    TextKey.SPACE_TRANSFER_TXN_NOT_FOUND to "العملية مش موجودة في البلد دي",
    TextKey.SPACE_TRANSFER_DATE to "التاريخ مش صالح",
    TextKey.ZAKAT_THIS_COUNTRY_ONLY to "الحساب ده على فلوسك في البلد دي بس",
    TextKey.BACKUP_SPACE_INVALID to "بيانات البلد «{0}» في النسخة مش سليمة",
    TextKey.BACKUP_SPACE_TRANSFER_INVALID to "تحويل لنفسك في النسخة مش سليم ({0})",
    TextKey.BACKUP_GROUP_SPACE_TRANSFERS to "التحويل لنفسك بين البلاد",
    TextKey.SPACE_TRANSFER_NOTE_LONG to "الملاحظة أطول من 1000 حرف",
    TextKey.SPACE_TRANSFER_LEG_LOCKED to "العملية دي تحويل لنفسك لبلد تانية — فك الربط الأول لو عايز تغيّر نوعها أو تربطها بحاجة تانية",
    TextKey.CATEGORIZED_MERCHANT_OTHER_COUNTRY to "التاجر «{0}» متصنف كده في بلدك التانية — اقتراح، أكّده لو صح",
)

internal val ENGLISH_SPACE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.COUNTRY_SA to "Saudi Arabia",
    TextKey.COUNTRY_EG to "Egypt",
    TextKey.SPACE_COUNTRY_UNKNOWN to "This country is not supported yet",
    TextKey.SPACE_COUNTRY_TAKEN to "You already have a “{0}” account — one account per country",
    TextKey.SPACE_NOT_FOUND to "This account was not found",
    TextKey.SPACE_DEFAULT_FIXED to "The main Saudi account cannot be archived",
    TextKey.BACKUP_GROUP_MERCHANT_CATEGORIES to "Merchant categories in this country",
    TextKey.SPACE_TRANSFER_SAME_SPACE to "A transfer to yourself goes between two different countries",
    TextKey.SPACE_TRANSFER_NEEDS_OUT to "The transaction in the sending country must be outgoing",
    TextKey.SPACE_TRANSFER_NEEDS_IN to "The transaction in the receiving country must be incoming",
    TextKey.SPACE_TRANSFER_AMOUNT to "The amount must be greater than zero",
    TextKey.SPACE_TRANSFER_WALLET to "Pick a wallet that exists in this country",
    TextKey.SPACE_TRANSFER_CURRENCY to "The transaction currency must match its wallet",
    TextKey.SPACE_TRANSFER_ALREADY to "This transaction is already part of a transfer to yourself",
    TextKey.SPACE_TRANSFER_LINKED to "This transaction is linked to something else (dues, zakat, an event, a project or a person) — unlink it first",
    TextKey.SPACE_TRANSFER_NOT_FOUND to "This transfer was not found",
    TextKey.SPACE_TRANSFER_TXN_NOT_FOUND to "The transaction was not found in this country",
    TextKey.SPACE_TRANSFER_DATE to "The date is not valid",
    TextKey.ZAKAT_THIS_COUNTRY_ONLY to "This calculation covers your money in this country only",
    TextKey.BACKUP_SPACE_INVALID to "The country “{0}” in the backup is not valid",
    TextKey.BACKUP_SPACE_TRANSFER_INVALID to "A transfer to yourself in the backup is not valid ({0})",
    TextKey.BACKUP_GROUP_SPACE_TRANSFERS to "Transfers to yourself between countries",
    TextKey.SPACE_TRANSFER_NOTE_LONG to "The note is longer than 1000 characters",
    TextKey.SPACE_TRANSFER_LEG_LOCKED to "This transaction is a transfer to yourself in another country — unlink it first to change its kind or link it to something else",
    TextKey.CATEGORIZED_MERCHANT_OTHER_COUNTRY to "The store “{0}” has this category in your other country — a suggestion, confirm it if right",
)

/** «حساب لكل بلد» بالفصحى المختصرة (OVERRIDES §66). */
internal val MSA_SPACE_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.COUNTRY_SA to "السعودية",
    TextKey.COUNTRY_EG to "مصر",
    TextKey.SPACE_COUNTRY_UNKNOWN to "هذا البلد غير مدعوم بعد",
    TextKey.SPACE_COUNTRY_TAKEN to "لديك حساب «{0}» سابقًا — لكل بلد حساب واحد",
    TextKey.SPACE_NOT_FOUND to "هذا الحساب غير موجود",
    TextKey.SPACE_DEFAULT_FIXED to "حساب السعودية الأساسي لا يُؤرشف",
    TextKey.BACKUP_GROUP_MERCHANT_CATEGORIES to "تصنيفات التجار في البلد",
    TextKey.SPACE_TRANSFER_SAME_SPACE to "التحويل لنفسك يكون بين بلدين مختلفين",
    TextKey.SPACE_TRANSFER_NEEDS_OUT to "يجب أن تكون العملية في بلد الإرسال صادرة",
    TextKey.SPACE_TRANSFER_NEEDS_IN to "يجب أن تكون العملية في بلد الاستلام واردة",
    TextKey.SPACE_TRANSFER_AMOUNT to "يجب أن يكون المبلغ أكبر من صفر",
    TextKey.SPACE_TRANSFER_WALLET to "اختر محفظة موجودة في هذا البلد",
    TextKey.SPACE_TRANSFER_CURRENCY to "يجب أن تطابق عملة العملية عملة محفظتها",
    TextKey.SPACE_TRANSFER_ALREADY to "هذه العملية مرتبطة بتحويل لنفسك سابقًا",
    TextKey.SPACE_TRANSFER_LINKED to "هذه العملية مرتبطة بشيء آخر (مستحقات أو زكاة أو حدث أو مشروع أو شخص) — فُكّ الربط أولًا",
    TextKey.SPACE_TRANSFER_NOT_FOUND to "هذا التحويل غير موجود",
    TextKey.SPACE_TRANSFER_TXN_NOT_FOUND to "العملية غير موجودة في هذا البلد",
    TextKey.SPACE_TRANSFER_DATE to "التاريخ غير صالح",
    TextKey.ZAKAT_THIS_COUNTRY_ONLY to "هذا الحساب لأموالك في هذا البلد فقط",
    TextKey.BACKUP_SPACE_INVALID to "بيانات البلد «{0}» في النسخة غير سليمة",
    TextKey.BACKUP_SPACE_TRANSFER_INVALID to "تحويل لنفسك في النسخة غير سليم ({0})",
    TextKey.BACKUP_GROUP_SPACE_TRANSFERS to "التحويل لنفسك بين البلدان",
    TextKey.SPACE_TRANSFER_NOTE_LONG to "الملاحظة أطول من 1000 حرف",
    TextKey.SPACE_TRANSFER_LEG_LOCKED to "هذه العملية تحويل لنفسك إلى بلد آخر — فُكّ الربط أولًا لتغيير نوعها أو ربطها بشيء آخر",
    TextKey.CATEGORIZED_MERCHANT_OTHER_COUNTRY to "التاجر «{0}» مصنَّف هكذا في بلدك الآخر — اقتراح، أكّده إن كان صحيحًا",
)
