package app.masroufy.core

/**
 * نصوص §69.4: ذوو الأرحام · الحسبة المحفوظة · تنبيه مصر «إعلام الوراثة» · «ممكن يختلف عن حكم المحكمة» — فصحى (§66) · مصري · إنجليزي.
 * - التنبيهين تحت النتيجة وملاحظة النص الغامض **بكلام المالك بالحرف** (رد صفحة `inherit` — §69.3).
 * - المصطلح الفقهي بين قوسين بعد شرح بسيط (§66 — الكلمات الثقيلة).
 */
internal val MSA_INHERITANCE_DISTANT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INHERIT_DISCLAIMER_EG to "حساب تقريبي للتخطيط، والقسمة الرسمية بإعلام الوراثة من المحكمة",
    TextKey.INHERIT_HEIR_DAUGHTER_SON to "ابن البنت",
    TextKey.INHERIT_HEIR_DAUGHTER_DAUGHTER to "بنت البنت",
    TextKey.INHERIT_HEIR_SON_DAUGHTER_SON to "ابن بنت الابن",
    TextKey.INHERIT_HEIR_SON_DAUGHTER_DAUGHTER to "بنت بنت الابن",
    TextKey.INHERIT_HEIR_FULL_SISTER_SON to "ابن الأخت الشقيقة",
    TextKey.INHERIT_HEIR_FULL_SISTER_DAUGHTER to "بنت الأخت الشقيقة",
    TextKey.INHERIT_HEIR_PATERNAL_SISTER_SON to "ابن الأخت من الأب",
    TextKey.INHERIT_HEIR_PATERNAL_SISTER_DAUGHTER to "بنت الأخت من الأب",
    TextKey.INHERIT_HEIR_FULL_BROTHER_DAUGHTER to "بنت الأخ الشقيق",
    TextKey.INHERIT_HEIR_PATERNAL_BROTHER_DAUGHTER to "بنت الأخ من الأب",
    TextKey.INHERIT_HEIR_MATERNAL_BROTHER_SON to "ابن الأخ من الأم",
    TextKey.INHERIT_HEIR_MATERNAL_BROTHER_DAUGHTER to "بنت الأخ من الأم",
    TextKey.INHERIT_HEIR_MATERNAL_SISTER_SON to "ابن الأخت من الأم",
    TextKey.INHERIT_HEIR_MATERNAL_SISTER_DAUGHTER to "بنت الأخت من الأم",
    TextKey.INHERIT_HEIR_MATERNAL_GRANDFATHER to "الجد (أبو الأم)",
    TextKey.INHERIT_HEIR_MATERNAL_UNCLE_FULL to "الخال الشقيق (أخو الأم)",
    TextKey.INHERIT_HEIR_MATERNAL_UNCLE_PATERNAL to "الخال من الأب (أخو الأم من أبيها)",
    TextKey.INHERIT_HEIR_MATERNAL_UNCLE_MATERNAL to "الخال من الأم (أخو الأم من أمها)",
    TextKey.INHERIT_HEIR_MATERNAL_AUNT_FULL to "الخالة الشقيقة (أخت الأم)",
    TextKey.INHERIT_HEIR_MATERNAL_AUNT_PATERNAL to "الخالة من الأب (أخت الأم من أبيها)",
    TextKey.INHERIT_HEIR_MATERNAL_AUNT_MATERNAL to "الخالة من الأم (أخت الأم من أمها)",
    TextKey.INHERIT_HEIR_PATERNAL_AUNT_FULL to "العمة الشقيقة (أخت الأب)",
    TextKey.INHERIT_HEIR_PATERNAL_AUNT_PATERNAL to "العمة من الأب (أخت الأب من أبيه)",
    TextKey.INHERIT_HEIR_PATERNAL_AUNT_MATERNAL to "العمة من الأم (أخت الأب من أمه)",
    TextKey.INHERIT_HEIR_MATERNAL_HALF_UNCLE to "العم من الأم (أخو الأب من أمه)",
    TextKey.INHERIT_NOTE_DISTANT_EXCLUDED to "الأقارب الذين ليس لهم نصيب محدد ولا يأخذون الباقي (ذوو الأرحام) لا يرثون مع وجود صاحب نصيب أو من يأخذ الباقي",
    TextKey.INHERIT_NOTE_DISTANT_TANZIL to "{0} يأخذ نصيب {1} الذي يصله بالمتوفى، والذكر مثل الأنثى (التنزيل)",
    TextKey.INHERIT_NOTE_DISTANT_EGYPT_ORDER to "الأقارب (ذوو الأرحام) يرثون بالترتيب: الأقرب صنفًا ثم درجةً ثم الأقوى قرابة، وللذكر مثل حظ الأنثيين",
    TextKey.INHERIT_NOTE_DISTANT_SIDES to "ثلثا نصيبهم لأقارب الأب، والثلث لأقارب الأم",
    TextKey.INHERIT_NOTE_DISTANT_SPOUSE to "أخذ {0} نصيبه كاملًا، والباقي للأقارب (ذوي الأرحام) قبل أن يُرد عليه",
    TextKey.INHERIT_NOTE_UNCLEAR to "قد يختلف عن حكم المحكمة — النص غير واضح في هذه المسألة",
    TextKey.INHERIT_NO_TEXT_DISTANT_NEARNESS to "أقارب من الجهة نفسها، وقربهم من المتوفى يختلف حسب طريقة العدّ، والمادة 236 لا تحدد طريقة العدّ",
    TextKey.INHERIT_NO_TEXT_DISTANT_SAME_PLACE to "أكثر من قريب بصلات مختلفة يقومون مقام الشخص نفسه، والمادة 235 لا تبيّن كيف يُقسم نصيبه بينهم",
    TextKey.INHERIT_NO_TEXT_DISTANT_SIDES_BLOCKING to "قريب يمنعه من الإرث قريبٌ من جهة أخرى؛ المادة 235 تمنعه (إرثًا وحجبًا)، والمادة 236 تورّث الجهات المختلفة معًا",
    TextKey.INHERIT_UNSUPPORTED_DISTANT_UNLISTED to "يرث هنا أقارب آخرون (ذوو الأرحام)؛ اكتبهم في قائمة الورثة إن كانوا منها (أولاد البنات والأخوات، الخال، العمة …)، ومن ليس في القائمة لا تحسبه هذه النسخة",
    TextKey.INHERIT_UNSUPPORTED_ASK_BRANCHES to "كل واحد يأخذ نصيب من يصله بالمتوفى؛ اكتب أولاد كل واحد من ({0}) وحده",
    TextKey.INHERIT_UNSUPPORTED_WAJIBA_DISTANT to "يرث هنا الأقارب (ذوو الأرحام)، والوصية الواجبة معهم لا تحسبها هذه النسخة",
    TextKey.INHERIT_INVALID_BRANCHES to "أولاد كل واحد من ({0}) لا يطابقون الأعداد المكتوبة",
    TextKey.INHERIT_SCENARIO_NAME_REQUIRED to "اكتب اسمًا للحسبة",
    TextKey.INHERIT_SCENARIO_NAME_LENGTH to "اسم الحسبة {0} حرفًا على الأكثر",
    TextKey.INHERIT_SCENARIO_NOT_FOUND to "الحسبة غير موجودة",
    TextKey.INHERIT_SCENARIO_PERSON_MINE to "تركتك أنت لا تُربط بشخص آخر",
    TextKey.INHERIT_SCENARIO_COUNTRY to "حاسبة الورث متاحة للسعودية ومصر فقط",
    TextKey.BACKUP_GROUP_INHERITANCE_SCENARIOS to "حسابات الإرث المحفوظة",
)

internal val EGYPTIAN_INHERITANCE_DISTANT_TEXTS: Map<TextKey, String> = MSA_INHERITANCE_DISTANT_TEXTS + mapOf(
    TextKey.INHERIT_HEIR_MATERNAL_UNCLE_PATERNAL to "الخال من الأب (أخو الأم من أبوها)",
    TextKey.INHERIT_HEIR_MATERNAL_AUNT_PATERNAL to "الخالة من الأب (أخت الأم من أبوها)",
    TextKey.INHERIT_HEIR_PATERNAL_AUNT_PATERNAL to "العمة من الأب (أخت الأب من أبوه)",
    TextKey.INHERIT_NOTE_DISTANT_EXCLUDED to "القرايب اللي مالهمش نصيب محدد ولا بياخدوا الباقي (ذوو الأرحام) مش بيورثوا طول ما فيه صاحب نصيب أو حد بياخد الباقي",
    TextKey.INHERIT_NOTE_DISTANT_TANZIL to "{0} بياخد نصيب {1} اللي بيوصله بالمتوفى، والولد زي البنت (التنزيل)",
    TextKey.INHERIT_NOTE_DISTANT_EGYPT_ORDER to "القرايب (ذوو الأرحام) بيورثوا بالترتيب: الأقرب صنف وبعدين درجة وبعدين الأقوى قرابة، وللولد ضعف البنت",
    TextKey.INHERIT_NOTE_DISTANT_SIDES to "تلتين نصيبهم لقرايب الأب، والتلت لقرايب الأم",
    TextKey.INHERIT_NOTE_DISTANT_SPOUSE to "{0} خد نصيبه كامل، والباقي للقرايب (ذوي الأرحام) قبل ما يرجع له",
    TextKey.INHERIT_NOTE_UNCLEAR to "ممكن يختلف عن حكم المحكمة — النص مش واضح في المسألة دي",
    TextKey.INHERIT_NO_TEXT_DISTANT_NEARNESS to "قرايب من نفس الجهة، وقربهم من المتوفى بيختلف حسب طريقة العد، والمادة 236 مش بتحدد طريقة العد",
    TextKey.INHERIT_NO_TEXT_DISTANT_SAME_PLACE to "أكتر من قريب بصلات مختلفة في مكان نفس الشخص، والمادة 235 مش بتقول نصيبه يتقسم بينهم إزاي",
    TextKey.INHERIT_NO_TEXT_DISTANT_SIDES_BLOCKING to "قريب بيمنعه من الورث قريب من جهة تانية؛ المادة 235 بتمنعه (إرثًا وحجبًا)، والمادة 236 بتورّث الجهات المختلفة مع بعض",
    TextKey.INHERIT_UNSUPPORTED_DISTANT_UNLISTED to "فيه قرايب تانيين بيورثوا هنا (ذوو الأرحام)؛ اكتبهم في قايمة الورثة لو منها (أولاد البنات والأخوات، الخال، العمة …)، واللي مش في القايمة النسخة دي مش بتحسبه",
    TextKey.INHERIT_UNSUPPORTED_ASK_BRANCHES to "كل واحد بياخد نصيب اللي بيوصله بالمتوفى؛ اكتب أولاد كل واحد من ({0}) لوحده",
    TextKey.INHERIT_UNSUPPORTED_WAJIBA_DISTANT to "هنا القرايب (ذوو الأرحام) هم اللي بيورثوا، والوصية الواجبة معاهم النسخة دي مش بتحسبها",
    TextKey.INHERIT_INVALID_BRANCHES to "أولاد كل واحد من ({0}) مش مطابقين للأعداد المكتوبة",
    TextKey.INHERIT_SCENARIO_NAME_REQUIRED to "اكتب اسم للحسبة",
    TextKey.INHERIT_SCENARIO_NAME_LENGTH to "اسم الحسبة {0} حرف بالكتير",
    TextKey.INHERIT_SCENARIO_NOT_FOUND to "الحسبة مش موجودة",
    TextKey.INHERIT_SCENARIO_PERSON_MINE to "تركتك انت مش بتتربط بشخص تاني",
    TextKey.INHERIT_SCENARIO_COUNTRY to "حاسبة الورث متاحة للسعودية ومصر بس",
    TextKey.BACKUP_GROUP_INHERITANCE_SCENARIOS to "حسابات الورث المتحفظة",
)

/** بالإنجليزي — كتابة Claude ومستنية مراجعة المالك (§40). */
internal val ENGLISH_INHERITANCE_DISTANT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.INHERIT_DISCLAIMER_EG to "An approximate figure for planning; the official division is the court's declaration of heirs (i'lam al-wiratha)",
    TextKey.INHERIT_HEIR_DAUGHTER_SON to "Daughter's son",
    TextKey.INHERIT_HEIR_DAUGHTER_DAUGHTER to "Daughter's daughter",
    TextKey.INHERIT_HEIR_SON_DAUGHTER_SON to "Son's daughter's son",
    TextKey.INHERIT_HEIR_SON_DAUGHTER_DAUGHTER to "Son's daughter's daughter",
    TextKey.INHERIT_HEIR_FULL_SISTER_SON to "Full sister's son",
    TextKey.INHERIT_HEIR_FULL_SISTER_DAUGHTER to "Full sister's daughter",
    TextKey.INHERIT_HEIR_PATERNAL_SISTER_SON to "Son of the sister through the father",
    TextKey.INHERIT_HEIR_PATERNAL_SISTER_DAUGHTER to "Daughter of the sister through the father",
    TextKey.INHERIT_HEIR_FULL_BROTHER_DAUGHTER to "Full brother's daughter",
    TextKey.INHERIT_HEIR_PATERNAL_BROTHER_DAUGHTER to "Daughter of the brother through the father",
    TextKey.INHERIT_HEIR_MATERNAL_BROTHER_SON to "Son of the brother through the mother",
    TextKey.INHERIT_HEIR_MATERNAL_BROTHER_DAUGHTER to "Daughter of the brother through the mother",
    TextKey.INHERIT_HEIR_MATERNAL_SISTER_SON to "Son of the sister through the mother",
    TextKey.INHERIT_HEIR_MATERNAL_SISTER_DAUGHTER to "Daughter of the sister through the mother",
    TextKey.INHERIT_HEIR_MATERNAL_GRANDFATHER to "Grandfather (mother's father)",
    TextKey.INHERIT_HEIR_MATERNAL_UNCLE_FULL to "Maternal uncle (mother's full brother)",
    TextKey.INHERIT_HEIR_MATERNAL_UNCLE_PATERNAL to "Maternal uncle (mother's brother through her father)",
    TextKey.INHERIT_HEIR_MATERNAL_UNCLE_MATERNAL to "Maternal uncle (mother's brother through her mother)",
    TextKey.INHERIT_HEIR_MATERNAL_AUNT_FULL to "Maternal aunt (mother's full sister)",
    TextKey.INHERIT_HEIR_MATERNAL_AUNT_PATERNAL to "Maternal aunt (mother's sister through her father)",
    TextKey.INHERIT_HEIR_MATERNAL_AUNT_MATERNAL to "Maternal aunt (mother's sister through her mother)",
    TextKey.INHERIT_HEIR_PATERNAL_AUNT_FULL to "Paternal aunt (father's full sister)",
    TextKey.INHERIT_HEIR_PATERNAL_AUNT_PATERNAL to "Paternal aunt (father's sister through his father)",
    TextKey.INHERIT_HEIR_PATERNAL_AUNT_MATERNAL to "Paternal aunt (father's sister through his mother)",
    TextKey.INHERIT_HEIR_MATERNAL_HALF_UNCLE to "Paternal uncle through the mother (father's brother through his mother)",
    TextKey.INHERIT_NOTE_DISTANT_EXCLUDED to "Relatives with no fixed share who do not take the rest (dhawu al-arham) do not inherit while a share holder or a residuary exists",
    TextKey.INHERIT_NOTE_DISTANT_TANZIL to "The {0} takes the share of the {1} who links them to the deceased, male and female alike (tanzil)",
    TextKey.INHERIT_NOTE_DISTANT_EGYPT_ORDER to "These relatives (dhawu al-arham) inherit in order: nearest class, then degree, then the stronger tie, a male taking twice a female's share",
    TextKey.INHERIT_NOTE_DISTANT_SIDES to "Two thirds of their share go to the father's relatives and one third to the mother's",
    TextKey.INHERIT_NOTE_DISTANT_SPOUSE to "The {0} took the full share, and the rest goes to the other relatives (dhawu al-arham) before anything returns to the {0}",
    TextKey.INHERIT_NOTE_UNCLEAR to "May differ from the court's ruling — the text is not clear on this case",
    TextKey.INHERIT_NO_TEXT_DISTANT_NEARNESS to "Relatives on the same side whose nearness to the deceased depends on how it is counted, and Article 236 does not say how",
    TextKey.INHERIT_NO_TEXT_DISTANT_SAME_PLACE to "More than one relative with different ties stands in the place of the same person, and Article 235 does not say how that share is divided",
    TextKey.INHERIT_NO_TEXT_DISTANT_SIDES_BLOCKING to "A relative is kept from inheriting by a relative on another side; Article 235 excludes them (inheritance and exclusion alike), while Article 236 lets different sides inherit together",
    TextKey.INHERIT_UNSUPPORTED_DISTANT_UNLISTED to "Other relatives (dhawu al-arham) inherit here; add them to the list of heirs if they are in it (children of daughters and sisters, maternal uncles, paternal aunts …) — anyone not in the list is not calculated in this version",
    TextKey.INHERIT_UNSUPPORTED_ASK_BRANCHES to "Each one takes the share of the person who links them to the deceased; enter the children of each ({0}) separately",
    TextKey.INHERIT_UNSUPPORTED_WAJIBA_DISTANT to "Other relatives (dhawu al-arham) inherit here, and an obligatory bequest alongside them is not calculated in this version",
    TextKey.INHERIT_INVALID_BRANCHES to "The children of each ({0}) do not match the numbers entered",
    TextKey.INHERIT_SCENARIO_NAME_REQUIRED to "Give the calculation a name",
    TextKey.INHERIT_SCENARIO_NAME_LENGTH to "The calculation name is {0} characters at most",
    TextKey.INHERIT_SCENARIO_NOT_FOUND to "The calculation was not found",
    TextKey.INHERIT_SCENARIO_PERSON_MINE to "Your own estate is not linked to another person",
    TextKey.INHERIT_SCENARIO_COUNTRY to "The inheritance calculator is available for Saudi Arabia and Egypt only",
    TextKey.BACKUP_GROUP_INHERITANCE_SCENARIOS to "Saved inheritance calculations",
)
