package app.masroufy.core

/** باقي نصوص الواجهة المشتركة **بالإنجليزي** — كتابة Claude ومستنية مراجعة المالك (OVERRIDES §40). */
internal val ENGLISH_SHELL_AUTH_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.UPCOMING_TITLE to "Coming up",
    TextKey.UPCOMING_LIST to "Upcoming dates",
    TextKey.UPCOMING_TODAY to "Today",
    TextKey.UPCOMING_TOMORROW to "Tomorrow",
    TextKey.UPCOMING_TWO_DAYS to "In 2 days",
    TextKey.UPCOMING_FEW_DAYS to "In {0} days",
    TextKey.UPCOMING_MANY_DAYS to "In {0} days",
    TextKey.UPCOMING_HELD to "Set aside",
    TextKey.UPCOMING_OPEN to "Not set aside",
    TextKey.UPCOMING_NO_AMOUNT to "No amount",
    TextKey.UPCOMING_INCOMING to "Expected income",
    TextKey.UPCOMING_LATE to "Overdue",
    TextKey.UPCOMING_EMPTY to "No upcoming dates.",
    TextKey.CALENDAR_OPEN to "Calendar",
    TextKey.QUICK_TITLE to "Expected this month, not recorded yet",
    TextKey.QUICK_SHEET_BODY to "The usual amount is filled in — change it if it's different this month.",
    TextKey.QUICK_USUAL to "Usually {0}, on day {1}",
    TextKey.QUICK_FROM to "Paid from?",
    TextKey.QUICK_SAVE to "Record it",
    TextKey.QUICK_SKIP to "Not paying it this month",
    TextKey.QUICK_RECORDED to "Recorded “{0}” {1}",
    TextKey.QUICK_SKIPPED to "OK — we won't ask about it again this month.",
    TextKey.CAL_PREV to "Previous month",
    TextKey.CAL_NEXT to "Next month",
    TextKey.CAL_TODAY to "Today",
    TextKey.CAL_NO_DATES to "No dates",
    TextKey.CAL_LEGEND_SUB to "Subscriptions and bills",
    TextKey.CAL_LEGEND_INST to "Installments",
    TextKey.CAL_LEGEND_ROSCA to "Savings circles",
    TextKey.CAL_LEGEND_DEBT to "Debts",
    TextKey.CAL_LEGEND_EVENT to "Events and occasions",
    TextKey.CAL_LEGEND_PAY to "Payday",
    TextKey.CAL_LEGEND_LATE to "Overdue",
    TextKey.CAL_MORE to "+{0}",
    TextKey.SIGNIN_WELCOME_TITLE to "Welcome to Masroufy",
    TextKey.SIGNIN_WELCOME_SUB to "One minute to set up your account; the rest whenever you like.",
    TextKey.SIGNIN_HOW to "How do you want to sign in?",
    TextKey.SIGNIN_HOW_SUB to "Your account saves your data and syncs it to all your devices.",
    TextKey.SIGNIN_GOOGLE to "Sign in with Google",
    TextKey.SIGNIN_WITH_EMAIL to "Sign in with email",
    TextKey.SIGNIN_TITLE to "Sign in with email",
    TextKey.SIGNIN_MODES to "Sign-in type",
    TextKey.SIGNIN_MODE_IN to "Sign in",
    TextKey.SIGNIN_MODE_NEW to "New account",
    TextKey.SIGNIN_EMAIL to "Email",
    TextKey.SIGNIN_PASSWORD to "Password",
    TextKey.SIGNIN_PASS_HINT to "At least 6 characters.",
    TextKey.SIGNIN_SHOW_PASS to "Show password",
    TextKey.SIGNIN_HIDE_PASS to "Hide password",
    TextKey.SIGNIN_SUBMIT_IN to "Sign in",
    TextKey.SIGNIN_SUBMIT_NEW to "Create account",
    TextKey.SIGNIN_BUSY_IN to "Signing in…",
    TextKey.SIGNIN_BUSY_NEW to "Creating account…",
    TextKey.SIGNIN_OFFLINE_NOTE to "Signing in needs an internet connection.",
    TextKey.SIGNIN_EMULATOR_NOTE to "Test build connected to the Firebase emulator on the computer — fake data only.",
    TextKey.RESET_TRIGGER to "Forgot your password?",
    TextKey.RESET_TITLE to "Reset password",
    TextKey.RESET_BODY to "Enter your email and we'll send it a link to set a new password.",
    TextKey.RESET_EMAIL_EMPTY to "Enter your email",
    TextKey.RESET_SEND to "Send reset link",
    TextKey.RESET_SENDING to "Sending…",
    TextKey.RESET_PRIVACY to "To protect accounts, we don't say whether an email is registered with us.",
    TextKey.RESET_SENT_TITLE to "Check your email",
    TextKey.RESET_SENT_BODY to "If {0} is registered with us, it will get a link to set a new password within minutes.",
    TextKey.RESET_SPAM to "Didn't arrive? Check your spam folder, or send it again.",
    TextKey.RESET_RESEND to "Send again",
    TextKey.RESET_AGAIN to "The link was sent again.",
    TextKey.RESET_WAIT_ONE to "You can send again in 1 second.",
    TextKey.RESET_WAIT_TWO to "You can send again in 2 seconds.",
    TextKey.RESET_WAIT_FEW to "You can send again in {0} seconds.",
    TextKey.RESET_WAIT_MANY to "You can send again in {0} seconds.",
    TextKey.RESET_CHANGE to "Change email",
    TextKey.RESET_FINISH to "Back to sign in",
    TextKey.RESET_OFFLINE to "Sending again needs an internet connection.",
    TextKey.LOCK_SCREEN_TITLE to "Masroufy is locked",
    TextKey.LOCK_SCREEN_BODY to "Unlock with your fingerprint or phone code.",
    TextKey.LOCK_SCREEN_OPEN to "Unlock",
    TextKey.LOCK_RELEASED to "Your phone has no lock, so the app lock was turned off. Turn it on from “More ← Settings” after setting a phone lock.",
    TextKey.FEED_OFFLINE to "No internet — couldn't update the prices.",
    TextKey.FEED_HTTP_FAILED to "Couldn't download the file (response {0}).",
    TextKey.FEED_UPDATED_AT to "Last updated {0}",
    TextKey.AUTH_GOOGLE_NO_ACCOUNT to "There's no Google account on this phone. Add one in the phone settings or sign in with email.",
    TextKey.AUTH_GOOGLE_FAILED to "Couldn't sign in with Google right now. Try again or sign in with email.",
)
