package app.masroufy.core

/**
 * نصوص «دفع زكاة السنة» (`ZakatPay`) و«يوم زكاتك الهجري» (`HawlDaySheet`) و«التحليلات الذكية» (`Advisor`) — جزء من نصوص منطقة الاستثمار.
 * الدفع كاش في كوتلن بيتسجل بالمبلغ والتاريخ بس (من غير عملية في محفظة الكاش) ⇒ النص بيقول كده.
 */
internal val MSA_INVEST_PAY_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ZAKAT_PAY_TITLE to "دفع زكاة السنة",
    UiKey.ZAKAT_PAY_FOR to "السنة التي موعدها {0}",
    UiKey.ZAKAT_PAY_DUE to "المطلوب",
    UiKey.ZAKAT_PAY_PAID to "دُفع",
    UiKey.ZAKAT_PAY_LEFT to "الباقي",
    UiKey.ZAKAT_PAY_ALL_DONE to "دُفعت زكاة هذه السنة كاملة.",
    UiKey.ZAKAT_PAY_ALL_DONE_EXTRA to "دُفعت زكاة هذه السنة كاملة، وصدقة إضافية {0}.",
    UiKey.ZAKAT_PAY_LINE_DONE to "دُفع ✓",
    UiKey.ZAKAT_PAY_LINE_PART to "دُفع {0}، بقي {1}",
    UiKey.ZAKAT_PAY_LINE_NONE to "لم يُدفع بعد",
    UiKey.ZAKAT_PAY_ALL to "دفعت الكل",
    UiKey.ZAKAT_PAY_HOW to "كيف دفعتها؟",
    UiKey.ZAKAT_PAY_FROM_STATEMENT to "من الكشف، تأخذ تصنيف «زكاة»",
    UiKey.ZAKAT_PAY_CASH to "دفعتها كاشًا",
    UiKey.ZAKAT_PAY_CASH_SUB to "بلا عملية — تُسجَّل بالمبلغ والتاريخ فقط",
    UiKey.ZAKAT_PAY_CASH_LABEL to "المبلغ كاشًا",
    UiKey.ZAKAT_PAY_NOTE to "الزكاة المدفوعة مصروف عادي في شهرها بتصنيف «زكاة». يمكن الدفع على مرات بأكثر من عملية.",
    UiKey.ZAKAT_PAY_RECORD to "سجّل الدفعة",
    UiKey.ZAKAT_PAY_ERR_HOW to "اختر العملية التي دفعت بها، أو «دفعتها كاشًا».",
    UiKey.ZAKAT_PAY_ERR_CASH to "اكتب المبلغ الذي دفعته كاشًا.",
    UiKey.ZAKAT_PAY_RECORDED to "سُجّلت الدفعة",
    UiKey.ZAKAT_PAY_PAYMENTS to "الدفعات",
    UiKey.ZAKAT_PAY_UNLINK to "فك",
    UiKey.ZAKAT_PAY_UNLINKED to "فُكّت الدفعة — عادت العملية كما كانت",
    UiKey.ZAKAT_PAY_CASH_ROW to "كاش",
    UiKey.ZAKAT_PAY_NO_OPS to "لا عمليات صرف في هذا الشهر.",
    UiKey.HAWL_OPEN to "غيّره ليوم هجري",
    UiKey.HAWL_TITLE to "يوم زكاتك الهجري",
    UiKey.HAWL_INTRO to "يوم ثابت كل سنة هجرية — المقترح من رصيدك {0}",
    UiKey.HAWL_INTRO_PLAIN to "يوم ثابت كل سنة هجرية.",
    UiKey.HAWL_MONTH to "الشهر الهجري",
    UiKey.HAWL_DAY to "اليوم من الشهر",
    UiKey.HAWL_TODAY to "اليوم {0}",
    UiKey.HAWL_DATE to "{0} {1} {2}",
    UiKey.HAWL_DAY_ARIA to "اليوم {0}",
    UiKey.HAWL_GREG_NA to "التاريخ الميلادي غير متاح بعد: تحويل اليوم الهجري لم يُبنَ في التطبيق.",
    UiKey.HAWL_REMIND to "يتغيّر موعد زكاتك، والتنبيه قبله بـ١٠ أيام.",
    UiKey.HAWL_SAVE to "احفظ اليوم",
    UiKey.HAWL_SAVE_BLOCKED to "الحفظ غير متاح حتى يُبنى تحويل اليوم الهجري.",
    UiKey.HAWL_MONTH_1 to "محرّم",
    UiKey.HAWL_MONTH_2 to "صفر",
    UiKey.HAWL_MONTH_3 to "ربيع الأول",
    UiKey.HAWL_MONTH_4 to "ربيع الآخر",
    UiKey.HAWL_MONTH_5 to "جمادى الأولى",
    UiKey.HAWL_MONTH_6 to "جمادى الآخرة",
    UiKey.HAWL_MONTH_7 to "رجب",
    UiKey.HAWL_MONTH_8 to "شعبان",
    UiKey.HAWL_MONTH_9 to "رمضان",
    UiKey.HAWL_MONTH_10 to "شوّال",
    UiKey.HAWL_MONTH_11 to "ذو القعدة",
    UiKey.HAWL_MONTH_12 to "ذو الحجة",
    UiKey.ADVISOR_SCREEN_TITLE to "التحليلات الذكية",
    UiKey.ADVISOR_SCREEN_INTRO to "يقرأ المساعد المالي عملياتك ويقيس على خططك. لكل كارت سببه ومصدره، والعدّ بالمرات.",
    UiKey.ADVISOR_SCREEN_QUIET_TITLE to "المساعد ساكت الآن",
    UiKey.ADVISOR_SCREEN_QUIET_BODY to "لا شيء يستحق التنبيه. ما يظهر ستجده هنا وفي الرئيسية.",
    UiKey.ADVISOR_SCREEN_NOW to "الآن",
    UiKey.ADVISOR_SCREEN_WHY to "لماذا؟",
    UiKey.ADVISOR_SCREEN_WHEN_DIGEST to "في الملخص",
    UiKey.ADVISOR_SCREEN_WHEN_USUAL to "في وقتك المعتاد",
    UiKey.ADVISOR_SCREEN_WHEN_NOW to "فورًا",
    UiKey.ADVISOR_SCREEN_WHEN_PAGE to "في الصفحة فقط",
    UiKey.ADVISOR_SCREEN_OPEN_GOALS to "افتح خطط الادخار",
    UiKey.ADVISOR_SCREEN_OPEN_BUDGETS to "افتح الميزانيات",
    UiKey.ADVISOR_SCREEN_OPEN_OPS to "اعرض العمليات",
    UiKey.ADVISOR_SCREEN_OFF to "المساعد مغلق: لا تظهر كروته في الرئيسية ولا في الإشعارات. أرقامك نفسها لا تتغير.",
    UiKey.ADVISOR_SCREEN_GROUP to "المساعد المالي",
    UiKey.ADVISOR_SCREEN_GROUP_DESC to "زر واحد يغلق تنبيهاته كلها",
    UiKey.ADVISOR_SCREEN_TURNED_OFF to "أُغلق المساعد — افتحه من هنا أو من إعدادات الإشعارات",
    UiKey.ADVISOR_SCREEN_TURNED_ON to "عاد المساعد للعمل",
)

internal val EGYPTIAN_INVEST_PAY_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ZAKAT_PAY_TITLE to "دفع زكاة السنة",
    UiKey.ZAKAT_PAY_FOR to "السنة اللي ميعادها {0}",
    UiKey.ZAKAT_PAY_DUE to "المطلوب",
    UiKey.ZAKAT_PAY_PAID to "اتدفع",
    UiKey.ZAKAT_PAY_LEFT to "الباقي",
    UiKey.ZAKAT_PAY_ALL_DONE to "اتدفعت زكاة السنة كلها.",
    UiKey.ZAKAT_PAY_ALL_DONE_EXTRA to "اتدفعت زكاة السنة كلها، وصدقة زيادة {0}.",
    UiKey.ZAKAT_PAY_LINE_DONE to "اتدفع ✓",
    UiKey.ZAKAT_PAY_LINE_PART to "اتدفع {0}، فاضل {1}",
    UiKey.ZAKAT_PAY_LINE_NONE to "لسه ما اتدفعش",
    UiKey.ZAKAT_PAY_ALL to "دفعت الكل",
    UiKey.ZAKAT_PAY_HOW to "دفعتها إزاي؟",
    UiKey.ZAKAT_PAY_FROM_STATEMENT to "من الكشف، هتاخد تصنيف «زكاة»",
    UiKey.ZAKAT_PAY_CASH to "دفعتها كاش",
    UiKey.ZAKAT_PAY_CASH_SUB to "من غير عملية — بتتسجل بالمبلغ والتاريخ بس",
    UiKey.ZAKAT_PAY_CASH_LABEL to "المبلغ كاش",
    UiKey.ZAKAT_PAY_NOTE to "الزكاة المدفوعة مصروف عادي في شهرها بتصنيف «زكاة». ممكن تدفع على مرات بأكتر من عملية.",
    UiKey.ZAKAT_PAY_RECORD to "سجّل الدفعة",
    UiKey.ZAKAT_PAY_ERR_HOW to "اختار العملية اللي دفعت بيها، أو «دفعتها كاش».",
    UiKey.ZAKAT_PAY_ERR_CASH to "اكتب المبلغ اللي دفعته كاش.",
    UiKey.ZAKAT_PAY_RECORDED to "اتسجّلت الدفعة",
    UiKey.ZAKAT_PAY_PAYMENTS to "الدفعات",
    UiKey.ZAKAT_PAY_UNLINK to "فك",
    UiKey.ZAKAT_PAY_UNLINKED to "اتفكت الدفعة — العملية رجعت زي ما كانت",
    UiKey.ZAKAT_PAY_CASH_ROW to "كاش",
    UiKey.ZAKAT_PAY_NO_OPS to "مفيش عمليات صرف في الشهر ده.",
    UiKey.HAWL_OPEN to "غيّره ليوم هجري",
    UiKey.HAWL_TITLE to "يوم زكاتك الهجري",
    UiKey.HAWL_INTRO to "يوم ثابت كل سنة هجرية — المقترح من رصيدك {0}",
    UiKey.HAWL_INTRO_PLAIN to "يوم ثابت كل سنة هجرية.",
    UiKey.HAWL_MONTH to "الشهر الهجري",
    UiKey.HAWL_DAY to "اليوم من الشهر",
    UiKey.HAWL_TODAY to "النهارده {0}",
    UiKey.HAWL_DATE to "{0} {1} {2}",
    UiKey.HAWL_DAY_ARIA to "يوم {0}",
    UiKey.HAWL_GREG_NA to "التاريخ الميلادي غير متاح لسه: تحويل اليوم الهجري ما اتبناش في التطبيق.",
    UiKey.HAWL_REMIND to "ميعاد زكاتك بيتغيّر، والتنبيه قبله بـ١٠ أيام.",
    UiKey.HAWL_SAVE to "احفظ اليوم",
    UiKey.HAWL_SAVE_BLOCKED to "الحفظ مش متاح لحد ما تحويل اليوم الهجري يتبني.",
    UiKey.HAWL_MONTH_1 to "محرّم",
    UiKey.HAWL_MONTH_2 to "صفر",
    UiKey.HAWL_MONTH_3 to "ربيع الأول",
    UiKey.HAWL_MONTH_4 to "ربيع الآخر",
    UiKey.HAWL_MONTH_5 to "جمادى الأولى",
    UiKey.HAWL_MONTH_6 to "جمادى الآخرة",
    UiKey.HAWL_MONTH_7 to "رجب",
    UiKey.HAWL_MONTH_8 to "شعبان",
    UiKey.HAWL_MONTH_9 to "رمضان",
    UiKey.HAWL_MONTH_10 to "شوّال",
    UiKey.HAWL_MONTH_11 to "ذو القعدة",
    UiKey.HAWL_MONTH_12 to "ذو الحجة",
    UiKey.ADVISOR_SCREEN_TITLE to "التحليلات الذكية",
    UiKey.ADVISOR_SCREEN_INTRO to "المساعد المالي بيقرا عملياتك ويقيس على خططك. كل كارت بسببه ومصدره، والعدّ بالمرات.",
    UiKey.ADVISOR_SCREEN_QUIET_TITLE to "المساعد ساكت دلوقتي",
    UiKey.ADVISOR_SCREEN_QUIET_BODY to "مفيش حاجة تستاهل تنبيه. أول ما يظهر حاجة هتلاقيها هنا وفي الرئيسية.",
    UiKey.ADVISOR_SCREEN_NOW to "دلوقتي",
    UiKey.ADVISOR_SCREEN_WHY to "ليه؟",
    UiKey.ADVISOR_SCREEN_WHEN_DIGEST to "في الملخص",
    UiKey.ADVISOR_SCREEN_WHEN_USUAL to "في وقتك المعتاد",
    UiKey.ADVISOR_SCREEN_WHEN_NOW to "على طول",
    UiKey.ADVISOR_SCREEN_WHEN_PAGE to "في الصفحة بس",
    UiKey.ADVISOR_SCREEN_OPEN_GOALS to "افتح خطط الادخار",
    UiKey.ADVISOR_SCREEN_OPEN_BUDGETS to "افتح الميزانيات",
    UiKey.ADVISOR_SCREEN_OPEN_OPS to "اعرض العمليات",
    UiKey.ADVISOR_SCREEN_OFF to "المساعد مقفول: كروته مش هتظهر في الرئيسية ولا في الإشعارات. أرقامك نفسها ما بتتغيرش.",
    UiKey.ADVISOR_SCREEN_GROUP to "المساعد المالي",
    UiKey.ADVISOR_SCREEN_GROUP_DESC to "زرار واحد بيقفل تنبيهاته كلها",
    UiKey.ADVISOR_SCREEN_TURNED_OFF to "اتقفل المساعد — تقدر تفتحه من هنا أو من إعدادات الإشعارات",
    UiKey.ADVISOR_SCREEN_TURNED_ON to "المساعد اشتغل تاني",
)

internal val ENGLISH_INVEST_PAY_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.ZAKAT_PAY_TITLE to "Pay this year's zakat",
    UiKey.ZAKAT_PAY_FOR to "The year due on {0}",
    UiKey.ZAKAT_PAY_DUE to "Due",
    UiKey.ZAKAT_PAY_PAID to "Paid",
    UiKey.ZAKAT_PAY_LEFT to "Left",
    UiKey.ZAKAT_PAY_ALL_DONE to "This year's zakat is fully paid.",
    UiKey.ZAKAT_PAY_ALL_DONE_EXTRA to "This year's zakat is fully paid, plus extra charity of {0}.",
    UiKey.ZAKAT_PAY_LINE_DONE to "Paid ✓",
    UiKey.ZAKAT_PAY_LINE_PART to "Paid {0}, {1} left",
    UiKey.ZAKAT_PAY_LINE_NONE to "Not paid yet",
    UiKey.ZAKAT_PAY_ALL to "I paid it all",
    UiKey.ZAKAT_PAY_HOW to "How did you pay it?",
    UiKey.ZAKAT_PAY_FROM_STATEMENT to "From the statement, gets the “Zakat” category",
    UiKey.ZAKAT_PAY_CASH to "I paid in cash",
    UiKey.ZAKAT_PAY_CASH_SUB to "No transaction — recorded with the amount and date only",
    UiKey.ZAKAT_PAY_CASH_LABEL to "Cash amount",
    UiKey.ZAKAT_PAY_NOTE to "Paid zakat is a normal expense in its month, in the “Zakat” category. You can pay in several transactions.",
    UiKey.ZAKAT_PAY_RECORD to "Record the payment",
    UiKey.ZAKAT_PAY_ERR_HOW to "Pick the transaction you paid with, or “I paid in cash”.",
    UiKey.ZAKAT_PAY_ERR_CASH to "Enter the amount you paid in cash.",
    UiKey.ZAKAT_PAY_RECORDED to "Payment recorded",
    UiKey.ZAKAT_PAY_PAYMENTS to "Payments",
    UiKey.ZAKAT_PAY_UNLINK to "Unlink",
    UiKey.ZAKAT_PAY_UNLINKED to "Payment unlinked — the transaction is back as it was",
    UiKey.ZAKAT_PAY_CASH_ROW to "Cash",
    UiKey.ZAKAT_PAY_NO_OPS to "No spending this month.",
    UiKey.HAWL_OPEN to "Change it to a Hijri day",
    UiKey.HAWL_TITLE to "Your Hijri zakat day",
    UiKey.HAWL_INTRO to "A fixed day every Hijri year — suggested from your balance: {0}",
    UiKey.HAWL_INTRO_PLAIN to "A fixed day every Hijri year.",
    UiKey.HAWL_MONTH to "Hijri month",
    UiKey.HAWL_DAY to "Day of the month",
    UiKey.HAWL_TODAY to "Today {0}",
    UiKey.HAWL_DATE to "{0} {1} {2}",
    UiKey.HAWL_DAY_ARIA to "Day {0}",
    UiKey.HAWL_GREG_NA to "The Gregorian date isn't available yet: converting a Hijri day isn't built in the app.",
    UiKey.HAWL_REMIND to "Your zakat date changes, and the reminder comes 10 days before.",
    UiKey.HAWL_SAVE to "Save the day",
    UiKey.HAWL_SAVE_BLOCKED to "Saving isn't available until converting a Hijri day is built.",
    UiKey.HAWL_MONTH_1 to "Muharram",
    UiKey.HAWL_MONTH_2 to "Safar",
    UiKey.HAWL_MONTH_3 to "Rabi al-Awwal",
    UiKey.HAWL_MONTH_4 to "Rabi al-Akhir",
    UiKey.HAWL_MONTH_5 to "Jumada al-Ula",
    UiKey.HAWL_MONTH_6 to "Jumada al-Akhirah",
    UiKey.HAWL_MONTH_7 to "Rajab",
    UiKey.HAWL_MONTH_8 to "Shaban",
    UiKey.HAWL_MONTH_9 to "Ramadan",
    UiKey.HAWL_MONTH_10 to "Shawwal",
    UiKey.HAWL_MONTH_11 to "Dhu al-Qadah",
    UiKey.HAWL_MONTH_12 to "Dhu al-Hijjah",
    UiKey.ADVISOR_SCREEN_TITLE to "Smart insights",
    UiKey.ADVISOR_SCREEN_INTRO to "The financial assistant reads your transactions and measures them against your plans. Every card has its reason and source, and counts are in times.",
    UiKey.ADVISOR_SCREEN_QUIET_TITLE to "The assistant is quiet now",
    UiKey.ADVISOR_SCREEN_QUIET_BODY to "Nothing is worth an alert. Whatever shows up, you'll find here and on Home.",
    UiKey.ADVISOR_SCREEN_NOW to "Now",
    UiKey.ADVISOR_SCREEN_WHY to "Why?",
    UiKey.ADVISOR_SCREEN_WHEN_DIGEST to "In the digest",
    UiKey.ADVISOR_SCREEN_WHEN_USUAL to "At your usual time",
    UiKey.ADVISOR_SCREEN_WHEN_NOW to "Right away",
    UiKey.ADVISOR_SCREEN_WHEN_PAGE to "On the page only",
    UiKey.ADVISOR_SCREEN_OPEN_GOALS to "Open savings plans",
    UiKey.ADVISOR_SCREEN_OPEN_BUDGETS to "Open budgets",
    UiKey.ADVISOR_SCREEN_OPEN_OPS to "Show transactions",
    UiKey.ADVISOR_SCREEN_OFF to "The assistant is off: its cards don't show on Home or in notifications. Your numbers themselves don't change.",
    UiKey.ADVISOR_SCREEN_GROUP to "Financial assistant",
    UiKey.ADVISOR_SCREEN_GROUP_DESC to "One switch turns all its alerts off",
    UiKey.ADVISOR_SCREEN_TURNED_OFF to "The assistant is off — turn it on here or in notification settings",
    UiKey.ADVISOR_SCREEN_TURNED_ON to "The assistant is back on",
)
