package app.masroufy.core

/** منطقة «الأشخاص» بالفصحى (السعودية والافتراضي) — العام · الأشخاص · «لك/عليك» · ملف الشخص · شخص جديد · الديون القديمة. */
internal val MSA_PEOPLE_AREA_1: Map<TextKey, String> = mapOf(
    // ── العام في المنطقة
    TextKey.PPL_AGO_DAYS to "قبل {0}",
    TextKey.PPL_IN_DAYS to "بعد {0}",
    TextKey.PPL_ARCHIVED to "مؤرشف",
    TextKey.PPL_CANCEL to "إلغاء",
    TextKey.PPL_DASH to "—",
    TextKey.PPL_DATE_INVALID to "تاريخ المناسبة غير صالح.",
    TextKey.PPL_DATE_WITH_YEAR to "{0} {1}",
    TextKey.PPL_DAYS_ONE to "يوم",
    TextKey.PPL_DAYS_TWO to "يومين",
    TextKey.PPL_DAYS_FEW to "{0} أيام",
    TextKey.PPL_DAYS_MANY to "{0} يومًا",
    TextKey.PPL_DAY_LABEL to "اليوم",
    TextKey.PPL_GIFTS_ONE to "نقطة واحدة",
    TextKey.PPL_GIFTS_TWO to "نقطتان",
    TextKey.PPL_GIFTS_TWO_OBJ to "نقطتين",
    TextKey.PPL_GIFTS_FEW to "{0} نقاط",
    TextKey.PPL_GIFTS_MANY to "{0} نقطة",
    TextKey.PPL_HOST_OF to "ل{0}",
    TextKey.PPL_ITEMS_ONE to "بند واحد",
    TextKey.PPL_ITEMS_TWO to "بندان",
    TextKey.PPL_ITEMS_TWO_OBJ to "بندين",
    TextKey.PPL_ITEMS_FEW to "{0} بنود",
    TextKey.PPL_ITEMS_MANY to "{0} بندًا",
    TextKey.PPL_LOAD_FAILED to "تعذّر التحميل.",
    TextKey.PPL_MINE to "حدثك",
    TextKey.PPL_MONTH_LABEL to "الشهر (ميلادي)",
    TextKey.PPL_NOT_BUILT to "لم تُفعَّل بعد — تأتي في خطوة قادمة.",
    TextKey.PPL_ONCE_NEEDS_YEAR to "المناسبة لمرة واحدة تحتاج السنة.",
    TextKey.PPL_OPS_ONE to "عملية واحدة",
    TextKey.PPL_OPS_TWO to "عمليتان",
    TextKey.PPL_OPS_TWO_OBJ to "عمليتين",
    TextKey.PPL_OPS_FEW to "{0} عمليات",
    TextKey.PPL_OPS_MANY to "{0} عملية",
    TextKey.PPL_OPTIONAL to "اختياري",
    TextKey.PPL_PEOPLE_ONE to "شخص واحد",
    TextKey.PPL_PEOPLE_TWO to "شخصين",
    TextKey.PPL_PEOPLE_FEW to "{0} أشخاص",
    TextKey.PPL_PEOPLE_MANY to "{0} شخصًا",
    TextKey.PPL_PERCENT to "{0}%",
    TextKey.PPL_PERCENT_SIGN to "%",
    TextKey.PPL_PICK_DATE to "اختر التاريخ",
    TextKey.PPL_REMOVE_NAMED to "حذف {0}",
    TextKey.PPL_REMOVE_ROW to "احذف السطر",
    TextKey.PPL_RETRY to "أعد المحاولة",
    TextKey.PPL_SAR_ONLY to "الدين القديم بالريال فقط حاليًا — لم يُفعَّل بعملة هذا البلد بعد.",
    TextKey.PPL_SAVE to "احفظ",
    TextKey.PPL_SAVED to "حُفظ التعديل",
    TextKey.PPL_SAVE_EDIT to "احفظ التعديل",
    TextKey.PPL_SEP to "، ",
    TextKey.PPL_SWITCH_OFF to "متوقف",
    TextKey.PPL_SWITCH_ON to "يعمل",
    TextKey.PPL_TXN_NO_NAME to "عملية بلا اسم",
    TextKey.PPL_YEAR to "السنة",
    TextKey.PPL_YEAR_OPTIONAL to "السنة (اختياري)",
    TextKey.PPL_YEAR_UNKNOWN to "غير معروفة",
    // ── الأشخاص (People)
    TextKey.PEOPLE_ADD to "إضافة",
    TextKey.PEOPLE_ADD_PERSON to "إضافة شخص",
    TextKey.PEOPLE_ALL to "الكل ({0})",
    TextKey.PEOPLE_BACK to "رجوع",
    TextKey.PEOPLE_CHARACTER_SLOT to "مكان شخصيتك المرسومة",
    TextKey.PEOPLE_CHIP_OWE to "عليك {0}",
    TextKey.PEOPLE_CHIP_OWED to "لك {0}",
    TextKey.PEOPLE_EMPTY_TITLE to "لم تُضف أحدًا بعد",
    TextKey.PEOPLE_EMPTY_BODY to "أضف من تتعامل معهم لتتابع ما لك وما عليك.",
    TextKey.PEOPLE_ERROR_TITLE to "تعذّر تحميل الأرصدة",
    TextKey.PEOPLE_ERROR_BODY to "الأشخاص ظاهرون، والأرقام تظهر بعد التحديث.",
    TextKey.PEOPLE_EVENTS to "الأحداث",
    TextKey.PEOPLE_ORBIT_NOTE to "أصحاب الأرصدة أولًا",
    TextKey.PEOPLE_OWED_BOX to "لك",
    TextKey.PEOPLE_OWE_BOX to "عليك",
    TextKey.PEOPLE_OWED_COUNT to "عند {0}",
    TextKey.PEOPLE_OWE_COUNT to "لـ{0}",
    TextKey.PEOPLE_OWE_TWO to "لشخصين",
    TextKey.PEOPLE_YOU to "أنت",
    // ── لك · عليك (OwedToYou · YouOwe)
    TextKey.OWED_TITLE_OWED to "لك",
    TextKey.OWED_TITLE_OWE to "عليك",
    TextKey.OWED_TOTAL_OWED to "مجموع ما لك",
    TextKey.OWED_TOTAL_OWE to "مجموع ما عليك",
    TextKey.OWED_SUB_OWED to "عند {0}، بلا مقاصة مع «عليك»",
    TextKey.OWED_SUB_OWE to "لـ{0}، بلا مقاصة مع «لك»",
    TextKey.OWED_ORDER_NOTE to "الأهم أولًا: ما فات موعده، ثم ما اقترب موعده",
    TextKey.OWED_FOOT to "اضغط على أي شخص لترى السجل بينكما وتسجّل سدادًا.",
    TextKey.OWED_EMPTY_OWED to "لا ديون لك عند أحد.",
    TextKey.OWED_EMPTY_OWE to "لا ديون عليك لأحد.",
    TextKey.OWED_DUE_ON to "موعدها {0}",
    TextKey.OWED_NO_DUE to "بلا موعد",
    TextKey.OWED_REASON_OPENING to "دين قديم",
    TextKey.OWED_REASON_RECEIVABLE to "سلفة أو نصيب دفعته عنه",
    TextKey.OWED_REASON_LOAN to "سلفة منه",
    TextKey.OWED_REASON_CUSTODY to "أمانة عندك",
    TextKey.OWED_SIGNAL_OVERDUE to "فات موعدها منذ {0}",
    TextKey.OWED_SIGNAL_SOON to "اقترب موعدها، {0}",
    // ── ملف الشخص (PersonProfile)
    TextKey.PERSON_PAGE_LAK to "لك عنده",
    TextKey.PERSON_PAGE_ALEK to "عليك له",
    TextKey.PERSON_PAGE_NOTHING to "لا شيء",
    TextKey.PERSON_PAGE_NO_NETTING to "بلا مقاصة بين الرقمين",
    TextKey.PERSON_PAGE_NOT_FOUND to "الشخص غير موجود.",
    TextKey.PERSON_PAGE_TOGETHER to "معًا",
    TextKey.PERSON_PAGE_ACT_ROSCA to "دعوة لجمعية",
    TextKey.PERSON_PAGE_ACT_PROJECT to "مشروع مشترك",
    TextKey.PERSON_PAGE_ACT_LINK to "طلب اتصال",
    TextKey.PERSON_PAGE_ACT_SPLIT to "تقسيم فاتورة",
    TextKey.PERSON_PAGE_FUTURE to "قريبًا: عندما يستخدم {0} مصروفي، تبنيان أشياء معًا من الحسابين.",
    TextKey.PERSON_PAGE_ROSCA_TITLE to "جمعية مع {0}",
    TextKey.PERSON_PAGE_ROSCA_BODY to "حدّد القسط الشهري لتُسجَّل الجمعية عندك. تصل الدعوة لـ{0} عند تفعيل ربط الحسابات.",
    TextKey.PERSON_PAGE_ROSCA_AMOUNT to "القسط الشهري",
    TextKey.PERSON_PAGE_ROSCA_GO to "سجّل الجمعية",
    TextKey.PERSON_PAGE_PROJECT_TITLE to "مشروع مع {0}",
    TextKey.PERSON_PAGE_PROJECT_BODY to "أنشئ مشروعًا يجمع مصروفاتكم المشتركة، مع نصيب كل منكما.",
    TextKey.PERSON_PAGE_PROJECT_GO to "أنشئ المشروع",
    TextKey.PERSON_PAGE_LINK_TITLE to "اربط حسابك بحساب {0}",
    TextKey.PERSON_PAGE_LINK_BODY to "بعد الربط تُسجَّل السلف والفواتير لدى الطرفين مرة واحدة.",
    TextKey.PERSON_PAGE_LINK_GO to "أرسل الطلب",
    TextKey.PERSON_PAGE_LINK_NOTE to "يحتاج ربط الحسابات، وهو في مرحلة قادمة.",
    TextKey.PERSON_PAGE_SPLIT_TITLE to "قسّم فاتورة مع {0}",
    TextKey.PERSON_PAGE_SPLIT_BODY to "اكتب مبلغ الفاتورة لتُقسَم بالتساوي، ويُسجَّل نصيبه في «لك».",
    TextKey.PERSON_PAGE_SPLIT_AMOUNT to "مبلغ الفاتورة",
    TextKey.PERSON_PAGE_SPLIT_GO to "سجّل التقسيم",
    TextKey.PERSON_PAGE_HISTORY to "السجل بينكما",
    TextKey.PERSON_PAGE_HISTORY_EMPTY to "لا ديون مفتوحة بينكما.",
    TextKey.PERSON_PAGE_DEBT_RECEIVABLE to "سلفة منك",
    TextKey.PERSON_PAGE_DEBT_LOAN to "سلفة منه",
    TextKey.PERSON_PAGE_DEBT_CUSTODY to "أمانة منه",
    TextKey.PERSON_PAGE_REMAINING to "باقٍ {0} من {1}",
    TextKey.PERSON_PAGE_BADGES to "النقوط بينكما",
    // ── شخص جديد (AddPersonSheet)
    TextKey.ADD_PERSON_TITLE to "شخص جديد",
    TextKey.ADD_PERSON_NAME to "الاسم",
    TextKey.ADD_PERSON_NAME_PH to "كما تناديه",
    TextKey.ADD_PERSON_CIRCLE to "الدائرة (اختياري)",
    TextKey.ADD_PERSON_REL to "صلته بك (اختياري)",
    TextKey.ADD_PERSON_REL_PH to "مثلًا: أخي، زميل في الدوام",
    TextKey.ADD_PERSON_OCC to "مناسبة له",
    TextKey.ADD_PERSON_OCC_NOTE_ONCE to "مرة واحدة، ونذكّرك قبلها بأسبوع.",
    TextKey.ADD_PERSON_OCC_NOTE_YEARLY to "كل سنة، ونذكّرك قبلها بأسبوع — ويمكنك تغيير ذلك من ملفه.",
    TextKey.ADD_PERSON_DEBT to "دين قديم بينكما",
    TextKey.ADD_PERSON_SIDE_LAK to "لي عنده",
    TextKey.ADD_PERSON_SIDE_ALEK to "عليّ له",
    TextKey.ADD_PERSON_AMOUNT to "المبلغ",
    TextKey.ADD_PERSON_DEBT_NOTE to "بلا عملية، ولا يمسّ أي محفظة ولا المصروف ولا الدخل.",
    TextKey.ADD_PERSON_SAVE to "أضفه",
    TextKey.ADD_PERSON_ADDED to "أُضيف {0}",
    TextKey.ADD_PERSON_NEED_NAME to "أدخل اسم الشخص.",
    TextKey.ADD_PERSON_NEED_MONTH to "اختر شهر المناسبة، أو أغلق خانتها.",
    TextKey.ADD_PERSON_NEED_SIDE to "اختر: لك عنده أم عليك له.",
    TextKey.ADD_PERSON_NEED_AMOUNT to "اكتب مبلغ الدين أكبر من صفر، أو أغلق خانته.",
    // ── الديون القديمة (ProfileDebtSheet)
    TextKey.PROFILE_DEBT_TITLE to "أضف الديون القديمة",
    TextKey.PROFILE_DEBT_NOTE to "تظهر في الأشخاص وتُسدَّد عاديًا، ولا تدخل في المصروف ولا الدخل ولا رصيد الكاش.",
    TextKey.PROFILE_DEBT_WHO to "مَن؟",
    TextKey.PROFILE_DEBT_NEW to "أو اكتب اسم شخص جديد",
    TextKey.PROFILE_DEBT_DIR_LAK to "لك عنده",
    TextKey.PROFILE_DEBT_DIR_ALEK to "عليك له",
    TextKey.PROFILE_DEBT_HOW_MUCH_LAK to "كم لك عنده؟",
    TextKey.PROFILE_DEBT_HOW_MUCH_ALEK to "كم عليك له؟",
    TextKey.PROFILE_DEBT_NEED_NAME to "أدخل اسم كل شخص",
    TextKey.PROFILE_DEBT_NEED_AMOUNT_OF to "يجب أن يكون مبلغ دين «{0}» أكبر من صفر",
    TextKey.PROFILE_DEBT_NEED_AMOUNT to "يجب أن يكون المبلغ أكبر من صفر",
    TextKey.PROFILE_DEBT_ADD_ANOTHER to "أضف شخصًا آخر",
    TextKey.PROFILE_DEBT_DONE to "تم",
)
