package app.masroufy.core

/**
 * نصوص محرك التنبيهات (OVERRIDES §61) باللغتين — بيتدمجوا في `ARABIC_TEXTS` و`ENGLISH_TEXTS`.
 * **`ALERT_LOCK_*` نص شاشة القفل:** ممنوع فيه أي رقم أو مبلغ أو اسم (حتى «3 أيام») — `systemNoticeFor` بيتأكد وقت التشغيل،
 * واختبار بيمر على كل الأنواع باللغتين. التفاصيل (المبالغ والأسامي) جوه التطبيق بس.
 * النبرة هادية (مصري، من غير تخويف). الإنجليزي كتابة Claude ومستني مراجعة المالك (§40).
 */
internal val ARABIC_ALERT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ALERT_LOCK_TITLE to "مصروفي",
    TextKey.ALERT_LOCK_DUE_SOON_PAY to "عندك ميعاد دفع قرّب — التفاصيل جوه التطبيق",
    TextKey.ALERT_LOCK_DUE_SOON_RECEIVE to "عندك فلوس جاية قرّب ميعادها — التفاصيل جوه التطبيق",
    TextKey.ALERT_LOCK_DUE_TODAY_PAY to "عندك ميعاد دفع النهارده",
    TextKey.ALERT_LOCK_DUE_TODAY_RECEIVE to "عندك فلوس ميعادها النهارده",
    TextKey.ALERT_LOCK_DUE_OVERDUE_PAY to "فيه ميعاد دفع عدّى — بص عليه لما تفتح",
    TextKey.ALERT_LOCK_DUE_OVERDUE_RECEIVE to "فيه فلوس ليك ميعادها عدّى — بص عليها لما تفتح",
    TextKey.ALERT_LOCK_BUDGET to "فيه تحديث على ميزانيتك",
    TextKey.ALERT_LOCK_QUESTION to "عندنا سؤال صغير عن تحويلاتك",
    TextKey.ALERT_LOCK_ZAKAT_SOON to "ميعاد زكاتك قرّب",
    TextKey.ALERT_LOCK_ZAKAT_TODAY to "ميعاد زكاتك النهارده",
    TextKey.ALERT_LOCK_ZAKAT_OVERDUE to "ميعاد زكاتك عدّى والحساب لسه ما اتثبتش",
    TextKey.ALERT_LOCK_BALANCE to "الرصيد محتاج مراجعة منك",
    TextKey.ALERT_LOCK_PROFILE to "ملفك ناقصه حاجات بسيطة",
    TextKey.ALERT_LOCK_GENERIC to "عندك تنبيه جديد",
    TextKey.ALERT_LOCK_DIGEST to "عندك كذا تنبيه في ملخص واحد",
    TextKey.ALERT_WHY_DUE_SOON to "ميعاده قرّب (خلال {0} أيام)",
    TextKey.ALERT_WHY_DUE_TODAY to "ميعاده النهارده",
    TextKey.ALERT_WHY_DUE_OVERDUE to "ميعاده عدّى ولسه ما اتربطش بعملية دفع",
    TextKey.ALERT_WHY_BUDGET_THRESHOLD to "مصروفك عدّى العتبة اللي إنت حددتها",
    TextKey.ALERT_WHY_BUDGET_EXCEEDED to "مصروفك عدّى سقف الميزانية",
    TextKey.ALERT_WHY_TRANSFER to "التحويلات مع الطرف ده كترت في شهر واحد",
    TextKey.ALERT_WHY_ZAKAT_SOON to "ميعاد الزكاة خلال {0} أيام",
    TextKey.ALERT_WHY_ZAKAT_TODAY to "ميعاد الزكاة النهارده",
    TextKey.ALERT_WHY_ZAKAT_OVERDUE to "ميعاد الزكاة عدّى ولسه فيه حاجة ما خلصتش",
    TextKey.ALERT_WHY_BALANCE to "رصيد التطبيق مش مطابق لرصيد الكشف",
    TextKey.ALERT_WHY_PROFILE to "ملفك لسه ناقص — كارت واحد بياخد ثواني",
    TextKey.ALERT_WHY_SERVER to "تنبيه من السيرفر",
    TextKey.ALERT_FACTOR_URGENT to "عشان كده اتبعت على طول",
    TextKey.ALERT_FACTOR_MONEY_IN to "دي فلوس جاية ليك مش عليك، فمش مستعجلة",
    TextKey.ALERT_FACTOR_BIG to "المبلغ كبير بالنسبة لميزانية شهرك",
    TextKey.ALERT_FACTOR_SMALL to "المبلغ صغير بالنسبة لميزانية شهرك",
    TextKey.ALERT_FACTOR_DECISION to "محتاج قرار منك",
    TextKey.ALERT_FACTOR_OPEN to "عادةً بتفتح التنبيه ده",
    TextKey.ALERT_FACTOR_SKIP to "غالبًا بتعدّي التنبيه ده من غير ما تفتحه",
    TextKey.ALERT_FACTOR_USUAL_NOW to "ودي ساعة بتفتح فيها التطبيق عادةً",
    TextKey.ALERT_FACTOR_WAIT to "فاستنينا لحد الساعة {0}، وقت ما بتفتح التطبيق عادةً",
    TextKey.ALERT_FACTOR_NOT_LEARNED to "ولسه بنتعلم إمتى بتفتح التطبيق، فاتبعت دلوقتي",
    TextKey.ALERT_FACTOR_BUNDLED to "فاتجمع مع غيره في ملخص واحد",
    TextKey.ALERT_FACTOR_PAGE_ONLY to "فسيبناه هنا في الصفحة من غير ما نزعجك",
    TextKey.ALERT_DUE_SOON_TITLE to "«{0}»: ميعاده كمان {1} يوم",
    TextKey.ALERT_DUE_TODAY_TITLE to "«{0}»: ميعاده النهارده",
    TextKey.ALERT_DUE_OVERDUE_TITLE to "«{0}»: ميعاده عدّى من {1} يوم",
    TextKey.ALERT_DUE_BODY_PAY to "عليك {0} — الميعاد {1}",
    TextKey.ALERT_DUE_BODY_RECEIVE to "ليك {0} — الميعاد {1}",
    TextKey.ALERT_TRANSFER_TITLE to "مين «{0}»؟",
    TextKey.ALERT_TRANSFER_BODY to "{0} تحويلات معاه في شهر {1} — ده حسابك التاني ولا شخص؟",
    TextKey.ALERT_ZAKAT_SOON_TITLE to "زكاتك: الميعاد كمان {0} يوم",
    TextKey.ALERT_ZAKAT_TODAY_TITLE to "زكاتك: الميعاد النهارده",
    TextKey.ALERT_ZAKAT_OVERDUE_TITLE to "زكاتك: الميعاد عدّى",
    TextKey.ALERT_ZAKAT_BODY to "الميعاد {0} — راجع الحساب وثبّته",
    TextKey.ALERT_BALANCE_TITLE to "الرصيد مش مطابق في «{0}»",
    TextKey.ALERT_BALANCE_BODY to "{0} سطر رصيدهم مختلف عن الكشف — أول اختلاف يوم {1}",
    TextKey.ALERT_PROFILE_TITLE to "ملفك {0}%",
    TextKey.ALERT_PROFILE_BODY to "كارت واحد (10 ثواني) بيخلّي أرقامك أدق",
    TextKey.ALERT_GROUP_DUES to "المستحقات",
    TextKey.ALERT_GROUP_BUDGET to "الميزانية",
    TextKey.ALERT_GROUP_QUESTIONS to "أسئلة محتاجة قرارك",
    TextKey.ALERT_GROUP_ZAKAT to "الزكاة",
    TextKey.ALERT_GROUP_BALANCE to "مطابقة الرصيد",
    TextKey.ALERT_GROUP_PROFILE to "ملفك",
    TextKey.ALERT_GROUP_SECURITY to "الأمان",
    TextKey.ALERT_GROUP_LINKED_ACCOUNTS to "الحسابات المربوطة",
    TextKey.ALERT_GROUP_EMAIL to "الإيميل",
)

internal val ENGLISH_ALERT_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.ALERT_LOCK_TITLE to "Masroufy",
    TextKey.ALERT_LOCK_DUE_SOON_PAY to "A payment is coming up — details inside the app",
    TextKey.ALERT_LOCK_DUE_SOON_RECEIVE to "Money is due to you soon — details inside the app",
    TextKey.ALERT_LOCK_DUE_TODAY_PAY to "You have a payment due today",
    TextKey.ALERT_LOCK_DUE_TODAY_RECEIVE to "Money is due to you today",
    TextKey.ALERT_LOCK_DUE_OVERDUE_PAY to "A payment date has passed — take a look when you open the app",
    TextKey.ALERT_LOCK_DUE_OVERDUE_RECEIVE to "Money due to you is past its date — take a look when you open the app",
    TextKey.ALERT_LOCK_BUDGET to "There is an update on your budget",
    TextKey.ALERT_LOCK_QUESTION to "We have a quick question about your transfers",
    TextKey.ALERT_LOCK_ZAKAT_SOON to "Your zakat date is coming up",
    TextKey.ALERT_LOCK_ZAKAT_TODAY to "Your zakat date is today",
    TextKey.ALERT_LOCK_ZAKAT_OVERDUE to "Your zakat date has passed and the calculation is not locked yet",
    TextKey.ALERT_LOCK_BALANCE to "Your balance needs a look",
    TextKey.ALERT_LOCK_PROFILE to "Your profile is missing a few small things",
    TextKey.ALERT_LOCK_GENERIC to "You have a new alert",
    TextKey.ALERT_LOCK_DIGEST to "You have a few alerts in one summary",
    TextKey.ALERT_WHY_DUE_SOON to "Its date is close (within {0} days)",
    TextKey.ALERT_WHY_DUE_TODAY to "Its date is today",
    TextKey.ALERT_WHY_DUE_OVERDUE to "Its date has passed and no payment is linked yet",
    TextKey.ALERT_WHY_BUDGET_THRESHOLD to "Your spending passed the threshold you set",
    TextKey.ALERT_WHY_BUDGET_EXCEEDED to "Your spending passed your budget limit",
    TextKey.ALERT_WHY_TRANSFER to "Transfers with this party piled up in one month",
    TextKey.ALERT_WHY_ZAKAT_SOON to "Your zakat date is within {0} days",
    TextKey.ALERT_WHY_ZAKAT_TODAY to "Your zakat date is today",
    TextKey.ALERT_WHY_ZAKAT_OVERDUE to "Your zakat date has passed and something is still open",
    TextKey.ALERT_WHY_BALANCE to "The app's balance does not match the statement",
    TextKey.ALERT_WHY_PROFILE to "Your profile is not complete — one card takes seconds",
    TextKey.ALERT_WHY_SERVER to "A server alert",
    TextKey.ALERT_FACTOR_URGENT to "so it was sent right away",
    TextKey.ALERT_FACTOR_MONEY_IN to "this is money coming to you, so it is not pressing",
    TextKey.ALERT_FACTOR_BIG to "the amount is large for your monthly budget",
    TextKey.ALERT_FACTOR_SMALL to "the amount is small for your monthly budget",
    TextKey.ALERT_FACTOR_DECISION to "it needs a decision from you",
    TextKey.ALERT_FACTOR_OPEN to "you usually open this alert",
    TextKey.ALERT_FACTOR_SKIP to "you usually skip this alert without opening it",
    TextKey.ALERT_FACTOR_USUAL_NOW to "and this is an hour you usually open the app",
    TextKey.ALERT_FACTOR_WAIT to "so we waited until {0}:00, when you usually open the app",
    TextKey.ALERT_FACTOR_NOT_LEARNED to "and we are still learning when you open the app, so it was sent now",
    TextKey.ALERT_FACTOR_BUNDLED to "so it was bundled with others in one summary",
    TextKey.ALERT_FACTOR_PAGE_ONLY to "so we left it here on the page without disturbing you",
    TextKey.ALERT_DUE_SOON_TITLE to "“{0}”: due in {1} days",
    TextKey.ALERT_DUE_TODAY_TITLE to "“{0}”: due today",
    TextKey.ALERT_DUE_OVERDUE_TITLE to "“{0}”: {1} days past its date",
    TextKey.ALERT_DUE_BODY_PAY to "You owe {0} — date {1}",
    TextKey.ALERT_DUE_BODY_RECEIVE to "You are owed {0} — date {1}",
    TextKey.ALERT_TRANSFER_TITLE to "Who is “{0}”?",
    TextKey.ALERT_TRANSFER_BODY to "{0} transfers in {1} — is this your other account or a person?",
    TextKey.ALERT_ZAKAT_SOON_TITLE to "Your zakat: due in {0} days",
    TextKey.ALERT_ZAKAT_TODAY_TITLE to "Your zakat: due today",
    TextKey.ALERT_ZAKAT_OVERDUE_TITLE to "Your zakat: the date has passed",
    TextKey.ALERT_ZAKAT_BODY to "Date {0} — review the calculation and lock it",
    TextKey.ALERT_BALANCE_TITLE to "The balance does not match in “{0}”",
    TextKey.ALERT_BALANCE_BODY to "{0} rows differ from the statement — the first on {1}",
    TextKey.ALERT_PROFILE_TITLE to "Your profile is {0}%",
    TextKey.ALERT_PROFILE_BODY to "One card (10 seconds) makes your numbers more accurate",
    TextKey.ALERT_GROUP_DUES to "Dues",
    TextKey.ALERT_GROUP_BUDGET to "Budget",
    TextKey.ALERT_GROUP_QUESTIONS to "Questions that need you",
    TextKey.ALERT_GROUP_ZAKAT to "Zakat",
    TextKey.ALERT_GROUP_BALANCE to "Balance check",
    TextKey.ALERT_GROUP_PROFILE to "Your profile",
    TextKey.ALERT_GROUP_SECURITY to "Security",
    TextKey.ALERT_GROUP_LINKED_ACCOUNTS to "Linked accounts",
    TextKey.ALERT_GROUP_EMAIL to "Email",
)
