package app.masroufy.core

/** نصوص الواجهة المشتركة **بالمصري** لحساب مصر (OVERRIDES §66) — من النموذج التفاعلي بالحرف (`eg ? …`). الفصحى في `TextsShell.kt`. */
internal val EGYPTIAN_SHELL_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.TAB_HOME to "الرئيسية",
    TextKey.TAB_OPERATIONS to "العمليات",
    TextKey.TAB_PEOPLE to "الأشخاص",
    TextKey.TAB_INVESTMENT to "الاستثمار",
    TextKey.SHELL_NAV to "التنقل",
    TextKey.SHELL_GEAR to "المزيد والإعدادات",
    TextKey.SHELL_BACK to "رجوع",
    TextKey.SHELL_CLOSE to "اقفل",
    TextKey.SHELL_NEW_DOT to "فيه جديد",
    TextKey.SHELL_TAB_WITH_NEW to "{0} — فيه جديد",
    TextKey.SHELL_OFFLINE to "مفيش نت — اللي قدامك محفوظ على الموبايل وممكن ما يكونش الأحدث.",
    TextKey.SHELL_OPENING to "بنجهّز بياناتك…",
    TextKey.SHELL_OPENING_PROGRESS to "{0} من {1}",
    TextKey.SHELL_PENDING_SCREEN to "الشاشة دي لسه بتتبني.",
    TextKey.SHELL_LOADING to "بيحمّل",
    TextKey.SHELL_RETRY to "جرّب تاني",
    TextKey.SHELL_LOAD_FAILED to "ما عرفناش نحمّل.",
    TextKey.BADGE_APPROX to "تقريبي",
    TextKey.GREETING_MORNING_NAME to "صباح الخير يا {0}",
    TextKey.GREETING_EVENING_NAME to "مساء الخير يا {0}",
    TextKey.GREETING_MORNING to "صباح الخير",
    TextKey.GREETING_EVENING to "مساء الخير",
    TextKey.ME_PROFILE to "ملفك",
    TextKey.ME_PROFILE_PERCENT to "ملفك — مكتمل {0}٪",
    TextKey.WEEKDAY_MON to "الاتنين",
    TextKey.WEEKDAY_TUE to "التلات",
    TextKey.WEEKDAY_WED to "الأربع",
    TextKey.WEEKDAY_THU to "الخميس",
    TextKey.WEEKDAY_FRI to "الجمعة",
    TextKey.WEEKDAY_SAT to "السبت",
    TextKey.WEEKDAY_SUN to "الحد",
    TextKey.WEEKDAY_SHORT_MON to "اتنين",
    TextKey.WEEKDAY_SHORT_TUE to "تلات",
    TextKey.WEEKDAY_SHORT_WED to "أربع",
    TextKey.WEEKDAY_SHORT_THU to "خميس",
    TextKey.WEEKDAY_SHORT_FRI to "جمعة",
    TextKey.WEEKDAY_SHORT_SAT to "سبت",
    TextKey.WEEKDAY_SHORT_SUN to "حد",
    TextKey.MONTH_1 to "يناير",
    TextKey.MONTH_2 to "فبراير",
    TextKey.MONTH_3 to "مارس",
    TextKey.MONTH_4 to "أبريل",
    TextKey.MONTH_5 to "مايو",
    TextKey.MONTH_6 to "يونيو",
    TextKey.MONTH_7 to "يوليو",
    TextKey.MONTH_8 to "أغسطس",
    TextKey.MONTH_9 to "سبتمبر",
    TextKey.MONTH_10 to "أكتوبر",
    TextKey.MONTH_11 to "نوفمبر",
    TextKey.MONTH_12 to "ديسمبر",
    TextKey.DATE_DAY_MONTH to "{0} {1}",
    TextKey.DATE_WEEKDAY_DAY_MONTH to "{0}، {1}",
    TextKey.DATE_MONTH_YEAR to "{0} {1}",
    TextKey.ASK_BAR to "اسأل مصروفي أو اطلب منه أي حاجة…",
    TextKey.ASK_MIC to "ضيف بصوتك",
    TextKey.ASK_TITLE to "مصروفي",
    TextKey.ASK_BRAND_TITLE to "مساعدك المالي الذكي",
    TextKey.ASK_DIALOG to "محادثة مع {0}",
    TextKey.ASK_HISTORY to "سجل المحادثات",
    TextKey.ASK_NEW to "محادثة جديدة",
    TextKey.ASK_NEW_STARTED to "بدأنا محادثة جديدة — اللي فاتت في السجل",
    TextKey.ASK_INTRO to "أنا {0}، {1}. اسألني عن فلوسك، أو قولّي أسجّل مصروف أو أقسّم فاتورة.",
    TextKey.ASK_TODO_TITLE to "حاجات لسه ما عملتهاش",
    TextKey.ASK_TODO_NOT_READY to "لسه مش متاح — القايمة دي لسه ما اتربطتش ببياناتك في النسخة دي.",
    TextKey.ASK_TODO_BASIS to "من رسايل البنك والفواتير اللي بتتكرر والميزانيات والديون.",
    TextKey.ASK_INPUT_HINT to "اكتب سؤالك أو اطلب أي حاجة…",
    TextKey.ASK_INPUT_LABEL to "رسالتك لـ{0}",
    TextKey.ASK_SEND to "ابعت",
    TextKey.ASK_TALK to "اتكلّم",
    TextKey.ASK_CLOSE to "اقفل المحادثة",
    TextKey.ASK_CHIPS_FOR to "اقتراحات لصفحة «{0}»",
    TextKey.ASK_NOT_READY to "المساعد لسه مش متاح — محتاج خدمة ذكاء اصطناعي ما اتحددش مزوّدها. تقدر تشوف بياناتك من التبويبات.",
    TextKey.ASK_VOICE_NOT_READY to "الإضافة بالصوت لسه مش متاحة.",
    TextKey.ASK_CHIP_SPENT to "صرفت كام الشهر ده؟",
    TextKey.ASK_CHIP_VOICE to "ضيف عملية بصوتي",
    TextKey.ASK_CHIP_SPLIT to "قسّم فاتورة مع صحابي",
    TextKey.ASK_CHIP_PLAN to "أنا ماشي على الخطة؟",
    TextKey.ASK_CHIP_OWED to "ليّا كام عند الناس؟",
    TextKey.ASK_CHIP_LOCK to "فين أغيّر القفل؟",
    TextKey.ASK_TYPING to "مصروفي بيكتب",
    TextKey.ASK_LISTENING to "بسمعك…",
    TextKey.ASK_HISTORY_CLOSE to "اقفل السجل",
    TextKey.ASK_HISTORY_SEARCH to "دوّر في محادثاتك",
    TextKey.ASK_HISTORY_TODAY to "النهارده",
    TextKey.ASK_HISTORY_CURRENT to "الحالية",
    TextKey.ASK_HISTORY_EMPTY to "لسه مفيش محادثات.",
    TextKey.ASK_HISTORY_NO_MATCH to "مفيش محادثات بالبحث ده.",
    TextKey.ASK_HISTORY_DELETE to "امسح «{0}»",
    TextKey.ASK_HISTORY_DELETED to "اتمسحت «{0}»",
    TextKey.ASK_HISTORY_UNDO to "رجّعها",
    TextKey.ADD_LABEL to "ضيف عملية",
    TextKey.ADD_TITLE to "عملية جديدة",
    TextKey.ADD_VOICE to "بصوتك",
    TextKey.ADD_KIND_TABS to "نوع العملية",
    TextKey.ADD_TYPE_OUT to "صرف",
    TextKey.ADD_TYPE_IN to "دخل",
    TextKey.ADD_TYPE_MOVE to "تحويل",
    TextKey.ADD_AMOUNT to "المبلغ",
    TextKey.ADD_CATEGORY to "التصنيف",
    TextKey.ADD_INCOME_KIND to "النوع",
    TextKey.ADD_FROM to "منين؟",
    TextKey.ADD_TO to "لفين؟",
    TextKey.ADD_SAVE to "سجّل",
    TextKey.ADD_SAVING to "بيتسجّل…",
    TextKey.ADD_SAVED to "اتسجّلت: {0}",
    TextKey.ADD_NO_WALLET to "ضيف محفظة الأول من «المزيد ← المحافظ».",
    TextKey.ADD_AMOUNT_INVALID to "اكتب مبلغ أكبر من صفر.",
    TextKey.BELL_TITLE to "الإشعارات",
    TextKey.BELL_LABEL_NEW to "الإشعارات — فيه جديد",
    TextKey.BELL_NEW_COUNT to "{0} جديد",
    TextKey.BELL_ALL_READ to "كله مقروء",
    TextKey.BELL_MARK_READ to "علّم الكل مقروء",
    TextKey.BELL_ALL to "كل الإشعارات",
    TextKey.BELL_EMPTY to "مفيش إشعارات دلوقتي.",
    TextKey.BELL_CLOSE to "اقفل الإشعارات",
    TextKey.SPACE_SWITCH_TITLE to "بدّل البلد",
    TextKey.SPACE_SWITCH_BODY to "كل بلد ليها حساب لوحدها بمحافظها وأرقامها وعملتها. التبديل على الموبايل ده بس، ومش بيغيّر حاجة في بياناتك.",
    TextKey.SPACE_ACTIVE to "الحالية",
    TextKey.SPACE_WITH_YOU to "معاك دلوقتي",
    TextKey.SPACE_OPENING to "بيفتح…",
    TextKey.SPACE_SHARED_NOTE to "مشترك بين البلاد: ملفك ويوم المرتب والأشخاص والتجار والوسوم.",
    TextKey.SPACE_MANAGE to "إدارة البلاد",
    TextKey.SPACE_TRIGGER to "البلد: {0} — دوس عشان تبدّل",
    TextKey.SPACE_SWITCHED to "بقيت في حساب {0}",
    TextKey.SPACE_SUB to "{0}، {1}",
    TextKey.CURRENCY_NAME_SAR to "ريال سعودي",
    TextKey.CURRENCY_NAME_EGP to "جنيه مصري",
    TextKey.HERO_WITH_YOU to "معاك دلوقتي",
    TextKey.HERO_CASH_CHIP to "منهم {0} كاش",
    TextKey.HERO_BANKS_TITLE to "معاك دلوقتي فين؟",
    TextKey.HERO_BANKS_LABEL to "البنوك اللي في «معاك دلوقتي»: {0}",
    TextKey.HERO_BANK_SUB to "حساب بنك",
    TextKey.HERO_DIGITAL_SUB to "محفظة إلكترونية",
    TextKey.HERO_CASH_SUB to "اللي في جيبك",
    TextKey.HERO_LOGO_NOTE to "لوجو كل بنك هيتحط مكان الحرف بعد ما بحث اللوجوهات يتعتمد.",
    TextKey.HERO_NA_LINE to "رصيد محفظة لسه مش متاح — بيبدأ من يوم ما اتفتحت في التطبيق.",
)
