package app.masroufy.core

/**
 * «إعدادات الإشعارات» (`NotificationSettings`) + «القفل واللغة والمحتوى» (`AppSettings`) — منطقة «المزيد». من النموذج بالحرف، إلا:
 * - شرح «الأسئلة» من غير «سلفة أم دعم؟ · هل هي سداد؟ · كم بالريال؟»: مجموعة الأسئلة في كوتلن فيها أطراف التحويلات بس (§75 «يسأل» مش متبني).
 * - «ملفك» مجموعة في المحرك (`AlertGroup.PROFILE`) مش مرسومة في النموذج — اتضافت آخر حاجة عشان تتقفل (اختيار Claude).
 * - سطور «غير متاح بعد» (سؤال الكاش · حفظ اللغة) — كتابة Claude.
 */
internal val MSA_MORE_SETTINGS_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.NSET_TITLE to "إعدادات الإشعارات",
    UiKey.NSET_INTRO to "أغلق أي مجموعة وحدها.",
    UiKey.NSET_NEW to "جديد",
    UiKey.NSET_BANK to "رسائل البنك",
    UiKey.NSET_BANK_DESC to "فقط عند وجود رسائل بانتظار تأكيدك. ما يُسجَّل تلقائيًا لا يصدر عنه إشعار.",
    UiKey.NSET_BANK_OFF_DESC to "مغلقة: الرسائل المنتظرة تظهر في صفحة الإشعارات فقط، بلا إشعار جوال.",
    UiKey.NSET_DUES to "المستحقات",
    UiKey.NSET_DUES_DESC to "الأقساط والاشتراكات والديون: قبل الموعد ويومه وعند تجاوزه",
    UiKey.NSET_BUDGET to "الميزانية",
    UiKey.NSET_BUDGET_DESC to "عند الاقتراب من السقف أو تجاوزه، ولو بسبب عملية سُجّلت تلقائيًا",
    UiKey.NSET_ASK to "الأسئلة",
    UiKey.NSET_ASK_DESC to "أطراف التحويلات بانتظار قرارك — وإن لم تردّ تبقى في المراجعة",
    UiKey.NSET_CASH to "سؤال الكاش",
    UiKey.NSET_CASH_DESC to "يسألك «كم معك كاش؟» ليبقى رصيد الكاش صحيحًا",
    UiKey.NSET_CASH_NOTE to "صباح الجمعة (مقترح). إن عددت الكاش بنفسك قبلها يتأجل السؤال.",
    UiKey.NSET_CASH_NOT_YET to "سؤال الكاش غير متاح بعد: لا تنبيه له في التطبيق حتى الآن.",
    UiKey.NSET_EVERY_WEEK to "كل أسبوع",
    UiKey.NSET_EVERY_2WEEKS to "كل أسبوعين",
    UiKey.NSET_EVERY_MONTH to "كل شهر",
    UiKey.NSET_INCOME to "الدخل",
    UiKey.NSET_INCOME_DESC to "إذا تأخر الراتب عن موعده",
    UiKey.NSET_OCC to "المناسبات",
    UiKey.NSET_OCC_DESC to "أعياد ميلاد أشخاصك ومناسباتهم",
    UiKey.NSET_ZAKAT to "الزكاة",
    UiKey.NSET_ZAKAT_DESC to "قبل موعدها بـ10 أيام ويومه",
    UiKey.NSET_BALANCE to "الرصيد",
    UiKey.NSET_BALANCE_DESC to "إذا لم يطابق رصيد محفظة الكشف",
    UiKey.NSET_ADVISOR to "المساعد",
    UiKey.NSET_ADVISOR_DESC to "التحليلات الذكية من المساعد المالي",
    UiKey.NSET_PROFILE to "ملفك",
    UiKey.NSET_PROFILE_DESC to "تذكير لطيف بإكمال أسئلة ملفك",
    UiKey.NSET_LATER_TITLE to "لاحقًا",
    UiKey.NSET_LATER_BODY to "الأمان · الحسابات المرتبطة · البريد الإلكتروني — تُضاف لاحقًا.",
    UiKey.NSET_LOCK_NOTE to "شاشة القفل تعرض نوع التنبيه فقط: بلا مبالغ ولا أسماء ولا أعداد.",
    UiKey.APPS_TITLE to "القفل واللغة والمحتوى",
    UiKey.APPS_LOCK_HEAD to "القفل",
    UiKey.APPS_LOCK_TITLE to "قفل البصمة",
    UiKey.APPS_LOCK_DESC to "يُقفل عند فتح التطبيق، وبعد 5 دقائق في الخلفية.",
    UiKey.APPS_LOCK_FACT_1 to "العودة قبل 5 دقائق لا تطلب البصمة.",
    UiKey.APPS_LOCK_FACT_2 to "إن تعذّرت البصمة: رمز قفل الجوال.",
    UiKey.APPS_LOCK_FACT_3 to "يبقى التطبيق خلف ضبابية حتى التحقق.",
    UiKey.APPS_LOCK_NA to "لا قفل شاشة ولا بصمة مسجلة في الجوال. فعّل قفل الشاشة من إعدادات الجوال أولًا.",
    UiKey.APPS_LOCK_ON_DONE to "تم تفعيل القفل",
    UiKey.APPS_LOCK_OFF_DONE to "تم إيقاف القفل",
    UiKey.APPS_LANG_HEAD to "اللغة",
    UiKey.APPS_LANG_AR to "العربية",
    UiKey.APPS_LANG_AR_DESC to "تلقائيًا حسب البلد: السعودية بالفصحى المختصرة، ومصر باللهجة المصرية. الآن: {0}.",
    UiKey.APPS_LANG_MSA to "الفصحى المختصرة",
    UiKey.APPS_LANG_EGYPTIAN to "اللهجة المصرية",
    UiKey.APPS_LANG_EN to "English",
    UiKey.APPS_LANG_EN_ALT to "الإنجليزية",
    UiKey.APPS_LANG_EN_DESC to "تنقلب الشاشة فتبدأ من اليسار.",
    UiKey.APPS_LANG_NEXT_OPEN to "تُطبَّق اللغة عند فتح التطبيق مرة أخرى.",
    UiKey.APPS_LANG_NOT_YET to "حفظ اختيار اللغة غير متاح بعد: يبدأ التطبيق بالعربية حاليًا.",
    UiKey.APPS_DIR_RTL to "اتجاه الشاشة: من اليمين إلى اليسار.",
    UiKey.APPS_DIR_LTR to "اتجاه الشاشة: من اليسار إلى اليمين.",
    UiKey.APPS_ISL_HEAD to "المحتوى الإسلامي",
    UiKey.APPS_ISL_TITLE to "إظهار المحتوى الإسلامي",
    UiKey.APPS_ISL_SHOWN to "ظاهر",
    UiKey.APPS_ISL_HIDDEN to "مخفي",
    UiKey.APPS_ISL_SHOWN_DONE to "أصبح المحتوى الإسلامي ظاهرًا",
    UiKey.APPS_ISL_HIDDEN_DONE to "أُخفي المحتوى الإسلامي",
    UiKey.APPS_ISL_LIST_ON to "يظهر:",
    UiKey.APPS_ISL_LIST_OFF to "مخفي الآن:",
    UiKey.APPS_ISL_ZAKAT to "الزكاة في الاستثمار وموعدها وتنبيهاتها",
    UiKey.APPS_ISL_CALENDAR to "رمضان والعيدان في التقويم",
    UiKey.APPS_ISL_NOTE to "إخفاء فقط — لا يُحذف شيء، ويعود كما كان عند إظهاره.",
)

internal val EGYPTIAN_MORE_SETTINGS_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.NSET_TITLE to "إعدادات الإشعارات",
    UiKey.NSET_INTRO to "كل مجموعة بتتقفل لوحدها.",
    UiKey.NSET_NEW to "جديد",
    UiKey.NSET_BANK to "رسايل البنك",
    UiKey.NSET_BANK_DESC to "بس لما فيه رسايل مستنية تأكيدك. اللي بيتسجل لوحده مالوش إشعار.",
    UiKey.NSET_BANK_OFF_DESC to "مقفولة: الرسايل المستنية بتبان في صفحة الإشعارات بس، من غير إشعار جوال.",
    UiKey.NSET_DUES to "المستحقات",
    UiKey.NSET_DUES_DESC to "الأقساط والاشتراكات والديون: قبل الميعاد ويومه ولو عدّى",
    UiKey.NSET_BUDGET to "الميزانية",
    UiKey.NSET_BUDGET_DESC to "لما تقرب من السقف أو تعدّيه، حتى لو بسبب عملية اتسجلت لوحدها",
    UiKey.NSET_ASK to "الأسئلة",
    UiKey.NSET_ASK_DESC to "أطراف التحويلات المستنية قرارك — ولو ما رديتش بتفضل في المراجعة",
    UiKey.NSET_CASH to "سؤال الكاش",
    UiKey.NSET_CASH_DESC to "يسألك «معاك كام كاش؟» عشان رصيد الكاش يفضل صح",
    UiKey.NSET_CASH_NOTE to "يوم الجمعة الصبح (اقتراح). لو عدّيت الكاش بنفسك قبلها، السؤال بيتأجل.",
    UiKey.NSET_CASH_NOT_YET to "سؤال الكاش لسه مش متاح: مالوش تنبيه في البرنامج لسه.",
    UiKey.NSET_EVERY_WEEK to "كل أسبوع",
    UiKey.NSET_EVERY_2WEEKS to "كل أسبوعين",
    UiKey.NSET_EVERY_MONTH to "كل شهر",
    UiKey.NSET_INCOME to "الدخل",
    UiKey.NSET_INCOME_DESC to "لو المرتب اتأخر عن ميعاده",
    UiKey.NSET_OCC to "المناسبات",
    UiKey.NSET_OCC_DESC to "أعياد ميلاد ومناسبات أشخاصك",
    UiKey.NSET_ZAKAT to "الزكاة",
    UiKey.NSET_ZAKAT_DESC to "قبل ميعادها بـ10 أيام ويومه",
    UiKey.NSET_BALANCE to "الرصيد",
    UiKey.NSET_BALANCE_DESC to "لو رصيد محفظة ما طابقش الكشف",
    UiKey.NSET_ADVISOR to "المساعد",
    UiKey.NSET_ADVISOR_DESC to "التحليلات الذكية من المساعد المالي",
    UiKey.NSET_PROFILE to "ملفك",
    UiKey.NSET_PROFILE_DESC to "تذكير خفيف تكمّل أسئلة ملفك",
    UiKey.NSET_LATER_TITLE to "بعدين",
    UiKey.NSET_LATER_BODY to "الأمان · الحسابات المربوطة · الإيميل — بتيجي بعدين.",
    UiKey.NSET_LOCK_NOTE to "شاشة القفل بتعرض نوع التنبيه بس: من غير مبالغ ولا أسامي ولا عدد.",
    UiKey.APPS_TITLE to "القفل واللغة والمحتوى",
    UiKey.APPS_LOCK_HEAD to "القفل",
    UiKey.APPS_LOCK_TITLE to "قفل البصمة",
    UiKey.APPS_LOCK_DESC to "بيتقفل لما تفتح البرنامج، وبعد 5 دقايق في الخلفية.",
    UiKey.APPS_LOCK_FACT_1 to "الرجوع قبل 5 دقايق مش بيسأل.",
    UiKey.APPS_LOCK_FACT_2 to "لو البصمة ما نفعتش: رمز قفل الجوال.",
    UiKey.APPS_LOCK_FACT_3 to "البرنامج بيفضل متغطي ببلور لحد ما تتأكد.",
    UiKey.APPS_LOCK_NA to "الجوال مالوش قفل شاشة ولا بصمة متسجلة. اعمل قفل شاشة من إعدادات الجوال الأول.",
    UiKey.APPS_LOCK_ON_DONE to "القفل اشتغل",
    UiKey.APPS_LOCK_OFF_DONE to "القفل اتوقف",
    UiKey.APPS_LANG_HEAD to "اللغة",
    UiKey.APPS_LANG_AR to "العربية",
    UiKey.APPS_LANG_AR_DESC to "لوحده حسب البلد: السعودية بالفصحى المختصرة، ومصر بالمصري. دلوقتي: {0}.",
    UiKey.APPS_LANG_MSA to "الفصحى المختصرة",
    UiKey.APPS_LANG_EGYPTIAN to "المصري",
    UiKey.APPS_LANG_EN to "English",
    UiKey.APPS_LANG_EN_ALT to "الإنجليزي",
    UiKey.APPS_LANG_EN_DESC to "الشاشة بتتعكس وتبدأ من الشمال.",
    UiKey.APPS_LANG_NEXT_OPEN to "اللغة بتتطبق لما تفتح البرنامج تاني.",
    UiKey.APPS_LANG_NOT_YET to "حفظ اختيار اللغة لسه مش متاح: البرنامج بيبدأ بالعربي دلوقتي.",
    UiKey.APPS_DIR_RTL to "اتجاه الشاشة: من اليمين للشمال.",
    UiKey.APPS_DIR_LTR to "اتجاه الشاشة: من الشمال لليمين.",
    UiKey.APPS_ISL_HEAD to "المحتوى الإسلامي",
    UiKey.APPS_ISL_TITLE to "اظهر المحتوى الإسلامي",
    UiKey.APPS_ISL_SHOWN to "ظاهر",
    UiKey.APPS_ISL_HIDDEN to "مخفي",
    UiKey.APPS_ISL_SHOWN_DONE to "المحتوى الإسلامي ظاهر",
    UiKey.APPS_ISL_HIDDEN_DONE to "المحتوى الإسلامي اتخفى",
    UiKey.APPS_ISL_LIST_ON to "بيظهر:",
    UiKey.APPS_ISL_LIST_OFF to "مخفي دلوقتي:",
    UiKey.APPS_ISL_ZAKAT to "الزكاة في الاستثمار وميعادها وإشعاراتها",
    UiKey.APPS_ISL_CALENDAR to "رمضان والعيدين في التقويم",
    UiKey.APPS_ISL_NOTE to "إخفا بس — مفيش حاجة بتتمسح، ولما ترجّعه بيرجع زي ما كان.",
)

internal val ENGLISH_MORE_SETTINGS_TEXTS: Map<UiKey, String> = mapOf(
    UiKey.NSET_TITLE to "Notification settings",
    UiKey.NSET_INTRO to "Turn off any group on its own.",
    UiKey.NSET_NEW to "New",
    UiKey.NSET_BANK to "Bank messages",
    UiKey.NSET_BANK_DESC to "Only when messages are waiting for your confirmation. What's recorded automatically sends no notification.",
    UiKey.NSET_BANK_OFF_DESC to "Off: waiting messages only show on the notifications page, with no phone notification.",
    UiKey.NSET_DUES to "Dues",
    UiKey.NSET_DUES_DESC to "Installments, subscriptions and debts: before the date, on it, and when it passes",
    UiKey.NSET_BUDGET to "Budget",
    UiKey.NSET_BUDGET_DESC to "When you near or pass the limit, even because of an automatically recorded transaction",
    UiKey.NSET_ASK to "Questions",
    UiKey.NSET_ASK_DESC to "Transfer parties waiting for your decision — unanswered ones stay in review",
    UiKey.NSET_CASH to "Cash question",
    UiKey.NSET_CASH_DESC to "Asks “How much cash do you have?” so your cash balance stays right",
    UiKey.NSET_CASH_NOTE to "Friday morning (suggested). If you count your cash before then, the question waits.",
    UiKey.NSET_CASH_NOT_YET to "The cash question isn't available yet: the app has no alert for it so far.",
    UiKey.NSET_EVERY_WEEK to "Every week",
    UiKey.NSET_EVERY_2WEEKS to "Every two weeks",
    UiKey.NSET_EVERY_MONTH to "Every month",
    UiKey.NSET_INCOME to "Income",
    UiKey.NSET_INCOME_DESC to "If your salary is late",
    UiKey.NSET_OCC to "Occasions",
    UiKey.NSET_OCC_DESC to "Your people's birthdays and occasions",
    UiKey.NSET_ZAKAT to "Zakat",
    UiKey.NSET_ZAKAT_DESC to "10 days before it's due, and on the day",
    UiKey.NSET_BALANCE to "Balance",
    UiKey.NSET_BALANCE_DESC to "If a wallet's balance doesn't match the statement",
    UiKey.NSET_ADVISOR to "Assistant",
    UiKey.NSET_ADVISOR_DESC to "Smart insights from the financial assistant",
    UiKey.NSET_PROFILE to "Your profile",
    UiKey.NSET_PROFILE_DESC to "A gentle reminder to finish your profile questions",
    UiKey.NSET_LATER_TITLE to "Later",
    UiKey.NSET_LATER_BODY to "Security · linked accounts · email — coming later.",
    UiKey.NSET_LOCK_NOTE to "The lock screen shows only the kind of alert: no amounts, names or counts.",
    UiKey.APPS_TITLE to "Lock, language and content",
    UiKey.APPS_LOCK_HEAD to "Lock",
    UiKey.APPS_LOCK_TITLE to "Fingerprint lock",
    UiKey.APPS_LOCK_DESC to "Locks when you open the app, and after 5 minutes in the background.",
    UiKey.APPS_LOCK_FACT_1 to "Coming back within 5 minutes doesn't ask.",
    UiKey.APPS_LOCK_FACT_2 to "If the fingerprint fails: your phone's lock code.",
    UiKey.APPS_LOCK_FACT_3 to "The app stays blurred until you confirm.",
    UiKey.APPS_LOCK_NA to "The phone has no screen lock or registered fingerprint. Turn on a screen lock in the phone's settings first.",
    UiKey.APPS_LOCK_ON_DONE to "Lock turned on",
    UiKey.APPS_LOCK_OFF_DONE to "Lock turned off",
    UiKey.APPS_LANG_HEAD to "Language",
    UiKey.APPS_LANG_AR to "العربية",
    UiKey.APPS_LANG_AR_DESC to "Automatic by country: Saudi Arabia in concise Standard Arabic, Egypt in Egyptian Arabic. Now: {0}.",
    UiKey.APPS_LANG_MSA to "Concise Standard Arabic",
    UiKey.APPS_LANG_EGYPTIAN to "Egyptian Arabic",
    UiKey.APPS_LANG_EN to "English",
    UiKey.APPS_LANG_EN_ALT to "الإنجليزية",
    UiKey.APPS_LANG_EN_DESC to "The screen flips to start from the left.",
    UiKey.APPS_LANG_NEXT_OPEN to "The language applies when you open the app again.",
    UiKey.APPS_LANG_NOT_YET to "Saving the language choice isn't available yet: the app starts in Arabic for now.",
    UiKey.APPS_DIR_RTL to "Screen direction: right to left.",
    UiKey.APPS_DIR_LTR to "Screen direction: left to right.",
    UiKey.APPS_ISL_HEAD to "Islamic content",
    UiKey.APPS_ISL_TITLE to "Show Islamic content",
    UiKey.APPS_ISL_SHOWN to "Shown",
    UiKey.APPS_ISL_HIDDEN to "Hidden",
    UiKey.APPS_ISL_SHOWN_DONE to "Islamic content is shown",
    UiKey.APPS_ISL_HIDDEN_DONE to "Islamic content is hidden",
    UiKey.APPS_ISL_LIST_ON to "Shows:",
    UiKey.APPS_ISL_LIST_OFF to "Hidden now:",
    UiKey.APPS_ISL_ZAKAT to "Zakat in Investment, its date and alerts",
    UiKey.APPS_ISL_CALENDAR to "Ramadan and the two Eids in the calendar",
    UiKey.APPS_ISL_NOTE to "Hiding only — nothing is deleted, and it comes back as it was.",
)
