package app.masroufy.core

/**
 * باقي نصوص الواجهة المشتركة **بالفصحى** («القادم» · الإضافة السريعة · شبكة التقويم · الدخول · نسيت كلمة المرور · شاشة القفل · ملفات الأسعار)
 * — ملف لوحده عشان حد الـ300 سطر. شاشة الدخول فصحى دايمًا قبل ما الحساب يتعرف (§66 — `AccountSession` بيرجّع الفصحى عند الخروج).
 */
internal val MSA_SHELL_AUTH_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.UPCOMING_TITLE to "القادم",
    TextKey.UPCOMING_LIST to "المواعيد القادمة",
    TextKey.UPCOMING_TODAY to "اليوم",
    TextKey.UPCOMING_TOMORROW to "غدًا",
    TextKey.UPCOMING_TWO_DAYS to "بعد يومين",
    TextKey.UPCOMING_FEW_DAYS to "بعد {0} أيام",
    TextKey.UPCOMING_MANY_DAYS to "بعد {0} يومًا",
    TextKey.UPCOMING_HELD to "محجوز",
    TextKey.UPCOMING_OPEN to "غير محجوز",
    TextKey.UPCOMING_NO_AMOUNT to "بلا مبلغ",
    TextKey.UPCOMING_INCOMING to "دخل متوقع",
    TextKey.UPCOMING_LATE to "فات موعده",
    TextKey.UPCOMING_EMPTY to "لا مواعيد قادمة.",
    TextKey.CALENDAR_OPEN to "التقويم",
    TextKey.QUICK_TITLE to "متوقّعة هذا الشهر ولم تُسجَّل بعد",
    TextKey.QUICK_SHEET_BODY to "المبلغ المعتاد جاهز — عدّله إن اختلف هذا الشهر.",
    TextKey.QUICK_USUAL to "عادةً {0}، يوم {1}",
    TextKey.QUICK_FROM to "من أين دفعتها؟",
    TextKey.QUICK_SAVE to "سجّلها",
    TextKey.QUICK_SKIP to "لن أدفعها هذا الشهر",
    TextKey.QUICK_RECORDED to "سُجّل «{0}» {1}",
    TextKey.QUICK_SKIPPED to "حسنًا — لن نسألك عنها مجددًا هذا الشهر.",
    TextKey.CAL_PREV to "الشهر السابق",
    TextKey.CAL_NEXT to "الشهر التالي",
    TextKey.CAL_TODAY to "اليوم",
    TextKey.CAL_NO_DATES to "لا مواعيد",
    TextKey.CAL_LEGEND_SUB to "اشتراكات وفواتير",
    TextKey.CAL_LEGEND_INST to "أقساط",
    TextKey.CAL_LEGEND_ROSCA to "جمعيات",
    TextKey.CAL_LEGEND_DEBT to "ديون",
    TextKey.CAL_LEGEND_EVENT to "أحداث ومناسبات",
    TextKey.CAL_LEGEND_PAY to "الراتب",
    TextKey.CAL_LEGEND_LATE to "فات موعده",
    TextKey.CAL_MORE to "+{0}",
    TextKey.SIGNIN_WELCOME_TITLE to "أهلًا بك في مصروفي",
    TextKey.SIGNIN_WELCOME_SUB to "دقيقة واحدة نجهّز فيها حسابك، والباقي متى شئت.",
    TextKey.SIGNIN_HOW to "كيف تريد الدخول؟",
    TextKey.SIGNIN_HOW_SUB to "يحفظ حسابك بياناتك ويزامنها على كل أجهزتك.",
    TextKey.SIGNIN_GOOGLE to "الدخول بحساب Google",
    TextKey.SIGNIN_WITH_EMAIL to "الدخول بالبريد الإلكتروني",
    TextKey.SIGNIN_TITLE to "الدخول بالبريد الإلكتروني",
    TextKey.SIGNIN_MODES to "نوع الدخول",
    TextKey.SIGNIN_MODE_IN to "تسجيل الدخول",
    TextKey.SIGNIN_MODE_NEW to "حساب جديد",
    TextKey.SIGNIN_EMAIL to "البريد الإلكتروني",
    TextKey.SIGNIN_PASSWORD to "كلمة المرور",
    TextKey.SIGNIN_PASS_HINT to "٦ أحرف على الأقل.",
    TextKey.SIGNIN_SHOW_PASS to "إظهار كلمة المرور",
    TextKey.SIGNIN_HIDE_PASS to "إخفاء كلمة المرور",
    TextKey.SIGNIN_SUBMIT_IN to "دخول",
    TextKey.SIGNIN_SUBMIT_NEW to "إنشاء الحساب",
    TextKey.SIGNIN_BUSY_IN to "جارٍ الدخول…",
    TextKey.SIGNIN_BUSY_NEW to "جارٍ إنشاء الحساب…",
    TextKey.SIGNIN_DONE_IN to "تم الدخول",
    TextKey.SIGNIN_DONE_NEW to "أُنشئ حسابك",
    TextKey.SIGNIN_DONE_LINE to "نكمل تجهيز حسابك من حيث توقفت.",
    TextKey.SIGNIN_OFFLINE_NOTE to "الدخول يحتاج اتصالًا بالإنترنت.",
    // نسخة الاختبار المتصلة بمحاكي فايربيز على الكمبيوتر (`assembleEmulator`) — اختيار Claude عشان ما تتلخبطش مع الحقيقية
    TextKey.SIGNIN_EMULATOR_NOTE to "نسخة اختبار متصلة بمحاكي فايربيز على الكمبيوتر — بيانات وهمية فقط.",
    TextKey.RESET_TRIGGER to "نسيت كلمة المرور؟",
    TextKey.RESET_TITLE to "إعادة تعيين كلمة المرور",
    TextKey.RESET_BODY to "أدخل بريدك، وسنرسل إليه رابطًا لتعيين كلمة مرور جديدة.",
    TextKey.RESET_EMAIL_EMPTY to "أدخل بريدك الإلكتروني",
    TextKey.RESET_SEND to "أرسل رابط إعادة التعيين",
    TextKey.RESET_SENDING to "جارٍ الإرسال…",
    TextKey.RESET_PRIVACY to "حمايةً للحسابات، لا نُظهر إن كان البريد مسجّلًا لدينا أم لا.",
    TextKey.RESET_SENT_TITLE to "راجع بريدك",
    TextKey.RESET_SENT_BODY to "إن كان {0} مسجّلًا لدينا، فسيصله رابط لتعيين كلمة مرور جديدة خلال دقائق.",
    TextKey.RESET_SPAM to "لم يصل؟ افحص الرسائل غير المرغوب فيها، أو أعد الإرسال.",
    TextKey.RESET_RESEND to "أعد الإرسال",
    TextKey.RESET_AGAIN to "أُرسل الرابط مرة أخرى.",
    TextKey.RESET_WAIT_ONE to "يمكنك الإرسال مجددًا بعد ثانية.",
    TextKey.RESET_WAIT_TWO to "يمكنك الإرسال مجددًا بعد ثانيتين.",
    TextKey.RESET_WAIT_FEW to "يمكنك الإرسال مجددًا بعد {0} ثوانٍ.",
    TextKey.RESET_WAIT_MANY to "يمكنك الإرسال مجددًا بعد {0} ثانية.",
    TextKey.RESET_CHANGE to "غيّر البريد",
    TextKey.RESET_FINISH to "العودة لتسجيل الدخول",
    TextKey.RESET_OFFLINE to "إعادة الإرسال تحتاج اتصالًا بالإنترنت.",
    TextKey.LOCK_SCREEN_TITLE to "مصروفي مقفل",
    TextKey.LOCK_SCREEN_BODY to "افتحه ببصمتك أو رمز الجوال.",
    TextKey.LOCK_SCREEN_OPEN to "افتح",
    TextKey.LOCK_RELEASED to "الجوال بلا قفل، فتوقف قفل التطبيق. فعّله من «المزيد ← الإعدادات» بعد ضبط قفل الجوال.",
    TextKey.FEED_OFFLINE to "لا اتصال بالإنترنت — تعذّر تحديث الأسعار.",
    TextKey.FEED_HTTP_FAILED to "تعذّر تنزيل الملف (الرد {0}).",
    TextKey.FEED_UPDATED_AT to "آخر تحديث {0}",
    TextKey.AUTH_GOOGLE_NO_ACCOUNT to "لا يوجد حساب Google على هذا الجوال. أضفه من إعدادات الجوال أو ادخل بالبريد الإلكتروني.",
    TextKey.AUTH_GOOGLE_FAILED to "تعذّر الدخول بحساب Google الآن. أعد المحاولة أو ادخل بالبريد الإلكتروني.",
)
