package app.masroufy.core

/**
 * «الاستيراد» ٤/٥: `ImportReview` + `ImportDuplicateSheet`. النص من النموذج التفاعلي بالحرف (الفصحى من `space = السعودية` والمصري من `مصر`)،
 * واللي مالوش مقابل في النموذج (أثر اختيار متغيّر «غير متاح» · مصادر التصنيف الزيادة) كتابة Claude بنفس النبرة. السبب في كل سطر = جملة منع التكرار
 * نفسها من المنطق (`DEDUPE_*`) — مش هنا. **ممنوع «·» جنب رقم عربي** ⇒ «،».
 */
internal val MSA_IMPORTS_REVIEW_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.IMPORT_REVIEW_TITLE to "مراجعة الكشف",
    TextKey.IMPORT_REVIEW_ERR_TITLE to "توقفنا قبل التسجيل",
    TextKey.IMPORT_REVIEW_ERR_BODY to "أعد المعاينة لمنع التكرار. لم يُسجَّل شيء.",
    TextKey.IMPORT_REVIEW_REDO to "أعد المعاينة",
    TextKey.IMPORT_REVIEW_REDONE to "أُعيدت المعاينة",
    TextKey.IMPORT_REVIEW_EMPTY_TITLE to "استوردت هذا الملف من قبل",
    TextKey.IMPORT_REVIEW_EMPTY_BODY to "في {0}: سُجّلت {1}، ولم يُضف {2}. كل ما فيه مسجل، فلا جديد.",
    TextKey.IMPORT_REVIEW_HERO_META to "{0}، {1}",
    TextKey.IMPORT_REVIEW_IMPACT to "أثر المحدد: {0}",
    TextKey.IMPORT_REVIEW_DONE_TITLE to "سُجّلت {0}",
    TextKey.IMPORT_REVIEW_ON_WALLET to "على المحفظة",
    TextKey.IMPORT_REVIEW_EXPENSE to "المصروف",
    TextKey.IMPORT_REVIEW_INCOME to "الدخل",
    TextKey.IMPORT_REVIEW_IMPACT_NA to "غيّرت الاختيار، وحساب أثر اختيار مختلف لم يُبنَ بعد.",
    TextKey.IMPORT_REVIEW_NEW to "جديد",
    TextKey.IMPORT_REVIEW_DUP to "مكرر",
    TextKey.IMPORT_REVIEW_SIMILAR to "شبيه",
    TextKey.IMPORT_REVIEW_CONFLICT to "تعارض",
    TextKey.IMPORT_REVIEW_INVALID to "غير صالح",
    TextKey.IMPORT_REVIEW_ROW to "الصف {0}",
    TextKey.IMPORT_REVIEW_DATE_ROW to "{0}، {1}",
    TextKey.IMPORT_REVIEW_CAT_SRC to "{0}، {1}",
    TextKey.IMPORT_REVIEW_SRC_CONFIRMED to "تصنيفك المؤكد",
    TextKey.IMPORT_REVIEW_SRC_MERCHANT to "تصنيف المتجر المؤكد",
    TextKey.IMPORT_REVIEW_SRC_RULE to "مقترح من قاعدة",
    TextKey.IMPORT_REVIEW_SRC_BANK to "تصنيف البنك",
    TextKey.IMPORT_REVIEW_SRC_OTHER_COUNTRY to "من المتجر في البلد الآخر",
    TextKey.IMPORT_REVIEW_SRC_NEW to "متجر جديد",
    TextKey.IMPORT_REVIEW_COMPARE to "قارن",
    TextKey.IMPORT_REVIEW_FOOT to "المكرر وغير الصالح لا يُضافان. في التعارض يبقى القديم كما هو حتى تعدّله بنفسك.",
    TextKey.IMPORT_REVIEW_COMMIT to "سجّل {0}",
    TextKey.IMPORT_REVIEW_SAVING to "جارٍ التسجيل…",
    TextKey.IMPORT_REVIEW_NOTE_ATOMIC to "يُسجَّل الكل دفعة واحدة أو لا شيء.",
    TextKey.IMPORT_REVIEW_NOTE_SAVING to "الضغط مرة أخرى لا يكرر شيئًا.",
    TextKey.IMPORT_REVIEW_NOTE_DONE to "يمكنك إرجاع الدفعة كلها من «دفعات الاستيراد».",
    TextKey.IMPORT_REVIEW_SAVED_TOAST to "سُجّلت {0}، ولم يُضف {1}",
    TextKey.IMPORT_DUP_TITLE_SIMILAR to "تشبه عملية موجودة",
    TextKey.IMPORT_DUP_TITLE_CONFLICT to "المرجع نفسه بتفاصيل مختلفة",
    TextKey.IMPORT_DUP_TITLE_DUP to "مسجلة سابقًا",
    TextKey.IMPORT_DUP_NEW_SIDE to "الجديدة من الكشف",
    TextKey.IMPORT_DUP_OLD_SIDE to "الموجودة لديك",
    TextKey.IMPORT_DUP_ROW_IN_FILE to "{0} في الكشف",
    TextKey.IMPORT_DUP_DIFF to "الفرق: {0}",
    TextKey.IMPORT_DUP_DIFF_AMOUNT to "المبلغ",
    TextKey.IMPORT_DUP_DIFF_DATE to "التاريخ",
    TextKey.IMPORT_DUP_CONFLICT_NOTE to "إن كان القديم خطأ فافتحه من العمليات وعدّل مبلغه يدويًا.",
    TextKey.IMPORT_DUP_SKIP to "هي نفسها — تجاهلها",
    TextKey.IMPORT_DUP_ADD to "لا، أضفها",
    TextKey.IMPORT_DUP_KEEP to "أبقِ القديم",
    TextKey.IMPORT_DUP_OK to "حسنًا",
)

internal val EGYPTIAN_IMPORTS_REVIEW_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.IMPORT_REVIEW_TITLE to "مراجعة الكشف",
    TextKey.IMPORT_REVIEW_ERR_TITLE to "وقفنا قبل التسجيل",
    TextKey.IMPORT_REVIEW_ERR_BODY to "اعمل معاينة جديدة علشان نمنع التكرار. مفيش حاجة اتسجلت.",
    TextKey.IMPORT_REVIEW_REDO to "معاينة جديدة",
    TextKey.IMPORT_REVIEW_REDONE to "اتعملت معاينة جديدة",
    TextKey.IMPORT_REVIEW_EMPTY_TITLE to "الملف ده اتستورد قبل كده",
    TextKey.IMPORT_REVIEW_EMPTY_BODY to "يوم {0}: اتسجلت {1}، ومتضافش {2}. كل اللي فيه متسجل، فمفيش حاجة جديدة.",
    TextKey.IMPORT_REVIEW_HERO_META to "{0}، {1}",
    TextKey.IMPORT_REVIEW_IMPACT to "أثر المختار: {0}",
    TextKey.IMPORT_REVIEW_DONE_TITLE to "اتسجلت {0}",
    TextKey.IMPORT_REVIEW_ON_WALLET to "على المحفظة",
    TextKey.IMPORT_REVIEW_EXPENSE to "المصروف",
    TextKey.IMPORT_REVIEW_INCOME to "الدخل",
    TextKey.IMPORT_REVIEW_IMPACT_NA to "غيّرت الاختيار، وحساب أثر اختيار تاني لسه ما اتبناش.",
    TextKey.IMPORT_REVIEW_NEW to "جديد",
    TextKey.IMPORT_REVIEW_DUP to "مكرر",
    TextKey.IMPORT_REVIEW_SIMILAR to "شبيه",
    TextKey.IMPORT_REVIEW_CONFLICT to "تعارض",
    TextKey.IMPORT_REVIEW_INVALID to "غير صالح",
    TextKey.IMPORT_REVIEW_ROW to "سطر {0}",
    TextKey.IMPORT_REVIEW_DATE_ROW to "{0}، {1}",
    TextKey.IMPORT_REVIEW_CAT_SRC to "{0}، {1}",
    TextKey.IMPORT_REVIEW_SRC_CONFIRMED to "تصنيفك المؤكد",
    TextKey.IMPORT_REVIEW_SRC_MERCHANT to "تصنيف المحل المؤكد",
    TextKey.IMPORT_REVIEW_SRC_RULE to "مقترح من قاعدة",
    TextKey.IMPORT_REVIEW_SRC_BANK to "تصنيف البنك",
    TextKey.IMPORT_REVIEW_SRC_OTHER_COUNTRY to "من المحل في البلد التانية",
    TextKey.IMPORT_REVIEW_SRC_NEW to "محل جديد",
    TextKey.IMPORT_REVIEW_COMPARE to "قارن",
    TextKey.IMPORT_REVIEW_FOOT to "المكرر وغير الصالح مش بيتضافوا. التعارض بيفضل القديم فيه زي ما هو لحد ما تعدّله بنفسك.",
    TextKey.IMPORT_REVIEW_COMMIT to "سجّل {0}",
    TextKey.IMPORT_REVIEW_SAVING to "بيتسجل…",
    TextKey.IMPORT_REVIEW_NOTE_ATOMIC to "كله بيتسجل مرة واحدة أو مفيش خالص.",
    TextKey.IMPORT_REVIEW_NOTE_SAVING to "الدوس تاني مش هيكرر حاجة.",
    TextKey.IMPORT_REVIEW_NOTE_DONE to "تقدر ترجّع الدفعة كلها من «دفعات الاستيراد».",
    TextKey.IMPORT_REVIEW_SAVED_TOAST to "اتسجلت {0}، وما اتضافش {1}",
    TextKey.IMPORT_DUP_TITLE_SIMILAR to "شبه عملية موجودة",
    TextKey.IMPORT_DUP_TITLE_CONFLICT to "نفس المرجع بتفاصيل مختلفة",
    TextKey.IMPORT_DUP_TITLE_DUP to "متسجلة قبل كده",
    TextKey.IMPORT_DUP_NEW_SIDE to "الجديدة من الكشف",
    TextKey.IMPORT_DUP_OLD_SIDE to "الموجودة عندك",
    TextKey.IMPORT_DUP_ROW_IN_FILE to "{0} في الكشف",
    TextKey.IMPORT_DUP_DIFF to "الفرق: {0}",
    TextKey.IMPORT_DUP_DIFF_AMOUNT to "المبلغ",
    TextKey.IMPORT_DUP_DIFF_DATE to "التاريخ",
    TextKey.IMPORT_DUP_CONFLICT_NOTE to "لو القديم غلط، افتحه من العمليات وعدّل مبلغه بإيدك.",
    TextKey.IMPORT_DUP_SKIP to "هي نفسها — تجاهلها",
    TextKey.IMPORT_DUP_ADD to "لأ، ضيفها",
    TextKey.IMPORT_DUP_KEEP to "سيب القديم",
    TextKey.IMPORT_DUP_OK to "تمام",
)

internal val ENGLISH_IMPORTS_REVIEW_TEXTS: Map<TextKey, String> = mapOf(
    TextKey.IMPORT_REVIEW_TITLE to "Review statement",
    TextKey.IMPORT_REVIEW_ERR_TITLE to "We stopped before saving",
    TextKey.IMPORT_REVIEW_ERR_BODY to "Preview again to prevent duplicates. Nothing was saved.",
    TextKey.IMPORT_REVIEW_REDO to "Preview again",
    TextKey.IMPORT_REVIEW_REDONE to "Previewed again",
    TextKey.IMPORT_REVIEW_EMPTY_TITLE to "You imported this file before",
    TextKey.IMPORT_REVIEW_EMPTY_BODY to "On {0}: {1} saved, {2} not added. Everything in it is already saved, so there's nothing new.",
    TextKey.IMPORT_REVIEW_HERO_META to "{0}, {1}",
    TextKey.IMPORT_REVIEW_IMPACT to "Effect of selection: {0}",
    TextKey.IMPORT_REVIEW_DONE_TITLE to "Saved {0}",
    TextKey.IMPORT_REVIEW_ON_WALLET to "On the wallet",
    TextKey.IMPORT_REVIEW_EXPENSE to "Spending",
    TextKey.IMPORT_REVIEW_INCOME to "Income",
    TextKey.IMPORT_REVIEW_IMPACT_NA to "You changed the selection; the effect of a different selection isn't built yet.",
    TextKey.IMPORT_REVIEW_NEW to "New",
    TextKey.IMPORT_REVIEW_DUP to "Duplicate",
    TextKey.IMPORT_REVIEW_SIMILAR to "Similar",
    TextKey.IMPORT_REVIEW_CONFLICT to "Conflict",
    TextKey.IMPORT_REVIEW_INVALID to "Invalid",
    TextKey.IMPORT_REVIEW_ROW to "Line {0}",
    TextKey.IMPORT_REVIEW_DATE_ROW to "{0}, {1}",
    TextKey.IMPORT_REVIEW_CAT_SRC to "{0}, {1}",
    TextKey.IMPORT_REVIEW_SRC_CONFIRMED to "Your confirmed category",
    TextKey.IMPORT_REVIEW_SRC_MERCHANT to "Confirmed merchant category",
    TextKey.IMPORT_REVIEW_SRC_RULE to "Suggested by a rule",
    TextKey.IMPORT_REVIEW_SRC_BANK to "Bank's category",
    TextKey.IMPORT_REVIEW_SRC_OTHER_COUNTRY to "From the merchant in the other country",
    TextKey.IMPORT_REVIEW_SRC_NEW to "New merchant",
    TextKey.IMPORT_REVIEW_COMPARE to "Compare",
    TextKey.IMPORT_REVIEW_FOOT to "Duplicates and invalid lines are not added. In a conflict the old one stays as it is until you edit it yourself.",
    TextKey.IMPORT_REVIEW_COMMIT to "Save {0}",
    TextKey.IMPORT_REVIEW_SAVING to "Saving…",
    TextKey.IMPORT_REVIEW_NOTE_ATOMIC to "Everything is saved at once, or nothing.",
    TextKey.IMPORT_REVIEW_NOTE_SAVING to "Tapping again won't duplicate anything.",
    TextKey.IMPORT_REVIEW_NOTE_DONE to "You can undo the whole batch from “Import batches”.",
    TextKey.IMPORT_REVIEW_SAVED_TOAST to "Saved {0}, {1} not added",
    TextKey.IMPORT_DUP_TITLE_SIMILAR to "Looks like an existing transaction",
    TextKey.IMPORT_DUP_TITLE_CONFLICT to "Same reference, different details",
    TextKey.IMPORT_DUP_TITLE_DUP to "Already saved",
    TextKey.IMPORT_DUP_NEW_SIDE to "New from the statement",
    TextKey.IMPORT_DUP_OLD_SIDE to "Already in your records",
    TextKey.IMPORT_DUP_ROW_IN_FILE to "{0} in the statement",
    TextKey.IMPORT_DUP_DIFF to "Difference: {0}",
    TextKey.IMPORT_DUP_DIFF_AMOUNT to "amount",
    TextKey.IMPORT_DUP_DIFF_DATE to "date",
    TextKey.IMPORT_DUP_CONFLICT_NOTE to "If the old one is wrong, open it from Transactions and edit its amount yourself.",
    TextKey.IMPORT_DUP_SKIP to "It's the same — skip it",
    TextKey.IMPORT_DUP_ADD to "No, add it",
    TextKey.IMPORT_DUP_KEEP to "Keep the old one",
    TextKey.IMPORT_DUP_OK to "OK",
)
