package app.masroufy.core

/**
 * صيغ زيادة — الجزء ٢: أسئلة البيانات بالاسم الأساسي والفترة · التنقل بأخطاء إملائية ولهجات · التحية جوه سؤال · كلام عادي. مخترعة.
 */
private val COFFEE = seedCategoryId("مطاعم وقهوة", "قهوة ومشروبات")
private val FOOD = seedCategoryId("مطاعم وقهوة", "مطاعم")
private val GROCERY = seedCategoryId("بقالة وسوبرماركت")
private val P = AssistPeriodKind.CURRENT_FISCAL

internal val EXTRA_CASES_2: List<AssistCase> = listOf(
    AssistCase("صرفت كام على القهوة الشهر اللي فات؟", "data.spend.category", subject = COFFEE, period = AssistPeriodKind.PREVIOUS_FISCAL),
    AssistCase("كم صرفت على البقالة هالشهر", "data.spend.category", subject = GROCERY, period = P),
    AssistCase("كم صرفت على القهوه من اول السنه", "data.spend.category", subject = COFFEE, period = AssistPeriodKind.THIS_YEAR),
    AssistCase("صرفت كام علي القهوه الاسبوع ده", "data.spend.category", subject = COFFEE, period = AssistPeriodKind.THIS_WEEK),
    AssistCase("كم انفقت على المطاعم في اكتوبر", "data.spend.category", subject = FOOD, period = AssistPeriodKind.NAMED_MONTH),
    AssistCase("صرفت كام في اخر ٧ ايام", "data.spend.total", period = AssistPeriodKind.LAST_DAYS),
    AssistCase("كم صرفت في آخر 3 شهور", "data.spend.total", period = AssistPeriodKind.LAST_MONTHS),
    AssistCase("كم صرفت الاسبوع اللي فات", "data.spend.total", period = AssistPeriodKind.LAST_WEEK),
    AssistCase("صرفت كام امبارح؟", "data.spend.total", period = AssistPeriodKind.YESTERDAY),
    AssistCase("صرفت كام النهارده", "data.spend.total", period = AssistPeriodKind.TODAY),
    AssistCase("مصاريفي كام هالشهر", "data.spend.total", period = P),
    AssistCase("وش صرفت هالاسبوع", "data.spend.total", period = AssistPeriodKind.THIS_WEEK),
    AssistCase("صرفت كااام الشهر ده", "data.spend.total", period = P),
    AssistCase("السلام عليكم، صرفت كام الشهر ده؟", "data.spend.total"),
    AssistCase("صباح الخير كم صرفت هالشهر", "data.spend.total"),
    AssistCase("صرفت كام في المرسى الشهر ده", "data.spend.merchant", subject = "m-marsa"),
    AssistCase("كم صرفت عند كافيه المرسى", "data.spend.merchant", subject = "m-marsa"),
    AssistCase("كم دفعت في مقهى المرسى", "data.spend.merchant", subject = "m-marsa"),
    AssistCase("اخر مره في المرسى امتى", "data.last_at_merchant", subject = "m-marsa"),
    AssistCase("ليا كام عند خالد", "data.person_balance", subject = "p-khaled"),
    AssistCase("خالد عليه كام؟", "data.person_balance", subject = "p-khaled"),
    AssistCase("كم لي عند احمد", "data.person_balance", subject = "p-ahmed"),
    AssistCase("عليا كام لفهد", "data.person_balance", subject = "p-fahd"),
    AssistCase("صرفت كام على ساره", "data.spend.person", subject = "p-sara"),
    AssistCase("كم اعطيت خالد هالشهر", "data.spend.person", subject = "p-khaled"),
    AssistCase("فاتورة الكهربا امتى", "data.bills", subject = "r-elec"),
    AssistCase("الايجار بيجي امتى", "data.bills", subject = "r-rent"),
    AssistCase("فاتورة النت بكام عادة", "data.bills", subject = "r-net"),
    AssistCase("وصلت لفين في هدف السفر", "data.goal_progress", subject = "g-travel"),
    AssistCase("كم باقي على السفر", "data.goal_progress", subject = "g-travel"),
    AssistCase("تمويل السيارة فاضل كام", "data.installments", subject = "pl-car"),
    AssistCase("دوري في جمعية الشغل امتى", "data.rosca", subject = "ro-work"),
    AssistCase("صرفت كام على الفرح", "data.event_spend", subject = "e-wedding"),
    AssistCase("العقيقة كلفتني كام", "data.event_spend", subject = "e-aqiqa"),
    AssistCase("مشروع البيت صرف كام", "data.project_spend", subject = "pr-home"),
    AssistCase("الذهب بكام", "data.assets", subject = "a-gold"),
    AssistCase("رصيد الراجحي كام", "data.on_hand", subject = "w-bank"),
    AssistCase("معايا كام كاش", "data.cash_on_hand"),
    AssistCase("كم معي كاش", "data.cash_on_hand"),
    AssistCase("وش باقي من الميزانية", "data.remaining"),
    AssistCase("فاضلي كام", "data.remaining"),
    AssistCase("فاضلي كام لحد المرتب", "data.remaining"),
    AssistCase("ميزانية القهوة فاضل فيها كام", "data.category_budget", subject = COFFEE),
    AssistCase("سقف البقاله وصل لفين", "data.category_budget", subject = GROCERY),
    AssistCase("المرتب امتى", "data.next_salary"),
    AssistCase("الراتب متى ينزل", "data.next_salary"),
    AssistCase("باقي كم يوم على الراتب", "data.next_salary"),
    AssistCase("مرتبي كام", "data.salary_amount"),
    AssistCase("مين عليه فلوس ليا", "data.owed_to_me"),
    AssistCase("ديوني كام", "data.i_owe"),
    AssistCase("مين اتأخر في السداد", "data.debts_overdue"),
    AssistCase("الديون المتاخره", "data.debts_overdue"),
    AssistCase("ايه اللي عليا قبل المرتب", "data.dues_upcoming"),
    AssistCase("كم رسالة مستنية تاكيد", "data.pending_review"),
    AssistCase("زكاتي كام", "data.zakat"),
    AssistCase("امتى الزكاه", "data.zakat"),
    AssistCase("اقدر اصرف كام في اليوم", "data.daily_allowance"),
    AssistCase("هوصل لكام آخر الشهر", "data.forecast"),
    AssistCase("انا ماشي على الخطه؟", "data.budget_status"),
    AssistCase("صرفت اكتر على ايه", "data.spend.biggest"),
    AssistCase("صرفت اكتر من الشهر اللي فات؟", "data.spend.compare"),
    AssistCase("دخلي كام السنه دي", "data.income", period = AssistPeriodKind.THIS_YEAR),
    AssistCase("مين عيد ميلاده قريب", "data.occasions"),
    AssistCase("فاضل كام قسط", "data.installments"),
    // التنقل: أخطاء إملائية · من غير همزة/تاء مربوطة · لهجات · الاسم
    AssistCase("فين الزكاه", "nav.zakat"),
    AssistCase("وين الزكاة", "nav.zakat"),
    AssistCase("الاشعرات", "nav.notifications"),
    AssistCase("افتح الميزانيه", "nav.budgets"),
    AssistCase("اعدادت الاشعارات", "nav.notification_settings"),
    AssistCase("فين الكاش", "nav.cash_details"),
    AssistCase("وريني ديوني", "nav.you_owe"),
    AssistCase("افتح احمد", "nav.person_profile", subject = "p-ahmed"),
    AssistCase("ملف ساره", "nav.person_profile", subject = "p-sara"),
    AssistCase("افتح الراجحي", "nav.wallet_detail", subject = "w-bank"),
    AssistCase("ميزانية الاكل", "nav.category_budget", subject = FOOD),
    AssistCase("صفحة مقهى المرسى", "nav.merchant", subject = "m-marsa"),
    AssistCase("افتح جمعية الشغل", "nav.roscas", subject = "ro-work"),
    AssistCase("افتح الذهب", "nav.asset_detail", subject = "a-gold"),
    AssistCase("ابي اشوف الاشتراكات", "nav.subscriptions"),
    AssistCase("عايز اشوف الجمعيات", "nav.roscas"),
    AssistCase("خذني للتقويم", "nav.calendar"),
    AssistCase("الحاسبه بتاعت التقاعد", "nav.retirement_calculator"),
    AssistCase("حاسبة الميراث", "nav.inheritance_calculator"),
    AssistCase("النسخه الاحتياطيه", "nav.backup"),
    AssistCase("رسايل البنك فين", "nav.bank_sms"),
    AssistCase("open budgets", "nav.budgets"),
    AssistCase("show me my wallets", "nav.wallets"),
    // كلام عادي · تحكم · مش فاهم
    AssistCase("هلا والله", "smalltalk.greeting"),
    AssistCase("مساء الخير", "smalltalk.greeting"),
    AssistCase("شكراااا", "smalltalk.thanks"),
    AssistCase("تسلم ايدك", "smalltalk.thanks"),
    AssistCase("انت بوت؟", "smalltalk.who_are_you"),
    AssistCase("ايش تقدر تسوي", "smalltalk.help"),
    AssistCase("مو فاهم شي", "smalltalk.frustration"),
    AssistCase("اشتري ذهب ولا اسهم", "smalltalk.advice_request"),
    AssistCase("ابدأ محادثه جديده", "control.new_conversation"),
    AssistCase("سجل المحادثات", "control.history"),
    AssistCase("وش تعرف عني", "control.memory"),
    AssistCase("وقف التعلم", "control.learning_switch"),
    AssistCase("ايوه", "action.confirm_pending"),
    AssistCase("اخبار السوق ايه", "fallback.unknown"),
    AssistCase("بيتزا ولا برجر", "fallback.unknown"),
    AssistCase("كوكو واوا", "fallback.unknown"),
)
