package app.masroufy.core

/**
 * أمثلة كتالوج النوايا من التصميم (`assistant-design.json` — اتولّدت بسكربت) بالنية المتوقعة لكل مثال، الجزء 3.
 * الأسامي كلها مخترعة (المستودع عام). اللي اتعدّل عن التصميم مكتوب سببه في `AssistCatalogueTest`.
 */
internal val CATALOGUE_CASES_3: List<AssistCase> = listOf(
    AssistCase("history", "control.history"),
    AssistCase("إيه اللي اتعلمته عني؟", "control.memory"),
    AssistCase("ماذا تعرف عني", "control.memory"),
    AssistCase("وش تعرف عني", "control.memory"),
    AssistCase("what do you know about me", "control.memory"),
    AssistCase("بطّل تتعلم من أسئلتي", "control.learning_switch"),
    AssistCase("أوقف التعلم", "control.learning_switch"),
    AssistCase("ارجع اتعلّم من أسئلتي", "control.learning_switch"),
    AssistCase("stop learning", "control.learning_switch"),
    AssistCase("انسى اللي اتعلمته", "control.forget_all"),
    AssistCase("امسح ما تعلّمته عني", "control.forget_all"),
    AssistCase("forget everything", "control.forget_all"),
    AssistCase("السلام عليكم", "smalltalk.greeting"),
    AssistCase("أهلًا", "smalltalk.greeting"),
    AssistCase("هلا", "smalltalk.greeting"),
    AssistCase("مرحبا", "smalltalk.greeting"),
    AssistCase("صباح الخير", "smalltalk.greeting"),
    AssistCase("إزيك", "smalltalk.greeting"),
    AssistCase("كيفك", "smalltalk.greeting"),
    AssistCase("hi", "smalltalk.greeting"),
    AssistCase("عامل إيه", "smalltalk.how_are_you"),
    AssistCase("كيف حالك", "smalltalk.how_are_you"),
    AssistCase("شخبارك", "smalltalk.how_are_you"),
    AssistCase("how are you", "smalltalk.how_are_you"),
    AssistCase("شكرًا", "smalltalk.thanks"),
    AssistCase("تسلم", "smalltalk.thanks"),
    AssistCase("مشكور", "smalltalk.thanks"),
    AssistCase("يعطيك العافية", "smalltalk.thanks"),
    AssistCase("ميرسي", "smalltalk.thanks"),
    AssistCase("thanks", "smalltalk.thanks"),
    AssistCase("باي", "smalltalk.bye"),
    AssistCase("مع السلامة", "smalltalk.bye"),
    AssistCase("تصبح على خير", "smalltalk.bye"),
    AssistCase("في أمان الله", "smalltalk.bye"),
    AssistCase("bye", "smalltalk.bye"),
    AssistCase("مين انت؟", "smalltalk.who_are_you"),
    AssistCase("من أنت", "smalltalk.who_are_you"),
    AssistCase("انت ذكاء اصطناعي؟", "smalltalk.who_are_you"),
    AssistCase("وش انت", "smalltalk.who_are_you"),
    AssistCase("who are you", "smalltalk.who_are_you"),
    AssistCase("تقدر تعمل إيه؟", "smalltalk.help"),
    AssistCase("ساعدني", "smalltalk.help"),
    AssistCase("ماذا يمكنك أن تفعل", "smalltalk.help"),
    AssistCase("وش تقدر تسوي", "smalltalk.help"),
    AssistCase("help", "smalltalk.help"),
    AssistCase("شاطر", "smalltalk.praise"),
    AssistCase("حلو كده", "smalltalk.praise"),
    AssistCase("ممتاز", "smalltalk.praise"),
    AssistCase("good job", "smalltalk.praise"),
    AssistCase("انت مش فاهم حاجة", "smalltalk.frustration"),
    AssistCase("مو فاهم", "smalltalk.frustration"),
    AssistCase("مفيش فايدة", "smalltalk.frustration"),
    AssistCase("useless", "smalltalk.frustration"),
    AssistCase("أستثمر في إيه؟", "smalltalk.advice_request"),
    AssistCase("أشتري ذهب ولا لأ؟", "smalltalk.advice_request"),
    AssistCase("هل أشتري أسهم", "smalltalk.advice_request"),
    AssistCase("should I buy gold", "smalltalk.advice_request"),
    AssistCase("عايز أعرف أخبار السوق", "fallback.unknown"),
    AssistCase("كوكو", "fallback.unknown"),
)
