package app.masroufy.core

/**
 * أمثلة كتالوج النوايا من التصميم (`assistant-design.json` — اتولّدت بسكربت) بالنية المتوقعة لكل مثال، الجزء 1.
 * الأسامي كلها مخترعة (المستودع عام). اللي اتعدّل عن التصميم مكتوب سببه في `AssistCatalogueTest`.
 */
internal val CATALOGUE_CASES_1: List<AssistCase> = listOf(
    AssistCase("الرئيسية", "nav.home"),
    AssistCase("ارجع للرئيسية", "nav.home"),
    AssistCase("ودّيني الصفحة الرئيسية", "nav.home"),
    AssistCase("أبي الصفحة الرئيسية", "nav.home"),
    AssistCase("go home", "nav.home"),
    AssistCase("فين الكاش؟", "nav.cash_details"),
    AssistCase("افتح صفحة الكاش", "nav.cash_details"),
    AssistCase("وين ألقى الكاش", "nav.cash_details"),
    AssistCase("تفاصيل الكاش", "nav.cash_details"),
    AssistCase("open cash", "nav.cash_details"),
    AssistCase("الإشعارات", "nav.notifications"),
    AssistCase("فين التنبيهات؟", "nav.notifications"),
    AssistCase("افتح الجرس", "nav.notifications"),
    AssistCase("وريني الإشعارات", "nav.notifications"),
    AssistCase("وين التنبيهات", "nav.notifications"),
    AssistCase("notifications", "nav.notifications"),
    AssistCase("إعدادات الإشعارات", "nav.notification_settings"),
    AssistCase("أبي أطفي تنبيهات الميزانية", "nav.notification_settings"),
    AssistCase("فين أقفل الإشعارات", "nav.notification_settings"),
    AssistCase("سؤال الكاش كل أسبوع", "nav.notification_settings"),
    AssistCase("notification settings", "nav.notification_settings"),
    AssistCase("التقويم", "nav.calendar"),
    AssistCase("افتح الكالندر", "nav.calendar"),
    AssistCase("مواعيدي", "nav.calendar"),
    AssistCase("الأجندة", "nav.calendar"),
    AssistCase("calendar", "nav.calendar"),
    AssistCase("كمّل ملفي", "nav.profile_question"),
    AssistCase("ملفي ناقص إيه؟", "nav.profile_question"),
    AssistCase("نسبة اكتمال ملفي", "nav.profile_question"),
    AssistCase("أبي أكمل ملفي", "nav.profile_question"),
    AssistCase("complete my profile", "nav.profile_question"),
    AssistCase("العمليات", "nav.operations"),
    AssistCase("افتح العمليات", "nav.operations"),
    AssistCase("وريني الحركات", "nav.operations"),
    AssistCase("سجل مصاريفي", "nav.operations"),
    AssistCase("فين عملياتي؟", "nav.operations"),
    AssistCase("transactions", "nav.operations"),
    AssistCase("فلتر العمليات", "nav.operation_filters"),
    AssistCase("صفّي العمليات بالمبلغ", "nav.operation_filters"),
    AssistCase("أبحث عن عملية", "nav.operation_filters"),
    AssistCase("فلترة الحركات", "nav.operation_filters"),
    AssistCase("filter transactions", "nav.operation_filters"),
    AssistCase("المراجعة", "nav.review_queue"),
    AssistCase("افتح العمليات اللي محتاجة تأكيد", "nav.review_queue"),
    AssistCase("وين اللي يبي تأكيد", "nav.review_queue"),
    AssistCase("أكّد العمليات", "nav.review_queue"),
    AssistCase("review queue", "nav.review_queue"),
    AssistCase("ضيف عملية", "nav.add_operation"),
    AssistCase("أضف عملية جديدة", "nav.add_operation"),
    AssistCase("أبي أسجّل مصروف", "nav.add_operation"),
    AssistCase("سجّل دخل", "nav.add_operation"),
    AssistCase("add a transaction", "nav.add_operation"),
    AssistCase("الميزانيات", "nav.budgets"),
    AssistCase("افتح الميزانية", "nav.budgets"),
    AssistCase("فين السقف؟", "nav.budgets"),
    AssistCase("حدود الصرف", "nav.budgets"),
    AssistCase("البادجت", "nav.budgets"),
    AssistCase("budgets", "nav.budgets"),
    AssistCase("ميزانية الأكل", "nav.category_budget"),
    AssistCase("افتح سقف البقالة", "nav.category_budget"),
    AssistCase("فين سقف القهوة", "nav.category_budget"),
    AssistCase("budget for groceries", "nav.category_budget"),
    AssistCase("المستحقات", "nav.dues"),
    AssistCase("الالتزامات", "nav.dues"),
    AssistCase("افتح المستحقات", "nav.dues"),
    AssistCase("وين المستحقات", "nav.dues"),
    AssistCase("dues", "nav.dues"),
    AssistCase("الديون", "nav.debts"),
    AssistCase("فين الديون؟", "nav.debts"),
    AssistCase("السلف", "nav.debts"),
    AssistCase("صفحة الديون", "nav.debts"),
    AssistCase("debts", "nav.debts"),
    AssistCase("افتح صفحة لك", "nav.owed_to_you"),
    AssistCase("اللي ليّا عند الناس فين", "nav.owed_to_you"),
    AssistCase("وريني المطلوب لي", "nav.owed_to_you"),
    AssistCase("open owed to me", "nav.owed_to_you"),
    AssistCase("افتح صفحة عليك", "nav.you_owe"),
    AssistCase("فين اللي عليّا للناس", "nav.you_owe"),
    AssistCase("وريني ديوني", "nav.you_owe"),
    AssistCase("open what I owe", "nav.you_owe"),
    AssistCase("الجمعيات", "nav.roscas"),
    AssistCase("افتح الجمعية", "nav.roscas"),
    AssistCase("جمعيتي", "nav.roscas"),
    AssistCase("صفحة الجمعيات", "nav.roscas"),
    AssistCase("roscas", "nav.roscas"),
    AssistCase("الأقساط", "nav.installments"),
    AssistCase("التقسيط", "nav.installments"),
    AssistCase("التمويل", "nav.installments"),
    AssistCase("أقساطي", "nav.installments"),
    AssistCase("installments", "nav.installments"),
    AssistCase("الاشتراكات", "nav.subscriptions"),
    AssistCase("الفواتير", "nav.subscriptions"),
    AssistCase("اشتراكاتي", "nav.subscriptions"),
    AssistCase("فواتير البيت", "nav.subscriptions"),
    AssistCase("subscriptions", "nav.subscriptions"),
    AssistCase("التحويلات", "nav.transfers"),
    AssistCase("الحوالات", "nav.transfers"),
    AssistCase("زون التحويلات", "nav.transfers"),
    AssistCase("فين اللي حوّلوا لي", "nav.transfers"),
    AssistCase("transfers", "nav.transfers"),
    AssistCase("التحويل بين البلدين", "nav.space_transfer"),
    AssistCase("حوّلت فلوس لمصر فين أسجّلها", "nav.space_transfer"),
    AssistCase("تحويل لنفسي من السعودية لمصر", "nav.space_transfer"),
    AssistCase("transfer between my countries", "nav.space_transfer"),
    AssistCase("المشاريع", "nav.projects"),
    AssistCase("افتح المشاريع", "nav.projects"),
    AssistCase("مشروع البيت", "nav.projects"),
    AssistCase("projects", "nav.projects"),
    AssistCase("صفحة مقهى المرسى", "nav.merchant"),
    AssistCase("افتح المرسى", "nav.merchant"),
    AssistCase("تاجر المرسى", "nav.merchant"),
    AssistCase("merchant page", "nav.merchant"),
    AssistCase("رسائل البنك", "nav.bank_sms"),
    AssistCase("الرسايل", "nav.bank_sms"),
    AssistCase("مسجات البنك", "nav.bank_sms"),
    AssistCase("الرسايل اللي مستنية", "nav.bank_sms"),
    AssistCase("bank messages", "nav.bank_sms"),
    AssistCase("إعدادات رسائل البنك", "nav.bank_sms_settings"),
    AssistCase("وقّف قراءة الرسايل", "nav.bank_sms_settings"),
    AssistCase("مرسلين البنك", "nav.bank_sms_settings"),
    AssistCase("sms settings", "nav.bank_sms_settings"),
    AssistCase("كشف الحساب", "nav.statement_import"),
    AssistCase("ارفع كشف", "nav.statement_import"),
    AssistCase("استيراد كشف", "nav.statement_import"),
    AssistCase("أبي أستورد كشف البنك", "nav.statement_import"),
    AssistCase("import a statement", "nav.statement_import"),
    AssistCase("دفعات الاستيراد", "nav.import_batches"),
    AssistCase("الاستيرادات اللي فاتت", "nav.import_batches"),
    AssistCase("تراجع عن استيراد", "nav.import_batches"),
    AssistCase("import history", "nav.import_batches"),
    AssistCase("الأشخاص", "nav.people"),
    AssistCase("الناس", "nav.people"),
    AssistCase("صحابي", "nav.people"),
    AssistCase("معارفي", "nav.people"),
    AssistCase("people", "nav.people"),
    AssistCase("افتح أحمد", "nav.person_profile"),
    AssistCase("ملف سارة", "nav.person_profile"),
    AssistCase("صفحة خالد", "nav.person_profile"),
    AssistCase("وريني أحمد", "nav.person_profile"),
    AssistCase("Ahmed's profile", "nav.person_profile"),
    AssistCase("ضيف شخص", "nav.add_person"),
    AssistCase("شخص جديد", "nav.add_person"),
    AssistCase("أضف صديق", "nav.add_person"),
    AssistCase("add a person", "nav.add_person"),
    AssistCase("الأحداث", "nav.events"),
    AssistCase("المناسبات", "nav.events"),
    AssistCase("الفرح", "nav.events"),
    AssistCase("العزاء", "nav.events"),
    AssistCase("events", "nav.events"),
    AssistCase("تجهيزات الفرح", "nav.event_prep"),
    AssistCase("قائمة التجهيز", "nav.event_prep"),
    AssistCase("تجهيزات الحدث الجاي", "nav.event_prep"),
    AssistCase("event prep", "nav.event_prep"),
    AssistCase("النقوط", "nav.nuqoot"),
    AssistCase("سجّل نقوط", "nav.nuqoot"),
    AssistCase("نقطة الفرح", "nav.nuqoot"),
    AssistCase("nuqoot", "nav.nuqoot"),
    AssistCase("الاستثمار", "nav.investment"),
    AssistCase("أصولي", "nav.investment"),
    AssistCase("الذهب", "nav.investment"),
    AssistCase("الأسهم", "nav.investment"),
    AssistCase("investment", "nav.investment"),
    AssistCase("افتح الذهب", "nav.asset_detail"),
    AssistCase("تفاصيل السهم", "nav.asset_detail"),
    AssistCase("صفحة الفضة", "nav.asset_detail"),
    AssistCase("asset details", "nav.asset_detail"),
    AssistCase("الزكاة", "nav.zakat"),
    AssistCase("فين الزكاه؟", "nav.zakat"),
    AssistCase("وين الزكاة", "nav.zakat"),
    AssistCase("الحول والنصاب", "nav.zakat"),
    AssistCase("zakat", "nav.zakat"),
    AssistCase("ادفع الزكاة", "nav.zakat_pay"),
    AssistCase("سجّل دفع الزكاة", "nav.zakat_pay"),
    AssistCase("دفعت زكاتي", "nav.zakat_pay"),
    AssistCase("pay zakat", "nav.zakat_pay"),
    AssistCase("حاسبة الادخار", "nav.savings_calculator"),
    AssistCase("أحوّش كام في الشهر عشان أوصل؟", "nav.savings_calculator"),
    AssistCase("كم أدخر عشان أوصل", "nav.savings_calculator"),
    AssistCase("savings calculator", "nav.savings_calculator"),
    AssistCase("حاسبة التقاعد", "nav.retirement_calculator"),
    AssistCase("المعاش", "nav.retirement_calculator"),
    AssistCase("التأمينات", "nav.retirement_calculator"),
    AssistCase("التقاعد", "nav.retirement_calculator"),
    AssistCase("retirement", "nav.retirement_calculator"),
    AssistCase("حاسبة الورث", "nav.inheritance_calculator"),
    AssistCase("الميراث", "nav.inheritance_calculator"),
    AssistCase("المواريث", "nav.inheritance_calculator"),
    AssistCase("التركة", "nav.inheritance_calculator"),
    AssistCase("inheritance", "nav.inheritance_calculator"),
    AssistCase("حسبات الورث المحفوظة", "nav.inheritance_saved"),
    AssistCase("الحسبات اللي حفظتها", "nav.inheritance_saved"),
    AssistCase("saved inheritance", "nav.inheritance_saved"),
    AssistCase("التحليلات", "nav.advisor"),
    AssistCase("التحليلات الذكية", "nav.advisor"),
    AssistCase("النصائح", "nav.advisor"),
    AssistCase("المستشار", "nav.advisor"),
    AssistCase("insights", "nav.advisor"),
    AssistCase("الأهداف", "nav.savings_goals"),
    AssistCase("خطط الادخار", "nav.savings_goals"),
    AssistCase("الحصالة", "nav.savings_goals"),
    AssistCase("التحويش", "nav.savings_goals"),
    AssistCase("goals", "nav.savings_goals"),
    AssistCase("هتوصل لكام", "nav.savings_growth"),
    AssistCase("لو حوّشت هوصل لكام", "nav.savings_growth"),
    AssistCase("مقارنة الادخار", "nav.savings_growth"),
    AssistCase("savings growth", "nav.savings_growth"),
    AssistCase("المزيد", "nav.more"),
    AssistCase("الترس", "nav.more"),
    AssistCase("القائمة", "nav.more"),
    AssistCase("more", "nav.more"),
    AssistCase("ملفي", "nav.account"),
    AssistCase("بروفايلي", "nav.account"),
    AssistCase("بياناتي الشخصية", "nav.account"),
    AssistCase("حسابي", "nav.account"),
    AssistCase("profile", "nav.account"),
    AssistCase("مصادر الدخل", "nav.income_sources"),
    AssistCase("فين دخلي", "nav.income_sources"),
    AssistCase("شغلي", "nav.income_sources"),
    AssistCase("وظيفتي", "nav.income_sources"),
    AssistCase("income sources", "nav.income_sources"),
    AssistCase("غيّرت شغلي", "nav.job_change"),
    AssistCase("شغل جديد", "nav.job_change"),
    AssistCase("استقلت", "nav.job_change"),
    AssistCase("تركت الدوام", "nav.job_change"),
    AssistCase("I changed jobs", "nav.job_change"),
    AssistCase("البلاد", "nav.spaces"),
    AssistCase("الدول", "nav.spaces"),
    AssistCase("أضف بلد", "nav.spaces"),
    AssistCase("حساب مصر", "nav.spaces"),
    AssistCase("countries", "nav.spaces"),
)
