package app.masroufy.core

/**
 * أمثلة كتالوج النوايا من التصميم (`assistant-design.json` — اتولّدت بسكربت) بالنية المتوقعة لكل مثال، الجزء 2.
 * الأسامي كلها مخترعة (المستودع عام). اللي اتعدّل عن التصميم مكتوب سببه في `AssistCatalogueTest`.
 */
internal val CATALOGUE_CASES_2: List<AssistCase> = listOf(
    AssistCase("حوّل لمصر", "nav.space_switch"),
    AssistCase("بدّل البلد", "nav.space_switch"),
    AssistCase("روح للسعودية", "nav.space_switch"),
    AssistCase("switch to Egypt", "nav.space_switch"),
    AssistCase("المحافظ", "nav.wallets"),
    AssistCase("محافظي", "nav.wallets"),
    AssistCase("حساباتي البنكية", "nav.wallets"),
    AssistCase("البنوك", "nav.wallets"),
    AssistCase("wallets", "nav.wallets"),
    AssistCase("افتح الراجحي", "nav.wallet_detail"),
    AssistCase("محفظة الكاش", "nav.wallet_detail"),
    AssistCase("تفاصيل حساب البنك", "nav.wallet_detail"),
    AssistCase("wallet details", "nav.wallet_detail"),
    AssistCase("التصنيفات", "nav.categories"),
    AssistCase("الفئات", "nav.categories"),
    AssistCase("عدّل التصنيفات", "nav.categories"),
    AssistCase("categories", "nav.categories"),
    AssistCase("القواعد", "nav.rules"),
    AssistCase("التجار", "nav.rules"),
    AssistCase("قواعد التصنيف", "nav.rules"),
    AssistCase("المحلات", "nav.rules"),
    AssistCase("rules", "nav.rules"),
    AssistCase("النسخة الاحتياطية", "nav.backup"),
    AssistCase("باك أب", "nav.backup"),
    AssistCase("صدّر بياناتي", "nav.backup"),
    AssistCase("تصدير إكسل", "nav.backup"),
    AssistCase("backup", "nav.backup"),
    AssistCase("القفل", "nav.lock"),
    AssistCase("البصمة", "nav.lock"),
    AssistCase("فين أغيّر القفل؟", "nav.lock"),
    AssistCase("قفل التطبيق", "nav.lock"),
    AssistCase("lock", "nav.lock"),
    AssistCase("اللغة", "nav.language"),
    AssistCase("خليه إنجليزي", "nav.language"),
    AssistCase("غيّر اللغة", "nav.language"),
    AssistCase("language", "nav.language"),
    AssistCase("المحتوى الإسلامي", "nav.islamic_content"),
    AssistCase("أخفِ الزكاة", "nav.islamic_content"),
    AssistCase("أظهر الزكاة", "nav.islamic_content"),
    AssistCase("islamic content", "nav.islamic_content"),
    AssistCase("صرفت كام الشهر ده؟", "data.spend.total"),
    AssistCase("كم صرفت هذا الشهر؟", "data.spend.total"),
    AssistCase("كم صرفت هالشهر", "data.spend.total"),
    AssistCase("مصروفي كام لحد دلوقتي", "data.spend.total"),
    AssistCase("صرفت كام الشهر اللي فات؟", "data.spend.total"),
    AssistCase("how much did I spend this month", "data.spend.total"),
    AssistCase("صرفت كام على القهوة الشهر ده؟", "data.spend.category"),
    AssistCase("كم أنفقت على المطاعم هذا الشهر؟", "data.spend.category"),
    AssistCase("كم صرفت على البقالة هالشهر", "data.spend.category"),
    AssistCase("القهوة كلفتني كام من أول السنة", "data.spend.category"),
    AssistCase("الأكل برّه كام الشهر اللي فات", "data.spend.category"),
    AssistCase("how much on coffee this week", "data.spend.category"),
    AssistCase("صرفت كام في مقهى المرسى؟", "data.spend.merchant"),
    AssistCase("كم صرفت عند المرسى هذا الشهر", "data.spend.merchant"),
    AssistCase("كم دفعت للمرسى من أول السنة", "data.spend.merchant"),
    AssistCase("المرسى أخد مني كام الشهر ده", "data.spend.merchant"),
    AssistCase("how much at Al Marsa", "data.spend.merchant"),
    AssistCase("صرفت كام على أحمد؟", "data.spend.person"),
    AssistCase("كم أعطيت سارة هذا الشهر", "data.spend.person"),
    AssistCase("كم هدايا لخالد السنة دي", "data.spend.person"),
    AssistCase("how much did I give Ahmed", "data.spend.person"),
    AssistCase("صرفت أكتر على إيه الشهر ده؟", "data.spend.biggest"),
    AssistCase("وش أكثر شيء صرفت عليه", "data.spend.biggest"),
    AssistCase("ما أكبر تصنيف صرفت عليه", "data.spend.biggest"),
    AssistCase("where did most of my money go", "data.spend.biggest"),
    AssistCase("صرفت أكتر من الشهر اللي فات؟", "data.spend.compare"),
    AssistCase("هل صرفي أعلى من الشهر الماضي", "data.spend.compare"),
    AssistCase("قارن صرفي بالشهر اللي فات", "data.spend.compare"),
    AssistCase("am I spending more than last month", "data.spend.compare"),
    AssistCase("دخلي كام الشهر ده؟", "data.income"),
    AssistCase("كم دخلي هذا الشهر", "data.income"),
    AssistCase("دخلي الحقيقي السنة دي كام", "data.income"),
    AssistCase("حركة الفلوس السنة دي", "data.income"),
    AssistCase("how much did I earn this year", "data.income"),
    AssistCase("فاضلي كام؟", "data.remaining"),
    AssistCase("كم بقي لي هذا الشهر", "data.remaining"),
    AssistCase("وش باقي من الميزانية", "data.remaining"),
    AssistCase("فاضل كام من ميزانية الشهر؟", "data.remaining"),
    AssistCase("how much do I have left", "data.remaining"),
    AssistCase("أقدر أصرف كام في اليوم؟", "data.daily_allowance"),
    AssistCase("كم أصرف يوميًا", "data.daily_allowance"),
    AssistCase("المتاح لي في اليوم", "data.daily_allowance"),
    AssistCase("daily allowance", "data.daily_allowance"),
    AssistCase("هوصل لكام آخر الشهر؟", "data.forecast"),
    AssistCase("كم سأصرف بنهاية الشهر", "data.forecast"),
    AssistCase("توقّع صرفي", "data.forecast"),
    AssistCase("forecast this month", "data.forecast"),
    AssistCase("أنا ماشي على الخطة؟", "data.budget_status"),
    AssistCase("هل أنا على الخطة؟", "data.budget_status"),
    AssistCase("الميزانية عاملة إيه", "data.budget_status"),
    AssistCase("وش وضع ميزانيتي", "data.budget_status"),
    AssistCase("am I on budget", "data.budget_status"),
    AssistCase("ميزانية الأكل فاضل فيها كام؟", "data.category_budget"),
    AssistCase("كم بقي في سقف البقالة", "data.category_budget"),
    AssistCase("سقف القهوة وصل لفين", "data.category_budget"),
    AssistCase("grocery budget left", "data.category_budget"),
    AssistCase("معايا كام كاش؟", "data.cash_on_hand"),
    AssistCase("كم معي كاش", "data.cash_on_hand"),
    AssistCase("صرفت كام كاش الشهر ده", "data.cash_on_hand"),
    AssistCase("كم الكاش اللي معي", "data.cash_on_hand"),
    AssistCase("how much cash do I have", "data.cash_on_hand"),
    AssistCase("معايا كام دلوقتي؟", "data.on_hand"),
    AssistCase("كم رصيدي", "data.on_hand"),
    AssistCase("كم معي الآن في كل الحسابات", "data.on_hand"),
    AssistCase("رصيد الراجحي كام", "data.on_hand"),
    AssistCase("what's my balance", "data.on_hand"),
    AssistCase("مين عليه فلوس ليّا؟", "data.owed_to_me"),
    AssistCase("من يدين لي", "data.owed_to_me"),
    AssistCase("مين مطلوب لي فلوس", "data.owed_to_me"),
    AssistCase("فلوسي عند الناس كام", "data.owed_to_me"),
    AssistCase("who owes me", "data.owed_to_me"),
    AssistCase("عليّا فلوس لمين؟", "data.i_owe"),
    AssistCase("لمن عليّ فلوس", "data.i_owe"),
    AssistCase("ديوني كام", "data.i_owe"),
    AssistCase("وش علي للناس", "data.i_owe"),
    AssistCase("who do I owe", "data.i_owe"),
    AssistCase("ليّا كام عند خالد؟", "data.person_balance"),
    AssistCase("كم لي عند خالد", "data.person_balance"),
    AssistCase("خالد عليه كام", "data.person_balance"),
    AssistCase("عليّا كام لأحمد", "data.person_balance"),
    AssistCase("how much does Khaled owe me", "data.person_balance"),
    AssistCase("مين اتأخر في السداد؟", "data.debts_overdue"),
    AssistCase("من تأخّر في السداد", "data.debts_overdue"),
    AssistCase("مين فات ميعاده", "data.debts_overdue"),
    AssistCase("الديون المتأخرة", "data.debts_overdue"),
    AssistCase("overdue debts", "data.debts_overdue"),
    AssistCase("إمتى الراتب؟", "data.next_salary"),
    AssistCase("متى ينزل الراتب", "data.next_salary"),
    AssistCase("المرتب بينزل امتى", "data.next_salary"),
    AssistCase("باقي كم يوم على الراتب", "data.next_salary"),
    AssistCase("when is payday", "data.next_salary"),
    AssistCase("راتبي كام؟", "data.salary_amount"),
    AssistCase("كم راتبي", "data.salary_amount"),
    AssistCase("المرتب المتوقع كام", "data.salary_amount"),
    AssistCase("what's my salary", "data.salary_amount"),
    AssistCase("آخر مرة في المرسى؟", "data.last_at_merchant"),
    AssistCase("آخر عملية عند مقهى المرسى", "data.last_at_merchant"),
    AssistCase("متى آخر مرة دفعت في المرسى", "data.last_at_merchant"),
    AssistCase("last time at Al Marsa", "data.last_at_merchant"),
    AssistCase("وصلت لفين في هدف السفر؟", "data.goal_progress"),
    AssistCase("كم بقي لهدف السفر", "data.goal_progress"),
    AssistCase("هل أنا ماشي في خطة الادخار", "data.goal_progress"),
    AssistCase("خطتي اللي عليها النجمة وصلت كام", "data.goal_progress"),
    AssistCase("goal progress", "data.goal_progress"),
    AssistCase("زكاتي كام؟", "data.zakat"),
    AssistCase("كم الزكاة عليّ هذا العام", "data.zakat"),
    AssistCase("إمتى الزكاة؟", "data.zakat"),
    AssistCase("موعد الحول", "data.zakat"),
    AssistCase("how much zakat do I owe", "data.zakat"),
    AssistCase("إيه اللي عليّا قبل المرتب؟", "data.dues_upcoming"),
    AssistCase("ما المستحق عليّ هذا الأسبوع", "data.dues_upcoming"),
    AssistCase("وش عليّ من مواعيد", "data.dues_upcoming"),
    AssistCase("أقساطي الجاية", "data.dues_upcoming"),
    AssistCase("what's due before payday", "data.dues_upcoming"),
    AssistCase("الكهربا بتيجي كام عادة؟", "data.bills"),
    AssistCase("متى فاتورة الكهرباء", "data.bills"),
    AssistCase("اشتراكاتي كام في الشهر", "data.bills"),
    AssistCase("فاتورة النت إمتى", "data.bills"),
    AssistCase("when is the electricity bill", "data.bills"),
    AssistCase("كام عملية محتاجة تأكيد؟", "data.pending_review"),
    AssistCase("فيه رسايل مستنية؟", "data.pending_review"),
    AssistCase("كم رسالة بانتظار تأكيدي", "data.pending_review"),
    AssistCase("anything waiting for me", "data.pending_review"),
    AssistCase("أصولي بكام؟", "data.assets"),
    AssistCase("كم قيمة ذهبي", "data.assets"),
    AssistCase("الأسهم عاملة إيه", "data.assets"),
    AssistCase("portfolio value", "data.assets"),
    AssistCase("صرفت كام على الفرح؟", "data.event_spend"),
    AssistCase("كم كلّفت العقيقة", "data.event_spend"),
    AssistCase("مصروف حدث الزواج", "data.event_spend"),
    AssistCase("event cost", "data.event_spend"),
    AssistCase("مشروع البيت صرف كام؟", "data.project_spend"),
    AssistCase("كم صرفت على مشروع التشطيب", "data.project_spend"),
    AssistCase("project spend", "data.project_spend"),
    AssistCase("دوري في الجمعية إمتى؟", "data.rosca"),
    AssistCase("متى أقبض الجمعية", "data.rosca"),
    AssistCase("فاضل كام قسط في الجمعية", "data.rosca"),
    AssistCase("rosca turn", "data.rosca"),
    AssistCase("فاضل كام قسط؟", "data.installments"),
    AssistCase("كم باقي على التمويل", "data.installments"),
    AssistCase("القسط الجاي إمتى", "data.installments"),
    AssistCase("installments left", "data.installments"),
    AssistCase("مين عيد ميلاده قريب؟", "data.occasions"),
    AssistCase("المناسبات الجاية", "data.occasions"),
    AssistCase("وش المناسبات القادمة", "data.occasions"),
    AssistCase("upcoming birthdays", "data.occasions"),
    AssistCase("قهوة ١٥", "action.quick_add"),
    AssistCase("دفعت ٤٢ ريال بنزين", "action.quick_add"),
    AssistCase("صرفت 200 جنيه بقالة كاش", "action.quick_add"),
    AssistCase("سجّل غدا ٣٥ امبارح", "action.quick_add"),
    AssistCase("أبي أسجل عشاء ب80 من الراجحي", "action.quick_add"),
    AssistCase("حط ٥٠ مواصلات", "action.quick_add"),
    AssistCase("coffee 15", "action.quick_add"),
    AssistCase("لا خليها ٢٠", "action.edit_pending", pending = true),
    AssistCase("كاش", "action.edit_pending", pending = true),
    AssistCase("من البنك", "action.edit_pending", pending = true),
    AssistCase("خليها امبارح", "action.edit_pending", pending = true),
    AssistCase("غيّر التصنيف لبقالة", "action.edit_pending", pending = true),
    AssistCase("make it 20", "action.edit_pending", pending = true),
    AssistCase("أيوه", "action.confirm_pending", pending = true),
    AssistCase("تمام سجّلها", "action.confirm_pending", pending = true),
    AssistCase("نعم", "action.confirm_pending", pending = true),
    AssistCase("أكيد", "action.confirm_pending", pending = true),
    AssistCase("احفظ", "action.confirm_pending", pending = true),
    AssistCase("yes", "action.confirm_pending", pending = true),
    AssistCase("لا", "action.cancel_pending", pending = true),
    AssistCase("لأ الغيها", "action.cancel_pending", pending = true),
    AssistCase("ما أبي", "action.cancel_pending", pending = true),
    AssistCase("بلاش", "action.cancel_pending", pending = true),
    AssistCase("cancel", "action.cancel_pending", pending = true),
    AssistCase("قسّم فاتورة العشا ٣٦٠ مع أحمد وسارة", "action.split"),
    AssistCase("قسّم 300 بيني وبين خالد", "action.split"),
    AssistCase("نقسم الحساب ١٢٠ على ٣", "action.split"),
    AssistCase("قسّم آخر عملية مع أحمد", "action.split"),
    AssistCase("split 360 with Ahmed and Sara", "action.split"),
    AssistCase("خلّي الكاش هي الأساسية", "action.set_main_wallet"),
    AssistCase("بصرف عادة من الراجحي", "action.set_main_wallet"),
    AssistCase("اجعل البنك محفظتي الأساسية", "action.set_main_wallet"),
    AssistCase("make cash my main wallet", "action.set_main_wallet"),
    AssistCase("سجّل فاتورة الكهرباء", "action.record_due_bill"),
    AssistCase("سجّل الإيجار", "action.record_due_bill"),
    AssistCase("دفعت الإيجار", "action.record_due_bill"),
    AssistCase("record the electricity bill", "action.record_due_bill"),
    AssistCase("محادثة جديدة", "control.new_conversation"),
    AssistCase("ابدأ من جديد", "control.new_conversation"),
    AssistCase("نبدأ من الأول", "control.new_conversation"),
    AssistCase("new chat", "control.new_conversation"),
    AssistCase("المحادثات القديمة", "control.history"),
    AssistCase("سجل المحادثات", "control.history"),
    AssistCase("وريني كلامنا اللي فات", "control.history"),
)
